### ISSUE TITLE
Discord modmail bot request

### ISSUE THREAD

**Issue by ririko5834** [parkervcp/eggs#1002]
Service: (Ex. minecraft/factorio/etc) Discord Modmail bot

Does this expand an already existing service: N

Link to game: https://github.com/kyb3r/modmail

Links for server downloads: https://github.com/kyb3r/modmail

Links for install steps/docs: https://github.com/kyb3r/modmail/blob/master/README.md#locally

I think that egg for Discord modmail bot in python from kyb3r would be helpful for many users.

**Comment by Fundryi** [comment]
I would also be really interested in this one!

**Comment by parkervcp** [comment]
I suspect this could be run with the python bot egg without needing anything custom

**Comment by ririko5834** [comment]
Please make egg for this. It will be easier to setup (using pterodactyl variables)
