### ISSUE TITLE
Request: Valheim Plus

### ISSUE THREAD

**Issue by MatusBoa** [parkervcp/eggs#1003]
Service: Valheim Plus

Does this expand an already existing service: Yes, expands Valheim by using mod called Valheim Plus

Link to game: https://github.com/valheimPlus/ValheimPlus

Links for server downloads: https://github.com/nxPublic/ValheimPlus/releases/latest/

Links for install steps/docs: https://github.com/valheimPlus/ValheimPlus#server-unix

**Comment by Software-Noob** [comment]
There is already PR open to add this egg

**Comment by MatusBoa** [comment]
> There is already PR open to add this egg

You r right, sorry for that. Forgot to check PRs.

Pasting reference in case somebody tries to search in issues for Valheim Plus.

PR: https://github.com/parkervcp/eggs/pull/1001
