### ISSUE TITLE
I am being stolen.

### ISSUE THREAD

**Issue by CastBlacKing** [parkervcp/eggs#1011]
Hello, I am making this ISSUE to explain a few things about my Pull Request and about me being ripped off.

**Eight days ago** I started to work on an EGG for Valheim (uMod), I had never worked with EGGs or Docker and was learning as I did, I made a lot of progress and lost a lot of nights, finally, **a while after I put my project on GitHub I received some Forks, one of these Forks was from a user named Software-Noob**, I ignored it.
**Two days ago** a user with this same name made a PR in this repository, with an EGG for Valheim (uMod) and **said he made this EGG in one day**, when I looked at his EGG, **it was eerily similar to mine**, and I believe this is a theft, because he did not give me any credit.

## I will show some similarities:
Mine:
```
#!/bin/bash
# Valheim Installation Script
# Colors
GR='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Server Files: /vhs/server
# Image to install with is 'debian:buster-slim'
apt update && apt upgrade -y
apt -y install libgcc1 lib32gcc1 gdb libc6 git wget curl tar zip unzip net-tools ca-certificates
apt update -y && apt upgrade -y && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt update -y && apt install -y dotnet-sdk-5.0 aspnetcore-runtime-5.0 libgdiplus
```

Yours:
```
#!/bin/bash
# Valheim Installation Script

# Server Files: /vhs/server
# Image to install with is 'debian:buster-slim'
apt update && apt upgrade -y
apt -y install libgcc1 lib32gcc1 gdb libc6 git wget curl tar zip unzip net-tools ca-certificates
apt update -y && apt upgrade -y && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt update -y && apt install -y dotnet-sdk-5.0 aspnetcore-runtime-5.0 libgdiplus
```
**It is quite similar, right?** Notice that there is a comment where it says "# Server Files: /vhs/server", for anyone who has ever made an EGG for Pterodactyl knows that the server should be mounted on /mnt/ and not /vhs/, this /vhs/ directory was the first problem I encountered when I started to make my EGG, I was innocent, I didn't even know what was /mnt/.
Também tenho uma testemunha que estava fazendo o EGG comigo, no dia em que cometi este erro, @Math-benites

----

Mine:
```
## create files to install server
mkdir -p /mnt/server
cd /mnt/server
chown -R root:root /mnt
export HOME=/mnt/server

# uMod fails otherwise for some reason, even running as root.
# This is changed at the end of the install process anyways.

# fixes Couldn't find a valid ICU package installed on the system
cd /mnt/server

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1; export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT" >> ~/.profile
export PATH="$PATH:/mnt/server/.dotnet/tools/"

log "Installing uMod global tool..."
dotnet tool update uMod --version "*-*" --global --add-source https://www.myget.org/f/umod/api/v3/index.json
dotnet new -i "uMod.Templates::*-*" --nuget-source https://www.myget.org/f/umod/api/v3/index.json &>/dev/null
```

Yours:
```
## Initialize folder permissions
mkdir -p /mnt/server
cd /mnt/server
chown -R root:root /mnt
export HOME=/mnt/server


# Configure dotnet
cd /mnt/server
dotnet tool update uMod --version "*-*" --global --add-source https://www.myget.org/f/umod/api/v3/index.json
dotnet new -i "uMod.Templates::*-*" --nuget-source https://www.myget.org/f/umod/api/v3/index.json &>/dev/null
echo "PATH=\$PATH:\$HOME/.dotnet/tools; export PATH" >> ~/.profile
echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1; export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT" >> ~/.profile

mkdir .dotnet && cd .dotnet
curl -sSL -o dotnet-sdk.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.103/dotnet-sdk-5.0.103-linux-x64.tar.gz.
tar -xvf dotnet-sdk.tar.gz && rm dotnet-sdk.tar.gz && cd /mnt/server
```

Notice that the beginning is identical; the dotnet commands part, I found out that I should use them directly in my installation script (instead of downloading a script from umod to install uMod) on 2/21 (As you can see here: https://github.com/CastBlacKing/Pterodactyl-Umod-Valheim/commit/6b4f1e2efcfe4c90937ded1dec0e897ca89ccc02), and the code of the user who is stealing from me has exactly this same part.

----

Mine:
```
$HOME/.dotnet/tools/umod complete --install
clear

chmod +x /mnt/server/.dotnet/tools/umod

## install game using uMod Tool
. ~/.profile
umod install valheim -P
umod new launcher valheim -P --force
chmod +x valheim_server.x86_64
```

Yours:
```
## install game
chmod +x /mnt/server/.dotnet/tools/umod
.dotnet/tools/umod complete --install
. ~/.profile
umod install valheim -P
umod new launcher valheim -P --force
chmod +x valheim_server.x86_64

# Delete unnecessary files
if [ -f /mnt/server/start_server.sh ]; then
rm launcher.sh umod-install.sh start_server.sh start_server_xterm.sh
rm "Valheim Dedicated Server Manual.pdf"
fi
```

Notice that the last four lines of my code are exactly the same as his, and the comment above "install game **using uMod Tool**" the part "using uMod Tool" has been removed. The (chmod +x /mnt/server/.dotnet/tools/umod) and ($HOME/.dotnet/tools/umod complete --install) were just moved around.

----

Finally, I am posting this ISSUE asking you to REMOVE the PR of the user who is trying to steal from me, if you want this is my repository: https://github.com/CastBlacKing/Pterodactyl-Umod-Valheim/commits/main for anyone who wants to look at all the changes I already made to it, comparing the two codes, and knowing that this user made a Fork of my project and then DELETED it, I show that what he is trying to do is steal from me.

It has been two days since I published my PR with everything I did on my project, along with the entrypoint.sh that Softwarenoob made (AutoUpdate Schema), I thought about deleting it, for the lack of hope of being noticed, but I won't, I won't hand in days of work without a fight.

I end this ISSUE by saying that I am openly accusing user @Software-Noob  of having stolen my code and much of my project, of having published a PR without giving any credit to me.
I, like all the other developers, deserve respect and recognition for my projects, and I'm sure none of us will let that other people steal our codes.

**Comment by gOOvER** [comment]
Noone steal your code. That are normal Linux Commands and a comment is no Code.

BTW, you self use the Code of the original Valheim Egg and all eggs here are Licenced under MIT. So all created eggs also under MIT ;) MB you should learn Licencing.

And please stop this now, to tell everyone, that they steal your code. I test your egg and it don't work.

**Comment by FoksVHox** [comment]
If you believe a theft has happened, then go to the police. But they'll most likely just ignore it as no theft has happened. The MIT license is a open source license which means everyone is allowed to fork it, make changes and make a PR to this repo.

**Comment by CastBlacKing** [comment]
> likely just ignore

The MIT license says that the only thing that must be maintained is: "with conditions only requiring preservation of copyright and license notices."

**Comment by CastBlacKing** [comment]
> 
> 
> If you believe a theft has happened, then go to the police. But they'll most likely just ignore it as no theft has happened. The MIT license is a open source license which means everyone is allowed to fork it, make changes and make a PR to this repo.

The MIT license says that the only thing that must be maintained is: "with conditions only requiring preservation of copyright and license notices."

**Comment by FoksVHox** [comment]
> > If you believe a theft has happened, then go to the police. But they'll most likely just ignore it as no theft has happened. The MIT license is a open source license which means everyone is allowed to fork it, make changes and make a PR to this repo.
> 
> The MIT license says that the only thing that must be maintained is: "with conditions only requiring preservation of copyright and license notices."

That is correct. however, if you are not able to prove that Software-Noob "stole" the config, there isn't anything to do, and even if you can, you don't own a set of Linux commands, there is no proof that Software-Noob weren't working on it, before/after/at the same time as you. You really need to stop crying about this. Yes, you made a PR, that wasn't working correctly, yes Software-Noob **MIGHT** have forked your repo and submitted a PR, where the egg has its base from your repo. At the end of the day, if you can't handle that a person, with more experience than you, forks your repo, and submits a functioning egg, you should've made the repo private. Your work wasn't stolen or anything else.

**Comment by gOOvER** [comment]
> > 
> > 
> > If you believe a theft has happened, then go to the police. But they'll most likely just ignore it as no theft has happened. The MIT license is a open source license which means everyone is allowed to fork it, make changes and make a PR to this repo.
> 
> The MIT license says that the only thing that must be maintained is: "with conditions only requiring preservation of copyright and license notices."

You used allready the whole Code from Vanilla Valheim Egg. So, where are the Copyright from this Autor?

whoever sits in a glass house shouldn't throw stones. ;)
