### ISSUE TITLE
Valheim Egg missing SDL

### ISSUE THREAD

**Issue by HoleInTheSeat** [parkervcp/eggs#1015]
The Valheim CMD egg is missing the SDL library causing this error on startup
"Warning: failed to init SDL thread priority manager: SDL not found"
and causes the boot to hang for a couple minutes.

This can be solve by installing libsdl2-2.0-0:i386. I've edited my script and this fixed the issue entirely.

**Comment by gOOvER** [comment]
This is not really a problem and the egg work as it should. this lib is missing in image ;)

**Comment by parkervcp** [comment]
I have added sdl to the docker containers. If you don't have sdl installed on the host it falls in the container as far as I know.

This is also not an actual issue.

**Comment by hackmoore** [comment]
> I have added sdl to the docker containers. If you don't have sdl installed on the host it falls in the container as far as I know.
> 
> This is also not an actual issue.

Hey could we have a link to installation instructions and a comment in the README to note that there is this dependancy?
I've run the following but still getting the below error.
`apt-get install gcc && apt-get install libsdl2-2.0`
`Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '896660' already up to date.
:/home/container$ export templdpath=$LD_LIBRARY_PATH; export DOORSTOP_ENABLE=TRUE; export DOORSTOP_INVOKE_DLL_PATH=./BepInEx/core/BepInEx.Preloader.dll; export DOORSTOP_CORLIB_OVERRIDE_PATH=./unstripped_corlib; export LD_LIBRARY_PATH=./doorstop_libs:$LD_LIBRARY_PATH; export LD_PRELOAD=libdoorstop_x64.so:$LD_PRELOAD; export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH; export SteamAppId=892970; ./start_server_bepinex.sh -nographics -batchmode -name "${SERVER_NAME}" -port ${SERVER_PORT} -world "${WORLD}" -password "${PASSWORD}" -public ${PUBLIC} > >(sed -uE "${FILTER}") & trap "${STOP}" 15; wait $!
/bin/sh: symbol lookup error: ./doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
