### ISSUE TITLE
Deno Programming Language

### ISSUE THREAD

**Issue by Steel-Discord** [parkervcp/eggs#1022]
Service: Deno 

Does this expand an already existing service: N

Link to game: https://deno.land

Links for server downloads: None (Read Install Instructions)

Links for install steps/docs:
Install Instructions: https://deno.land/
Docs: https://deno.land/manual

**Comment by parkervcp** [comment]
@Steel-Discord You want to test #1058 ?

**Comment by Steel-Discord** [comment]
@parkervcp this works perfectly thanks!
