### ISSUE TITLE
Cant start jmusicbot

### ISSUE THREAD

**Issue by finnie2006** [parkervcp/eggs#1023]
i settet up the bot but when i start i get this

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from xcgc/images 
Digest: sha256:fb9ff91918c94a1ad8d254180436098bdbb3eae64d241990e369aec796a74b2e 
Status: Image is up to date for ghcr.io/xcgc/images:debian_node14 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ java -Djavax.accessibility.assistive_technologies=" " -Dnogui=true -jar JMusicBot.jar
/entrypoint.sh: line 10: java: command not found
container@pterodactyl~ Server marked as offline...

**Comment by gOOvER** [comment]
Looks like a wrong image. its node14, not java

**Comment by finnie2006** [comment]
Yeah i fixed it thanks
