### ISSUE TITLE
FiveM Server Status Bug

### ISSUE THREAD

**Issue by Blizzard098** [parkervcp/eggs#103]
Panel Version: Latest
Daemon Version: Latest 
Service: FiveM
Modified: No

Expected Behavior: Display proper server status

Actual Behavior: Displaying "starting" while the server is running. Not too big of an issue, just making my OCD twitch haha.

Steps to Reproduce: (Step by step what to do to cause the issue)

1. Install the FiveM Egg
2. Start the server
3. Go to "My Servers" and look at the server status. It says "Starting" even though it's running.

**Comment by Blizzard098** [comment]
Nevermind, resolved itself after 5 minutes.

**Comment by Sir3lit** [comment]
For future reference, it waits for the console to say a set message when the server is 100% done starting thus goes for all servers.
