### ISSUE TITLE
[REQUEST] BeamMP Mod

### ISSUE THREAD

**Issue by Tim-Rambo** [parkervcp/eggs#1030]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc)
BeamNG
Does this expand an already existing service: Y/N
N
Link to game: (Ex. minecraft.net/factorio.com/etc)
https://www.beamng.com
Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
https://beammp.com
Links for install steps/docs:
https://wiki.beammp.com/en/home/server-installation

**Comment by parkervcp** [comment]
Can you test #983 ?

**Comment by Tim-Rambo** [comment]
> Can you test #983 ?

Thats a different mod I have never heard of. BeamMP has been out way longer than KissMP(Nov 6th 2020)

**Comment by parkervcp** [comment]
Ah I see

**Comment by Tim-Rambo** [comment]
> Ah I see

Found out about BeamMP trough 1m+ youtubers that does FiveM RP

**Comment by PenguinNexus** [comment]
Please see that I've already submitted a request for this: https://github.com/parkervcp/eggs/issues/1014 :)
