### ISSUE TITLE
Server won't show in Steam & Serverlist

### ISSUE THREAD

**Issue by TheFrodo** [parkervcp/eggs#1032]
Panel Version: 1.3.1
Daemon Version: 1.3.1
Service: Valheim
Modified: no

Expected Behavior: show in steam / valheim server list

Actual Behavior: in steam: no Answer from Server / in valheim wont show up in serverlist

IDK if the server shows up in steam serverlist, but in Valheim it must show up?

**Comment by Software-Noob** [comment]
This is an issue with the game itself and is up to the game developers to fix. Join their Discord server to keep up with any updates and bugs.
