### ISSUE TITLE
[Egg] - Discord.JS egg will not clone/pull git changes for private repositories.

### ISSUE THREAD

**Issue by DylanGS9** [parkervcp/eggs#1034]
Panel Version: 1.3.1
Daemon Version: latest as of 3/16/2021
Service: discordjs
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables): no

Expected Behavior: To pull git changes/clone the git repository.

Actual Behavior: Nothing, just kinda stays there and does nothing.

Problem: will not clone/pull git changes for private repositories. I've put in all the info I've needed to, tried several different things, and even asked around the pterodactyl discord server.

Steps to Reproduce: (Step by step what to do to cause the issue):
Create a server.
Put in the information of a PRIVATE github repository. 
and boom, it won't clone

**Comment by parkervcp** [comment]
can you give an example of the repo name you used?

**Comment by DylanGS9** [comment]
> can you give an example of the repo name you used?

My repository is named XovBot, I tried the entire url, with and without `https://`
I also tried with just the name, and my user and the repo, for example: DylanGS9/XovBot

**Comment by parkervcp** [comment]
I made a private repo - `parkervcp/test-js` and generated a personal access token to use instead of a password.

This pulled my private repo just fine.

If you didn't set a branch it defaults to `master` as that is the old default, `main`. You didn't provide install logs so I will be closing this out.
