### ISSUE TITLE
Zeppelin Discord bot

### ISSUE THREAD

**Issue by ririko5834** [parkervcp/eggs#1035]
Service: (Ex. minecraft/factorio/etc) Zeppelin Discord bot

Does this expand an already existing service: N

Link to game: https://github.com/Dragory/ZeppelinBot

Links for server downloads: https://github.com/Dragory/ZeppelinBot

Links for install steps/docs: https://github.com/Dragory/ZeppelinBot#running-the-bot

**Comment by parkervcp** [comment]
This could run in the generic nodejs egg but they decided to pack their stuff in a way to make it difficult. I won't make an egg specific to this.
