### ISSUE TITLE
pocketmine_mp PHP link needs updated

### ISSUE THREAD

**Issue by cyberz0mbie** [parkervcp/eggs#1036]
The PHP version listed on this egg needs updated to use 7.4 as the 7.3 link is dead.

**Comment by gOOvER** [comment]
> The PHP version listed on this egg needs updated to use 7.4 as the 7.3 link is dead.

Use the updated Egg. It's a long time on 7.4

**Comment by cyberz0mbie** [comment]
Rip. Thanks.
