### ISSUE TITLE
Request: Call of Duty 4 X (CoD4X)

### ISSUE THREAD

**Issue by h0rnyc0rny** [parkervcp/eggs#1038]
Service: CoD4X

Does this expand an already existing service: N

Link to game: https://store.steampowered.com/app/7940/Call_of_Duty_4_Modern_Warfare/

Links for server downloads: 
https://cod4x.me/
https://cod4x.me/downloads/cod4x_server-linux_19.3.zip

Links for install steps/docs: https://github.com/callofduty4x/cod4x_server#setting-up-a-call-of-duty-4-server-with-cod4x-18
It is more an install doc when all game files are already available - here i didn't find some official

Also a Nest/Eggs that uses LGSM would be nice - So they already implemented to setting up a CoD4x server
https://linuxgsm.com/lgsm/cod4server/

Dont judge me or my nick, please ;)

**Comment by DatMayo** [comment]
@h0rnyc0rny The provided download link is only valid, if you create an account on cod4x site. You need to provide a link where a script can auto download the server files.

**Comment by h0rnyc0rny** [comment]
@DatMayo im not sure but i can Download the Serverfiles directly using this link: 
https://cod4x.me/downloads/cod4x_server-linux_19.3.zip
But by using this provided server files it wont work, because the game files are missing

thats why i recommanded using LGSM for that - https://linuxgsm.com/lgsm/cod4server/ - maybe LGSM can be integrated in an egg?

it has a very similar list of games compared to pterodactly eggs. It is an easy way to manage servers using the terminal, but hard to give simple mangement fetures to other useres. 

if this is to much effort to check, no worries. it was just an idea :)

**Comment by DylanGS9** [comment]
> @DatMayo im not sure but i can Download the Serverfiles directly using this link:
> https://cod4x.me/downloads/cod4x_server-linux_19.3.zip
> But by using this provided server files it wont work, because the game files are missing
> 
> thats why i recommanded using LGSM for that - https://linuxgsm.com/lgsm/cod4server/ - maybe LGSM can be integrated in an egg?
> 
> it has a very similar list of games compared to pterodactly eggs. It is an easy way to manage servers using the terminal, but hard to give simple mangement fetures to other useres.
> 
> if this is to much effort to check, no worries. it was just an idea :)

That link does in fact work for direct downloads btw.
