### ISSUE TITLE
Jenkins Build Server

### ISSUE THREAD

**Issue by JohnB17** [parkervcp/eggs#1039]
Service: Jenkins Build Server

Does this expand an already existing service: N

Link to game: [NONE]

Links for server downloads: https://www.jenkins.io/

Links for install steps/docs: https://www.jenkins.io/doc/book/installing/

**Comment by parkervcp** [comment]
A build server is not something you want to run in pterodactyl. It's either going to run out of memory due to limits or use most than you want if you don't set them up.

On top of all of this it's a java application so you can run it in any java based egg like the minecraft one.

**Comment by kubo6472** [comment]
Hey, I would suggest running Jenkins' jobs inside pterodactyl seems like a great idea to further properly isolate it. Not sure about the UI itself though.
