### ISSUE TITLE
Curl large files

### ISSUE THREAD

**Issue by githubAlireza** [parkervcp/eggs#1040]
Panel Version: 1.2.2
Daemon Version: 1.2.2
Service: (minecraft/factorio/etc...)
Modified: (yes)

Expected Behavior:
Should fully download the file as in ubuntu 

Actual Behavior:
  0     0    0     0    0     0      0      0 --  1  677M    1 9408k    0     0  22.0M      0  0  6  677M    6 44.4M    0     0  31.5M      0  0 11  677M   11 76.2M    0     0  31.6M      0  0 14  677M   14  100M    0     0  31.3M      0  0:00:21  0:00:03  0:00:18 31.3M
curl: (23) Failed writing body (1596 != 5840)

It downloads only first 100 MB of the file

Steps to Reproduce:
curl -L -o  cs_public.tar.gz http://172.16.0.20/pack/cs_public.tar.gz

**Comment by danny6167** [comment]
tmpfs is my default limited to 100MB. Either change your wings config, or download into your servers folder.

**Comment by gOOvER** [comment]
this have nothing to Do with eggs

**Comment by parkervcp** [comment]
curl into the /mnt/server/ directory if you want to curl large files.

This is not an egg issue.
