### ISSUE TITLE
Mumble SSL Certificate Issue

### ISSUE THREAD

**Issue by HidYn** [parkervcp/eggs#1041]
---------------

Panel Version: 1.3.1
Daemon Version: 1.3.1
Service: Mumble
Modified: No

Expected Behavior:
Mumble is able to read and apply LetsEncrypt certificates. I have tested this via mounts and simply uploading the certificates to a folder using the file manager.

Actual Behavior:
It looks like there is a permission issue when it comes to reading the certs.  Once the settings is applied the container will no longer start up due to an error reading the files.

Steps to Reproduce: 
Generate a LetsEncrypt certificate for you domain eg. mumble.example.com and try and apply the certificates in the mumble.ini file. Not sure if this article helps - https://github.com/mumble-voip/mumble/issues/1949#issuecomment-189831316

**Comment by TjeuKayim** [comment]
Did you already find a solution by yourself?

**Comment by HidYn** [comment]
I'm afraid not but I realised Mumble is a core egg so I opened a ticket on on the pterodactyl panel github. Not that used to Github so sorry for the inconvenience.
