### ISSUE TITLE
Error when transfering a server to another node

### ISSUE THREAD

**Issue by Kriiiiiiiz** [parkervcp/eggs#1042]
I get this when transfering a server:

![screenshot_ptero](https://user-images.githubusercontent.com/13300613/112069879-edf64280-8b6c-11eb-917b-b163ca418d56.png)

What could be causing it ?

**Comment by gOOvER** [comment]
Have nothing to Do with eggs. Use Ptero Bugtracker

**Comment by Kriiiiiiiz** [comment]
Sorry, u right, didnt notice. Where can i find Ptero Bugtracker ? @gOOvER

**Comment by FoksVHox** [comment]
@Kriiiiiiiz On their GitHub
