### ISSUE TITLE
7 Days to Die telnet password variable missing

### ISSUE THREAD

**Issue by daredev** [parkervcp/eggs#1043]
Panel Version: 1.3.1
Daemon Version: 1.3.1
Service: 7 Days to Die
Modified: no

Expected Behavior: Telnet password variable for use in serverconfig.xml and during the server start/restart.

Actual Behavior: After every restart panel reports STARTING status until password is entered manually in the panel console

[Screenshot](https://cdn.discordapp.com/attachments/404105683336953866/823999945123954698/unknown.png)

Steps to Reproduce: 

1. Install server
2. Set your telnet password in serverconfig.xml
3. Restart the server manually or by setting up a scheduled restart

**Comment by parkervcp** [comment]
telnet has no way to automate a password input. If you are running the server without the port being exposed then you are fine to not have a password set.
