### ISSUE TITLE
7 Days to Die: commands not being executed immediately

### ISSUE THREAD

**Issue by daredev** [parkervcp/eggs#1044]
Panel Version: 1.3.1
Daemon Version: 1.3.1
Service: 7 Days to Die
Modified: no

Expected Behavior: "say" command being executed immediately (without offset)

Actual Behavior:  If you create two scheduled Send command tasks: one at 9:00 and second at 9:05 and use: `say "test1"` and `say "test2"` the time the first message will be executed is 9:05. The task will execute but the command will not be sent. If you send `say ""` command through the panel's console after the first scheduled task but before second task then the missing first message suddenly executes. 

Steps to Reproduce: 

1. Install the server
2. Create scheduled task with Send command as `say "TEST 1"` to fire in 5 minutes
3. Create another scheduled task with Send command as `say "TEST 2"` to fire in 10 minutes
4. Run `say ""` in panel's console

**Comment by Software-Noob** [comment]
I just made a test server with a schedule that contains three tasks of `say "test1" say "test2" say "test3"` at different intervals, and they all were sent successfully with all of them including the first one being shown in the console and sent to the server

**Comment by daredev** [comment]
> 
> 
> I just made a test server with a schedule that contains three tasks of `say "test1" say "test2" say "test3"` at different intervals, and they all were sent successfully with all of them including the first one being shown in the console and sent to the server

@Software-Noob Thank you for trying to help me out with this issue!

Did you get lines in the console containing `Chat (from '-non-player-', entity id '-1', to 'Global'):` after scheduler executing the commands? This is an indicator that the commands were actually sent and the game executed them. 

I get output like this: 

say "test1"  

say "test2"  

INF Executing command 'say "test1"' by Telnet from 127.0.0.1:37962  

INF Chat (from '-non-player-', entity id '-1', to 'Global'): 'Server': test1  

while being in the game I haven't seen the first message

**Comment by Software-Noob** [comment]
> > I just made a test server with a schedule that contains three tasks of `say "test1" say "test2" say "test3"` at different intervals, and they all were sent successfully with all of them including the first one being shown in the console and sent to the server
> 
> @Software-Noob Thank you for trying to help me out with this issue!
> 
> Did you get lines in the console containing `Chat (from '-non-player-', entity id '-1', to 'Global'):` after scheduler executing the commands? This is an indicator that the commands were actually sent and the game executed them.
> 
> I get output like this:
> 
> say "test1"
> 
> say "test2"
> 
> INF Executing command 'say "test1"' by Telnet from 127.0.0.1:37962
> 
> INF Chat (from '-non-player-', entity id '-1', to 'Global'): 'Server': test1
> 
> while being in the game I haven't seen the first message

I am unable to replicate your issue. I tested this on two new servers with a 30-second offset. They also show up in the in-game chat

```
2021-03-23T22:03:25 34.440 INF [Steamworks.NET] GameServer.LogOn successful, SteamID=90144412674718722, public IP=5*.19*.6*.4*
say "test1"
2021-03-23T22:03:58 67.293 INF Executing command 'say "test1"' by Telnet from 127.0.0.1:35164
2021-03-23T22:03:58 67.298 INF Chat (from '-non-player-', entity id '-1', to 'Global'): 'Server': test1
say "test2"
2021-03-23T22:04:30 98.642 INF Executing command 'say "test2"' by Telnet from 127.0.0.1:35164
2021-03-23T22:04:30 98.642 INF Chat (from '-non-player-', entity id '-1', to 'Global'): 'Server': test2
say "test 3"
2021-03-23T22:05:00 128.741 INF Executing command 'say "test 3"' by Telnet from 127.0.0.1:35164
2021-03-23T22:05:00 128.741 INF Chat (from '-non-player-', entity id '-1', to 'Global'): 'Server': test 3
```

**Comment by parkervcp** [comment]
This is not an egg issue but a panel issue. Likely with your pteroq.
