### ISSUE TITLE
OpenVPN Egg

### ISSUE THREAD

**Issue by DylanGS9** [parkervcp/eggs#1047]
Service: OpenVPN

Does this expand an already existing service: N
Link: https://openvpn.net/

Links for server downloads: https://openvpn.net/vpn-software-packages/
The link above has all versions for Linux.

Links for install steps/docs:
https://openvpn.net/vpn-software-packages/
https://openvpn.net/community-resources/how-to/
https://openvpn.net/community-resources/how-to/#installing-openvpn

**Comment by DylanGS9** [comment]
I'll try to do a PR if I could figure it out!

**Comment by parkervcp** [comment]
#817 as to why I closed this.
