### ISSUE TITLE
Code-Server SSL

### ISSUE THREAD

**Issue by HarrisonMayotte** [parkervcp/eggs#1048]
Hi,
I was wondering how I can install SSL with lets-encrypt for the code-server egg. I'm not sure if that would mean adding something to the docker container or what would need to go on there.

**Comment by parkervcp** [comment]
You can copy your ssl cert into the egg and have it reference it there.

**Comment by HarrisonMayotte** [comment]
@parkervcp Where do I do that? Is that a CLI thing?
