### ISSUE TITLE
Valheim Plus version issues after install

### ISSUE THREAD

**Issue by SG-Brandon** [parkervcp/eggs#1049]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number) current
Daemon Version: (version number) current
Service: (minecraft/factorio/etc) Valheim Plus
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) To produce error, no - to fix it, yes.  You change enforce mod to false server and client side

Expected Behavior: client can immediately log into server after server installs and they install valheim plus client side

Actual Behavior:  Client must edit config file on server and on client to not enforce mod.

Steps to Reproduce: (Step by step what to do to cause the issue)  Install server, log in, version incompatibility

**Comment by Software-Noob** [comment]
"current" is not a valid version. That error should really only occur on the old 0.7 panel, which requires a restart after importing new eggs

**Comment by SG-Brandon** [comment]
v1.0.33 Wisp

Yeah I'm not sure what is or isn't causing it.  I just know on a 100% fresh install of valheim plus, client and server have to edit the config file to enforcemod = false

**Comment by gOOvER** [comment]
@parkervcp 

Can be closed. Have nthing to do with the Egg
