### ISSUE TITLE
Request: LS19

### ISSUE THREAD

**Issue by NxrVincent** [parkervcp/eggs#1053]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Landwirtschafts-Simulator 19

Does this expand an already existing service: Y

Link to game:
https://www.farming-simulator.com/?lang=de

Links for server downloads:
https://github.com/cbeneke/docker-farming-simulator-server

Links for install steps/docs:
https://github.com/cbeneke/docker-farming-simulator-server/blob/master/README.md

**Comment by parkervcp** [comment]
As I said in #307 I am closing this out. I don't want to fight with wine to try and get it working.

If someone can get a working copy of the server to run in wine, and join it, I will consider accepting a PR.
