### ISSUE TITLE
Discord .Net

### ISSUE THREAD

**Issue by TonyS95** [parkervcp/eggs#1054]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc) Discord .Net Egg

Does this expand an already existing service: Y/N N

Link to game: (Ex. minecraft.net/factorio.com/etc) https://github.com/discord-net/Discord.Net

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page. https://github.com/discord-net/Discord.Net

Links for install steps/docs:

**Comment by Software-Noob** [comment]
Do you have an example repository of a .NET discord bot for testing?

**Comment by TheRealHeyJack** [comment]
how about this @Software-Noob https://github.com/Coding-with-Efehan/Tutorial-DNBDS

**Comment by QuintenQVD0** [comment]
There was a generic C# egg added what runs .net so that can be used.
