### ISSUE TITLE
Veloren Dedicated Server

### ISSUE THREAD

**Issue by HEZiogg** [parkervcp/eggs#1068]
Service: Veloren

Does this expand an already existing service: No

Link to game: https://veloren.net/download/

Links for server downloads: https://gitlab.com/veloren/veloren/-/tree/master/server-cli/src 

Links for install steps/docs: https://book.veloren.net/players/hosting-a-server.html - They only give an example for Docker, but perhaps its still a possible candidate for an egg, since they provide the rs files. 

Update:
Did some more digging and found this: https://book.veloren.net/players/hosting-server-on-rpi.html - This looks like it could help set up the egg a bit more than the docker image. The challenge is then, how to best keep it updated.

https://book.veloren.net/players/userdata-folder-structure.html#settingsron-server-edition -> server settings (view distance, max players, etc)

Thanks for the consideration

**Comment by parkervcp** [comment]
@HEZiogg If you want to test that out,

**Comment by HEZiogg** [comment]
Tested. Works after adding a start condition string. Just needs config of the server port, server name, view distance etc. Great job!
