### ISSUE TITLE
Jts3servermod Request

### ISSUE THREAD

**Issue by buracat** [parkervcp/eggs#107]
**Service**: Jts3servermod (this is a teamspeak 3 bot)

**Link to game**: https://www.stefan1200.de/forum/index.php?topic=2.0

**Extra**: https://github.com/phaldan/docker-JTS3ServerMod

**Comment by NgLoader** [comment]
@buracat Finished
![Picture](https://user-images.githubusercontent.com/13753840/51004044-4ff0a180-1539-11e9-9f0a-31bc7712fada.png)

**Comment by NgLoader** [comment]
@parkervcp You can close this egg request
