### ISSUE TITLE
Terraria Vanilla 4.1.2 Update Request

### ISSUE THREAD

**Issue by TheBossTim** [parkervcp/eggs#1070]
Service: Terraria (Vanilla)

Does this expand an already existing service: Y

Link to game: https://terraria.org/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page. https://terraria.org/system/dedicated_servers/archives/000/000/043/original/terraria-server-142.zip

Links for install steps/docs: https://terraria.fandom.com/wiki/Server

**Comment by Software-Noob** [comment]
The terraria egg isn't locked to any specific version, you can specify what version you want to install in the startup variables. Setting it to latest would install the latest version - It requires a reinstall to update.

I just tested and it installed v1.4.2 just fine for me.

**Comment by parkervcp** [comment]
Have you looked at where those download links point?
