### ISSUE TITLE
Nameless-Link Bot

### ISSUE THREAD

**Issue by HidYn** [parkervcp/eggs#1071]
Service: Nameless-Link Bot

Does this expand an already existing service: N

Link to game: https://github.com/NamelessMC/Nameless-Link

Links for server downloads: https://ci.derkad.es/job/Nameless%20Link/

Links for install steps/docs: https://github.com/NamelessMC/Nameless-Link/wiki/Installation-guide

Nameless-Link is a Discord bot that intergrates with NamelessMC and allows Role Syncing.

**Comment by parkervcp** [comment]
As this takes 2 images in their docs. I am not particularly interested in building out the single image to do the same thing.

**Comment by parkervcp** [comment]
> Ah I see what you mean for the Database mode. I was requesting just for the Stateless mode as it's what they recommend and it supports 1 Discord server and 1 Website sorry for not being more clear.
> 
> Thank you for replying :)

That is a very different thing then.

**Comment by parkervcp** [comment]
If this is just a jar file you can duplicate any minecraft egg and use it to run this.
