### ISSUE TITLE
Request: Rocket chat server

### ISSUE THREAD

**Issue by LosBagros** [parkervcp/eggs#1075]
Service: Rocket chat

Does this expand an already existing service: N

Link to game: https://rocket.chat/

Links for server downloads: https://rocket.chat/install/

Links for install steps/docs: https://docs.rocket.chat/

**Comment by parkervcp** [comment]
Per their docs they require a mongodb on top of their own server images. I don't really want to work on cramming it all into one.

**Comment by parkervcp** [comment]
You are probably better off just running the docker-compose files.
