### ISSUE TITLE
FiveM Keeps on Crashing Exit code: 134

### ISSUE THREAD

**Issue by NexCodeJimM** [parkervcp/eggs#1079]
Panel Version: 1.3.2
Daemon Version: 1.3.2
Service: FiveM
Modified: No

The server keeps on crashing. Below the is log before the crash. I'm trying to run a personal FiveM server with txAdmin enabled using the FiveM egg provided by parkervcp. It keeps saying Exit code: 134 but I do not really know what that means. Hopefully, someone can help me with this :/

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.

/entrypoint.sh: line 12: 21 Aborted (core dumped) $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 134
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

Steps to Reproduce: (Step by step what to do to cause the issue)
1. I just started the server.
2. After 3-5 minutes the server will crash and will automatic restart.

**Comment by parkervcp** [comment]
@NexCodeJimM Is this a stock server or have you added plugins?

**Comment by NexCodeJimM** [comment]
@parkervcp I've only enabled tcAdmin. Also just to add, every time I boot the server, it will show a message saying that tcAdmin is outdated.

**Comment by parkervcp** [comment]
I just reinstalled and have no issues. Server has been up for hours. As for the txadmin version being out of date they just haven't updated the latest recommended version on the artifacts page yet.

**Comment by NexCodeJimM** [comment]
@parkervcp hmm.. weird. Did you also tried opening txAdmin when you reinstalled it? There are also times that it will crash while just exploring the txAdmin page.

**Comment by parkervcp** [comment]
I defaultéd to using tx admin after you said you enabled it.

**Comment by parkervcp** [comment]
I am using txadmin on the latest build (3797) with no issues. I didn't have issues before that either on the recommended build (3539).

**Comment by parkervcp** [comment]
I can't recreate this. I have tried several different fivem versions all with txadmin enabled. I even connected to the server and ran around to make sure it was running fine too.

**Comment by parkervcp** [comment]
The closest I have come to seeing an actual issue is someone using esx panel to do something.

**Comment by Bus13** [comment]
I am able to recreate this issue. The only thing I have enabled is txAdmin.

[22]: ../../../../vendor/node/src/env-inl.h:508:void node::Environment::DecreaseWaitingRequestCounter(): Assertion `(request_waiting_) >= (0)' failed.
Stacktrace:

/proc/self/maps:
41a24000-41a64000 rwxp 00000000 00:00 0 
1ef600000000-1ef600003000 rw-p 00000000 00:00 0 
1ef600003000-1ef600004000 ---p 00000000 00:00 0 
1ef600004000-1ef600014000 r-xp 00000000 00:00 0 
1ef600014000-1ef60003f000 ---p 00000000 00:00 0 
1ef60003f000-1ef600040000 ---p 00000000 00:00 0 
1ef600040000-1ef600043000 rw-p 00000000 00:00 0 
1ef600043000-1ef600044000 ---p 00000000 00:00 0 
1ef600044000-1ef60007f000 r-xp 00000000 00:00 0 
1ef60007f000-1ef600080000 ---p 00000000 00:00 0 
1ef600080000-1ef600083000 rw-p 00000000 00:00 0 
1ef600083000-1ef600084000 ---p 00000000 00:00 0 
1ef600084000-1ef6000bf000 r-xp 00000000 00:00 0 
1ef6000bf000-1ef6000c0000 ---p 00000000 00:00 0 
1ef6000c0000-1ef6000c3000 rw-p 00000000 00:00 0 
1ef6000c3000-1ef6000c4000 ---p 00000000 00:00 0 
1ef6000c4000-1ef6000ff000 r-xp 00000000 00:00 0 
1ef6000ff000-1ef600100000 ---p 00000000 00:00 0 
1ef600100000-1ef600103000 rw-p 00000000 00:00 0 
1ef600103000-1ef600104000 ---p 00000000 00:00 0 
1ef600104000-1ef60013f000 r-xp 00000000 00:00 0 
1ef60013f000-1ef600140000 ---p 00000000 00:00 0 
1ef600140000-1ef600143000 rw-p 00000000 00:00 0 
1ef600143000-1ef600144000 ---p 00000000 00:00 0 
1ef600144000-1ef60017f000 r-xp 00000000 00:00 0 
Memory around native instruction pointer (0x7f3d7add73f1):
0x7f3d7add73e1  00 00 b8 0e 00 00 00 31 d2 bf 02 00 00 00 0f 05  .......1........
0x7f3d7add73f1  c3 48 63 ff 50 b8 24 00 00 00 0f 05 48 89 c7 e8  .Hc.P.$.....H...
0x7f3d7add7401  08 89 fd ff 5a c3 48 63 ff 50 48 63 f6 b8 3e 00  ....Z.Hc.PHc..>.
0x7f3d7add7411  00 00 0f 05 48 89 c7 e8 f0 88 fd ff 5a c3 85 ff  ....H.......Z...

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

/entrypoint.sh: line 12:    22 Aborted                 (core dumped) $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
