### ISSUE TITLE
L4D2 Request

### ISSUE THREAD

**Issue by ToggleIP** [parkervcp/eggs#108]
Please fill out the information bellow and remove from the line up
---------------
Service:  Left 4 Dead 2

Link to game: http://www.l4d.com/blog/

**Comment by Jonnyfencing1** [comment]
Left for dead 2 is a source game

**Comment by parkervcp** [comment]
Here is the list of steam server ID's you can use to install the L4D server using the stock source engine game egg. https://developer.valvesoftware.com/wiki/Dedicated_Servers_List

**Comment by ToggleIP** [comment]
And how do i even do that. Is there any tutorial or something like that about custom source engine games
