### ISSUE TITLE
Bug: Permission Denied - ./bedrock_server

### ISSUE THREAD

**Issue by TheCuteFoxxy** [parkervcp/eggs#1080]
Panel Version: 1.3.2
Daemon Version: 1.3.2
Service: Minecraft Vanilla Bedrock
Modified: No

Expected Behavior:
Clicking panel start button starts the bedrock server and displays server information (i.e port)

Actual Behavior:
Server crashes with 
```
:/home/container$ ./bedrock_server
/entrypoint.sh: line 12: ./bedrock_server: Permission denied
```

Steps to Reproduce:
1. Load egg
2. Start server
3. Observe crashed state and error

**Comment by Software-Noob** [comment]
Reinstall the server to fix the permission or manually change the permission of the file as instructed on the Discord
