### ISSUE TITLE
OpenTTD egg script needs an update for 1.11.0

### ISSUE THREAD

**Issue by Wulfvenstierna** [parkervcp/eggs#1084]
**Panel Version:** 1.3.2
**Daemon Version:** 1.2.3
**Service:** OpenTTD
**Modified:** no (only in attempts to fix it myself)

**Expected Behavior:**

--2021-04-08 11:53:15--  https://cdn.openttd.org/openttd-releases/1.10.3/openttd-1.10.3-linux-ubuntu-bionic-amd64.deb
Resolving cdn.openttd.org... 13.225.87.50, 13.225.87.46, 13.225.87.30, ...
Connecting to cdn.openttd.org|13.225.87.50|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4852316 (4.6M) [application/octet-stream]
Saving to: 'openttd.deb'

openttd.deb           0%[                    ]       0  --.-KB/s              
openttd.deb         100%[===================>]   4.63M  --.-KB/s    in 0.07s   

2021-04-08 11:53:16 (62.6 MB/s) - 'openttd.deb' saved [4852316/4852316]

./
./usr/
./usr/games/
./usr/games/openttd
./usr/share/
./usr/share/applications/
./usr/share/applications/openttd.desktop
./usr/share/doc/
./usr/share/doc/openttd/
. . .

**Actual Behavior:**

--2021-04-08 11:52:01--  https://cdn.openttd.org/openttd-releases/1.11.0/openttd-1.11.0-linux-ubuntu-bionic-amd64.deb
Resolving cdn.openttd.org... 13.225.87.30, 13.225.87.46, 13.225.87.60, ...
Connecting to cdn.openttd.org|13.225.87.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6569398 (6.3M) [application/x-debian-package]
Saving to: 'openttd.deb'

openttd.deb           0%[                    ]       0  --.-KB/s              
openttd.deb         100%[===================>]   6.26M  --.-KB/s    in 0.1s    

2021-04-08 11:52:02 (62.7 MB/s) - 'openttd.deb' saved [6569398/6569398]

tar: can't open 'data.tar.xz': No such file or directory
mv: can't rename 'usr/share/games/openttd/*': No such file or directory
mv: can't rename 'usr/games/openttd': No such file or directory
chmod: openttd: No such file or directory
. . .

Able to get the extracting properly done on 1.11.0, however another issue occurred then which leads me to suspect this is something which needs to be solved within the script container itself:

:/home/container$ ./openttd -D
./openttd: error while loading shared libraries: libfluidsynth.so.1: cannot open shared object file: No such file or directory
. . .

**Comment by parkervcp** [comment]
@Wulfvenstierna  can you test that update please.

**Comment by Wulfvenstierna** [comment]
> @Wulfvenstierna can you test that update please.

It helped with the extraction :) However the issue with the audio file persist:

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:423f6da5e96c19df93382f824896625c726744aca0609f2166886c77990feff9 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:base_ubuntu 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./openttd -D
./openttd: error while loading shared libraries: libfluidsynth.so.1: cannot open shared object file: No such file or directory
container@pterodactyl~ Server marked as offline...

**Comment by parkervcp** [comment]
I thought that was part of the original issue and missed that the first time.

**Comment by parkervcp** [comment]
@Wulfvenstierna Should be fixed now. I updated the image.

**Comment by Wulfvenstierna** [comment]
> @Wulfvenstierna Should be fixed now. I updated the image.

Yes, it's working now! Thanks so much for the quick solution.
