### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by DylanGS9** [parkervcp/eggs#1085]
Panel Version: latest/1.3.2
Daemon Version: latest/1.3.2
Service: VS Code
Modified: no

Expected Behavior: To Run

Actual Behavior: Says it's running but doesn't work upon visiting the IP.

Steps to Reproduce: (Step by step what to do to cause the issue)
Install VS code egg
Set the bind-addr as your vps ip and dedicated port
go to the ip and port; example: 0.0.0.0:25565

**Comment by parkervcp** [comment]
`latest` is not a valid version number for the panel and daemon.

**Comment by DylanGS9** [comment]
> `latest` is not a valid version number for the panel and daemon.

latest means the latest panel and daemon version... which is 1.3.2

**Comment by parkervcp** [comment]
> latest means the latest panel and daemon version... which is 1.3.2

When a new release comes out that will no longer be valid. I ask for verions for a reason.

**Comment by DylanGS9** [comment]
> > latest means the latest panel and daemon version... which is 1.3.2
> 
> When a new release comes out that will no longer be valid. I ask for verions for a reason.

alright...

**Comment by omxpro** [comment]
Uh there is No Vs code egg or I can't find it?

**Comment by parkervcp** [comment]
<https://github.com/parkervcp/eggs/tree/master/software/code-server>

**Comment by parkervcp** [comment]
as far as I know others are running this server fine. I will be closing this out.
