### ISSUE TITLE
Self hosting Discord Invite Manager

### ISSUE THREAD

**Issue by Felix5566** [parkervcp/eggs#1087]
Service: Self hosting Discord Invite Manager

Does this expand an already existing service: N

Link to game: https://github.com/SideProjectGuys/invite-manager-bot

Links for install steps/docs:
1. https://github.com/SideProjectGuys/invite-manager-bot
2. and I think https://github.com/SideProjectGuys/invite-manager-bot/issues/167

**Comment by parkervcp** [comment]
This can be done with the discord.js egg. Everything but the db setup is already supported.

instead of `npm start` you just set the `bot_js` variable to `scripts/dev-run.js`

**Comment by Felix5566** [comment]
an how can i do npm install?

**Comment by parkervcp** [comment]
the install script in my egg does that already.

**Comment by Felix5566** [comment]
i dont think so

**Comment by Felix5566** [comment]
Can you add me on Discord? Felix5566#8183
