### ISSUE TITLE
Ark Server Egg: rcon startup

### ISSUE THREAD

**Issue by 0xfgarcia** [parkervcp/eggs#1091]
Panel Version: 1.2.2
Daemon Version: 1.2.3
Service: (Ark)
Modified: No

Console:
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...

![imagen](https://user-images.githubusercontent.com/2559586/114315025-6c575c00-9afd-11eb-8e28-d301857a624a.png)

**Comment by thibaultgamingshow** [comment]
how many time you waited ? cause its normal ...

**Comment by parkervcp** [comment]
You need to wait for the server to go online first.

**Comment by 0xfgarcia** [comment]
How long is it necessary to wait ? 

After 10 minutes I keep getting the same message, starting...

![imagen](https://user-images.githubusercontent.com/2559586/114438070-937a6000-9bc7-11eb-90d4-6af326ed5e6d.png)

**Comment by parkervcp** [comment]
@0xfgarcia Your first message said it isn't starting due to the query being the same as the game port. Which you can't do.

**Comment by 0xfgarcia** [comment]
Sorry, I had the Ark server running, I updated the egg, the mods and the server stopped booting.

I have tried clean install it again but I always have the same error. These are the ports that I have configured. 

What can be wrong? 

![imagen](https://user-images.githubusercontent.com/2559586/114444032-b2c8bb80-9bce-11eb-9f37-ad5d9df3bf8e.png)

**Comment by parkervcp** [comment]
primary is 7777 not 27015

**Comment by rdiane575** [comment]
Abort . Cant continue nothing working for me

**Comment by parkervcp** [comment]
no logs no help. So far this is still not an egg issue.

**Comment by 0xfgarcia** [comment]
Ok, thanks for your help it was a port problem, reinstall and working now!

**Comment by MrGoHosting** [comment]
i have the same probleme
