### ISSUE TITLE
Discord.JS BUG: Not pulling GitHub repo when it should

### ISSUE THREAD

**Issue by cayoten** [parkervcp/eggs#1092]
Panel Version: Latest (1.3.2)
Daemon Version: Latest (1.3.2)
Service: Discord.js
Modified: No

Expected Behavior: On startup, the server pulls any new code from GitHub repository and runs it locally.

Actual Behavior: It doesn't pull at all. (Even with an empty config, the files don't pull.) Configuration will be pasted below.

Steps to Reproduce: (Step by step what to do to cause the issue) Place any github link as a repository in your "Startup" params.

![image](https://user-images.githubusercontent.com/57970060/114317221-ab20ee00-9acc-11eb-8a56-1ebacb04ab41.png)

**Comment by arnav7633** [comment]
DId you find a fix, i have the same issue @cayoten

**Comment by cayoten** [comment]
> DId you find a fix, i have the same issue @cayoten

I had to create a new installation and set the repo then. I then just moved critical files that aren’t in the repo using FTP.

**Comment by Software-Noob** [comment]
You must have a git folder and auto update set to 1. Delete the git folder and reinstall if it doesn't work.
