### ISSUE TITLE
FiveM Symbols not found

### ISSUE THREAD

**Issue by larsjarred9** [parkervcp/eggs#1096]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: WISP Panel
Daemon Version: WISP Latest
Service: FiveM
Modified: no

Expected Behavior:
No errors in concole

Actual Behavior:
Missing symbols and other errors: https://prnt.sc/11cgept

Steps to Reproduce: 
1. Install server with the FiveM egg
2. Start that server after updating fivem key
3. Error

**Comment by parkervcp** [comment]
Please make sure you update your egg.

I am not sure what version you are on or what docker image it's using.
