### ISSUE TITLE
problem with egg curse-generic

### ISSUE THREAD

**Issue by Family4GamersYT** [parkervcp/eggs#1098]
Good afternoon, we have a problem with the egg curseforge generic, when we create a server with this egg it downloads all the files in the root of the server and downloads everything out of place, I attach a screen

Panel Version: latest/1.3.2
Daemon Version: latest/1.3.2
Service: VS Code
Modified: no

![Screenshot egg curse](https://user-images.githubusercontent.com/80338177/114706576-6d6cd100-9d29-11eb-937d-316107a1412f.png)

**Comment by parkervcp** [comment]
I do not support this egg anymore due to the sheer number of servers each being packed differently and the script is already huge and accounts for about 80% of the curseforge eggs.
