### ISSUE TITLE
Minecraft Bedrock Vanilla issue

### ISSUE THREAD

**Issue by dallaspowers** [parkervcp/eggs#110]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.10
Daemon Version: (version number)
Service: Minecraft Bedrock
Modified: No

Expected Behavior: Starting fine without error 

Actual Behavior: 
![image](https://user-images.githubusercontent.com/14980812/48302605-5aa4a100-e4cc-11e8-9832-96d75b137561.png)
I installed the egg the way it tells me to and it refuses to start.

**Comment by mayed505** [comment]
Restart your daemon `systemctl restart wings`

**Comment by dallaspowers** [comment]
wow... I thought I ran the command before. my apoligies.
