### ISSUE TITLE
Python egg 3.9

### ISSUE THREAD

**Issue by NoodlesDev987** [parkervcp/eggs#1100]
Please add also version 3.9 to discord.py egg

**Comment by parkervcp** [comment]
I already have a python 3.9 image you can add to your own egg.

**Comment by NoodlesDev987** [comment]
Just a question: Do I need to modify discord.py egg startup command to make it work with 3.9?
This is default command:
```if [[ -d .git ]] && [[ {{AUTO_UPDATE}} == "1" ]]; then git pull; fi; if [[ ! -z {{PY_PACKAGES}} ]]; then pip install -U --target .local/lib/python3.8/site-packages {{PY_PACKAGES}}; fi; if [[ -f /home/container/${REQUIREMENTS_FILE} ]]; then pip install -U --target .local/lib/python3.8/site-packages -r ${REQUIREMENTS_FILE}; fi; /usr/local/bin/python /home/container/{{BOT_PY_FILE}}```

Do I need to modify it to:
```if [[ -d .git ]] && [[ {{AUTO_UPDATE}} == "1" ]]; then git pull; fi; if [[ ! -z {{PY_PACKAGES}} ]]; then pip install -U --target .local/lib/python3.9/site-packages {{PY_PACKAGES}}; fi; if [[ -f /home/container/${REQUIREMENTS_FILE} ]]; then pip install -U --target .local/lib/python3.9/site-packages -r ${REQUIREMENTS_FILE}; fi; /usr/local/bin/python /home/container/{{BOT_PY_FILE}}```

**Comment by parkervcp** [comment]
In theory you don't need to specify the python version. I totally didn't notice that.
