### ISSUE TITLE
Node.js v15

### ISSUE THREAD

**Issue by NoodlesDev987** [parkervcp/eggs#1101]
Add support for node.js v15 to discord.js egg

**Comment by Software-Noob** [comment]
This would be something to suggest in the [images repository.](https://github.com/parkervcp/images) I have Nodejs 15 image available [here ](https://github.com/Software-Noob/pterodactyl-images/tree/main/debian-nodejs15)`quay.io/softwarenoob/pterodactyl-images:debian-nodejs15`

**Comment by parkervcp** [comment]
nodejs 15 now exists in my images repo
