### ISSUE TITLE
Reverse Proxying to Code server shows white screen.

### ISSUE THREAD

**Issue by Tydium** [parkervcp/eggs#1104]
Panel Version: 1.3.2
Daemon Version: 1.3.2
Service: code-server
Modified: No

Expected Behavior: Expect SSL to work properly and also be able to use the server.

Actual Behavior: Reverse proxy from nginx causes white screen.

Steps to Reproduce: 
1. Install the code server from egg
2. Setup your code server ports
3. Set certs in config to true.
3. run the code server.
4. setup a reverse proxy from nginx
5. try to connect with your domain in browser.
6. whitescreen should appear

**Comment by parkervcp** [comment]
Your reverse proxy should be closing the ssl connection not the code server. Trust me it will make it easier.

On a related note can you get logs for nginx here?

**Comment by Tydium** [comment]
I just fixed it. I rewrote my config and it works!
