### ISSUE TITLE
Game Request: OpenArena 0.8.8

### ISSUE THREAD

**Issue by Gadorach** [parkervcp/eggs#1105]
Service: OpenArena

Does this expand an already existing service: N

Link to game: http://www.openarena.ws/

Links for server downloads: http://www.openarena.ws/download.php

Links for install steps/docs: https://openarena.fandom.com/wiki/Servers

OpenArena is a game built from the IOQuake3 engine and contains completely community-created assets. As a result, it is completely free for use and play. I use this regularly, and I believe it would make a great addition to the Egg library. It should really go side-by-side with both the original Quake 3 and Urban Terror mods though.

**Comment by parkervcp** [comment]
@Gadorach if you can test that out.

**Comment by Gadorach** [comment]
I did attempt to test the egg, but I'm getting a "docker API v1.41 too new, only API 1.40 available" error currently. Haven't been able to find a more recent docker build than 20.10.6, that actually handles API v1.41, for my linux build, which is a 20.04 Ubuntu server. It's possible that the egg works fine, I just can't test it yet until docker releases more recent engine versions for my linux build.

Thanks a bunch for making it though, I'm sure it'll be useful to me as soon as the new docker version drops supporting API v1.41 that I can install haha
