### ISSUE TITLE
Factorio Egg not working

### ISSUE THREAD

**Issue by boyfromgermany** [parkervcp/eggs#1106]
The installation works however i cannot start the server afterwards

**Here is the Output of factorio-current.log**
   0.000 2021-04-20 19:52:16; Factorio 1.1.32 (build 58364, linux64, headless)
   0.000 Operating system: Linux
   0.000 Program arguments: "./bin/x64/factorio" "--create" "gamesave" 
   0.000 Read data path: /mnt/server/data
   0.000 Write data path: /mnt/server [24759/50139MB]
   0.000 Binaries path: /mnt/server/bin
   0.004 System info: [CPU: Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz, 4 cores, RAM: 15942 MB]
   0.004 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
   0.004 Running in headless mode
   0.007 Loading mod core 0.0.0 (data.lua)
   0.049 Loading mod base 1.1.32 (data.lua)
   0.278 Loading mod base 1.1.32 (data-updates.lua)
   0.400 Checksum for core: 4236520717
   0.400 Checksum of base: 1357215736
   0.565 Prototype list checksum: 3034860339
   0.602 Info PlayerData.cpp:73: Local player-data.json unavailable
   0.602 Info PlayerData.cpp:78: Cloud player-data.json unavailable
   0.604 Factorio initialised
   0.604 Info Main.cpp:739: Creating new map /mnt/server/gamesave
   1.430 Loading level.dat: 1259288 bytes.
   1.430 Info Scenario.cpp:197: Map version 1.1.32-0
   1.462 Checksum for script /mnt/server/temp/currently-playing/control.lua: 1735894310
   1.583 Goodbye

**Here is the Webinterface output**
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic reboot: last crash occurred less than 60 seconds ago.
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic reboot: last crash occurred less than 60 seconds ago.
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic reboot: last crash occurred less than 60 seconds ago.

**Comment by gOOvER** [comment]
The egg work as it Should; i have 2 Factorio Server
