### ISSUE TITLE
Add Wreckfest egg

### ISSUE THREAD

**Issue by Felix5566** [parkervcp/eggs#1107]
Does this expand an already existing service: N

Link to game: https://store.steampowered.com/app/228380/Wreckfest/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.

Links for install steps/docs:
https://discord.com/invite/wreckfest
https://discord.com/channels/330023066900103169/745926064844439592/745953274418692117
1. To load Wrekcfest with mods through SteamCMD: https://steamcommunity.com/workshop/filedetails/discussion/764432700/1645418344568183830/
2. General guide for setting up dedicated severs: https://steamcommunity.com/workshop/filedetails/discussion/764432700/1728701877518409023/

**Comment by waffleuncle** [comment]
100 % need this one !

**Comment by waffleuncle** [comment]
Any progress ?

**Comment by gOOvER** [comment]
Why you must join their Disord to install the Server?

**Comment by gOOvER** [comment]
As i see Windowes Only. So not possible with Ptero

**Comment by Felix5566** [comment]
> Why you must join their Disord to install the Server?

there is the Installation guide

**Comment by gOOvER** [comment]
> > Why you must join their Disord to install the Server?
> 
> there is the Installation guide

Windows only

**Comment by EsserGaming** [comment]
bruh

**Comment by Felix5566** [comment]
> > > Why you must join their Disord to install the Server?
> > 
> > 
> > there is the Installation guide
> 
> Windows only

And what is this?
https://github.com/WGOS/pteroq-eggs/tree/master/wreckfest

**Comment by gOOvER** [comment]
> > > > Why you must join their Disord to install the Server?
> > > 
> > > 
> > > there is the Installation guide
> > 
> > Windows only
> 
> And what is this?
> https://github.com/WGOS/pteroq-eggs/tree/master/wreckfest

idk. Theb use this

**Comment by Felix5566** [comment]
> 
> 
> > > > > Why you must join their Disord to install the Server?
> > > > 
> > > > 
> > > > there is the Installation guide
> > > 
> > > 
> > > Windows only
> > 
> > 
> > And what is this?
> > https://github.com/WGOS/pteroq-eggs/tree/master/wreckfest
> 
> idk. Theb use this

I am onyl using official eggs

**Comment by rdiane575** [comment]
So will I

**Comment by 88nightrider** [comment]
So no new development on this?

**Comment by gOOvER** [comment]
> So no new development on this?

can you read?

**https://github.com/parkervcp/eggs/issues/1107#issuecomment-1083232031**

**Comment by QuintenQVD0** [comment]
I will close this as Goover https://github.com/parkervcp/eggs/issues/1107#issuecomment-1083232031 told here
