### ISSUE TITLE
Mordhau, weird undocumented map/?MaxSlots=48 parameter used, crashes server on start

### ISSUE THREAD

**Issue by Arcanum417** [parkervcp/eggs#1109]
Panel Version: 1.3.2
Daemon Version: (version number)
Service: mordhau
Modified: no

Expected Behavior: Mordhau server launches

Actual Behavior: Doesn't and log ends with error `LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/Game/Mordhau/Maps/Grad/FL_Grad?MaxSlots=48?' is not a standard unreal filename or a long path name. Reason: Name may not contain the following characters: '?'`

Steps to Reproduce: Import mordhau egg, create mordhau server, start mordhau server

**Comment by parkervcp** [comment]
can you say which mordhau egg this is. The linux or wine one are vastly different.

**Comment by Arcanum417** [comment]
Sorry, it't the linux one.

**Comment by Software-Noob** [comment]
I've remade the egg, you can download and test it from the pull request above
