### ISSUE TITLE
Killing Floor 2 parse bug (?)

### ISSUE THREAD

**Issue by blu3bird23** [parkervcp/eggs#1112]
Panel Version: 1.3.2
Daemon Version: (version number)
Service: Killing Floor 2 (Source-Engine)
Modified: no

Expected Behavior:

Server name and WebAdmin settings should match the values from the panel.

Example:

Servername according to the panel = testserver.
After starting server = "Killing Floor 2 Server".

Actual Behavior:

Server name and WebAdmin settings are not changed. 
The default values are not overwritten.

Steps to Reproduce: install a fresh Server and enter all informations (Servername etc.)

**Comment by Software-Noob** [comment]
I can confirm that the parser isn't able to locate the required variables. I will push a new fix shortly.

**Comment by Software-Noob** [comment]
@blu3bird23 Can you test [this egg here](https://raw.githubusercontent.com/Software-Noob/eggs/patch-5/steamcmd_servers/killing_floor_2/egg-killing-floor2.json) and tell me if it resolves your reported issues.

**Comment by blu3bird23** [comment]
@Software-Noob works like a charm.
Thank you for your fast response!

Cheers
Kevin
