### ISSUE TITLE
New Egg For The GTA Connected platform

### ISSUE THREAD

**Issue by Lemonita66** [parkervcp/eggs#1115]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

**Service:**
Gta Connected Its a Multiplayer platform for gta 4 and other older gta games. like vice city, san anderas and gta 3

Does this expand an already existing service: Y/N
I dont think so, i dont know actually

**Link to game:** 
https://gtaconnected.com/downloads/

**Links for server downloads:** 
https://gtaconnected.com/downloads/GTAC-Server-Linux-1.2.10.tar.gz

**Links for install steps/docs:**
https://wiki.gtaconnected.com/LinuxServer

I tried it myself but couldn't figure it out, hope you can make one. its as simple as a gta samp server.

**Comment by Software-Noob** [comment]
Is this an empty sandbox from which you build your server? I've set it up, and there's really nothing going on, and the wiki doesn't provide much information.

**Comment by Lemonita66** [comment]
@Software-Noob, its something like fivem but for gta iv. you need to downgrade gta iv to 1.0.7.0,

Ive set up everything aswell, and when i hit lounge i join the server.

**Comment by Software-Noob** [comment]
What specifically are you stuck on if you can make it run and join? From a quick read, it appears to be installed on top of game server files, and then you script resources that you want

**Comment by Lemonita66** [comment]
@Software-Noob Like i said, its works the same like fivem, you install gta connected in a separate folder, just like fivem.

I just need an egg so i can host it in the panel.

**Comment by Lemonita66** [comment]
Its realy easy btw, u download the server. move it into your root.

CD server
chmod +x Server

and to start it
./Server
to close it
^C

**Comment by Software-Noob** [comment]
You can find the egg in the pull request above

**Comment by Lemonita66** [comment]
HERO! Tested it, works good ;)
