### ISSUE TITLE
Non-Game Egg Request

### ISSUE THREAD

**Issue by StormyIceLeopard** [parkervcp/eggs#1117]
Not sure if you do non-game requests but I would really use this.
I would even do it myself but I do not understand any of this.
---------------

Service: PLEX

Does this expand an already existing service: Yes

Link to service (not a game): https://www.plex.tv/

Links for server downloads: https://www.plex.tv/media-server-downloads/#plex-media-server

Links for install steps/docs: (Yes on forum but posted by an Employee) https://forums.plex.tv/t/official-plex-media-server-docker-images-getting-started/172291
![image](https://user-images.githubusercontent.com/10292779/115976930-d1b93d00-a540-11eb-98d4-a78a094cf02d.png)

**Comment by TASelwyn** [comment]
This panel is designed for game servers. Not running media servers.
If you want to run a plex server on the same server as pterodactyl, just add the docker container for plex and use it that way. Pterodactyl isn't designed to manage those. At all.

**Comment by StormyIceLeopard** [comment]
Bummer, okay.

**Comment by JulienTant** [comment]
> This panel is designed for game servers. Not running media servers.
> If you want to run a plex server on the same server as pterodactyl, just run the docker container for plex and use it that way. Pterodactyl isn't designed to manage those. At all.

Just adding to that that if your point is to get an UI, look at portainer to manager your docker containers.

**Comment by parkervcp** [comment]
So Plesx has no Command Line tooling. It's either running or it's not. with their own image it's still not built for pterodactyl and even if you added a mount for the files it's not really logical to host it in the panel.
