### ISSUE TITLE
Yatopia Egg Request

### ISSUE THREAD

**Issue by reputationpen** [parkervcp/eggs#1119]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Minecraft Yatopia Server)

Does this expand an already existing service: Y

Link to game: (https://yatopiamc.org/)

Links for server downloads: https://yatopiamc.org/download.html

Links for install steps/docs: It's the same as a normal minecraft server, but the jarfile is the yatopia one

**Comment by Software-Noob** [comment]
Duplicate of #967 which was refused

**Comment by EsserGaming** [comment]
The project is now archived
