### ISSUE TITLE
Rage.MP

### ISSUE THREAD

**Issue by waffleuncle** [parkervcp/eggs#1120]
Hello , 
As indicated I have allocated the ports to the server.
Unfortunately, once the server is launched it does not seem to download any file related to GTA MP. 
Is it possible to update it or simply remove it?

**Comment by Software-Noob** [comment]
The issue is not related to ports, it's because ragemp removed the old download files from their site. There is a pull request #1083 to update it, try it and post there if it works for you.

**Comment by parkervcp** [comment]
Closed with #1083
