### ISSUE TITLE
7 Days to die steamclient.so error

### ISSUE THREAD

**Issue by DGZYT** [parkervcp/eggs#1123]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number)
WISP v1.0.36
Daemon Version: (version number)
Not Sure
Service: (minecraft/factorio/etc)
7 Days to die
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)
No

Expected Behavior:
Server should find the steamclient.so file but cannot find it:

`[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
2021-04-27T19:12:50 41.458 ERR [Steamworks.NET] Could not initialize GameServer `

Actual Behavior:
The Error specified above

Steps to Reproduce: (Step by step what to do to cause the issue)
It was a clean install so no files were actually touched.

**Comment by TASelwyn** [comment]
This is Pterodactyl, not wisp. Contact wisp for help.

**Comment by Software-Noob** [comment]
> This is Pterodactyl, not wisp. Contact wisp for help.

There's no difference egg functionality-wise between the two.

@DGZYT You have to provide install logs for us to assist you.

**Comment by parkervcp** [comment]
I am not seeing this issue with the latest egg that is currently in the repo.

While it could probably use a quick touchup to use the latest steamcmd install script it's not broken so far as I can tell.
