### ISSUE TITLE
Apache2 egg

### ISSUE THREAD

**Issue by hypen-eng** [parkervcp/eggs#1127]
Please add an Apache2 egg it's an web-hosting egg
---------------

Service: 

Does this expand an already existing service: Y/N: N

Links for server downloads: https://httpd.apache.org/download.cgi

Links for install steps/docs:https://httpd.apache.org/download.cgi

**Comment by Software-Noob** [comment]
Pterodactyl isn't designed for hosting websites, denied in #87

**Comment by anondev-sudo** [comment]
Please add it

**Comment by Software-Noob** [comment]
Please stop spamming all issues.
