### ISSUE TITLE
Tea Speak server

### ISSUE THREAD

**Issue by EsserGaming** [parkervcp/eggs#1128]
Panel Version: 4.0.0
Daemon Version: 4.0.1
Service: TeaSpeak Server
Modified: no

Expected Behavior:
Marked as online

Actual Behavior: Starting server: then errors `Failed to parse config entry "query.max_line_buffer": Invalid node content. Requested was a integral of type unsigned long!`

Steps to Reproduce: Start server after reinstalling then error: `- Failed to parse config entry "query.max_line_buffer": Invalid node content. Requested was a integral of type unsigned long!`. I also get missing libs, only 3 out of the 14 included in the server zip from the official website.

**Comment by parkervcp** [comment]
Please be sure you are on the latest egg. It's currently working for me and I am having no issues.

**Comment by EsserGaming** [comment]
I apologize, I tried it on stable and it works fine. I was on Nightly, apologies! I still don't know if it is a tea speak issue or the egg

**Comment by EsserGaming** [comment]
Here is a image of the console on latest nightly:
![image](https://user-images.githubusercontent.com/36900138/116486767-fb7da700-a853-11eb-85d4-1256dec719ba.png)

**Comment by parkervcp** [comment]
It looks like they shipped a bad lib file as it's supposed to be in their download. I only support their stable builds.
