### ISSUE TITLE
Code-Server terminal can't install it's own packages

### ISSUE THREAD

**Issue by VasilisThePikachu** [parkervcp/eggs#1130]
Panel Version: 1.4.0
Daemon Version: 1.4.0
Service: Code-Server
Modified: yes (added --link at the end of the startup command)

Expected Behavior: commands like `apt install` successfully install packages

Actual Behavior: commands like `apt install` fail cause you don't have permissions

Steps to Reproduce: 
1: connect to your server
2: open a terminal in a new project
3: attempt to use commands in the terminal like `apt install` `sudo` and trying to switch to superuser with `su`

I don't know if this is possible to fix (or if something is wrong with my installation) but being able to use `pip` to install python packages or install other coding languages is pretty important to have for an ide

**Comment by parkervcp** [comment]
there is no privilege escalation in the containers. They get loaded read only so you can't install things anyways.

If you need something installed you can build a custom image to run the server.
