### ISSUE TITLE
VS Code Server Bug

### ISSUE THREAD

**Issue by MCBoos** [parkervcp/eggs#1131]
Panel Version: 1.3.1
Daemon Version:  1.3.2
Service: /software/code-server
Modified: no

Expected Behavior:

I expect to be able to compile normally, but because I have too many files, an error is reported. I want to try to modify the container, but I don't have the password of the root user

Actual Behavior:

Error: ENOSPC: System limit for number of file watchers reached, watch

Steps to Reproduce: (Step by step what to do to cause the issue)

I made a mistake while compiling my Vue project

**Comment by MCBoos** [comment]
![image](https://user-images.githubusercontent.com/12481285/116795167-86d19380-ab05-11eb-8cb5-8b13251a8596.png)

**Comment by MCBoos** [comment]
![image](https://user-images.githubusercontent.com/12481285/116795183-981aa000-ab05-11eb-8b17-6d368456f728.png)

**Comment by parkervcp** [comment]
You can't escalate priviledge in the container.

Change the file limits on your host.

**Comment by MCBoos** [comment]
> You can't escalate priviledge in the container.
> 
> Change the file limits on your host.

Change the file limits

> You can't escalate priviledge in the container.
> 
> Change the file limits on your host.

please tell me, how to Change the file limits?please  T_T

**Comment by BossDaily** [comment]
The file limit was changed on the host but after a few weeks the error popped up again
