### ISSUE TITLE
fivem - Error when installing 

### ISSUE THREAD

**Issue by idpt-stds** [parkervcp/eggs#1133]
Panel Version: 1.4.0
Daemon Version: 1.4.1
Service: Fivem
Modified: no

Expected Behavior: Install & run FiveM server 

Actual Behavior:

[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
/entrypoint.sh: line 12: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: No such file or directory

Steps to Reproduce: (Step by step what to do to cause the issue)
1. Create new nest
2. Add fiveM egg
3. Create server
4. Inserts required info
5. Starting server
6. Error

**Comment by parkervcp** [comment]
Please get the install logs.

**Comment by idpt-stds** [comment]
> Please get the install logs.

I didn’t get anything in my logs directory.

**Comment by parkervcp** [comment]
there are install logs. you may need to look around for them.

**Comment by idpt-stds** [comment]
Where would they be located?

**Comment by idpt-stds** [comment]
> there are install logs. you may need to look around for them.

If you mean the exit code it is 127.

**Comment by parkervcp** [comment]
in general this should get the latest install log.

`tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptdl.co 99`

**Comment by idpt-stds** [comment]
> in general this should get the latest install log.
> 
> `tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/ */ /g' | cut -s -d' ' -f9) | nc bin.ptdl.co 99`

Nothing happens when I try to run it in the console.

**Comment by idpt-stds** [comment]
I had entered an extra character at the download link, and it now works.
