### ISSUE TITLE
Filestash

### ISSUE THREAD

**Issue by DylanGS9** [parkervcp/eggs#1134]
Service: File Manager/Service.

Does this expand an already existing service: No

Link to game: https://www.filestash.app/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page: https://www.filestash.app/docs/install-and-upgrade/

Links for install steps/docs:

curl -O https://downloads.filestash.app/latest/docker-compose.yml
docker-compose up -d

**Comment by parkervcp** [comment]
> curl -O https://downloads.filestash.app/latest/docker-compose.yml
> docker-compose up -d

This is not a standalone install. It uses 2 images as far as I know.

**Comment by parkervcp** [comment]
Yeah this is going to be a no from me. It would take a ton of work to potentially get this into a single container.
