### ISSUE TITLE
Discord.py Egg not working 

### ISSUE THREAD

**Issue by PyDevs-Deutschland** [parkervcp/eggs#1138]
I installed and imported the Egg for Discord.py and I got my "bot.py" File uploaded but when  I start it, it only starts the Python Console and not the Script
<img src="https://i.imgur.com/9vv2jEY.png">

**Comment by parkervcp** [comment]
This looks a whole lot your not started you just missed most of the start messaging.

If you refresh the page it will pull more of the startup.

**Comment by PyDevs-Deutschland** [comment]
<img src="https://i.imgur.com/7GaBjos.png">

**Comment by PyDevs-Deutschland** [comment]
Is this better?

**Comment by parkervcp** [comment]
that looks like it's just starting the python cli interface. The `>>>` is usually that.

**Comment by PyDevs-Deutschland** [comment]
Yes but I want to start the Script and not the python Console

**Comment by PyDevs-Deutschland** [comment]
I got it working thx
