### ISSUE TITLE
Bastion

### ISSUE THREAD

**Issue by Matthww** [parkervcp/eggs#114]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.10
Daemon Version: 0.6.8
Service: Bastion
Modified: no

Expected Behavior: Bastion starting up normally

Actual Behavior: On a clean bastion install it's outputting this error:
[Pterodactyl Daemon] A fatal error was encountered while starting this server.

Steps to Reproduce: (Step by step what to do to cause the issue)
Import the egg, restart the daemon and create a bastion server

**Comment by Sir3lit** [comment]
You need to get us logs. For us to help you. This tells us nothing

What else does the console say when it's start?

**Comment by Matthww** [comment]
I had to restart the server for something else and now everything is working...

**Comment by Sir3lit** [comment]
If you would've restarted the daemon like it says everywhere. You wouldn't of had this issue

**Comment by Matthww** [comment]
I did already restart the daemon like I said in the steps to reproduce.
