### ISSUE TITLE
Update java version

### ISSUE THREAD

**Issue by EsserGaming** [parkervcp/eggs#1144]
Service: minecraft

Does this expand an already existing service: Y

Link to game: https://www.minecraft.net

Links for server downloads: https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a

Links for install steps/docs: No links, just a update 😄

**Comment by parkervcp** [comment]
There is already a java 16 image. Once the full release is out or announced I will update the egg.

**Comment by EsserGaming** [comment]
I would prefer to have it now, but since it isn't required so I can see why you wont want it public yet. (If you don't mind can I have the updated image?)

**Comment by TASelwyn** [comment]
> I would prefer to have it now, but since it isn't required so I can see why you wont want it public yet. (If you don't mind can I have the updated image?)

quay.io/parkervcp/pterodactyl-images:debian_openjdk-16

**Comment by EsserGaming** [comment]
Thank you
