### ISSUE TITLE
Request: AzuraCast

### ISSUE THREAD

**Issue by Jelcoo** [parkervcp/eggs#1145]
Service: AzuraCast

Does this expand an already existing service: N

Link to game: https://www.azuracast.com/

Links for server downloads: https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh

Links for install steps/docs: https://docs.azuracast.com/en/getting-started/installation/docker

**Comment by gOOvER** [comment]
Ptero is not designed to host this. Docker install means not that it's compatible with Ptero.

**Comment by parkervcp** [comment]
Duplicate of #953
