### ISSUE TITLE
Sinusbot Scripts

### ISSUE THREAD

**Issue by masterhacka** [parkervcp/eggs#1146]
Hi there,

I am using the Sinusbot egg on Pterodactyl. So far so good but the issue is, when I am trying to paste the following Script to the scripts folder and restart Sinusbot, it does not show up: https://github.com/Support-pp/Support-pp/releases/tag/2.6.4

Please help

**Comment by parkervcp** [comment]
are you going to share any startup here. It looks like it's just nodejs and should just load.

**Comment by masterhacka** [comment]
It was just an issue when enabling discord instances. The Script is for ts. Can be closed here thanks!
