### ISSUE TITLE
Ark: Survival Evolved Not Working

### ISSUE THREAD

**Issue by ElectroGamesYT** [parkervcp/eggs#1151]
Panel Version: 1.4.1
Daemon Version: 1.4.1
Service: Ark: Survival Evolved
Modified: No

Expected Behavior:
Allow players to join the ARK Servers

Actual Behavior:
ARK located the server and shows that it is online but when I join the server it says "Connection Timeout"
Right before the server starts, it says this in the console.
`waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
read tcp 127.0.0.1:57034->127.0.0.1:27020: i/o timeout
waiting for rcon connection...
Waiting commands for 127.0.0.1:27020 (or type :q to exit)
container@pterodactyl~ Server marked as running...`
And yes, I did allocate all of the required ports to my servers.

Steps to Reproduce: (Step by step what to do to cause the issue)
Create an ARK server and try to join it.

**Comment by parkervcp** [comment]
Your server was marked as running. The server is started. There's no issues I see here.

**Comment by ElectroGamesYT** [comment]
> Your server was marked as running. The server is started. There's no issues I see here.

I thought this egg was to host a server for players to join though? What do I need to allow players to join the server?

**Comment by parkervcp** [comment]
The logs you provided show nothing. From the looks of it though you should be okay.

**Comment by skytek73** [comment]
i get the same thing connection timed out

**Comment by KuebelHund** [comment]
same Problem here, tried many methods, like manually adjusting iptables and stuff, but nothing worked so far. My Server seems to not even notice, when someone is trying to join. CPU load is at a steady 15 - 17% and RAM Usage at steady 7,7 gigs. Nothing changes in terms of server resource usage, when i am trying to connect. Same Problem with some of my friends as well. Noone can connect to my Server at all and im out of ideas right now.

**Comment by parkervcp** [comment]
You need to allocate all the ports required for the server, of which there are three. From my experience this is the most common issue we have.

**Comment by RoverDevelopment** [comment]
i get the same thing
there all allowed

**Comment by parkervcp** [comment]
Can you all validate what ports you have allocated on the server?

**Comment by parkervcp** [comment]
If you allocate `26508` as the primary you need to allocate `26509` as well.

**Comment by tyler72us** [comment]
Not to necro an old issue, but why does `26508` and 26509 both need allocated?

**Comment by QuintenQVD0** [comment]
> Not to necro an old issue, but why does `26508` and 26509 both need allocated?

Thats how the game wants it. 
Read the readme.
And do not use old issues for this!
