### ISSUE TITLE
JupyterLab

### ISSUE THREAD

**Issue by VirtualHorror** [parkervcp/eggs#1152]
Service: JuypterLab

Does this expand an already existing service: N

Link to service: https://jupyter.org/

Links for server downloads: https://jupyter.org/install

Links for install steps/docs: https://jupyterlab.readthedocs.io/en/stable/getting_started/overview.html
                                            https://jupyter.org/documentation

**Comment by parkervcp** [comment]
This might actually be doable with the discordpy egg already as you can use pip to install it.
