### ISSUE TITLE
Web server (LEMP example) request

### ISSUE THREAD

**Issue by TOWUK** [parkervcp/eggs#1153]
Service: simple box with custom parameters:
**litespeed**/**apache**/**nginx**/ **apache+nginx**
**php** 7.4.x to 8.0.x (latest builds currently)
**mariaDB** 10.5 or **mysql** 8.x (only latest builds currently)
**redis** server, **sFTP**, **roundcube** with **mail server** (optional)

Does this expand an already existing service: maybe (no)

Link to game: none

Links for server downloads:
[Litespeed](https://www.litespeedtech.com/open-source)
[nginx](https://nginx.org/ru/download.html)
[Apache](https://httpd.apache.org/download.cgi)
[PHP](https://www.php.net/downloads)
[MariaDB](https://mariadb.org/download/) or [Mysql](https://dev.mysql.com/downloads/mysql/)
[proFTPd](http://www.proftpd.org/) or [pureFTPd](https://www.pureftpd.org/project/pure-ftpd/download/)

Links for install steps/docs: i am junior, sorry :(

**Comment by TOWUK** [comment]
> Service: simple box with custom parameters:
> **litespeed**/**apache**/**nginx**/ **apache+nginx**
> **php** 7.4.x to 8.0.x (latest builds currently)
> **mariaDB** 10.5 or **mysql** 8.x (only latest builds currently)
> **redis** server, **sFTP**, **roundcube** with **mail server** (optional)
> 
> Does this expand an already existing service: maybe (no)
> 
> Link to game: (Ex. minecraft.net/factorio.com/etc)
> 
> Links for server downloads:
> [Litespeed](https://www.litespeedtech.com/open-source)
> [nginx](https://nginx.org/ru/download.html)
> [Apache](https://httpd.apache.org/download.cgi)
> [PHP](https://www.php.net/downloads)
> [MariaDB](https://mariadb.org/download/) or [Mysql](https://dev.mysql.com/downloads/mysql/)
> [proFTPd](http://www.proftpd.org/) or [pureFTPd](https://www.pureftpd.org/project/pure-ftpd/download/)
> 
> Links for install steps/docs: i am junior, sorry :(

**Comment by gOOvER** [comment]
Ptero is the Wrong Panel. ;9 Search closed tickets
