### ISSUE TITLE
LavaLink Egg

### ISSUE THREAD

**Issue by rowansc1** [parkervcp/eggs#1154]
Panel Version: N/A
Daemon Version: N/A
Service: Lavalink
Modified: (yes/no) N/A

Expected Behavior: 
The panel should download Lavalink from the repo https://github.com/freyacodes/lavalink however it fetches from an outdated URL which is https://github.com/Frederikam/Lavalink/ since the user changed their name. 

Actual Behavior:
Downloads nothing from https://github.com/Frederikam/Lavalink/ since the files don't exist there

Steps to Reproduce: (Step by step what to do to cause the issue)
Install the LavaLink egg from the repo, try and install the server. Be treated by 404 not found within the files.

**Comment by rowansc1** [comment]
After some more looking into it, it looks like the repo https://github.com/freyacodes/lavalink doesn't have the lavalink.jar file in it anywhere.

**Comment by parkervcp** [comment]
Update your egg. This was resolved in #1089
