### ISSUE TITLE
curseforge-generic doesn't work anymore

### ISSUE THREAD

**Issue by JohnB17** [parkervcp/eggs#1157]
Panel Version: 1.4.1
Daemon Version: 1.4.2
Service: Minecraft curseforge-generic
Modified: no

Expected Behavior:
Installs normally
Actual Behavior:
Fails to install
Steps to Reproduce: Install the server

**Comment by parkervcp** [comment]
This is probably a pack specific error and you have provided no information other than "it doesn't work",

**Comment by JohnB17** [comment]
The error happened when I was installing The Mightiest Heroes modpack ([](https://www.curseforge.com/minecraft/modpacks/the-mightiest-heroes)) I have uploaded the error to pastebin:

Full Log: https://pastebin.com/YtqUTbx4
Just the error: https://pastebin.com/CtWf7yut

**Comment by JohnB17** [comment]
Oh never mind, just an issue with The Mightiest Heroes.

**Comment by tmunsch** [comment]
There isn't much consistency across modpacks and it's something that would be to labor intensive to resolve for every mod pack. A good rule of thumb is... if it installs the default bofa mods mod pack then it's working. If it isn't then it's probably the modpack.

**Comment by parkervcp** [comment]
with the current release it't probably around 80% of the curseforge packs. Which is probably impressive.
