### ISSUE TITLE
ATLBot - Broken

### ISSUE THREAD

**Issue by Sir3lit** [parkervcp/eggs#116]
The devs for ATLBot have updated it to require nodejs version 10, the image it uses has 8 causing the install to fail. Also `git` needs to be added to the install script, for one of the npm modules, or it will also fail to install

**Comment by Sir3lit** [comment]
That's a negative.

**Comment by parkervcp** [comment]
@Sir3lit then change it to node 10 for the install container...

**Comment by parkervcp** [comment]
Fixed by a3ed32f2bef186eaa12a6fa3759a9d8e46bbfb32
