### ISSUE TITLE
Use local dir for games

### ISSUE THREAD

**Issue by githubAlireza** [parkervcp/eggs#1161]
Panel Version: 1.41
Daemon Version: 1.4.1
Service: egg programming
Modified: yes

I want to create an egg which uses a local directory and copies and pastes from an Ubuntu OS directory to the main egg directory;
For example , the egg should copy the base files of CSGO from a directory of OS then update it to the latest version,
It takes so much less installing time also bandwidtg usage.
If I am about to use Mount option, tell me how?

**Comment by gOOvER** [comment]
Use Discord for help. Thats a BUG Tracker ;)
