### ISSUE TITLE
Docker Image Minecraft

### ISSUE THREAD

**Issue by DJKenzoDE** [parkervcp/eggs#1166]
If exist a pterodactyl /parkervcp docker Image with Java 16?

Paper Server and 1/2 plugins say that older Java Version have no Support if the New minecraft version Released

Gread work and nice greetz from Berlin.

**Comment by Software-Noob** [comment]
Add this to your egg. 

`quay.io/parkervcp/pterodactyl-images:debian_openjdk-16`
