### ISSUE TITLE
Gitlab

### ISSUE THREAD

**Issue by NgLoader** [parkervcp/eggs#1168]
Service: Gitlab

Does this expand an already existing service: N

Link to game: https://gitlab.com

Links for install steps/docs: https://docs.gitlab.com/ee/install/

My currently try:
build image: [Gitlab Image](https://github.com/NgLoader/images/tree/debian/gitlab)
egg-gitlab.json `{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v1",
        "update_url": null
    },
    "exported_at": "2021-06-03T22:44:33+02:00",
    "name": "Gitlab",
    "author": "mail@wuffy.eu",
    "description": "Iterate faster, innovate together: Our open DevOps platform is a single application for unparalleled collaboration, visibility, and development velocity.",
    "features": null,
    "images": [
        "quay.io\/ngloader\/images:debian_gitlab"
    ],
    "file_denylist": [],
    "startup": "gitlab-ee",
    "config": {
        "files": "{}",
        "startup": "{}",
        "logs": "{}",
        "stop": "^C"
    },
    "scripts": {
        "installation": {
            "script": "apt update\r\napt install -y curl\r\n\r\ncurl -s https:\/\/packages.gitlab.com\/install\/repositories\/gitlab\/gitlab-ce\/script.deb.sh | bash",
            "container": "debian:buster-slim",
            "entrypoint": "bash"
        }
    },
    "variables": []
}`

**Comment by DatMayo** [comment]
There is no way running GitLab as an egg. You need to have control over different folders on the file system, which is imho not posibile with an egg.

**Comment by MoonBarc** [comment]
> There is no way running GitLab as an egg. You need to have control over different folders on the file system, which is imho not posibile with an egg.

Perhaps the egg could have a startup script which moves all the files from the main server volume to their actual locations and then starts the server.

**Comment by DatMayo** [comment]
No, its not posibile. GitLab has to many things it depends on.

> The GitLab installation consists of setting up the following components:
> 
> Packages and dependencies.
> 
> 1. Ruby.
> 2. Go.
> 3. Node.
> 4. System users.
> 5. Database.
> 6. Redis.
> 7. GitLab.
> 8. NGINX.

**Comment by DatMayo** [comment]
@MoonBarc Is there a reason why it souldbe gitlab? I'm testing Gitea (hardcoded a lot, wich will be corrected in the near future), I'f you're interested, I can provide you that egg.

**Comment by mitchal01** [comment]
@DatMayo would you care to link the Egg ? I have been looking into this aswell.
