### ISSUE TITLE
Issue installing SCP:SL

### ISSUE THREAD

**Issue by TheCreeperCow** [parkervcp/eggs#1171]
Panel Version: 1.4.2
Daemon Version: 1.4.3
Service: SCP:SL Dedicated
Modified: No

Expected Behavior:
Installation succeeds without errors

Actual Behavior:
Installation fails citing permission error as cause

Steps to Reproduce: 1. Import egg
2. Create server with egg
3. Watch as the installation commences and eventual fails
Attaching log:
https://pastebin.com/0edmEQFt

**Comment by parkervcp** [comment]
This is a known issue. Please check discord.

**Comment by TheCreeperCow** [comment]
Sorry for commenting on closed. Where do i find the discord?

**Comment by Software-Noob** [comment]
https://discord.gg/pterodactyl

The latest steamcmd is currently experiencing issues with downloads. Temporary fix is to create `steamapps` folder and reinstall.
