### ISSUE TITLE
Killing Floor 2 Egg installation

### ISSUE THREAD

**Issue by DJKenzoDE** [parkervcp/eggs#1172]
Server Created
Server install all complete without error's

Login in Steam after that it will update/install the game but this error is shown

----------
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
ERROR! Failed to install app '232130' (Disk write failure)
'linux32/steamclient.so' -> '../.steam/sdk32/steamclient.so'
'linux64/steamclient.so' -> '../.steam/sdk64/steamclient.so'
----------

can anyone help me?

Best wishes from Berlin

**Comment by Software-Noob** [comment]
Refer to #1171
