### ISSUE TITLE
1.17 released, update Java version.

### ISSUE THREAD

**Issue by EsserGaming** [parkervcp/eggs#1174]
Service: minecraft

Does this expand an already existing service: Y

Link to game: https://www.minecraft.net

Links for server downloads: https://www.minecraft.net/en-us/article/caves---cliffs--part-i-out-today-java

Links for install steps/docs: No links, just a update 😄

**Comment by TASelwyn** [comment]
You can already add `quay.io/parkervcp/pterodactyl-images:debian_openjdk-16` 
to an egg and use java 16.

**Comment by EsserGaming** [comment]
I know, but this is for the people who don't.

**Comment by TASelwyn** [comment]
The stock eggs will be updated when there's a jdk 16 docker image in the official pterodactyl repo

**Comment by EsserGaming** [comment]
There is one already, just waiting for parker. 
https://github.com/parkervcp/eggs/issues/1144#issuecomment-840224001

**Comment by Software-Noob** [comment]
Vanilla Minecraft is the only version that currently supports java 16, with panel core eggs being handled by the Panel repository. There's a PR to add the images to them [here.](https://github.com/pterodactyl/panel/pull/3382) Additional eggs will receive new images when they support them

**Comment by Oyplap** [comment]
I also need this for paper.

**Comment by EsserGaming** [comment]
> I also need this for paper.

https://github.com/PaperMC/Paper/issues/5785
Progress on paper's 1.17 update.

**Comment by Oyplap** [comment]
> > I also need this for paper.
> 
> [PaperMC/Paper#5785](https://github.com/PaperMC/Paper/issues/5785)
> Progress on paper's 1.17 update.

I did the method above (quay.io/parkervcp/pterodactyl-images:debian_openjdk-16) and that works. Waiting for paper to release :)
