### ISSUE TITLE
Bug Report - Pocketmine MP Egg

### ISSUE THREAD

**Issue by omxpro** [parkervcp/eggs#1175]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (1 before latest)
Daemon Version: (1 before latest)
Service: (minecraft)
Modified: (no) (did you add or change things, this includes startup configs/install scripts/variables)

Expected Behavior: Starting up the MC server

Actual Behavior: not starting and giving errors

Steps to Reproduce: Make a server With bin folder start it [Pictures of error](https://cdn.discordapp.com/attachments/808235286446342192/852025288149827634/Screenshot_20210609-084911_Brave.png)

**Comment by parkervcp** [comment]
Get the install logs please.

**Comment by iamkubi** [comment]
Just installed the pocketmine egg and can confirm it works fine.

**Comment by omxpro** [comment]
this is the error from the console. 
hello, my server console show's this as an error.. i dont really know how to fix it..
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard --disable-ansi
./bin/php7/bin/php: error while loading shared libraries: /home/container/bin/php7/bin/../lib/libyaml-0.so.2: file too short
container@pterodactyl~ Server marked as offline...

**Comment by omxpro** [comment]
> Get the install logs please.

How could I get them

**Comment by omxpro** [comment]
Its empty
https://cdn.discordapp.com/attachments/808235286446342192/852030604156993556/Screenshot_20210609-091504_Brave.png

**Comment by omxpro** [comment]
@parkervcp

**Comment by Software-Noob** [comment]
Reinstall the server and type `tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptdl.co 99` in your ssh terminal to retrieve the latest install logs

**Comment by Software-Noob** [comment]
@omxpro This appears to be a stale issue. Did you resolve the problem?

**Comment by omxpro** [comment]
Nope and as it's not my hosting I cannot reinstall the server
As I don't have ssh

**Comment by parkervcp** [comment]
If you can't get logs then we can't help here @omxpro

**Comment by parkervcp** [comment]
closed because you can't get us the logs.
