### ISSUE TITLE
Minecraft Vanilla Plugin Configs Are Not Persistent Through Reboots

### ISSUE THREAD

**Issue by apcorton** [parkervcp/eggs#1182]
Panel Version: v1.0.37
Daemon Version: v1.0.15
Service: Minecraft Vanilla Egg
Modified: Yes - changed server name/description

Expected Behavior:
> Plugin config files being consistent through reboots

Actual Behavior:
> Edited plugin configs are not persistent through server instance reboots, the config files are overwritten or reset back to default. This applies to config files within /home/container/plugins/ and not server config files

Steps to Reproduce: 
> Edit config file, reboot server instance, config files are not persistent. This happens when editing through WISP file editor and also uploading the files through SFTP.

**Comment by parkervcp** [comment]
The panel edits configs on start to match variables set in the panel. That is likely the issue you are seeing. There are no plugins for vanilla minecraft.

If this is a WISP issue talk to their team.

**Comment by apcorton** [comment]
Would the configs be left alone if I select "Skip Egg Install Script" on WISP?

Apologies you're not able to answer this, hopefully I get a response from WISP soon.

Thanks

**Comment by Software-Noob** [comment]
> Would the configs be left alone if I select "Skip Egg Install Script" on WISP?
> 
> Apologies you're not able to answer this, hopefully I get a response from WISP soon.
> 
> Thanks

No, that only skips the whole install process. You would have to look into the egg configuration parser.
