### ISSUE TITLE
FiveM Server doesnt start

### ISSUE THREAD

**Issue by chaosbe** [parkervcp/eggs#1187]
Im created a new FiveM Server in my Pterodactyl Panel but there is a error.
Panel Version is 1.4.2
![image](https://user-images.githubusercontent.com/58701769/122079674-ed80e700-cdfd-11eb-8008-2d6bb80147a0.png)

**Comment by parkervcp** [comment]
Please ask in Discord before posting issues here.

I am working with the FiveM team to have a better way to get versions for downloads.

**Comment by chaosbe** [comment]
sorry im not on the discord

**Comment by chaosbe** [comment]
where i can find the invite link?

**Comment by i-eat-burgers** [comment]
> where i can find the invite link?
https://discord.gg/pterodactyl

**Comment by chaosbe** [comment]
thx
