### ISSUE TITLE
NanoLimbo

### ISSUE THREAD

**Issue by kubo6472** [parkervcp/eggs#1190]
Service: Minecraft

Does this expand an already existing service: Y

Link to game: minecraft.net

Links for server downloads: https://github.com/Nan1t/NanoLimbo/releases/latest

Links for install steps/docs: https://github.com/Nan1t/NanoLimbo#installation

**Comment by Software-Noob** [comment]
The project seems to be abandoned. You can use any of the existing Minecraft eggs with the jar

**Comment by kubo6472** [comment]
Closing in favor of #251
