### ISSUE TITLE
Mongodb; Access control is not enabled for the database.

### ISSUE THREAD

**Issue by nickdevnl** [parkervcp/eggs#1196]
---------------

Panel Version: (version number) 1.4.2
Daemon Version: (version number) 1.4.3
Service: (minecraft/factorio/etc) mongodb
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)
only password at variables
Expected Behavior:
access control should be enabled because its has no security right now
Actual Behavior:
Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
Steps to Reproduce: (Step by step what to do to cause the issue)
Just install a server with the egg and start it.

**Comment by parkervcp** [comment]
latest is not a number...

**Comment by nickdevnl** [comment]
now good?

**Comment by parkervcp** [comment]
That's fine. To note, those aren't actually the latest release... which is 1.4.4 now.

All this probably needs is a config change somewhere I assume.

**Comment by Software-Noob** [comment]
Pretty sure all this requires is `--auth` in the startup parameters?

**Comment by nickdevnl** [comment]
> Pretty sure all this requires is `--auth` in the startup parameters?

doesn't work i tried but it didn't work

**Comment by nickdevnl** [comment]
i found another way to do it
