### ISSUE TITLE
Waterfall egg

### ISSUE THREAD

**Issue by Artuto** [parkervcp/eggs#120]
Hi, so basically you need at least 2 ports to run Waterfall because you cant toggle query off, and this causes a port conflict  between the proxy port and the query port.

**Comment by parkervcp** [comment]
You only need one. The query and listen port can be the same. A fresh install is working fine with no issues.

![image](https://user-images.githubusercontent.com/1207679/49471110-4c932900-f7c9-11e8-80e5-56342b0a1844.png)
