### ISSUE TITLE
CurseForge packaging changes and problems

### ISSUE THREAD

**Issue by lancerdl** [parkervcp/eggs#1200]
Panel Version: 1.4.2
Daemon Version: 1.4.4
Service: Minecraft, CurseForge Generic, for modpack 467342 latest (Seaopolis) but possibly others
Modified: no

Expected Behavior:
When clicking the "Reinstall Server" button, it is expected that the installation completes and that a subsequent run is able to launch the server.

Actual Behavior:
The installation process is unable to find the installer: "No forge installer found moving on."
One exists, but it is in a sub-directory. In this case, /mnt/server/Seaopolis/install.sh. It is also not executable by default (644).
There may also be issues with the java parameters they require.

Steps to Reproduce:
Install the egg for "Curseforge Generic"
Create a server using this egg.
Set Modpack to: 467342
Set version to: latest
In the Manage tab, click: Install/Reinstall the server
Console output will show "No forge installer found moving on." towards the end.
Running after installation is said to have completed will end abruptly.

**Comment by gOOvER** [comment]
As i know, the Egg is not really longer supported, so this Ticket can be closed

**Comment by Software-Noob** [comment]
> As i know, the Egg is not really longer supported, so this Ticket can be closed

Parker requested this to be created

**Comment by parkervcp** [comment]
This is less a problem with curseforge, but an issue with the all the mods guys.

**Comment by QuintenQVD0** [comment]
This should have been resolved a while back with the big update of the curseforge egg
