### ISSUE TITLE
Add PurpurMC

### ISSUE THREAD

**Issue by EsserGaming** [parkervcp/eggs#1202]
Service: Purpur

Does this expand an already existing service: Yes

Link to game: https://purpur.pl3x.net

Links for server downloads: https://purpur.pl3x.net/downloads

Links for install steps/docs: Same as Paper

`I do not expect this to be added, but it would be nice.`

**Comment by parkervcp** [comment]
Am I blind or https://github.com/parkervcp/eggs/tree/master/minecraft/java/purpur ?

**Comment by EsserGaming** [comment]
I'm blind, thank you.
