### ISSUE TITLE
Minecraft - Airplane

### ISSUE THREAD

**Issue by DrakMC** [parkervcp/eggs#1203]
Service: Minecraft

Does this expand an already existing service: Y

Link to game: minecraft.net

Links for server downloads: https://ci.tivy.ca/

**Comment by parkervcp** [comment]
This offers no explanation as to what airplane is or why I should add it.

**Comment by DrakMC** [comment]
**Airplane provides performance improvements:**
**Improved entity performance** from a reduction in ticking entity behavior based on how far away they are from the player.

**Reduced GC times & frequency** from removing useless allocations, which also improves CPU performance.

**Fast raytracing** which improves performance of any entity which utilizes line of sight, mainly Villagers.

Faster crafting, reduction in uselessly loaded chunks, faster entity ticking, faster block ticking, faster bat spawning, and more!

More features about Aiplane you can find here: https://blog.airplane.gg/about/

**Comment by parkervcp** [comment]
I see no real reason to add this. We have a ton of standard server software and you specify a download url if you want to download this one.
