### ISSUE TITLE
Half-Life Dedicated Server

### ISSUE THREAD

**Issue by regulad** [parkervcp/eggs#1206]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc)

Half-Life Dedicated Server

Does this expand an already existing service: Y/N

No

Link to game: (Ex. minecraft.net/factorio.com/etc)

https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.

See install link below

Links for install steps/docs:

https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server#Installation

**Comment by parkervcp** [comment]
Maybe I am blind here - https://github.com/parkervcp/eggs/tree/master/steamcmd_servers/hlds_server

**Comment by regulad** [comment]
Oh boy, I am blind. Thanks, GitHub search!
