### ISSUE TITLE
ViaVersion as a Service

### ISSUE THREAD

**Issue by regulad** [parkervcp/eggs#1207]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc)

ViaVersion as a Service (VIAaaS)

Does this expand an already existing service: Y/N

No.

Link to game: (Ex. minecraft.net/factorio.com/etc)

Not sure what I should put here... https://minecraft.net/ I suppose?

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.

https://github.com/ViaVersion/VIAaaS

Links for install steps/docs:

https://github.com/ViaVersion/VIAaaS#setting-up-server-instance

~~Sorry about that last PR, this time I'm sure that an egg does not already exist.~~

**Comment by parkervcp** [comment]
Any of the java eggs can do this.

**Comment by regulad** [comment]
Yes, I'm aware, just would be a little bit more convenient to have a dedicated egg. I'll write my own egg and create a PR if nobody else ends up doing this.
