### ISSUE TITLE
Gitea - Testing

### ISSUE THREAD

**Issue by DatMayo** [parkervcp/eggs#1208]
Service: Gitea

Does this expand an already existing service: N

Link to game: https://gitea.io/en-us/

Links for server downloads: https://dl.gitea.io/gitea

ATTENTION: This is not a request, its an issue to test my created egg before it's pushed into the main repo

Test Egg: [egg-gi-tea.zip](https://github.com/parkervcp/eggs/files/6724261/egg-gi-tea.zip)

**Comment by DatMayo** [comment]
@mitchal01 Feel free to test and report any issues

**Comment by PrestonJude** [comment]
Ive been wanting this.. let me test this!

**Comment by Kckiller338** [comment]
Ok

**Comment by mitchal01** [comment]
I haven't had any issues with it, got busy buy going to put a reverse proxy for nginx to try the domain

**Comment by DatMayo** [comment]
> I haven't had any issues with it, got busy buy going to put a reverse proxy for nginx to try the domain
Did it work?

**Comment by mitchal01** [comment]
I'm not going to lie I tried it one night and haven't tried since but could not get it to work. I will try again later today but have been busy because of service.

**Comment by DatMayo** [comment]
Can you tell me, if there were any errors in your console or anything else?

**Comment by Theyka** [comment]
No errors with nginx proxy pass. Good work 👍

**Comment by DatMayo** [comment]
@mitchal01 any new infos?
