### ISSUE TITLE
Papermc 1.13.2

### ISSUE THREAD

**Issue by yummiesttag** [parkervcp/eggs#121]
Service: minecraft/papermc

Link to game: https://papermc.io

**Comment by Sir3lit** [comment]
Next time look please.

https://github.com/parkervcp/eggs/blob/master/minecraft_java/spigot/paper-legacy/paper-legacy.json

**Comment by DrZoddiak** [comment]
https://github.com/parkervcp/eggs/blob/master/minecraft_java/spigot/paper-spigot/egg-paper-spigot.json#L20

That one appears to link to it as well

**Comment by yummiesttag** [comment]
> https://github.com/parkervcp/eggs/blob/master/minecraft_java/spigot/paper-spigot/egg-paper-spigot.json#L20
> 
> That one appears to link to it as well

That was it thank you
