### ISSUE TITLE
Better folder structure

### ISSUE THREAD

**Issue by elias-knodel** [parkervcp/eggs#1214]
**Software** eggs are in the **software** folder.
**Storage** eggs are in the **storage** folder.
**Database** eggs are in the **database** folder.
And **Bots** are in the **bots** folder.

But **Game Eggs** are completely random distributet over the whole root of the repository.

It confuses me and also doesn't look that good. All eggs should be in their corresponding category. Like **Game Eggs** in a _games_ directory.

I would change it and make a contribution so it's more clear and better understandable.

**Comment by parkervcp** [comment]
At first the repo was games only. As people asked for other things I added extra sub-folders to organize those. As games are the main focus, keeping them up front is more in line with how I originally imagined it.

The README links to all the eggs available and is searchable.

**Comment by Software-Noob** [comment]
@parkervcp I agree that it would be easier for users to find eggs and the readme itself. Right now, users have to scroll way down, making them miss the readme.

What do you think of dumping all game eggs into its own folder? Everything would otherwise stay the same but easier to navigate.

**Comment by parkervcp** [comment]
> @parkervcp I agree that it would be easier for users to find eggs and the readme itself. Right now, users have to scroll way down, making them miss the readme.
> 
> What do you think of dumping all game eggs into its own folder? Everything would otherwise stay the same but easier to navigate.

You can update the main game readme and eggs that call the repo for files.
