### ISSUE TITLE
Elastic

### ISSUE THREAD

**Issue by VBDojnaz** [parkervcp/eggs#1216]
Service: Elastic

Does this expand an already existing service: N

Link to game: https://www.elastic.co/

Links for server downloads: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

Links for install steps/docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by FoksVHox** [comment]
Isn't ElsticSearch a paid service?

**Comment by pascal-zarrad** [comment]
@FoksVHox ElasticSearch is open sourced and licensed under a dual license model as you can see in their LICENSE.txt on their repository: https://github.com/elastic/elasticsearch/blob/master/LICENSE.txt

**Comment by pascal-zarrad** [comment]
I think if ElasticSearch is added as an egg, Kibana (and Logstash) might be added too. This would provide the core services of the Elastic Stack. Especially Kibana would be useful. 
Base versions of those three services are all free and available on GitHub.

**Comment by docimin** [comment]
> I think if ElasticSearch is added as an egg, Kibana (and maybe Logstash) might be added too. This would provide the core services of the Elastic Stack. Especially Kibana would be useful.
> Base versions of those three services are all free and available on GitHub.

Do all three have to be installed on the same, or do you mean seperate?

**Comment by pascal-zarrad** [comment]
@docimin Seperate. Multi eggs shouldn't be created. In this official eggs repo you won't find any multi-eggs now and in the future as those are not (officially) supported.

**Comment by docimin** [comment]
I got elasticsearch working so far, just seeing if i can do it a little better and cleaner :)

**Comment by docimin** [comment]
Hey. So small update. People will need to change their max virtual memory if not set correctly.
This can be found here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode

I got the egg to work,  but i will need to change some more things.

**Comment by docimin** [comment]
Hey. So small update. People will need to change their max virtual memory if not set correctly.
This can be found here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode

@parkervcp Will this be an issue? See above

I got the egg to work,  but i will need to change some more things.

**Comment by pascal-zarrad** [comment]
@docimin Pretty common issue with Elastic and most people will have to do it. 

In my opinion I think it will be fine if it is documented in the README. Unlike game servers I think most people who use ElasticSearch know that they need ElasticSearch might now that they have to do that.

**Comment by docimin** [comment]
Alright, no worries, just a heads up. Will continue later today, i'm a bit rusty with the configuration stuff so takes me a bit lol

**Comment by HVEVB** [comment]
@docimin I very much appreciate the work you're doing :)

**Comment by docimin** [comment]
Hey @HVEVB, Do you use Elasticsearch?
If so, would you use an Egg for production use?
If also, what are your arguments that you use for your current setup?

**Comment by HVEVB** [comment]
@docimin I haven't used Elasticsearch yet, unfortunately.
