### ISSUE TITLE
Vanilla Bedrock Egg Latest Server Download Failing

### ISSUE THREAD

**Issue by empowerservers** [parkervcp/eggs#1218]
The latest version download for the Vanilla Bedrock egg is failing. The curl command appears to result in a 403 command from the Minecraft.net servers and it is therefore unable to find the correct URL to download. 

curl -sSL https://www.minecraft.net/en-us/download/server/bedrock/
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;www&#46;minecraft&#46;net&#47;en&#45;us&#47;download&#47;server&#47;bedrock&#47;" on this server.<P>
Reference&#32;&#35;18&#46;387cd117&#46;1625338631&#46;ed5dfe
</BODY>
</HTML>

**Comment by Software-Noob** [comment]
This is a user-agent problem as akamai is detecting the script to be a bot
