### ISSUE TITLE
Pls Help Me Error Vanilla Bedrock :(

### ISSUE THREAD

**Issue by BranGamer145** [parkervcp/eggs#1221]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------
This Bug? Error from Start Server.

- [ ] 
![20210704204547](https://user-images.githubusercontent.com/74217443/124385685-68f0fc80-dd09-11eb-8179-5d90653a5ef4.jpg)
This Picture

**Comment by Software-Noob** [comment]
This is solved in #1219
