### ISSUE TITLE
[Bug]: Arma3 always crashes

### ISSUE THREAD

**Issue by Indoraptor1** [parkervcp/eggs#1226]
### Panel Version

1.4.2

### Wings Version

1.4.2

### Service

Arma3

### Modified

No, I did not modify the egg

### Expected Behavior

Start the server

### Actual Behavior

[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:676ee454d9fbddce0ef322d7f975ab6c1027d5ba1427e1b9babe88376ab0f229 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:game_arma3 
[Pterodactyl Daemon]: Finished pulling Docker container image

STARTUP_ERR: Specified server binary could not be found in files!
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
[Pterodactyl Daemon]: Finished pulling Docker container image
Digest: sha256:676ee454d9fbddce0ef322d7f975ab6c1027d5ba1427e1b9babe88376ab0f229 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:game_arma3 

STARTUP_ERR: Specified server binary could not be found in files!
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

start the server

### Relevant log output

```shell
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:676ee454d9fbddce0ef322d7f975ab6c1027d5ba1427e1b9babe88376ab0f229 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:game_arma3 
[Pterodactyl Daemon]: Finished pulling Docker container image

STARTUP_ERR: Specified server binary could not be found in files!
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
[Pterodactyl Daemon]: Finished pulling Docker container image
Digest: sha256:676ee454d9fbddce0ef322d7f975ab6c1027d5ba1427e1b9babe88376ab0f229 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:game_arma3 

STARTUP_ERR: Specified server binary could not be found in files!
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

**Comment by parkervcp** [comment]
Your install failed. You need to have a user that owns the game install the server.
