### ISSUE TITLE
Conan Exiles connection issue

### ISSUE THREAD

**Issue by Okura66** [parkervcp/eggs#123]
Panel Version: 0.7.11
Daemon Version: 0.6.8
Linux(x64) 4.9.0-8-amd64
Service: Conan Exiles
Modified: yes

I replaced quay.io/exonical/pterodactyl-containers:conanexiles with quay.io/parkervcp/pterodactyl-images:wine-source that solved some problems.

Steps to Reproduce: 
Install egg on Debian9, the server is "online" but impossible to join.

Server Console → https://pastebin.com/1graXctc

**Comment by Okura66** [comment]
re-test with new install on Ubuntu 18:04 and same problem with this egg

**Comment by parkervcp** [comment]
So you are saying using the wine-source image and it worked?

**Comment by parkervcp** [comment]
This should have been a comment on the PR and not its own issue...
