### ISSUE TITLE
[Bug]: FiveM server starts but panel keeps haning on status 'starting'

### ISSUE THREAD

**Issue by stanbrug** [parkervcp/eggs#1230]
### Panel Version

1.4.2

### Wings Version

1.4.5

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

That the status goes to running when the server is running.

### Actual Behavior

The status stays on starting while everything on the server works. And console commands doent work either. This is only with 2 servers.

### Steps To Reproduce

1 I press start
2 everything start
3 the panel status is stuck on starting

**Comment by CherryBrad** [comment]
im having this issue too

**Comment by Software-Noob** [comment]
If the server is indeed running, but the status didn't change, the Panel didn't detect the text that is configured for the egg start config. 

Provide the console output when the server starts, and show your egg Start Configuration

**Comment by stanbrug** [comment]
Start configuration:
![image](https://user-images.githubusercontent.com/79198363/124813669-70144680-df65-11eb-8535-d42f4c0fb9e6.png)


Start logs:
container@pterodactyl Server marked as starting...
[ citizen-server-impl] Started resource gta_props_fivem
[    c-scripting-core] Creating script environments for mountzonah_lift
[ citizen-server-impl] Started resource mountzonah_lift
[ citizen-server-impl] Asset mz_addons/moutnz_zonah.ytd uses 40.0 MiB of physical memory.
[ citizen-server-impl] Started resource mz_addons
[ citizen-server-impl] Started resource operation_floor
[ citizen-server-impl] Started resource room_floor
[ citizen-server-impl] Started resource urgence_floor
[                 cmd] Argument count mismatch (passed 2, wanted 1)
[ citizen-server-impl] Couldn't find resource kr-Casino.
[ citizen-server-impl] Couldn't find resource kr-senoratrees.
[ citizen-server-impl] Couldn't find resource kr-Anwb.
[ citizen-server-impl] Couldn't find resource kr-TankStations.
[ citizen-server-impl] Couldn't find resource kr-VespucciExtra.
[ citizen-server-impl] Couldn't find resource Qpark.
[ citizen-server-impl] Couldn't find resource kr-SandyTrees.
[ citizen-server-impl] Started resource kr-Maskshop
[ citizen-server-impl] Couldn't find resource kr-missionrow.
[ citizen-server-impl] Started resource kr-Border
[ citizen-server-impl] Couldn't find resource HVR-CarDealer.
[ citizen-server-impl] Couldn't find resource kr-NederlandseBushokjes.
[ citizen-server-impl] Couldn't find resource kr-Prullenbak_Groen.
[ citizen-server-impl] Couldn't find resource prop_bin_12a.
[ citizen-server-impl] Couldn't find resource kr-NederlandsePaaltjes.
[ citizen-server-impl] Couldn't find resource kr-PaaltjesGroen.
[ citizen-server-impl] Started resource kr-ikea
[ citizen-server-impl] Couldn't find resource kr-BlaineCountySignals.
[ citizen-server-impl] Asset kr-stoplichten/prop_sign_road_03g.yft uses 64.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset kr-stoplichten/prop_sign_road_05za.yft uses 64.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Started resource kr-stoplichten
[ citizen-server-impl] Couldn't find resource kr-JDSports.
[ citizen-server-impl] Couldn't find resource kr-wegen.
[ citizen-server-impl] Couldn't find resource kr-Billboard.
[ citizen-server-impl] Couldn't find resource kr-Banner.
[ citizen-server-impl] Couldn't find resource kr-Banken.
[ citizen-server-impl] Started resource kr-gabz_harmony
[ citizen-server-impl] Started resource kr-HMSHOP
[ citizen-server-impl] Couldn't find resource kr-NederlandseAfzethekjes.
[ citizen-server-impl] Couldn't find resource kr-xnBahamaMamas.
[ citizen-server-impl] Couldn't find resource kr-PacificBank.
[ citizen-server-impl] Started resource kr-LegionBar
[ citizen-server-impl] Couldn't find resource kr-Politiebureau.
[ citizen-server-impl] Couldn't find resource kr-prison.
[ citizen-server-impl] Couldn't find resource kr-prisonextras.
[ citizen-server-impl] Couldn't find resource kr-CityHall.
[ citizen-server-impl] Couldn't find resource kr-PolitieBureauLift.
[ citizen-server-impl] Couldn't find resource kr-courthouse.
[ citizen-server-impl] Couldn't find resource kr-KmarTrainingfield.
[ citizen-server-impl] Couldn't find resource kr-GunShopReskin.
[ citizen-server-impl] Asset kr-Modernhous/modernhouse1.ytd uses 23.2 MiB of physical memory.
[ citizen-server-impl] Started resource kr-Modernhous
[ citizen-server-impl] Couldn't find resource kr-pd_sandy.
[ citizen-server-impl] Couldn't find resource kr-SandyDrag.
[ citizen-server-impl] Couldn't find resource kr-Jumpsfix.
[ citizen-server-impl] Couldn't find resource kr-Zieknhuis.
[ citizen-server-impl] Couldn't find resource kr-Bosque.
[ citizen-server-impl] Couldn't find resource kr-JobCnetrum.
[ citizen-server-impl] Couldn't find resource kr-Blokkenpark.
[ citizen-server-impl] Couldn't find resource kr-defensebollards.
[ citizen-server-impl] Couldn't find resource kr-removebarricades.
[ citizen-server-impl] Couldn't find resource NL_Paaltjes.
[ citizen-server-impl] Asset playboy/int_mafshell.ydr uses 18.5 MiB of physical memory.
[ citizen-server-impl] Started resource playboy
[ citizen-server-impl] Started resource vlag
[ citizen-server-impl] Started resource bankmelding
[ citizen-server-impl] Couldn't find resource postal_map.
[ citizen-server-impl] Asset map-police/gabz_mrpd_txd.ytd uses 38.5 MiB of physical memory.
[ citizen-server-impl] Started resource map-police
[ citizen-server-impl] Started resource mythic_notify
[ citizen-server-impl] Started resource kr-tgm_legion
[ citizen-server-impl] Started resource paintball_map
[ citizen-server-impl] Couldn't find resource kr-guns.
[ citizen-server-impl] Couldn't find resource kr-TLG-ADS.
[ citizen-server-impl] Couldn't find resource kr-ffpsshot_aim.
[ citizen-server-impl] Started resource extra_pinautomaten
[    c-scripting-core] Creating script environments for esx_onoffduty
[ citizen-server-impl] Started resource esx_onoffduty
[    c-scripting-core] Creating script environments for esx_pawnshop
[ citizen-server-impl] Started resource esx_pawnshop
[ citizen-server-impl] Started resource brownprison
[ citizen-server-impl] Started resource esx_speedcamera
[ citizen-server-impl] Started resource brancard
[ citizen-server-impl] Couldn't find resource esx_kashacters.
[ citizen-server-impl] Started resource 4Cry_sirenes_politie
[ citizen-server-impl] Could not open logo.png for reading.
[              server] Warning: `onesync_enabled` is deprecated. Please use `onesync legacy` instead.
[              server] Authenticating server license key...
cfx> [  script:mysql-async] [mysql-async] [SUCCESS] Database server connection established.
[script:essentialmode] Performing version check against: https://api.kanersps.pw/em/version?version=6.4.2&uuid=6f2910e5-2fdf-4700-b304-9d76a4023fdd
[script:essentialmode] 
[      script:elsplus] ELS-Plus: Total ELS Resources: 5
[      script:elsplus] ELS-Plus: Checking for ELS+ Updates in 5
[          svadhesive] Server license key authentication succeeded. Welcome!
[ citizen-server-impl] server thread hitch warning: timer interval of 817 milliseconds
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [ERROR] [es_extended] An error happens for query "SELECT * FROM items : []": getaddrinfo ENOTFOUND game03.olympiahosting.nl
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_addoninventory] [570ms] SELECT * FROM items : []
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_boat] [576ms] UPDATE owned_vehicles SET `stored` = true WHERE `stored` = false AND type = ? : ["boat"]
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_society] [574ms] SELECT * FROM jobs : []
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_property] [576ms] SELECT * FROM properties : []
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_shops] [575ms] SELECT * FROM shops LEFT JOIN items ON items.name = shops.item : []
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_vehicleshop] [174ms] SELECT * FROM vehicle_categories : []
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_datastore] [174ms] SELECT * FROM datastore : []
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_addonaccount] [172ms] SELECT * FROM addon_account : []
[  script:es_extended] SCRIPT ERROR: @es_extended/server/common.lua:23: attempt to get length of a nil value (local 'result')
[  script:es_extended] > ref (@es_extended/server/common.lua:23)
[  script:es_extended] > <unknown> (@mysql-async/mysql-async.js:15543)
[  script:mysql-async] 
[  script:es_extended] es_extended: invalid job "offanwb" from table job_grades ignored!
[  script:es_extended] es_extended: invalid job "offanwb" from table job_grades ignored!
[  script:es_extended] es_extended: invalid job "offanwb" from table job_grades ignored!
[  script:es_extended] es_extended: invalid job "offanwb" from table job_grades ignored!
[  script:es_extended] es_extended: ignoring job "offambulance" due to missing job grades!
[  script:esx_society] SCRIPT ERROR: @esx_society/server/main.lua:26: attempt to index a nil value (field '?')
[  script:esx_society] > fn (@mysql-async/lib/MySQL.lua:226)
[script:essentialmode] 
[script:essentialmode] [EssentialMode] Current version: 6.4.2
[script:essentialmode] [EssentialMode] Updater version: 6.4.2
[script:essentialmode] 
[ citizen-server-impl] sync thread hitch warning: timer interval of 200 milliseconds
[ citizen-server-impl] network thread hitch warning: timer interval of 201 milliseconds
[                 cmd] Access denied for command sets.
[                 cmd] Access denied for command sets.
[script:essentialmode] [EssentialMode] Everything is nice and updated!
[script:essentialmode] 
[script:essentialmode] Advertisement: Want to have EssentialMode pre-installed on a good and affordable server host? Go to the following link: https://zap-hosting.com/EssentialMode
[ citizen-server-impl] server thread hitch warning: timer interval of 226 milliseconds
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_addonaccount] [292ms] SELECT * FROM addon_account_data WHERE account_name = ? : ["property_black_money"]
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_datastore] [294ms] SELECT * FROM datastore_data WHERE name = ? : ["society_ambulance"]
[  script:mysql-async] [MariaDB:10.5.11-MariaDB-1:10.5.11+mariafocal] [WARNING] [esx_addoninventory] [287ms] SELECT * FROM addon_inventory_items WHERE inventory_name = ? : ["property"]
[      script:elsplus] ELS-Plus: Checking for ELS+ Updates in 4
[  script:kr-dpemotes] 
[  script:kr-dpemotes] dp Emotes (kr-dpemotes) is up to date. (173)
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: 
[ citizen-server-impl] -- [server notice: hostname_rework]
[ citizen-server-impl] You don't have sv_projectName/sv_projectDesc set.
[ citizen-server-impl] These variables augment sv_hostname and fix your server name being cut off in the server list.
[ citizen-server-impl] Use `sets sv_projectName ..` and `sets sv_projectDesc ..` to set them.
[ citizen-server-impl] 
[script:linden_outlaw] [linden_outlawalert-master] Version 2.7.1 is available! You are using version 2.6.4
[ citizen-server-impl] Authenticated with Tebex: | Officiële Donatie Pagina
[      script:elsplus] ELS-Plus: Checking for ELS+ Updates in 3
[      script:elsplus] ELS-Plus: Checking for ELS+ Updates in 2
[      script:elsplus] ELS-Plus: Checking for ELS+ Updates in 1
[ citizen-server-impl] server thread hitch warning: timer interval of 539 milliseconds

**Comment by DatMayo** [comment]
```
[ citizen-server-impl] You don't have sv_projectName/sv_projectDesc set.
[ citizen-server-impl] These variables augment sv_hostname and fix your server name being cut off in the server list.
```
This would explain, why it wont work

**Comment by stanbrug** [comment]
This is with only default resources. Still the same problem
```
container@pterodactyl~ Server marked as starting...
:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
[    c-scripting-core] Creating script environments for _cfx_internal
[ citizen-server-impl] Scanning resources.
[    c-resources-core] Resource loading for Rugzakken failed:
[    c-resources-core] Could not open resource metadata file /home/container/resources//[eup]/Rugzakken/__resource.lua.
[    c-resources-core] Resource loading for VehicleObjects failed:
[    c-resources-core] Could not open resource metadata file /home/container/resources//[non-esx]/VehicleObjects/__resource.lua.
[ citizen-server-impl] Found 231 resources.
[ citizen-server-impl] Some resources have an outdated resource manifest:
[ citizen-server-impl]     - AutoMessage
[ citizen-server-impl]     - ESX_GiveCarKeys
[ citizen-server-impl]     - Elevator
[ citizen-server-impl]     - FCV
[ citizen-server-impl]     - HVR_TLG-ADS
[ citizen-server-impl]     - HVR_ffpsshot_aim
[ citizen-server-impl]     - No-NPC
[ citizen-server-impl]     - PoliceVehiclesWeaponDeleter
[ citizen-server-impl]     - SmartTrafficLights
[ citizen-server-impl]     - autokontrollit2
[ citizen-server-impl]     - chat-theme-civlifechat
[ citizen-server-impl]     - crouch
[ citizen-server-impl]     - devtools
[ citizen-server-impl]     - enablepvp
[ citizen-server-impl]     - es_admin2
[ citizen-server-impl]     - esx_addons_gcphone
[ citizen-server-impl]     - esx_cruisecontrol
[ citizen-server-impl]     - esx_drugs
[ citizen-server-impl]     - gcphone
[ citizen-server-impl]     - handsup
[ citizen-server-impl]     - kr-Carry
[ citizen-server-impl]     - kr-Hornflash
[ citizen-server-impl]     - kr-Loading
[ citizen-server-impl]     - kr-NoDriveBy
[ citizen-server-impl]     - kr-PauseMenu
[ citizen-server-impl]     - kr-Pointfinger
[ citizen-server-impl]     - kr-Ragdoll
[ citizen-server-impl]     - kr-SeatShuffle
[ citizen-server-impl]     - kr-Voertuigslot
[ citizen-server-impl]     - kr-Watermark
[ citizen-server-impl]     - kr-headid
[ citizen-server-impl]     - meos
[ citizen-server-impl]     - minimap
[ citizen-server-impl]     - new_banking
[ citizen-server-impl]     - progressBars
[ citizen-server-impl]     - vir-deathscreen
[ citizen-server-impl]     - vlag
[ citizen-server-impl] 
[ citizen-server-impl] Please update these resources.
[    c-scripting-core] Creating script environments for sessionmanager
[ citizen-server-impl] Started resource sessionmanager
[    c-scripting-core] Creating script environments for esx_bratva
[   script:esx_bratva] Error loading script server/main.lua in resource esx_bratva: @esx_bratva/server/main.lua:143: attempt to index a nil value (global 'ESX')
[   script:esx_bratva] stack traceback:
[   script:esx_bratva]  @esx_bratva/server/main.lua:143: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource esx_bratva
[                 cmd] Argument count mismatch (passed 1, wanted 2)
[    c-scripting-core] Creating script environments for mapmanager
[ citizen-server-impl] Started resource mapmanager
[    c-scripting-core] Creating script environments for chat
[ citizen-server-impl] Started resource chat
[ citizen-server-impl] Started resource spawnmanager
[   script:mapmanager] Started gametype Freeroam
[ citizen-server-impl] Started resource basic-gamemode
[    c-scripting-core] Creating script environments for hardcap
[ citizen-server-impl] Started resource hardcap
[    c-scripting-core] Creating script environments for rconlog
[ citizen-server-impl] Started resource rconlog
[          svadhesive] Authenticating server license key...
cfx> [   script:mapmanager] Started map fivem-map-skater
[ citizen-server-impl] Started resource fivem-map-skater
[          svadhesive] Server license key authentication succeeded. Welcome!
[ citizen-server-impl] Authenticated with Tebex: | Officiële Donatie Pagina
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: https://
```

**Comment by Software-Noob** [comment]
The start config and logs appear to be correct if that's what you are indeed using. Unfortunately, I can't replicate this myself. 

This would be a wings-related issue, especially if it only occurs on some of your servers, as you stated before. The egg only specifies the start config text that the Pterodactyl would be looking for to detect the server as running.  After that, it's all up to the Panel/Wings with the server status changed to running when text specified in the start config is detected.

Restart wings, and should the issue still occur consistently, consider opening a bug report on the Panel repository.

**Comment by kor3y** [comment]
Have this problem too, it happens whenever you try to start the server with alpine corrupted, no alpine, or you drag a downloaded alpine over the existing one. The server shows starting and you need to refresh to panel to have the console updated, so it is problablly not a egg problem. Sometimes you can start the server with the folder alpine not existing and it will bug, but most of the times it shows that alpine doesn't exists and just stops.

**Comment by osdaohdph** [comment]
![panel-534620200-image-5938df75-53bf-4b94-a5aa-ecf2bea9c775](https://github.com/parkervcp/eggs/assets/140257054/932f6636-54fd-420a-bb55-7fa57dd13c62)

**Comment by osdaohdph** [comment]
![image](https://github.com/parkervcp/eggs/assets/140257054/9f39ff26-fa3f-4c44-bf1e-20a69fb78aa0)
hellp me
