### ISSUE TITLE
Terraria Download links not exist anymore

### ISSUE THREAD

**Issue by pao2pao16** [parkervcp/eggs#1234]
### Panel Version

1.x.x

### Wings Version

1.x.x

### Service

terraria

### Modified

No, I did not modify the egg

### Expected Behavior

Install egg, start, play

### Actual Behavior

http://bin.ptdl.co/yo8i0

It looks like the download links of Terraria Servers are not working at this link.
https://terraria.fandom.com/wiki/Server

That is why installation is failing

### Steps To Reproduce

Step 1. Install Egg
Step 2. Create server
Step 3. Wait for install

**Comment by parkervcp** [comment]
This is not an egg issue so much as all their download links are dead. I can't fix that either.

**Comment by pao2pao16** [comment]
Perhaps a temporary egg update

https://terraria.org/

At footer, click PC Dedicated Server

This URL link will be found
https://terraria.org/api/download/pc-dedicated-server/terraria-server-1423.zip

Only for latest version.
