### ISSUE TITLE
Bug with paper-legacy

### ISSUE THREAD

**Issue by jimmyr57000** [parkervcp/eggs#124]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.11
Daemon Version: latest
Service: minecraft (paper-legacy eggs)
Modified: no

Expected Behavior:
Server not starting 

Actual Behavior:
 No server egg configuration could be located; aborting startup.

Steps to Reproduce: Start server

**Comment by parkervcp** [comment]
You need to restart your daemon after importing an egg. I call it out in several places.
