### ISSUE TITLE
[Egg Request]: Subservers

### ISSUE THREAD

**Issue by kubo6472** [parkervcp/eggs#1244]
### Service

minecraft

### Does this expand an already existing service

No

### Link to game

https://github.com/ME1312/SubServers-2

### Links for server downloads

https://www.spigotmc.org/resources/subservers-2.11264/download?version=403014

### Links for the install docs

https://github.com/ME1312/SubServers-2/wiki/How-It-Works

**Comment by parkervcp** [comment]
I am going to go with a no as this looks like something you need to manually configure across a bunch of servers.

**Comment by kubo6472** [comment]
Aight. From what I understand, those are only the options. Basic thing runs inside a folder. But from my experiments with replacing files in a velocity server on pterodactyl it tries to use bash for that, which is not there.
