### ISSUE TITLE
[Egg Request]: CloudNet

### ISSUE THREAD

**Issue by kubo6472** [parkervcp/eggs#1245]
### Service

minecraft

### Does this expand an already existing service

No

### Link to game

https://www.spigotmc.org/resources/cloudnet-v3-the-cloud-network-environment-technology.42059/

### Links for server downloads

https://www.spigotmc.org/resources/cloudnet-v3-the-cloud-network-environment-technology.42059/download?version=331885

### Links for the install docs

https://github.com/CloudNetService/CloudNet-v3/wiki

**Comment by kubo6472** [comment]
I'll expand on my today's attempt at using subservers with this simpler alternative. It's almost like sinusbot :D

**Comment by parkervcp** [comment]
Per my comment on the PR

```
This is not really conducive to pterodactyl.

It's meant to automate a lot of things pterodactyl does but on a single host and spin up/down servers.
```

**Comment by kubo6472** [comment]
The features I am then missing in pterodactyl are starting to get pretty obvious. The cross server awareness that enables to have persistent data and just spin em up, when they are needed. Something that would allow for an easy way to get a minecraft server network together. Aight, nevermind. Thanks for the consideration at least.
