### ISSUE TITLE
[Egg Request]: reposilite

### ISSUE THREAD

**Issue by shitzuu** [parkervcp/eggs#1249]
### Service

reposilite

### Does this expand an already existing service

No

### Link to game

https://reposilite.com/

### Links for server downloads

https://github.com/dzikoysk/reposilite

### Links for the install docs

https://reposilite.com/docs/install

**Comment by parkervcp** [comment]
The minecraft egg could literally run this.

**Comment by shitzuu** [comment]
Okay, I will try this 👍🏼

**Comment by parkervcp** [comment]
Even better this egg - https://github.com/parkervcp/eggs/tree/master/bots/discord/discord%20java
