### ISSUE TITLE
[Egg Request]: JetBrains TeamCity

### ISSUE THREAD

**Issue by JohnB17** [parkervcp/eggs#1251]
### Service

TeamCity

### Does this expand an already existing service

No

### Link to game

https://www.jetbrains.com/teamcity/

### Links for server downloads

https://www.jetbrains.com/teamcity/

### Links for the install docs

https://www.jetbrains.com/help/teamcity/installing-and-configuring-the-teamcity-server.html

**Comment by pascal-zarrad** [comment]
Running the TC server itself would be possible.

Running the Agents is possible too, but you would be limited to builds that do not use Docker. 
Docker in Docker is not possible with Pterodactyl. Connecting to a hosts Docker socket is possible, but I think not really a great solution.

I don't think it makes sense to implement this in the scope of an official egg as it would definitly involve security issues for the agents.

**Comment by parkervcp** [comment]
I wouldn't host this in pterodactyl, and I do all kinds of sketchy weird things while testing out stuff.
