### ISSUE TITLE
[Bug]: RedDiscordBot  

### ISSUE THREAD

**Issue by includes08** [parkervcp/eggs#1284]
### Panel Version

1.5.0

### Wings Version

1.4.6

### Service

Redbot

### Modified

No, I did not modify the egg

### Expected Behavior

Startup

### Actual Behavior

Not starting

### Steps To Reproduce

Start the server

### Relevant log output

```shell
``[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
Traceback (most recent call last):
  File "/home/container/.local/bin/redbot", line 5, in <module>
    from redbot.__main__ import main
  File "/home/container/.local/lib/python3.8/site-packages/redbot/__main__.py", line 32, in <module>
    from redbot.setup import get_data_dir, get_name, save_config
  File "/home/container/.local/lib/python3.8/site-packages/redbot/setup.py", line 49, in <module>
    instance_data = load_existing_config()
  File "/home/container/.local/lib/python3.8/site-packages/redbot/setup.py", line 46, in load_existing_config
    return json.load(fs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)``
```

**Comment by includes08** [comment]
update on #1286 

```
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
[13:23:23] INFO     Begin updating guild configs to support multiple       [red]
                    mod/admin roles                                             
           INFO     Done updating guild configs to support multiple        [red]
                    mod/admin roles                                             
           INFO     Moving shared API tokens to a custom group             [red]
[13:23:24] CRITICAL The main bot task didn't handle an exception and  [red.main]
                    has crashed                                                 
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:473 in │
│ red_exception_handler                                                        │
│ ❱ 473         red_task.result()                                              │
│ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:387 in │
│ run_bot                                                                      │
│ ❱ 387         await red.start(token, bot=True, cli_flags=cli_flags)          │
│ /home/container/.local/lib/python3.8/site-packages/redbot/core/bot.py:1048   │
│ in start                                                                     │
│ ❱ 1048         return await super().start(*args, **kwargs)                   │
│ /home/container/.local/lib/python3.8/site-packages/discord/client.py:666 in  │
│ start                                                                        │
│ ❱  666         await self.connect(reconnect=reconnect)                       │
│ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:435 in   │
│ connect                                                                      │
│ ❱ 435                         raise item.error                               │
│ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:151 in   │
│ worker                                                                       │
│ ❱ 151                 await self.ws.poll_event()                             │
│ /home/container/.local/lib/python3.8/site-packages/discord/gateway.py:582 in │
│ poll_event                                                                   │
│ ❱ 582                 raise ConnectionClosed(self.socket, shard_id=self.shar │
│       from None                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
ConnectionClosed: Shard ID 0 WebSocket closed with 4004
           WARNING  Attempting to die as gracefully as possible...    [red.main]
           INFO     Shutting down from unhandled exception            [red.main]
```

**Comment by Software-Noob** [comment]
> update on #1286
> 
> ```
> [Pterodactyl Daemon]: Finished pulling Docker container image
> :/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
> [13:23:23] INFO     Begin updating guild configs to support multiple       [red]
>                     mod/admin roles                                             
>            INFO     Done updating guild configs to support multiple        [red]
>                     mod/admin roles                                             
>            INFO     Moving shared API tokens to a custom group             [red]
> [13:23:24] CRITICAL The main bot task didn't handle an exception and  [red.main]
>                     has crashed                                                 
> ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
> │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:473 in │
> │ red_exception_handler                                                        │
> │ ❱ 473         red_task.result()                                              │
> │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:387 in │
> │ run_bot                                                                      │
> │ ❱ 387         await red.start(token, bot=True, cli_flags=cli_flags)          │
> │ /home/container/.local/lib/python3.8/site-packages/redbot/core/bot.py:1048   │
> │ in start                                                                     │
> │ ❱ 1048         return await super().start(*args, **kwargs)                   │
> │ /home/container/.local/lib/python3.8/site-packages/discord/client.py:666 in  │
> │ start                                                                        │
> │ ❱  666         await self.connect(reconnect=reconnect)                       │
> │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:435 in   │
> │ connect                                                                      │
> │ ❱ 435                         raise item.error                               │
> │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:151 in   │
> │ worker                                                                       │
> │ ❱ 151                 await self.ws.poll_event()                             │
> │ /home/container/.local/lib/python3.8/site-packages/discord/gateway.py:582 in │
> │ poll_event                                                                   │
> │ ❱ 582                 raise ConnectionClosed(self.socket, shard_id=self.shar │
> │       from None                                                              │
> ╰──────────────────────────────────────────────────────────────────────────────╯
> ConnectionClosed: Shard ID 0 WebSocket closed with 4004
>            WARNING  Attempting to die as gracefully as possible...    [red.main]
>            INFO     Shutting down from unhandled exception            [red.main]
> ```

I can't replicate this with a fresh install. Do you have custom cogs or something else that differentiates your setup?

**Comment by includes08** [comment]
> > update on #1286
> > ```
> > [Pterodactyl Daemon]: Finished pulling Docker container image
> > :/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
> > [13:23:23] INFO     Begin updating guild configs to support multiple       [red]
> >                     mod/admin roles                                             
> >            INFO     Done updating guild configs to support multiple        [red]
> >                     mod/admin roles                                             
> >            INFO     Moving shared API tokens to a custom group             [red]
> > [13:23:24] CRITICAL The main bot task didn't handle an exception and  [red.main]
> >                     has crashed                                                 
> > ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
> > │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:473 in │
> > │ red_exception_handler                                                        │
> > │ ❱ 473         red_task.result()                                              │
> > │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:387 in │
> > │ run_bot                                                                      │
> > │ ❱ 387         await red.start(token, bot=True, cli_flags=cli_flags)          │
> > │ /home/container/.local/lib/python3.8/site-packages/redbot/core/bot.py:1048   │
> > │ in start                                                                     │
> > │ ❱ 1048         return await super().start(*args, **kwargs)                   │
> > │ /home/container/.local/lib/python3.8/site-packages/discord/client.py:666 in  │
> > │ start                                                                        │
> > │ ❱  666         await self.connect(reconnect=reconnect)                       │
> > │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:435 in   │
> > │ connect                                                                      │
> > │ ❱ 435                         raise item.error                               │
> > │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:151 in   │
> > │ worker                                                                       │
> > │ ❱ 151                 await self.ws.poll_event()                             │
> > │ /home/container/.local/lib/python3.8/site-packages/discord/gateway.py:582 in │
> > │ poll_event                                                                   │
> > │ ❱ 582                 raise ConnectionClosed(self.socket, shard_id=self.shar │
> > │       from None                                                              │
> > ╰──────────────────────────────────────────────────────────────────────────────╯
> > ConnectionClosed: Shard ID 0 WebSocket closed with 4004
> >            WARNING  Attempting to die as gracefully as possible...    [red.main]
> >            INFO     Shutting down from unhandled exception            [red.main]
> > ```
> 
> I can't replicate this with a fresh install. Do you have custom cogs or something else that differentiates your setup?

Removed my message, i noticed my bot key got reset somehow. Sorry for the inconvenience. Question i have tho, is it possible to change instance names, or make a option to do so? Also how would updating work?

**Comment by includes08** [comment]
> > > > update on #1286
> > > > ```
> > > > [Pterodactyl Daemon]: Finished pulling Docker container image
> > > > :/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
> > > > [13:23:23] INFO     Begin updating guild configs to support multiple       [red]
> > > >                     mod/admin roles                                             
> > > >            INFO     Done updating guild configs to support multiple        [red]
> > > >                     mod/admin roles                                             
> > > >            INFO     Moving shared API tokens to a custom group             [red]
> > > > [13:23:24] CRITICAL The main bot task didn't handle an exception and  [red.main]
> > > >                     has crashed                                                 
> > > > ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
> > > > │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:473 in │
> > > > │ red_exception_handler                                                        │
> > > > │ ❱ 473         red_task.result()                                              │
> > > > │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:387 in │
> > > > │ run_bot                                                                      │
> > > > │ ❱ 387         await red.start(token, bot=True, cli_flags=cli_flags)          │
> > > > │ /home/container/.local/lib/python3.8/site-packages/redbot/core/bot.py:1048   │
> > > > │ in start                                                                     │
> > > > │ ❱ 1048         return await super().start(*args, **kwargs)                   │
> > > > │ /home/container/.local/lib/python3.8/site-packages/discord/client.py:666 in  │
> > > > │ start                                                                        │
> > > > │ ❱  666         await self.connect(reconnect=reconnect)                       │
> > > > │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:435 in   │
> > > > │ connect                                                                      │
> > > > │ ❱ 435                         raise item.error                               │
> > > > │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:151 in   │
> > > > │ worker                                                                       │
> > > > │ ❱ 151                 await self.ws.poll_event()                             │
> > > > │ /home/container/.local/lib/python3.8/site-packages/discord/gateway.py:582 in │
> > > > │ poll_event                                                                   │
> > > > │ ❱ 582                 raise ConnectionClosed(self.socket, shard_id=self.shar │
> > > > │       from None                                                              │
> > > > ╰──────────────────────────────────────────────────────────────────────────────╯
> > > > ConnectionClosed: Shard ID 0 WebSocket closed with 4004
> > > >            WARNING  Attempting to die as gracefully as possible...    [red.main]
> > > >            INFO     Shutting down from unhandled exception            [red.main]
> > > > ```
> > > 
> > > 
> > > I can't replicate this with a fresh install. Do you have custom cogs or something else that differentiates your setup?
> > 
> > 
> > Removed my message, i noticed my bot key got reset somehow. Sorry for the inconvenience. Question i have tho, is it possible to change instance names, or make a option to do so? Also how would updating work?
> 
> The instance name in the egg should be `pterodactyl` in the startup parameters. Updating is accomplished by performing a reinstall which would update the server.

Thanks for the clarification.

I still seem to get occasional errors and bugs tho. I think the last one might be solved with increasing tmpfs, but for the others i wouldn't have a clue.
```
[15:37:48] ERROR    ERROR: Could not install packages due to an [red.downloader]
                    EnvironmentError: [Errno 28] No space left                  
                    on device                                                   
                                                                                
                    WARNING: You are using pip version 20.2.3;                  
                    however, version 21.2.2 is available.                       
                    You should consider upgrading via the                       
                    '/usr/local/bin/python -m pip install                       
                    --upgrade pip' command.                                     
           ERROR    Something went wrong when installing the    [red.downloader]
                    following requirements: scipy                               
[15:38:04] ERROR    ERROR: Could not install packages due to an [red.downloader]
                    EnvironmentError: [Errno 28] No space left                  
                    on device     
```

**Comment by Software-Noob** [comment]
> > > > > update on #1286
> > > > > ```
> > > > > [Pterodactyl Daemon]: Finished pulling Docker container image
> > > > > :/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
> > > > > [13:23:23] INFO     Begin updating guild configs to support multiple       [red]
> > > > >                     mod/admin roles                                             
> > > > >            INFO     Done updating guild configs to support multiple        [red]
> > > > >                     mod/admin roles                                             
> > > > >            INFO     Moving shared API tokens to a custom group             [red]
> > > > > [13:23:24] CRITICAL The main bot task didn't handle an exception and  [red.main]
> > > > >                     has crashed                                                 
> > > > > ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
> > > > > │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:473 in │
> > > > > │ red_exception_handler                                                        │
> > > > > │ ❱ 473         red_task.result()                                              │
> > > > > │ /home/container/.local/lib/python3.8/site-packages/redbot/__main__.py:387 in │
> > > > > │ run_bot                                                                      │
> > > > > │ ❱ 387         await red.start(token, bot=True, cli_flags=cli_flags)          │
> > > > > │ /home/container/.local/lib/python3.8/site-packages/redbot/core/bot.py:1048   │
> > > > > │ in start                                                                     │
> > > > > │ ❱ 1048         return await super().start(*args, **kwargs)                   │
> > > > > │ /home/container/.local/lib/python3.8/site-packages/discord/client.py:666 in  │
> > > > > │ start                                                                        │
> > > > > │ ❱  666         await self.connect(reconnect=reconnect)                       │
> > > > > │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:435 in   │
> > > > > │ connect                                                                      │
> > > > > │ ❱ 435                         raise item.error                               │
> > > > > │ /home/container/.local/lib/python3.8/site-packages/discord/shard.py:151 in   │
> > > > > │ worker                                                                       │
> > > > > │ ❱ 151                 await self.ws.poll_event()                             │
> > > > > │ /home/container/.local/lib/python3.8/site-packages/discord/gateway.py:582 in │
> > > > > │ poll_event                                                                   │
> > > > > │ ❱ 582                 raise ConnectionClosed(self.socket, shard_id=self.shar │
> > > > > │       from None                                                              │
> > > > > ╰──────────────────────────────────────────────────────────────────────────────╯
> > > > > ConnectionClosed: Shard ID 0 WebSocket closed with 4004
> > > > >            WARNING  Attempting to die as gracefully as possible...    [red.main]
> > > > >            INFO     Shutting down from unhandled exception            [red.main]
> > > > > ```
> > > > 
> > > > 
> > > > I can't replicate this with a fresh install. Do you have custom cogs or something else that differentiates your setup?
> > > 
> > > 
> > > Removed my message, i noticed my bot key got reset somehow. Sorry for the inconvenience. Question i have tho, is it possible to change instance names, or make a option to do so? Also how would updating work?
> > 
> > The instance name in the egg should be `pterodactyl` in the startup parameters. Updating is accomplished by performing a reinstall which would update the server.
> 
> Thanks for the clarification.
> 
> I still seem to get occasional errors and bugs tho. I think the last one might be solved with increasing tmpfs, but for the others i wouldn't have a clue.
> ```
> [15:37:48] ERROR    ERROR: Could not install packages due to an [red.downloader]
>                     EnvironmentError: [Errno 28] No space left                  
>                     on device                                                   
>                                                                                 
>                     WARNING: You are using pip version 20.2.3;                  
>                     however, version 21.2.2 is available.                       
>                     You should consider upgrading via the                       
>                     '/usr/local/bin/python -m pip install                       
>                     --upgrade pip' command.                                     
>            ERROR    Something went wrong when installing the    [red.downloader]
>                     following requirements: scipy                               
> [15:38:04] ERROR    ERROR: Could not install packages due to an [red.downloader]
>                     EnvironmentError: [Errno 28] No space left                  
>                     on device     
> ```

The only error is for lack of space be it tmpfs or your partition. Please use Discord for configuration issues
