### ISSUE TITLE
[Egg Request]: Add jq

### ISSUE THREAD

**Issue by DeJayDev** [parkervcp/eggs#1288]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

jq is in the egg

### Actual Behavior

jq is not in the egg

### Steps To Reproduce

- `which jq`

No where.

Please add jq to `quay.io/parkervcp/pterodactyl-images:debian_openjdk-16`. I might also close this myself if it's not hard.

**Comment by Software-Noob** [comment]
Moved to https://github.com/parkervcp/images/pull/94
