### ISSUE TITLE
[Egg Request]: mastodon

### ISSUE THREAD

**Issue by Bobby99as** [parkervcp/eggs#1291]
### Service

mastodon

### Does this expand an already existing service

No

### Link to game

https://joinmastodon.org/

### Links for server downloads

https://github.com/mastodon/mastodon

### Links for the install docs

https://docs.joinmastodon.org/user/run-your-own/

**Comment by Software-Noob** [comment]
This is a full-blown website application with many different dependencies, such as web server, database, ruby, etc. This is not something that should be managed inside of Pterodactyl.
