### ISSUE TITLE
[Bug]: Re-installing a server bypasses the "file_denylist"

### ISSUE THREAD

**Issue by BlackKnight683** [parkervcp/eggs#1294]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

voice_servers/lavalink/egg-lavalink.json

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

The files should not be able ot be modified by anyone.

### Actual Behavior

Files can be edited, deleted and renamed by the user.

### Steps To Reproduce

Step 1 Add some files to the `file_denylist` of the egg
Step 2 Create a server with that egg
Step 3 Re-install the server from settings section
Step 4 Try to edit the file added in the deny list

**Comment by Software-Noob** [comment]
This is not egg related issue, panel bugs should be reported on the panel repository.
