### ISSUE TITLE
[Bug]: Parsing a file which is in denylist bugs it out

### ISSUE THREAD

**Issue by BlackKnight683** [parkervcp/eggs#1295]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

voice_servers/lavalink/egg-lavalink.json

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

You should not be able to delete/edit/rename the file.

### Actual Behavior

You are able to delete/edit/rename the file.

### Steps To Reproduce

Step 1 get the lavalink egg
Step 2 add the `application.yml` file in the denylist
Step 3 create a server and try to edit the application.yml file

**Comment by Software-Noob** [comment]
The issues on this repository are for something with the eggs themselves, not for reporting panel related issues.

Report panel issues on the panel repository instead.
