### ISSUE TITLE
[Egg Request]: Synergy mod

### ISSUE THREAD

**Issue by Zara-fox** [parkervcp/eggs#1296]
### Service

Synergy

### Does this expand an already existing service

No

### Link to game

https://store.steampowered.com/app/17520/Synergy/

### Links for server downloads

https://steamdb.info/app/17525/

### Links for the install docs

https://www.synergymod.net/Documents/Dedicated%20Servers

**Comment by parkervcp** [comment]
The steamcmd generic egg should handle this already.
