### ISSUE TITLE
[Egg Request]: FlamePaper

### ISSUE THREAD

**Issue by DrakMC** [parkervcp/eggs#1299]
### Service

Minecraft

### Does this expand an already existing service

Yes

### Link to game

Minecraft.net

### Links for server downloads

https://github.com/2lstudios-mc/FlamePaper/releases

### Links for the install docs

https://www.mc-market.org/resources/19660/

**Comment by parkervcp** [comment]
This could be as easy as just putting a download link in the minecraft or paper eggs. 

This is is also minecraft 1.8.x which I am not interested in supporting in any way.
