### ISSUE TITLE
[Bug]: Forge enchanced Stats not displaying

### ISSUE THREAD

**Issue by tindolt** [parkervcp/eggs#1303]
### Panel Version

1.4.2

### Wings Version

1.4.1

### Service

Minecraft/forge/forgeenchanced

### Modified

No, I did not modify the egg

### Expected Behavior

Ram and CPU stats to display on server running and or starting

### Actual Behavior

Does not display stats

### Steps To Reproduce

Step one, install any version of forge enchanced and create server with any parameters (test on mutliple configs)
Step two run server after install
Step three realize that stats aren't available for the running server therefore you can not monitor performance.

### Relevant log output

```shell
N/A
```

**Comment by Software-Noob** [comment]
Eggs have no control over the Docker stats. This sounds more like an issue with Docker or the panel itself. Join the Discord server and share more information because what you provided isn't enough to troubleshoot anything.
