### ISSUE TITLE
[Egg Request]:  Colony Survival

### ISSUE THREAD

**Issue by DEPSTRCZ** [parkervcp/eggs#1307]
### Service

colonysurvival/server

### Does this expand an already existing service

No

### Link to game

https://store.steampowered.com/app/366090/Colony_Survival/

### Links for server downloads

https://colonysurvival.fandom.com/wiki/Dedicated_Server

### Links for the install docs

https://colonysurvival.fandom.com/wiki/Dedicated_Server

**Comment by killertobyd** [comment]
hi @ItzDepstRT 
I have built the Egg for this and only need a tester. Since I do not have the game myself

**Comment by ItzDepstRT** [comment]
> hi @ItzDepstRT I have built the Egg for this and only need a tester. Since I do not have the game myself

okay

**Comment by killertobyd** [comment]
@ItzDepstRT  here is my Discord name   Killertobyd #5717

**Comment by EthanCostello** [comment]
Did this egg ever work? Looking for it

**Comment by QuintenQVD0** [comment]
> Did this egg ever work? Looking for it

Look in #1947
