### ISSUE TITLE
[Bug]: Eco won't start

### ISSUE THREAD

**Issue by ConanDoyl** [parkervcp/eggs#1314]
### Panel Version

1.4.2

### Wings Version

1.4.5

### Service

ECO

### Modified

No, I did not modify the egg

### Expected Behavior

After starting the server it should load some things so it starts correctly.

### Actual Behavior

After pressing start it crash

### Steps To Reproduce

Create a new Server with the ECO Egg. 
Wait until the installation is finished. 
Start the Server 

Video: https://img.dsh.gg/DSH-GW02-2K5ver5eds-24-08-2021-10-09AM.mp4

### Relevant log output

```shell
:/home/container$ export DOTNET_BUNDLE_EXTRACT_BASE_DIR=./dotnet-bundle && ./EcoServer
/entrypoint.sh: line 12:    13 Segmentation fault      (core dumped) ./EcoServer
```

**Comment by gOOvER** [comment]
#1310

**Comment by gOOvER** [comment]
fixed in Master
