### ISSUE TITLE
[Bug]: Grand Theft Auto Connected "Failed to connect to the server listing"

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1317]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

gta/gtac

### Modified

No, I did not modify the egg

### Expected Behavior

 no "connect to the server listing" failure

### Actual Behavior

:/home/container$ ./Server
Loading modules...
0/0 Modules loaded, 0 failed
Scanning resources...
Loading resources...
1 resources in the resource cache
Server is starting...
Server is now listening on port 18025 max players 32...
Starting resources...
START: Starting resource freeroam...
Cannot randomise car colour 101!
START: Resource freeroam started.
1/1 Resources loaded, 0 failed
Connecting to the masterlist...
**Failed to connect to the server listing
Connecting to the masterlist...
Failed to connect to the server listing
Connecting to the masterlist...
Failed to connect to the server listing
Connecting to the masterlist...**

### Steps To Reproduce

Step 1 create server
Step 2 wait for console output

**Comment by BenasPaulikas** [comment]
@parkervcp 

I've did docker exec -it dc6fa645-55f9-4e90-8b06-6040764d9208 bash
then `curl domainx.com` where domainx is any random domain and it works. I doubt this is DNS issue.

@Software-Noob  I've tried ./Server command inside container(docker exec..) and result is same. console output contains "Failed to connect to the server listing"

**Comment by Software-Noob** [comment]
I can't reproduce this myself. 

```
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:d0c9bf7cd93a519d5156472deacdb112ad2c6b037b638cddc1b1c9b200eb30ea 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:base_debian 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./Server
Loading modules...
0/0 Modules loaded, 0 failed
Scanning resources...
Loading resources...
1 resources in the resource cache
Server is starting...
Server is now listening on port 20012 max players 32...
Starting resources...
START: Starting resource freeroam...
Cannot randomise car colour 101!
START: Resource freeroam started.
1/1 Resources loaded, 0 failed
Connecting to the masterlist...
Connected to the server listing
SERVER LISTING: Pinging server...
container@pterodactyl~ Server marked as running...
SERVER LISTING: Successfully added server.
```

**Comment by BenasPaulikas** [comment]
@Software-Noob 

this is fresh install ? no changes ? I've even tried different fresh servers with ubuntu 18 and result is same :D

**Comment by BenasPaulikas** [comment]
Turns out it was indeed dns issue. False alarm
