### ISSUE TITLE
[Bug]: Curl SSL cert error when installing Rust server

### ISSUE THREAD

**Issue by Homosanians** [parkervcp/eggs#1328]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

 Rust Autowipe

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server without any errors

### Actual Behavior

curl can't download some data due to impossibility to establish a secure connection to a file server

### Steps To Reproduce

1. Use Proxmox OS (uname: Linux PVE1 5.11.22-3-pve #1 SMP PVE 5.11.22-7 (Wed, 18 Aug 2021 15:06:12 +0200) x86_64 GNU/Linux)
2. Install wings in it
3. Install Rust server

### Relevant log output

```shell
...

Reading state information... Done
The following additional packages will be installed:
  libasn1-8-heimdal libc6-i386 libcurl4 libgssapi-krb5-2 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3
  libkrb5support0 libldap-2.4-2 libldap-common libnghttp2-14 libpsl5
  libroken18-heimdal librtmp1 libsasl2-2 libsasl2-modules-db libsqlite3-0
  libssl1.1 libwind0-heimdal openssl
Suggested packages:
  krb5-doc krb5-user
Recommended packages:
  krb5-locales publicsuffix libsasl2-modules
The following NEW packages will be installed:
  ca-certificates curl lib32gcc1 libasn1-8-heimdal libc6-i386 libcurl4
  libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhx509-5-heimdal libk5crypto3 libkeyutils1
  libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
  libnghttp2-14 libpsl5 libroken18-heimdal librtmp1 libsasl2-2
  libsasl2-modules-db libsqlite3-0 libssl1.1 libwind0-heimdal openssl
0 upgraded, 29 newly installed, 0 to remove and 0 not upgraded.
Need to get 7373 kB of archives.
After this operation, 26.7 MB of additional disk space will be used.

...

Setting up curl (7.58.0-2ubuntu3.14) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Processing triggers for ca-certificates (20210119~18.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
steam user is not set.

Using anonymous user.

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
tar (child): steamcmd.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/mnt/install/install.sh: line 35: ./steamcmd.sh: No such file or directory
cp: cannot stat 'linux32/steamclient.so': No such file or directory
cp: cannot stat 'linux64/steamclient.so': No such file or directory

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
tar (child): steamcmd.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/mnt/install/install.sh: line 35: ./steamcmd.sh: No such file or directory
cp: cannot stat 'linux32/steamclient.so': No such file or directory
cp: cannot stat 'linux64/steamclient.so': No such file or directory
```

**Comment by Homosanians** [comment]
I tried to download http://curl.haxx.se/ca/cacert.pem to /etc/ssl/certs but it didn't change anything

**Comment by TuEye** [comment]
This is not a bug of the egg. Rather, it is a network/system error.

Apart from the fact that it is not recommended to install Docker directly on a proxmox host, I would currently suspect that the time of your host system is wrong (you can check this with the command "date" on the host). 
This means that the time in the container is also wrong and will make the verification of SSL certificates impossible. 

Since the container installed the current ca-certificates shortly before the error, it will also not be an error regarding old or missing ca certificates.

**Comment by Homosanians** [comment]
> This is not a bug of the egg. Rather, it is a network/system error.

No errors were found in journalctl log. NTP client working fine, the curl command from the install script was successfully run on the host.

![image](https://user-images.githubusercontent.com/35880220/131807136-2b036ee7-5f9d-4778-a2e4-96590c8aa4f9.png)

`/etc/network/interfaces` on the host. eno is UP, enp is DOWN

![image](https://user-images.githubusercontent.com/35880220/131807613-6d58570f-462f-4f57-bfa7-8304c21d519e.png)

**Comment by Homosanians** [comment]
The problem was a conflict between docker networking and proxmox VE. The easiest way to solve this, without adding any dirty hacks to the source code, was to create a lxc container with nesting turned on for the needs of the wings.
