### ISSUE TITLE
[Bug]: Atlas not Starting

### ISSUE THREAD

**Issue by Gizmo0320** [parkervcp/eggs#1329]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

Atlas

### Modified

No, I did not modify the egg

### Expected Behavior

To be able to start the server

### Actual Behavior

This shows up when trying to start it
`/entrypoint.sh: line 36: trap: -e: invalid signal specification
/entrypoint.sh: line 36: trap: "ctrl-c: invalid signal specification
/entrypoint.sh: line 36: trap: caught": invalid signal specification`

### Steps To Reproduce

Download the egg from this Repo and try and start it

### Relevant log output

```shell
/entrypoint.sh: line 36: trap: -e: invalid signal specification
/entrypoint.sh: line 36: trap: "ctrl-c: invalid signal specification
/entrypoint.sh: line 36: trap: caught": invalid signal specification
```

**Comment by Gizmo0320** [comment]
This also shows up 
`Signal 11 caught.
EngineCrashHandler: Signal=11`

**Comment by yesBad** [comment]
Don't report it here as it's not even PR'd yet.

**Comment by yesBad** [comment]
It is literally the reason it's not PR'd yet.
![chrome_UD5lEFBjxP](https://user-images.githubusercontent.com/87938689/132249132-d09535d3-7886-4063-b23f-3c1638991700.png)

**Comment by Software-Noob** [comment]
As yesbad mentioned above, there's no atlas egg. There's only a pending pull request, which has not been merged yet because it's not ready.
