### ISSUE TITLE
Factorio server crashes because it cannot chown

### ISSUE THREAD

**Issue by Smartjer123** [parkervcp/eggs#133]
Panel Version: 0.7.11
Daemon Version: 0.6.8
Service: factorio
Modified: no

What it shows when it crashes:

3.803 Factorio initialised
3.887 Info GlobalContext.cpp:696: Waiting for child processes to exit:
3.896 Info ServerMultiplayerManager.cpp:142: Quitting multiplayer connection.
3.904 Info ServerMultiplayerManager.cpp:699: mapTick(4294967295) changing state from(Ready) to(Closed)
3.905 Warning WriteFileGuard.cpp:86: Couldn't chown /home/container/player-data.tmp.json: Operation not permitted
3.946 Goodbye
0.000 Error Util.cpp:49: Value must be a string in property tree at ROOT.game_password

**Comment by Smartjer123** [comment]
It is set though....

**Comment by Sir3lit** [comment]
Set it as the variable in the settings, not manually in the file

**Comment by Smartjer123** [comment]
The password is only numbers I think thats the problem....

**Comment by Sir3lit** [comment]
@parkervcp this can be closed.

**Comment by waterlubber** [comment]
This appears to still be a problem -- the egg is setting game-password to `0` instead of `""`, which crashes the server, even after I manually change it back.

**Comment by Sir3lit** [comment]
Yeh it's a issue with how pterodactyl does the value and puts it a 0 instead of a blank string. Nothing can be done to really fix it.

**Comment by Sir3lit** [comment]
The only solution is to remove it as a variable for the egg itself I've already talked to the devs and they won't change it
