### ISSUE TITLE
[Bug]: Battleye Enable/Disable ARK Survival Evolved

### ISSUE THREAD

**Issue by DoktorHeisenberg** [parkervcp/eggs#1335]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

ark

### Modified

No, I did not modify the egg

### Expected Behavior

The "Battle Eye" Startup Configuration should disable BattleEye on 0 and enable it on 1 while defaulting to 1, as described in the startup settings page:

Enable BattleEye 0 to disable 1 to enable default="1"

### Actual Behavior

Setting BattleEye to 0 enables BattleEye since ?-NoBattlEye is not added to the startup command anymore. Setting it to 1, actually leads to '?-NoBattlEye' being appended at again. 

### Steps To Reproduce

Step 1: Install Ark Server
Step 2: Enable Battleye via setting it to "1" in startup settings page
Step 3: Look at the ./ShooterGameServer command that's actually being started, its actually appended by "?-NoBattlEye"

### Relevant log output

```shell
Command that has been started while BattleEye is enabled (set to 1):

./ShooterGameServer TheIsland?listen?SessionName=Sneadle spielt mit Dinos?ServerPassword=PASS?ServerAdminPassword=PASS?Port=7777?PeerPort=7778?RCONPort=27020?QueryPort=27015?RCONEnabled=True?-NoBattlEye -server -log

Command that has been started while BattleEye is disabled (set to 0):
./ShooterGameServer TheIsland?listen?SessionName=Sneadle spielt mit Dinos?ServerPassword=PASS?ServerAdminPassword=PASS?Port=7777?PeerPort=7778?RCONPort=27020?QueryPort=27015?RCONEnabled=True -server -log
```

**Comment by Software-Noob** [comment]
This was already fixed. Update the egg.
