### ISSUE TITLE
[Bug]: Space Engineers Not Installing

### ISSUE THREAD

**Issue by JaiceT** [parkervcp/eggs#1338]
### Panel Version

1.5.1

### Wings Version

1.5.1

### Service

/steamcmd_servers/space_engineers

### Modified

No, I did not modify the egg

### Expected Behavior

Install Space Engineers server and get the server online. 

### Actual Behavior

Does not install Space Engineers Server

### Steps To Reproduce

Install Egg
Start server and watch it install

### Relevant log output

```shell
Running on Debian 10.8
Current timezone: Etc/UTC
wine-6.0
steam user is not set.

Using anonymous user.

No appid set. Starting Server
First launch will throw some errors. Ignore them
:/home/container$ cd /home/container/spaceengineers/DedicatedServer64/; wine /home/container/spaceengineers/DedicatedServer64/SpaceEngineersDedicated.exe -path Z:\\home\\container\\config -noconsole -ignorelastsession
/entrypoint.sh: line 84: cd: /home/container/spaceengineers/DedicatedServer64/: No such file or directory
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
wine: cannot find L"/home/container/spaceengineers/DedicatedServer64/SpaceEngineersDedicated.exe"
```

**Comment by rowansc1** [comment]
+1 Can reproduce.

**Comment by parkervcp** [comment]
From what I can tell the appid is set in the variables. You need to get the install logs.

**Comment by JaiceT** [comment]
> From what I can tell the appid is set in the variables. You need to get the install logs.

I am attempting to get you the logs

**Comment by JaiceT** [comment]
@parkervcp here are the logs https://bin.ptdl.co/qics1/ 

I have tried with 32 and 64 still get the same error

**Comment by parkervcp** [comment]
> @parkervcp here are the logs https://bin.ptdl.co/qics1/ 
> 
> I have tried with 32 and 64 still get the same error

That is the start not the install log.

**Comment by JaiceT** [comment]
> > @parkervcp here are the logs https://bin.ptdl.co/qics1/
> > I have tried with 32 and 64 still get the same error
> 
> That is the start not the install log.

I ran this command 

tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptdl.co 99 

Is that not the correct command?

**Comment by danny6167** [comment]
The no app id message is because the source entrypoint.sh is checking for SRCDS_APPID and the space engineers egg uses APPID so it skips attempting to update and carries on trying to launch.
We would need some changes to entrypoint.sh and the egg to support automatic update because we need to handle the forced install path space engineers uses and the flag for it being windows install.

As far as this issue goes, I just tested a space engineers install and everything installed fine. Check the full setup log, you might need to grab more than the last 100 lines. Most likely your install failed for some reason, possibly disk space.

**Comment by JaiceT** [comment]
> The no app id message is because the source entrypoint.sh is checking for SRCDS_APPID and the space engineers egg uses APPID so it skips attempting to update and carries on trying to launch.
> We would need some changes to entrypoint.sh and the egg to support automatic update because we need to handle the forced install path space engineers uses and the flag for it being windows install.
> 
> As far as this issue goes, I just tested a space engineers install and everything installed fine. Check the full setup log, you might need to grab more than the last 100 lines. Most likely your install failed for some reason, possibly disk space.

I have checked the Disk space and I have 50GB set on that server, I don't think it would need more right?

**Comment by parkervcp** [comment]
> The no app id message is because the source entrypoint.sh is checking for SRCDS_APPID and the space engineers egg uses APPID so it skips attempting to update and carries on trying to launch.
> We would need some changes to entrypoint.sh and the egg to support automatic update because we need to handle the forced install path space engineers uses and the flag for it being windows install.
> 
> As far as this issue goes, I just tested a space engineers install and everything installed fine. Check the full setup log, you might need to grab more than the last 100 lines. Most likely your install failed for some reason, possibly disk space.

Other way around. Update the egg. There are many other eggs that do this right already. No editing my images for a single egg someone did wrong.

**Comment by JaiceT** [comment]
> > The no app id message is because the source entrypoint.sh is checking for SRCDS_APPID and the space engineers egg uses APPID so it skips attempting to update and carries on trying to launch.
> > We would need some changes to entrypoint.sh and the egg to support automatic update because we need to handle the forced install path space engineers uses and the flag for it being windows install.
> > As far as this issue goes, I just tested a space engineers install and everything installed fine. Check the full setup log, you might need to grab more than the last 100 lines. Most likely your install failed for some reason, possibly disk space.
> 
> Other way around. Update the egg. There are many other eggs that do this right already. No editing my images for a single egg someone did wrong.

No worries thanks!

**Comment by parkervcp** [comment]
With the responses about the appid missing though I still have at least one person where it installed fine and one that agrees this is an issue. This is a pretty small subset.

**Comment by danny6167** [comment]
> > The no app id message is because the source entrypoint.sh is checking for SRCDS_APPID and the space engineers egg uses APPID so it skips attempting to update and carries on trying to launch.
> > We would need some changes to entrypoint.sh and the egg to support automatic update because we need to handle the forced install path space engineers uses and the flag for it being windows install.
> > As far as this issue goes, I just tested a space engineers install and everything installed fine. Check the full setup log, you might need to grab more than the last 100 lines. Most likely your install failed for some reason, possibly disk space.
> 
> Other way around. Update the egg. There are many other eggs that do this right already. No editing my images for a single egg someone did wrong.

Sorry, yes, the wine image does have the ability to set the windows flag for streamcmd, I was thinking about the source image entrypoint.sh. But we do need to see if that custom forced install directory is necessary for some reason, if it is then the image will still need to be expanded.

@JaiceT Can you grab the *full* install log?

**Comment by JaiceT** [comment]
@danny6167 Sure will do later after work and post it.

**Comment by parkervcp** [comment]
Can the `${EXTRA_FLAGS}` variable not handle that?

**Comment by Software-Noob** [comment]
> Can the `${EXTRA_FLAGS}` variable not handle that?

That's only included in the install script and thus requires reinstalling to apply. The image entrypoint has a forced install directory, without the `EXTRA_FLAGS` variable or any way to change the install dir because there's never a requirement for games through steamcmd must be located in a specific folder. I've never heard of it at least.

I made a fresh install and it works fine. The appid or directory mentioned above doesn't affect the installation, only auto-updates. I will fix the auto-updates in a moment. 

@JaiceT 
 
Your issue is related to something else during the install, which most likely is simply the lack of disk space. Full install logs are required. The default log command only prints 100 lines `-n 100` which isn't enough for this, because Wine installation spams the logs.

**Comment by rowansc1** [comment]
This is @JaiceT 's logs for the installation. 

https://bin.ptdl.co/jj57q/

**Comment by Software-Noob** [comment]
> This is @JaiceT 's logs for the installation.
> 
> https://bin.ptdl.co/jj57q/

Please refer to my previous message that covers this. Provide the **full** log file. The head of the log file contains all server variables and uuid, while the tail would finish with the server being installed. It would contain thousands of lines that Wine spams.

You can reinstall and use `ls -1t /var/log/pterodactyl/install/*.log | head -1` to find the latest log file.

**Comment by JaiceT** [comment]
@Software-Noob I will pass the logs later today. but thats all there is on it. I will try again later .

**Comment by JaiceT** [comment]
@Software-Noob These are the last 100 lines of the latest log

https://bin.ptdl.co/taodx/

**Comment by JaiceT** [comment]
The game server does not start so unfortunately those are the only logs I can get you as that is the latest. 

It only happens with Space Engineers if that helps :)

**Comment by JaiceT** [comment]
Sorry you prob want this http://bin.ptdl.co/8v0pg

**Comment by parkervcp** [comment]
> Sorry you prob want this http://bin.ptdl.co/8v0pg I tried with 16GB of RAM as well just incase but its the same. 

The amount of ram allocated is generally not the issue, but the amount of disk space your boat server has left is.

**Comment by JaiceT** [comment]
@parkervcp Sorry for the late response, this has been resolved. Many thanks for the help!
