### ISSUE TITLE
[Egg Request]: BombSquad Game Server

### ISSUE THREAD

**Issue by DeathGOD7** [parkervcp/eggs#1340]
### Service

Bombsquad Server

### Does this expand an already existing service

Maybe Yes (As the game runs in Python)

### Link to game

https://www.froemling.net/apps/bombsquad

### Links for server downloads

https://files.ballistica.net/bombsquad/builds/

### Links for the install docs

https://www.froemling.net/docs/hosting-bombsquad-games

**Comment by DeathGOD7** [comment]
**Additional Notes**
Docker Image: https://github.com/alibo/bombsquad-docker
Game Written in Python

Also if you can do it for ARM64, as there is an official build for arm64 (mac).

**Comment by QuintenQVD0** [comment]
I have tryed to make an egg for it but it can not work because it needs /etc/machine-id what is not present on pterodactyl containers and not possible to make as the filesystem is read only
![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/778b637e-beab-4d39-a5f5-0c3ffb119979)
