### ISSUE TITLE
[Bug]: Purpur Egg not downloading correct server.jar

### ISSUE THREAD

**Issue by vijaypondini** [parkervcp/eggs#1342]
### Panel Version

1.6.1

### Wings Version

1.5.0

### Service

minecraft/purpur

### Modified

No, I did not modify the egg

### Expected Behavior

I expect that the install script should get the latest download of purpur jar, but it does not. This is because of purpur's v1 api going offline. I understand parker updated it with v2 api, but there is a mistake in the link itself.

### Actual Behavior

The curl it tries is this instead. And note i removed `/api` from the link because that's not there in the latest purpur api ( as mentioned above )

![image](https://user-images.githubusercontent.com/70318494/133921040-8a479250-eefb-4591-92e2-0f1f02c4bc2f.png)

It's supposed to be running curl -o server.jar https://api.pl3x.net/v2/purpur/1.17.1/latest/download

There is no `/api` before `/v2`, it wont work if there is ( try https://api.pl3x.net/api/v2/purpur/1.17.1/latest/download )

Second, the 1.17.1 $MINECRAFT_VERSION variable does not work properly. An example with the latest

![image](https://user-images.githubusercontent.com/70318494/133921097-5b7657ae-9341-4577-81b2-adbfa69837c7.png)

### Steps To Reproduce

Step 1 - simply install the purpur egg onto pterodactyl
Step 2 - try to install a server, the server jarfile will not download correctly

**Comment by parkervcp** [comment]
This worked before. So I'm assuming something changed.

**Comment by vijaypondini** [comment]
Yes, in the link there is no more `/api` before `/v2`
Im not sure about minecraft version though

**Comment by Software-Noob** [comment]
There's no such `api` before v2 in any of the paths in the install script, nor can I reproduce this issue. I can install 1.17.1 and all other versions. 

```
Chosen build is valid. Using version latest
Version being downloaded
MC Version: 1.17.1
Build: latest
running curl -o server.jar https://api.pl3x.net/v2/purpur/1.17.1/latest/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 62.2M  100 62.2M    0     0  89.8M      0 --:--:-- --:--:-- --:--:-- 89.6M
Downloading MC server.properties
```

Your screenshot looks like a completely different egg from what we have here. Please make sure that you have the latest version of the egg from this repository.

**Comment by vijaypondini** [comment]
Ok, I tested again, updated the egg and it was fine.. don't know what happened

Still, thanks anyway!
