### ISSUE TITLE
MC | FTB | Foolcraft 3

### ISSUE THREAD

**Issue by AugusDogus** [parkervcp/eggs#135]
Service: Minecraft modpack Foolcraft 3

Link to game: https://minecraft.curseforge.com/projects/foolcraft-3

Would love to contribute myself, but I'm a little bit weary on editing your FTB Revelations egg as this would be my first run at trying pterodactyl at all.

**Comment by Sir3lit** [comment]
I don't see why you could use the normal minecraft egg? Install any version the. Just delete it all and upload the correct files.? Not home to test it but in should work

**Comment by parkervcp** [comment]
@Sir3lit While true the other eggs have automated the entire install process...

The generic ftb egg is here https://github.com/parkervcp/eggs/tree/master/minecraft_java/ftb/feed-the-beast

**Comment by Sir3lit** [comment]
Also this not Not a feed the beast pack, so he can't just plugin the name and expect it to work

**Comment by parkervcp** [comment]
After looking you are correct. The Generic Forge egg is a better fit.

https://github.com/parkervcp/eggs/tree/master/minecraft_java/forge/forge-generic

**Comment by AugusDogus** [comment]
I misunderstood how these eggs were designed. Didn't realize that one could use the forge generic egg for any curse-forge pack. Thanks a ton!
