### ISSUE TITLE
[Bug]: Panel Not Pulling Private Repo

### ISSUE THREAD

**Issue by michaelrosstarr** [parkervcp/eggs#1350]
### Panel Version

1.6.2

### Wings Version

1.5.1

### Service

nodejs/discord.js

### Modified

No, I did not modify the egg

### Expected Behavior

I just wanted to know if it can pull from private repos? (The pull feature) I have put the username and the access token with access to all repo's but nothing is pulling.

### Actual Behavior

For it to pull from a private repo

### Steps To Reproduce

Step 1: Enter the github details (username and access token)
Step 2: It does not pull

**Comment by yesBad** [comment]
It works. I use it.

**Comment by yesBad** [comment]
Do you already have a **.git** folder?

**Comment by michaelrosstarr** [comment]
In the private repo?

**Comment by yesBad** [comment]
In your panel's files.

**Comment by michaelrosstarr** [comment]
I dont understand?

**Comment by michaelrosstarr** [comment]
You mean in my bot's code? the root directory?

**Comment by yesBad** [comment]
Like this ![](http://my-favourite-loli.is-having.fun/3vs9xmwpr0pv.png)

**Comment by Software-Noob** [comment]
It works with all Github repositories. You must have a git folder in the container and auto update variable set to 1. Reinstall to apply the credentials, which would generate the git folder.

**Comment by yesBad** [comment]
> It works with all Github repositories. You must have a git folder in the container and auto update variable set to 1. Reinstall to apply the credentials, which would generate the git folder.

Yep was remembering something like this, thanks for the clarification.

**Comment by michaelrosstarr** [comment]
So before it can pull, there must be a .git folder?

**Comment by yesBad** [comment]
> So before it can pull, there must be a .git folder?

Reinstall to apply the credentials, which would generate the git folder.

**Comment by michaelrosstarr** [comment]
Reinstalling the service does not create the .git folder

**Comment by Software-Noob** [comment]
I can't reproduce. Created a new server and pulled a repository successfully. Most likely you don't have the variables set.

**Comment by michaelrosstarr** [comment]
Are these the correct scopes for the access token? As far as i understand, its is the only one i need?

![210929-9X5j1j5n1m](https://user-images.githubusercontent.com/22572866/135338074-4b028da0-26a2-42ef-91a0-18abcc12591b.png)
