### ISSUE TITLE
[Bug]: Outdated minecraft vanilla bedrock server

### ISSUE THREAD

**Issue by thowitz** [parkervcp/eggs#1355]
### Panel Version

1.6.2

### Wings Version

1.5.1

### Service

minecraft/bedrock/bedrock

### Modified

No, I did not modify the egg

### Expected Behavior

Play on the server like I have been able to before

### Actual Behavior

Minecraft pe reports 

Could not connect: Outdated server!

Server version: 1.17.11.01

Quay repo also reports that the container was last updated 5 months ago

### Steps To Reproduce

Install server
Receive error

**Comment by thowitz** [comment]
Thanks for the quick response😀

Do I have to delete and then recreate the server through the pterodactyl panel or is there another way to reinstall it?

**Comment by Software-Noob** [comment]
> Thanks for the quick response😀
> 
> Do I have to delete and then recreate the server through the pterodactyl panel or is there another way to reinstall it?

Go to the settings tab and click reinstall. It will run the install script to update the server while preserving your configuration files.

![image](https://user-images.githubusercontent.com/10975908/136091704-2d092fc5-80fb-4c1f-9339-d91de6d3c9d2.png)
