### ISSUE TITLE
[Bug]: csgo endless updates

### ISSUE THREAD

**Issue by Dancbeunny98** [parkervcp/eggs#1359]
### Panel Version

1.6.2

### Wings Version

1.5.0

### Service

csgo

### Modified

No, I did not modify the egg

### Expected Behavior

The server should start after the start as it was updated last time!

### Actual Behavior

The server checks for updates every time and downloads it! What for?

### Steps To Reproduce

Updated server egg from this repository

`Warning: failed to init SDL thread priority manager: SDL not found`

### Relevant log output

```shell
container@pterodactyl~ Server marked as starting...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Warning: failed to init SDL thread priority manager: SDL not found
 Update state (0x61) downloading, progress: 67.92 (20764116851 / 30570722178)
 Update state (0x61) downloading, progress: 68.02 (20795250291 / 30570722178)
 Update state (0x61) downloading, progress: 68.17 (20839835382 / 30570722178)
 Update state (0x61) downloading, progress: 68.33 (20888326181 / 30570722178)
 Update state (0x61) downloading, progress: 68.52 (20948195853 / 30570722178)
 Update state (0x61) downloading, progress: 68.72 (21008968398 / 30570722178)
 Update state (0x61) downloading, progress: 68.91 (21065278271 / 30570722178)
```

**Comment by Software-Noob** [comment]
SDL is not your error, and it's still downloading the game update according to your logs.

**Comment by Dancbeunny98** [comment]
> SDL is not your error, and it's still downloading the game update according to your logs.

Every time I reboot the server, I pump it over to the server. My nerves are giving up.

**Comment by xMaZax** [comment]
One of me has a problem, is that the server starts checking files when updating ?

**Comment by parkervcp** [comment]
Make sure `VALIDATE` is blank.  Any value set will make it run a validate on startup.

**Comment by Software-Noob** [comment]
Closing as this is an old issue with no new developments or ways to reproduce. Feel free to open a new bug report with as much information as possible should this still be relevant.
