### ISSUE TITLE
[Bug]: arma 3 not loading mods

### ISSUE THREAD

**Issue by HeyItSloth** [parkervcp/eggs#1360]
### Panel Version

1.0.45

### Wings Version

N/A (WiSP)

### Service

Arma 3

### Modified

No, I did not modify the egg

### Expected Behavior

The modlist has been provided, and the account linked owns Arma 3. The mods download, and _should_ load the mods

### Actual Behavior

The mods are not loading.

### Steps To Reproduce

Booting the server with modlist enabled (confirmed the correct modlist due to it downloading mods)

### Relevant log output

```shell
[UPDATE]: Steam Workshop mod update check complete!
[STARTUP]: Starting server with the following startup command:
./arma3server_x64 -ip=0.0.0.0 -port=2306 -profiles=./serverprofile -bepath=./battleye -cfg=basic.cfg -config=server.cfg -mod="" -serverMod="" -noLogs
20:41:04 SteamAPI initialization failed. Steam features won't be accessible!
sh: 1: /sbin/ifconfig: not found
20:41:10 Dedicated host created.
CAppInfoCacheReadFromDiskThread took 15 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
RecordSteamInterfaceCreation (PID 2025): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 2025): SteamUtils009 / Utils
Setting breakpad minidump AppID = 107410
20:41:16 Game Port: 2306, Steam Query Port: 2307
RecordSteamInterfaceCreation (PID 2025): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 2025): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 2025): SteamNetworking005 / Networking
RecordSteamInterfaceCreation (PID 2025): SteamGameServerStats001 / GameServerStats
RecordSteamInterfaceCreation (PID 2025): STEAMHTTP_INTERFACE_VERSION002 / HTTP
RecordSteamInterfaceCreation (PID 2025): STEAMINVENTORY_INTERFACE_V002 / Inventory
RecordSteamInterfaceCreation (PID 2025): STEAMUGC_INTERFACE_VERSION010 / UGC
RecordSteamInterfaceCreation (PID 2025): STEAMAPPS_INTERFACE_VERSION008 / Apps
Arma 3 Console version 2.06.148221 x64 : port 2306
20:41:16 Host identity created.
[WISP] Server marked as ON
```

**Comment by HeyItSloth** [comment]
Thanks for the reply.

The startup command from the Admin page: 
`./{{SERVER_BINARY}} -ip=0.0.0.0 -port={{SERVER_PORT}} -profiles=./serverprofile -bepath=./battleye -cfg=basic.cfg -config=server.cfg -mod=\"{{CLIENT_MODS}}\" -serverMod=\"{{SERVERMODS}}\" {{STARTUP_PARAMS}}`

The startup page for the client:
https://prnt.sc/1w6ucjj

I downloaded the egg and imported it myself, WiSP doesn't update anything itself. I'll see if I can update it and see if that does anything. Thanks again for the quick reply

**Comment by lilkingjr1** [comment]
> I'll see if I can update it and see if that does anything.

Hmm... Likely no need... Looks like you have the latest and sounds like you did a clean install from scratch (ie. no existing Arma servers on old eggs).

Startup command looks correct; no issues.
Screenshot looks fine. Does adding a single mod to Additional Mods get it load that one mod?

**Comment by lilkingjr1** [comment]
Issue isn't present on my end btw (using vanilla Ptero; just tested), so it's likely local to you or a weird WiSP specific issue (which I hope it's not for your sake, because I would have no idea how to start troubleshooting that).

**Comment by HeyItSloth** [comment]
> Does adding a single mod to Additional Mods get it load that one mod?

I've used a couple different modlists to test it, and every time, it downloads/updates mods, but doesn't load anything. 
I should specify too, I'm running on Linux (Ubuntu) if that changes anything at all?

**Comment by lilkingjr1** [comment]
By trying “Additional Mods”, I meant the literal “Additional Mods” Startup parameter, where you can manually specify mods. Try adding a single mod ID to that (one that you already have downloaded) and make your modlist parameter blank (or just remove the modlist from your files), just to see if that works. The function that reads the modlist is also heavily involved with reading the Additional Mods (and Server Mods) parameter, so I want to see if there’s an issue there.

**Comment by HeyItSloth** [comment]
I just tried doing that, and it downloads, but still does not actually loads the mods up.

**Comment by HeyItSloth** [comment]
After a little bit more investigation, it actually seems like the issue might lie in the fact that it doesn't even load up any missions either. It constantly throws up an "error loading mission" over and over when I try to load into the server

**Comment by lilkingjr1** [comment]
> After a little bit more investigation, it actually seems like the issue might lie in the fact that it doesn't even load up any missions either. It constantly throws up an "error loading mission" over and over when I try to load into the server

That's a completely separate issue unfortunately, but is likely due to a missing mission file or misconfigured server.sqf. What's odd about your original issue is that Startup inputs are not making it to the startup command (as displayed by your logs).

Unfortunately this issue might be too difficult to troubleshoot over slow-text on GitHub, especially when it seems to be a local issue and likely not an issue with the egg. However, feel free to PM me on Discord if you'd like to screen share and chat about troubleshooting. You can find me on the Ptero Discord under the same username.

**Comment by parkervcp** [comment]
@HeyItSloth Was this resolved? I see @lilkingjr1 asked to DM them on Discord.

**Comment by lilkingjr1** [comment]
@parkervcp He never DM'd me, so I couldn't follow up or dive any deeper. But given that it's WISP and he couldn't even load a mission without mods, I have a feeling the issue was misconfiguration or something unrelated to the egg.
