### ISSUE TITLE
[Egg Request]: Storage Egg/Server

### ISSUE THREAD

**Issue by omxpro** [parkervcp/eggs#1368]
### Does this expand an already existing service

Yes/Maybe

### Link to a game or software

https://github.com/kalcaddle/kodbox

### Links for the download

https://download1581.mediafire.com/fb7s6t4r0qsg/n7rmriyg09f5wzk/kodbox-main.zip or https://bit.ly/storage-server

### Links for the install docs

https://github.com/kalcaddle/kodbox#install

**Comment by docimin** [comment]
Tell me if i'm incorrect, but this is a web page.
Host apache2/nginx and then put these files in there, it requires php 5 at least :P

**Comment by omxpro** [comment]
> Tell me if i'm incorrect, but this is a web page. Host apache2/nginx and then put these files in there, it requires php 5 at least :P

I know I can use Nginx but I want it to be a egg so everything is done by default with no effort for my host

**Comment by parkervcp** [comment]
I am not really interested in this. Hosting a webpage will be way harder than it needs to be.

To clarify, the minio egg is only cli and just a server without a gui so far as I know.
