### ISSUE TITLE
[Egg Request]: Update SAMP Egg to tail server_log.txt

### ISSUE THREAD

**Issue by Aurilau** [parkervcp/eggs#1378]
### Does this expand an already existing service

Yes

### Link to a game or software

https://sa-mp.com/

### Links for the download

http://files.sa-mp.com/samp037svr_R2-1.tar.gz

### Links for the install docs

https://team.sa-mp.com/wiki/Linux_Server.html

**Comment by DatMayo** [comment]
Can you tell me, whats the issure with the current egg?

**Comment by Aurilau** [comment]
> 
> 
> Can you tell me, whats the issure with the current egg?

It does not show the server console output correctly. it needs to show everything in server_log.txt

**Comment by parkervcp** [comment]
If you are having an issue this should have been a bug report and not a new egg request.

**Comment by Aurilau** [comment]
When i asked in the WISP discord about this SoftwareNoob asked me to make a new egg request
