### ISSUE TITLE
[Bug]: Egg-redis-6

### ISSUE THREAD

**Issue by Azurz** [parkervcp/eggs#1386]
### Panel Version

1.6.3

### Wings Version

1.5.3

### Service

Pterodactyl-Eggs/database/redis/redis-6/egg-redis-6.json

### Modified

No, I did not modify the egg

### Expected Behavior

Nothing can be done in the redis console  

### Actual Behavior

I would like to be able to run commands directly in the redis console except that I can't run the console and freezze 

### Steps To Reproduce

Nothing special I just installed egg

**Comment by Software-Noob** [comment]
Pterodactyl does not run interactive programs. It's not a bug with the egg itself. You have to use the config file or startup parameters to pass any arguments.
