### ISSUE TITLE
[Egg Request]: TeaSpeak (Not TeamSpeak)

### ISSUE THREAD

**Issue by LegacyAngel2K9** [parkervcp/eggs#1388]
### Does this expand an already existing service

No

### Link to a game or software

https://teaspeak.de/gb/

### Links for the download

https://repo.teaspeak.de/

### Links for the install docs

https://forum.teaspeak.de/index.php?threads/how-to-install-a-teaspeak-server.520/

**Comment by Software-Noob** [comment]
This already exists. Please search the repo before making egg requests
