### ISSUE TITLE
[Egg Request]: etherpad-lite

### ISSUE THREAD

**Issue by AllyPallies** [parkervcp/eggs#1389]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/ether/etherpad-lite

### Links for the download

https://github.com/ether/etherpad-lite/releases/download/1.8.14/etherpad-lite-win.zip

### Links for the install docs

https://github.com/ether/etherpad-lite#gnulinux-and-other-unix-like-systems

**Comment by parkervcp** [comment]
It looks like this could just be ran using https://github.com/parkervcp/eggs/tree/master/bots/discord/discord.js

**Comment by parkervcp** [comment]
The install script or startup may need some work but for the most part it looks like it should be all there.
