### ISSUE TITLE
[Egg Request]: taiga-docker

### ISSUE THREAD

**Issue by AllyPallies** [parkervcp/eggs#1390]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/taigaio/taiga-docker

### Links for the download

https://github.com/taigaio/taiga-docker/archive/refs/heads/master.zip

### Links for the install docs

https://github.com/taigaio/taiga-docker#start-the-application

**Comment by parkervcp** [comment]
This service uses 9 different docker containers to run. this would take more work to run in pterodactyl than is feasible.
