### ISSUE TITLE
[Egg Request]: RaceRoo.

### ISSUE THREAD

**Issue by Draxilius** [parkervcp/eggs#1392]
### Does this expand an already existing service

No

### Link to a game or software

https://game.raceroom.com/

### Links for the download

https://steamdb.info/app/354060/

### Links for the install docs

https://forum.sector3studios.com/index.php?threads/multiplayer-dedicated-how-to.687/

**Comment by gOOvER** [comment]
This is a Windows only Server

**Comment by gOOvER** [comment]
Dedicated application is only supported for Windows Vista and newer Windows Operating Systems. Linux support is being investigated

**Comment by Draxilius** [comment]
Is it not similar to an arma server as that uses steam cmd to install aswell

**Comment by Software-Noob** [comment]
> Is it not similar to an arma server as that uses steam cmd to install aswell

Steamcmd is used to download files from games on steam. It does not affect the requirements or support of the game itself.

Windows only builds can't natively run on Linux. It would require Wine to host it, if it runs under it.

**Comment by gOOvER** [comment]
> Is it not similar to an arma server as that uses steam cmd to install aswell

This is from their Homepage:

https://github.com/parkervcp/eggs/issues/1392#issuecomment-964845306

**Comment by lilkingjr1** [comment]
> Is it not similar to an arma server as that uses steam cmd to install aswell

For the record, Arma uses SteamCMD to download the ***Linux*** binary of the game server, which was made an option by the devs. Some devs don't provide a Linux executable for their server.

**Comment by QuintenQVD0** [comment]
I am closing this as it hard binds to 127.0.0.1,  does not allow to change the port.
