### ISSUE TITLE
[Bug]: TF2 Classic debian_base failure

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1393]
### Panel Version

1.5.3

### Wings Version

1.5.3

### Service

game_eggs/steamcmd_servers/team_fortress_2_classic

### Modified

No, I did not modify the egg

### Expected Behavior

no error while installing

### Actual Behavior

Nov 10 23:14:45 Ubuntu-1804-bionic-64-minimal wings[27728]: ERROR: [Nov 10 23:14:45.595] failed to create server environment during install process error=environment/docker: failed to pull "quay.io/parkervcp/pterodactyl-images:debian_base" image for server: Error response from daemon: manifest for quay.io/parkervcp/pterodactyl-images:debian_base not found: manifest unknown: manifest unknown server=6281f1a0-5db8-4020-9951-83514212af6f

### Steps To Reproduce

install egg
install server
get error

**Comment by BenasPaulikas** [comment]
Changed from 
["quay.io/parkervcp/pterodactyl-images:debian_base"]
to
["quay.io/parkervcp/pterodactyl-images:base_debian"]

and now error is:

```
 Update state (0x81) verifying update, progress: 17.03 (116186385 / 682404429)
Success! App '244310' fully installed.
'linux32/steamclient.so' -> '../.steam/sdk32/steamclient.so'
'linux64/steamclient.so' -> '../.steam/sdk64/steamclient.so'
--2021-11-10 22:32:43--  https://chapo.services/tf2c/tf2classic-2.0.1.7z
Resolving chapo.services (chapo.services)... 51.15.247.36
Connecting to chapo.services (chapo.services)|51.15.247.36|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://tf2classic.org/tf2c/tf2classic-2.0.3.zip [following]
--2021-11-10 22:32:44--  https://tf2classic.org/tf2c/tf2classic-2.0.3.zip
Resolving tf2classic.org (tf2classic.org)... 51.15.247.36
Connecting to tf2classic.org (tf2classic.org)|51.15.247.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [application/octet-stream]
Saving to: 'tf2classic.7z'

tf2classic.7z         0%[                    ]       0  --.-KB/s              
tf2classic.7z       100%[===================>]      20  --.-KB/s    in 0s      

2021-11-10 22:32:44 (4.77 MB/s) - 'tf2classic.7z' saved [20/20]


7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,24 CPUs AMD Ryzen 9 3900 12-Core Processor              (870F10),ASM,AES-NI)

Scanning the drive for archives:
1 file, 20 bytes (1 KiB)

Extracting archive: tf2classic.7z
ERROR: tf2classic.7z
tf2classic.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Is not archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```

**Comment by parkervcp** [comment]
Please switch to using the yolks repo.

**Comment by BenasPaulikas** [comment]
@parkervcp ty after using ["ghcr.io/parkervcp/yolks:debian"]

I get this after server is installed. Is this expected ?
![image](https://user-images.githubusercontent.com/6473565/141332515-851fdf13-58c6-45a3-9c31-4cc7faa1b723.png)
