### ISSUE TITLE
[Egg Request]: MCDR Egg (A daemon of the Minecraft Server)

### ISSUE THREAD

**Issue by Sam-Chai** [parkervcp/eggs#1398]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/Fallen-Breath/MCDReforged

### Links for the download

https://github.com/Fallen-Breath/MCDReforged

### Links for the install docs

https://github.com/Fallen-Breath/MCDReforged

**Comment by parkervcp** [comment]
You could have at least linked to the actual install docs...

**Comment by parkervcp** [comment]
Reading more into this the panel does most of the work and this require new images to run it. I am going to go with a no on this.
