### ISSUE TITLE
[Bug]: Specified command or file was not found for CryoFall Egg

### ISSUE THREAD

**Issue by Kickbut101** [parkervcp/eggs#1401]
### Panel Version

1.6.2

### Wings Version

1.5.0

### Service

Cryofall

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play it

### Actual Behavior

`  * You intended to execute a .NET program, but dotnet-Binaries/Server/CryoFall_Server.dll does not exist.`

### Steps To Reproduce

Changed the "Game  Server Version" variable to 1.31.8.1
Gave it 2048MB of RAM, 10000MB of HDD space

Everything else was default
Crash

### Relevant log output

```shell
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:5c55197c348f53ea3346fac56ee1a3bcc7936dd5eec9067b75c8c7caf7ee814f 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_dotnet-5 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ dotnet Binaries/Server/CryoFall_Server.dll loadOrNew
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-Binaries/Server/CryoFall_Server.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:5c55197c348f53ea3346fac56ee1a3bcc7936dd5eec9067b75c8c7caf7ee814f 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_dotnet-5 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ dotnet Binaries/Server/CryoFall_Server.dll loadOrNew
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-Binaries/Server/CryoFall_Server.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

**Comment by gOOvER** [comment]
1.) update Panel and Wings to latest
2.) you modify the startup: `dotnet-Binaries/Server/CryoFall_Server.dll` is definitiv wrong

Can be closed. not a bug

**Comment by Software-Noob** [comment]
> you modify the startup: `dotnet-Binaries/Server/CryoFall_Server.dll` is definitiv wrong

`dotnet Binaries/Server/CryoFall_Server.dll loadOrNew` is the default startup of the egg.

---

@Kickbut101 Can you please provide your install logs:

If you are on 1.0:
`tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptero.sh 99`

If you upgraded from 0.7:
`tail -n 100 $(ls -Alrt /srv/daemon/config/servers/*/install.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptero.sh 99`

**Comment by Kickbut101** [comment]
> @Kickbut101 Can you please provide your install logs:
> 
> If you are on 1.0: `tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/ */ /g' | cut -s -d' ' -f9) | nc bin.ptero.sh 99`
> 
> If you upgraded from 0.7: `tail -n 100 $(ls -Alrt /srv/daemon/config/servers/*/install.log | tail -1 | sed 's/ */ /g' | cut -s -d' ' -f9) | nc bin.ptero.sh 99`

can this at all be run through the UI or do I have to open a terminal on the pterodactyl host?

**Comment by Software-Noob** [comment]
Reinstall the server. After that, get the install logs. It will, by default, take the last 100 lines `-n 100` of your latest install logs file

**Comment by Kickbut101** [comment]
> Reinstall the server. After that, get the install logs. It will, by default, take the last 100 lines `-n 100` of your latest install logs file

Is that not what is in that link I posted?

**Comment by gOOvER** [comment]
@Kickbut101

No. a lot of lines missing

**Comment by Kickbut101** [comment]
![image](https://user-images.githubusercontent.com/16029826/142345409-95e82b8f-23fd-4f62-a6dc-31983fa67540.png)
This is what happens when I run that it just... hangs?

**Comment by Kickbut101** [comment]
Not sure what changed between last this egg was made and now, but the issue is that the startup command references the wrong spot.

Here is the directory tree created by the egg
![image](https://user-images.githubusercontent.com/16029826/142347471-48307407-f14d-4990-86fa-3874156bded8.png)


the call for the .dll to start the server was looking in /Binaries/Server/CryoFall_Server.dll when in fact it should be looking for the specified folder created that we can see above. 

Either that or there was a copy/extract command that failed during install. I never got that tail command to work, but this is the straight output from console on the install (attached)
[DirectConsoleOutput.log](https://github.com/parkervcp/eggs/files/7559724/DirectConsoleOutput.log)


Either way, there is a flaw in the egg

**Comment by gOOvER** [comment]
the last line in your log indicate, that the dl link is invalid. So pls reinstall and Post console output.

for me the egg works

**Comment by Kickbut101** [comment]
> 
> 
> the last line in your log indicate, that the dl link is invalid. So pls reinstall and Post console output.
> 
> for me the egg works

I don't see anywhere where it says the download link is bad? Can you please paste in the line you see?

What did you use for the "Game Version" Variable? I just tried it twice, once by leaving it at "Latest" and another where I changed it to "1.31.8.1" both failed.

Install logs for both:
[1.31.8.1 - ConsoleOutput.log](https://github.com/parkervcp/eggs/files/7564081/1.31.8.1.-.ConsoleOutput.log)
[Latest - ConsoleOutput.log](https://github.com/parkervcp/eggs/files/7564082/Latest.-.ConsoleOutput.log)

**Comment by Software-Noob** [comment]
Please post the logs online rather than downloadable files. I would rather not constantly download files from everyone to read logs.

The archive structure might've changed, and we'd have to ignore the parent folder instead of the contents based on your previous screenshot. Logs would confirm this. I can also test an installation later myself.

**Comment by Kickbut101** [comment]
> Please post the logs online rather than downloadable files. I would rather not constantly download files from everyone to read logs.

> The archive structure might've changed, and we'd have to ignore the parent folder based on your previous screenshot. Logs would confirm this. I can also test an installation later myself.

1.31.8.1 - https://pastebin.com/VnYEMnQN
Latest - https://pastebin.com/nv3T5nMc

**Comment by gOOvER** [comment]
add me on Discord: gOOvER#9999

i can send you a egg, which use steamcmd insteed download the Server from Github

**Comment by gOOvER** [comment]
when it work for you, i will push it to parkers repro

**Comment by Kickbut101** [comment]
I have made it work by specifically modifying the startup command. (Which obviously isn't a good work around and will break on any server update). But it sounds like you were able to verify the issue and find a fix?

**Comment by gOOvER** [comment]
i have a working egg with steamcmd

**Comment by Software-Noob** [comment]
> 1.31.8.1 - [pastebin.com/VnYEMnQN](https://pastebin.com/VnYEMnQN) Latest - [pastebin.com/nv3T5nMc](https://pastebin.com/nv3T5nMc)

Logs indicate the archive file structure has changed. So we'd have to ignore the parent folder `CryoFall_Server_v1.31.8.1` during the extraction process or change the startup parameters. The former would be cleaner in the file manager.

I don't know the difference between SteamCMD and their website, but if they offer the same server through SteamCMD, it will make auto-update easier. Right now, egg uses their website and not Github.

**Comment by gOOvER** [comment]
there is nothing different. i push the egg, when i'm back home

**Comment by parkervcp** [comment]
@Kickbut101 can you try out #1403 before I merge it?

**Comment by Kickbut101** [comment]
@parkervcp Not until much much later today. Sendit
