### ISSUE TITLE
[Egg Request]: Myth of Empires

### ISSUE THREAD

**Issue by Chillpilltv** [parkervcp/eggs#1404]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/1371580/Myth_of_Empires/

### Links for the download

steamcmd appid 1794810

### Links for the install docs

https://www.youtube.com/watch?v=Zq7sl6ifXLM
https://steamcommunity.com/app/1371580/discussions/0/3204869541726186348/

**Comment by MedGR450** [comment]
> ### Links for the download
> 
> steamcmd appid 1371580

Wrong steam ID, that's for the actual game which needs ownership to work on steamcmd. Correct ID for the dedicated server is 1794810

**Comment by Chillpilltv** [comment]
Ah my bad thanks.  Fixed it

**Comment by gOOvER** [comment]
Myth of Empire needs 10 Till 16GB RAM only for startup

**Comment by Software-Noob** [comment]
This game has been removed from Steam for legal issues. However, feel free to open this should it return.
