### ISSUE TITLE
[Egg Request]: NanoLimbo

### ISSUE THREAD

**Issue by ajgeiss0702** [parkervcp/eggs#1409]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/Nan1t/NanoLimbo

### Links for the download

https://github.com/Nan1t/NanoLimbo/releases

### Links for the install docs

https://github.com/Nan1t/NanoLimbo/blob/main/README.md

**Comment by ajgeiss0702** [comment]
Also note it looks like this was previously requested in the past, but was rejected in favor of TyphoonLimbo. Typhoon limbo hasnt gotten an update in a while, but NanoLimo is getting frequent updates now.

**Comment by NgLoader** [comment]
Working on it
