### ISSUE TITLE
[Egg Request]: Phpmyadmin

### ISSUE THREAD

**Issue by anondev-sudo** [parkervcp/eggs#1414]
### Does this expand an already existing service

No

### Link to a game or software

https://www.phpmyadmin.net/

### Links for the download

https://www.phpmyadmin.net/

### Links for the install docs

https://docs.phpmyadmin.net/en/latest/

**Comment by Software-Noob** [comment]
I am going to go with a no similar to all requests related to putting web servers into containers.

**Comment by anondev-sudo** [comment]
But why

**Comment by Software-Noob** [comment]
The answer is in many duplicates such as #1127
