### ISSUE TITLE
[Egg Request]: Website Egg (can display a website hosted in the server)

### ISSUE THREAD

**Issue by broimsuperman** [parkervcp/eggs#1421]
### Does this expand an already existing service

No

### Link to a game or software

N/A

### Links for the download

N/A

### Links for the install docs

N/A

**Comment by gOOvER** [comment]
without words :D

Ptero is not for hosting Websites :) Use existing NGINX or a Panel like HestiaCP

**Comment by yesBad** [comment]
no.

**Comment by broimsuperman** [comment]
> without words :D
> 
> Ptero is not for hosting Websites :) Use existing NGINX or a Panel like HestiaCP

This would actually help alot, and prevent people from messing up NGINX. All they'd have to do is reverse proxy, extremely beneficial too, if you wanted to deploy a website fast to test it out.

**Comment by broimsuperman** [comment]
> without words :D
> 
> Ptero is not for hosting Websites :) Use existing NGINX or a Panel like HestiaCP

(ptero can be used for virtually anything)

**Comment by gOOvER** [comment]
> > without words :D
> > Ptero is not for hosting Websites :) Use existing NGINX or a Panel like HestiaCP
> 
> (ptero can be used for virtually anything)

nope

**Comment by Boy132** [comment]
See #87. Parker said no. (and he's right)

**Comment by yesBad** [comment]
> > without words :D
> > Ptero is not for hosting Websites :) Use existing NGINX or a Panel like HestiaCP
> 
> This would actually help alot, and prevent people from messing up NGINX. All they'd have to do is reverse proxy, extremely beneficial too, if you wanted to deploy a website fast to test it out.

If they actually know how to install Pterodactyl without any installers // other bullshit, they should know how to use god damn Nginx. Also if they know how to reverse proxy, they should know how to config nginx correctly. It even has `nginx -t` to test if your Nginx config is wrong, it'll even tell what is wrong if it isn't correct. Pterodactyl is meant for **games**. bruh

**Comment by parkervcp** [comment]
Closed per my prior reasons for closing webhosting eggs
