### ISSUE TITLE
[Egg Request]: NodeRED

### ISSUE THREAD

**Issue by derrobin154** [parkervcp/eggs#1429]
### Does this expand an already existing service

No

### Link to a game or software

https://nodered.org/

### Links for the download

https://github.com/node-red/node-red

### Links for the install docs

https://nodered.org/docs/getting-started/development

**Comment by parkervcp** [comment]
The discord.js generic egg could probably run this fine without needing a standalone egg

https://github.com/parkervcp/eggs/tree/master/bots/discord/discord.js
