### ISSUE TITLE
Pterodactyl cant find config 

### ISSUE THREAD

**Issue by Dennis-8844** [parkervcp/eggs#143]
I get this error for the Bastion discord egg 
[Pterodactyl Daemon] No server egg configuration could be located; aborting startup.

Do i need a difrent startup config?

**Comment by Ethereal739** [comment]
You have to restart the daemon. Do
service wings restart

**Comment by Dennis-8844** [comment]
It starts thanks. but now i get a SQ lite error. there is no file.
but i will contact the bastion support for that

**Comment by Justman10000** [comment]
And what if you don't have root access?
