### ISSUE TITLE
[Egg Request]: myth of empires

### ISSUE THREAD

**Issue by nightmarepup** [parkervcp/eggs#1432]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1371580/Myth_of_Empires/

### Links for the download

https://store.steampowered.com/app/1371580/Myth_of_Empires/

### Links for the install docs

https://steamah.com/myth-of-empires-dedicated-server-guide/

**Comment by danny6167** [comment]
Duplicate of #1404
