### ISSUE TITLE
[Egg Request]: Darkflame Universe (Lego Universe)

### ISSUE THREAD

**Issue by MedPlex98** [parkervcp/eggs#1438]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/DarkflameUniverse/DarkflameServer

### Links for the download

https://www.darkflameuniverse.org/

### Links for the install docs

https://github.com/DarkflameUniverse/DarkflameServer

**Comment by SweptWasTaken** [comment]
It looks like DLU is just about to merge a fully-automated Docker setup PR which could be a useful starting point.

https://github.com/DarkflameUniverse/DarkflameServer/pull/90

**Comment by Software-Noob** [comment]
> It looks like DLU is just about to merge a fully-automated Docker setup PR which could be a useful starting point.
> 
> https://github.com/DarkflameUniverse/DarkflameServer/pull/90

Pterodactyl is not a portainer that runs any docker containers. There are specific requirements that are unique to pterodactyl. As such, other docker images are of no help

**Comment by SweptWasTaken** [comment]
> > It looks like DLU is just about to merge a fully-automated Docker setup PR which could be a useful starting point.
> > [DarkflameUniverse/DarkflameServer#90](https://github.com/DarkflameUniverse/DarkflameServer/pull/90)
> 
> Pterodactyl is not a portainer that runs any docker containers. There are specific requirements that are unique to pterodactyl. As such, other docker images are of no help

I know this, but creating a Docker image for Pterodactyl could be easier looking at that PR.

**Comment by Software-Noob** [comment]
> > > It looks like DLU is just about to merge a fully-automated Docker setup PR which could be a useful starting point.
> > > [DarkflameUniverse/DarkflameServer#90](https://github.com/DarkflameUniverse/DarkflameServer/pull/90)
> > 
> > Pterodactyl is not a portainer that runs any docker containers. There are specific requirements that are unique to pterodactyl. As such, other docker images are of no help
> 
> I know this, but creating a Docker image for Pterodactyl could be easier looking at that PR.

Not really as it's a different process. The install instructions are very clear. It contains multiple components that all must be built, together with a database.

However, for whatever reason it wants a privileged port under 1024 for authentication that's not supported by Pterodactyl.

**Comment by MedPlexNi** [comment]
Is there any update?

**Comment by BlueSky-fur** [comment]
Bump, any news? 👉👈

**Comment by gOOvER** [comment]
> Bump, any news? 👉👈

Looks like, noone have time to craete an egg. So NO, no news about it. Feel free to create the egg

**Comment by BlueSky-fur** [comment]
Which Project DLU or Pterodactyl?

Darkflame is still getting updates daily, and pterodactyl simply doesn't update for small stuff.

**Comment by gOOvER** [comment]
> Which Project DLU or Pterodactyl?
> 
> Darkflame is still getting updates daily, and pterodactyl simply doesn't update for small stuff its still used widely by many people, just because Matthew doesn't do anything doesn't mean its dead.

hahaha, i love you :D 

Only looked at the releases page :D 
When i have some time  on weekend, i'll take a look into it :)

**Comment by QuintenQVD0** [comment]
there latest release is from 2021 but there are cli builds but you need a github token to download those. I have some time rn, I see what I can do

**Comment by QuintenQVD0** [comment]
wait this can not work

`If everything has been configured correctly you should now be able to run the MasterServer binary which is located in the build directory. Darkflame Universe utilizes port numbers under 1024, so under Linux you either have to give the AuthServer binary network permissions or run it under sudo. To give AuthServer network permissions and not require sudo, run the following command`

**Comment by QuintenQVD0** [comment]
I will have to close this for that reason

**Comment by RogueRaiden** [comment]
That port requirement blows, i only just learned of this lego mmo lol

**Comment by QuintenQVD0** [comment]
I am closing this as ports below 1024 are needed.
