### ISSUE TITLE
[Egg Request]: LazyMC - Stop your server when no-one is online

### ISSUE THREAD

**Issue by Codixer** [parkervcp/eggs#1439]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/timvisee/lazymc

### Links for the download

https://github.com/timvisee/lazymc/releases/tag/v0.2.6

### Links for the install docs

https://github.com/timvisee/lazymc/blob/master/README.md#usage

**Comment by BasToTheMax** [comment]
This would be really usefull for hosting providers!

**Comment by gOOvER** [comment]
> This would be really usefull for hosting providers!

A Hosting Provider can pay Guys to create such an  egg for him :) Or he can do this on his own :)

**Comment by parkervcp** [comment]
If a user is paying for service I would expect it to be online and ready when they want. I am closing this as I don't think it's an ideal I want to support.

**Comment by Codixer** [comment]
Wow, I completly forgot about this issue. 
This is not for hosting, but more the people who have a dedicated where they host multiple servers, but are unable to maintain the CPU for a full modpack server or because they want to save their hard drive or ram for other stuff. 

It's a big factor in people who selfhost everything, since they have control over it.

**Comment by Codixer** [comment]
ok, now that I say that. It sounds like a thing for hosting in anyway you look at it. And that could be abused
