### ISSUE TITLE
[Bug]: Sogebot 14.x.x fails to install

### ISSUE THREAD

**Issue by Curtisdhi** [parkervcp/eggs#1440]
### Panel Version

1.6.6

### Wings Version

1.5

### Service

Sogebot

### Modified

No, I did not modify the egg

### Expected Behavior

Install to complete.

### Actual Behavior

Install crashes as it fails to download the sogebot release zip.

Seems curl is not handling the 301 redirect from github.

### Steps To Reproduce

Install from the latest egg file

### Relevant log output

```shell
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
jq: error (at <stdin>:1): Cannot iterate over null (null)
Downloading from 
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
unzip:  cannot find or open sogeBot-*.zip, sogeBot-*.zip.zip or sogeBot-*.zip.ZIP.

No zipfiles found.
Installing dependencies, this will take some time so sit back and relax...
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-05T21_55_39_890Z-debug.log
```

**Comment by Software-Noob** [comment]
Github api is used to fetch releases directly, which wouldn't have any redirects and works fine for me. 

Something goes wrong since no results are returned for you. Would have to add more debug steps to see what exactly is returned and happens.

**Comment by Software-Noob** [comment]
Appears the repo was migrated to a different org thus Github does force a redirect. Would have to update the link

**Comment by Curtisdhi** [comment]
Not sure how you got it to work. Executing the same curl command results in a 301, and not teh correct json.

`$ curl --silent "https://api.github.com/repos/sogehige/sogeBot/releases/latest"`
```
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/59561561/releases/latest",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```
