### ISSUE TITLE
[Egg Request]: 7 Days to Die **Latest Experimental Builds**

### ISSUE THREAD

**Issue by JMCY26** [parkervcp/eggs#1443]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/251570/7_Days_to_Die/

### Links for the download

https://store.steampowered.com/app/251570/7_Days_to_Die/

### Links for the install docs

https://developer.valvesoftware.com/wiki/7_Days_to_Die_Dedicated_Server

**Comment by JMCY26** [comment]
7 days to die just dropped Alpha 20 on steam.
Can be accessed by right clicking the game, Beta tab, and going down to *latest experimental*.

Can you create an egg for this if possible please so I can run the egg on my host to get the latest content?

Currently the existing egg you have is only for fully released content.

**Comment by iamkubi** [comment]
This won't require a separate egg, you can use the existing 7D2D egg.  All it requires is an extra flag in the install script (`-beta latest_experimental`) to get it working.

The egg should probably be updated to allow specifying the -beta flag value through an egg variable, so I'll leave this open as a feature request for that.

**Comment by JMCY26** [comment]
> This won't require a separate egg, you can use the existing 7D2D egg. All it requires is an extra flag in the install script (`-beta latest_experimental`) to get it working.
> 
> The egg should probably be updated to allow specifying the -beta flag value through an egg variable, so I'll leave this open as a feature request for that.

Much appreciated, I'll forward this on, looking at my startup options, if a -beta flag could be added, that will allow me to add it myself without bothering the host.

Regards

**Comment by Software-Noob** [comment]
> This won't require a separate egg, you can use the existing 7D2D egg.  All it requires is an extra flag in the install script (`-beta latest_experimental`) to get it working.
> 
> The egg should probably be updated to allow specifying the -beta flag value through an egg variable, so I'll leave this open as a feature request for that.

This alone wouldn't work, because the steamcmd auto update would overwrite this once server starts.

The docker image already supports all kinds of flags including beta branches. Inform your host to create egg variable `SRCDS_BETAID`

The value of the variable can be the branch you wish to install, such as `latest_experimental `. This would ensure that all auto updates will use -beta {variable value}.

**Comment by JMCY26** [comment]
This has now been setup successfully, thank you for the help!

**Comment by kezc7** [comment]
At the risk of sounding stupid, how would someone new to this go about doing this? Thanks in advance :)

**Comment by kezc7** [comment]
Sorry, I re-read and now i'm sorted, thanks guys!
