### ISSUE TITLE
[Bug]: ARK: Survival Evolved Egg not working

### ISSUE THREAD

**Issue by wafebreaker** [parkervcp/eggs#1451]
### Panel Version

1.6.6

### Wings Version

1.5.3

### Service

ARK Server starting

### Modified

No, I did not modify the egg

### Expected Behavior

Install Server, start it, wait for Server to start (ignore the RCON messages) and play

### Actual Behavior

I get a message with "/entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory"

Full Code:

Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.

Using anonymous user.

Not updating game server as auto update was set to 0. Starting Server
:/home/container$ rmv() { echo -e "stopping server"; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c saveworld && rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c DoExit; }; trap rmv 15; cd ShooterGame/Binaries/Linux && ./ShooterGameServer ${SERVER_MAP}?listen?SessionName="${SESSION_NAME}"?ServerPassword=${ARK_PASSWORD}?ServerAdminPassword=${ARK_ADMIN_PASSWORD}?Port=${SERVER_PORT}?RCONPort=${RCON_PORT}?QueryPort=${QUERY_PORT}?RCONEnabled=True$( [ "$BATTLE_EYE" == "1" ] || printf %s ' -NoBattlEye' ) -server ${ARGS} -log & until echo "waiting for rcon connection..."; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD}; do sleep 5; done
waiting for rcon connection...
/entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory
cli: auth: rcon: dial tcp 127.0.0.1:27001: connect: connection refused
waiting for rcon connection...

### Steps To Reproduce

Step 1: Import Egg as Json
Step 2: Install Server
Step 3: Start Server

**Comment by yesBad** [comment]
![bruh](https://user-images.githubusercontent.com/87938689/145408809-1f2db97c-7298-42a6-b2c8-440d9f5a9528.png)

**Comment by wafebreaker** [comment]
> ![bruh](https://user-images.githubusercontent.com/87938689/145408809-1f2db97c-7298-42a6-b2c8-440d9f5a9528.png) That's not a bug...?

Then tell me what is this? I hope i did nothing wrong and it should work shoudnt it?

**Comment by QuintenQVD0** [comment]
/entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory
 
 means probly install faild or out off disk space for the host or that container

**Comment by wafebreaker** [comment]
I think you read wrong: My error is the line with
"/entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory"
Because i think this should start the server but it wont

**Comment by wafebreaker** [comment]
> 

Disk Space is 50gb and i reinstalled it twice. 50gb should be enough i guess? And other servers works well. I dont know what i can change to make it works



> > > ![bruh](https://user-images.githubusercontent.com/87938689/145408809-1f2db97c-7298-42a6-b2c8-440d9f5a9528.png) That's not a bug...?
> > 
> > 
> > Then tell me what is this? I hope i did nothing wrong and it should work shoudnt it?
> 
> You need to wait for rcon connection... It'll take like 10mins? (I don't use ARK egg, so not sure how long it takes exactly.)

i hope you feel a bit like a idiot not reading my message right

**Comment by yesBad** [comment]
> > 
> 
> Disk Space is 50gb and i reinstalled it twice. 50gb should be enough i guess? And other servers works well. I dont know what i can change to make it works
> 
> > > > ![bruh](https://user-images.githubusercontent.com/87938689/145408809-1f2db97c-7298-42a6-b2c8-440d9f5a9528.png) That's not a bug...?
> > > 
> > > 
> > > Then tell me what is this? I hope i did nothing wrong and it should work shoudnt it?
> > 
> > 
> > You need to wait for rcon connection... It'll take like 10mins? (I don't use ARK egg, so not sure how long it takes exactly.)
> 
> i hope you feel a bit like an idiot not reading my message right

Now your starting to be a dick huh? Lmao.

**Comment by yesBad** [comment]
> > 
> 
> Disk Space is 50gb and i reinstalled it twice. 50gb should be enough i guess? And other servers works well. I dont know what i can change to make it works
> 
> > > > ![bruh](https://user-images.githubusercontent.com/87938689/145408809-1f2db97c-7298-42a6-b2c8-440d9f5a9528.png) That's not a bug...?
> > > 
> > > 
> > > Then tell me what is this? I hope i did nothing wrong and it should work shoudnt it?
> > 
> > 
> > You need to wait for rcon connection... It'll take like 10mins? (I don't use ARK egg, so not sure how long it takes exactly.)
> 
> i hope you feel a bit like an idiot not reading my message right

You should use more than 50GB, atleast that's what I found out from Google. I also literally said "i don't use ark egg myself."

**Comment by yesBad** [comment]
I've just seen so many people that don't know that they need to wait for RCON to start and they think that it's a bug....

**Comment by wafebreaker** [comment]
> 

You started posting this image, make me feel dumb, explain me to wait because its rcon needs 10 minutes to load but all of these tips are wrong because the error isnt the rcon? xD 

i said it twice: I MEAN THE LINE "/entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory"? This isnt a rcon error?

**Comment by yesBad** [comment]
That's an emote I usually use in Discord.... :v 
> /entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory
I got it now. Thanks for saying it 2 times. I got what you meant. How much diskspace do you have available?

**Comment by wafebreaker** [comment]
> /entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory
> 
> means probly install faild or out off disk space for the host or that container

i gave it unlimited disk space and the disk has 4tb left

**Comment by yesBad** [comment]
And you have tried reinstalling? Also are u sure u got the latest egg?

**Comment by wafebreaker** [comment]
third time i reinstalled it now and i used the latest egg on [https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/ark_survival_evolved](url)

**Comment by parkervcp** [comment]
Please get your install logs

It looks like the install has failed

`/entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory`

**Comment by wafebreaker** [comment]
[https://pastebin.com/Sp1XHk0d](https://pastebin.com/Sp1XHk0d)
I hope pastebin is okay.

it shows an 0x202 SteamCMD error which means not enough space but: Pterodactyl has 300gb to use and i gave the server unlimited (0)

[https://i.imgur.com/HbKr9so.png](https://i.imgur.com/HbKr9so.png)
[https://i.imgur.com/sA4QiRV.png](https://i.imgur.com/sA4QiRV.png)

**Comment by Software-Noob** [comment]
Your system partition doesn't have enough disk space. Type `df -h` to check. 

Pterodactyl does not monitor real time usage on the machine. Quick glance only shows what you allocated.

**Comment by wafebreaker** [comment]
Exactly that was the issue. I have virtualized the game daemon in proxmox and gave it more space but i need to update in linux aswell. I didnt know that. Thank you very much!
