### ISSUE TITLE
[Egg Request]: Minecraft Bedrock on ARM64 (RaspberryPi)

### ISSUE THREAD

**Issue by vuanhson** [parkervcp/eggs#1457]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.minecraft.net/en-us/download/server/bedrock

### Links for the download

https://www.minecraft.net/en-us/download/server/bedrock

### Links for the install docs

https://www.minecraft.net/en-us/download/server/bedrock

**Comment by vuanhson** [comment]
idk it work or not if we change base image to arm64 debian image (not tested)
https://github.com/parkervcp/eggs/blob/a054437bad1b563c809f7e3d48be5112ec930e8b/game_eggs/minecraft/bedrock/bedrock/egg-vanilla-bedrock.json#L13

**Comment by parkervcp** [comment]
I am pretty sure the bedrock server isn't arm compatible.

**Comment by vuanhson** [comment]
@parkervcp oh, thank you for letting me know, I will close this issue.
