### ISSUE TITLE
[Egg Request]: NachoSpigot

### ISSUE THREAD

**Issue by kalebchoi** [parkervcp/eggs#1458]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/CobbleSword/NachoSpigot

### Links for the download

https://nightly.link/CobbleSword/NachoSpigot/workflows/build-nachospigot/master/NachoSpigot-server.zip

### Links for the install docs

https://github.com/CobbleSword/NachoSpigot/blob/master/README.md

**Comment by TASelwyn** [comment]
You can just run the normal spigot egg and replace the file with this "NachoSpigot".

**Comment by parkervcp** [comment]
If I added every Minecraft form we have several hundred.

The default Minecraft egg had the option to set a download link for jar files though and will download for you.
