### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hakan9878** [parkervcp/eggs#1462]
### Panel Version

1.6

### Wings Version

1.5

### Service

Project Zomboid

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Set up the config, start the server and get it online

### Actual Behavior

Server crashes with this exception:

ExceptionLogger.logException> Exception thrown java.lang.UnsatisfiedLinkError: /home/container/natives/libRakNet64.so: /lib/x86_64-linux-gnu/libm.so.6: version \GLIBC_2.29' not found (required by /home/container/natives/libRakNet64.so) at NativeLibraries.load (Native Method)

Pasting an answer I've got from game's reddit:

"I've done some looking. Pterodactyl egg puts PZ in the debian buster container. It needs to be in a bullseye container; https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/project_zomboid/egg-project-zomboid.json "container": "debian:buster-slim","

### Steps To Reproduce

Add "-beta b41multiplayer" to install script in the egg config to get the latest beta
Create the server
Install and run the server

**Comment by gOOvER** [comment]
Not a Bug;

Use `ghcr.io/parkervcp/games:source` as image. Only Bullseye support 2.29

**Comment by Software-Noob** [comment]
old glibc issue is an issue with the runtime image and not install one, since installation only pulls it from the steamcmd. We've migrated the Docker images to yolks, can you try using `ghcr.io/pterodactyl/games:source` instead?
