### ISSUE TITLE
[Bug]: nukkit

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1464]
### Panel Version

1.5.1

### Wings Version

1.4.7

### Service

minecraft/nukkit

### Modified

No, I did not modify the egg

### Expected Behavior

no error

### Actual Behavior

Error: Unable to access jarfile server.jar

### Steps To Reproduce

install nukkit egg

**Comment by parkervcp** [comment]
With no logs we cannot troubleshoot.

**Comment by parkervcp** [comment]
You can re-open this issue when you have logs.
