### ISSUE TITLE
[Egg Request]: Dynamica Discord Bot

### ISSUE THREAD

**Issue by sebasptsch** [parkervcp/eggs#1465]
### Does this expand an already existing service

No

### Link to a game or software

https://dynamica.dev/

### Links for the download

https://github.com/sebasptsch/Dynamica

### Links for the install docs

https://dynamica.dev/docs/selfhosting/#pterodactyl-egg

**Comment by Software-Noob** [comment]
It looks like you already made an egg. Why not open a pull request to add the necessary changes?
