### ISSUE TITLE
[Egg Request]: Wiki.js

### ISSUE THREAD

**Issue by OperatorEK0** [parkervcp/eggs#1472]
### Does this expand an already existing service

No

### Link to a game or software

https://js.wiki/

### Links for the download

https://hub.docker.com/r/requarks/wiki

### Links for the install docs

https://docs.requarks.io/install/docker

**Comment by parkervcp** [comment]
requires multiple containers working together. 

Just because it has a docker container doesn't mean it will just work with pterodactyl.

**Comment by parkervcp** [comment]
Yeah. This is a 3 container system. I won't be adding this.

**Comment by OperatorEK0** [comment]
I see, I didn't do my research correctly sorry.

**Comment by loprima-l** [comment]
Maybe i'm not rright but if think this could work because u can use the mysql instance of the panel to do the db runner, i'm trying to but i can't put my config.yml in it becayse the files aren't linking to the panel
