### ISSUE TITLE
[Egg Request]: Getting Over It Multiplayer (GOIMP)

### ISSUE THREAD

**Issue by CommandCracker8** [parkervcp/eggs#1479]
### Does this expand an already existing service

No

### Link to a game or software

https://discord.gg/msxx6Vr

### Links for the download

https://discord.gg/msxx6Vr (Go to #download)

### Links for the install docs

There aren't any

**Comment by CommandCracker8** [comment]
About the install docs, here is how to run the server (btw it's Windows based so something like Wine or Mono is needed):

Download and unzip the files
Run the main .exe file (GettingOverItMP.Server.exe) with the optional command line parameters. Here's what you can use:

```
--hostname The server name that should be shown in the server browser.

--private [optional] If enabled then the server will not appear in the server browser.

--maxplayers The max amount of players allowed on the server.

--port [optional] The port to listen on. The default is 25050

--nosteam [optional] If enabled then steam authentication will be disabled. Players can join without owning the game on Steam but user identity verification will be limited to IP.
```

Then, you have a working server. If anyone does decide to try and do this, and doesn't have Getting Over It, you can contact me at **CCCFan#8350** on Discord.

**Comment by parkervcp** [comment]
Unless they have an official site and instructions this is not happening.

**Comment by CommandCracker8** [comment]
Also, you'll see that the mod is technically unsupported even by the creator(s?) now. From what I know it's still used quite a lot. Also I **have** managed to successfully run this using `mono` on an Ubuntu server VPS so it is possible. I tried using a Mono image to run it in Pterodactyl but with no luck.

**Comment by CommandCracker8** [comment]
> Unless they have an official site and instructions this is not happening.

Oh Ok.
