### ISSUE TITLE
Adding fivem onesynch support to the egg.

### ISSUE THREAD

**Issue by RikoDEV** [parkervcp/eggs#148]
Panel Version: 0.7.11
Daemon Version: 0.6.8
Service: fivem
Modified: (yes/no) np

I suggests increasing the maximum number of max players slots from 32 to 64. Since currently you can not run fivem server in the onesynch mode with 64 slots.

**Comment by parkervcp** [comment]
What this supposed to be a PR? There was already a PR that does this but I closed it out due to not getting an answer.

**Comment by NgLoader** [comment]
I think its not a egg bug

**Comment by RikoDEV** [comment]
Okay, so I'm closing the issue.
