### ISSUE TITLE
[Bug]: code server not working

### ISSUE THREAD

**Issue by ggvick** [parkervcp/eggs#1481]
### Panel Version

1.6.6

### Wings Version

1.5.3

### Service

software/code-server

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

*I modified the docker image to include pip but code server has worked for me for the past month or so so it should not be a problem, I have a older server that was installed previously and it works fine with that image*

Install code server, go to the ip and use it

### Actual Behavior

The install script is not downloading from GitHub because the url parameter in the install script is left blank

### Steps To Reproduce

step 1: get code server 
step 2: run code server
step 3: the package will not download

*as mentioned above, I did change the docker image to include pip. It is the exact same one from your parkervcp/yolks just with "python3-pip" included in the "RUN apt install"

### Relevant log output

```shell
jq: error (at <stdin>:1): Cannot iterate over null (null)
Downloading 
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

full install log here: https://bin.ptdl.co/vvlpm/

*In the install script it has a line "echo "Downloading $DOWNLOAD_URL"" and above it echos Downloading but nothing regarding a download url or a link to GitHub to download signalling that the DOWNLOAD_URL variable is blank*
```

**Comment by parkervcp** [comment]
@ggvick we would need to while log. Not the tiny but you have.

**Comment by gOOvER** [comment]
Echo have nothing to do with the Download. you can Google ECHO

**Comment by gOOvER** [comment]
URL of Repo has changed

https://github.com/coder/code-server
