### ISSUE TITLE
[Bug]: SPACE ENGINEERS EGG HAVE PROBLEM

### ISSUE THREAD

**Issue by zarar2312** [parkervcp/eggs#1482]
### Panel Version

LAST

### Wings Version

LAST

### Service

Space_Engineers

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

![image](https://user-images.githubusercontent.com/24358398/146518935-070a0bdf-0314-4a86-803b-b4c0d0107eb5.png)

### Actual Behavior

#!/bin/bash
# Installation Script
#
## Define variables
dlurl="https://raw.githubusercontent.com/parkervcp/eggs/master/game_eggs/steamcmd_servers/space_engineers"

THIS SCRIPT ERROR: PLEASE FIX IT

### Steps To Reproduce

İ have 100 reinstall server...

**Comment by gOOvER** [comment]
i See No Problem

**Comment by zarar2312** [comment]
If the problem does not appear, how does it not work?

**Comment by Software-Noob** [comment]
That's a base variable that will be used with other variables. It's not used as-is.

Closing this since you've provided no logs or valid information to understand your issue. LAST is not a version.
