### ISSUE TITLE
[Egg Request]: Craftopia

### ISSUE THREAD

**Issue by lejoueur50** [parkervcp/eggs#1486]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1307550/Craftopia/

### Links for the download

SteamCmd : app_update 1670340

### Links for the install docs

https://steamcommunity.com/sharedfiles/filedetails/?id=2525156012

**Comment by parkervcp** [comment]
This could probably the wine source egg I already have.

**Comment by danny6167** [comment]
SteamDB says there are linux server files https://steamdb.info/depot/1670342/

**Comment by parkervcp** [comment]
then the steamcmd generic

**Comment by lejoueur50** [comment]
I tried to create a new egg with the steamcmd script and the wine source egg

With the first option, I've downloaded the steamcmd, and the server without any problems, but trying to start throw an SIGSEGV error, don't really know why

For the wine source egg, I've followed the installs docs, installed everything on Windows and uploaded the folder on the server. For the moment, this solution seems to work, we can join and play normally

Thanks for the help !

**Comment by gOOvER** [comment]
I'm on it. Have a Basic egg for now. Hope i can push it these days

**Comment by ZaxLofful** [comment]
> I'm on it. Have a Basic egg for now based on source Image. Hope i can push it these days. It's all a bit too much Alpha state :D

Can you post the full template, that you used?

**Comment by elysium38711** [comment]
> I'm on it. Have a Basic egg for now based on source Image. Hope i can push it these days. It's all a bit too much Alpha state :D

I think Craftopia might be coming out of Alpha this year and go into Beta maybe.

**Comment by gOOvER** [comment]
> > I'm on it. Have a Basic egg for now based on source Image. Hope i can push it these days. It's all a bit too much Alpha state :D
> 
> Can you post the full template, that you used?

Not yet: first i need to add configparsing

**Comment by gOOvER** [comment]
Egg added. Please test

#1523

**Comment by lejoueur50** [comment]
I've tested it, that's perfectly working, thanks !

Just had to edit `ServerSetting.ini` to have it running on the right port

**Comment by gOOvER** [comment]
> I've tested it, that's perfectly working, thanks !
> 
> Just had to edit `ServerSetting.ini` to have it running on the right port

No need. When port is added in variables, port is autoset

**Comment by lejoueur50** [comment]
> For me it works; The allocated gameport is added to the ini file. Only 1 Port is needed and is parsed during startup

I've tried multiple times, that's working but not on the first launch :

To explain :
- When I install the server, the file `ServerSetting.ini` isn't created.
- Then, I start and let it run normally : File created with Craftopia's default values
- Finally, I restart it, default values are replaced by correct values

Thanks again !

**Comment by gOOvER** [comment]
> > For me it works; The allocated gameport is added to the ini file. Only 1 Port is needed and is parsed during startup
> 
> I've tried multiple times, that's working but not on the first launch :
> 
> To explain :
> 
> * When I install the server, the file `ServerSetting.ini` isn't created.
> * Then, I start and let it run normally : File created with Craftopia's default values
> * Finally, I restart it, default values are replaced by correct values
> 
> Thanks again !

Thank you for the answer. I will create a workaround :)
