### ISSUE TITLE
[Egg Request]: SSM - Satisfactory Server Manager

### ISSUE THREAD

**Issue by LegacyAngel2K9** [parkervcp/eggs#1490]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/mrhid6/SatisfactoryServerManager

### Links for the download

https://github.com/mrhid6/SatisfactoryServerManager/releases

### Links for the install docs

https://github.com/mrhid6/SatisfactoryServerManager/blob/master/README.md

**Comment by LegacyAngel2K9** [comment]
so the SSM makes it easy for the end user to install mods on dedicated servers

**Comment by parkervcp** [comment]
This is basically a way to have people break their installs and blame us for them being broken when a mod doesn't work.

**Comment by LegacyAngel2K9** [comment]
Adding a disclaimer for that?
Or do you know how to add a modded Satisfactory version to the already existing egg?

**Comment by gOOvER** [comment]
> Adding a disclaimer for that? Or do you know how to add a modded Satisfactory version to the already existing egg?

There is No working modmanger Version now for Servers

**Comment by gOOvER** [comment]
> so the SSM makes it easy for the end user to install mods on dedicated servers

That Script is not for MODS !!!!!!!

Read the description correct

`Satisfactory Server Manager (SSM) is a webpage designed to manage and control you satisfactory dedicated server.`

**Comment by LegacyAngel2K9** [comment]
> > so the SSM makes it easy for the end user to install mods on dedicated servers
> 
> 
> 
> This WebScript is not for managing MODS !!!!!!!
> 
> 
> 
> Read the description correct
> 
> 
> 
> `Satisfactory Server Manager (SSM) is a webpage designed to manage and control you satisfactory dedicated server.`

Im Well aware that it is a webpage to control the Satisfactory server, and it is Also a WebScript for managing mods, i have been in contact with Refined R&D/mrhid6 to develop to Get a new design there which im currently designing for them, and when i installed the SSM i saw all the features in it, installing a mod manager and mod for server is in there, i think you should check it out a little more than just reading the readme file

**Comment by Software-Noob** [comment]
Personally, I don't see any reason to have nested server managers. Pterodactyl is already one

**Comment by gOOvER** [comment]
> > > so the SSM makes it easy for the end user to install mods on dedicated servers
> > 
> > 
> > This WebScript is not for managing MODS !!!!!!!
> > Read the description correct
> > `Satisfactory Server Manager (SSM) is a webpage designed to manage and control you satisfactory dedicated server.`
> 
> Im Well aware that it is a webpage to control the Satisfactory server, and it is Also a WebScript for managing mods, i have been in contact with Refined R&D/mrhid6 to develop to Get a new design there which im currently designing for them, and when i installed the SSM i saw all the features in it, installing a mod manager and mod for server is in there, i think you should check it out a little more than just reading the readme file

As i said; how is he able to manage Mods in Dedicated Servers, when there is no support for it?
