### ISSUE TITLE
[Egg Request]: Pufferfish

### ISSUE THREAD

**Issue by RealCamar** [parkervcp/eggs#1492]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/pufferfish-gg/Pufferfish

### Links for the download

https://ci.pufferfish.host/

### Links for the install docs

Same process as how you install Paper.

**Comment by gOOvER** [comment]
https://github.com/parkervcp/eggs/issues/1458#issuecomment-991638742

**Comment by IceColdTray** [comment]
Airplane recently discontinued for 1.18 and this has been the go-to replacement for it for 1.18 and since it ported Airplane patches to 1.18 + some other cool features like Sentry support

**Comment by parkervcp** [comment]
You can already set up the java eggs to download a jar file. This is why I have been saying no to these as forks come and go on a regular basis.
