### ISSUE TITLE
[Egg Request]: AutoMuteUs

### ISSUE THREAD

**Issue by BothimTV** [parkervcp/eggs#1496]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/denverquane/automuteus

### Links for the download

https://github.com/denverquane/automuteus

### Links for the install docs

https://github.com/denverquane/automuteus/blob/master/README.md#self-hosting

**Comment by parkervcp** [comment]
The golang egg would probably handle this fine. I don't see why this needs to be separate.

**Comment by gOOvER** [comment]
**Requires [amonguscapture](https://github.com/denverquane/amonguscapture) to capture and relay game data.**

**Comment by BothimTV** [comment]
The problem is, that you have hard rate limits on the public bot (without premium), that is on large servers a huge problem.
