### ISSUE TITLE
[Egg Request]: iRedMail

### ISSUE THREAD

**Issue by mitchal01** [parkervcp/eggs#1498]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/iredmail/dockerized

### Links for the download

https://hub.docker.com/r/iredmail/mariadb

### Links for the install docs

https://github.com/iredmail/dockerized

**Comment by parkervcp** [comment]
This wont work in pterodactyl as we block all ports under 1024 for security reasons.

**Comment by mitchal01** [comment]
Thank you for your response !!
