### ISSUE TITLE
[Egg Request]: Add FarmingSimulator 22 server hosting

### ISSUE THREAD

**Issue by Default-01** [parkervcp/eggs#1499]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/parkervcp/eggs/issues/1499#issue-1088864648

### Links for the download

https://github.com/parkervcp/eggs/issues/1499#issue-1088864648

### Links for the install docs

https://github.com/parkervcp/eggs/issues/1499#issue-1088864648

**Comment by iamkubi** [comment]
None of the links you've included provide the information being asked for.  Duplicate of #307 #1053 #1160
