### ISSUE TITLE
[Egg Request]: nextcord 

### ISSUE THREAD

**Issue by fizztune** [parkervcp/eggs#1503]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/nextcord/nextcord

### Links for the download

https://github.com/nextcord/nextcord

### Links for the install docs

https://github.com/nextcord/nextcord#installing

**Comment by parkervcp** [comment]
This is literally handled already by the discord.py egg.

It's a generic why and doesn't actually install discord.py

**Comment by fizztune** [comment]
Oops, sorry
