### ISSUE TITLE
[Bug]: Error on installing FiveM server.

### ISSUE THREAD

**Issue by Megapluto8** [parkervcp/eggs#1504]
### Panel Version

1.0.1

### Wings Version

1.5.3

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

That it starts the server.

### Actual Behavior

:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
/entrypoint.sh: line 12: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: No such file or directory

full console log: https://pastebin.com/E3jfxiFT

### Steps To Reproduce

version: 5104
https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/5104-5ebb6dfe826667c841027d6dbc7390e42abfb196/fx.tar.xz

startup command:
$(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey {{FIVEM_LICENSE}} +set steam_webApiKey {{STEAM_WEBAPIKEY}} +set sv_maxplayers {{MAX_PLAYERS}} +set serverProfile default +set txAdminPort {{TXADMIN_PORT}} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )

start up script: https://pastebin.com/SRm9r4uu

**Comment by Software-Noob** [comment]
Provide the install logs `tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99`

Also, should you really be running panel 1.0.1, you definitely have to update.

**Comment by Megapluto8** [comment]
Hi thanks for responding so fast.
i'm running pterodactyl version 1.6.5 and software version 1.0.1 i didn't know wich one was the right one.
and is there any way to find the logs without using ssh cause i only have acces to the pterodactyl panel.

**Comment by Software-Noob** [comment]
Unless you have install logs, there's nothing we can assist you with. Please ask your panel owner for support or for them to open a bug report/ask in Discord help channels.

**Comment by Megapluto8** [comment]
> Unless you have install logs, there's nothing we can assist you with. Please ask your panel owner for support or for them to open a bug report/ask in Discord help channels.

i will thanks for helping anyways!

**Comment by Megapluto8** [comment]
ok thanks for your help so far and with a bit of messing around i fixed this issue but now i have run into a new error 
https://pastebin.com/usku4EDM
