### ISSUE TITLE
[Bug]: five m server start error

### ISSUE THREAD

**Issue by Megapluto8** [parkervcp/eggs#1506]
### Panel Version

1.6.5

### Wings Version

1.5.3

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

That it starts the server.

### Actual Behavior

it keeps crashing and spits a lot of error full error log = pastebin.com/usku4EDM

first few lines : 
Error loading shared library libstdc++.so.6: Exec format error (needed by /home/container/alpine/opt/cfx-server/FXServer)
Error loading shared library libstdc++.so.6: Exec format error (needed by /home/container/alpine/opt/cfx-server/libCoreRT.so)
Error relocating /home/container/alpine/opt/cfx-server/libCoreRT.so: __cxa_begin_catch: symbol not found

### Steps To Reproduce

version : 5104 https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/5104-5ebb6dfe826667c841027d6dbc7390e42abfb196/fx.tar.xz

start up command: 
$(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey {{FIVEM_LICENSE}} +set steam_webApiKey {{STEAM_WEBAPIKEY}} +set sv_maxplayers {{MAX_PLAYERS}} +set serverProfile default +set txAdminPort {{TXADMIN_PORT}} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )

start up script: https://pastebin.com/zXtyDEGr

### Install logs

i dont have acces to that :(

**Comment by Software-Noob** [comment]
Please do not open multiple issues. You already received a response in #1504
