### ISSUE TITLE
[Egg Request]: Plutonium T6

### ISSUE THREAD

**Issue by GaryCraft** [parkervcp/eggs#1507]
### Does this expand an already existing service

Yes

### Link to a game or software

https://plutonium.pw/

### Links for the download

https://cdn.plutonium.pw/updater/plutonium.exe https://plutonium.pw/pluto_t6_full_game.torrent

### Links for the install docs

https://plutonium.pw/docs/install/#t6

**Comment by GaryCraft** [comment]
## Additional Info
[An Existing Version of this Egg](https://github.com/GaryCraft/ptero-plutonium)

**Comment by gOOvER** [comment]
`Aim Assist` sounds like a Aimbot xD

**Comment by gOOvER** [comment]
> ## Additional Info
> [An Existing Version of this Egg](https://github.com/GaryCraft/ptero-plutonium/blob/main/EGGS/egg-plutonium-t6.json?rgh-link-date=2021-12-30T21%3A46%3A58Z)

Better start a PR for your egg.

**Comment by GaryCraft** [comment]
I've tried ParkerCVP yolk, but it didn't work properly (at all) because the game requires a custom working directory to start and run

**Comment by gOOvER** [comment]
> I've tried ParkerVCP's yolk, when suggested by him before, but it didn't work properly (at all) because the game requires a custom working directory to start and run

what dir you need? For start you can only use /home/container, so i think, its not needed to use an own image

**Comment by GaryCraft** [comment]
The Working directory need to be `` /home/container/T6_Server/Plutonium`` required by the server software

**Comment by gOOvER** [comment]
I think thats not needed, when /T6_Server/Plutonium is not hardcoded

**Comment by GaryCraft** [comment]
https://forum.plutonium.pw/post/60686
