### ISSUE TITLE
[Bug]: Arma 3 Egg does not fill `-mod` startup parameter as expected

### ISSUE THREAD

**Issue by SkyMulley** [parkervcp/eggs#1508]
### Panel Version

WISP (Custom Ptero)

### Wings Version

WISP (Custom Ptero)

### Service

Arma3

### Modified

No, I did not modify the egg

### Expected Behavior

Using a `modlist.html` within the root directory of the container or a specified list of mods in the `Additional Mods` startup parameter; when the server boots it should update then load all respective mods using the `-mod` startup parameter (as insinuated in the startup parameter descriptions).

### Actual Behavior

Server updates or validates the mods in the file or parameter as intended, but does not fill the `-mod` startup parameter as expected but instead leaves it blank:

`[STARTUP]: Starting server with the following startup command:
./arma3server_x64 -ip=0.0.0.0 -port=2302 -profiles=./serverprofile -bepath=./battleye -cfg=basic.cfg -config=server.cfg -mod="" -serverMod="" -noLogs`

### Steps To Reproduce

Step 1: Fresh install of the Arma 3 egg into a server
Step 2: Add a valid `modlist.html` or Additional Mods startup parameter
Step 3: Start the server

### Install logs

https://pastebin.com/Vztqytwr

**Comment by lilkingjr1** [comment]
Possibly related to issue #1360. WISP seems to have issues with this egg for some reason, and I'm not sure why. Works as expected on an un-modded install of Pterodactyl.

**Comment by gOOvER** [comment]
You should ask WISP for support

**Comment by SkyMulley** [comment]
Do you guys have any image specific details I can take to WISP support regarding the issue as to not be ambigious?

**Comment by lilkingjr1** [comment]
@SkyMulley If they aren't running this exact image address for their egg, the egg is not guaranteed to work: `ghcr.io/parkervcp/games:arma3`

If they are, then their modified panel or wings is doing something extra (or maybe security related?) with the startup command execution. It's almost as if the image `entrypoint.sh` is running everything fine with access to the variables, but the startup parameter/command is being handled differently (which wouldn't be surprising). The startup command uses variables that are not immediately available before server launch (ie. they don't show "properly" in the startup field in the panel), but they are generated every startup up during the image's `entrypoint.sh` script.

**Comment by SkyMulley** [comment]
Thanks for the confirmation, I've confirmed that it is an issue with WISP over multiple instances and that Pterodactyl works fine so have escalated the issue to them.
