### ISSUE TITLE
[Bug]: there is no egg ( json file) for Geyser

### ISSUE THREAD

**Issue by QuintenQVD0** [parkervcp/eggs#1512]
### Panel Version

1.6.6

### Wings Version

1.5.3

### Service

minecraft/proxy/cross-platform/geyser

### Modified

No, I did not modify the egg

### Expected Behavior

there should be a .json file for a egg 

### Actual Behavior

there is just a readme

### Steps To Reproduce

go to the egg repo pres on the home page to geyser and you only get a readme

### Install logs

not required

**Comment by gOOvER** [comment]
Read the README correct ;)
