### ISSUE TITLE
[Bug]: Tuinity server.jar download fails

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1517]
### Panel Version

latest

### Wings Version

latest

### Service

minecraft/tuinity

### Modified

No, I did not modify the egg

### Expected Behavior

no error

### Actual Behavior

container@pterodactyl~ java -Xms128M -Xmx9216M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
Error: Invalid or corrupt jarfile server.jar

### Steps To Reproduce

install egg

### Install logs

above

**Comment by QuintenQVD0** [comment]
Is there in the file manger a server.jar?

**Comment by Software-Noob** [comment]
Fill the template correctly. There are no bugs if you can't provide logs.

**Comment by BenasPaulikas** [comment]
server.jar content 

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/job/Spottedleaf/job/Tuinity/lastStableBuild/artifact/tuinity-paperclip.jar</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>

</body>
</html>

**Comment by QuintenQVD0** [comment]
> server.jar content
> 
> ```
> <html>
> <head>
> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
> <title>Error 404 Not Found</title>
> </head>
> <body><h2>HTTP ERROR 404 Not Found</h2>
> <table>
> <tr><th>URI:</th><td>/job/Spottedleaf/job/Tuinity/lastStableBuild/artifact/tuinity-paperclip.jar</td></tr>
> <tr><th>STATUS:</th><td>404</td></tr>
> <tr><th>MESSAGE:</th><td>Not Found</td></tr>
> <tr><th>SERVLET:</th><td>Stapler</td></tr>
> </table>
> <hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>
> 
> </body>
> </html>
> ```

fill in the forum  with version numbers and proper logs. so make the issue again and fill it in right!
