### ISSUE TITLE
[Egg Request]: Stardew Valley & SMAPI

### ISSUE THREAD

**Issue by ultraic-space** [parkervcp/eggs#1525]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.stardewvalley.net/

### Links for the download

https://smapi.io/

### Links for the install docs

https://stardewvalleywiki.com/Modding:Player_Guide/Getting_Started

**Comment by ultraic-space** [comment]
I have tried getting [this](https://github.com/metrogamelab/stardew-valley-server/tree/main) to work, to no avail. It hasn't been updated for over a year, and the egg file doesn't seem to work. (It's in a branch called egg-fail.)

A docker thingy I found can be located [here](https://github.com/printfuck/stardew-multiplayer-docker), which I too, have no idea how to get working.

Please. I want this so bad, thank so much for whoever'll pr or contribute this.

**Comment by parkervcp** [comment]
The SMAPI doesn't have a server but is a client to client mod.

**Comment by ultraic-space** [comment]
> The SMAPI doesn't have a server but is a client to client mod.

Definitely should've clarified this, SMAPI has a mod https://www.nexusmods.com/stardewvalley/mods/2677?tab=files that allows for 'servers' to sort-of be made. Will this be possible as an egg? The docker version thing seems to have web gui to manage the server account.

To simplify, could a server egg be made for [this](https://github.com/printfuck/stardew-multiplayer-docker)?

**Comment by parkervcp** [comment]
After looking at that I am even less likely to make that.

**Comment by DNAniel213** [comment]
any possibilities of this happening still?
