### ISSUE TITLE
[Egg Request]: LS22

### ISSUE THREAD

**Issue by edvnetwork** [parkervcp/eggs#1528]
### Does this expand an already existing service

No

### Link to a game or software

https://www.giants-software.com/

### Links for the download

--

### Links for the install docs

--

**Comment by Software-Noob** [comment]
You've put no effort into the request. Wild guess based on the website it's a farming simulator, which doesn't have Linux support. #307

**Comment by edvnetwork** [comment]
Here is a Docker Pull to the ls22 server and can run with wine.

https://hub.docker.com/r/toetje585/docker-winebased-server-fs22
