### ISSUE TITLE
[Egg Request]: LiteLoader for Bedrock edition

### ISSUE THREAD

**Issue by Ultr4Anubis** [parkervcp/eggs#1532]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.litebds.com/

### Links for the download

https://github.com/LiteLDev/LiteLoaderBDS/releases

### Links for the install docs

https://github.com/LiteLDev/LiteLoaderBDS

**Comment by gOOvER** [comment]
This is Windows only

**Comment by aShanki** [comment]
It's not windows only though, it works with docker on linux
```
docker pull shrbox/liteloaderbds
docker create --name liteloader -p 19132:19132/udp -i -t shrbox/liteloaderbds
```
then 
```
Start server: docker container start liteloader

Stop server(unrecommended): docker container stop liteloader

Enter console: docker attach liteloader

Exit console: press Ctrl + P + Q. If you press Ctrl + C, the server process will exit. If you want to manage server file, use docker volume --help for more details
```

**Comment by DatMayo** [comment]
There is no "real" Linux version. Its Just `RUN /bin/sh -c wine SymDB2.exe && rm plugins/LiteLoader/CrashLogger_Daemon.exe && rm /home/bds/.wine -r # buildkit` that makes the magic. So it can break every time

**Comment by parkervcp** [comment]
Going with a no on this one.

**Comment by Ultr4Anubis** [comment]
Is it still a no on this one?
