### ISSUE TITLE
[Bug]: SourceEngine - Garry's Mod

### ISSUE THREAD

**Issue by ItJustFox** [parkervcp/eggs#1533]
### Panel Version

1.6.6

### Wings Version

1.5.6

### Service

eggs/stock_eggs/source-engine/egg-garrys-mod.json

### Modified

No, I did not modify the egg

### Expected Behavior

When after the install of the server using the basic egg for garry's mod server, whe exceped that he will normally start but he just dont want.

### Actual Behavior

when he actually start he just keep crashing. with the exit code 13

### Steps To Reproduce

Go to 'Servers'
Click on 'Server'
Click create a gmod server
Start the Server after the install
Error will show in console.

### Install logs

https://pastebin.com/uxwRPEWR

**Comment by parkervcp** [comment]
@ItJustFox you had the right place before. I'll close this and we can talk about this on the first issue.
