### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ItzDepstRT** [parkervcp/eggs#1534]
### Panel Version

1.6.6

### Wings Version

1.5.3

### Service

eggs/game_eggs/gta/fivem/

### Modified

No, I did not modify the egg

### Expected Behavior

Change the version

### Actual Behavior

Doesnt change the fivem version

### Steps To Reproduce

1. Set to latest
2. Started the server 
3. 3. Server started without updating 

### Install logs

Cant provide

**Comment by gOOvER** [comment]
i see no bug

**Comment by Software-Noob** [comment]
Changing a version requires a reinstall.

**Comment by ItzDepstRT** [comment]
I already reinstalled

**Comment by Software-Noob** [comment]
In that case fill the template correctly. You provided no information.
