### ISSUE TITLE
[Egg Request]: wine 7 for conan exile server because wine 5 is running out of ram and crashing server

### ISSUE THREAD

**Issue by KingCobra70** [parkervcp/eggs#1542]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.winehq.org/announce/7.0

### Links for the download

https://dl.winehq.org/wine/source/7.0/wine-7.0.tar.xz

### Links for the install docs

https://www.winehq.org/documentation

**Comment by parkervcp** [comment]
stopping and starting your server should pull the latest wine image which we already have built.

**Comment by parkervcp** [comment]
FYI

This literally builds weekly and just uses the latest wine release

https://github.com/parkervcp/yolks/blob/master/wine/latest/Dockerfile

**Comment by KingCobra70** [comment]
I think that worked. Testing to see if it fixed memory issue. Thanks for the support!!! If it works better I will update, so you might update main file so other people don't have to go through this
