### ISSUE TITLE
[Bug]: Adding .Net 6.0.0 Support to ALT:V

### ISSUE THREAD

**Issue by Gogadon** [parkervcp/eggs#1543]
### Panel Version

1.7.0

### Wings Version

1.5.6

### Service

AltV

### Modified

No, I did not modify the egg

### Expected Behavior

The Server Loads CS Ressources (dll Files)

### Actual Behavior

When I try to run the latest version of AltV I get the following error: (attached in the log from the server startup)

`It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - The following frameworks were found:
      5.0.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=debian.10-x64`

### Steps To Reproduce

Install AltV
use the release branch "rc"
start server

### Install logs

.

**Comment by gOOvER** [comment]
you are free, to create a PR. As i know, the egg don't install any DotNet. Is this needed for a plugin?

**Comment by Gogadon** [comment]
That may be but in docker it installs dotnet 5 but I need dotnet 6

**Comment by gOOvER** [comment]
you need it or the Game need it? can you Post a Log, where dotnet6 is needed?

MB after Work, i Push the Image to ghcr and when dotnet6 is a required, then i add dotnet6

**Comment by Gogadon** [comment]
The server needs dotnet6 or rather the csharp module from the server. I can't post logs to them right now because I have to go to work. 🙂
As I said, the new Release Candidate version with csharp module needs dotnet6.
Try installing the server on RC yourself in the configuration. Activate the csharp module in the configuration and start the server

**Comment by Gogadon** [comment]
Here is a log when I start the server

![2022-01-29_08-56](https://user-images.githubusercontent.com/58675646/151652885-03b519c7-593b-44b2-982f-d0f054d4e492.png)

Furthermore, the file "AltV.Net.Host.runtimeconfig.json" contains the following information 

`{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}`

**Comment by gOOvER** [comment]
i will update the image asap

**Comment by gOOvER** [comment]
@Gogadon can you contact me via Discord to test the image? 

gOOvER#9999

**Comment by wil2005-development** [comment]
Any updates on this? Because i have the same problem.

**Comment by gOOvER** [comment]
> Any updates on this? Because i have the same problem.

the Update is releases Yesterday. i can Push a new Image, but Problem ist, thats Not kompatible with older version

**Comment by wil2005-development** [comment]
I must have .Net 6.0.0 otherwise alt:V server will not work for me so if you can push a new image that does work with .Net 6.0.0 please or is there another way I can get it without that it destroys something?

**Comment by gOOvER** [comment]
@parkervcp you must decide. New Versions of alt:V needs dotnet 6. Older Version don't work on dotnet 6. 

i have allready an image for newer Versions. Should i push it?

**Comment by gOOvER** [comment]
> I must have .Net 6.0.0 otherwise alt:V server will not work for me so if you can push a new image that does work with .Net 6.0.0 please or is there another way I can get it without that it destroys something?

contact me on Discord: gOOvER#9999 - I can give you an image, that runs with newer Versions.

**Comment by Gogadon** [comment]
> > I must have .Net 6.0.0 otherwise alt:V server will not work for me so if you can push a new image that does work with .Net 6.0.0 please or is there another way I can get it without that it destroys something?
> 
> contact me on Discord: gOOvER#9999 - I can give you an image, that runs with newer Versions.

Well, I'll be honest, everyone has to use the latest server version, because the client side actually forces you to update.
I think you should just take the latest! So in this case the one with dotnet 6

So I can say, with the Docker I got from you everything runs, so I have no problems with it to just keep running, but that's not the point.

**Comment by MstrKnight** [comment]
> Well, I'll be honest, everyone has to use the latest server version, because the client side actually forces you to update.
> I think you should just take the latest! So in this case the one with dotnet 6

Hi @gOOvER , is it possible to contact you to have the image with DotNet 6

**Comment by parkervcp** [comment]
@gOOvER Does this yolk not work?

https://github.com/parkervcp/yolks/tree/master/dotnet/6

**Comment by gOOvER** [comment]
> @gOOvER Does this yolk not work?
> 
> [https://github.com/parkervcp/yolks/tree/master/dotnet/6](https://github.com/parkervcp/yolks/tree/master/dotnet/6?rgh-link-date=2022-02-09T22%3A57%3A28Z)

the Altv Image based on `node:16-bullseye`. There are also a lot of libs. 
```
apt install -y gcc g++ libgcc-s1 lib32gcc-s1 gdb libc6 git wget curl tar zip unzip binutils xz-utils liblzo2-2 cabextract iproute2 net-tools netcat telnet libatomic1 libsdl1.2debian libsdl2-2.0-0 \
        libfontconfig1 libicu67 icu-devtools libunwind8 libssl-dev sqlite3 libsqlite3-dev libmariadb-dev libduktape205 locales ffmpeg gnupg2 apt-transport-https software-properties-common ca-certificates tzdata
```

I don't play altv; i only created a image with dotnet for a friend

**Comment by MstrKnight** [comment]
Pr is coming ? ^^

**Comment by MstrKnight** [comment]
@gOOvER Thank you !!!  it was just merged and it's ok !

**Comment by gOOvER** [comment]
> @gOOvER Thank you !!! it was just merged and it's ok !

ty for reply :)
