### ISSUE TITLE
[Egg Request]: Tekxit 3.14 Pi (Official) Modpack from Technic Launcher

### ISSUE THREAD

**Issue by TheFrodo** [parkervcp/eggs#1547]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.technicpack.net/modpack/tekxit-314-official-1122.1718228

### Links for the download

https://www.technicpack.net/modpack/tekxit-314-official-1122.1718228

### Links for the install docs

https://www.technicpack.net/modpack/tekxit-314-official-1122.1718228

**Comment by gOOvER** [comment]
https://github.com/parkervcp/eggs/issues/1458#issuecomment-991638742

**Comment by parkervcp** [comment]
I am at the point where adding more minecraft servers is not what I want to do. You can PR it if you want to.
