### ISSUE TITLE
[Bug]: Postgres egg seems to be broken

### ISSUE THREAD

**Issue by SentixDev** [parkervcp/eggs#1549]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

postgres

### Modified

No, I did not modify the egg

### Expected Behavior

After setting up the server i wanted to connect to the postgres db.

### Actual Behavior

Trying to connect via pgadmin results in "FATAL: password authentication failed for user 'pterodactyl'"

### Steps To Reproduce

1. Download the egg and create a port allocation in the node
2. Create a server using the postgres egg and change the default passwords
3. Replace postgresql.conf with the provided 
4. Add the pg_hba.conf entry for the host to be able to connect from
5. Try to connect to the database with the configured password

### Install logs

command is taking hours to load smh

**Comment by janganlahkau** [comment]
Can I get your web panel? Plss

**Comment by FC5570** [comment]
Can this be looked into please.

**Comment by Software-Noob** [comment]
The specified egg variables are never used anywhere in the egg. I'm currently busy but leaving this here for the future.

**Comment by tescomealdealll** [comment]
sorry to ask but will this be fixed anytime soon?

**Comment by SentixDev** [comment]
> sorry to ask but will this be fixed anytime soon?

I don't think so. Just install Postgres & pgadmin with docker compose, does the same job, just no fancy web ui :(

**Comment by ggvick** [comment]
Thats sad, I would also love to see this egg fixed but nobody seems to care about it too much

**Comment by omxpro** [comment]
Yeaa

**Comment by DTS-11** [comment]
any plans of fixing this issue?

**Comment by DTS-11** [comment]
> > sorry to ask but will this be fixed anytime soon?
> 
> I don't think so. Just install Postgres & pgadmin with docker compose, does the same job, just no fancy pterodactyl ui :( 

install postgres on my local machine or on the host? and how do I connect it? I can't find connection url and password.. kinda new to this platform
