### ISSUE TITLE
[Egg Request]: Titanfall 2 - R2Northstar (mod)

### ISSUE THREAD

**Issue by Luna-foxx** [parkervcp/eggs#1553]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1237970/Titanfall_2/

### Links for the download

https://github.com/R2Northstar/Northstar

### Links for the install docs

https://r2northstar.gitbook.io/r2northstar-wiki/

**Comment by lilkingjr1** [comment]
I don't think this is really practical on Pterodactyl yet, but you could try out this standalone Docker container or try adapting it to Pterodactyl (which would be pretty difficult, and potentially impossible because it requires GPU related DX12 calls still): [https://github.com/pg9182/northstar-dedicated](https://github.com/pg9182/northstar-dedicated)

**Comment by Luna-foxx** [comment]
ah ok 
i just thought that with the -softwared3d11 flag it might work 
that part is in best practice | hosting a dedicated server
would be really cool to host titanfall 2 off of pterodactyl 
if that would not work ill try and see if i could get it to work 
(i have never done this before so i guess ill have to learn)

**Comment by lilkingjr1** [comment]
Yeh, I've been eye-balling this too and would really like to see it on Pterodactyl. I even started looking into writing an egg and image for it, but when I read [pg9182](https://github.com/pg9182)'s README on his container and the fact that he had to make "custom d3d11 and gfsdk stubs" and a "custom wine build" to make it run cleanly, I realized it was above my pay-grade and nope'd out real quick, haha.

**Comment by Luna-foxx** [comment]
yea that does not sound fun 
dang that really sucks

**Comment by pg9182** [comment]
I don't know anything about Pterodactyl, but I've made the process relatively streamlined now. I have a custom wine build (it also builds 3x faster than normal wine and doesn't require 32-bit libs), 3 stub dlls (simply compile them with mingw-w64 or extract them from the docker images), and a wrapper for managing all the processes as one, filtering logs, detecting hangs, etc. I actually recently [split](https://github.com/pg9182/northstar-dedicated/blob/experimental-stuff/src/nswrap/nswrap.c) the wrapper into a standalone tool which can be used outside the container.

**Comment by pg9182** [comment]
Hmm, after taking a quick look at an egg, it seems like you could just use the container as-is, then download the game files from wherever to /mnt/titanfall.

**Comment by Luna-foxx** [comment]
i have never made an egg
does anyone have any resources that would be helpful that i would need to set one up?
also i currently do not have a server for pterodactyl but if this works i will go set one up

**Comment by Luna-foxx** [comment]
> Hmm, after taking a quick look at an egg, it seems like you could just use the container as-is, then download the game files from wherever to /mnt/titanfall.

the docker container would need to be modified to run with pterodactyl 
i dont think pterodactyl takes docker commands directly 
and from what im looking at it needs the docker command to be able to properly configure the server config
anyone feel free to correct me this is just from the knowledge i know

**Comment by pg9182** [comment]
No, it works fine without it, and you can just execute it explicitly.

**Comment by lilkingjr1** [comment]
@pg9182 @Luna-foxx Pterodactyl requires specially crafted docker images that at some point run a script (typically called `entrypoint.sh`) that processes/honors the egg's/panel's specified startup command with any startup command variables (if applicable). It also requires (well, I guess not required technically, but preferably) that all the server files reside in `/home/container` (and not any other folders), and that the "container" user is created and used.

Anyone, please correct me if I am wrong, but TL;DR:
- Could you possibly get the existing docker image to run within Pterodactyl? Maybe?.. But Probably not.
- Would it be a clean, fully functioning egg that meets the standards of most eggs in this repo? No. Thus, a custom image (possibly an easy fork of @pg9182's) is required.

**Comment by pg9182** [comment]
> possibly an easy fork of @pg9182's

That sounds possible based on what you described.

**Comment by lilkingjr1** [comment]
@pg9182 I sent you a Discord DM to possibly explore this further :)

**Comment by FacelessFace** [comment]
> @pg9182 I sent you a Discord DM to possibly explore this further :)

have you managed to get it working with thee egg or would i just have to usee docker

**Comment by lilkingjr1** [comment]
> > @pg9182 I sent you a Discord DM to possibly explore this further :)
> 
> have you managed to get it working with thee egg or would i just have to usee docker

Sadly no. Getting a working image for the egg to use was beyond my current expertise.

**Comment by StormyIceLeopard** [comment]
This exists
Has anyone tried this?
https://github.com/joeyjoey1234/Pterodactyl_Egg_Titanfall_2_Northstar

**Comment by QuintenQVD0** [comment]
> This exists Has anyone tried this? https://github.com/joeyjoey1234/Pterodactyl_Egg_Titanfall_2_Northstar

We wont. Needs mount with the full game, startup is hardcoded in the image. Non offical image. So no feel free to use it at your own risk but not supported.
