### ISSUE TITLE
[Bug]: The Forest no one can join

### ISSUE THREAD

**Issue by Felix5566** [parkervcp/eggs#1556]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

game_eggs/steamcmd_servers/the_forest

### Modified

No, I did not modify the egg

### Expected Behavior

All can play on The Forest server

### Actual Behavior

Unfortunately, no one can connect to the game server.
I think at the end when starting the server come many error messages, I downloaded the egg today.
I think errors from line 440 to 570: https://pastebin.com/bcbj7d64

### Steps To Reproduce

Install the server and start

### Install logs

https://pastebin.com/bcbj7d64

**Comment by Software-Noob** [comment]
There are no errors as the server is running. Those Wine errors are normal with Wine. Failing to join tends to be a allocation/firewall issue.

You must assign the required 3 ports and connect using the query port.

**Comment by gOOvER** [comment]
can't confirm. Server works as it should. i bet you don't have the correct ports

**Comment by Felix5566** [comment]
This are my Ports: https://i.imgur.com/13ABJAg.png

**Comment by Felix5566** [comment]
https://youtu.be/4t8Kbe4taHQ 
and https://i.imgur.com/6SNgFcf.png ...
