### ISSUE TITLE
[Bug]: standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [parkervcp/eggs#1562]
### Panel Version

1.7

### Wings Version

1.6.1

### Service

Mindustry, Haste-Server

### Modified

No, I did not modify the egg

### Expected Behavior

They should work

### Actual Behavior

They dont work

### Steps To Reproduce

Download egg
Put it in panel
Start it
Wait 'till it installed
Try to start it
Get this error (standard_init_linux.go:228: exec user process caused: exec format error)

### Install logs

Install is fine. It happens when u try to start it

**Comment by parkervcp** [comment]
You were literally just told to try the ghcr images instead of the quay ones.

**Comment by gOOvER** [comment]
can't confirm for haste-Server. I run 4 and never see this error

**Comment by MrMasrozYTLIVE** [comment]
I just used latest

**Comment by MrMasrozYTLIVE** [comment]
> You were literally just told to try the ghcr images instead of the quay ones.

Lmfao how i'm stupid

**Comment by parkervcp** [comment]
We just need to update the eggs to use the newer images.

**Comment by MrMasrozYTLIVE** [comment]
I guess so. And i just used Discord.js one for node and Minecraft's java one

**Comment by Software-Noob** [comment]
> can't confirm for haste-Server. I run 4 and never see this error

This is a multiarch (ARM64) issue. Someone just has to update the eggs to use the yolks images, which are multiarch

**Comment by gOOvER** [comment]
fix for haste-server #1563
