### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by craciu25yt** [parkervcp/eggs#1566]
### Panel Version

1.7.0

### Wings Version

idk how watch it

### Service

Teaspeak

### Modified

No, I did not modify the egg

### Expected Behavior

The server open and work fine

### Actual Behavior

![image](https://user-images.githubusercontent.com/48807342/154822965-4a4a289c-aee5-4293-8caa-66810bea2c23.png)

### Steps To Reproduce

Install test panel and execute it. It start to install and after it say that

### Install logs

I execute the command and noting haopends

**Comment by parkervcp** [comment]
There is no t.sh file and that is a modified egg.

**Comment by craciu25yt** [comment]
I didn't modified anything, I downloaded from here https://github.com/parkervcp/eggs/tree/master/voice_servers/teaspeak and how can I do t.sh file
