### ISSUE TITLE
[Bug]: Pocketmine MP egg broken

### ISSUE THREAD

**Issue by breixopd** [parkervcp/eggs#1568]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, start and play

### Actual Behavior

Server installs PHP 8 but calls `/bin/php7/bin/php` resulting in console saying `/entrypoint.sh: line 12: ./bin/php7/bin/php: No such file or directory`

### Steps To Reproduce

Step 1: Make server using Pocketmine MP egg
Step 2: Start server

### Install logs

No /var/log/pterodactyl in server

**Comment by Software-Noob** [comment]
We need the install logs to see what's going on and why your install failed. The folder name is not the issue, Pocketmine has it under php7 even after updating to 8, which I assume is for backward compatibility.

`/var/log/pterodactyl `is the default log_directory. Open your Wings config and see what's yours and replace the path in the command.

**Comment by gOOvER** [comment]
i bet, he uses an old egg

**Comment by breixopd** [comment]
I found the problem, i get an exec format error because my server is ARM

**Comment by QuintenQVD0** [comment]
> I found the problem, i get an exec format error because my server is ARM

The egg now supports arm64 if your still interseted

**Comment by breixopd** [comment]
Thanks, yeah will use later!
