### ISSUE TITLE
[Bug]: MariaDB: Update to use the correct images 

### ISSUE THREAD

**Issue by cfouche3005** [parkervcp/eggs#1569]
### Does this expand an already existing service

Yes

### Link to a game or software

database/sql/mariadb

### Links for the download

https://github.com/parkervcp/yolks/tree/master/mariadb

### Links for the install docs

I don't know what type to issue to open so. My request is to update the mariadb egg to use the correct docker images. Thanks

**Comment by EgoMaw** [comment]
Currently, both the mariadb and postgres eggs are bound to use the same version the installation script uses therefore if you want to upgrade the version, you will have to update both the installation image and the image it uses to run and also run `mariadb-upgrade` or `mysql-upgrade` for mariadb and `pg_upgrade` for postgres to upgrade your existing database.

**Comment by cfouche3005** [comment]
I may be dump but is it possible to use the newer image of the parkervcp/yolks ?

**Comment by EgoMaw** [comment]
yes, but you need to make sure the image is for the version of mariadb your database was made on, or you will have to upgrade it

**Comment by cfouche3005** [comment]
when I use ghcr.io/parkervcp/yolks:mariadb_10.7 as the docker image and mariadb:10.7 as the build configuration with no change in the installation script, I get this error : `[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:58a44bd0d95cf8ef8cf391f95098af0df8546444218feb6baca6bf6cbfaf4a73 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mariadb_10.7 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ { /usr/sbin/mysqld & } && sleep 5 && mysql -u root
2022-02-24 14:27:22 0 [Note] /usr/sbin/mysqld (server 10.7.1-MariaDB-1:10.7.1+maria~focal) starting as process 16 ...
2022-02-24 14:27:22 0 [Warning] Can't create test file /var/lib/mysql/05a442c3-bf55-4cf1-a527-2ddc04f91b02.lower-test
2022-02-24 14:27:22 0 [ERROR] mysqld: Can't create/write to file './ddl_recovery.log' (Errcode: 13 "Permission denied")
2022-02-24 14:27:22 0 [ERROR] DDL_LOG: Failed to create ddl log file: ./ddl_recovery.log
2022-02-24 14:27:22 0 [ERROR] Aborting
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
container@pterodactyl~ Server marked as offline...


[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
`

**Comment by cfouche3005** [comment]
do you have the original quay.io/parkervcp/pterodactyl-images:db_mariadb DockerFile ?

**Comment by gOOvER** [comment]
> do you have the original quay.io/parkervcp/pterodactyl-images:db_mariadb DockerFile ?

not needed, because github images are the same. Based on Quay Images.

The egg needs to be rewritten to be more  generic. ATM the install Image is  Mariadb10.3 and this will not work with the Mariadb image 10.7.

Or we must create eggs for every Mariadb Version

**Comment by cfouche3005** [comment]
`container@pterodactyl~ Starting installation process, this could take a few minutes...
+ echo -e 'installing dependencies'
installing dependencies
+ apt-get -y update
           ]
Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
           
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
                                                                              f
                                                                  ]
                                  ]
           ]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
                                                                              1
                                                       ]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
                                                                              1
                                                      ]
Get:3 https://archive.mariadb.org/mariadb-10.6.7/repo/ubuntu focal InRelease [7767 B]
                                                      
                                  ]
           ]
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1592 kB]
                                 ]
                                              ]
Get:7 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [994 kB]
                                                   ]
                                              ]
Get:8 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [844 kB]
                                                        ]
                                              ]
Get:9 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [25.8 kB]
                                                                              0
                                              ]
Get:10 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
                                                         ]
                        ]
Get:11 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
                                                         ]
                                                           ]
Get:12 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
                                                           
Get:13 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
                                                           
                                                        ]
                                                              ]
                                                          ]
                                                           ]
                                                           ]
                                               ]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2017 kB]
                                                          ]
                                               ]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1063 kB]
                                                          ]
                                               ]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1136 kB]
                                                          ]
                                               ]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [29.4 kB]
                                                           ]
                                                            ]
                                                             ]
Get:18 https://archive.mariadb.org/mariadb-10.6.7/repo/ubuntu focal/main amd64 Packages [17.8 kB]
                                                                              .
                                                             ]
                                                ]
Get:19 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [26.0 kB]
                                                             ]
                          ]
Get:20 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [51.2 kB]
                                                       ]
                          ]
                          ]
                          ]
                          ]
                          ]
                          ]
                          ]
                          ]
             ]
Fetched 21.2 MB in 2s (12.8 MB/s)
Reading package lists... Done
+ apt-get -y install curl
Reading package lists... Done
Building dependency tree      %

Reading state information... Done
The following additional packages will be installed:
  krb5-locales libbrotli1 libcurl4 libgssapi-krb5-2 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 libnghttp2-14 libpsl5 librtmp1 libssh-4
  publicsuffix
Suggested packages:
  krb5-doc krb5-user
The following NEW packages will be installed:
  curl krb5-locales libbrotli1 libcurl4 libgssapi-krb5-2 libk5crypto3
  libkeyutils1 libkrb5-3 libkrb5support0 libnghttp2-14 libpsl5 librtmp1
  libssh-4 publicsuffix
0 upgraded, 14 newly installed, 0 to remove and 0 not upgraded.
Need to get 1713 kB of archives.
After this operation, 5408 kB of additional disk space will be used.
           ]
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 krb5-locales all 1.17-6ubuntu4.1 [11.4 kB]
                                       ]
           ]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libkrb5support0 amd64 1.17-6ubuntu4.1 [30.9 kB]
                                        ]
           ]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libk5crypto3 amd64 1.17-6ubuntu4.1 [79.9 kB]
                                    ]
            ]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 libkeyutils1 amd64 1.6-6ubuntu1 [10.2 kB]
                                      ]
            ]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libkrb5-3 amd64 1.17-6ubuntu4.1 [330 kB]
                                   ]
            ]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgssapi-krb5-2 amd64 1.17-6ubuntu4.1 [121 kB]
                                     ]
                        ]
Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 libpsl5 amd64 0.21.0-1ubuntu1 [51.5 kB]
                                ]
            ]
Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 publicsuffix all 20200303.0012-1 [111 kB]
                                      ]
                        ]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libbrotli1 amd64 1.0.7-6ubuntu0.1 [267 kB]
                                    ]
                        ]
Get:10 http://archive.ubuntu.com/ubuntu focal/main amd64 libnghttp2-14 amd64 1.40.0-1build1 [78.7 kB]
                                         ]
Get:11 http://archive.ubuntu.com/ubuntu focal/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2build1 [54.9 kB]
                                         
                                     ]
            ]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssh-4 amd64 0.9.3-2ubuntu2.2 [170 kB]
                                   ]
            ]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4 amd64 7.68.0-1ubuntu2.7 [234 kB]
                                  ]
            ]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 curl amd64 7.68.0-1ubuntu2.7 [161 kB]
                               ]
             ]
Fetched 1713 kB in 0s (9555 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package krb5-locales.
(Reading database ...
(Reading database ... 10095 files and directories currently installed.)
Preparing to unpack .../00-krb5-locales_1.17-6ubuntu4.1_all.deb ...
Unpacking krb5-locales (1.17-6ubuntu4.1) ...
Selecting previously unselected package libkrb5support0:amd64.
Preparing to unpack .../01-libkrb5support0_1.17-6ubuntu4.1_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.17-6ubuntu4.1) ...
Selecting previously unselected package libk5crypto3:amd64.
Preparing to unpack .../02-libk5crypto3_1.17-6ubuntu4.1_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.17-6ubuntu4.1) ...
Selecting previously unselected package libkeyutils1:amd64.
Preparing to unpack .../03-libkeyutils1_1.6-6ubuntu1_amd64.deb ...
Unpacking libkeyutils1:amd64 (1.6-6ubuntu1) ...
Selecting previously unselected package libkrb5-3:amd64.
Preparing to unpack .../04-libkrb5-3_1.17-6ubuntu4.1_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.17-6ubuntu4.1) ...
Selecting previously unselected package libgssapi-krb5-2:amd64.
Preparing to unpack .../05-libgssapi-krb5-2_1.17-6ubuntu4.1_amd64.deb ...
Unpacking libgssapi-krb5-2:amd64 (1.17-6ubuntu4.1) ...
Selecting previously unselected package libpsl5:amd64.
Preparing to unpack .../06-libpsl5_0.21.0-1ubuntu1_amd64.deb ...
Unpacking libpsl5:amd64 (0.21.0-1ubuntu1) ...
Selecting previously unselected package publicsuffix.
Preparing to unpack .../07-publicsuffix_20200303.0012-1_all.deb ...
Unpacking publicsuffix (20200303.0012-1) ...
Selecting previously unselected package libbrotli1:amd64.
Preparing to unpack .../08-libbrotli1_1.0.7-6ubuntu0.1_amd64.deb ...
Unpacking libbrotli1:amd64 (1.0.7-6ubuntu0.1) ...
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../09-libnghttp2-14_1.40.0-1build1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.40.0-1build1) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../10-librtmp1_2.4+20151223.gitfa8646d.1-2build1_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2build1) ...
Selecting previously unselected package libssh-4:amd64.
Preparing to unpack .../11-libssh-4_0.9.3-2ubuntu2.2_amd64.deb ...
Unpacking libssh-4:amd64 (0.9.3-2ubuntu2.2) ...
Selecting previously unselected package libcurl4:amd64.
Preparing to unpack .../12-libcurl4_7.68.0-1ubuntu2.7_amd64.deb ...
Unpacking libcurl4:amd64 (7.68.0-1ubuntu2.7) ...
Selecting previously unselected package curl.
Preparing to unpack .../13-curl_7.68.0-1ubuntu2.7_amd64.deb ...
Unpacking curl (7.68.0-1ubuntu2.7) ...
Setting up libkeyutils1:amd64 (1.6-6ubuntu1) ...
Setting up libpsl5:amd64 (0.21.0-1ubuntu1) ...
Setting up libbrotli1:amd64 (1.0.7-6ubuntu0.1) ...
Setting up libnghttp2-14:amd64 (1.40.0-1build1) ...
Setting up krb5-locales (1.17-6ubuntu4.1) ...
Setting up libkrb5support0:amd64 (1.17-6ubuntu4.1) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2build1) ...
Setting up libk5crypto3:amd64 (1.17-6ubuntu4.1) ...
Setting up libkrb5-3:amd64 (1.17-6ubuntu4.1) ...
Setting up publicsuffix (20200303.0012-1) ...
Setting up libgssapi-krb5-2:amd64 (1.17-6ubuntu4.1) ...
Setting up libssh-4:amd64 (0.9.3-2ubuntu2.2) ...
Setting up libcurl4:amd64 (7.68.0-1ubuntu2.7) ...
Setting up curl (7.68.0-1ubuntu2.7) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
+ echo -e 'adding container user'
adding container user
+ useradd -d /home/container -m container -s /bin/bash
+ chown container: /mnt/server/
+ echo -e 'getting my.conf'
getting my.conf
+ '[' -f /mnt/server/.my.cnf ']'
+ runuser -l container -c 'curl https://raw.githubusercontent.com/parkervcp/eggs/master/database/sql/mariadb/install.my.cnf > /mnt/server/.my.cnf'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5286  100  5286    0     0  31652      0 --:--:-- --:--:-- --:--:-- 31652
+ echo -e 'installing mysql database'
installing mysql database
+ runuser -l container -c 'mkdir -p /mnt/server/run/mysqld'
+ runuser -l container -c 'mkdir -p /mnt/server/log/mysql'
+ runuser -l container -c 'mkdir /mnt/server/mysql'
+ runuser -l container -c 'mysql_install_db --defaults-file=/mnt/server/.my.cnf'
Installing MariaDB/MySQL system tables in '/mnt/server/mysql' ...
2022-03-04  7:21:48 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system


Two all-privilege accounts were created.
One is root@localhost, it has no password, but you need to
be system 'root' user to connect. Use, for example, sudo mysql
The second is container@localhost, it has no password either, but
you need to be the system 'container' user to connect.
After connecting you can set the password, if you would need to be
able to connect as any of these users with a password and without sudo

See the MariaDB Knowledgebase at https://mariadb.com/kb

You can start the MariaDB daemon with:
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/mnt/server/mysql'

You can test the MariaDB daemon with mysql-test-run.pl
cd '/usr/mysql-test' ; perl mysql-test-run.pl

Please report any problems at https://mariadb.org/jira

The latest information about MariaDB is available at https://mariadb.org/.

Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

+ '[' -f /mnt/server/custom.my.cnf ']'
+ curl https://raw.githubusercontent.com/parkervcp/eggs/master/database/sql/mariadb/my.cnf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5335  100  5335    0     0  29475      0 --:--:-- --:--:-- --:--:-- 29475
+ echo -e 'install complete'
install complete
+ exit

[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:46809c5e3446e7c8a8ae8fde0e5a75c29ad38d127007dc89a485dddd6778acd6 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mariadb_10.6 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ { /usr/sbin/mysqld & } && sleep 5 && mysql -u root
2022-03-04  7:22:03 0 [Note] /usr/sbin/mysqld (server 10.6.7-MariaDB-1:10.6.7+maria~focal) starting as process 15 ...
2022-03-04  7:22:03 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-03-04  7:22:03 0 [Note] InnoDB: Number of pools: 1
2022-03-04  7:22:03 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-03-04  7:22:03 0 [Note] InnoDB: Using Linux native AIO
2022-03-04  7:22:03 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728
2022-03-04  7:22:03 0 [Note] InnoDB: Completed initialization of buffer pool
2022-03-04  7:22:03 0 [Note] InnoDB: 128 rollback segments are active.
2022-03-04  7:22:03 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-03-04  7:22:03 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-03-04  7:22:03 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-03-04  7:22:03 0 [Note] InnoDB: 10.6.7 started; log sequence number 42173; transaction id 14
2022-03-04  7:22:03 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-03-04  7:22:03 0 [Note] InnoDB: Loading buffer pool(s) from /home/container/mysql/ib_buffer_pool
2022-03-04  7:22:03 0 [Note] InnoDB: Buffer pool(s) load completed at 220304  7:22:03
2022-03-04  7:22:03 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2022-03-04  7:22:03 0 [Note] Server socket created on IP: '0.0.0.0'.
2022-03-04  7:22:03 0 [ERROR] Can't start server : Bind on unix socket: Read-only file system
2022-03-04  7:22:03 0 [ERROR] Do you already have another server running on socket: /run/mysqld/mysqld.sock ?
2022-03-04  7:22:03 0 [ERROR] Aborting
Warning: Memory not freed: 280
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:46809c5e3446e7c8a8ae8fde0e5a75c29ad38d127007dc89a485dddd6778acd6 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mariadb_10.6 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ { /usr/sbin/mysqld & } && sleep 5 && mysql -u root
2022-03-04  7:22:12 0 [Note] /usr/sbin/mysqld (server 10.6.7-MariaDB-1:10.6.7+maria~focal) starting as process 14 ...
2022-03-04  7:22:12 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-03-04  7:22:12 0 [Note] InnoDB: Number of pools: 1
2022-03-04  7:22:12 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-03-04  7:22:12 0 [Note] InnoDB: Using Linux native AIO
2022-03-04  7:22:12 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728
2022-03-04  7:22:12 0 [Note] InnoDB: Completed initialization of buffer pool
2022-03-04  7:22:12 0 [Note] InnoDB: 128 rollback segments are active.
2022-03-04  7:22:12 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-03-04  7:22:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-03-04  7:22:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-03-04  7:22:12 0 [Note] InnoDB: 10.6.7 started; log sequence number 42185; transaction id 14
2022-03-04  7:22:12 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-03-04  7:22:12 0 [Note] InnoDB: Loading buffer pool(s) from /home/container/mysql/ib_buffer_pool
2022-03-04  7:22:12 0 [Note] InnoDB: Buffer pool(s) load completed at 220304  7:22:12
2022-03-04  7:22:12 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2022-03-04  7:22:12 0 [Note] Server socket created on IP: '0.0.0.0'.
2022-03-04  7:22:12 0 [ERROR] Can't start server : Bind on unix socket: Read-only file system
2022-03-04  7:22:12 0 [ERROR] Do you already have another server running on socket: /run/mysqld/mysqld.sock ?
2022-03-04  7:22:12 0 [ERROR] Aborting
Warning: Memory not freed: 280
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
`
I have done more test since a pr have modified the docker, and I get this error
