### ISSUE TITLE
[Egg Request]:  viewtube

### ISSUE THREAD

**Issue by KaspianDev** [parkervcp/eggs#1570]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/ViewTube/viewtube-vue

### Links for the download

https://github.com/ViewTube/viewtube-vue#docker

### Links for the install docs

https://github.com/ViewTube/viewtube-vue/wiki/Installation

**Comment by parkervcp** [comment]
The nodejs egg could probably already run this. I have no interest in making an egg for it as a standalone.
