### ISSUE TITLE
[Egg Request]: Chatwoot

### ISSUE THREAD

**Issue by Phyroks** [parkervcp/eggs#1576]
### Does this expand an already existing service

No

### Link to a game or software

https://www.chatwoot.com/

### Links for the download

https://www.chatwoot.com/docs/self-hosted

### Links for the install docs

https://www.chatwoot.com/docs/self-hosted/deployment/docker

**Comment by gOOvER** [comment]
I think, this is not possible with Petro

**Comment by parkervcp** [comment]
This service uses 5 different containers to manage and it would need separate eggs. Which I have some eggs that this could use already this would be a complex and tedious setup to maintain in pterodactyl.
