### ISSUE TITLE
[Bug]: Issue starting stormworks server

### ISSUE THREAD

**Issue by RelativeSure** [parkervcp/eggs#1577]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

Stormworks

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it and play on it.

### Actual Behavior

Crashes with this 
mm_resource_mesh: unable to load file: meshes/component_inventory_equipment_coal
.mesh
Generated trainline in 4 attempts
Server created.
Connected to steam
wine: Unhandled page fault on write access to 8344B849 at address 7BC26466 (thread 0024), starting debugger...
0024:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 32 272" (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":99"
      after 185 requests (185 known processed) with 0 events remaining.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":99"
      after 15 requests (15 known processed) with 0 events remaining.

### Steps To Reproduce

Step 1: Install server
Step 2: Start server
Step 3: Crashes

### Install logs

https://pastebin.com/yqx2KzBM

**Comment by parkervcp** [comment]
Which egg are you using here?

**Comment by RelativeSure** [comment]
this one
https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/stormworks

**Comment by parkervcp** [comment]
you said steamworks and not stormworks. I was searching the repo for it,

**Comment by RelativeSure** [comment]
ah, sorry about that!

**Comment by gOOvER** [comment]
this Looks more like a Bug in Game or failed installation

**Comment by RelativeSure** [comment]
> this Looks more like a Bug in Game or failed installation 

Do you mean that I did something wrong in the installation or there's something wrong with the egg?

**Comment by Software-Noob** [comment]
I can't reproduce this. The first startup as always with Wine threw those errors and subsequent startups worked fine.

**Comment by RelativeSure** [comment]
Do you have any special programs installed that I might've missed?
Like do I need to install any software on the host server to make it work?

I use Debian 11 on a dedicated server from Hetzner. What about you?

**Comment by RelativeSure** [comment]
@Software-Noob 
I installed wine on my dedicated server and now the stormworks server works - Thanks!
