### ISSUE TITLE
[Bug]: Space engineers fails to start

### ISSUE THREAD

**Issue by includes08** [parkervcp/eggs#1578]
### Panel Version

1.6.2

### Wings Version

1.5.1

### Service

space engineers

### Modified

No, I did not modify the egg

### Expected Behavior

Startup

### Actual Behavior

`[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:90485be496339b1796a724923be06d4853fc0a934786131e48ea52da1e4303cf 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_wine-5 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 10.8
Current timezone: Etc/UTC
wine-6.0
steam user is not set.

Using anonymous user.

WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1646446107
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...Connectivity test: result=Connected, in progress=0
OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Please use force_install_dir before logon!
Success! App '298740' already up to date.
First launch will throw some errors. Ignore them
:/home/container$ cd /home/container/DedicatedServer64/; wine /home/container/DedicatedServer64/SpaceEngineersDedicated.exe -path Z:\\home\\container\\config -noconsole -ignorelastsession
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
2022-03-07 18:00:40.205: App Version: 01_200_030
2022-03-07 18:00:40.212: Is official: True [NO][NIS][NAMP]
2022-03-07 18:00:40.212: Environment.ProcessorCount: 8
2022-03-07 18:00:40.215: Environment.OSVersion: Microsoft Windows 7 Professional
 (Microsoft Windows NT 6.1.7601 Service Pack 1)
2022-03-07 18:00:40.215: Environment.CommandLine: "Z:\home\container\DedicatedSe
rver64\SpaceEngineersDedicated.exe" -path Z:\home\container\config -noconsole -i
gnorelastsession
2022-03-07 18:00:40.215: Environment.Is64BitProcess: True
2022-03-07 18:00:40.215: Environment.Is64BitOperatingSystem: True
2022-03-07 18:00:40.216: Environment.Version: .NET Framework 4.8.3761.0
2022-03-07 18:00:40.216: Environment.CurrentDirectory: Z:\home\container\Dedicat
edServer64
2022-03-07 18:00:40.216: CPU Info: AMD Ryzen 9 5950X 16-Core Processor
2022-03-07 18:00:41.343: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
dbus[66]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007F4A21DB47BB (thread 0060), starting debugger...
wine client error:164: write: Bad file descriptor
2022-03-07 18:00:53.394: Error: No IP assigned.`

**IF I ADD THE EXTERNAL IP IN THE CONFIG**

`container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:90485be496339b1796a724923be06d4853fc0a934786131e48ea52da1e4303cf 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_wine-5 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 10.8
Current timezone: Etc/UTC
wine-6.0
steam user is not set.

Using anonymous user.

WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1646446107
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...Connectivity test: result=Connected, in progress=0
OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Please use force_install_dir before logon!
Success! App '298740' already up to date.
First launch will throw some errors. Ignore them
:/home/container$ cd /home/container/DedicatedServer64/; wine /home/container/DedicatedServer64/SpaceEngineersDedicated.exe -path Z:\\home\\container\\config -noconsole -ignorelastsession
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
2022-03-07 18:05:14.725: App Version: 01_200_030
2022-03-07 18:05:14.732: Is official: True [NO][NIS][NAMP]
2022-03-07 18:05:14.732: Environment.ProcessorCount: 8
2022-03-07 18:05:14.735: Environment.OSVersion: Microsoft Windows 7 Professional
 (Microsoft Windows NT 6.1.7601 Service Pack 1)
2022-03-07 18:05:14.735: Environment.CommandLine: "Z:\home\container\DedicatedSe
rver64\SpaceEngineersDedicated.exe" -path Z:\home\container\config -noconsole -i
gnorelastsession
2022-03-07 18:05:14.735: Environment.Is64BitProcess: True
2022-03-07 18:05:14.735: Environment.Is64BitOperatingSystem: True
2022-03-07 18:05:14.735: Environment.Version: .NET Framework 4.8.3761.0
2022-03-07 18:05:14.736: Environment.CurrentDirectory: Z:\home\container\Dedicat
edServer64
2022-03-07 18:05:14.736: CPU Info: AMD Ryzen 9 5950X 16-Core Processor
2022-03-07 18:05:15.859: Bind IP : 185.216.162.57:27016
Setting breakpad minidump AppID = 244850
2022-03-07 18:05:17.735: Error binding server endpoint: Unknown error (0x2726)
dbus[66]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007F5D4F2097BB (thread 0060), starting debugger...
wine client error:160: write: Bad file descriptor
CreateBoundSocket: ::bind to port 0 returned error [no name available](10022)
CreateBoundSocket: ::bind to port 0 returned error [no name available](10022)`

is there a solution to fix this?

### Steps To Reproduce

Run the egg

### Install logs

*

**Comment by includes08** [comment]
https://github.com/parkervcp/eggs/issues/1400 same issue as the following.

**Comment by Syntax3rror404** [comment]
Are you using the latest egg.json? You must using predefined map or generate a map on your system and uploading it. If you change the map name it won't work. I tried the egg and I have no problem at all.

**Comment by includes08** [comment]
Seems like the issue is remote api, as soon as you enable it it doesn't start anymore.

**Comment by includes08** [comment]
@Syntax3rror404

**Comment by TuEye** [comment]
I see 3 problems here at the moment.

First, the problem with "Error: No IP assigned". 
This error can occur regardless of whether a bind IP is specified or not. When starting the game, an attempt is made to determine the public IP address via the Steam API. If this does not work > Error: No IP assigned and abort. There are already bug reports about this ([Link1](https://support.keenswh.com/spaceengineers/pc/topic/23390-error-no-ip-assigned) / [Link2](https://support.keenswh.com/spaceengineers/pc/topic/error-no-ip-assigned)) and several other Docker SE implementations also seem to suffer from this problem. The only "solution" seems to be to restart the container until it runs. 

And the remote api really makes the server stop starting (just like issue #1602). At least with the used Wine image. With a slightly modified Wine 6 image (and egg) I was able to start the server including the remote api. But it was still not useful, because apparently there is a small problem in connection with Wine and its httpapi.dll ([Link](https://github.com/Devidian/docker-spaceengineers/discussions/14)) which makes the use of the Api impossible at the moment. Therefore, the remote api should not or cannot be used at the moment.

And the last problem: 
In the second log you had specified your public WAN IP as bind IP. However, the server needs the interface IP (e.g. 172.18.0.99) of the container, otherwise it cannot connect to any interface and crashes. 

I suppose I should add this information to the egg readme.

**Comment by gOOvER** [comment]
> I see 3 problems here at the moment.
> 
> First, the problem with "Error: No IP assigned". This error can occur regardless of whether a bind IP is specified or not. When starting the game, an attempt is made to determine the public IP address via the Steam API. If this does not work > Error: No IP assigned and abort. There are already bug reports about this ([Link1](https://support.keenswh.com/spaceengineers/pc/topic/23390-error-no-ip-assigned) / [Link2](https://support.keenswh.com/spaceengineers/pc/topic/error-no-ip-assigned)) and several other Docker SE implementations also seem to suffer from this problem. The only "solution" seems to be to restart the container until it runs.
> 
> And the remote api really makes the server stop starting (just like issue #1602). At least with the used Wine image. With a slightly modified Wine 6 image (and egg) I was able to start the server including the remote api. But it was still not useful, because apparently there is a small problem in connection with Wine and its httpapi.dll ([Link](https://github.com/Devidian/docker-spaceengineers/discussions/14)) which makes the use of the Api impossible at the moment. Therefore, the remote api should not or cannot be used at the moment.
> 
> And the last problem: In the second log you had specified your public WAN IP as bind IP. However, the server needs the interface IP (e.g. 172.18.0.99) of the container, otherwise it cannot connect to any interface and crashes.
> 
> I suppose I should add this information to the egg readme.

The problem here was your installscript, becasue you install WINE4 in installscript and the image uses 7.0. Thats not possible. i rewrote the complete egg and it should work now ;)

https://github.com/parkervcp/eggs/issues/1602#issuecomment-1304414645
