### ISSUE TITLE
[Egg Request]: Long-vinter

### ISSUE THREAD

**Issue by Sergentval** [parkervcp/eggs#1579]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1635450/Longvinter/

### Links for the download

https://github.com/Uuvana-Studios/longvinter-linux-server

### Links for the install docs

https://docs-server.longvinter.com/

**Comment by gOOvER** [comment]
i dont have the game. You can send me a game Key, then i can create the egg

**Comment by Vibeshibe** [comment]
1+

Longvinter also supports Docker now:
https://docs-server.longvinter.com/windows/setup-docker/

**Comment by gOOvER** [comment]
Longvinter works fine. Not need for the dockerguide
