### ISSUE TITLE
Cant connect to 7dtd server (v 17.1)

### ISSUE THREAD

**Issue by JayJay1989** [parkervcp/eggs#158]
Panel Version: latest
Daemon Version: latest
Service: 7 days to die (17.1)
Modified: no

Expected Behavior: 
can connect to server

Actual Behavior:
Cannot to server, 'Connection timed out'

server config:
ufw disabled & stopped.

Steps to Reproduce:
1. update egg form your repo
2. create server
3. start server
4. start the game
5. connect to the server
6. Connection timed out

**Comment by parkervcp** [comment]
Can you give me anything like the console output from the panel?

**Comment by JayJay1989** [comment]
sure: [panel log](https://gist.github.com/JayJay1989/78083c6994c5f179f41aff5d13909c44)

it just starts fine, it is in the public game server list, but cannot join it for some reason

**Comment by parkervcp** [comment]
I was asking for the log that the panel console outputs. That looks like it missing some things like the RCON coming up and other things. I assume that is the actual server log.

**Comment by parkervcp** [comment]
Should look more like this - https://gist.github.com/parkervcp/0c1d7be1b867e12b50dee22a8530cad4

**Comment by parkervcp** [comment]
Did you assign all the port required to run the server (minimum 3)?

**Comment by JayJay1989** [comment]
i updated that log btw. i did, but the values are not assigned. as you can read in the updated log. Also the serverconfig.xml get with every reboot corrupted. I get <root> values stacking. thats why i changed the startup script using the copy

**Comment by parkervcp** [comment]
What I am looking for is this - 
![image](https://user-images.githubusercontent.com/1207679/52535358-68600180-2d1b-11e9-9b54-967c8cd171f6.png)

**Comment by JayJay1989** [comment]
[log panel](https://gist.github.com/JayJay1989/fd2ff7d39a1adc15721841bc14d89a4c)

**Comment by parkervcp** [comment]
Did you assign all the ports required

default is 26900-26902 at a minimum.

**Comment by JayJay1989** [comment]
there's only one port required. telnet or webpanel is optional

**Comment by parkervcp** [comment]
The other 2 are game server ports.

**Comment by parkervcp** [comment]
There are 3 server ports. I call this out in the [README](https://github.com/parkervcp/eggs/blob/master/source_servers/7_days_to_die/README.md).

There is a reason I make README's for the eggs.

**Comment by parkervcp** [comment]
Their official docs even call out needing extra ports... - https://7daystodie.gamepedia.com/Server#Port_Forwarding

**Comment by JayJay1989** [comment]
also after port 26900-26902 assigned, the xml got corrupted with multiple <root> after each reboot
[see here](https://gist.github.com/JayJay1989/dfc75c7ca1a36491aeba521bef55e1cb)

**Comment by parkervcp** [comment]
I am looking into that issue right now. Trying to figure out how to edit the xml properly using the parser. It's not exactly a clean config file.

Open a separate issue for the xml config corruption.

**Comment by AndyLee1024** [comment]
Can you fix this bug?

**Comment by parkervcp** [comment]
@AndyLee1024 Please see the previous message about the xml corruption

**Comment by AndyLee1024** [comment]
Yes, I think it's a bug. Because  in 7d2d's serverconfig, Serverport like         <property name="ServerPort" value="26900"/> but  eggs find ServerPort then replace it.  So that action will damage the serverconfig.xml

**Comment by AndyLee1024** [comment]
Hi, developer. Thank you for your contribution.
I found that the 7d2d egg has two bugs.
1. Startup property don't need $,  It will cause can't connect to server. 
 
<img width="1471" alt="1234" src="https://user-images.githubusercontent.com/3479173/58691788-8c754a80-83bf-11e9-804b-cc6a1cdb1ad3.png">

2. I think deamon's  xml find and repleace Feature Incompatible with 7d2d's serverconfig.xml

can you fix it ?

**Comment by parkervcp** [comment]
The $ is for a veriable and it gets replaced.

**Comment by parkervcp** [comment]
@AndyLeo1024 I have said to open a new issue if you needed anything.
