### ISSUE TITLE
[Egg Request]: VPN Eggs

### ISSUE THREAD

**Issue by TeunSchrader** [parkervcp/eggs#1580]
### Does this expand an already existing service

No

### Link to a game or software

https://pivpn.io/

### Links for the download

https://github.com/InnovativeInventor/docker-pivpn

### Links for the install docs

In the readme

**Comment by WavingCatDevs** [comment]
This would be cool to have, +1

**Comment by AlpacaServers** [comment]
Its for pi i dont know if its compatible with x86
but good idea

**Comment by parkervcp** [comment]
This will not offer any sort of performance as it will run in user space.
