### ISSUE TITLE
[Egg Request]: Azuracast 

### ISSUE THREAD

**Issue by SadisticSurgeon** [parkervcp/eggs#1581]
### Does this expand an already existing service

No

### Link to a game or software

https://www.azuracast.com/

### Links for the download

https://docs.azuracast.com/en/getting-started/installation/docker

### Links for the install docs

https://docs.azuracast.com/en/getting-started/installation/docker

**Comment by parkervcp** [comment]
as per #953 I am going to say no to this one.

**Comment by SadisticSurgeon** [comment]
I just put this in because they recently updated to only use one docker container.
