### ISSUE TITLE
[Bug]: ^C not sending SIGINT on Java egg

### ISSUE THREAD

**Issue by JasonHorkles** [parkervcp/eggs#1585]
### Panel Version

1.7.0

### Wings Version

1.6 I think - not entirely sure how to check but I just got it

### Service

Discord Java 17

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

The stop command `^C` should send a SIGINT, just like the pterodactyl Java egg, which works fine (ghcr.io/pterodactyl/yolks:java_17)

### Actual Behavior

`^C` just seems to kill the instance instead

### Steps To Reproduce

1. Use the ghcr.io/parkervcp/yolks:java_17 egg
2. Run a jar that properly utilizes a shutdown hook (code below)
3. Press stop and see that it doesn't say "Shutting down..."

```java
public class Main {
    public static void main(String[] args) throws InterruptedException {
        // Shutdown hook
        Runtime.getRuntime().addShutdownHook(new Thread(() -> System.out.println("Shutting down...")));

        while (true) {
            System.out.println("Program active...");
            Thread.sleep(1000);
        }
    }
}
```

### Install logs

https://paste.gg/p/JasonHorkles/68f4cd68873442e7a4d5624492696ad4

**Comment by parkervcp** [comment]
This is a known issue with the fact that we use eval and not exec.

**Comment by JasonHorkles** [comment]
Ah alright. Is there any way to work around this or should I just continue to use the ptero egg instead?

**Comment by parkervcp** [comment]
You can make your own container to runt hings but so far this is the best option we have.

**Comment by BasToTheMax** [comment]
Try to use ^^C

**Comment by JasonHorkles** [comment]
> Try to use ^^C

Doesn't work, same issue

**Comment by xF4m3** [comment]
I am not sure if this is the same issue/bug but on the ARK Survival Egg i am getting the exact same issue using the Trap command in the startup command to catch the ^C does not work, it just kills the instance. I was in the discord and it seems like this was working at some Point, so something must have changed since then.
The Ark egg uses the ghcr.io/parkervcp/games:source container

(I am writing here cause it seems to me its the same issue, so i dont want to create a new issue that just gets closed and linked to this.) If needed i can create a seperate issue.

**Comment by parkervcp** [comment]
> If needed i can create a seperate issue.

This should be a different git issue if anything

**Comment by Tomasan7** [comment]
For me, using this java egg: https://github.com/parkervcp/eggs/tree/master/generic/java has the same problem. It just doesn't get killed by itself, but is stopping forever.

**Comment by JasonHorkles** [comment]
An alternative I've been using was just having the program listen for "stop" and have the panel run that instead

**Comment by QuintenQVD0** [comment]
This was fixt with tini
