### ISSUE TITLE
[Bug]: Can't join Satisfactory Server

### ISSUE THREAD

**Issue by rockof73** [parkervcp/eggs#1594]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

Satisfactory

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Being able to log into the server.

### Actual Behavior

The server load in the "Server manager", but after creating the world and try to join it, the game reload after 20-25 seconds and an error pop up.
![sfconnerr](https://user-images.githubusercontent.com/100205324/160289035-0d82efb0-d64f-4acc-9c84-5d60543bcaf9.png)

### Steps To Reproduce

Step 1: Install satisfactory's egg. (Only change the value of "Upload Crash Reports" to false).
Step 2: Add the server to server manager inside of Satisfactory. ("IP adress" in ip field and "15777" in the port field).
Step 3: Claim the server by setting a name and an admin password.
Step 3: Create the world.
Step 4: Click "Join the game" (I have the game language in Italian so don't know what is the correct name of the button in english.).

### Install logs

https://pastebin.com/raw/qyMx2TS2

**Comment by parkervcp** [comment]
Where are you hosting this? Have you checked firewalls? Did you forward the port to the server? Did you forward both TCP and UDP where needed?

**Comment by gOOvER** [comment]
He use only 2 Ports and 12 Port twice

`Command Line:  ?listen -Port=15777 -ServerQueryPort=15777`

**Comment by rockof73** [comment]
Solved. The primary port must be setted to 7777.
