### ISSUE TITLE
[Bug]: standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by Isaac-Cooper** [parkervcp/eggs#1595]
### Panel Version

1.7.0

### Wings Version

Not too sure on how to find the wings version

### Service

Minio

### Modified

No, I did not modify the egg

### Expected Behavior

Should work

### Actual Behavior

Server crashed with error: standard_init_linux.go:228: exec user process caused: exec format error

### Steps To Reproduce

Import mini egg,
create a server using the mini egg
start the server and then I got this error.

### Install logs

Not too sure how do do this.

**Comment by HyperKiko** [comment]
thatss probably an arch problem (arm64 vs amd64)

**Comment by Isaac-Cooper** [comment]
How can I fix this?

**Comment by parkervcp** [comment]
This is an arm64 vs amd64 issue. You would need to build a custom image for the egg.

**Comment by Isaac-Cooper** [comment]
How would I go about doing that?

**Comment by Software-Noob** [comment]
You could try using the base Debian image, which is multi-arch. `ghcr.io/parkervcp/yolks:debian`

Otherwise, you can either create a custom image or open an issue/PR to implement the required packages. The minio egg is using an old ubuntu image that's built for amd64 only.
