### ISSUE TITLE
[Egg Request]:  OpenSpeedTest

### ISSUE THREAD

**Issue by M3MRY** [parkervcp/eggs#1596]
### Does this expand an already existing service

No

### Link to a game or software

https://openspeedtest.com/

### Links for the download

https://openspeedtest.com/speed-testing-application-for-your-website.php

### Links for the install docs

https://openspeedtest.com/speed-testing-application-for-your-website.php

**Comment by gOOvER** [comment]
this is nothing for Pterodactyl. Ptero is for Gameserver Hosting, not for hosting  Websites. You can use it with Portainer

**Comment by parkervcp** [comment]
While I don't agree with how goover said it, I agree that this is not something pterodactyl was built to host. There are better services to manage and host websites and webpages.
