### ISSUE TITLE
Wurm Unlimited

### ISSUE THREAD

**Issue by ZakDank** [parkervcp/eggs#160]
Service: 
Wurm Unlimited

Link to game: 
https://store.steampowered.com/app/366220/Wurm_Unlimited/
https://steamdb.info/app/402370/

Info:
https://www.wurmpedia.com/index.php/Server_administration_(Wurm_Unlimited)

**Comment by NgLoader** [comment]
Currently testing [Script](https://github.com/NgLoader/pterodactyl-eggs/tree/wurm_unlimited/wurm_unlimited/wurm_unlimited/wurm_unlimited)

**Comment by NgLoader** [comment]
Update: https://gitlab.com/_pterodactyl/eggs/tree/master/Wurm-Unlimited

**Comment by gOOvER** [comment]
@NgLoader after 4 years :D i have a running egg of Wurm, but it nieeds an own image. Thats why i dont make it public :) Let me know, if you need it :P

**Comment by NgLoader** [comment]
Nice, the ``Wurm Unlimited`` egg where I was working on was for @ZakDank .
When you like you can ask him if he still needs it.

**Comment by ZakDank** [comment]
Yes - still interested in this @gOOvER

**Comment by gOOvER** [comment]
@ZakDank i sended the egg via discord for testing
