### ISSUE TITLE
[Bug]: No ressources display Project Zomboid Egg

### ISSUE THREAD

**Issue by Xen0Xys** [parkervcp/eggs#1601]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

Project ZOmboid

### Modified

No, I did not modify the egg

### Expected Behavior

See the ressource usage (working on all others server)
![image](https://user-images.githubusercontent.com/47594493/161445620-bb9e47d5-73b4-473a-964d-a081821c08cd.png)

### Actual Behavior

The ressource usage not display correctly

### Steps To Reproduce

Install Project Zomboid egg
Create and start the server
See the problem

### Install logs

Log command not working... It just freeze

**Comment by parkervcp** [comment]
This is a know issue and not caused by the egg.
https://github.com/pterodactyl/panel/issues/3999
