### ISSUE TITLE
[Bug]: git pull not working for me

### ISSUE THREAD

**Issue by louisplayz-inc-ask** [parkervcp/eggs#1603]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

discord/discord.js

### Modified

No, I did not modify the egg

### Expected Behavior

pulling my repo

### Actual Behavior

i entered the information  
![image](https://user-images.githubusercontent.com/98408573/161613426-93f896a2-8aac-4f2d-88a2-1444631628e9.png)
(prived repo)

but its not pulling it 

### Steps To Reproduce

none

### Install logs

'/var/log/pterodactyl/install/*.log': No such file or directory

**Comment by gOOvER** [comment]
its all OK with your pull and No need to Open after a endless senseless discussion on Discord Here a Ticket.

its Not a Bug anx Support only in discord

**Comment by gOOvER** [comment]
> but its not pulling for me so thats why i'm here

It's pulling for you. All logs you are posted on discord showed, that your bot ist working. So sth is pulled ;) There are no error and 3 gus told you that.

This can be closed, becasue no log contain any error and he can't explain the error. See Discord last night (CET)

**Comment by gOOvER** [comment]
> eh no its not puling on the server because i see a command on the github but not on the server

Should i post your log from discords, where everyone see's that your bot is running from your private Repo?

@parkervcp this can ber closed. all needed logs are in discord. no log shows any error and his bot runs as it should

**Comment by Louissplayz** [comment]
because is was uploaded via smtp

**Comment by Louissplayz** [comment]
and NOT pulled

**Comment by Louissplayz** [comment]
how?

**Comment by parkervcp** [comment]
Both the bot on discord and when you create an issue request logs. The commands to do it are there.

For your information.  
`tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99`

**Comment by Louissplayz** [comment]
'/var/log/pterodactyl/install/*.log': No such file or directory
[message.txt](https://github.com/parkervcp/eggs/files/8420398/message.txt)

**Comment by Louissplayz** [comment]
i tryed on an new server with no files and for me it did not pull

**Comment by parkervcp** [comment]
did you specify a repo or set the upload variable to 1. I believe that skips the installer.

**Comment by Louissplayz** [comment]
yea this https://github.com/utools-official/utools-offlicial-bot but its prived

**Comment by Louissplayz** [comment]
but i think its something with the github personal token scopes

**Comment by Louissplayz** [comment]
oh forgot to say 

upload variable is already on  1

**Comment by QuintenQVD0** [comment]
> oh forgot to say
> 
> upload variable is already on 1

It should be 0 if you want to pull files

**Comment by QuintenQVD0** [comment]
This is clearly misconfiguration, for that come to the discord as the generic nodejs git pull works just fine.
