### ISSUE TITLE
[Bug]: Subnautica File Not found

### ISSUE THREAD

**Issue by vRazgriz1** [parkervcp/eggs#1604]
### Panel Version

1.7

### Wings Version

1.6

### Service

subnautica

### Modified

No, I did not modify the egg

### Expected Behavior

Subnautica to start/Run

### Actual Behavior

[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Status: Image is up to date for quay.io/pterodactyl/core:mono 
Digest: sha256:a7b7e6641ecb3512eb4b116ec3c3266ddfd41056745b0de084185353b882b185 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Status: Image is up to date for quay.io/pterodactyl/core:mono 
Digest: sha256:a7b7e6641ecb3512eb4b116ec3c3266ddfd41056745b0de084185353b882b185 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

Install egg
Then run

### Install logs

https://pteropaste.com/a8td9g

**Comment by parkervcp** [comment]
From your install logs. 

```
Archive:  /mnt/server/nitrox/Nitrox.1.6.0.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /mnt/server/nitrox/Nitrox.1.6.0.0.zip or
        /mnt/server/nitrox/Nitrox.1.6.0.0.zip.zip, and cannot find /mnt/server/nitrox/Nitrox.1.6.0.0.zip.ZIP, period.
```


As far as I can tell then it's a download issue or something with the Nitrox release.

**Comment by vRazgriz1** [comment]
Should I try and use the 1.5.0 version? 
I have tired manually downloading it off of their website and starting up as well. I believe I get the same issue. Do we know of a workaround?

**Comment by vRazgriz1** [comment]
Can confirm that 1.5.0.1 works. It must be something with the 1.6.0.0 version, either its not being downloaded correctly or the egg does not know how to unpack/find the zip file

**Comment by Software-Noob** [comment]
The 1.6.0 release zip name has changed. We'll have to update the egg to work with it.

**Comment by ClassyCustom** [comment]
![image](https://user-images.githubusercontent.com/37226417/163627533-99104ebd-1563-435d-b7be-40f7d966dd5c.png)
I think this is also a problem after the name of the zip file
