### ISSUE TITLE
[Bug]: Cannot connect to ark

### ISSUE THREAD

**Issue by Saelman** [parkervcp/eggs#1607]
### Panel Version

1.6.6

### Wings Version

v1.5.3

### Service

Ark

### Modified

No, I did not modify the egg

### Expected Behavior

Players able to connect

### Actual Behavior

Players get time out

### Steps To Reproduce

Start service and connect

### Install logs

nothing happens when I run this.

**Comment by Saelman** [comment]
I've bound all ports 
![Screenshot 2022-04-06 230418](https://user-images.githubusercontent.com/24628383/162112093-8495fe50-7285-49a4-b40c-44ee0f9479eb.png)
port forward everything as needed. Players can see the server as online but when attempting to connect they get timed out.

**Comment by Software-Noob** [comment]
The primary port is 7777 udp and not the query tcp port. They connect to 27015.

**Comment by Saelman** [comment]
Switched ports. Still not able to connect. double checked all ports are forwarded.

**Comment by 32Puschel** [comment]
I have the same Issue.

**Comment by Saelman** [comment]
so. in my case I had a proxy server in VMWare I forgot about that was trying to bind to the port aswell. Once I killed the proxy server they connected no problem..
