### ISSUE TITLE
[Bug]: Bastion Egg not working due to it's updates

### ISSUE THREAD

**Issue by yesBad** [parkervcp/eggs#1609]
### Panel Version

1.7.0

### Wings Version

1.5.3 (customized)

### Service

Bastion

### Modified

No, I did not modify the egg

### Expected Behavior

It would install successfully & start.

### Actual Behavior

It installs fine, but it doesn't seem to be updated with the newest bastion updates as it can't start. Their stuff has changed, atleast the docs say use some .sh file in the pulled repo. They also seem to have changed from yarn -> npm etc... 

### Steps To Reproduce

1. Install the server with the egg.
2. Press start
3. See it not work :(

### Install logs

tail is stuck & nothing wrong with install :)

**Comment by Corza** [comment]
I am also having this issue, are there any updates for this? :)

**Comment by Jm15itch** [comment]
I'm having this issue will there be a fix?

**Comment by QuintenQVD0** [comment]
> I'm having this issue will there be a fix?

Do you have any logs? With does not work we are nothing.

**Comment by Jm15itch** [comment]
First, the bot tokens for discord aren't 64 characters long despite the bastion egg having it set to a max of 64. 
But the major error seems to be bastion throwing an error. The file attached is the output.

[output.txt](https://github.com/parkervcp/eggs/files/9908260/output.txt)

**Comment by QuintenQVD0** [comment]
yea something is wrong, I do not have the skills to fix that startup cmd.

**Comment by gOOvER** [comment]
Bastion updated to v3 and the egg is not compatible with latest Bastion Bot
