### ISSUE TITLE
Request for Starbound

### ISSUE THREAD

**Issue by MothGirlMusic** [parkervcp/eggs#161]
Please fill out the information bellow and remove from the line up
---------------
Service: (Ex. minecraft/factorio/etc)
Starbound

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://store.steampowered.com/app/211820/Starbound/

**Comment by NgLoader** [comment]
For what is this issue?

**Comment by zCodeg** [comment]
Its probably a request for Starbound egg, which is here already: https://github.com/parkervcp/eggs/tree/master/source_servers/starbound

**Comment by parkervcp** [comment]
Starbound already exists. If there is an issue please fill out all the information in the template.

**Comment by MothGirlMusic** [comment]
oh.. i guess i didn't see it i thought i had looked it over completely. i apologize then.
