### ISSUE TITLE
[Bug]: ALT:V Cant seem to join server, Blurry screen idles

### ISSUE THREAD

**Issue by augesrob** [parkervcp/eggs#1617]
### Panel Version

1.7.0

### Wings Version

not sure

### Service

ALT:V

### Modified

No, I did not modify the egg

### Expected Behavior

Install server fresh, Try to connect using server ip
Enters the game without download prompt

### Actual Behavior

Joins a empty map all blurry screen.

### Steps To Reproduce

Install on fresh server
Changed password to 123456789
Restart server 
attempted to join server.

### Install logs

x

**Comment by gOOvER** [comment]
logs? because this Report say not really something

**Comment by DatMayo** [comment]
This is the default behaviour. You need to spawn the player, otherwise you cam will be stuck at X: 0 Y: 0 Z: 0. There are many good tutorials out there, which cover everything u need
