### ISSUE TITLE
How do i use any of this?

### ISSUE THREAD

**Issue by MothGirlMusic** [parkervcp/eggs#162]
its not a bug, but i don't know where else to ask this.. 

but after installing pterodactyl, it seems to want me to upload a single file and these are a bunch of folders with a bunch of different files in it. are they supposed to be zipped up? i'm very confused as i've never imported anything before.. there's no documentation on the website besides actually installing pterodactyl.. and the website also links to this GitHub.. which also doesn't have any documentation on how to import eggs. so, how do you import something from your GitHub here? i'm trying to import nukkit

**Comment by Sir3lit** [comment]
You download the egg's json file, and import it.

Also, use the discord for support :)

**Comment by MothGirlMusic** [comment]
thank you so much!

**Comment by schrej** [comment]
Maybe we should add instructions to the root readme.
