### ISSUE TITLE
[Bug]: FiveM Egg

### ISSUE THREAD

**Issue by broimsuperman** [parkervcp/eggs#1626]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

Install, start, then get up and running.

### Actual Behavior

After installing, it will attempt to start then will display this following error:
"standard_init_linux.go:228: exec user process caused: exec format error"

### Steps To Reproduce

Step 1: Add latest FiveM egg to your Nests. 
Step 2: Create a server & install
Step 3: Press Start

### Install logs

(doesn't work)

**Comment by parkervcp** [comment]
If you are running on ARM this will not work for you.
