### ISSUE TITLE
[Egg Request]: Counter Strike: Source

### ISSUE THREAD

**Issue by Lightningblade** [parkervcp/eggs#1629]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/240/CounterStrike_Source/

### Links for the download

https://store.steampowered.com/app/240/CounterStrike_Source/

### Links for the install docs

SteamCMD id 240

**Comment by parkervcp** [comment]
the steamcmd custom egg should be able to run this already. It's built into the panel as a default egg.
