### ISSUE TITLE
[Bug]: Magma egg fails to download server files

### ISSUE THREAD

**Issue by Razernok** [parkervcp/eggs#1632]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

eggs/game_eggs/minecraft/java/magma/

### Modified

No, I did not modify the egg

### Expected Behavior

the server to be fully installed

### Actual Behavior

no files are download or installed

### Steps To Reproduce

setup a server for any mc version of magma.
nothing is downloaded or installed

Note: appears magma now uses api.magmafoundation.org/api/v2/{version}/latest/download

### Install logs

https://pteropaste.com/epqqgm

**Comment by Software-Noob** [comment]
It's broken because the project was deleted and later appeared back, but this time with a completely different API and on Gitlab. I can take a look into changing it to use their new API.
