### ISSUE TITLE
[Bug]: Satisfactory Server runs behind system time

### ISSUE THREAD

**Issue by SneaKz123** [parkervcp/eggs#1635]
### Panel Version

1.7.0

### Wings Version

1.7.0

### Service

steamcmd_servers/satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Server should run in Timezone UTC +2 (Germany/Berlin)

### Actual Behavior

Server runs in Timezone UTC +0 (So the Server runs two hours behind)

### Steps To Reproduce

I don’t know how to reproduce the Bug.

This only occurs on Satisfactory installations.
The Node Servers and also the Panel Server have the correct timezone (UTC +2) set.

### Install logs

https://pastebin.com/nwKK8rZ6

**Comment by Software-Noob** [comment]
That sounds like an issue with Satisfactory itself. The last time I played it, the timezone for logs was hardcoded. Where exactly is the timezone wrong, what's the timezone value of the container and in your Wings config for the instance that's hosting the Satisfactory server?

**Comment by SneaKz123** [comment]
Hey @Software-Noob 

as i already wrote in the section "Steps To Reproduce" Every timezone is set to UTC +2

The Console times from the satisfactory console are running behind two hours. also every log runs behind two hours.

**Comment by gOOvER** [comment]
The problem is the Image itself;

https://github.com/parkervcp/yolks/blob/cc7a9d0da5a402c22d10a7923fa1141a4757db21/games/source/entrypoint.sh#L29

It's set to UTC

**Comment by parkervcp** [comment]
`TZ=${TZ:-UTC}` Defaults `TZ` to `UTC` unless `TZ` is set. It's a bash operation.  
https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_03.html

On top of this looking like a satisfactory bug.

**Comment by SneaKz123** [comment]
Thanks for the answers.

So i will wait for some Satisfactory Updates and hopefully a fix in the future
