### ISSUE TITLE
[Bug]: code-server not starting

### ISSUE THREAD

**Issue by blockiyt** [parkervcp/eggs#1636]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

code-server

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, run it, and go on code-server

### Actual Behavior

Server crashed with error:
![IMG_1433](https://user-images.githubusercontent.com/65811753/166969776-473747f8-cb00-45e6-b1ae-49ab8914de9a.jpeg)

### Steps To Reproduce

Import code-server egg, create new server and try to start it

### Install logs

https://just-paste.it/8Az5l32Ziv

**Comment by blockiyt** [comment]
I edited the issue @QuintenQVD0 and pasted the log

**Comment by parkervcp** [comment]
This looks like you are trying to run this on a ARM based machine.

**Comment by blockiyt** [comment]
yeah I do, this node is a raspberrypi 4, is that a problem?

**Comment by parkervcp** [comment]
That's why the install is failing. It's trying to use an x84_64 image.

**Comment by jannis6023** [comment]
> yeah I do, this node is a raspberrypi 4, is that a problem?

Why shall one run Ptero on a Raspi?! xD

**Comment by jannis6023** [comment]
> ahhh I understand, so I shouldn't run ptero nodes on arm, right?

"besser isses" xD

**Comment by QuintenQVD0** [comment]
there is a codeserver release for arm:
![afbeelding](https://user-images.githubusercontent.com/67589015/166975597-0676559c-1b52-42c0-a835-ae67bf3d2823.png)
And the parcker nodejs 17 image is build for arm

**Comment by gOOvER** [comment]
Not only the install image is not for arm64,

in installscripot, only amd64 will be installed:

`MATCH=linux-amd64`

**Comment by gOOvER** [comment]
> > ahhh I understand, so I shouldn't run ptero nodes on arm, right?
> 
> "besser isses" xD

geht auch in englisch ;)

**Comment by QuintenQVD0** [comment]
@blockiyt I quickly tryed to rewrite the egg to support arm64 

but I do not have a arm64 machine online atm can you test it out for me: https://pteropaste.com/cl27ik

**Comment by blockiyt** [comment]
> @blockiyt I quickly tryed to rewrite the egg to support arm64
> 
> but I do not have a arm64 machine online atm can you test it out for me: https://pteropaste.com/cl27ik

yeah I will, gimme a sec

**Comment by QuintenQVD0** [comment]
> > @blockiyt I quickly tryed to rewrite the egg to support arm64
> > but I do not have a arm64 machine online atm can you test it out for me: https://pteropaste.com/cl27ik
> 
> works fine for me, thank you! :) ~would it be possible to update the old egg script to automatically check if it is arm or amd? if not, would it instead be possible to put the new arm64 file into the repo @parkervcp ? thanks!~
> 
> EDIT: the script already checks which system it is, (I think so, because I looked into the file), so no need for that, an update would nevertheless be very nice to have :)

Yea I wrote a check to auto select the host architecture. So you can close this issue
