### ISSUE TITLE
Spaceengineers egg

### ISSUE THREAD

**Issue by OmegaRogue** [parkervcp/eggs#164]
Link to game: https://www.spaceengineersgame.com/

Extra: https://www.spaceengineerswiki.com/Dedicated_Servers

**Comment by ZeProf2Code** [comment]
It's only available for Windows Servers

**Comment by OmegaRogue** [comment]
It works with wine https://gist.github.com/CoffeePirate/102e789310719cad6457

**Comment by parkervcp** [comment]
The WindDB disagrees. - https://appdb.winehq.org/objectManager.php?sClass=application&iId=16019

It used to work but in the last few years there was a change made that breaks it in wine.
