### ISSUE TITLE
[Egg Request]: Cry  of fear 

### ISSUE THREAD

**Issue by StoneMcYT** [parkervcp/eggs#1642]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/223710/Cry_of_Fear/

### Links for the download

https://store.steampowered.com/app/223710/Cry_of_Fear/

### Links for the install docs

Launch the game, click host server, set map type hostname max players server password auto start time etc

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> 
> Yes
> ### Link to a game or software
> 
> https://store.steampowered.com/app/223710/Cry_of_Fear/
> ### Links for the download
> 
> https://store.steampowered.com/app/223710/Cry_of_Fear/
> ### Links for the install docs
> 
> Launch the game, click host server, set map type hostname max players server password auto start time etc

you did not gave the install docs link and because it is not posible to run it as a standalone server

**Comment by gOOvER** [comment]
1. There is no Server
2. Is Windows only and you need a GUI. Thats not supported

**Comment by StoneMcYT** [comment]
Ah so since no dedicated server cant run it
