### ISSUE TITLE
[Bug]: TModLoader No Longer Working

### ISSUE THREAD

**Issue by PixelPacker** [parkervcp/eggs#1644]
### Panel Version

1.7.0

### Wings Version

1.6

### Service

Terraria/TModLoader

### Modified

No, I did not modify the egg

### Expected Behavior

Install the egg and let the server launch

### Actual Behavior

Egg is unable to download required files

### Steps To Reproduce

Step 1: Install TModLoader Egg

### Install logs

https://pteropaste.com/ttx7qg

**Comment by Software-Noob** [comment]
This is because their releases have partially changed. Automated and manual ones are different.

The script has to be updated for that and for missing steam dll files that are only present in manual releases

**Comment by docimin** [comment]
A fix would be to use this for releases
```RELEASES=$(curl --silent "https://api.github.com/repos/$GITHUB_PACKAGE/releases" | jq '.[] | select(.name | contains("v0"))')```
But i'm getting stuck at the latest json.. what's the way to get the last json based on the filters?
Something like ```jq '.[] | select(.name | contains("v0")) | first'```, but this does not work.

Any ideas?

**Comment by PixelPacker** [comment]
Looks like there may be another potential issue with the egg, after updating it thankfully works however it doesn't appear that it can install from the 1.4 stable branch. Would an install option be possible to get this done?

1.4 Stable Github release page: https://github.com/tModLoader/tModLoader/releases

**Comment by digitalravenstudio** [comment]
In regards to this issue, 
I have added a new pull request for 1.4 Support.

If you would like to comment or try it for yourself, feel free to check it out here: https://github.com/parkervcp/eggs/pull/1686
Feedback on potential issues or improvements is always appreciated.
