### ISSUE TITLE
[Egg Request]: uptime-kuma

### ISSUE THREAD

**Issue by SentixDev** [parkervcp/eggs#1645]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/louislam/uptime-kuma

### Links for the download

http://git.kuma.pet/install.sh

### Links for the install docs

https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

**Comment by WavingCatDevs** [comment]
I'm pretty sure you can just use the nodejs egg

**Comment by parkervcp** [comment]
The discordjs egg could run this for you.
