### ISSUE TITLE
[Egg Request]: Core Keeper

### ISSUE THREAD

**Issue by Loapu** [parkervcp/eggs#1647]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1621690/Core_Keeper/

### Links for the download

https://store.steampowered.com/app/1621690/Core_Keeper/

### Links for the install docs

https://store.steampowered.com/news/app/1621690/view/3185744478433987795

**Comment by parkervcp** [comment]
In theory the SteamCMD generic egg should be able to install this. All you should need it to do it update the start command.

**Comment by Loapu** [comment]
Could you provide me with a link to that specific egg? I can't seem to find it here.

**Comment by gOOvER** [comment]
Dedi App ID:

**Comment by gOOvER** [comment]
> Could you provide me with a link to that specific egg? I can't seem to find it here.

I'll try to create one on Weekend. is not so hard :)

offtopic:

und schöne Grüße an Hessen :P

**Comment by YannikSc** [comment]
As it turned out, you might be able to create a server using the "Custom Source Engine Game" in theory, but in practice it actually is'nt working (without touching the egg anyway) as the game Id is validated as `required|numeric|digits_between:1,6` and, well, the id of Core Keeper is 7 digits long.

So I created an egg. It also seems to work, mostly.
- Install works
- Running/starting works
- Connection fails

Not sure if its due to using IPv6 on my server or if the egg or even the game makes trouble. 
If someone wants to check it out, [here you go](https://github.com/YannikSc/pterodactyl_eggs/blob/add/core-keeper/game_eggs/steamcmd_servers/core_keeper/egg-core-keeper.json)

(Does'nt mean that I stop working on it, it's just late)

**Comment by kapatheus** [comment]
> Not sure if its due to using IPv6 on my server or if the egg or even the game makes trouble. If someone wants to check it out, [here you go](https://github.com/YannikSc/pterodactyl_eggs/blob/add/core-keeper/game_eggs/steamcmd_servers/core_keeper/egg-core-keeper.json)

I just tried this and it seems to work well. The installation went well and I was able to connect to the server.

**Comment by parkervcp** [comment]
So all we really need to do is make the variable take longer numbers.

**Comment by gOOvER** [comment]
> As it turned out, you might be able to create a server using the "Custom Source Engine Game" in theory, but in practice it actually is'nt working (without touching the egg anyway) as the game Id is validated as `required|numeric|digits_between:1,6` and, well, the id of Core Keeper is 7 digits long.
> 
> So I created an egg. It also seems to work, mostly.
> 
> * Install works
> * Running/starting works
> * Connection fails
> 
> Not sure if its due to using IPv6 on my server or if the egg or even the game makes trouble. If someone wants to check it out, [here you go](https://github.com/YannikSc/pterodactyl_eggs/blob/add/core-keeper/game_eggs/steamcmd_servers/core_keeper/egg-core-keeper.json?rgh-link-date=2022-05-15T22%3A13%3A16Z)
> 
> (Does'nt mean that I stop working on it, it's just late)

use the ghcr image. quay images are old.

`"quay.io\/pterodactyl\/core:source"`

**Comment by gOOvER** [comment]
> So it took me a bit, but I was able to get the Server installed Running and people are able to connect, only thing it, it's showing the server as starting and doesn't switch to running.

do you have

`Started session with Game ID` in your console?

**Comment by YannikSc** [comment]
> use the ghcr image. quay images are old.

Thanks for the info! I updated the image to the `ghrc.io/pterodactyl/games:source` one.

> So all we really need to do is make the variable take longer numbers.

In general I think that would be a good Idea if you are fine with having to take care of the startup command by yourself, but if possible I would prefer to have specific eggs for games.

> So it took me a bit, but I was able to get the Server installed Running and people are able to connect, only thing it, it's showing the server as starting and doesn't switch to running.

Were you using my egg? My server shows that it's running

**Comment by exptofu** [comment]
> Were you using my egg? My server shows that it's running

Have you been trying to connect to the server? I've had issues with your egg. Only way I've gotten it to work is to use xvfb-run to emulate a screen.

**Comment by gOOvER** [comment]
> Alright. I see. This is the problem then, not my IPv6. So then I need a container with xvfb installed. Have you used the `_launch.sh` script to start the server or have you just added xvfb to the Startup command? (if its the second would you please share your startup command so that I can try it out?)

must be in the image.

But this is, why i stoped to create an egg for this Game. The Server is  in an  early alpha state and the server is a pain. I have also a working egg

**Comment by YannikSc** [comment]
No, it does'nt, I'm currently running the Server in the `ghrc.io/pterodactyl/games:source` image (which, from what I can tell, is not having Xvfb), works like a charm in my case. 
But its true, the Server feels very much alpha and documentation is rare but to be fair, the game itself is still in early access.

**Comment by gOOvER** [comment]
the devs wrote, that `-nographics` not work on Linux and so Xvfb is needed. Thats why i use it

**Comment by YannikSc** [comment]
I'm aware, that they wrote it. But its working. I would'nt yet consider it reliable, but it works, which is good enough for me.
And with that said, I think I will not create a PR for it, its just too early

**Comment by reno218** [comment]
Yeah that's where I'm at. The server installs, gets gameID just doesn't shut down correct and doesn't show as Running

**Comment by YannikSc** [comment]
Well, this part is working for me. But I'm also not using wine

**Comment by exptofu** [comment]
Yannik, I tried your updated egg and it still could not connect for me.

This is a modified version of your egg but using the wine image. I haven't been able to get the setup working with just installing xvfb and not using a wine image but haven't looked too much into it. Modified _launch.sh to allow argument forwarding which works from my testing.

https://gist.github.com/exptofu/44948b580eb3fbd47595e92ac8470234

**Comment by YannikSc** [comment]
I don't think its a good Idea to start the server in the setup script.
The setup script is only meant to install the server, there you won't need to have xvfb. 
This would also explain why you can't connect and why the server is not showing up as running to you. The setup (from my knowledge) is not having the game ports exposed (which are actually 27015 and 27016, you have to add the allocations when setting up the server).

Also, in the startup script, you kept the options (-world etc.) but you call the `_launch.sh` script. The official launch script is not passing the arguments to the server.

**Comment by exptofu** [comment]
The install runs sed to update _launch.sh to have "$@" in the corekeeperserver call. It doesn't actually start the script.

From what I understand, the game does not need port forwarding to host the servers, which is why the Game ID is used to share with people.

**Comment by gOOvER** [comment]
> Yannik, I tried your updated egg and it still could not connect for me.
> 
> This is a modified version of your egg but using the wine image. I haven't been able to get the setup working with just installing xvfb and not using a wine image but haven't looked too much into it. Modified _launch.sh to allow argument forwarding which works from my testing.
> 
> [gist.github.com/exptofu/44948b580eb3fbd47595e92ac8470234](https://gist.github.com/exptofu/44948b580eb3fbd47595e92ac8470234)_ (too large to embed)_

xvfb must be a part of the image; not the install  script

**Comment by exptofu** [comment]
> xvfb must be a part of the image; not the install script
Ah, that would make sense. Is there an image with just xvfb and not wine?

**Comment by exceloid** [comment]
> Yannik, I tried your updated egg and it still could not connect for me.
> 
> This is a modified version of your egg but using the wine image. I haven't been able to get the setup working with just installing xvfb and not using a wine image but haven't looked too much into it. Modified _launch.sh to allow argument forwarding which works from my testing.
> 
> https://gist.github.com/exptofu/44948b580eb3fbd47595e92ac8470234

this worked fine for me.  thanks!

**Comment by DaGrub** [comment]
Would love to see this game added properly so I don't have to run a VPS or use wine as a workaround in an egg. There's a June update coming out soon and there may be a lot of people wanting to set up servers. :)

**Comment by gOOvER** [comment]
> Would love to see this game added properly so I don't have to run a VPS or use wine as a workaround in an egg. There's a June update coming out soon and there may be a lot of people wanting to set up servers. :)

you dont need wine running; only xvfb

**Comment by DaGrub** [comment]
I'm new to pterodactyl and haven't used it, but can the egg be updated with xvfb or does what it runs on have to be updated? If it's possible to just have an egg, then it would make it easier. I'm using a VPS with screen to keep the server up right now.

**Comment by Sethfire** [comment]
I was trying to figure out how to enable hard mode difficulty on the dedicated server but apparently you can't enable this on the dedicated servers yet, the devs on the official discord said it will be added in the next update.

**Comment by QuintenQVD0** [comment]
Closed as of #2056
