### ISSUE TITLE
[Egg Request]:  Graphwar

### ISSUE THREAD

**Issue by StoneMcYT** [parkervcp/eggs#1649]
### Does this expand an already existing service

No

### Link to a game or software

http://www.graphwar.com/

### Links for the download

http://www.graphwar.com/graphwar.jar

### Links for the install docs

https://github.com/catabriga/graphwar (Bottem of the page)

**Comment by parkervcp** [comment]
They converted this to a standalone single player game. There's no reason to try and run this on a server.

**Comment by StoneMcYT** [comment]
> They converted this to a standalone single player game. There's no reason to try and run this on a server.
Wait isn't the game still multiplayer though? Since me and my mates have founded a create game option? 
![image](https://user-images.githubusercontent.com/67421882/168077128-79949259-3351-4fa1-b795-5ba87cccb387.png)

**Comment by parkervcp** [comment]
They also call out browsers are blocking applets so they released it as a standalone.
