### ISSUE TITLE
Update Waterfall to use Parchment instead of the deprecated Paper CI when downloading its .jar

### ISSUE THREAD

**Issue by James76931** [parkervcp/eggs#165]
As of February 27th 2019, PaperMC has made the downloading of server binaries from their CI a deprecated method - they now use an API called "Parchment" to handle the downloading of these files.
Once downloading from the CI is completely shut off, the Waterfall egg will not install properly as it is still reliant on this old service. "The old Jenkins based download links you used in the past are now subject to change without notice. You should move over to these API links as soon as possible."

Documentation can be found here: https://paper.readthedocs.io/en/stable/site/api.html
Original announcement: https://papermc.io/forums/t/introducing-parchment/549

**Comment by parkervcp** [comment]
Updated with https://github.com/parkervcp/eggs/commit/97d6eece6a8cd62862c3d46a84c7673ae88b4259
