### ISSUE TITLE
[Bug]: 7DTD Cannot Restart Servers

### ISSUE THREAD

**Issue by MayhemBill** [parkervcp/eggs#1655]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

7 Days to Die

### Modified

No, I did not modify the egg

### Expected Behavior

hit restart
server restarts
profit

### Actual Behavior

server freezes after hitting restart and has to be manually killed and started.

### Steps To Reproduce

hit restart
server starts shutting down
freezes when stopping just shy of completing
hit kill to fully stop server
hit start manually to restart server

### Install logs

https://pteropaste.com/8lz8m2/

**Comment by kibubek** [comment]
Can confirm, happens here aswell. Might have to do with the latest version of 7DTD

**Comment by RogueRaiden** [comment]
what was the solution to this?

**Comment by MayhemBill** [comment]
it was an issue with 7dtd itself not the egg.
