### ISSUE TITLE
[Bug]: the forest error (Filename:  Line: -1)

### ISSUE THREAD

**Issue by Just-Toast** [parkervcp/eggs#1657]
### Panel Version

1.7

### Wings Version

1.5

### Service

The forest

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server and just play

### Actual Behavior

InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper managed-to-native) object:__icall_wrapper_mono_object_castclass (object,intptr)
  at UdpKit.UdpEvent.As[UdpEventStartDone] () [0x00000] in <filename unknown>:0
  at BoltCore.PollNetwork () [0x00000] in <filename unknown>:0
  at BoltCore.Poll () [0x00000] in <filename unknown>:0
  at BoltPoll.FixedUpdate () [0x00000] in <filename unknown>:0

(Filename:  Line: -1)

### Steps To Reproduce

Install the server
start server
get the error

### Install logs

.

**Comment by yesBad** [comment]
Just did a fresh install with The Forest egg and I don't have any issues. (amd64, ubuntu 20.04.03)
Me and my friend were both able to join & kill each other 😄

**Comment by Just-Toast** [comment]
@yesBad did you you modify something in the egg?

**Comment by yesBad** [comment]
> @yesBad did you you modify something in the egg?

Nope, downloaded it from the repo, added the 3 ports, added my token & started it

**Comment by Just-Toast** [comment]
> > @yesBad did you you modify something in the egg?
> 
> Nope, downloaded it from the repo, added the 3 ports, added my token, installed & started it

there are only 2 ports needed for the server?

**Comment by QuintenQVD0** [comment]
> > > @yesBad did you you modify something in the egg?
> > 
> > 
> > Nope, downloaded it from the repo, added the 3 ports, added my token, installed & started it
> 
> there are only 2 ports needed for the server?

nop 3:
![afbeelding](https://user-images.githubusercontent.com/67589015/168477196-ff2331bd-4682-4b10-9310-e7967846500e.png)

**Comment by yesBad** [comment]
Steam 8766 is steam stuffies.
Server 27015 is what I used.
Query 27016 is what you connect with.

**Comment by Just-Toast** [comment]
Yeah it says know Game autosave started and pterodactyl says its running so i think everything is working know

**Comment by yesBad** [comment]
Glad to hear. So it just didn't wanna work w/o the ports

**Comment by Just-Toast** [comment]
> Glad to hear. So it just didn't wanna work w/o the ports

yeah it looks like it. So thanks for you help man i appreciate it!
