### ISSUE TITLE
Unturned

### ISSUE THREAD

**Issue by CozmicHosting** [parkervcp/eggs#166]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: (0.7.12)
Daemon Version: (6.8)
Service: (Unturned)
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)

Actual Behavior:
The Unturned egg installs but it either says Unturned executable not found or has a Mono Run time Error
Steps to Reproduce: (Step by step what to do to cause the issue)
The issue is straight when its installed.

**Comment by parkervcp** [comment]
This appears to have been fixed by the devs.
