### ISSUE TITLE
[Egg Request]: ARMA Reforger

### ISSUE THREAD

**Issue by ARCOMMADMIN** [parkervcp/eggs#1661]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1874880/Arma_Reforger/

### Links for the download

Steam CMD: https://store.steampowered.com/app/1874880/Arma_Reforger/

### Links for the install docs

https://community.bistudio.com/wiki/Arma_Reforger:Server_Hosting

**Comment by ARCOMMADMIN** [comment]
Here is the Steamdb info if necessary: https://steamdb.info/app/1874900/info/

**Comment by lilkingjr1** [comment]
Just got the game. I'll start working on one. Might take some time though, because I need to determine if it will require a custom image or not.

**Comment by ARCOMMADMIN** [comment]
No worries. Thank you for looking into it!

**Comment by uaon** [comment]
> Just got the game. I'll start working on one. Might take some time though, because I need to determine if it will require a custom image or not.

If it helps, I'm using a rough Frankenstein of the ARMA3 image+egg I built for it. It works, but not great for public consumption.
 dockerfiles for build -> https://github.com/uaon/yolk-reforger
 egg -> https://github.com/7Cav/service-level-configs/blob/develop/pterodactyl/eggs/arma/egg-reforger.json

**Comment by JasonTurk** [comment]
Server up and running! Thanks lilkingjr1!!

I don't know if it's just me, but I can't open anything in the File Manager tab. Even clicking on a readme brings up a something went wrong "An unexpected error was encountered while processing this request, please try again." error message.

**Comment by lilkingjr1** [comment]
> I don't know if it's just me, but I can't open anything in the File Manager tab. Even clicking on a readme brings up a something went wrong "An unexpected error was encountered while processing this request, please try again." error message.

I think it might just be a panel or daemon issue on your end. 😕 I didn't put any file restrictions in the egg and files open fine for me in my File Manager.

**Comment by danir-de** [comment]
Max players are not limited to 64, otherwise #1664  works for me.

```
playerCountLimit
number value, range 1..256, default: 127
```

**Comment by parkervcp** [comment]
Resolved with #1664
