### ISSUE TITLE
[Egg Request]: Rimworld - Open World

### ISSUE THREAD

**Issue by KartoniarzEssa** [parkervcp/eggs#1663]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/TastyLollipop/OpenWorld

### Links for the download

https://github.com/TastyLollipop/OpenWorld/releases

### Links for the install docs

https://github.com/TastyLollipop/OpenWorld/blob/main/README.md

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> 
> No
> ### Link to a game or software
> 
> https://github.com/TastyLollipop/OpenWorld
> ### Links for the download
> 
> https://github.com/TastyLollipop/OpenWorld/releases
> ### Links for the install docs
> 
> https://github.com/TastyLollipop/OpenWorld/blob/main/README.md

You can try It , maby I will PR it but with no arm64 support

**Comment by gOOvER** [comment]
fixed with: https://github.com/parkervcp/eggs/pull/1985

**Comment by QuintenQVD0** [comment]
fixed with: https://github.com/parkervcp/eggs/pull/1985
