### ISSUE TITLE
[Egg Request]: Call of Duty 2

### ISSUE THREAD

**Issue by M0rkulv** [parkervcp/eggs#1677]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/2630/Call_of_Duty_2/

### Links for the download

...

### Links for the install docs

...

**Comment by parkervcp** [comment]
You gave nothing but the link to steam. I have already said no to other CoD games because there are no public server files.

**Comment by M0rkulv** [comment]
oh well thats fine i only wanted to try
