### ISSUE TITLE
[Egg Request]: PLUTONIUM BLACK OPS II SERVER

### ISSUE THREAD

**Issue by navin-hariharan** [parkervcp/eggs#1681]
### Does this expand an already existing service

No

### Link to a game or software

https://plutonium.pw/docs/install/#t6-black-ops-2

### Links for the download

https://github.com/xerxes-at/T6ServerConfigs/archive/master.zip

### Links for the install docs

https://plutonium.pw/docs/server/t6/setting-up-a-server/

**Comment by parkervcp** [comment]
I have stated multiple times that there are no public server files available. These are generally sketchy.

**Comment by toster234** [comment]
I play plutonium and did make my server but the server files are really a joke. Not good for use on pterodactyl

**Comment by navin-hariharan** [comment]
> I played plutonium and made my server, but the server files are a joke. Not suitable for use on pterodactyl

I agree with this man! They don't even have a CLI version! You need wine for running it
