### ISSUE TITLE
[Bug]: RCON connection refused on ARK after more than 10 hours

### ISSUE THREAD

**Issue by YoanSF1** [parkervcp/eggs#1687]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

ARK : Survival Evolved

### Modified

No, I did not modify the egg

### Expected Behavior

the server had to spend 10 to 20 minutes before successfully connecting to the RCON

### Actual Behavior

I left my server on all night and the RCON connection still didn't work

### Steps To Reproduce

- Create an ARK server
- Assign all ports to the server
- Wait for connection to the RCON

### Install logs

https://pastebin.com/GDrc58jn

**Comment by gOOvER** [comment]
Install failed


/entrypoint.sh: line 69: cd: ShooterGame/Binaries/Linux: No such file or directory

**Comment by YoanSF1** [comment]
ah ok, how much disk space is needed?

**Comment by gOOvER** [comment]
you are using Debian 9 which is EoL 8n 3 weeks. Update to Debian 11

**Comment by YoanSF1** [comment]
ok thx
