### ISSUE TITLE
[Bug]: Mohist

### ISSUE THREAD

**Issue by seailz** [parkervcp/eggs#1689]
### Panel Version

N/A

### Wings Version

N/A

### Service

N/A

### Modified

No, I did not modify the egg

### Expected Behavior

Mohist is a dangerous server software, so I believe it should be removed from the repoistory.
It's been documented multiple times. Here is a link to one of these. https://essentialsx.net/do-not-use-mohist.html

### Actual Behavior

N/A

### Steps To Reproduce

N/A

### Install logs

N/A

**Comment by yesBad** [comment]
You should really know the backstory. As Mohist does not force to use modified files & the modified source-code can be viewed.
