### ISSUE TITLE
ETLegacy

### ISSUE THREAD

**Issue by KurwyGithub** [parkervcp/eggs#169]
Service: ET Legacy
Link to game: https://www.etlegacy.com/download

**Comment by danny6167** [comment]
Anyone working on this? I might take a wack at it if @KurwyGithub is still around to test.
Should we be packing the 32 or 64 bit version ?

**Comment by KurwyGithub** [comment]
Well there was test EGG but I didn't get further support. There was problem with connecting server.

**Comment by danny6167** [comment]
Oh? Do you have a link to or copy of the test EGG?

**Comment by parkervcp** [comment]
@danny6167 Can you check here please and let me know - https://github.com/parkervcp/eggs/tree/add/etlegacy/etlegacy/etlegacy

**Comment by danny6167** [comment]
Will do!

**Comment by danny6167** [comment]
Needed a couple of changes. Have submitted a PR here https://github.com/parkervcp/eggs/pull/191

This PR has been tested for:
- both 32 and 64 bit servers
- Bots working
- Client connects and can play
- Server marked as running once started.
