### ISSUE TITLE
[Egg Request]: Necesse

### ISSUE THREAD

**Issue by MakaryGo** [parkervcp/eggs#1690]
### Does this expand an already existing service

No

### Link to a game or software

https://necessegame.com/

### Links for the download

https://necessewiki.com/Multiplayer#Downloading_Server_Files

### Links for the install docs

https://necessewiki.com/Multiplayer

**Comment by QuintenQVD0** [comment]
> Thanks, feel free to close this one

Only you or the repo author can do that
