### ISSUE TITLE
[Bug]: Space Engineers RemoteAPI

### ISSUE THREAD

**Issue by Gabgobie** [parkervcp/eggs#1691]
### Panel Version

1.8.0

### Wings Version

1.6.4

### Service

Space Engineers

### Modified

No, I did not modify the egg

### Expected Behavior

Server starting as usual with the API on Port 8081 enabled

### Actual Behavior

Server crashed while starting up. From the logs it seems that the OS is not supported. 

Exception occurred: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.HttpListener..ctor()
   at VRage.Dedicated.RemoteAPI.MyRemoteServer.Listen()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Steps To Reproduce

Install Space Engineers server and start it with RemoteAPI enabled. It will work mostly fine without the API enabled.

### Install logs

This is not applicable since there is no problem with the install but i provided the important part of the log in the Actual Behavior textfield

**Comment by gOOvER** [comment]
https://github.com/parkervcp/eggs/issues/1602#issuecomment-1304414645

**Comment by gOOvER** [comment]
@Gabgobie pls test my PR, if the API works. As i know is there a problem with Wine and API calls

**Comment by Gabgobie** [comment]
Please excuse my late answer. I haven't been on github in quite some time. I'll check it out as soon as i get the time to but I haven't had any time to play games so i haven't really touched hosting either.

**Comment by QuintenQVD0** [comment]
> Please excuse my late answer. I haven't been on github in quite some time. I'll check it out as soon as i get the time to but I haven't had any time to play games so i haven't really touched hosting either.

If you check and config Goover egg then the leave a comment if it works then it will be merged

**Comment by gOOvER** [comment]
> > Please excuse my late answer. I haven't been on github in quite some time. I'll check it out as soon as i get the time to but I haven't had any time to play games so i haven't really touched hosting either.
> 
> If you check and config Goover egg then the leave a comment if it works then it will be merged

its allready merged :) But i think, Remote API will not work with Wine
