### ISSUE TITLE
[Egg Request]: MCSleepingServerStarter

### ISSUE THREAD

**Issue by Timong-craft** [parkervcp/eggs#1693]
### Does this expand an already existing service

Yes

### Link to a game or software

https://papermc.io/downloads

### Links for the download

https://github.com/vincss/mcsleepingserverstarter

### Links for the install docs

https://github.com/vincss/mcsleepingserverstarter#-install

**Comment by gOOvER** [comment]
This is a plugin and you can easily  install this yourself :)

**Comment by Timong-craft** [comment]
How?

**Comment by gOOvER** [comment]
> How?

read the install doc you posted

**Comment by Timong-craft** [comment]
I think this can't be possible.
Pls watch this: https://www.youtube.com/watch?v=WqvQISpr6-s

**Comment by Timong-craft** [comment]
> > How?
> 
> read the install doc you posted

yes

**Comment by Timong-craft** [comment]
I had the idea to implement this into an egg becorse there isn't anything like this.
This is starting your server when joining.
(Written in Node.js)

**Comment by parkervcp** [comment]
You are paying for the server space and availability. I am certain that stopping the server isn't going to save you money.

**Comment by BasToTheMax** [comment]
This is useful for free minecraft hostings

**Comment by Timong-craft** [comment]
right

**Comment by parkervcp** [comment]
If you are hosting for free then that's your problem.

**Comment by Timong-craft** [comment]
Ah they made one on there own: https://github.com/vincss/mcsleepingserverstarter/blob/master/docs/egg-paper-mcsleepingserverstarter.json
