### ISSUE TITLE
[Bug]: Pocketmine egg does not work for arm

### ISSUE THREAD

**Issue by devgocri** [parkervcp/eggs#1694]
### Panel Version

1.8.1

### Wings Version

1.6.4

### Service

minecraft/pocketmine?

### Modified

No, I did not modify the egg

### Expected Behavior

For it to install the server and necessary files successfully

### Actual Behavior

It states:

`container@pterodactyl~ Starting installation process, this could take a few minutes...`

then 

`exec /bin/bash: exec format error`

### Steps To Reproduce

Step 1: Get an arm server
Step 2: Download the egg and import it
Step 3: Create a server with the egg

If it instantly jumps to offline, then goto settings and click reinstall server and click console right after so you can see the install log/console

### Install logs

my console doesn't show anything when i run this command idk why

**Comment by gOOvER** [comment]
As i told you on Discord, there is NO Arm64 Release. you must compile php yourself, so not really a Bug

**Comment by gOOvER** [comment]
See:

https://jenkins.pmmp.io/job/PHP-8.0-Aggregate/

**Comment by devgocri** [comment]
> As i told you on Discord, there is NO Arm64 Release. you must compile php yourself, so not really a Bug

Yeah but the script just doesn't run anything such as downloading the pocketmine phar which is listed before where it downloads the php bin

**Comment by devgocri** [comment]
but u can make an image for pocketmine by having their build script running and also and for it to download the latest phar. Manually doing this worked so i don't see why its an issue

**Comment by gOOvER** [comment]
> but u can make an image for pocketmine by having their build script running and also and for it to download the latest phar. Manually doing this worked so i don't see why its an issue

Again; It looks like, you wil not really understand

THERE IS NOOOOO PRECOMPILED  VERSION OF PHP !!!! SO NO ARM SUPPORT !!! CREATE THE IMAGE YOURSELF

**Comment by devgocri** [comment]
> 

But then why can't the egg compile it itself though like how get.pmmp.io does?
