### ISSUE TITLE
[Bug]: CurseForge API V2 deprecated?  

### ISSUE THREAD

**Issue by Zage83** [parkervcp/eggs#1698]
### Panel Version

1.8

### Wings Version

1.6

### Service

minecraft/java/curseforge-generic

### Modified

No, I did not modify the egg

### Expected Behavior

Installation und run of a Curse Modpack "Forever Stranded" Server.
https://www.curseforge.com/minecraft/modpacks/forever-stranded

### Actual Behavior

On reinstall the Server, there is the following error-message in the console with the url api call.
No files are created in the volume.
The URL "https://addons-ecs.forgesvc.net/api/v2/addon/253026" brings Error 403 No Access.
I think the Api of CurseForge is redesigned?! 

```
Curling the json for the modpack
running: curl -sSL https://addons-ecs.forgesvc.net/api/v2/addon/253026
Getting latest download url
File ID is: 
jq: error: syntax error, unexpected ')' (Unix shell quoting issues?) at <top-level>, line 1:
.latestFiles[] | select(.id==) | .isServerPack                             
jq: 1 compile error
```

### Steps To Reproduce

Step 1: Create a  server with your Egg "minecraft/java/curseforge generic"
Step 2: Install the Server

**Comment by gOOvER** [comment]
There is a new  api and as i know, you need an  apikey to use the API

**Comment by Zage83** [comment]
> 

i think so,too. is there a new egg?

**Comment by gOOvER** [comment]
> > 
> 
> i think so,too. is there a new egg?

nope; Curseforge will not give everyone a API Key ;) Get an API Key and then  we can talk to create an new egg ;)

**Comment by parkervcp** [comment]
I am looking at the api now. It's not hard to work with.

**Comment by parkervcp** [comment]
@Zage83 You can try that out if you want.

**Comment by Zage83** [comment]
@parkervcp thx for your fast support. I tested but fai:

```
Curling the json for the modpack
running: curl -sSLX GET https://api.curseforge.com/v1/mods/253026 -H 'Accept: application/json' -H 'x-api-key: API_KEY'
Getting latest download url
File ID is: 
jq: error: syntax error, unexpected ')' (Unix shell quoting issues?) at <top-level>, line 1:
.data.latestFiles[] | select(.id==) | .isServerPack                                  
jq: 1 compile error
Download url set to 
```

**Comment by parkervcp** [comment]
You will need to get an API key to use this now. They don't have a public api currently

**Comment by Zage83** [comment]
Yes yes, i saw. I reinstalled and it worked. The only thing now is the .jar file: 
```
container@pterodactyl~ java -Xms128M -Xmx8200M -jar server.jar
Error: Unable to access jarfile server.jar
```

**Comment by parkervcp** [comment]
Yeah I thought i updated the script after finding that. Rename the forge universal jar to server.jar. I am pushing an update now.
