### ISSUE TITLE
[feature]: QUERY_PORT Variable Request

### ISSUE THREAD

**Issue by iPink01** [parkervcp/eggs#1700]
### Panel Version

1.8.1

### Wings Version

1.6

### Service

V- Rising

### Modified

No, I did not modify the egg

### Expected Behavior

Not able to connect to server easily.

I expected to find under start-up variables, a block to enter the server QUERY_PORT, 

without being able to set to the steam query port, players will be unable to connect. - this might make it harder for newer users to understand as I had to edit the config value from ``"QueryPort": "{{server.build.env.QUERY_PORT}}",```` to ````QueryPort": "27015"`` manually. which then allowed players to connect. 

In previous builds the Query_Port Variable exisited.

### Actual Behavior

On panel: Server Running, 

In Game: Connection timed Out.

### Steps To Reproduce

Don't Set the Query_Port Var.

### Install logs

<link here>

**Comment by Software-Noob** [comment]
There is such a variable and config parser for it already. Only admins can modify it.

https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/v_rising/egg-v-rising.json#L32-L40

` "QueryPort": "{{server.build.env.QUERY_PORT}}"`
