### ISSUE TITLE
Space Engineers? 

### ISSUE THREAD

**Issue by TheStrato** [parkervcp/eggs#171]
Service: (Ex. minecraft/factorio/etc)
Space Engineers perhaps? 
Link to game: (Ex. minecraft.net/factorio.com/etc)
https://store.steampowered.com/app/244850/Space_Engineers/

**Comment by parkervcp** [comment]
Previously opened and closed in #164 due to space engineers not working in linux some updates ago.

**Comment by TheStrato** [comment]
Okay, I have a Windows 2k16 server as well, could you help me run it on there?

**Comment by TheStrato** [comment]
Ptero is over on my Ubuntu server as it didn't play well in Docker for Windows, but I could just run a SE server on my Win box if you can point me in the right direction.

**Comment by parkervcp** [comment]
That's not how this works. I don't support the games. I support running them on pterodactyl. That game won't run on pterodactyl.

**Comment by TheStrato** [comment]
Okay. Thanks.

**Comment by cTurtle98** [comment]
is it possible to do this with a custom container image that has wine+proton on it?

**Comment by Software-Noob** [comment]
> is it possible to do this with a custom container image that has wine+proton on it?

This already exists. Please look into the repository readme.

**Comment by cTurtle98** [comment]
> > is it possible to do this with a custom container image that has wine+proton on it?
> 
> This already exists. Please look into the repository readme.

lol thanks, this is still the first result when you google for a space engineers egg
