### ISSUE TITLE
[Bug]: Pocketmine do not set a default password

### ISSUE THREAD

**Issue by mrdiploben** [parkervcp/eggs#1710]
### Panel Version

Any

### Wings Version

Any

### Service

minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

In the pocketmine egg an rcon password has already been setup. This can cause massive security issues within the server if you turn on rcon and dont change the password.

### Actual Behavior

In the pocketmine egg an rcon password has already been setup. This can cause massive security issues within the server if you turn on rcon and dont change the password.

### Steps To Reproduce

Check server.properties in the pocketmine egg.

### Install logs

Not needed

**Comment by gOOvER** [comment]
rcon is not set as default in pmmp egg

**Comment by mrdiploben** [comment]
![image](https://user-images.githubusercontent.com/81100371/174328838-a1bbab7e-0230-488c-8a76-9111b541fd06.png)
It is a said there

**Comment by Software-Noob** [comment]
Should someone go into the config to enable rcon, one would hope they are not blind to see rcon password right below it.

We have default example password for some eggs that require it. Not sure if that's the case with pocketmine as well.

**Comment by mrdiploben** [comment]
Most people turn on rcon but leave password. I have done it in the past with many others aswell. It seems to be an issue with latest still requiring rcon as it is needed as said by mojang.

**Comment by Software-Noob** [comment]
> Most people turn on rcon but leave password. I have done it in the past with many others aswell. It seems to be an issue with latest still requiring rcon as it is needed as said by mojang.

I'm not familiar with pocketmine, but you usually can't have passwordless rcon? It's also not recommended to be used by PMM devs, well, because RCON. We could randomly generate a password and insert it into the config on install, but ideally, I'd trust the users to choose it themselves should navigate into the config and enable rcon manually.

**Comment by mrdiploben** [comment]
To be honest, i would just remove the password and set it to blank like other properties files.

**Comment by Software-Noob** [comment]
Heh, yeah that'd be the wisest option. Didn't have morning coffee yet.
