### ISSUE TITLE
[Bug]: tModloader not installing

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1712]
### Panel Version

latest

### Wings Version

latest

### Service

terraria/tmodloader

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it

### Actual Behavior

Running hooks in /etc/ca-certificates/update.d...
done.
using anon api call
defaulting to latest release
running: curl -sSL -o
curl: option -o: requires parameter
curl: try 'curl --help' or 'curl --manual' for more information
Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
[--mime-type] [-e ] [-F ] [-f ]
[-m ] [-P <parameter=value>] ...
file -C [-m ]
file [--help]
unknown filetype. Exiting

### Steps To Reproduce

Install egg
Install server

### Install logs

Provided above

**Comment by gOOvER** [comment]
#1686

**Comment by BenasPaulikas** [comment]
Closing this in favor of #1686
