### ISSUE TITLE
[Egg Request]: UrlHum

### ISSUE THREAD

**Issue by Doncellup** [parkervcp/eggs#1713]
### Does this expand an already existing service

No

### Link to a game or software

https://urlhum.com/

### Links for the download

git clone https://github.com/urlhum/UrlHum.git .

### Links for the install docs

https://urlhum.readme.io/docs/installation

**Comment by gOOvER** [comment]
Not really something for Ptero. nginx, MySQL is needed

**Comment by Software-Noob** [comment]
This is essentially running a laravel application like Pterodactyl. The complexity is beyond the supported scope of eggs and should be done using Docker itself or outside of Pterodactyl
