### ISSUE TITLE
Update Unturned egg to .net 4.6.1

### ISSUE THREAD

**Issue by ghost** [parkervcp/eggs#172]
Hello,

The Unturned egg needs to be updated to work with the new Unturned .net 4.6.1 update. This can be done by using the depot id 304937, but I think you still need to do some mono updates as well.

Regards,
TermsGames

**Comment by Edbtvplays** [comment]
Hello,
This is indeed correct. 
Unturned can be used on two differnt .net versions, .net 3.5 is more stable. But 4.6.1 is more updated and a lot of plugins have updated to this. Both work but one is more stable in short. I recommend that two seperate Eggs are made for this, i am currently working on one for both but I am quite busy, I May PR them here once complete. 

Regards ,
Edbtvplays

**Comment by DragonHacker1** [comment]
Hey, might need that.. if is possible i let you an working dockerfile. https://github.com/ImperialPlugins/unturned-docker 
Btw, look is fine but need a bit tweaking the egg adding support (already included versions chooser, 
RocketMod 4 and RocketMod 5 or vanilla

**Comment by Trojaner** [comment]
#248

**Comment by parkervcp** [comment]
I am fairly certain this was fixed resolved by #413 as it doesn't even need mono and works fine.
