### ISSUE TITLE
[Bug]: Missing Value

### ISSUE THREAD

**Issue by 60plus** [parkervcp/eggs#1723]
### Panel Version

1.8.1

### Wings Version

1.6.4

### Service

Arma Reforger

### Modified

No, I did not modify the egg

### Expected Behavior

ability to set up "steamQueryPort"  

### Actual Behavior

missing value "steamQueryPort":

### Steps To Reproduce

install egg
try set up

**Comment by lilkingjr1** [comment]
I can add this, but I don't see point, or maybe I underestimate its need. The Steam Query protocol is off by default according to the docs, rendering the port specification useless. In my testing (when I originally wrote the egg) it seems like this port doesn't need to be allocated or forwarded for the server to be connectable or show in the server list. Maybe something has changed since then, or maybe I just don't understand the special use-case where using the protocol is useful. If you can formulate a reason why adding this variable will help more people using the egg connect successfully to their servers, then I will add it; but I don't want to add an additional required port value to the startup parameters if it's not needed because this can add additional overhead to panel admins managing port allocations or people using deployment automation like WHMCS.

**Comment by 60plus** [comment]
In this case, something else is wrong with this egg because the ping shown on the list of servers is 999+. But in fact it is normal. which discourages people from playing on the server.When I run the server through portainer stack everything is OK. The same if I run the server from windows everything works.

![obraz](https://user-images.githubusercontent.com/73450566/175812795-69d8611d-4d19-4e89-9db7-71aa080f99c0.png)
I thought after the description that this port is responsible for these things.

**Comment by JasonTurk** [comment]
Double check and make sure you have the correct line endings (CR/LR) in your confg.json file. The sever will still run with the wrong one but show a ping of 999+

**Comment by 60plus** [comment]
I don't understand what you mean by correct line endings
![obraz](https://user-images.githubusercontent.com/73450566/175818400-4ae7f20b-c5e1-4831-bb25-35e6f2cc6f59.png)

**Comment by JasonTurk** [comment]
https://en.wikipedia.org/wiki/Newline#Representation

You mention you had the server running in Windows fine so I'm assuming your running the *exact same* config.json file in both.
I'm not 100% sure if the Pterodactyl file manager will convert line endings to LF, but just to be sure download Sublime Text and open up the config.json file then go to View>Line Endings>Unix then save it and re-upload the file in Pterodactyls file manager.

**Comment by JasonTurk** [comment]
Also I think you accidentally have an extra 0 in your ports. 20002 instead of 2002

**Comment by 60plus** [comment]
> Also I think you accidentally have an extra 0 in your ports. 20002 instead of 2002

No it is not a mistake. I wants server to be running on this port.

**Comment by JasonTurk** [comment]
Ok that's fine. I'm willing to bet changing the line endings should make ever thing work.

**Comment by 60plus** [comment]
> Ok that's fine. I'm willing to bet changing the line endings should make ever thing work.

what line endings you are talking about ?

**Comment by lilkingjr1** [comment]
I’ll have to check if the Steam Query protocol is required for the ping to be transmitted properly to the server list. Also, is your node behind a NAT? I noticed your register bind address was a local IP address in your config.

**Comment by 60plus** [comment]
but ports on my router are fowarded. I have Reforger servers running in docker and windows they are showing normal ping. I like to move them to Pterodacty but for some reason is not working.

**Comment by lilkingjr1** [comment]
> but ports on my router are fowarded. I have Reforger servers running in docker and windows they are showing normal ping. I like to move them to Pterodacty but for some reason is not working.

Okay… But that doesn’t answer my question about being behind a NAT/router (it matters for Ptero, as you would know if you read the egg’s README). I didn’t really mention ports. However, does enabling the Steam Query protocol and setting a port manually in the config resolve your issue?

**Comment by JasonTurk** [comment]
Line endings are invisible ways an operating system interprets line breaks. Windows and *nix systems do this two diffident ways that aren't compatible. I was having the *exact same problem* you were and this fixed it.

Download this text editor https://www.sublimetext.com/download then open up the config.json file in it, then go to View>Line Endings>Unix then save it and re-upload the file in Pterodactyls file manager.

**Comment by lilkingjr1** [comment]
> I was having the exact same problem you were and this fixed it.

@JasonTurk Interesting... So you uploaded a config file from Windows with wrong line endings and it caused this issue? Out of curiosity, do you enable the Steam Query protocol in the config and allocate a port for it? Just curious if that is at all a factor and if I need to investigate that further.
