### ISSUE TITLE
[Bug]: Ark Server not installing

### ISSUE THREAD

**Issue by Felix5566** [parkervcp/eggs#1724]
### Panel Version

1.8.1

### Wings Version

1.6.4

### Service

ark-survival evolved 

### Modified

No, I did not modify the egg

### Expected Behavior

[ 27%] Downloading update (18013 of 54952 KB)...
[ 32%] Downloading update (20538 of 54952 KB)...
[ 37%] Downloading update (23052 of 54952 KB)...
[ 41%] Downloading update (25810 of 54952 KB)...
[ 46%] Downloading update (28310 of 54952 KB)...
[ 51%] Downloading update (30763 of 54952 KB)...
[ 55%] Downloading update (33275 of 54952 KB)...
[ 60%] Downloading update (35782 of 54952 KB)...
[ 65%] Downloading update (37633 of 54952 KB)...
[ 68%] Downloading update (38896 of 54952 KB)...
[ 70%] Downloading update (40284 of 54952 KB)...
[ 73%] Downloading update (41560 of 54952 KB)...
[ 75%] Downloading update (42810 of 54952 KB)...
[ 77%] Downloading update (44199 of 54952 KB)...
[ 80%] Downloading update (45474 of 54952 KB)...
[ 82%] Downloading update (46743 of 54952 KB)...
[ 85%] Downloading update (48138 of 54952 KB)...
[ 87%] Downloading update (49408 of 54952 KB)...
[ 89%] Downloading update (50674 of 54952 KB)...
[ 92%] Downloading update (52061 of 54952 KB)...
[ 94%] Downloading update (53333 of 54952 KB)...
[ 97%] Downloading update (54730 of 54952 KB)...
[ 99%] Downloading update (54952 of 54952 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1654574676
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '376030' state is 0x202 after update job.
'linux32/steamclient.so' -> '../.steam/sdk32/steamclient.so'
'linux64/steamclient.so' -> '../.steam/sdk64/steamclient.so'

### Actual Behavior

Server not Downloading Ark

### Steps To Reproduce

Install the Ark Server

Server is under a 1gb of disk usage: https://i.imgur.com/Weahbh0.png

### Install logs

https://pteropaste.com/q6zewa

**Comment by Software-Noob** [comment]
> Error! App '376030' state is 0x202 after update job. 

You don't have enough of disk space. The panel would also inform you of this in a pop-up modal with instructions if you are up to date.
