### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mrfixit935** [parkervcp/eggs#1725]
### Panel Version

1.8

### Wings Version

1.6

### Service

minectaft/forge

### Modified

No, I did not modify the egg

### Expected Behavior

Start the server 

### Actual Behavior

It could not find version 1.15.2.

### Steps To Reproduce

Make a forge server 
watch it install and the last the will say the error

### Install logs

https://ptero.co/ywutysiryz.pl

**Comment by Software-Noob** [comment]
You must specify the exact version as displayed on forge website. It's not a bug if the version you are providing doesn't exist.

**Comment by Mrfixit935** [comment]
What is a version then
