### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mrfixit935** [parkervcp/eggs#1726]
### Panel Version

1.9

### Wings Version

1.6

### Service

Gta/Multitheftauto

### Modified

No, I did not modify the egg

### Expected Behavior

install the server and start it without errors

### Actual Behavior

tar: Error is not recoverable: exiting now
cp: cannot stat 'baseconfig/*': No such file or directory

### Steps To Reproduce

Make a Multitheftauto server
watch it install and the error is right at the end of installing

### Install logs

https://pteropaste.com/8fl5wj

**Comment by QuintenQVD0** [comment]
> 
I did a fresh install of ptero and import the egg from github and works fine (install logs https://pteropaste.com/i6shxe/) 
![afbeelding](https://user-images.githubusercontent.com/67589015/176503182-231c7038-5b74-4e81-a36b-fa6781309a2e.png)
@Mrfixit935

**Comment by Mrfixit935** [comment]
@QuintenQVD0 I am using a discord bot. this is the code That I did for the egg. is there anything wrong with it? https://dpaste.org/pQ66K

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 I am using a discord bot. this is the code That I did for the egg. is there anything wrong with it? https://dpaste.org/pQ66K

there is one extra space on Line 3 https://dpaste.org/pQ66K#L3
but I guess your have a old egg

**Comment by Software-Noob** [comment]
I can't reproduce. Update your egg and make a new installation, because the archive format was fixed. Should the issue persist, reopen the issue and share the full install log from `/var/log/pterodactyl/install/` by pasting it to pastebin or something alike.
