### ISSUE TITLE
[Egg Request]: QuiltMC (for Minecraft)

### ISSUE THREAD

**Issue by James76931** [parkervcp/eggs#1728]
### Does this expand an already existing service

Yes

### Link to a game or software

https://quiltmc.org/

### Links for the download

https://maven.quiltmc.org/repository/release/org/quiltmc/quilt-installer/latest/quilt-installer-latest.jar

### Links for the install docs

https://quiltmc.org/install/server/

**Comment by parkervcp** [comment]
I have said before that I will no longer be adding more minecraft servers to the repo.

**Comment by James76931** [comment]
My apologies, @parkervcp. I wasn't aware of this, but I understand.
