### ISSUE TITLE
[Egg Request]: Modrinth Modpacks (for Minecraft)

### ISSUE THREAD

**Issue by James76931** [parkervcp/eggs#1729]
### Does this expand an already existing service

Yes

### Link to a game or software

https://modrinth.com/modpacks

### Links for the download

N/A

### Links for the install docs

https://docs.modrinth.com/ Has info on modpacks & the Modrinth API spec for egg integration

**Comment by leumasme** [comment]
Why is this closed as completed? I couldn't find a modrinth egg and from other issues it seems like you're not accepting new minecraft egg requests currently - did you mean to close this as not planned/rejected?

**Comment by parkervcp** [comment]
As it stands I am accepting no more minecraft egg requests. If someone want's to PR one I will consider accepting it. accept it.
