### ISSUE TITLE
[Bug]: Installation for FTB Modpacks using Java 17 and the FTB egg not completing install

### ISSUE THREAD

**Issue by thaimichael** [parkervcp/eggs#1731]
### Panel Version

1.9.1

### Wings Version

1.6.4

### Service

minecraft/java/ftb

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, push start, eula popup, start server.

### Actual Behavior

Installing any of the 1.18 or 1.19 servers using java 17 and the ftb egg is not working.

During install most things download:
Patching com/mojang/blaze3d/vertex/VertexFormatElement$Usage$SetupState 1/1
The server installed successfully
You can delete this installer file now if you wish

the final configuration does not seem to complete
2022/06/30 10:19:38 Extracting jdk-17.0.2+8-jre/legal/java.xml/bcel.md -> jre/jdk-17.0.2+8-jre/legal/java.xml/bcel.md
2022/06/30 10:19:38 Installed!
mv: cannot stat 'forge-*.jar': No such file or directory

tried all 4 current servers using java 17
FTB Presents Direwolf20 1.18
FTB Plexiglass Mountain
FTB One
FTB Chocolate

all 4 stopped at "mv: cannot stat 'forge-*.jar': No such file or directory"

all expected mods and files have been downloaded.

The forge-server.jar does not complete

Tried a couple of 1.16 modpacks and the egg worked as expected

### Steps To Reproduce

Step 1: install latest egg-ftb-modpacksch-server.json
    "meta": {
        "version": "PTDL_v1",
        "update_url": null
    },
    "exported_at": "2021-06-14T21:28:54+03:00",
Step 2: Configure server to use Nest:Minecraft, Egg:FTB=modpacks.ch Server, Select java 17 yolk  Select FTB modpack ID i.e. 95 FTB Pack Version ID i.e. 2141 (example is for dirwold20 1.18 1.5.0  
Step 3 Save Modifications
Step 4 Reinstall Server

### Install logs

https://pteropaste.com/ok7z8n

**Comment by thaimichael** [comment]
Did more looking and it appears the 1.18 and 1.19 modpacks now do not put the forge jar in the directory where it use to be.  This is from the start.sh file on the startup for linux
./jre/jdk-17.0.2+8-jre/bin/java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.1.47/unix_args.txt nogui

**Comment by Software-Noob** [comment]
> Did more looking and it appears the 1.18 and 1.19 modpacks now do not put the forge jar in the directory where it use to be. This is from the start.sh file on the startup for linux ./jre/jdk-17.0.2+8-jre/bin/java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.1.47/unix_args.txt nogui

Forge 1.17+ uses JPMS, instead of a single bundled jar.
