### ISSUE TITLE
[Egg Request]: Add Lost Island to ARK EGG

### ISSUE THREAD

**Issue by JamesKhan2k6** [parkervcp/eggs#1734]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/1691800/Lost_Island__ARK_Expansion_Map/

### Links for the download

https://store.steampowered.com/app/1691800/Lost_Island__ARK_Expansion_Map/

### Links for the install docs

https://store.steampowered.com/app/1691800/Lost_Island__ARK_Expansion_Map/

**Comment by gOOvER** [comment]
you can use LostIsland allready witrh ARK Egg

**Comment by JamesKhan2k6** [comment]
Thanks for the quick reply. 
It's not stated that the map is available. 

![image](https://user-images.githubusercontent.com/22389226/176988053-8a687a6b-581c-452e-9819-d86fbedf81ad.png)

Thanks.

**Comment by QuintenQVD0** [comment]
> Thanks for the quick reply. It's not stated that the map is available.
> 
> ![image](https://user-images.githubusercontent.com/22389226/176988053-8a687a6b-581c-452e-9819-d86fbedf81ad.png)
> 
> Thanks.

It is added to the egg shiped with ptero and will be listed in the next update

**Comment by JamesKhan2k6** [comment]
So I tried entering it in to the server map manually, but it didn't work. No one can connect to it. We I use a map that is listed, it works. I guess I'll wait for it to get updated in the next release.

Thanks for your help.

**Comment by Software-Noob** [comment]
No new update issue required to support it. The variable description is just that; a description.

**Comment by QuintenQVD0** [comment]
I am gone close this as it is just a description notthing limits you from using that map
