### ISSUE TITLE
[Egg Request]: ARM versions

### ISSUE THREAD

**Issue by kry008** [parkervcp/eggs#1739]
### Does this expand an already existing service

Yes

### Link to a game or software

Everything what is possible 

### Links for the download

For example: terraria, TS3, Minecraft, gitea, 

### Links for the install docs

quintenqvd\/pterodactyl_images:mono, this docker works

**Comment by kry008** [comment]
https://github.com/QuintenQVD0/Q_eggs

**Comment by yesBad** [comment]
Minecraft already works on ARM.

**Comment by kry008** [comment]
> Minecraft Java already works on ARM.
> 
> Also how would this help with Gitea?

Only work eggs which are on java, in gitea doesn't work ssh.

**Comment by yesBad** [comment]
It's not only Java eggs that work to be fair.

**Comment by kry008** [comment]
> It's not only Java eggs that work to be fair.

I've tried all, only work eggs that are on Java, but i open this for not only Minecraft, also Terraria (in link is working), gitea, TS3. Last three don't work from this repo.

**Comment by kry008** [comment]
```
Linux vpn 5.15.0-1003-oracle #5-Ubuntu SMP Wed Apr 20 04:51:36 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by QuintenQVD0** [comment]
From my repo? The all work on my pi 4 

> > It's not only Java eggs that work to be fair.
> 
> I've tried all, only work eggs that are on Java, but i open this for not only Minecraft, also Terraria (in link is working), gitea, TS3. Last three don't work from this repo.

**Comment by parkervcp** [comment]
@QuintenQVD0 I don't know why you are assuming I won't accept PRs for images and arm versions of an egg.

**Comment by kry008** [comment]
But first how to mark that is ARM or AMD64, some already works for both (i try NodeJS eggs, Minecraft Java servers, openttd, visual studio code server) Gita and TS3 don't work on arm from oracle

**Comment by QuintenQVD0** [comment]
I made in the past a PR to the gitea egg to make it multi arch and it got merged.
It works on my pi 4 arm64 debian 11
![afbeelding](https://user-images.githubusercontent.com/67589015/177379616-690e1eae-1e49-4c1d-9ccc-2f7eefac0d2a.png)

**Comment by kry008** [comment]
@QuintenQVD0 


> I made in the past a PR to the gitea egg to make it multi arch and it got merged. It works on my pi 4 arm64 debian 11 ![afbeelding](https://user-images.githubusercontent.com/67589015/177379616-690e1eae-1e49-4c1d-9ccc-2f7eefac0d2a.png)
