### ISSUE TITLE
[Bug]: Velocity Egg config file error and outdated velocity.toml

### ISSUE THREAD

**Issue by itsmemac** [parkervcp/eggs#1741]
### Panel Version

1.9.2

### Wings Version

1.6.4

### Service

game_eggs/minecraft/proxy/java/velocity/

### Modified

No, I did not modify the egg

### Expected Behavior

Veloctiy egg should generate the velocity.toml file with all the required settings in the file and should be using latest velocity.toml

### Actual Behavior

1. Once the velocity server is installed, the velocity.toml provide in the first install is v1.0 which isn't secure anymore and cannot be used for latest version of Velocity
```You are currently using a deprecated configuration version. The "forwarding-secret" parameter has been recognized as a security concern and has been removed in config version 2.0. It's recommended you rename your current "velocity.toml" to something else to allow Velocity to generate a config file of the new version. You may then configure that file as you normally would. The only differences are the config-version and "forwarding-secret" has been replaced by "forwarding-secret-file".```
should be using the latest v2.0 velocity.toml file from 
https://raw.githubusercontent.com/PaperMC/Velocity/dev/3.0.0/proxy/src/main/resources/default-velocity.toml

2. Once the default 1.0 velocity.toml is generated and then we stop the server. Remove all the files from the server except serve.jar, start the server
The server only generates incomplete velocity.toml file with just ```forwarding-secret = "xxxxxxxx"``` in the file and nothing more.
![image](https://user-images.githubusercontent.com/37410297/177486038-ffb793fa-f97e-4471-ab15-946ba669a61c.png)
Change the server to waterfall egg and do the above steps, it generates velocity.toml with all the information correctly without any issue

### Steps To Reproduce

1. Select Velocity Egg
2. Create the server
3. Remove all the files expect server.jar
4. Start the server again

### Install logs

https://pteropaste.com/530qaj

**Comment by parkervcp** [comment]
@itsmemac you said converting to a waterfall server generates a valid velocity toml. Does that mean velocity is built into waterfall? Can I just remove velocity?

**Comment by parkervcp** [comment]
I didn't write the velocity egg. We can update to jave it just pull the egg from the paper repo instead. they didn't have one at the time so I have my own.

**Comment by electronicboy** [comment]
The velocity egg is for some reason downloading a config file to the disk which weirds me out, the reason why the waterfall egg works is because it doesn't do anything, don't have a ptero setup to diagnose this, but, the startup logic in there to pull the file just looks weird
