### ISSUE TITLE
[Egg Request]: linuxserver/code-server

### ISSUE THREAD

**Issue by felipe-negri** [parkervcp/eggs#1746]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/linuxserver/docker-code-server

### Links for the download

https://github.com/linuxserver/docker-code-server

### Links for the install docs

https://github.com/linuxserver/docker-code-server

**Comment by felipe-negri** [comment]
a cod-server version with a linux server

**Comment by parkervcp** [comment]
There is already a code server egg.
