### ISSUE TITLE
[Bug]: Panel crashing while importing MariaDB egg

### ISSUE THREAD

**Issue by SpielenmitLili** [parkervcp/eggs#1747]
### Panel Version

1.9.2

### Wings Version

1.6.4

### Service

database/sql/mariadb

### Modified

No, I did not modify the egg

### Expected Behavior

Import the egg and use it to create a server with the database MariaDB

### Actual Behavior

First do this:
![image](https://user-images.githubusercontent.com/74246564/177852034-3407f589-290b-4cab-a60b-07aaf28c5bbd.png)
Used code
![image](https://user-images.githubusercontent.com/74246564/177852144-7d43ec11-5890-4b36-b280-4f54b23cb7b1.png)
Than get this:
![image](https://user-images.githubusercontent.com/74246564/177851356-82a600a5-9519-41f7-ae67-f06e154a1255.png)
After reload the page:
![image](https://user-images.githubusercontent.com/74246564/177851361-b26662cb-ba5b-432c-8224-df673ba8beca.png)

### Steps To Reproduce

Step 1: Go to https://panel.example.org/admin/nests
Step 2: Click on "Import egg"
Step 3: Select the downloaded file ( https://github.com/ign-gg/Pterodactyl-Eggs/blob/master/database/sql/mariadb/egg-maria-d-b.json )
Step 4: Select Associated Nest 
Step 5: Click on import
Step 6: Get the errpr

### Install logs

https://pteropaste.com/bl9m1k

**Comment by parkervcp** [comment]
The egg you linked in the reproduction steps is not the egg from my repo.
