### ISSUE TITLE
[Egg Request]: 

### ISSUE THREAD

**Issue by Vondyy** [parkervcp/eggs#1748]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/coleifer/sqlite-web

### Links for the download

https://github.com/coleifer/sqlite-web

### Links for the install docs

https://github.com/coleifer/sqlite-web

**Comment by parkervcp** [comment]
This is not exactly usable in pterodactyl with the separation of server. You would need to manually upload your sqlite files and it opens one at a time.
