### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CGCNight** [parkervcp/eggs#1754]
### Panel Version

1.9.2

### Wings Version

1.6.4

### Service

game_eggs/cod/cod4x/

### Modified

No, I did not modify the egg

### Expected Behavior

The script was expected to automatically download the latest version of cod4x server linux.

### Actual Behavior

The script didnt download anything cuz cod4x.me doesnt exist anymore. They moved to cod4x.ovh and they created a new link for download cod4x-server-linux files. Also current steps inside script will not work(I mean on moving/removing zip files, since zip file has 2 folders on download). 
New link is pointed to: https://cod4x.ovh/uploads/short-url/59kvOM9hBabZjPJRlLX029BcskI.zip
/cod4x_server-linux_21.2/cod4x-linux-server/*

### Steps To Reproduce

Install servers with egg
Server isnt installed properly

### Install logs

no logs required

**Comment by parkervcp** [comment]
So I am just going to remove the cod eggs. I am uninterested in dealing with them.
