### ISSUE TITLE
[Egg Request]: Astroneer

### ISSUE THREAD

**Issue by ZaxLofful** [parkervcp/eggs#1757]
### Does this expand an already existing service

No, new game using SteamCMD.

### Link to a game or software

https://store.steampowered.com/app/361420/ASTRONEER/

### Links for the install docs

https://blog.astroneer.space/p/astroneer-dedicated-server-details/

https://steamcommunity.com/app/361420/discussions/0/2281582783370192139/

**Comment by gOOvER** [comment]
still Not possible, because there is No Linux Server and the Game dont Run in wine.

**Comment by ZaxLofful** [comment]
https://github.com/alatnet/astroneer-docker-server

**Comment by ZaxLofful** [comment]
Is this a wine issue? Like if someone were to figure out the bug in Wine; it would work fine?

**Comment by gOOvER** [comment]
duplicate #544
