### ISSUE TITLE
[Egg Request]:  FTL: tachyons

### ISSUE THREAD

**Issue by LoneWolfGmer** [parkervcp/eggs#1761]
### Does this expand an already existing service

Yes

### Link to a game or software

https://spektor.itch.io/tachyon

### Links for the download

https://spektor.itch.io/tachyon/download/eyJleHBpcmVzIjoxNjU4MTAyMDQ5LCJpZCI6NjY2NzF9%2eKrFlcd3mf%2byhZdiMhDAtmfT0mtY%3d

### Links for the install docs

https://www.subsetgames.com/forum/viewtopic.php?f=12&t=28850

**Comment by LoneWolfGmer** [comment]
i later found these for the install docs. this may be helpful to you
https://help.1e.com/display/TCN51/Tachyon+Setup

**Comment by Software-Noob** [comment]
This already exists [FTL: Tachyon.](https://github.com/parkervcp/eggs/tree/master/game_eggs/ftl/tachyon)

The only difference is that they added an additional new letter `S` to their rebranded name.

> i later found these for the install docs. this may be helpful to you [help.1e.com/display/TCN51/Tachyon+Setup](https://help.1e.com/display/TCN51/Tachyon+Setup)

This is an enterprise SaaS product named tachyon.
