### ISSUE TITLE
[Bug]: Rust Egg (all)

### ISSUE THREAD

**Issue by GameHackerTV** [parkervcp/eggs#1762]
### Panel Version

1.9.2

### Wings Version

1.6.4

### Service

rust

### Modified

No, I did not modify the egg

### Expected Behavior

Install server / start server

### Actual Behavior

![IMG_20220718_091600](https://user-images.githubusercontent.com/86518375/179455336-42ba628b-2ff9-4f0f-b41c-bf2347dc2a6b.jpg)
then writes that quay.io/pterodactyl/core:rust does not exist 

### Steps To Reproduce

1) Install a server with a default egg that is built into the panel / download auto wipe egg from github
2) Try to install server / run 

### Install logs

it's not in the panel, but in the docker

**Comment by GameHackerTV** [comment]
root@Ubuntu-2004-focal-64-minimal ~ # docker pull quay.io/pterodactyl/core:rust rust: Pulling from pterodactyl/core                                             68e7bb398b9f: Retrying in 10 seconds                                            73c55fbbe6d7: Retrying in 10 seconds                                            be0ed1e1ca74: Retrying in 10 seconds                                            780b1d634b5f: Waiting                                                           error pulling image configuration: download failed after attempts=6: dial tcp 108.157.214.32:443: i/o timeout

**Comment by Software-Noob** [comment]
This is a system issue and not an egg one. Troubleshoot why your machine fails to reach the registry to pull the image.
