### ISSUE TITLE
[Bug]: LeagueSandbox (cp: cannot stat 'GameServerConsole/bin/Debug/netcoreapp3.0/*': No such file or directory)

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1765]
### Panel Version

latest latest

### Wings Version

latest latest

### Service

game_eggs/leaguesandbox

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server

### Actual Behavior

Server install fails, therefore start fails.

### Steps To Reproduce

Install egg
Install server
Problem.

### Install logs

https://pastebin.com/96LmVmWx

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> 
> latest latest
> ### Wings Version
> 
> latest latest
> ### Service
> 
> game_eggs/leaguesandbox
> ### Modified
> 
> No, I did not modify the egg
> ### Expected Behavior
> 
> Install the server
> ### Actual Behavior
> 
> Server install fails, therefore start fails.
> ### Steps To Reproduce
> 
> Install egg Install server Problem.
> ### Install logs
> 
> https://pastebin.com/96LmVmWx

This egg and image is old.
I tryed to fix it but it looks like it needs wine and dotnet
I do not have time to make / fix this 
This is the version that I currently have , I have no idea if it works:

```json
{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v2",
        "update_url": null
    },
    "exported_at": "2022-07-20T18:39:16+02:00",
    "name": "LeagueSandbox",
    "author": "domi@imagine.team",
    "description": "A simple egg to run LeagueSandbox server in pterodactyl",
    "features": null,
    "docker_images": {
        "ghcr.io\/parkervcp\/yolks:dotnet_6": "ghcr.io\/parkervcp\/yolks:dotnet_6"
    },
    "file_denylist": [],
    "startup": ".\/GameServerConsole --port {{SERVER_PORT}}",
    "config": {
        "files": "{}",
        "startup": "{\r\n    \"done\": \"Game is ready.\"\r\n}",
        "logs": "{}",
        "stop": "^C"
    },
    "scripts": {
        "installation": {
            "script": "#!\/bin\/bash\r\n\r\napt update\r\napt install -y zip unzip jq curl wget git\r\n\r\nmkdir -p \/mnt\/server\r\ncd \/mnt\/server\r\n\r\ngit clone https:\/\/github.com\/LeagueSandbox\/GameServer.git\r\nrm .git -rf\r\n\r\ncd GameServer\/\r\n\r\ngit submodule init\r\ngit submodule update\r\n\r\n#wget https:\/\/packages.microsoft.com\/config\/debian\/11\/packages-microsoft-prod.deb -O packages-microsoft-prod.deb\r\n#dpkg -i packages-microsoft-prod.deb\r\n#rm packages-microsoft-prod.deb\r\n#apt-get update\r\n#apt-get install -y apt-transport-https\r\n#apt-get update\r\n#apt-get install -y dotnet-sdk-5.0\r\n\r\ndotnet build .\r\ncp -r GameServerConsole\/bin\/Debug\/net6.0\/* \/mnt\/server\/\r\ncp -r Content \/mnt\/server\/Content\r\necho \"done\"",
            "container": "bitnami\/dotnet-sdk:6-debian-11",
            "entrypoint": "bash"
        }
    },
    "variables": []
}
```

**Comment by BenasPaulikas** [comment]
Your egg logs https://pastebin.com/P1Lhhrh1
It fails to build

**Comment by BenasPaulikas** [comment]
@QuintenQVD0 ty

Your egg logs https://pastebin.com/P1Lhhrh1
It fails to build

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 ty
> 
> Your egg logs https://pastebin.com/P1Lhhrh1 It fails to build

This are clezrly no logs from my egg as it spins out a apk error , and that is not use in the egg i sended here

**Comment by QuintenQVD0** [comment]
Try making a new server with this egg not reinstalling.

**Comment by BenasPaulikas** [comment]
Much better. Thank you
