### ISSUE TITLE
[Egg Request]: Curse-Updates Discord Bot

### ISSUE THREAD

**Issue by Charismara** [parkervcp/eggs#1773]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/Davoleo/curse-updates

### Links for the download

https://github.com/Davoleo/curse-updates

### Links for the install docs

https://github.com/Davoleo/curse-updates#running-your-own-version-of-this-bot-self-hosting

**Comment by yesBad** [comment]
I don't think there's a need for an egg. You can just use the Node (DiscordJS) egg.

**Comment by gOOvER** [comment]
you can use the Discord.js egg for this

**Comment by Software-Noob** [comment]
As mentioned above, the discord.js egg for running javascript applications can run this.
