### ISSUE TITLE
[Bug]: RedM server will not finish setting up.

### ISSUE THREAD

**Issue by jev217** [parkervcp/eggs#1776]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

RedM

### Modified

No, I did not modify the egg

### Expected Behavior

Setup the server with the needed variables and then the server sets up the basic environment.

### Actual Behavior

I input the asked variables then the server doesn't start with the following message:
```
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${CFX_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +exec server.cfg +set gamename rdr3
/entrypoint.sh: line 13: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: No such file or directory
```

### Steps To Reproduce

Step 1: Import the egg
Step 2: Create a server with said egg
Step 3: Wait awhile and the server will still say setting up
Step 4: Start the server

### Install logs

https://pteropaste.com/h9gfuk

**Comment by parkervcp** [comment]
The cfx changelog site is currently down. This is not an egg issue.
