### ISSUE TITLE
[Bug]: FiveM egg not working.

### ISSUE THREAD

**Issue by WagonToZiomal** [parkervcp/eggs#1778]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

fivem

### Modified

No, I did not modify the egg

### Expected Behavior

The server installs with alpine.

### Actual Behavior

The server didn't install with alpine meaning it is useless.

### Steps To Reproduce

Install

### Install logs

https://pteropaste.com/p71z5l

**Comment by parkervcp** [comment]
Currently the fivem changelog site is down. This is how we were tracking versions. This is not an egg issue but their changelog site being down.
