### ISSUE TITLE
Bastion discord bot youtube-dl crash

### ISSUE THREAD

**Issue by GoldeneK** [parkervcp/eggs#178]
Panel Version: 0.7.13
Daemon Version: 0.6.11
Service: bastion discord bot
Modified: (yes/no) no
Expected Behavior:
Start
Actual Behavior:
Crash
Steps to Reproduce: (Step by step what to do to cause the issue)
Click button "start" under the console

Logs: https://hastebin.com/tezaqikana.md

**Comment by HexDevOfficial** [comment]
It says here you don't have youtube-dl installed. It's possible you haven't installed the `youtube-dl` module. If you have then you may need to reupload the `package.json` and `package-lock.json` files to the server.

**Comment by aldun** [comment]
Panel Version: 0.7.13
Daemon Version: 0.6.12
Service: Bastion
Modified: No
Expected Behavior: Start
Actual Behavior: Crash
Steps to Reproduce: Fresh install of Bastion bot and attempt to start.

I'm having this same issue.

**Comment by NgLoader** [comment]
Try

npm install youtube-dl

**Comment by parkervcp** [comment]
I will accept the PR and close this out then since there has been no confirmation.
