### ISSUE TITLE
[Bug]: No Czech characters like ěščřž in the log files of PZ server

### ISSUE THREAD

**Issue by Bazimek** [parkervcp/eggs#1780]
### Panel Version

1.10.1

### Wings Version

1.6.4

### Service

Project Zomboid

### Modified

No, I did not modify the egg

### Expected Behavior

To have Czech characters like ěščřžý visible in the log files.

### Actual Behavior

For example:
This is in chat: "čau čau"

In the log and console:
New message 'ChatMessage{chat=General, author='Bazim', text='?au ?au'}' was sent members of chat '0'

### Steps To Reproduce

Step 1: Post in chat Czech characters and watch the console.

I tried the update locale-gen and /etc/locale.gen, restart the machine, but it does not work. And in the install log I see this:
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.

### Install logs

https://pteropaste.com/qcvueo

**Comment by QuintenQVD0** [comment]
not realy egg releated as ptero only supports the Basis ASCII codes 0 tot 127 and mayby the EXTENDED ASCII TABEL
https://www.asciitable.com/
