### ISSUE TITLE
[Egg Request]: 

### ISSUE THREAD

**Issue by KillerCrazy25** [parkervcp/eggs#1782]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/Fallen-Breath/MCDReforged

### Links for the download

https://github.com/Fallen-Breath/MCDReforged/releases/

### Links for the install docs

https://mcdreforged.readthedocs.io/en/latest/

**Comment by parkervcp** [comment]
The panel already controls the server. We don't need a wrapper inside to manage the server on top of that.
