### ISSUE TITLE
[Bug]: MariaDB can't start

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [parkervcp/eggs#1783]
### Panel Version

1.7

### Wings Version

1.6.1

### Service

MariaDB

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Work

### Actual Behavior

Crashing after start

### Steps To Reproduce

Install Egg
Change quay to ghcr
Create server
Try to start it

### Install logs

https://pastebin.com/KBMZWx6N

**Comment by MrMasrozYTLIVE** [comment]
Oops. Put Crash log into Install log. I'm stupid, sorry

**Comment by docimin** [comment]
@MrMasrozYTLIVE Hello there!
Would you be so nice and send the egg that you are using? :)

**Comment by MrMasrozYTLIVE** [comment]
> @MrMasrozYTLIVE Hello there!
> Would you be so nice and send the egg that you are using? :)

It is same as normal, just switched guay to ghcr so i can run it on arm cpu

**Comment by docimin** [comment]
I see that the issue is even on default install.
See issue #1717

**Comment by MrMasrozYTLIVE** [comment]
> I see that the issue is even on default install. See issue #1717

i fixed that issue (I think) but it still doesn't want to run

**Comment by MrMasrozYTLIVE** [comment]
^ Missclick lol

**Comment by GaryCraft** [comment]
Can confirm this issue

**Comment by QuintenQVD0** [comment]
The egg has been changed to support only 10.3, we need some changes to the wings for other versions to work. 10.3 works just fine
