### ISSUE TITLE
[Egg Request]: Minecraft Arclight Server

### ISSUE THREAD

**Issue by Charismara** [parkervcp/eggs#1785]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/IzzelAliz/Arclight

### Links for the download

https://github.com/IzzelAliz/Arclight/releases

### Links for the install docs

https://github.com/IzzelAliz/Arclight#installing

**Comment by yesBad** [comment]
Pretty sure Parker doesn't wanna add more MC eggs

**Comment by parkervcp** [comment]
I do not need more minecraft servers. All the other eggs have download links.
