### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1786]
### Panel Version

latest heehee

### Wings Version

latest heehee

### Service

minecraft/java/magma

### Modified

No, I did not modify the egg

### Expected Behavior

Install server

### Actual Behavior

Install fails

```
Setting up libcurl4:amd64 (7.74.0-1.3+deb11u1) ...
Setting up curl (7.74.0-1.3+deb11u1) ...
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Version not set. Defaulting to latest
running: curl -sSL -o installer.jar 
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
1.16.5 or newer version detected. Running installer
Error: Unable to access jarfile installer.jar
install failed exit 4
mv: cannot stat 'forge-*.jar': No such file or directory
Deleting installer.jar file.
Install Complete
```

### Steps To Reproduce

Download egg. Install server with that egg

### Install logs

above

**Comment by parkervcp** [comment]
your versions are not valid and heehee doesn't make it funny. That also looks like a dns failure which is not an egg issue.
