### ISSUE TITLE
[Bug]: MongoDB Default startup script throwing exec format error

### ISSUE THREAD

**Issue by vlink102** [parkervcp/eggs#1787]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

database/nosql/mongodb

### Modified

No, I did not modify the egg

### Expected Behavior

Expected to startup and start the MongoDB server

### Actual Behavior

```
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:db_mongo-4 
Digest: sha256:f8a22f87ec21ef005f79ebaafd93424f0d3d0e2f4faf129fde2b6cacc20ac552 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
exec /usr/local/bin/docker-entrypoint.sh: exec format error
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:db_mongo-4 
Digest: sha256:f8a22f87ec21ef005f79ebaafd93424f0d3d0e2f4faf129fde2b6cacc20ac552 
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /usr/local/bin/docker-entrypoint.sh: exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

### Steps To Reproduce

Step 1: Install latest version of mongodb egg from github raw download
Step 2: import egg to pterodactyl under any nest
Step 3: Create and run server without changing scripts
Step 4: It won't run

### Install logs

https://pteropaste.com/a0147o/

**Comment by rotvproHD** [comment]
Can not reproduce, why? i dont use ARM.
Exact Words from Bot:

The Docker image or application that you are trying to use does not support your CPU architecture. Support for ARM64 is scarce, and most applications do not support it; thus, Docker images for those applications are built for AMD64(x86_64) only.

Multiarch Docker images have been built for applications that do run on ARM64, so make sure that your egg and docker image is up to date. SteamCMD eggs will not work at all.

**Comment by Software-Noob** [comment]
The image doesn't support your CPU architecture, which in this case is not AMD64.

You can try replacing it with `ghcr.io/parkervcp/yolks:mongodb_4` and see if that works. Yolks image is multi-arch but hasn't been tested with the egg.

**Comment by vlink102** [comment]
> The image doesn't support your CPU architecture, which in this case is not AMD64.
> 
> You can try replacing it with `ghcr.io/parkervcp/yolks:mongodb_4` and see if that works. Yolks image is multi-arch but hasn't been tested with the egg.

Thanks, i've done it with the multi-arch one and it works properly now sorry about the bug report 😬

**Comment by Software-Noob** [comment]
This can stay open until the egg is updated to use the new images.

**Comment by QuintenQVD0** [comment]
> This can stay open until the egg is updated to use the new images.

This can be closed: https://github.com/parkervcp/eggs/pull/1838
