### ISSUE TITLE
[Bug]: FiveM egg not working, screenshot included

### ISSUE THREAD

**Issue by Djassie18698** [parkervcp/eggs#1788]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

Server should install

### Actual Behavior

Server can not start

### Steps To Reproduce

Setup server like normal and start server
![image](https://user-images.githubusercontent.com/51295582/182251814-e2448a93-f914-4b24-a849-3f2638c81def.png)

### Install logs

https://pteropaste.com/ij6qqu

**Comment by docimin** [comment]
Hey @Djassie18698, if i remember correctly, FiveM has been really toxic towards self hosting if i remember correctly and even implemented malicious code at one point.

As again, as far as i remember, Pterodactyl no longer supports FiveM
https://discord.com/channels/122900397965705216/124919575534895105/869733533495746560
![image](https://user-images.githubusercontent.com/30414906/182568121-91a3e748-44bc-49de-bd32-93b89b913bb2.png)

However, if you still want help to set it up, I would say check the curl -o installation part:
`curl -sSL ${DOWNLOAD_LINK} -o ${DOWNLOAD_LINK##*/}` on line 42, as it appears it cannot find the ${DOWNLOAD_LINK##*/} variable.

Have a wonderful Day!

**Comment by Djassie18698** [comment]
@docimin Ah! I didn't know that! That sucks to hear. I will try with the method you provided, and if that doesn't work I'll get something that is a little bit less toxic. Thank you anyway!

**Comment by docimin** [comment]
Yeah no worries, feel free to close the issue!

**Comment by Djassie18698** [comment]
One last question @docimin Where can i find the installation part? The only thing i find is the install script but that's only 32 lines. If you could send me in the right direction that will be the last FiveM related thing I will do on here!

**Comment by Djassie18698** [comment]
Ah, i think im in way over my head! I'm not bad with pc's, but linux/scripting is a league higher. Don't think I'm able to know what im doing, even if you guide me in the right direction :p! I do appreciate you looking into this, thankyou!

**Comment by docimin** [comment]
Hey @Djassie18698,
You are free to do whatever :)

The total FiveM script should be 72 lines.
I just noticed that the FiveM egg has been updated, which seems to work. So i would recommend to update the egg: https://github.com/parkervcp/eggs/blob/master/game_eggs/gta/fivem/egg-five-m.json
