### ISSUE TITLE
[Bug]: Fix for Starbound server egg

### ISSUE THREAD

**Issue by unquietwiki** [parkervcp/eggs#1789]
### Panel Version

1.9.2

### Wings Version

1.7.0

### Service

starbound

### Modified

No, I did not modify the egg

### Expected Behavior

Starbound server would execute. Attempting to change to **./linux/starbound_server** also did not help.

### Actual Behavior

**./starbound_server** and/or other files would not be found.

_Working command fix:_ **cd linux && ./starbound_server**

### Steps To Reproduce

1. Attempt unmodified egg install of Starbound.
2. SteamCMD downloads the files successfully.
3. Container fails after unable to find starbound_server.

_Working command fix:_ **cd linux && ./starbound_server**

### Install logs

n/a

**Comment by unquietwiki** [comment]
Weird... reinstalled the image trying to add a mod, and the issue reverted itself.

**Comment by unquietwiki** [comment]
_[Info] Root: Writing runtime configuration to './storage/starbound_server.config'
[Error] Fatal Exception caught: (IOException) Error opening file './mods/*.pak', error: No such file or directory_

Okay... I guess there's a new issue after all; just not the one I originally reported.

**Comment by unquietwiki** [comment]
Re-closing again. Need to figure out what exactly the bug is & re-issue a new report. Due apologies.

**Comment by Wazbat** [comment]
Running into this same issue ourselves. A fresh install of Pterodactyl and we're also getting this error after the game downloads. It seems to download fine, but we get the same error relating to `./starbound_server` not being found

**Comment by unquietwiki** [comment]
@Wazbat I did a PR to try to fix this; https://github.com/parkervcp/eggs/pull/1791

They want more adjustments before approving; I'll have that tried & tested this week, as able.
