### ISSUE TITLE
OpenTTD version is out-of-date

### ISSUE THREAD

**Issue by Jeroen52** [parkervcp/eggs#179]
OpenTTD is version 1.8.0 in these eggs, the latest version is 1.9.1.

I tried to look if there are recent binaries, however it appears that the only things available right now are packages.

**Comment by parkervcp** [comment]
Considering they got rid of the generic files for OpenTTD it seems like they may not care about anyone trying to run it on non-ubuntu distros

**Comment by parkervcp** [comment]
There I fixed it. 

There are now variables for the OpenTTD and OpenGFX versions.

this will now only support 1.9.0 and later as the removed the generic tar files.
