### ISSUE TITLE
[Bug]: Valheim cannot quickly skip GPU shaders at startup, resulting in long waits

### ISSUE THREAD

**Issue by aopkcn** [parkervcp/eggs#1795]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

Valheim

### Modified

No, I did not modify the egg

### Expected Behavior

Is there a solution?

### Actual Behavior

wait too long-nographics in -nographics -batchmode in startup command doesn't seem to work, the wait time is too often about 10 minutes

### Steps To Reproduce

[Message:   BepInEx] Chainloader startup complete
08/04/2022 19:57:13: Starting to load scene:start
ERROR: Shader UI/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Lux Lit Particles/ Bumped shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Legacy Shaders/Particles/Additive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Autodesk Interactive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Unlit/Color shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/Particles/Alpha Blended shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/Particles/Alpha Blended Premultiply shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
HDR Render Texture not supported, disabling HDR on reflection probe.
HDR Render Texture not supported, disabling HDR on reflection probe.
Unloading 6 Unused Serialized files (Serialized files now loaded: 1)

### Install logs

1

**Comment by gOOvER** [comment]
i See No error

**Comment by aopkcn** [comment]
Valheim cannot quickly skip GPU shaders at startup, resulting in long waits

**Comment by aopkcn** [comment]
[wings.log](https://github.com/parkervcp/eggs/files/9259669/wings.log)

**Comment by gOOvER** [comment]
> Valheim cannot quickly skip GPU shaders at startup, resulting in long waits

Thats not an Egg problem; ask the Devs of Valheim. Thats an engine problem

**Comment by aopkcn** [comment]
It is normal for this problem to occur. If you wait too long, it should be your network problem. Please delete the server and recreate it and try again!
My problem has been solved.
