### ISSUE TITLE
[Egg Request]: Dark and Light

### ISSUE THREAD

**Issue by aopkcn** [parkervcp/eggs#1796]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/529180

### Links for the download

https://steamdb.info/app/684480/

### Links for the install docs

no

**Comment by gOOvER** [comment]
There is no Server:

<html>
<body>


ReleaseState | unavailable
-- | --



</body>
</html>

**Comment by parkervcp** [comment]
I am going to go with a no on this due to it being early access with no server software.
