### ISSUE TITLE
Factorio recommended option: require_user_verification

### ISSUE THREAD

**Issue by Jeroen52** [parkervcp/eggs#180]
I think it is really useful to have this as a configuration option, it is a simple boolean.

True: Only users who are authenticated via Factorio.com can enter the server.
False: The opposite from above.

**Comment by parkervcp** [comment]
The configuration is stupid and only accepts 0/1 as input for a boolean value. which I assume the config takes true/false only.

**Comment by Jeroen52** [comment]
It doesn't allow 0/1 but it does allow false/true.

Op wo 10 apr. 2019 03:57 schreef Michael (Parker) Parker <
notifications@github.com>:

**Comment by parkervcp** [comment]
The laravel boolean in the panel is 0/1 only not true/false.

**Comment by Jeroen52** [comment]
I've noticed that when I tested it yesterday, I've made my own
implementation locally that I'm using that is basically a string with a max
length of 5 chars.

**Comment by parkervcp** [comment]
put the word plus in there and see how it does.

You can make a regex. But I don't think it's that hard for a user to change a config. The startup config is more to enforce certain settings.
