### ISSUE TITLE
[Music bots not playing music]: 

### ISSUE THREAD

**Issue by JanjyTapYT** [parkervcp/eggs#1808]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

bots/discord/discord.js

### Modified

No, I did not modify the egg

### Expected Behavior

When the server is started and running and i try to play a song with the music bot it dosent play music.

### Actual Behavior

nothing

### Steps To Reproduce

Step1: Start the Server
Step2: When the server is started try playing a song inside of discord

### Install logs

https://pteropaste.com/1ij2bg/

**Comment by QuintenQVD0** [comment]
This sounds more like a coding issue then a egg / panel issue

**Comment by parkervcp** [comment]
This is not an issue caused by pterodactyl.
