### ISSUE TITLE
[Bug]: Avorion server not allowing mods to read/write files

### ISSUE THREAD

**Issue by RogueRaiden** [parkervcp/eggs#1809]
### Panel Version

1.10.1

### Wings Version

1.6.4

### Service

Avorion

### Modified

No, I did not modify the egg

### Expected Behavior

Certain mods to create new files in the moddata folder.

### Actual Behavior

Certain mods cannot read/write anywhere.

I have even tried on two different machines now and i have no idea what to do anymore. ive been asking around for a week or two at least, scouring google and trying a few different things. nothing has worked so far.

### Steps To Reproduce

Install Avorion with the Panel.
Create modconfig.lua
add mods that need to create configs to modconfig.lua
start server
get errors about mod being unable to read/write files

### Install logs

https://pteropaste.com/1ugcco

**Comment by gOOvER** [comment]
1. you use an old Egg
2. can you please Post the Error you get?

**Comment by RogueRaiden** [comment]
the main error is
Error finding home directory: getpwuid(getuid()) returned NULL
the error for AvorionAnnouncer is in here
https://pastebin.com/sPVaxZ2b

**Comment by RogueRaiden** [comment]
the new egg doesnt solve the issue

**Comment by gOOvER** [comment]
> the new egg doesnt solve the issue

i still need the complete Error message

**Comment by gOOvER** [comment]
more infos Here:

https://avorion.fandom.com/wiki/Using_Mods_on_Dedicated_Servers

**Comment by RogueRaiden** [comment]
the server will download and run mods just fine, its just if a mod needs to read/write files it throws errors. that wiki page provides no further info.

**Comment by Software-Noob** [comment]
It's trying to access something outside the container that doesn't exist. Chances are it's the users home directory and there's no such thing in the containers.

Quick Google search returns results of ability to modify the paths in the `settings.ini`.

**Comment by RogueRaiden** [comment]
there are no mod paths in the Avorion server.ini file to change. I can install an Avorion server with LinuxGSM and these mods can read/write config files with no issues. Just Pterodactyl instances refuse to allow them

**Comment by Software-Noob** [comment]
As stated above there's a big difference between isolated docker container running with bind mount and running on a machine itself with no isolation of any kind.
