### ISSUE TITLE
[Egg Request]: SteamCMD: DCS World

### ISSUE THREAD

**Issue by Hazerre** [parkervcp/eggs#1812]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/223750/DCS_World_Steam_Edition/

### Links for the download

https://store.steampowered.com/app/223750/DCS_World_Steam_Edition/

### Links for the install docs

https://www.digitalcombatsimulator.com/en/downloads/world/server/

**Comment by parkervcp** [comment]
You can try this egg for this game. https://github.com/parkervcp/eggs/tree/master/game_eggs/wine/generic

You will need to customize the start command and the script will fail if right now.

**Comment by gOOvER** [comment]
The Game dont work in Wine.

**Comment by Hazerre** [comment]
Is there a way to condense all of this down into an egg?

https://www.reddit.com/r/hoggit/comments/ns6g7j/comment/h0lrxz0/

**Comment by parkervcp** [comment]
> Is there a way to condense all of this down into an egg?

Could it be an egg, probably. It's probably going to be slow.

**Comment by gOOvER** [comment]
i tried it in past with some other guy. The Server will not start, because you need keyboard and mouse support. see xdotool. This will not really work in Ptero

**Comment by Aterfax** [comment]
Hi @parkervcp, as I think most of the annoying bits of getting this working are already sorted in https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker do you think it would be possible to get this as an Egg? 

I'm happy to maintain it (and tweak the upstream image), but I don't really know the process for making the Egg part from an existing Docker image.

**Comment by gOOvER** [comment]
> Hi @parkervcp, as I think most of the annoying bits of getting this working are already sorted in https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker do you think it would be possible to get this as an Egg?
> 
> I'm happy to maintain it (and tweak the upstream image), but I don't really know the process for making the Egg part from an existing Docker image.

nothing vhanged:

https://github.com/parkervcp/eggs/issues/1812#issuecomment-1221242810

**Comment by Aterfax** [comment]
Yes, things absolutely have changed. 

>i tried it in past with some other guy. The Server will not start, because you need keyboard and mouse support. see xdotool. This will not really work in Ptero

Please try the upstream Docker image I mentioned as it accounts for these issues. I would hardly be talking about the image I maintain here it if it didn't already work.

**Comment by gOOvER** [comment]
> Yes, things absolutely have changed.
> 
> > i tried it in past with some other guy. The Server will not start, because you need keyboard and mouse support. see xdotool. This will not really work in Ptero
> 
> Please try the upstream Docker image I mentioned as it accounts for these issues. I would hardly be talking about the image I maintain here it if it didn't already work.

you know, that ptero needs special images?

**Comment by Aterfax** [comment]
> I'm happy to maintain it (and tweak the upstream image)
