### ISSUE TITLE
[Bug]: hurtworld server console command not working

### ISSUE THREAD

**Issue by ProtoGhost** [parkervcp/eggs#1813]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

Server version is: 1.0.0.6

### Modified

No, I did not modify the egg

### Expected Behavior

when I'm giving cmd from panel console it's not working. I don't know why this problem is happening if you tell me or if you can fix it 

### Actual Behavior

when I'm giving cmd from panel console it's not working.
![image](https://user-images.githubusercontent.com/67905221/184473455-f46b1dde-4678-4f8d-bb7f-aff24ac43673.png)

### Steps To Reproduce

step 1 install hurtworld server 
step 2 install oxide event if you don't install oxide it's still happening 
step 3 run any command it will not work

### Install logs

i cant give you it in public cause here is my private dedi ip address im sorry i can dm you

**Comment by gOOvER** [comment]
this is no real console. It's not possible to send commands through console

**Comment by ProtoGhost** [comment]
@gOOvER then how i send command without opening the game?

Idk much about hurtworld in linux but its working in window

**Comment by gOOvER** [comment]
> 

idk the game. mb there is RCON or sth

**Comment by ProtoGhost** [comment]
Everyone knows that linux is not windows what a stupid answer

**Comment by gOOvER** [comment]
> Everyone knows that linux is not windows what a stupid answer

like yours, that it works on Windows ;) There is no rcon and you cant send commands to the server without joining.

**Comment by ProtoGhost** [comment]
Read the comments careful before answering  i told Idk much about hurtworld in linux but its working in window (as i said idk much about linux hurtworld)

**Comment by gOOvER** [comment]
> Read the comments careful before answering i told Idk much about hurtworld in linux but its working in window (as i said idk much about linux hurtworld)

i think, we should stop here now. its not possible to send commands through ptero console, because this is no real console. So it's not an egg issue

**Comment by ProtoGhost** [comment]
Okay

**Comment by parkervcp** [comment]
There is no rcon without oxide and I am not adding that if it's not absolutely required.
