### ISSUE TITLE
[Egg Request]: Obico Private Server

### ISSUE THREAD

**Issue by DigiVore-Programing** [parkervcp/eggs#1814]
### Does this expand an already existing service

No

### Link to a game or software

https://obico.io/

### Links for the download

https://github.com/TheSpaghettiDetective/obico-server

### Links for the install docs

https://github.com/TheSpaghettiDetective/obico-server

**Comment by gOOvER** [comment]
ptero is the wrong plattform for this.

**Comment by parkervcp** [comment]
You are better off just using docker compose to run this.
