### ISSUE TITLE
[Egg Request]: Python

### ISSUE THREAD

**Issue by Bobby99as** [parkervcp/eggs#1826]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.python.org/

### Links for the download

https://www.python.org/downloads/

### Links for the install docs

https://docs.python.org/3/using/index.html

**Comment by parkervcp** [comment]
there is already a generic python egg - https://github.com/parkervcp/eggs/tree/master/bots/discord/discord.py

I am working on moving it.

**Comment by Marijn-de-Mul** [comment]
Yeah, its gone for some reason. Can this be brought back? Thanks in advance!
