### ISSUE TITLE
[Bug]: starbound not installing mods

### ISSUE THREAD

**Issue by Wazbat** [parkervcp/eggs#1827]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

starbound

### Modified

No, I did not modify the egg

### Expected Behavior

If I enable the `WORKSHOP` setting, it should install and mount every subscribed mod so that the server loads them

### Actual Behavior

Some mods do not have a contents.pak file. Instead, the .pak file is named diferently. In one case, we observed the file name was the name of the mod. In another case, it was the actual workshop ID already. And in another, it was 2 files, `post.pak` and `contents.pak`, both being necessary for servers [as per the mods workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=764887546)

Here is the formated relevant code from the egg's [installation script](https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/starbound/egg-starbound.json#L27), right at the end
```bash
## use Worksop content
if [ "${WORKSHOP}" == "1" ]; then
    for dir in /mnt/server/steamapps/workshop/content/211820/*/
    do
     dir=${dir%*/}
     echo Sym-linking mod ${dir##*/} into the mods folder
     ln -r -s /mnt/server/steamapps/workshop/content/211820/${dir##*/}/contents.pak /mnt/server/mods/${dir##*/}.pak
    done
fi
```

As you can see there, it creates a symlink between each subscribed item's contents.pak file into the mods directory

This would normally work, however not every mod has a contents.pak file. A couple of workshop mods do not have just one single `contents.pak` file, sometimes having multiple, or a different name. The filename can be anything, though it is admittedly usually `contents.pak`

I have also seen some of these folders even including a `.DS_Store` file after being freshly subscribed to

### Steps To Reproduce

Create a starbound server
Install a mod like `764887546` which has 2 .pak files, `post.pak` and `contents.pak`, or `862287085` which has a wrongly named .pak file
The code does not copy over these files as it is written to only link `contents.pak` files

### Install logs

https://pteropaste.com/2uigw5/

**Comment by gOOvER** [comment]
> I might have a go at fixing this however my bash scripting is rather rusty

open pr with your fix. then we can help :)

**Comment by Wazbat** [comment]
> open pr with your fix. then we can help :)

I messed around with it a bit and I think it's working haha. Just testing it now. If it works, I'll export the egg and open a PR
