### ISSUE TITLE
Nameless Website

### ISSUE THREAD

**Issue by Gizmo0320** [parkervcp/eggs#1828]
### Does this expand an already existing service

No

### Link to a game or software

https://namelessmc.com/

### Links for the download

https://github.com/NamelessMC/Nameless/releases/tag/v2.0.2

### Links for the install docs

https://docs.namelessmc.com/en/installation

**Comment by gOOvER** [comment]
Ptero is the wrong solution for this.

**Comment by parkervcp** [comment]
I specifically don't build in webservers into the panel. It requires manually configuring reverse proxies as you cannot use normal http ports with pterodactyl.
