### ISSUE TITLE
[Egg Request]: RageCOOP

### ISSUE THREAD

**Issue by LegacyAngel2K9** [parkervcp/eggs#1832]
### Does this expand an already existing service

No

### Link to a game or software

https://ragecoop.online/

### Links for the download

https://github.com/RAGECOOP/RAGECOOP-V/

### Links for the install docs

https://github.com/RAGECOOP/RAGECOOP-V/wiki/Set-up-a-server

**Comment by LegacyAngel2K9** [comment]
since there is a version for Beta and for Nightly, can there be a variable for the option to choose what install you want also?

**Comment by QuintenQVD0** [comment]
@LegacyAngel2K9 Please test and leave a revieuw on the linked PR!

**Comment by LegacyAngel2K9** [comment]
Have tested, worked like a charm ^^
