### ISSUE TITLE
[Bug]: SA-MP /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by plugins/GPS.so)

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1833]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

game_eggs/gta/samp/egg-s-a--m-p.json

### Modified

No, I did not modify the egg

### Expected Behavior

No error for GLIBCXX

### Actual Behavior

/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by plugins/GPS.so)

### Steps To Reproduce

Install egg.
Upload plugin GPS.so add it to server.cfg
Start server

### Install logs

above

**Comment by BenasPaulikas** [comment]
I've tried running those commands in install script but no help. I guess they need to be added to image instead of install script ?

**Comment by QuintenQVD0** [comment]
It uses already the newest image.  So eather your egg is not up to date. Or your server still uses the old image

**Comment by Software-Noob** [comment]
Your egg or the used image is out of date.

The egg was updated in May to use new Yolks image repo, where images are rebuilt every Monday to contain the newest packages.

**Comment by BenasPaulikas** [comment]
I can confirm that it's good now. Not sure what step failed before.
@QuintenQVD0 @Software-Noob thank you for such fast replies :1st_place_medal:
