### ISSUE TITLE
[Egg Request]: Mongodb Update To Latest

### ISSUE THREAD

**Issue by TheGamer3514** [parkervcp/eggs#1837]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.mongodb.com/

### Links for the download

https://www.mongodb.com/try/download

### Links for the install docs

https://www.mongodb.com/docs/

**Comment by QuintenQVD0** [comment]
just make a quick PR, it is not that hard

**Comment by TheGamer3514** [comment]
> just make a quick PR, it is not that hard

i don't understand how to edit eggs, if i did i would have made a pr .

**Comment by QuintenQVD0** [comment]
> > just make a quick PR, it is not that hard
> 
> i don't understand how to edit eggs, if i did i would have made a pr .

give me like 30 min , I am testing something first then I will make the PR for you

**Comment by gOOvER** [comment]
added 6 as a PR too
