### ISSUE TITLE
FiveM egg gives error on boot.

### ISSUE THREAD

**Issue by SYGRayDobson** [parkervcp/eggs#184]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.13.
Daemon Version: 0.6.12
Service: FiveM.
Modified: No.

Expected Behavior: Should boot up with the start button.

Actual Behavior:
:/home/container$ /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path /home/container/alpine/usr/lib/v8/:/home/container/alpine/lib/:/home/container/alpine/usr/lib/ -- /home/container/alpine/opt/cfx-server/FXServer +set citizen_dir /home/container/alpine/opt/cfx-server/citizen/ +set sv_licenseKey dnenuonsv93bfyac47odwfmtp749xrs9 +set sv_maxplayers 32 +exec server.cfg
/entrypoint.sh: eval: line 1: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: Permission denied

Steps to Reproduce: (Step by step what to do to cause the issue)
Attempting to start the server.

**Comment by parkervcp** [comment]
You exposed your key FYI.

Also I just pulled my latest version of the fivem egg and imported to be sure.

https://gist.github.com/parkervcp/d6ef415b173b08fdce222d85d753b7f5

**Comment by SYGRayDobson** [comment]
I'll contact you on Discord.

Many thanks.

**Comment by SYGRayDobson** [comment]
Right, would you know how to fix it seeing as I'm using your latest egg & panel update?

**Comment by parkervcp** [comment]
What server OS are you on?

I have tested on my public panel with a daemon in a container and my internal Ubuntu 18.04 install (no docker) and they both start with no issue.
