### ISSUE TITLE
[Egg Request]: Rust Autowipe on Specific Time

### ISSUE THREAD

**Issue by Gogglehotmail** [parkervcp/eggs#1845]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/252490/Rust/

### Links for the download

https://store.steampowered.com/app/252490/Rust/

### Links for the install docs

https://store.steampowered.com/app/252490/Rust/

**Comment by Gogglehotmail** [comment]
Would be Awesome if there would be the Option to Wipe the Rust Server Automatically at a specific Time/Day Daily/Weekly/Monthly

**Comment by parkervcp** [comment]
You can't do this in the egg. You would need an external service with api access to do this.
