### ISSUE TITLE
[Bug]: Magma - Download link invalid

### ISSUE THREAD

**Issue by AIMBOT312** [parkervcp/eggs#1846]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

Minecraft Magma

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server

### Actual Behavior

Validating download link
Download URL "https://git.magmafoundation.org/api/v4/projects/8/packages/maven/org/magmafoundation/Magma/1.16.5-36.2.35-80d5f97a/Magma-1.16.5-36.2.35-80d5f97a-server.jar" is invalid. Terminating install.

### Steps To Reproduce

Set egg to Magma and install it

### Install logs

https://pteropaste.com/y3q8f0

**Comment by parkervcp** [comment]
That link is valid but this could be a networking or dns config issue and not an issue with the egg. I am checking this out now though to see if I can re-create it.

What settings did you have when you created the server?

**Comment by QuintenQVD0** [comment]
This should be fixt by https://github.com/parkervcp/eggs/pull/1882
