### ISSUE TITLE
PocketMine-MP Egg not installing bin

### ISSUE THREAD

**Issue by alexbgameson** [parkervcp/eggs#185]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 7.13
Daemon Version: 6.12
Service: minecraft
Modified: no

Expected Behavior:
Server installs with binary folder and boots normally.

Actual Behavior:
Server installs but binary is nowhere to be found. 

The server fails to boot because it is missing bin.

Steps to Reproduce: 
1. Install PocketMine-MP server
2. Attempt to run by hitting start button.

**Comment by alexbgameson** [comment]
It appears that the PMMP jenkins is offline.

**Comment by parkervcp** [comment]
Closing this as a "not an egg issue".

**Comment by alexbgameson** [comment]
This is an egg issue the egg has a link that doesnt work.

**Comment by parkervcp** [comment]
Their jenkins is down. I don't control that. I can't fix it.

**Comment by alexbgameson** [comment]
So it just gonna stay broken forever unless Jenkins comes back online.

**Comment by parkervcp** [comment]
And their Jenkins is back.
