### ISSUE TITLE
[Bug]: Black mesa egg doesn't start steamcmd not installed

### ISSUE THREAD

**Issue by shodanx2** [parkervcp/eggs#1856]
### Panel Version

9.99

### Wings Version

9.99

### Service

black mesa egg

### Modified

No, I did not modify the egg

### Expected Behavior

install server and click start
then join the game

### Actual Behavior

These errors on the console
/entrypoint.sh: line 16: ./steamcmd/steamcmd.sh: No such file or directory
/entrypoint.sh: line 25: ./srcds_run: No such file or directory

![image](https://user-images.githubusercontent.com/10621885/189283783-fb555cb2-becb-42a3-ac26-87ffcb24ba04.png)

### Steps To Reproduce

Install pterodactyl
go to nest, import black mesa egg
create server using black mesa egg
click start

### Install logs

As for the install logs There is no logs, this command records my csgo install, I checked, there's only a log for the minecraft test server and the csgo server. For some reason it didn't create a black mesa install log ?!

**Comment by gOOvER** [comment]
Post Install logs. your screen say nothing. also pls fill the correct ptero and Wings version

**Comment by shodanx2** [comment]
Hello,
I don't know what happenned but something went wrong with the install script.
I just erased the server and created a new one and it just worked !

I was going for a Black Mesa co-op server
I scp'd the files from the tutorial

https://mms.alliedmods.net/mmsdrop/1.11/mmsource-1.11.0-git1143-linux.tar.gz
https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6874-linux.tar.gz
https://github.com/ampreeT/SourceCoop/releases/latest

set mp_timelimit 0 in server.cfg (not sure that actually worked)
then changed the map in the startup command to mp_timelimit 

And that makes a kick ass co-op server 

I'm going to try and figure out how to turn this into an egg
