### ISSUE TITLE
[Egg Request]: MCHPRS

### ISSUE THREAD

**Issue by ReFruity** [parkervcp/eggs#1860]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/MCHPR/MCHPRS

### Links for the download

https://github.com/MCHPR/MCHPRS

### Links for the install docs

https://github.com/MCHPR/MCHPRS#building

**Comment by QuintenQVD0** [comment]
Parcker stated multiple times that he will not be adding more flavors of minecraft servers

**Comment by ReFruity** [comment]
> Parcker stated multiple times that he will not be adding more flavors of minecraft servers

Sorry, didn't know about it. Why is that?

**Comment by QuintenQVD0** [comment]
> > Parcker stated multiple times that he will not be adding more flavors of minecraft servers
> 
> Sorry, didn't know about it. Why is that?

I have no idea ask him

**Comment by ReFruity** [comment]
@parkervcp Why not? This one allows for blazing fast CPUs to be made

**Comment by parkervcp** [comment]
99 percent of the time they are projects that die in months. I stopped accepting them due to that alone.
