### ISSUE TITLE
[Bug]: Cannot connect to Satisfactory server

### ISSUE THREAD

**Issue by JustRed23** [parkervcp/eggs#1863]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Server install finishes, server starts, you connect

### Actual Behavior

Server install finishes, server starts, cannot connect

### Steps To Reproduce

Step 1: set version to experimental
Step 2: let the server install
Step 3: start the server and try to connect

For extra info: I tried connecting to the port 15777, i have three ports forwarded through the firewall and added to pterodactyl: 25601, 15000 and 15777
![image](https://user-images.githubusercontent.com/21986809/190861985-e52a078b-a6bb-4da0-ae68-e882260cfb7f.png)
Whenever I add the server it says Server name pending and i get no connection at all. But when i try to connect with the 25601 port my console gets spammed with "LogNet: NotifyAcceptingConnection accepted from: xx.xxx.xxx.125:49652" but nothing happens on the client. Firewall should be okay, ports 25601, 15777 and 15000 are forwarded through tcp/udp

### Install logs

https://pteropaste.com/auy0ft/

**Comment by JustRed23** [comment]
Idk if this helps but i also get this whenever the server starts.
![image](https://user-images.githubusercontent.com/21986809/190862142-4c4f0323-3f48-478f-aa47-05f6c5800514.png)

**Comment by parkervcp** [comment]
your query port should be the default port. As seen here I have a running satisfactory server that works.

![image](https://user-images.githubusercontent.com/1207679/190862182-eb5d5945-83e3-4fd8-b693-e3901101876a.png)

**Comment by JustRed23** [comment]
![image](https://user-images.githubusercontent.com/21986809/190862390-7efc5b99-615c-451a-89fd-1c56a1f527d2.png)
Set 15777 to default, nothing changed

**Comment by JustRed23** [comment]
Nvm figured it out, had my ingress rules set incorrectly on oracle cloud platform.

**Comment by TheBlackDrake** [comment]
Wait, I have the same issue.
But the strange part for me is.
If I run the same startupcommand stright from commandline (linux) the server starts and I could claim the server, and me and external friends could connect.

But If I start the server from webgui, the server starts, but shows as offline. Not able to join nor claim the server.

I have tried with default and alternate ports.
Fresh install.
Allways the same as in JustRed screenshot.
Server name Pending and appear to be offline.

Unless I run the same startup command in CLI directly on the server via SSH

**Comment by lilkingjr1** [comment]
@TheBlackDrake Unless you're running on the Oracle Cloud platform, I don't believe you have the same root issue as JustRed. Please ask in the Discord for help, or open your own Issue. Please include screenshots of your Network and Startup tabs.
