### ISSUE TITLE
[Egg Request]: Astrooner

### ISSUE THREAD

**Issue by GawrrVR** [parkervcp/eggs#1865]
### Does this expand an already existing service

No

### Link to a game or software

store.steampowered.com/app/361420/ASTRONEER/

### Links for the download

SteamCMD ( ASTRONEER Dedicated Server )

### Links for the install docs

blog.astroneer.space/p/astroneer-dedicated-server-details/

**Comment by silverfox0000** [comment]
duplicate #544
