### ISSUE TITLE
[Egg Request]: Grasscutter

### ISSUE THREAD

**Issue by mzrtamp** [parkervcp/eggs#1871]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/Grasscutters/Grasscutter

### Links for the download

https://github.com/Grasscutters/Grasscutter/suites/8437821714/artifacts/373896029

### Links for the install docs

https://github.com/Grasscutters/Grasscutter#quick-setup-guide

**Comment by mzrtamp** [comment]
I also need help with:
> Proxy Daemon: [mitmproxy](https://mitmproxy.org/) (mitmdump, recommended), [Fiddler Classic](https://telerik-fiddler.s3.amazonaws.com/fiddler/FiddlerSetup.exe), etc.
From this link https://github.com/Grasscutters/Grasscutter#requirements

**Comment by parkervcp** [comment]
Any of the java eggs will run this. You will need your own mitmproxy and mongodb.
