### ISSUE TITLE
[Bug]: Terraria tShock

### ISSUE THREAD

**Issue by hz-ad** [parkervcp/eggs#1872]
### Panel Version

1.10

### Wings Version

1.10

### Service

Terraria tShock

### Modified

No, I did not modify the egg

### Expected Behavior

Server should not experience an SSL handshake error

### Actual Behavior

After a tshock server has started:

UpdateManager warning: An error occurred while sending the request
        -> Error: TrustFailure (Authentication failed, see inner exception.)
        -> Authentication failed, see inner exception.
        -> Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.20.1.19/external/boringssl/ssl/handshake_client.c:1132
Retrying in 5 minutes.

More than likely this is due to mono not having certain root certs. Does there need to be an update to the mono yolk, or maybe its something else?

### Steps To Reproduce

Install Terraria Tshock

Let the server load and start
Wait for some time and the update manager will fail with a handshake error

### Install logs

The server installs normally.

**Comment by parkervcp** [comment]
Can you post the console output please. The error alone is not really helpful in this case.

**Comment by hz-ad** [comment]
Saving world data: 9%
Saving world data: 15%
Saving world data: 24%
Saving world data: 30%
Saving world data: 39%
Saving world data: 46%
Saving world data: 54%
Saving world data: 60%
Saving world data: 68%
Saving world data: 74%
Saving world data: 83%
Saving world data: 89%
Saving world data: 97%
Saving world data: 100%
Validating world save: 70%
World saved.
Backing up world file
UpdateManager warning: An error occurred while sending the request
        -> Error: TrustFailure (Authentication failed, see inner exception.)
        -> Authentication failed, see inner exception.
        -> Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.20.1.19/external/boringssl/ssl/handshake_client.c:1132
Retrying in 5 minutes.
UpdateManager warning: An error occurred while sending the request
        -> Error: TrustFailure (Authentication failed, see inner exception.)
        -> Authentication failed, see inner exception.
        -> Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.20.1.19/external/boringssl/ssl/handshake_client.c:1132
Retrying in 5 minutes.
UpdateManager warning: An error occurred while sending the request
        -> Error: TrustFailure (Authentication failed, see inner exception.)
        -> Authentication failed, see inner exception.
        -> Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.20.1.19/external/boringssl/ssl/handshake_client.c:1132
Retrying in 5 minutes.
UpdateManager warning: An error occurred while sending the request
        -> Error: TrustFailure (Authentication failed, see inner exception.)
        -> Authentication failed, see inner exception.
        -> Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.20.1.19/external/boringssl/ssl/handshake_client.c:1132
Retrying in 5 minutes.
UpdateManager warning: An error occurred while sending the request
        -> Error: TrustFailure (Authentication failed, see inner exception.)
        -> Authentication failed, see inner exception.
        -> Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /home/buildozer/aports/testing/mono/src/mono-5.20.1.19/external/boringssl/ssl/handshake_client.c:1132
Retrying in 5 minutes.

**Comment by eloiselle** [comment]
Have you tried updating again? Maybe 5 days later, if the error message is to be believed and the problem really is about an SSL certificate, it has been reissued or taken care of?
