### ISSUE TITLE
[Bug]: SinusBot Youtube-DL

### ISSUE THREAD

**Issue by ImFound** [parkervcp/eggs#1873]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

SinusBot

### Modified

No, I did not modify the egg

### Expected Behavior

youtube-dl working

### Actual Behavior

SinusBot says "youtube-dl not available"

### Steps To Reproduce

Step 1 Install the egg
Step 2 Create the server
Step 3 Try to download something from youtube from the sinusbot panel

### Install logs

.

**Comment by parkervcp** [comment]
Please get install logs @ImFound

**Comment by gOOvER** [comment]
Sinusbot is more or lesser dead and recived since over 2 yeaes no more updates

**Comment by parkervcp** [comment]
That install log shows youtube dl being downloaded.

**Comment by ImFound** [comment]
![immagine](https://user-images.githubusercontent.com/76497130/192878302-b70ca454-c9da-4d17-a72a-3397c038e9c0.png)
okay, but, sinusbot says this.

**Comment by gOOvER** [comment]
> ![immagine](https://user-images.githubusercontent.com/76497130/192878302-b70ca454-c9da-4d17-a72a-3397c038e9c0.png)
> okay, but, sinusbot says this.

See my Post above.

**Comment by ImFound** [comment]
> > ![immagine](https://user-images.githubusercontent.com/76497130/192878302-b70ca454-c9da-4d17-a72a-3397c038e9c0.png)
> > okay, but, sinusbot says this.
> 
> See my Post above. 

It doesn't really matter that it's not up to date.. If I manually install it on a separate VM everything works without any problems.

**Comment by gOOvER** [comment]
youtubedl must be in the Image, not in the installscript

**Comment by Panda260** [comment]
When will the SinusBot image be updated? because there is a new version out there
https://www.sinusbot.com/pre/sinusbot-1.0.1-amd64.tar.bz2

**Comment by parkervcp** [comment]
> there is a new version out there

We install the current release and not the pre-release versions.

**Comment by ImFound** [comment]
now it works, i love you <3

**Comment by gOOvER** [comment]
> > there is a new version out there
> 
> We install the current release and not the pre-release versions.

problem is, they only release PRE Versions. The official Version is old as hell

**Comment by gOOvER** [comment]
> [pteropaste.com/whi1me](https://pteropaste.com/whi1me/)

please test it with the new image. I'll added youtube-dl to the image

**Comment by QuintenQVD0** [comment]
Parker asked me to remove it as it is not needed as it is download by the install script:
![afbeelding](https://user-images.githubusercontent.com/67589015/193408279-254f16ba-bd85-4f61-a3c2-ac63d8314825.png)
The new image before groover pr:
![afbeelding](https://user-images.githubusercontent.com/67589015/193408307-65ffe009-9c56-4b29-8f1d-dccb9f811e62.png)

If it only now works with the new latest PR image then the new PR to remove it back will be closed
![afbeelding](https://user-images.githubusercontent.com/67589015/193408364-1bb7b935-0e7e-4ec0-8bfe-8c2f42abb9c7.png)
