### ISSUE TITLE
[Egg Request]: Discord-MusicBot

### ISSUE THREAD

**Issue by szentigrad3** [parkervcp/eggs#1875]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5

### Links for the download

https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5

### Links for the install docs

https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5

**Comment by parkervcp** [comment]
The generic nodejs egg will likely do this.

https://github.com/parkervcp/eggs/tree/master/generic/nodejs
