### ISSUE TITLE
[Install Bug]: <egg-v-rising.json>

### ISSUE THREAD

**Issue by thephatcrew** [parkervcp/eggs#1878]
### Panel Version

1.3.1

### Wings Version

1.3.1

### Service

game_eggs\steamcmd_servers\v_rising\

### Modified

No, I did not modify the egg

### Expected Behavior

For the import to install

### Actual Behavior

The JSON file provided is not in a format that can be recognized.

### Steps To Reproduce

Try to import V rising egg

### Install logs

tried running command said permission denied and canty access

**Comment by danny6167** [comment]
The egg imports just fine. Your issue is you're running an completely outdated and obsolete version of the panel.
1.3.1 was released in Mar 08, 2021

**Comment by thephatcrew** [comment]
> The egg imports just fine. Your issue is you're running an completely outdated and obsolete version of the panel. 1.3.1 was released in Mar 08, 2021

What version are you running?

**Comment by lilkingjr1** [comment]
@thephatcrew, the answer @danny6167 gave is the correct one. The eggs provided in this repo are only guaranteed to work on the latest version of the panel. The panel is backwards compatible and not all eggs in this repo are fully up to date with Egg Version 2. Therefore, some eggs may still work on your older panel version. You can verify your issue by trying to import another V2 egg, like Satisfactory (confirmed working), and you will get the same error on your panel.
