### ISSUE TITLE
Request for possibility to select the forge version to install

### ISSUE THREAD

**Issue by Fireztonez** [parkervcp/eggs#188]
Service: Minecraft

Does this expand an already existing service: Yes

Link to game: https://files.minecraftforge.net/

Description of What I want:
Basically, i'm a modpack developper, and I want to be able to test my modpack on a server. And, like you possibly already know, using the latest version of forge is not always good or can just doesn't work at all with some mods... So, question of be able to test, sometime I have to install an older version of forge or sometime I have to try with a version and with another one... Now, I have to download manually the forge version I want to transfer by SFTP, it take me about 5 to 8 min just question to install a specific version of forge. So if I have to change multiple time in a row, question of testing, this is just a waste of time.

The code is already made question to downlaod forge automatically, but now it always download the latest version, how is not good for most modpacks. Can you add possibility to type the version of forge we want to download directly and at the same time having a possibility to enter a link to a custom version of forge will be great (Sometime, this is possible we have to test with a dev version of forge, who is not already available to the public).

I know the egg of Paper already possibility to type the jar link file at the creation of server. So Something like that should be nice, with Forge Version variable and Custom Link variable. And for sure, the user should be able to change the version of Forge if needed...

If you have a question or something, let me know!
Thank's for your work
Fireztonez

**Comment by NgLoader** [comment]
Your able to select a version https://github.com/parkervcp/eggs/pull/156

**Comment by NgLoader** [comment]
But I commit a change where you can select a custom link :)

**Comment by parkervcp** [comment]
This egg - https://github.com/parkervcp/eggs/tree/master/minecraft_java/forge/forge-generic

You just pass it a curse forge pack url and it will pull and install the pack.

**Comment by Fireztonez** [comment]
The forge-generic is good for public modpack available on Curse Forge, but this doesn't help me on my case. But I'm really interest to see the new commit for the Forge-Enhence... Because Like I say, i'm a modpack developper and I have to test my modpack on my server befaure I even think about updload to curseforge. And this egg doesn't allow to change the forge version, so, again, this is absolutly not what I looking for.

But I'm really interest to see  your commit @NgLoader if you have a link or something to the code of the egg, I will be able to test and see if it work!

**Comment by NgLoader** [comment]
@Fireztonez Use https://github.com/parkervcp/eggs/pull/156/files

**Comment by NgLoader** [comment]
Use https://github.com/NgLoader/pterodactyl-eggs/tree/minecraft/forge-enhanced/minecraft_java/forge/forge-enhanced

**Comment by NgLoader** [comment]
@Fireztonez Use [Forge Enhanced](https://github.com/NgLoader/pterodactyl-eggs/tree/minecraft/forge-enhanced/minecraft_java/forge/forge-enhanced)

**Comment by Fireztonez** [comment]
@NgLoader ok, you commit that in February!! But, I just look the code, there have no place yet where to place the custom link, so I imagine you will work on that and commit when it's done?

thank's for that, really appreciated!!

**Comment by Fireztonez** [comment]
@NgLoader Your Egg work great for the installation, but, there have a way to force the re-execution of the script, if I change the forge version??

Now, I install the server with the version 1.12.2-14.23.5.2831 and I try to change for the 1.12.2-14.23.5.2828 and when I start back the server, the forge version loaded is still the 1.12.2-14.23.5.2831, so look like the download script is re-execute after the change...

**Comment by NgLoader** [comment]
@Fireztonez I commit the changes at sunday.
Sry for that but its my birtsday today :)

**Comment by Fireztonez** [comment]
Happy Birthday @NgLoader, take your time, this is not really urgent, I don't want to bother you with that!! Have good day!!

**Comment by parkervcp** [comment]
To make it download a different version the current setup is to run a re-install.

This will not delete your server files but just download the server jar again.

**Comment by Fireztonez** [comment]
Ok, thank's
The notes from pterodactyl confused me a bit I think on the re-install button. Thanks for information!
