### ISSUE TITLE
[Egg Request]: SinusBot UPDATE!

### ISSUE THREAD

**Issue by Panda260** [parkervcp/eggs#1884]
### Does this expand an already existing service

Yes

### Link to a game or software

www.sinusbot.com

### Links for the download

https://www.sinusbot.com/pre/sinusbot-1.0.1-amd64.tar.bz2

### Links for the install docs

https://sinusbot.github.io/docs/installation/linux/

**Comment by parkervcp** [comment]
There is already a sinusbot egg.

**Comment by Panda260** [comment]
Yes I know that's why I wrote update above my question is when this will be updated because there is a new version of the bot as they have fixed a slightly major bug

**Comment by RT18818** [comment]
Please update the egg

**Comment by parkervcp** [comment]
Then this would be a bug in which #1873 already exists.
