### ISSUE TITLE
[Bug]: Craftopia egg fail

### ISSUE THREAD

**Issue by wompmacho** [parkervcp/eggs#1887]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

craftopia

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, run, connect via IP. Play game. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/56491202/193368240-701a226c-e97b-42d6-9785-a8d0d156dd29.png)

Cannot make a connection to server. Running a Minecraft node on same server - can connect just fine, ports open. 

### Steps To Reproduce

Step 1: Save raw json file - [egg-craftopia.json](https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/craftopia/egg-craftopia.json)
Step 2: Rename to egg-craftopia.json
Step 3: Create new nest - named Craftopia
Step 4: Import egg-craftopia.json to new Craftopia nest and save egg
Step 5: create new server with name Craftopia, assign user and default port
Step 6: set memory and disk space to 0
Step 7: set nest and egg configuration to craftopia
Step 8: click create server button - wait for install
step 9: after server marked as running - connect to server via address and port on server console page in game
step 10: profit

### Install logs

https://pteropaste.com/elokms

**Comment by gOOvER** [comment]
Check your Port settings, when you get a TIMEOUT Error

**Comment by wompmacho** [comment]
> Check your Port settings, when you get a TIMEOUT Error

Port is what it should be.

**Comment by parkervcp** [comment]
this is not an install bug but an egg start / config issue most likely.

**Comment by gOOvER** [comment]
Looks like, someone broke the ini parser also an ptero update. Switched to file parsing, although it has worked in the past with ini parser. Pls test this egg.

[](https://github.com/gOOvER/goover-eggs/blob/main/Craftopia/egg-craftopia.json)

**Comment by wompmacho** [comment]
> https://github.com/gOOvER/goover-eggs/blob/main/Craftopia/egg-craftopia.json

![image](https://user-images.githubusercontent.com/56491202/193430813-d8ab5441-4910-4e65-995f-18b6078d8b67.png)

**Comment by QuintenQVD0** [comment]
> Looks like, someone broke the ini parser also in a ptero update. Switched to file parsing, although it has worked in the past with ini parser. Pls test this egg. if it works for you, ill push the fix to repo
> 
> https://github.com/gOOvER/goover-eggs/blob/main/Craftopia/egg-craftopia.json

That repo is private ... so eather share the egg here in text format or make a PR with the changes so we can test it that way

**Comment by gOOvER** [comment]
> > Looks like, someone broke the ini parser also in a ptero update. Switched to file parsing, although it has worked in the past with ini parser. Pls test this egg. if it works for you, ill push the fix to repo
> > [gOOvER/goover-eggs@`main`/Craftopia/egg-craftopia.json](https://github.com/gOOvER/goover-eggs/blob/main/Craftopia/egg-craftopia.json?rgh-link-date=2022-10-02T08%3A13%3A47Z)
> 
> That repo is private ... so eather share the egg here in text format or make a PR with the changes so we can test it that way

now its public ;)

**Comment by gOOvER** [comment]
> > [gOOvER/goover-eggs@`main`/Craftopia/egg-craftopia.json](https://github.com/gOOvER/goover-eggs/blob/main/Craftopia/egg-craftopia.json?rgh-link-date=2022-10-01T22%3A39%3A51Z)
> 
> ![image](https://user-images.githubusercontent.com/56491202/193430813-d8ab5441-4910-4e65-995f-18b6078d8b67.png)

works now

**Comment by wompmacho** [comment]
> > > [gOOvER/goover-eggs@`main`/Craftopia/egg-craftopia.json](https://github.com/gOOvER/goover-eggs/blob/main/Craftopia/egg-craftopia.json?rgh-link-date=2022-10-01T22%3A39%3A51Z)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56491202/193430813-d8ab5441-4910-4e65-995f-18b6078d8b67.png)
> 
> works now. idk, why it was private :)

Tried this egg, did **not** work. 

Fiddled around a bit. Seems that your startup config is not correctly updating the ServerSetting.ini file. Default port and server name does not get updated with the startup variables - "world/server name" and "allocated server port"

![image](https://user-images.githubusercontent.com/56491202/193707210-66f3cf08-6f16-4d48-adf1-1389ff1c8b4e.png)


Can directly edit the file ServerSetting.ini after install and works fine. 

Just need to update startup/config files so that this gets updated correctly.

**Comment by wompmacho** [comment]
here you go - problem solved

Configuration Files -->
{
    "ServerSetting.ini": {
        "parser": "ini",
        "find": {
            "GameWorld.name": "{{server.build.env.WORLD_NAME}}",
            "Host.port": "{{server.build.default.port}}"
        }
    }
}

**Comment by QuintenQVD0** [comment]
This should be fixt with #1894
