### ISSUE TITLE
[Egg Request]: Discord-MusicBot

### ISSUE THREAD

**Issue by felipe-negri** [parkervcp/eggs#1892]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/SudhanPlayz/Discord-MusicBot

### Links for the download

https://github.com/SudhanPlayz/Discord-MusicBot

### Links for the install docs

https://github.com/SudhanPlayz/Discord-MusicBot/wiki/Installation-on-a-Linux-server

**Comment by parkervcp** [comment]
Fairly likely that the nodejs generic egg could run this - https://github.com/parkervcp/eggs/tree/master/generic/nodejs

**Comment by yesBad** [comment]
You can easily run it with NodeJS.

**Comment by QuintenQVD0** [comment]
Duplicate #1875

But then difrend brach. Bot run fine with the generic nodejs egv

**Comment by felipe-negri** [comment]
works perfect, but the status of the cointainer is always starting
<img width="224" alt="image" src="https://user-images.githubusercontent.com/27769172/193640599-d6286dca-140c-4e0b-bac5-76bd264cdb6e.png">

**Comment by yesBad** [comment]
> works perfect, but the status of the cointainer is always starting
> <img width="224" alt="image" src="https://user-images.githubusercontent.com/27769172/193640599-d6286dca-140c-4e0b-bac5-76bd264cdb6e.png">
> 

read eggs readme.

**Comment by felipe-negri** [comment]
thanks for the help
