### ISSUE TITLE
[Egg Request]: <Solace Crafting>

### ISSUE THREAD

**Issue by BrickBotTM** [parkervcp/eggs#1893]
### Does this expand an already existing service

No

### Link to a game or software

https://solacecrafting.com

### Links for the download

https://store.steampowered.com/app/670260/Solace_Crafting/

### Links for the install docs

https://solace-crafting.fandom.com/wiki/Multiplayer_Hosting_Guide

**Comment by lilkingjr1** [comment]
Is there a dedicated server binary for this app? From what I can tell from the install docs you linked, there is not a dedicated server, and hosting a server can currently only be done by using the GUI of a client copy of the game (which would not be possible on Pterodactyl given its automated nature of starting servers). Please close this issue if so, as a dedicated server will have to be available to make an Egg for this game.

**Comment by BrickBotTM** [comment]
https://steamdb.info/app/670260/depots/?branch=dedicatedserver

**Comment by gOOvER** [comment]
i have allready an egg for it. i will push it

**Comment by gOOvER** [comment]
please test this:

https://github.com/parkervcp/eggs/pull/1927

**Comment by BrickBotTM** [comment]
I have tested it and for now it is working fine.

**Comment by gOOvER** [comment]
> I have tested it and for now it is working fine.

can you leave a review in the PR of the egg pls?

**Comment by BrickBotTM** [comment]
Did a bit of research and suggested some edits that you should make

**Comment by gOOvER** [comment]
> Did a bit of research and suggested some edits that you should make

and where you suggest? I will not a a config parsing, because config file change with every update, so its useless to add paring

**Comment by BrickBotTM** [comment]
In the review, but I will post it here too.

The app id should be 1086950 so it can be logging in as anonymous for install. 1086950 is for the normal dedicated server. That way you don't need someone who owns the game to install the server. So you don't need the variables.
