### ISSUE TITLE
when you close your laptop for 30 mins

### ISSUE THREAD

**Issue by Coolionas** [parkervcp/eggs#1896]
### Panel Version

idk

### Wings Version

idk

### Service

brick-hill.com/forum

### Modified

No, I did not modify the egg

### Expected Behavior

So when you are on forum post and close your laptop (for around 30 minutes) then reopen it and refresh the page it keeps refreshing and not letting you go to the forum post.

### Actual Behavior

it keeps refreshing

### Steps To Reproduce

close your laptop for 30 mi ns

### Install logs

idkwhatsgoingon.com/idk

**Comment by QuintenQVD0** [comment]
that brick-hill.com/forum of you is not a offical egg and if you do not fill in this template correctly this wil be closed.
