### ISSUE TITLE
[Egg Request]: PHP language container

### ISSUE THREAD

**Issue by ax3lt** [parkervcp/eggs#1900]
### Does this expand an already existing service

No

### Link to a game or software

https://www.php.net/downloads.php

### Links for the download

https://www.php.net/distributions/php-8.1.11.tar.gz

### Links for the install docs

https://www.php.net/manual/en/install.php

**Comment by QuintenQVD0** [comment]
You mean like under the generic egg with composer installed? And for something else then web hosting?

**Comment by ax3lt** [comment]
I was thinking just about web hosting

**Comment by yesBad** [comment]
No

**Comment by QuintenQVD0** [comment]
Ptero is not made for web hosting , there are better panels for that. There will be no webhosting eggs be pushed to this repo.
