### ISSUE TITLE
[Egg Request]: <Valheim/ARM>

### ISSUE THREAD

**Issue by domrockt** [parkervcp/eggs#1902]
### Does this expand an already existing service

Yes

### Link to a game or software

Valheim.com

### Links for the download

cd /home/pi/steamcmd ----> ./steamcmd.sh +@sSteamCmdForcePlatformType linux +login anonymous +force_install_dir /home/pi/valheim_server +app_update 896660 validate +quit

### Links for the install docs

https://pimylifeup.com/raspberry-pi-valheim-server/

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> 
> Yes
> ### Link to a game or software
> 
> Valheim.com
> ### Links for the download
> 
> cd /home/pi/steamcmd ----> ./steamcmd.sh +@sSteamCmdForcePlatformType linux +login anonymous +force_install_dir /home/pi/valheim_server +app_update 896660 validate +quit
> ### Links for the install docs
> 
> https://pimylifeup.com/raspberry-pi-valheim-server/

This needs a lot of emulation, I will try it but the image is janck , Currently does not even work and because of that likly wont get merged but if  I get it for some reason running then I share it with you

**Comment by QuintenQVD0** [comment]
Yea this will not work in pterodactyl due to the really have emulation needed an oracle stupid kernel that does not auto start the emulation

**Comment by QuintenQVD0** [comment]
@domrockt I have it running , it is posted in my repo but note the steamcmd warning in the readme
