### ISSUE TITLE
[Bug]: Golang generic does not follow generics startup

### ISSUE THREAD

**Issue by devnote-dev** [parkervcp/eggs#1903]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

Golang Generic

### Modified

No, I did not modify the egg

### Expected Behavior

(I'm aware this isn't technically a bug but it doesn't fit into the other issue categories)

The egg should get the dependencies and run the source on startup. This would also be in line with the other generic eggs which all run the source code from the startup command rather than relying on the server install process.

### Actual Behavior

The egg only gets the dependencies and compiles in server install process.

### Steps To Reproduce

1. Upload your Go project source files
2. Start the server (will not run)

or alternatively:
1. Upload your Go project source files
2. Reinstall the server
3. Start the server (works)
4. Change something in the source code
5. Restart the server (code does not recompile, changes are not reflected)

### Install logs

N/A

**Comment by devnote-dev** [comment]
I'm holding off on PRing a fix as I would like to know whether this should be a change to the existing egg, or added as a separate egg also under the Golang generics section, as some people are fine with the current egg's process.

**Comment by parkervcp** [comment]
What is the difference with generics that the current egg is missing.

I am not using `go run` to start applications on the fly like the other languages as go is more of a compiled language versus a parsed language like python, nodejs, lua, etc.

**Comment by devnote-dev** [comment]
@parkervcp The issue is that changes made to the source code aren't reflected because it isn't recompiled at startup, and having to reinstall the server just to do this is tedious. It doesn't necessarily have to use `go run`, but `go get; go build; ./${EXECUTABLE}` should be fine.

**Comment by parkervcp** [comment]
Any packaged needed for the go build would need to be included in the image so it can build I don't know how this would work out.

**Comment by devnote-dev** [comment]
Not sure I follow - why does it need to be part of the image?

**Comment by devnote-dev** [comment]
What if you changed `GOMODCACHE` to be inside `/mnt/server` (`/home/container/.cache` for example), as opposed to being in a directory outside the container?

**Comment by parkervcp** [comment]
That's not the issue though. You still need those required package to compile as well. I am unsure if they are needed to run any applications.

The generic eggs are more of a template for others so far as I am concerned.

**Comment by devnote-dev** [comment]
Closing as there isn't a way to do this efficiently.
