### ISSUE TITLE
[Egg Request]: Jellyfin Media Server

### ISSUE THREAD

**Issue by danbracey** [parkervcp/eggs#1904]
### Does this expand an already existing service

No

### Link to a game or software

https://jellyfin.org/

### Links for the download

https://jellyfin.org/downloads/

### Links for the install docs

https://jellyfin.org/docs/

**Comment by parkervcp** [comment]
As with the request to add plex (#1117) there is no reason to run this in pterodactyl. Most likely it would mean taking their image apart to build one for pterodactyl.
