### ISSUE TITLE
[Egg Request]: Kotlin Language Host

### ISSUE THREAD

**Issue by louanfontenele** [parkervcp/eggs#1905]
### Does this expand an already existing service

No

### Link to a game or software

https://kotlinlang.org/

### Links for the download

https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS43LjEwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS5cbiAqIHBsYXkua290bGlubGFuZy5vcmdcbiAqL1xuZnVuIG1haW4oKSB7XG4gICAgcHJpbnRsbihcIkhlbGxvLCB3b3JsZCEhIVwiKVxufSJ9

### Links for the install docs

https://kotlinlang.org/docs/home.html

**Comment by Goksi** [comment]
Can't you just use standard java egg ?

**Comment by louanfontenele** [comment]
> Can't you just use standard java egg ? As stdlib is usually shaded inside of jar, there shouldn't be any difference
> 
> Edit: I just confirmed, it works with [generic java egg](https://github.com/parkervcp/eggs/tree/master/generic/java)

how can i deploy?

**Comment by Goksi** [comment]
> > Can't you just use standard java egg ? As stdlib is usually shaded inside of jar, there shouldn't be any difference
> > Edit: I just confirmed, it works with [generic java egg](https://github.com/parkervcp/eggs/tree/master/generic/java)
> 
> how can i deploy?

You lookup, how to import an egg [here](https://github.com/parkervcp/eggs#how-to-import-an-egg), and use [generic java](https://github.com/parkervcp/eggs/tree/master/generic/java) one

**Comment by QuintenQVD0** [comment]
I will close this as you can use the generic java egg
