### ISSUE TITLE
[Bug]: Valheim Plus

### ISSUE THREAD

**Issue by skynett81** [parkervcp/eggs#1913]
### Panel Version

latest

### Wings Version

latest

### Service

Valheim Plus Mod

### Modified

No, I did not modify the egg

### Expected Behavior

That the server boots / Starts

### Actual Behavior

the servers wont start correctly  and needs update to follow the latest Valheim Updates

### Steps To Reproduce

restart the server

### Install logs

https://pteropaste.com/qfawp1/

**Comment by parkervcp** [comment]
When you filled out the information here we specifically say that "latest" is not a version...

**Comment by parkervcp** [comment]
#1907 Already exists to update the valheim plus egg.
