### ISSUE TITLE
[Egg Request]: Node.js add v18

### ISSUE THREAD

**Issue by TheGamer3514** [parkervcp/eggs#1917]
### Does this expand an already existing service

Yes

### Link to a game or software

https://nodejs.org/

### Links for the download

https://nodejs.org/en/download/

### Links for the install docs

https://nodejs.org/en/docs/

**Comment by TheGamer3514** [comment]
also if possible fix the git pull

**Comment by gOOvER** [comment]
Looks like, you are not able to read and search in yolks repo:

`ghcr.io/parkervcp/yolks:nodejs_18`

Whats the "Git pull"? and what should be fixed?

**Comment by gOOvER** [comment]
git pull works fine
