### ISSUE TITLE
[Bug]: Stormworks

### ISSUE THREAD

**Issue by gsilk45** [parkervcp/eggs#1919]
### Panel Version

1.10.3

### Wings Version

1.7.2

### Service

Stormworks

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, update config, start server

### Actual Behavior

installed server, server_config.xml was not created, server crashes on startup, created server_config.xml file, server still crashes.

[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:70be6ff0bb7c260c1b4c5da7b4fd3ae13c2a237743ec2aa513d5567ed086cad8 
Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 11.5
Current timezone: Etc/UTC
wine-7.0
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1665183746
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '1247090' already up to date.
First launch will throw some errors. Ignore them
:/home/container$ xvfb-run wine server64.exe +server_dir /home/container
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
wine: could not load kernel32.dll, status c0000135
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 53
[Pterodactyl Daemon]: Out of memory: false

### Steps To Reproduce

Install Server
Start Server

### Install logs

command did not work

**Comment by parkervcp** [comment]
can you run `uname -a` please

**Comment by gsilk45** [comment]
> 

Linux Tower 5.19.14-Unraid #1 SMP PREEMPT_DYNAMIC Thu Oct 6 09:15:00 PDT 2022 x86_64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz GenuineIntel GNU/Linux

**Comment by gsilk45** [comment]
I deleted the server and re-installed it and now its giving different errors. I'm not sure what I am doing wrong.

[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest 
Digest: sha256:c6bdcab00e5474f9a293569a838e921f268fe6eb402e6ea3e9f8c6aa776f10b9 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 11.5
Current timezone: Etc/UTC
wine-7.0
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1665183746
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1247090' already up to date.
First launch will throw some errors. Ignore them
:/home/container$ xvfb-run wine server64.exe +server_dir /home/container
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
00e0:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000268FE10
00e4:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00000000027AFE10
00dc:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
X connection to :99 broken (explicit kill or server shutdown).
X connection to :99 broken (explicit kill or server shutdown).
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 5
[Pterodactyl Daemon]: Out of memory: false

**Comment by gOOvER** [comment]
i  think the Problem here is unraid. i will Take a Look into it later

**Comment by gsilk45** [comment]
I'm not sure if it makes any difference but I was able to get a vanilla minecraft server running with no issues

**Comment by QuintenQVD0** [comment]
> I'm not sure if it makes any difference but I was able to get a vanilla minecraft server and a rust server running with no issues

This is related to thr kernel and java does not realy care about that.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0: MB you can merge Wine Staging in parkers repo

I can't as it is my PR so even if someone else aproves it I can not merge it.

**Comment by QuintenQVD0** [comment]
I got it to run with the stable wine image:
![afbeelding](https://user-images.githubusercontent.com/67589015/196208101-21515f74-7cbd-4183-a0f4-d18287ecbcf3.png)
The ports are not right but it does start

**Comment by gOOvER** [comment]
> I got it to run with the stable wine image: ![afbeelding](https://user-images.githubusercontent.com/67589015/196208101-21515f74-7cbd-4183-a0f4-d18287ecbcf3.png) The ports are not right but it does start

Ports must be set by hand, becasue the parser dont work correct

**Comment by gOOvER** [comment]
> I deleted the server and re-installed it and now its giving different errors. I'm not sure what I am doing wrong.
> 
> [Pterodactyl Daemon]: Finished pulling Docker container image Running on Debian 11.5 Current timezone: Etc/UTC wine-7.0 steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1665183746 -- type 'quit' to exit -- Loading Steam API...OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK Success! App '1247090' already up to date. First launch will throw some errors. Ignore them :/home/container$ xvfb-run wine server64.exe +server_dir /home/container _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. _XSERVTransmkdir: ERROR: Cannot create /tmp/.X11-unix _XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 17 _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix 00e4:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000268FE10 00e8:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00000000027AFE10 00e0:fixme:dbghelp_dwarf:dwarf2_read_range no entry found X connection to :99 broken (explicit kill or server shutdown). X connection to :99 broken (explicit kill or server shutdown). container@pterodactyl~ Server marked as offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 5 [Pterodactyl Daemon]: Out of memory: false

This is definitely a problem with Unraid. Unraid is not really supported by Petrodactyl. Use a normal kernel, then it should work.

I think here can be closed

**Comment by QuintenQVD0** [comment]
Yea this is a issue with unraid kernel.
