### ISSUE TITLE
StoneServer Egg Request

### ISSUE THREAD

**Issue by Dmitri233** [parkervcp/eggs#192]
Service: Minecraft bedrock

Does this expand an already existing service: Y(I don't understand this）

Link to game: minecraft.net

Links for server downloads: https://github.com/codehz/StoneServer

Links for install steps/docs:1. Download the code from https://github.com/codehz/StoneServer
2. Install docker and docker-compose
3. Extract the "lib" and "assets" folders from the Minecraft bedrock x86 version of the installation package (or use this script https://gist.github.com/codehz/3fd825b822369d23e3a2a8a46a4638a7/
After selecting Download Game, the "lib" and "assets" folders will be downloaded automatically.）
4. Run the server with `docker-compose up`

**Comment by HuanzuoSP** [comment]
I agree this issues, because the StoneServer can use to scripting!

**Comment by parkervcp** [comment]
So really this should be labeled "StoneServer Egg Request"

**Comment by Dmitri233** [comment]
The stone server also needs a Redis service to support it. This can be very troublesome

**Comment by parkervcp** [comment]
I am not building in a redis service for this.

You can build a custom service for this then as it would need a custom image for everything. 

Also your install instructions are basically useless to me.

**Comment by Dmitri233** [comment]
Ok, thanks. You can refer to docker-compose.yml

**Comment by parkervcp** [comment]
Even worse is just saying "refer to the docker-compose". I can't use that as a base for anything.

**Comment by Dmitri233** [comment]
Have you used my installation documentation yet? He can indeed use

**Comment by Dmitri233** [comment]
I recorded a video telling you how to start it.
https://youtu.be/ZU09dDQO6Xk

**Comment by parkervcp** [comment]
That is outside of pterodactyl. Try that in pterodactyl and tell me when it works.

**Comment by Dmitri233** [comment]
<img width="379" alt="捕获" src="https://user-images.githubusercontent.com/36127740/57175824-cb78b480-6e82-11e9-8783-07c696a6a47e.PNG">
This will be executed first
Redis-server --port 0 --unixsocket /data/apid.socket --save ""
Then execute
Docker-compose up
right

**Comment by parkervcp** [comment]
that's not going to work in this situation man.docker-compose isn't going to work. We don't have root to run docker in the container. This is really an argument with someone who doesn't understand what they are talking about.

**Comment by Dmitri233** [comment]
I understand this. But I want to know if I can execute multiple commands like this.

**Comment by Dmitri233** [comment]
I want to open two containers. Then one of them uses redis. One of them is stoneserver. Because stoneserver needs a redis as support.

**Comment by Dmitri233** [comment]
How should I mount the directory inside the container?

**Comment by Dmitri233** [comment]
<img width="477" alt="捕获" src="https://user-images.githubusercontent.com/36127740/57196573-c6099000-6f90-11e9-9914-e25365cd6fc5.PNG">
Or how to follow this setting

**Comment by parkervcp** [comment]
As I have said before. None of this will work the way you think it should. You still don't understand how pterodactyl works.

I will continue to keep this request closed.

**Comment by Dmitri233** [comment]
Sorry. Today I found out that your official website has an eggs tutorial. I have been watching the get started page before.
