### ISSUE TITLE
[Egg Request]: Terraria Update

### ISSUE THREAD

**Issue by louanfontenele** [parkervcp/eggs#1924]
### Does this expand an already existing service

Yes

### Link to a game or software

Terraria

### Links for the download

https://terraria.org/api/download/pc-dedicated-server/terraria-server-1446-fixed.zip

### Links for the install docs

https://terraria.wiki.gg/wiki/Talk:Server

**Comment by Software-Noob** [comment]
The egg can pull the latest or allows you to specify the version in the startup variables. Reinstallation of the server is required for it to pull the files.

**Comment by louanfontenele** [comment]
> The egg can pull the latest or allows you to specify the version in the startup variables. Reinstallation of the server is required for it to pull the files.

Sorry, I don't really know how to ask for an update here, but I notice that the Terraria Server is now in a new domain, in the egg configuration it pointed to terraria.wiki.gg - but in the new configuration it asks to change the pointing to as per the image below:

![image](https://user-images.githubusercontent.com/2886066/197366110-ef69ef76-5c3d-4dec-bb22-868687115409.png)

Therefore, the wiki always updates only later, while directly through the site it always updates faster.

**Comment by louanfontenele** [comment]
> The egg can pull the latest or allows you to specify the version in the startup variables. Reinstallation of the server is required for it to pull the files.

Recently an update has arrived that fixes a bug, but it doesn't show on the wiki, but on the website it can download.

Also, I already downloaded and tried to install manually but it doesn't work because it asks for chmod permissions

**Comment by Software-Noob** [comment]
The egg scrapes terraria.wiki.gg which is what their official website points to as well. I don't remember why the main site wasn't used for fetching the latest, but there was a good reason at some point that I don't remember - either the format or anti-bot measures.

You can open a new issue or a pull request to change what's used for latest. Opening a feature request with simply a download link to a specific version provides no information whatsoever about the intention.
