### ISSUE TITLE
[Install Bug]: BeamMP

### ISSUE THREAD

**Issue by w00p** [parkervcp/eggs#1930]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

BeamNG/BeamMP

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play

### Actual Behavior

```
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
Digest: sha256:df7fa703ce272b70c963f578443b21059f7697975add738d61764652250c0fee 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./BeamMP-Server
./BeamMP-Server: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

### Steps To Reproduce

Set up the server, start.

### Install logs

https://nolog

**Comment by w00p** [comment]
I think this is related to the new BeamMP server update (v3.1.0) released?

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> 
> 1.10.1
> ### Wings Version
> 
> 1.7.0
> ### Service
> 
> BeamNG/BeamMP
> ### Modified
> 
> No, I did not modify the egg
> ### Expected Behavior
> 
> Install the server, start it, play
> ### Actual Behavior
> 
> ```
> container@pterodactyl~ Server marked as starting...
> [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
> Pulling from parkervcp/yolks 
> Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
> Digest: sha256:df7fa703ce272b70c963f578443b21059f7697975add738d61764652250c0fee 
> [Pterodactyl Daemon]: Finished pulling Docker container image
> :/home/container$ ./BeamMP-Server
> ./BeamMP-Server: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
> ```
> 
> ### Steps To Reproduce
> 
> Set up the server, start.
> ### Install logs
> 
> https://nolog

Please try this image and let me know if it works! `quintenqvd/pterodactyl_images:debian`

**Comment by spookybear0** [comment]
still having this issue after using that image

**Comment by QuintenQVD0** [comment]
> 

post install log

**Comment by QuintenQVD0** [comment]
looks like it runs for me if I builded it from source:
![afbeelding](https://user-images.githubusercontent.com/67589015/198692116-2385d15c-eba0-4d87-9ad5-8230ce167d58.png)
