### ISSUE TITLE
[Bug]: <7 Days to Die> Server is crashing. Because of telnet: Connection closed by foreign host.

### ISSUE THREAD

**Issue by Bazimek** [parkervcp/eggs#1941]
### Panel Version

1.10.1

### Wings Version

1.7.2

### Service

7 Days to Die

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Run the server without an issue.

### Actual Behavior

Clean installation. I just need to modify the telnet 127.0.0.1 because that can't connect. So I change to my internal IP (192.168.0.110) and it connecst but it says this:

Connection to 192.168.0.110 8086 port [tcp/*] succeeded!
Trying 192.168.0.110...
Connected to 192.168.0.110.
Escape character is 'off'.
Connection closed by foreign host.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

Install server via 7 Days to Die egg.
Run the server with default.

### Install logs

https://pteropaste.com/u3c51x

**Comment by Software-Noob** [comment]
You shouldn't modify the telnet address. It's local for a reason, as it's connecting to itself inside a container to provide console output.

**Comment by Bazimek** [comment]
But it cannot connect to the 127.0.0.1 ... it saying connection refused? I can't using 127.0.0.1 I guess because I am behind the router?

**Comment by Bazimek** [comment]
Oh .. nvm .. fixed. I just turn off the telnet in the origin config file and now it works. Thank you very much.
