### ISSUE TITLE
[Egg Request]: <ProjecrZomboid> Need update for new game version

### ISSUE THREAD

**Issue by Shuazijun** [parkervcp/eggs#1957]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/project_zomboid

### Links for the download

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/project_zomboid

### Links for the install docs

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/project_zomboid

**Comment by QuintenQVD0** [comment]
You use the template new egg, and you ask for an update? Use the  Install Bug Report or bug report one with logs on wy it is failing with the latest version

**Comment by Shuazijun** [comment]
for old egg error with mod.error like this.  
![image](https://user-images.githubusercontent.com/30001049/201481648-186e0e0a-e7e5-4989-b69a-ee2faac3570b.png)  
Server Settings:  
Mods=59meteor;DELIVERYBAGPACKS;ECTO1;67commando;70dodge;74amgeneralM151A2;78amgeneralM35A2;78amgeneralM49A2C;tsarslib;78amgeneralM50A3;RS_WaterCistern;82jeepJ10;82jeepJ10t;82oshkoshM911;83amgeneralM923;84merc;85merc;86fordE150;86fordE150dnd;86fordE150mm;86oshkoshP19A;87cruiser;88chevyS10;88golfMk2;88jettaMk2;89fordBronco;89def110;89def90;90niva;91range;92amgeneralM998;92nissanGTR;2507488373;AdmMTiles;AlexDakis;WaifuDakis;AlexDakisShop;AAS;AutoDrop;AutoLoot_CN;AutoMechanics;autotsartrailers;ATA_Bus;ATA_Dadge;ATA_VanDeRumba;ATA_Mustang_x2;ATA_Mustang;ATA_Jeep;ATA_Jeep_x2;ATA_Luton;ATA_Petyarbuilt;BRHextech;BedfordFalls;BetterFlashlights;betterLockpicking;ProfessionFrameworkB41Patch;BetterSortCC;Better crowbar;WaifuDakisShop;Blackwood;Blueberry;tkTiles_01;BogaPizza;ddBritaSoundFix;Brita_2;Brita_K153;pz-bzoukhotbar;bcUtils;CDDA_Zombie;CartoonTV;CatsReadMod;ChatBubble;CheatMenuRB;Chestown;Chinatown;ColdArmsOfChina;CombatText;Compatible Weapon Accessories;isoContainers;CCS;CosplayShop;CraftHelperContinued;DadgePPGPolice;Diederiks Tile Palooza;Dontbescared;waterPipes;DucklingsDakis;DylansTiles;EGNHInuman;EDW;IMWSEnergyDrinks;Everything Can Be Cooked    HydroCraft Part;Everything Can Be Cooked    Vanilla Part;ExtraMapSymbols;ExtraMapSymbolsUI;EN_Newburbs;EN_Flags;EN_Flags_Craft;faction_safehouses;FantaStreetTiles_01;FasterHoodOpening;FRUsedCarsNLF;FRUsedCarsNRN;FRUsedCars;FRUsedCarsFT;firearmmod;firearmmodbspatch;FixFloor;FH;fuelsideindicator;GetSquidCrayfishandShrimp;GhostTime;GhostTime_SP;Grapeseed;GreensTiles;GunSuicide;P4HasBeenRead;NoLighterNeeded;icecreammaker;ImprovisedGlass;ItemTweakerAPI;jumpThroughWindows;katanasandmachetesonbackorbelt;Ladders;lakeivytownship;MGS-Alert;MinimalDisplayBars;ModManager;ModManagerServer;modoptions;MonkeysLib;MoodleFramework;MoreBuilds;ToadTraits;ToadTraitsDisablePrepared;ToadTraitsDisableSpec;More Traits_CN;NewEkron;NightSprinters;nattachments;nukatilespack;OujinjinTiles;PwSleepingbags;PertsPartyTiles;PlayableArcadeMachines41;PocketKittens;projcardz;RAboiPetyarbuiltSkin;RAboiyemaMod1;RainWash;Ranking_PVE_Fix;UIMod;RavenCreek;readym;ReduceLagofCraftingMenu;ReducedWoodWeight2x41;RepairAnyClothes;RepairAnyMod;SlingModFix;StalkerArmorPack;sapphcooking;sapphcookingbettersorting;ScrapArmor(new version);TheWorkshop(new version);ScrapGuns(new version);ScrapWeapons(new version);Server Exchange;VUP-Simulator;ServerMessages;ShowSkillXpGain;showweaponstats;showweaponstatsTranslate;simonMDsDestroyedTiles;simonMDsTiles;SkillRecoveryJournal;SkizotsTiles;sleeponit;SleepWithFriends;SpnCloth;SpnHair;SupraMkIVfhq_skin;SupraMkIVfhq;survivingthroughseasons;Swatpack;Ramen;ToyotaSupraA80;ToyotaSupraA80_x2;RS_WaterCistern_FR_Overwrite;RS_WaterCistern_KI5_Addon;TMA_HOYOMIX;truemusic;classic_gd_music;Micha_elHits;TMC_TrueActions;TrueActionsDancing;VDK;ValhallaAdjustments;ValhallaAegis;VehiclePartsRepair;TheStar;Weapon Condition Indicator_CN;WestPointExpansion;wringclothesnostr;YouDriveISleep;svgMCerdato;ZBR;MWPWeapons;bikinitools;bt-ch-legacy;cherbourg;jiggasAddictionMod;jiggasGreenfireMod;Cosplaywa;GRTranslationCN;Swetrm Chinese Sinicization B;Swetrm Chinese Sinicization A;Swetrm Module Sinicization;TrueRollAction;Fox Translation;TrueMusic_Jay_Chou;CNRadioS;REMOD;REWMOD  
  
Map=BedfordFalls;Blackwood;Blueberry;Chestown;Chinatown;li_township;NewEkron;RavenCreek;west_point_expansion;cherbourg;Muldraugh, KY  
  
WorkshopItems=2772575623;2850450638;2478247379;2873290424;2785549133;2799152995;2392709985;2719592131;2886832257;2618213077;2811383142;2805630347;2469388752;2870394916;2566953935;2489148104;2886832936;2516123638;2522173579;2886833398;2441990998;2443275640;2422681177;2409333430;2642541073;2846036306;2507488373;2711526629;2818423278;2756636139;2427699853;2577903374;2669796154;2588598892;2282429356;2592358528;2743496289;2811232708;2681635926;2636100523;2792425535;2782258356;2862088921;522891356;2766033079;2368058459;2216760107;2313387159;2811707580;2536865912;2671890843;2384329562;2675786278;2768678519;2460154811;2794684100;2434425002;503640135;2749928925;2850170557;2690908199;2688676019;2732834772;2840889213;2730975264;2645618806;2286124931;2564624871;2625625421;2412050672;2707905930;2787291513;2809276103;2337452747;2775466475;2464581798;2811982953;2599752664;2673329292;2782740343;2674541310;2714731856;2701170568;2774834715;2784607980;2717575749;2554699200;2584112711;1510950729;2256623447;2756490460;2447729538;2616986064;2710945663;2772690680;2463499011;2734679675;2402057349;2544353492;2714198296;2754525193;2800412098;566115016;2688884240;2016648690;2737665235;2252982049;2557401447;2004998206;2694448564;2725216703;2169435993;2842158398;2859296947;515555911;1299328280;2672560941;2712480036;2104939198;2754567348;2858186668;2844829195;2714848168;2837923608;2445720450;2883925239;2851202490;2841573155;2806388145;2657661246;2800829125;2813282807;2196102849;2851584592;2611723883;2377867605;2142622992;2684045242;2831715402;2832136889;2658619264;2680473910;2125659488;2122265954;2749073898;2747736405;2759895539;2313633950;2762715872;2775382764;2862154374;2852704777;2503622437;2740919036;2673713236;2686624983;2684285534;2463184726;2774453073;2742154419;2753086629;2091564445;2382777667;2738652267;2832731073;2613146550;2865012251;2831194434;2487022075;2648779556;2689863681;2694358451;1558779191;2619072426;2674031168;2195155059;2724435363;2830570280;926315905;2834896128;2732407704;2634426926;1827428289;1703604612;2810320955;2216172287;2506921282;2507161010;2814226196;2522940210;2843701809;2234859503;2392317746
