### ISSUE TITLE
[Bug]:  ProjectZomboid

### ISSUE THREAD

**Issue by Shuazijun** [parkervcp/eggs#1958]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/project_zomboid

### Links for the download

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/project_zomboid

### Links for the install docs

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/project_zomboid

**Comment by Shuazijun** [comment]
For old egg error with mod.error like this.   
![image](https://user-images.githubusercontent.com/30001049/201481648-186e0e0a-e7e5-4989-b69a-ee2faac3570b.png)   
Error Logs:  
 https://pastebin.com/wXVymkp4  
Server Settings Info:   
https://pastebin.com/U3K7R61V

**Comment by QuintenQVD0** [comment]
This egg does not support mods

as you showed here:
![afbeelding](https://user-images.githubusercontent.com/67589015/201482325-e46b8b0c-5870-4e3a-bf13-ccdcc141084a.png)

**Comment by gOOvER** [comment]
This is not a Bug; this is a Feature Request

**Comment by QuintenQVD0** [comment]
> This is not a Bug; this is a Feature Request

He selected the template new egg , I changed the title. this should be closed and force them to use the right templete but yea.. this is the 2nd time the do this

**Comment by Shuazijun** [comment]
maybe ,you can test this config.  
https://github.com/parkervcp/eggs/issues/1958#issuecomment-1312540060  
I guess this may be caused by the container using an account with non root permissions, and the official support personnel did not give specific instructions.

**Comment by QuintenQVD0** [comment]
This is some issue with the mod not the egg
