### ISSUE TITLE
[Bug]: MongoDB

### ISSUE THREAD

**Issue by Huguitis** [parkervcp/eggs#1963]
### Panel Version

1.10.4

### Wings Version

1.7.2

### Service

mongodb

### Modified

No, I did not modify the egg

### Expected Behavior

Install the mongodb server and a nodejs server for discord bot (for example) on the same node (vps/machine). Start both servers connecting the nodejs server to the mongodb server without problems.

### Actual Behavior

When starting the both servers, the nodejs server (for example) doesn't connect to the mongodb server if both servers are on the same node. ("Connection refused" error)
I have tried separating these servers and running each one on different nodes and it works fine, with the same mongodb credentials.
![image](https://user-images.githubusercontent.com/65133800/202256962-0e985173-1b10-4158-a077-b2faac93951d.png)

### Steps To Reproduce

1. Create a mongodb server and a nodejs server (for example)
2. Start the mongodb server without any problem.
3. Make the nodejs server to connect to the mongodb one with the mongoose library (Or other libraries)
4. Start the nodejs and see the results.

### Install logs

https://pteropaste.com/sqk3j7

**Comment by TASelwyn** [comment]
Try binding the mongodb to 172.18.0.1, and in your nodejs server connect to 172.18.0.1.
Since servers in pterodactyl are ran in containers, 127.0.0.1 refers to the container. Not the node. You need to use the docker network interface (172.18.0.1) to communicate between containers. It's similar to why you need to follow https://pterodactyl.io/community/games/minecraft.html for minecraft.

**Comment by Huguitis** [comment]
Hello, thanks for responding! But doen't seems to work.

**Comment by parkervcp** [comment]
I don't see this as a MongoDB issue but potentially with your nodejs configuration.

**Comment by Huguitis** [comment]
But I have tried separating these servers and running each one on different nodes and it works fine, with the same mongodb credentials and code for the nodejs server.

**Comment by TASelwyn** [comment]
"Connection refused" is a networking issue. Check your ip allocations; firewall for 172.18 (docker's network interface doesn't like connections to others by default)

**Comment by parkervcp** [comment]
If they are on the same host then it's likely to be a firewall issue.

**Comment by Huguitis** [comment]
> "Connection refused" is a networking issue. Check your ip allocations; firewall for 172.18 (docker's network interface doesn't like connections to others by default)

The alloction IP must be "172.18.0.1"?

**Comment by Huguitis** [comment]
Not working...

**Comment by QuintenQVD0** [comment]
I think this has to be setup the same way as minecraft bunngecord

Set the allocated ip to `127.0.0.1:<LOCALHOST_PORT>`
Run the ufw command to allow that port on 127.0.0.1 to the pterodactyl0 docker interface 
```sh
ufw allow in on pterodactyl0 to 172.18.0.1 port <LOCALHOST_PORT> proto tcp
```
use `172.18.0.1` in your bot config

**Comment by Huguitis** [comment]
Still the connection refushed error:
![image](https://user-images.githubusercontent.com/65133800/202551544-ca9c8b09-a7d5-471d-94fa-0d62214ceebf.png)

**Comment by Software-Noob** [comment]
This is a configuration issue related to Docker network isolation and not a bug in the egg.

Some advise has been provided above, you can follow the Minecraft documentation or use Discord channel for possibly someone to provide the steps.
