### ISSUE TITLE
[Egg Request]: <Software/Game> Frozen Flame

### ISSUE THREAD

**Issue by elysium38711** [parkervcp/eggs#1964]
### Does this expand an already existing service

No

### Link to a game or software

https://frozen-flame.com/

### Links for the download

https://steamdb.info/app/1348640/info/

### Links for the install docs

https://steamdb.info/app/1348640/info/

**Comment by gOOvER** [comment]
I dont own the game and its a OwnersOnly Server.

`section_type | ownersonly`

**Comment by QuintenQVD0** [comment]
We generally do not make egg for game servers that require ownership of that game.

**Comment by QuintenQVD0** [comment]
If someone that owns that game and knows how to make a egg for it then fine,

**Comment by Blitzbat** [comment]
I've added a pull request for frozen flame #1968

**Comment by QuintenQVD0** [comment]
closes as #1968 is merged
