### ISSUE TITLE
[Egg Request]: SpotDL

### ISSUE THREAD

**Issue by wombat24455** [parkervcp/eggs#1973]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/spotDL/spotify-downloader

### Links for the download

https://github.com/spotDL/spotify-downloader/releases/

### Links for the install docs

https://spotdl.readthedocs.io/en/latest/installation/

**Comment by Software-Noob** [comment]
This is grey/illegal area regarding downloading copyrighted music.
