### ISSUE TITLE
[Install Bug]: 5etools startup script typo

### ISSUE THREAD

**Issue by ReonMonterus** [parkervcp/eggs#1980]
### Panel Version

1.10.4

### Wings Version

1.7.2

### Service

5etools

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start the server, use the webpage

### Actual Behavior

Server crashed with error: Error: unknown shorthand flag: 'c' in -config

### Steps To Reproduce

Step 1 install egg
Step 2 start server

### Install logs

https://pteropaste.com/6m8n3o

**Comment by ReonMonterus** [comment]
Config needs to be run with --config instead of -config.

**Comment by gOOvER** [comment]
> Config needs to be run with --config instead of -config.

why don't you open a PR?

**Comment by ReonMonterus** [comment]
Crippling anxiety mostly.
