### ISSUE TITLE
[Egg Request]: altV - Athena Framework

### ISSUE THREAD

**Issue by MorisatoK** [parkervcp/eggs#1982]
### Does this expand an already existing service

Yes

### Link to a game or software

https://athenaframework.com/

### Links for the download

https://github.com/stuyk/altv-athena

### Links for the install docs

https://athenaframework.com/intro/install/installing-on-linux

**Comment by MorisatoK** [comment]
Requesting this, since this is not as straight forward as it seems with the existing altV egg. Athena Framework is on top of altV (without actually requiring it) and requires a database and uses a Git workflow (to a private repo) for its customized resources.

**Comment by QuintenQVD0** [comment]
Not realy posible as it also needs mongo db and ssh keys and private repo's

**Comment by MorisatoK** [comment]
That's a bummer, I had hopes it would be possible with the mongo db egg (connection strings are configurable) and some configuration magic during egg install.

**Comment by QuintenQVD0** [comment]
> That's a bummer, I had hopes it would be possible with the mongo db egg (connection strings are configurable) and some configuration magic during egg install.

likly not a egg can only install 1 server. This is way to complicated for ptero as it needs 2 servers and a private repo with ssh keys
