### ISSUE TITLE
[Bug]: <fiveM>

### ISSUE THREAD

**Issue by ImagineWagons1** [parkervcp/eggs#1984]
### Panel Version

newest  

### Wings Version

Newest 

### Service

Fivem

### Modified

No, I did not modify the egg

### Expected Behavior

Buy server creates and then it works 

### Actual Behavior

![D16C1D6E-88DE-4C66-8E74-7BB62CCAA965](https://user-images.githubusercontent.com/66953572/204920148-369e1c45-f41a-49c6-a39e-4ddc5cefdedc.png)

### Steps To Reproduce

Try to buy a server 

### Install logs

No logs required

**Comment by parkervcp** [comment]
This is not a problem with the egg.

1. You are not supposed to sell fivem hosting.
2. If you can't figure this part out maybe you shouldn't be charging people to host for them.
3. "newest" is not a valid version.
