### ISSUE TITLE
[Egg Request]: <Icarus Dedicated Server>

### ISSUE THREAD

**Issue by skynett81** [parkervcp/eggs#1993]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/RocketWerkz/IcarusDedicatedServer/wiki/Server-Setup

### Links for the download

https://github.com/RocketWerkz/IcarusDedicatedServer/wiki/Server-Setup

### Links for the install docs

https://github.com/RocketWerkz/IcarusDedicatedServer/wiki

**Comment by QuintenQVD0** [comment]
<html><body>


section_type | ownersonly
-- | --



</body>
</html>

So likly no, maby if someone ows the game of the staff them or of the community then yes

**Comment by QuintenQVD0** [comment]
and windows only so it needs to run with wine

**Comment by skynett81** [comment]
you find all info you need on the links

https://github.com/RocketWerkz/IcarusDedicatedServer/wiki

**Comment by Software-Noob** [comment]
> section_type	ownersonly
> So likly no, maby if someone ows the game of the staff them or of the community then yes

The game requires ownership, but the [dedicated server depot is public.](https://steamdb.info/app/2089300/subs/)

**Comment by skynett81** [comment]
Setting up a dedicated server is a technical process and not something we expect every player to do

Icarus
- Branch: Dedilive
- PW: 'IWillBackUpMyLocalSave'
- Run to start the Icarus Client
- If you are worried about your offline data, please back it up before logging in as a data migration occurs

Icarus Dedicated Servers
- Dedicated Server Application
- https://github.com/RocketWerkz/IcarusDedicatedServer/wiki
- Run to start a dedicated server

Please note, this is our testing release, we have more work to do
We appreciate all feedback on all aspects related to the dedicated servers

When mentioning issues please provide
- P2p or dedicated server connection
- A description of the issue (endret)

**Comment by QuintenQVD0** [comment]
> Setting up a dedicated server is a technical process and not something we expect every player to do
> 
> Icarus
> 
>     * Branch: Dedilive
> 
>     * PW: 'IWillBackUpMyLocalSave'
> 
>     * Run to start the Icarus Client
> 
>     * If you are worried about your offline data, please back it up before logging in as a data migration occurs
> 
> 
> Icarus Dedicated Servers
> 
>     * Dedicated Server Application
> 
>     * https://github.com/RocketWerkz/IcarusDedicatedServer/wiki
> 
>     * Run to start a dedicated server
> 
> 
> Please note, this is our testing release, we have more work to do We appreciate all feedback on all aspects related to the dedicated servers
> 
> When mentioning issues please provide
> 
>     * P2p or dedicated server connection
> 
>     * A description of the issue (endret)

I now how to setup steamcmd server / eggs
![afbeelding](https://user-images.githubusercontent.com/67589015/206192349-c3dd5968-c209-4958-a21b-ce488de58a5e.png)

 I can try but not RN, maybe 17/12. I am bussy until then

**Comment by parkervcp** [comment]
Per the steamdb page the server is owners only - https://steamdb.info/app/2089300/

**Comment by gOOvER** [comment]
you dont need the Game for installing the Server.

i have allready an Egg for it, but its not Public for now

**Comment by BolverBlitz** [comment]
Feel free to try out #1996 and provide some feedback, i do have very litle knowlage about wine, winefix and pterodactyl eggs in general. 
It installes fine. You can join. I just have not played a mission on it yet, since they require quite some time ^^

Basicly just followed what @gOOvER had to say on the discord.

**Comment by ImagineWagons1** [comment]
> i have all ready an Egg for it, but its not Public for now

quoting that you have an egg for it? so it is do able?

**Comment by QuintenQVD0** [comment]
> 

There is a egg in PR but it needs some changes. it will already work but need some change to let updating work and reduse install time

**Comment by parkervcp** [comment]
Egg was merged
