### ISSUE TITLE
[Egg Request]: ATS / ETS Convoy Dedicated Server

### ISSUE THREAD

**Issue by gothaussencl** [parkervcp/eggs#1997]
### Does this expand an already existing service

Yes

### Link to a game or software

https://blog.scssoft.com/2022/12/convoy-dedicated-servers-support.html

### Links for the download

Steam Dedicated Server

### Links for the install docs

https://blog.scssoft.com/2022/12/convoy-dedicated-servers-support.html

**Comment by QuintenQVD0** [comment]
This currently is not posible as there is literly 0 documentation. I tryed. it need some file that is generate by a running game. and it will always look for that file in /home what is not writeable. I tryed native linux and wine and both have the same problem. Is there is some good documentation out then yes, else currently no

**Comment by RADICALAdrift** [comment]
I mean there is some and i say some documentation included with the server files in the form of a readme and yes that is literally all the docs they have released that i can find, But i will warn you it is very limited on actually helping set-up a server in my opinion plus it needs extra files which you have to generate within ATS or ETS2 by typing export_server_packages in the in-game console

**Comment by QuintenQVD0** [comment]
> I was able to mount the server (without the panel) and indeed, it needs 2 files that are extracted from the game (which should be an extra step inside the egg) This file goes inside a folder that the server creates automatically in my case: /root/.local/share/Euro Truck Simulator 2/

I have a all most working egg as I miss those 2 files.
What I understand is that the 1 file is just a config file what is standart for every server
but it needs like a pack and that is specific to DLC installed?

**Comment by gothaussencl** [comment]
oops, I accidentally closed the thread.

**Comment by QuintenQVD0** [comment]
> necessary

SO if I understand it, both files are specific to the steam account / game the are generated on?
If they're non-specific I can just include them but if the are specific I will have the user manualy have to upload the files ..
yea, it would be really nice if you can send them to me on discord `Quinten#6775`

**Comment by RADICALAdrift** [comment]
> Indeed, you have to have those 2 files that are generated through the game, but that does not mean that it can be universal. If you want I can share the files (which are without mods and with some dlcs) It is not necessary for the server to contain those DLC's because the files that the server requests are only called by "name or something like that" but the server as those dlc's does not need them.

True, i guess you could just have the files there with the option for the user to replace them with their own files if they so choose to and of course know how to

**Comment by RADICALAdrift** [comment]
i wouldn't see why they would tie them to a specific steam account but game yes of course ETS2 for a ETS2 server and ATS for a ATS Server,

The only other issue i could see where the user would need to own the game is for a Server Logon Token
7. Server logon token
---------------------
By default whenever a dedicated server is launched it is using an anonymous account. For such an account non-persistent server id is generated (used for direct search). To avoid this you can acquire a logon token on https://steamcommunity.com/dev/managegameservers (game ownership is required).

**Comment by HerrSammyDE** [comment]
> i wouldn't see why they would tie them to a specific steam account but game yes of course ETS2 for a ETS2 server and ATS for a ATS Server,
> 
> The only other issue i could see where the user would need to own the game is for a Server Logon Token, Though i would guess anyone wanting to run a server for either game would own the game anyway
> 
> 7. Server logon token

It seems that this is needed for every server, so I would not consider this a problem if the server owner has to specify a token.

**Comment by RADICALAdrift** [comment]
> > i wouldn't see why they would tie them to a specific steam account but game yes of course ETS2 for a ETS2 server and ATS for a ATS Server,
> > The only other issue i could see where the user would need to own the game is for a Server Logon Token, Though i would guess anyone wanting to run a server for either game would own the game anyway
> > 
> > 7. Server logon token
> 
> It seems that this is needed for every server, so I would not consider this a problem if the server owner has to specify a token.

Its needed to allow the server to show up on the convoy session list thats about it though

**Comment by RADICALAdrift** [comment]
I suppose its only an issue when the person trying to setup the server doesn't actually own the game to get a token for the server but tbh thats likely a small minority like

**Comment by QuintenQVD0** [comment]
ATS is merged and ETS2 is in PR
