### ISSUE TITLE
[Feedback]: Remove "Buy me a coffee" Link from this repo and let Egg creaters add their own donation Link

### ISSUE THREAD

**Issue by gOOvER** [parkervcp/eggs#2000]
### Expected Behavior

Every Egg Author, which push to this repro should be able to provide their own Donation Link

### Actual Behavior

ATM Only Parker have a Donation Link for "Buy me a Coffey"

**Comment by gOOvER** [comment]
The development of Egg is not always self-evident and there is work behind it. So it can't be that only the repo owner has a donation link.

Every Egg author should be allowed to add a donation link, so that their work is appreciated.

**Comment by parkervcp** [comment]
Nobody has ever asked or tried adding a donation link. I had mine there from the beginning for when I was making eggs alone and had to buy many games to test them out.

As the repo has grown and I have gotten PR's from more people to add eggs it has expanded beyond what I ever imagined. I had added more maintainers to help manage incoming PR's. There are plans on expanding some of the tooling around the repo so make PR's more "automated" on the maintainer end. Hopefully that will make the process easier for us.

Honestly, adding a maintainer and donation link is probably a better approach to the egg readme's than removing my link outright.

**Comment by gOOvER** [comment]
copy and pated from Discord:

`Your repo and your decision; but in my opinion your link is always visible first and you also know that 98% never read the readme. So at least an equal opportunity would be created`

**Comment by lilkingjr1** [comment]
Unfortunately, this is where I again would like to give my opinion that if the Pterodactyl community is to have an "official" repo of eggs, it should really be migrated to the generic Pterodactyl Github account as a separate repo (separate from the even more official `seeding` folder of the project; unless that is desired).

Short of that, it's my personal opinion that:
- The front page donation link should just be removed
- Any eggs parker originally made should have the donation link added to their readme's
- Any eggs that have active maintainers or creators should have the right to PR their personal donation link to, effectively, **their** egg's readme

But that's just an opinion and not a reality. If parker wants to just take all the PRs he's gotten over the years and just own them outright, he has full right to. I just think one's more fair than the other.

On a side note, I think taking the HTML template I use on my readme's to indicate authors and maintainers and applying it to the whole repo could be nice. Could even modify it to include donation links.

**Comment by gOOvER** [comment]
> Unfortunately, this is where I again would like to give my opinion that if the Pterodactyl community is to have an "official" repo of eggs, it should really be migrated to the generic Pterodactyl Github account as a separate repo (separate from the even more official `seeding` folder of the project; unless that is desired).
> 
> Short of that, it's my personal opinion that:
> 
> * The front page donation link should just be removed
> * Any eggs parker originally made should have the donation link added to their readme's
> * Any eggs that have active maintainers or creators should have the right to PR their personal donation link to, effectively, **their** egg's readme
> 
> But that's just an opinion and not a reality. If parker wants to just take all the PRs he's gotten over the years and just own them outright, he has full right to. I just think one's more fair than the other.
> 
> On a side note, I think taking the HTML template I use on my readme's to indicate authors and maintainers and applying it to the whole repo could be nice. Could even modify it to include donation links.

Exactly what I think all along and also have long suggested.

Parker, nothing against you, but as mentioned your link is very dominant here, that is, everyone sees it first and you also do not really much for some time. if there are donations, they go to you. (Without really having had work)

I would ask you to finally turn the whole thing into an official repo under the administration of pterodactyl.

**Comment by ZaxLofful** [comment]
Just my two cents...I agree that this repo should be moved to the official Pterodactyl GitHub account.

At the same time, this repo should just be default in Pterodactyl.

Everything in this repo should just show up in Pterodactyl by default....Why should I have to add all these Eggs myself?

Its not like the JSON configs are large by any means, just include everything from the start.

**Comment by QuintenQVD0** [comment]
> Just my two cents...I agree that this repo should be moved to the official Pterodactyl GitHub account.
> 
> At the same time, this repo should just be default in Pterodactyl.
> 
> Everything in this repo should just show up in Pterodactyl by default....Why should I have to add all these Eggs myself?
> 
> Its not like the JSON configs are large by any means, just include everything from the start.

The panel repo mainains like 10 eggs, we way more.

**Comment by Northwave** [comment]
As User I like the idea, in every fresh install i have to upload the eggs again and again

> Everything in this repo should just show up in Pterodactyl by default....Why should I have to add all these Eggs myself?

**Comment by QuintenQVD0** [comment]
> fresh

All egg shipped with the panel pterodactyl are almost 100% guaranty to work. That is currently not with this repo

**Comment by parkervcp** [comment]
Per this request. I have removed my buymeacoffee link as that was the main concern.

As I had previously stated, I never told anyone they couldn't add their own donation link, as nobody ever asked or tried.

For the rest of the conversation, I will say that the amount of eggs I have in this repo would be unsustainable for the panel to keep in place. The sheer number of docker images and games that require fairly regular updates is already daunting.
