### ISSUE TITLE
[Bug]: egg-rage--m-p.json

### ISSUE THREAD

**Issue by dension0** [parkervcp/eggs#2003]
### Panel Version

WISP - v2.4.29

### Wings Version

WISP - v2.0.28

### Service

eggs/game_eggs/gta/ragemp/

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Just I added two lines begin of script:

# Clean reinstall - Remowe files before reinstall
rm -rf /mnt/server

### Actual Behavior

[SILVERHOST] Server marked as OFF
[SILVERHOST] ---------- Detected server process in a crashed state! ----------
[SILVERHOST] Exit code: 1
[SILVERHOST] Out of Memory: false
[SILVERHOST] Error Response: 
[SILVERHOST] Server process detected as entering a crashed state; rebooting.

Log:
generic.starting_container
:/home/container$ ./ragemp-server
generic.state_changed.off
generic.crash_detected
generic.exit_code
generic.out_of_memory
generic.error_response
generic.aborting_reboot

### Steps To Reproduce

The WISP is a extended Pterodactyl: https://pterodactyl.io/project/about.html#sponsors

All eggs working what I could try. But RAGMP is not working. Download all files, but start with crash and stop.

### Install logs

https://termbin.com/4ysf6

**Comment by QuintenQVD0** [comment]
This is ptero support not WISP

**Comment by dension0** [comment]
> + that egg is 2 years old

Thank your information, but that doesn't solve the problem.

**Comment by QuintenQVD0** [comment]
> > * that egg is 2 years old
> 
> Thank your information, but that doesn't solve the problem.

You pay them for support. The egg here will soon get a update

**Comment by dension0** [comment]
> This is ptero support not WISP

I am aware of. But the eggs made for Pterodactyl work perfectly and flawlessly with WISP, it is no coincidence that WISP is a major financial supporter of the Pterodactyl project.
So if it doesn't work with WISP, it won't work with Pterodatyl either.

**Comment by QuintenQVD0** [comment]
I am looking at the egg rn

**Comment by QuintenQVD0** [comment]
and we can not do rm -rf on startup as it will remove maps and player data and plugins

**Comment by dension0** [comment]
> and we can not do rm -rf on startup as it will remove maps and player data and plugins

I remove the added first two lines and tested. The problem is same. When I try to start server it crashes.

**Comment by QuintenQVD0** [comment]
> > and we can not do rm -rf on startup as it will remove maps and player data and plugins
> 
> I remove the added first two lines and tested. The problem is same. When I try to start server it crashes.

the egg downloads old builds , I am changing it rn

**Comment by dension0** [comment]
> 

Thank you very much.

**Comment by QuintenQVD0** [comment]
@dension0 ^^ egg is in PR

**Comment by dension0** [comment]
> @dension0 ^^ egg is in PR

I tried it with modified config. Daemon restarted of course. I got error: 
:/home/container$ ./ragemp-server
/entrypoint.sh: line 12:    13 Aborted                 (core dumped) ./ragemp-server

**Comment by QuintenQVD0** [comment]
> > @dension0 ^^ egg is in PR
> 
> I tried it with modified config. Daemon restarted of course. I got error: :/home/container$ ./ragemp-server /entrypoint.sh: line 12: 13 Aborted (core dumped) ./ragemp-server

Are you on arm64? As it works fine for mz in ptero. 
This is likly related to wips and not ptero

**Comment by dension0** [comment]
> 

Dedicated Intel based server (64 bit)

Log:
generic.starting_container
:/home/container$ ./ragemp-server
terminate called after throwing an instance of 'Json::LogicError'
what():  Value is not convertible to bool.
/entrypoint.sh: line 12:    13 Aborted                 (core dumped) ./ragemp-server
generic.state_changed.off
generic.crash_detected
generic.exit_code
generic.out_of_memory
generic.error_response
generic.aborting_reboot

**Comment by QuintenQVD0** [comment]
> > 
> 
> Dedicated Intel based server (64 bit)
> 
> Log: generic.starting_container :/home/container$ ./ragemp-server terminate called after throwing an instance of 'Json::LogicError' what(): Value is not convertible to bool. /entrypoint.sh: line 12: 13 Aborted (core dumped) ./ragemp-server generic.state_changed.off generic.crash_detected generic.exit_code generic.out_of_memory generic.error_response generic.aborting_reboot

It is becausz the config changed but it can not pull it because it is not yet in the master branch

**Comment by QuintenQVD0** [comment]
Remove the file parser out of that egg, and replace the config with the one feom this pr and manual change the port

**Comment by dension0** [comment]
> Remove the file parser out of that egg, and replace the config with the one feom this pr and manual change the port

Thanks. Now it is working.
