### ISSUE TITLE
[Egg Request]: Pufferfish Server

### ISSUE THREAD

**Issue by WaldperlachFabi** [parkervcp/eggs#2013]
### Does this expand an already existing service

No

### Link to a game or software

https://pufferfish.host/downloads

### Links for the download

https://github.com/pufferfish-gg/Pufferfish

### Links for the install docs

https://docs.pufferfish.host/

**Comment by QuintenQVD0** [comment]
Parker stated multpile times that we will not add more flavors of MC

**Comment by parkervcp** [comment]
There are enough minecraft eggs that also let you put your own download links in. I will maintain this point of view until one proves to outlast the other minecraft servers we already have.
