### ISSUE TITLE
[Egg Request]: Mattermost

### ISSUE THREAD

**Issue by peteret** [parkervcp/eggs#2015]
### Does this expand an already existing service

No

### Link to a game or software

https://mattermost.com/

### Links for the download

https://github.com/mattermost/mattermost-server

### Links for the install docs

https://docs.mattermost.com/guides/deployment.html#install-guides

**Comment by parkervcp** [comment]
You need to have a DB to run with this egg. While possible it would require either running a db in the container with it or a separate egg.

**Comment by peteret** [comment]
Please creat separated egg for mattermost
