### ISSUE TITLE
[Bug]: Python Generic 

### ISSUE THREAD

**Issue by pernydev** [parkervcp/eggs#2016]
### Panel Version

1.10.4

### Wings Version

1.7.2

### Service

python

### Modified

Nope.

### Expected Behavior

When I modify the git credentials and reinstall the server it would modify the .git folder with the updated access token ect. Without having to remove all files. 

### Actual Behavior

It doesn't update the .git/config file and old access key stays there.

### Steps To Reproduce

1. Make a private repository
2. Make an access token
3. Make the Pterodactyl server
4. Regenerate the token
5. Update it in Startup settings
6. Reinstall the server

### Install logs

I don't think this is required for my issue. If requested, I will provide.

**Comment by yesBad** [comment]
Step 5.5 Delete all files.

**Comment by pernydev** [comment]
@yesBad That'll just fix it. Read read "Expected Behavior"

**Comment by yesBad** [comment]
Also this is with all generic eggs that have git integration iirc.

**Comment by pernydev** [comment]
True.

**Comment by parkervcp** [comment]
The generic egg just pulls the files as is and I am not accounting for people changing credentials. That would be an undertaking I am not interested in.
