### ISSUE TITLE
[Egg Request]: Uptime Kuma

### ISSUE THREAD

**Issue by ManucrackYT** [parkervcp/eggs#2017]
### Does this expand an already existing service

No

### Link to a game or software

https://uptime.kuma.pet/

### Links for the download

https://github.com/louislam/uptime-kuma

### Links for the install docs

https://github.com/louislam/uptime-kuma/wiki

**Comment by QuintenQVD0** [comment]
Duplicated #1645

**Comment by QuintenQVD0** [comment]
Now named generic nodejs

**Comment by gOOvER** [comment]
fixed with #2076
