### ISSUE TITLE
[Bug]: <Minecraft Paper>

### ISSUE THREAD

**Issue by ImagineWagons1** [parkervcp/eggs#2024]
### Panel Version

1.11.1

### Wings Version

latest

### Service

Minecraft paper

### Modified

No, I did not modify the egg

### Expected Behavior

install server on 1.19.2 version 

### Actual Behavior

Error when changing the minecraft version to 1.19.2 error below 
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

set minecraft version and paper version to 1.19.2
start 
error 
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Install logs

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 1 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by parkervcp** [comment]
you have any more log here?

**Comment by NgLoader** [comment]
Can you please tell us the wings version you're currently using and not ``latest`` please?
You can see your wings version when hovering over the heartbeat symbol under ``Admin -> Nodes``

Also check if you have selected the right java version!
You need to select Java17 for Minecraft 1.19.*

Also please provide some more info like:
- Allocated Memory
- Disk Space Limit
- Block IO Proportion

And what kind of variables you have set:
- Minecraft Version
- Build Number

**Comment by QuintenQVD0** [comment]
Without install  logs we are notthing.

**Comment by ImagineWagons1** [comment]
I'll send them over when I'm back home, just in work

**Comment by ImagineWagons1** [comment]
Wings version 1.11.0
Allocated Memory: 6000
Disk Space Limit:10000
Block IO Proportion: 500

Minecraft Version:1.19.2
Build Number: 
Java Version Java17
Install Logs: https://pteropaste.com/ghf318/

**Comment by parkervcp** [comment]
That install says fabric installer. I am going to assume it failed due to this being a different server first.

**Comment by ImagineWagons1** [comment]
It's a brand new server, its never been another version

**Comment by ImagineWagons1** [comment]
It doesn't think on the first time install

**Comment by ImagineWagons1** [comment]
it does it on the First time install *
