### ISSUE TITLE
[Egg Request]: Hell Let Loose

### ISSUE THREAD

**Issue by SintrixV1** [parkervcp/eggs#2026]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.hellletloose.com/

### Links for the download

https://store.steampowered.com/app/686810/Hell_Let_Loose/

### Links for the install docs

Have not found one, Sorry

**Comment by yesBad** [comment]
you cant selfhosted that is atleast how it looks...

**Comment by SintrixV1** [comment]
Ok thanks man
