### ISSUE TITLE
[Bug]: Discord.py

### ISSUE THREAD

**Issue by FroostySnoowman** [parkervcp/eggs#2027]
### Panel Version

1.10.4

### Wings Version

1.7.2

### Service

Discord.py

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

It should clone the specific GitHub Repository and import the files.

### Actual Behavior

The files are not imported. I have tried numerous different configurations and I can't get any files to be cloned or imported from my GitHub Repository.

### Steps To Reproduce

Install discord.py egg
Setup a GitHub Repo
Do the configs below
<img width="1045" alt="Screenshot 2022-12-28 at 2 27 13 PM" src="https://user-images.githubusercontent.com/49008912/209873883-2bba0a12-925f-4eeb-ac23-d335ce411b52.png">
Nothing happens.

### Install logs

https://pteropaste.com/s1b5pr

**Comment by parkervcp** [comment]
the install log shows that git url specified was the py file and not the repo itself.

**Comment by FroostySnoowman** [comment]
> The install log shows that git url specified was the py file and not the repo itself.
> 
> Specifically
> 
> ```
> fatal: repository 'https://github.com/FroostySnoowman/TestingPtero/blob/main/main.py.git/' not found
> ```

I noticed this before doing the log and for whatever reason it does not appear to update. I will get the paste again after doing a fresh install.

**Comment by FroostySnoowman** [comment]
Here is the new log.

https://pteropaste.com/i8h7gk

**Comment by danny6167** [comment]
You have put the git repo address in the branch field.

**Comment by FroostySnoowman** [comment]
> You have put the git repo address in the branch field.

That is indeed something that I have tried with my numerous attempts and it still doesn't pull from the repository.

**Comment by FroostySnoowman** [comment]
Technically I can get it to update, however, I need to reinstall the server every time. I was hoping that when you click "Start" it'll do it automatically and not need to reinstall.

**Comment by FroostySnoowman** [comment]
Got it to work- The thing I was missing for all of the steps was "Auto Update".
<img width="1016" alt="Screenshot 2022-12-28 at 3 32 12 PM" src="https://user-images.githubusercontent.com/49008912/209881085-f7391433-1443-4cd2-a789-f7c4f6b0b106.png">
