### ISSUE TITLE
[Bug]: stationeers requires a newer glibc version

### ISSUE THREAD

**Issue by X-Coder** [parkervcp/eggs#2031]
### Panel Version

1.10.3

### Wings Version

1.7.2

### Service

stationeers

### Modified

No, I did not modify the egg

### Expected Behavior

Currently this egg is crashing on start on all of my servers.
Can you please verify this egg is still working for you?

It seems, since stationeers did a new game release, ~two weeks ago, this egg is broken because of a missing dependency, it requires a newer version of glibc. 

From what I have read on the official stationeers discord, the new game release is now based on a newer glibc release: linux glibcxx 3.4.29 & glibc 2.34) because it is based now on ubuntu 22.

With debian 11 (glibc 2.31) it does not work any more. Don't know if stationeers devs intend to restore debian 11 compatibility.

[The user mike842 confirmed, dedicated server works in debian testing bookworm.](https://discord.com/channels/276525882049429515/392080751648178188/1055378559851569212)

### Actual Behavior

This is the error message, when the server is crashing at start:
`DllNotFoundException: RocketNet assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) RocketNet.RocketNetNative.abi_GetInstance()
  at RocketNet.RocketNetInstance..ctor () [0x00006] in <48b2691811284ed4b05f438d7468f1d9>:0 
  at Assets.Scripts.Networking.NetworkManager..cctor () [0x0004e] in <c4203c98d3da42cd97754c092c6c3f1d>:0 
Rethrow as TypeInitializationException: The type initializer for 'Assets.Scripts.Networking.NetworkManager' threw an exception.
  at NetworkBase..cctor () [0x00000] in <c4203c98d3da42cd97754c092c6c3f1d>:0 
Rethrow as TypeInitializationException: The type initializer for 'Assets.Scripts.NetworkServer' threw an exception.
  at Assets.Scripts.GameManager.Awake () [0x0003c] in <c4203c98d3da42cd97754c092c6c3f1d>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception, Object)
Assets.Scripts.GameManager:Awake()`

### Steps To Reproduce

Just install and start.

### Install logs

N/A

**Comment by gOOvER** [comment]
this is known and there is allready an Image in Review, so no need to open a bugreport

**Comment by gOOvER** [comment]
as a quickfix, use this Image:


`ghcr.io/goover/steamcmd:ubuntu`

**Comment by X-Coder** [comment]
Thank you, I will test it.

**Comment by X-Coder** [comment]
Your quickfix is working fine, thanks four your fast help.

I leave this bug report open, until the fix is applied, in case someone has the same issue.

**Comment by QuintenQVD0** [comment]
> Your quickfix is working fine, thanks for your fast help.
> 
> I leave this bug report open, until the fix is applied, in case someone has the same issue.

There is a open PR for a offical ubuntu steamcmd image, I am revieuwing it rn

**Comment by QuintenQVD0** [comment]
New image is on the way but I something went wrong with the Dockerfile that I looked over, It will be fixt later this day

**Comment by QuintenQVD0** [comment]
egg is in PR and ready to be merged!
