### ISSUE TITLE
[Bug]: Don't Starve Together

### ISSUE THREAD

**Issue by DatCaptainHorse** [parkervcp/eggs#2035]
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

SteamCMD

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Install server, assume everything including "Caves" shard server works and is accessible ingame.

### Actual Behavior

"Caves" shard is inaccessible, going into Caves through sinkhole ingame results in player getting thrown back into character selection screen, with error "Failed to migrate to the Caves" in server console.

### Steps To Reproduce

Step 1 Add egg to server nests if not already there

Step 2 Create and install DST server

Step 3 Join the game, collect 2 sticks and 2 flint in order to make a pickaxe, find a blocked sinkhole (or with command `c_gonext("cave_entrance")` ingame to be teleported near one).

Step 4 If the sinkhole isn't blocked, jump in and get thrown to character selection screen, with the error in server console.

### Egg modifications:

1. Remove deprecated `-console` parameters from startup
2. Switch to x64 server binaries `bin64/dontstarve_dedicated_server_nullrenderer_x64`
3. Assign and allocate following ports to game shards and cluster:
    - 10099: as `[NETWORK] server_port` config port in Master-shard server.ini
    - 11000: as `[NETWORK] server_port` config port in Caves-shard server.ini
    - 11001: as `[STEAM] master_server_port` config port in Master-shard server.ini
    - 11002: as `[STEAM] authentication_port` config port in Master-shard server.ini
    - 11003: as `[STEAM] master_server_port` config port in Caves-shard server.ini
    - 11004: as `[STEAM] authentication_port` config port in Caves-shard server.ini
    - 11005: as `[SHARD] master_port` config port in cluster.ini, marked as Primary port

4. Change Caves-shard server.ini id from big number to 2 `[SHARD] id = 2`
5. Change `bind_ip` startup options and *.ini changes to `0.0.0.0`, not sure if needed but I did that just in case

Generally I referred to the configurations made in this docker: https://github.com/ich777/docker-steamcmd-server/tree/dontstarve
As I used that before without issues.

### Install logs

[Pterodactyl-Wings docker has no sh or bash installed, unable to run any command]

**Comment by gOOvER** [comment]
feel free to provide a PR, to fix this issue,

**Comment by QuintenQVD0** [comment]
A game that needs 7 ports, thats bad but oké. You clearly have fixt it so feel free to make 1 pr with all changes and the config parser auto setting all variables in the .ini file

**Comment by parkervcp** [comment]
You only need a single port the primary server proxies all connections to the shards.

**Comment by parkervcp** [comment]
@DatCaptainHorse I got this working with a single port and the 64 bit with minimal changes. All the other values were stock.

I am still validating my changes but You should also only need a single port.

**Comment by parkervcp** [comment]
If you could try #2044 @DatCaptainHorse

**Comment by DatCaptainHorse** [comment]
@parkervcp

Tested the PR egg with fresh install, player transfer to Caves works 👍
Closing as fixed!
