### ISSUE TITLE
[Install Bug]: <Egg Name>

### ISSUE THREAD

**Issue by Partymann2000** [parkervcp/eggs#2036]
### Panel Version

latest

### Wings Version

latest

### Service

eggs/game_eggs/steamcmd_servers/truck-simulator/euro-truck-simulator2/

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

When he asks me in the Consdole to enter my Steam Guard code and I enter it nothing happens

### Actual Behavior

Server gos offline

### Steps To Reproduce

Normal install

### Install logs

https://pteropaste.com/r98hdp

**Comment by QuintenQVD0** [comment]
The console is non interactive. Steam guard must be off for it to work. Just like almost every steam game that needs auth with a real user.

**Comment by QuintenQVD0** [comment]
You can always try loggin in as anonymous and no password ( you will edit the variable regex to allow that) and the  generate the game token for stram with your own account

**Comment by Partymann2000** [comment]
> You can always try loggin in as anonymous and no password ( you will edit the variable regex to allow that) and the generate the game token for stram with your own account

what you mean with regex

**Comment by QuintenQVD0** [comment]
> > You can always try loggin in as anonymous and no password ( you will edit the variable regex to allow that) and the generate the game token for stram with your own account
> 
> what you mean with regex

There is validation on the steam password varianle field that it can not be empty.

**Comment by gOOvER** [comment]
Steam Username and password are notr needed and both variables should be removed
