### ISSUE TITLE
[Bug]: ECO - Invalid rule for "Public Server" variable

### ISSUE THREAD

**Issue by szentigrad3** [parkervcp/eggs#2037]
### Panel Version

1.10.1

### Wings Version

1.7.0

### Service

eco

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server

### Actual Behavior

Can't install server with new eco egg > https://i.imgur.com/bE4On13.png

### Steps To Reproduce

install the server

### Install logs

N/A

**Comment by QuintenQVD0** [comment]
Is this some sort of joke?

1. Your panel and wings are not up to date
2. You did not provide install logs
3. The url to the image does not work

**Comment by lilkingjr1** [comment]
@gOOvER I think the panel forces the `boolean` rule to only return 1 or 0 from the drop down box, so `in:true,false` invalidates it.

@szentigrad3 Try removing `|in:true,false` from the "Public Server" startup variable by editing the egg. Make sure it is set correctly for the server and try again.

**Comment by Northwave** [comment]
The Image works and says the Public server variable must be set either to true or false. Maybe that’s the issue ?

**Comment by lilkingjr1** [comment]
If it explicitly needs "true" and "false", the following should be used instead: `required|string|in:true,false`

**Comment by QuintenQVD0** [comment]
The in:true,false also now has the same toggle layout (switch) as the boolean validation

**Comment by lilkingjr1** [comment]
@QuintenQVD0 Ahh, so just `boolean` needs to be removed? (I think that is forcing it to `1` and `0`)

**Comment by QuintenQVD0** [comment]
Boolean is 0 or 1 and gets converted to that switch
The rule in:true,false also gets converted to that switch but then has a  value of true or false

**Comment by szentigrad3** [comment]
installed now and getting this error now >
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Error Event [f1f497c2-c81f-4721-ac52-be3fed816431]: environment/docker: failed to pull "ghcr.io/parkervcp/steamcmd:dotnet" image for server: Error response from daemon: Head "https://ghcr.io/v2/parkervcp/steamcmd/manifests/dotnet": unauthorized

**Comment by lilkingjr1** [comment]
@parkervcp The `steamcmd` package doesn't seem to be public somehow?...
https://ghcr.io/parkervcp/games is reachable.
https://ghcr.io/parkervcp/steamcmd is not.

**Comment by QuintenQVD0** [comment]
> @parkervcp The `steamcmd` yolk package doesn't seem to be public somehow?... https://ghcr.io/parkervcp/games is reachable. https://ghcr.io/parkervcp/steamcmd is not.

New ghcr packages always come by default at private

**Comment by QuintenQVD0** [comment]
> installed now and getting this error now > [Pterodactyl Daemon]: Finished pulling Docker container image container@pterodactyl~ Error Event [f1f497c2-c81f-4721-ac52-be3fed816431]: environment/docker: failed to pull "ghcr.io/parkervcp/steamcmd:dotnet" image for server: Error response from daemon: Head "https://ghcr.io/v2/parkervcp/steamcmd/manifests/dotnet": unauthorized

It is now public

**Comment by QuintenQVD0** [comment]
@Northwave please test out ^^^
