### ISSUE TITLE
Velocity Proxy For Minecraft

### ISSUE THREAD

**Issue by ConflictKingdoms** [parkervcp/eggs#204]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc)
Minecraft
Does this expand an already existing service: Y/N
Y
Link to game: (Ex. minecraft.net/factorio.com/etc)
https://forums.spongepowered.org/t/velocity-the-modern-minecraft-proxy/25426
Links for server downloads: 
https://www.velocitypowered.com/downloads
Links for install steps/docs:
https://docs.velocitypowered.com/en/latest/

**Comment by newbie029** [comment]
+1
