### ISSUE TITLE
[Egg Request]: Assetto Corsa with Server Manager integration

### ISSUE THREAD

**Issue by MaxPainNL** [parkervcp/eggs#2043]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.racedepartment.com/downloads/ac-server-manager.25683/

### Links for the download

https://github.com/JustaPenguin/assetto-server-manager/releases

### Links for the install docs

https://github.com/JustaPenguin/assetto-server-manager

**Comment by MaxPainNL** [comment]
There is already an Assetto Corsa egg in this Github repo. So using that as a base with integration for server manager would be great. Would also be nice that I can use the premium Server Manager to host multiple Assetto Corsa server in the same installation.

**Comment by MaxPainNL** [comment]
There is already and Assetto Corsa egg. But using the server manager to manage the server would be great. I also want to use Server Manager Premium so I can run multiple Assetto Corsa servers in the same installation.

**Comment by QuintenQVD0** [comment]
This project last commit was 1 year ago and most 2. It looks a litte dead

**Comment by QuintenQVD0** [comment]
and as goover pointed out. it is max 1 game a docker container

**Comment by gOOvER** [comment]
a complete new image is needed with steamcmd, nodejs and go

**Comment by QuintenQVD0** [comment]
the have prebuild bins so normaly then go is not needed

**Comment by QuintenQVD0** [comment]
I will not add this as the project last commit was  1.5 years ago.

**Comment by MrHtgreen** [comment]
> There is already and Assetto Corsa egg. But using the server manager to manage the server would be great. I also want to use Server Manager Premium so I can run multiple Assetto Corsa servers in the same installation.

Hi mate, I was actually in the same boat but I have edited the standard egg to download and install server-manager 1.7.9 and a working config that I made, don't forget to open all three ports 8772 8081 9600

https://www.dropbox.com/s/b50ux0pklrj137a/egg-assetto-corsa.json?dl=0

**Comment by Nrde** [comment]
Just a comment about ACSM. V. 1.x (latest is/was 1.79). That is the open source version which was last updated some years ago. 

The current version, updated regularly, is v. 2.x (latest as of writing this update is 2/2024) is closed source, paid software allowing multiple servers running on the same machine. https://emperorservers.com/products/assetto-corsa-server-manager

You can either self-host it or pay for emperor to host it.

The current version does not differ much from the old one, only the ports used as there are multiple servers so more ports need to be open. ACSM handles starting assetto server binaries.
