### ISSUE TITLE
[Egg Request]: Icarus

### ISSUE THREAD

**Issue by 60plus** [parkervcp/eggs#2045]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1149460/ICARUS/

### Links for the download

https://github.com/RocketWerkz/IcarusDedicatedServer

### Links for the install docs

https://github.com/RocketWerkz/IcarusDedicatedServer/wiki/Server-Setup

**Comment by parkervcp** [comment]
https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/icarus

**Comment by 60plus** [comment]
thank you
