### ISSUE TITLE
Battlefield Hardline

### ISSUE THREAD

**Issue by icedmoca** [parkervcp/eggs#205]
Service: Battlefield Hardline

Does this expand an already existing service: not sure

Link to game: http://battlelog.battlefield.com/bfh/

Links for server downloads: I don't know where to find the server downloads.. That's why I'm requesting.

Links for install steps/docs: ..

**Comment by parkervcp** [comment]
For all the servers software out there I don't trust a single one I have found.

EA only allows official hosts to run their servers for rent. I won't touch this in any way.

**Comment by icedmoca** [comment]
Good to know! Thankyou.
