### ISSUE TITLE
[Egg Request]: Apache Web Server

### ISSUE THREAD

**Issue by HyperfireRS** [parkervcp/eggs#2050]
### Does this expand an already existing service

Yes

### Link to a game or software

https://httpd.apache.org/

### Links for the download

https://httpd.apache.org/download.cgi

### Links for the install docs

https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=115522329#content/view/115522329 I think

**Comment by gOOvER** [comment]
Ptero is not for webhosting, so it will never happend sich an egg

**Comment by QuintenQVD0** [comment]
There is no support for webhosting. Pterodactyl is not made for that.

**Comment by HyperfireRS** [comment]
But why do you offer something called webhost-egg then skull

**Comment by lilkingjr1** [comment]
@HyperfireRS We don't.
![Capture](https://user-images.githubusercontent.com/4533989/212580475-72c9c9a1-9c90-4ace-bbad-608c2f9bc386.PNG)

**Comment by HyperfireRS** [comment]
Holy shit I'm dumb

Sorry for wasting your time I was legit on the wrong repo

**Comment by gOOvER** [comment]
can be closed
