### ISSUE TITLE
[Install Bug]: tModLoader

### ISSUE THREAD

**Issue by HerrSammyDE** [parkervcp/eggs#2051]
### Panel Version

1.10.3

### Wings Version

1.7.2

### Service

[terraria/tmodloader](https://github.com/parkervcp/eggs/tree/master/game_eggs/terraria/tmodloader)

### Modified

No, I did not modify the egg

### Expected Behavior

The version I selected cannot be installed, in this case `0.11.7.6`.

### Actual Behavior

The newest version is installed, due to an error in the installation's script - see screenshot:

![chrome_smYLhsj5rj](https://user-images.githubusercontent.com/38103916/211598116-afb126d1-3282-4a1d-8114-1b34b063dc30.png)

Error: The older tModLoader versions were called different then than now!

### Steps To Reproduce

Select the version `0.11.7.6` or `v0.11.7.6` and try to install it, you will get the latest version.

### Install logs

https://ptero.co/evidedaliq.properties

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> 
> 1.10.3
> ### Wings Version
> 
> 1.7.2
> ### Service
> 
> [terraria/tmodloader](https://github.com/parkervcp/eggs/tree/master/game_eggs/terraria/tmodloader)
> ### Modified
> 
> No, I did not modify the egg
> ### Expected Behavior
> 
> The version I selected cannot be installed, in this case `0.11.7.6`.
> ### Actual Behavior
> 
> The newest version is installed, due to an error in the installation's script - see screenshot:
> 
> ![chrome_smYLhsj5rj](https://user-images.githubusercontent.com/38103916/211598116-afb126d1-3282-4a1d-8114-1b34b063dc30.png)
> 
> Error: The older tModLoader versions were called different then than now!
> ### Steps To Reproduce
> 
> Select the version `0.11.7.6` or `v0.11.7.6` and try to install it, you will get the latest version.
> ### Install logs
> 
> https://ptero.co/evidedaliq.properties

ofc , that version is from May 29, 2020. The egg is not made to run that

**Comment by HerrSammyDE** [comment]
> > ### Panel Version
> > 1.10.3
> > ### Wings Version
> > 1.7.2
> > ### Service
> > [terraria/tmodloader](https://github.com/parkervcp/eggs/tree/master/game_eggs/terraria/tmodloader)
> > ### Modified
> > No, I did not modify the egg
> > ### Expected Behavior
> > The version I selected cannot be installed, in this case `0.11.7.6`.
> > ### Actual Behavior
> > The newest version is installed, due to an error in the installation's script - see screenshot:
> > ![chrome_smYLhsj5rj](https://user-images.githubusercontent.com/38103916/211598116-afb126d1-3282-4a1d-8114-1b34b063dc30.png)
> > Error: The older tModLoader versions were called different then than now!
> > ### Steps To Reproduce
> > Select the version `0.11.7.6` or `v0.11.7.6` and try to install it, you will get the latest version.
> > ### Install logs
> > https://ptero.co/evidedaliq.properties
> 
> ofc , that version is from May 29, 2020. The egg is not made to run that

Could it be optimized for that?

**Comment by QuintenQVD0** [comment]
> > > ### Panel Version
> > > 1.10.3
> > > ### Wings Version
> > > 1.7.2
> > > ### Service
> > > [terraria/tmodloader](https://github.com/parkervcp/eggs/tree/master/game_eggs/terraria/tmodloader)
> > > ### Modified
> > > No, I did not modify the egg
> > > ### Expected Behavior
> > > The version I selected cannot be installed, in this case `0.11.7.6`.
> > > ### Actual Behavior
> > > The newest version is installed, due to an error in the installation's script - see screenshot:
> > > ![chrome_smYLhsj5rj](https://user-images.githubusercontent.com/38103916/211598116-afb126d1-3282-4a1d-8114-1b34b063dc30.png)
> > > Error: The older tModLoader versions were called different then than now!
> > > ### Steps To Reproduce
> > > Select the version `0.11.7.6` or `v0.11.7.6` and try to install it, you will get the latest version.
> > > ### Install logs
> > > https://ptero.co/evidedaliq.properties
> > 
> > 
> > ofc , that version is from May 29, 2020. The egg is not made to run that
> 
> Could it be optimized for that?

I see no need to support a almost 3 year old version.

**Comment by HerrSammyDE** [comment]
> > > > ### Panel Version
> > > > 1.10.3
> > > > ### Wings Version
> > > > 1.7.2
> > > > ### Service
> > > > [terraria/tmodloader](https://github.com/parkervcp/eggs/tree/master/game_eggs/terraria/tmodloader)
> > > > ### Modified
> > > > No, I did not modify the egg
> > > > ### Expected Behavior
> > > > The version I selected cannot be installed, in this case `0.11.7.6`.
> > > > ### Actual Behavior
> > > > The newest version is installed, due to an error in the installation's script - see screenshot:
> > > > ![chrome_smYLhsj5rj](https://user-images.githubusercontent.com/38103916/211598116-afb126d1-3282-4a1d-8114-1b34b063dc30.png)
> > > > Error: The older tModLoader versions were called different then than now!
> > > > ### Steps To Reproduce
> > > > Select the version `0.11.7.6` or `v0.11.7.6` and try to install it, you will get the latest version.
> > > > ### Install logs
> > > > https://ptero.co/evidedaliq.properties
> > > 
> > > 
> > > ofc , that version is from May 29, 2020. The egg is not made to run that
> > 
> > 
> > Could it be optimized for that?
> 
> I see no need to support a almost 3 year old version.

Apparently there are still many mods for this that don't exist in 1.4 yet, according to some of our customers. I'm not so in it myself, so I can't make a firm statement about it unfortunately.

**Comment by QuintenQVD0** [comment]
> Select the version `0.11.7.6` or `v0.11.7.6` and try to install it, you will get the latest version.

then add a match variable and use that in the install script. Also you would need a other image.

**Comment by gOOvER** [comment]
> Apparently there are still many mods for this that don't exist in 1.4 yet, according to some of our customers. I'm not so in it myself, so I can't make a firm statement about it unfortunately.

You are a hoster, so you should be able to add this yourself, because you get paid.

btw: Ptero and Wings are not update

**Comment by HerrSammyDE** [comment]
> 
> > Apparently there are still many mods for this that don't exist in 1.4 yet, according to some of our customers. I'm not so in it myself, so I can't make a firm statement about it unfortunately.
> 
> You are a hoster, so you should be able to add this yourself, because you get paid.
> 
> btw: Ptero and Wings are not update
> 

Just because I'm a hoster doesn't mean I have to know anything about it, does it?

If I was familiar with it, I certainly wouldn't have opened this issue. Please think before you write something!

**Comment by gOOvER** [comment]
> > 
> > > Apparently there are still many mods for this that don't exist in 1.4 yet, according to some of our customers. I'm not so in it myself, so I can't make a firm statement about it unfortunately.
> > 
> > You are a hoster, so you should be able to add this yourself, because you get paid.
> > 
> > btw: Ptero and Wings are not update
> > 
> 
> Just because I'm a hoster doesn't mean I have to know anything about it, does it?
> 
> If I was familiar with it, I certainly wouldn't have opened this issue. Please think before you write something!


You want a big change and as hoster you can pay someone to make this for you.

i see it a little differently. personally, i find it a little cheeky to ask for a free service here, if you earn money yourself then with it.

**Comment by QuintenQVD0** [comment]
We have no intention to add support for a 3 year old version. All versions for the last year should work. If you need support for that old of a version then you will have to make / edit a egg yourself
