### ISSUE TITLE
[Egg Request]: Assetto Corsa (Freeroam + AI)

### ISSUE THREAD

**Issue by MaxPainNL** [parkervcp/eggs#2052]
### Does this expand an already existing service

No

### Link to a game or software

https://assettoserver.org/

### Links for the download

https://github.com/compujuckel/AssettoServer/releases

### Links for the install docs

https://github.com/compujuckel/AssettoServer

**Comment by MaxPainNL** [comment]
Can somebody help me out with this?

**Comment by QuintenQVD0** [comment]
> Can somebody help me out with this?

Does this need anything else then just dotnet and a download binary?

**Comment by Epicsadface** [comment]
> Does this need anything else then just dotnet and a download binary?

Not the original requester but It should only need dotnet, specifically ASP.NET 6.

It also requires the base assetto server. It modifies a few files and replaces the main "acserver" launcher.

Hope this helps!

**Comment by MaxPainNL** [comment]
Thanks Epicsadface for your reply. I hope someone can make an egg that I can test.
