### ISSUE TITLE
[Egg Request]: ToolJet

### ISSUE THREAD

**Issue by BeeTwenty** [parkervcp/eggs#2053]
### Does this expand an already existing service

No

### Link to a game or software

https://www.tooljet.com/

### Links for the download

https://docs.tooljet.com/docs/setup/

### Links for the install docs

https://docs.tooljet.com/docs/setup/

**Comment by gOOvER** [comment]
I think, thats not possible with Petro, because you need a lot of images.

you cant use the Docker iamges allready provided. I would reccoment docker compose or Portainer for this, but Petro is the wrong solution

**Comment by QuintenQVD0** [comment]
Not possible as it needs more than 1 container
