### ISSUE TITLE
[Install Bug]: egg-curseforge-generic

### ISSUE THREAD

**Issue by Loci2021** [parkervcp/eggs#2057]
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

minecraft/egg-curseforge-generic

### Modified

No, I did not modify the egg

### Expected Behavior

I expect that i can install the server and can play on in.

### Actual Behavior

I installed the server and in the instalation a error happend.

### Steps To Reproduce

Step 1: I set the modpack id and the API Key.
Step 2: I install the server.
Step 3: Then the error happend that shows in the file below.
[logs.txt](https://github.com/parkervcp/eggs/files/10415405/logs.txt)

### Install logs

https://pteropaste.com/crrwlf/

**Comment by parkervcp** [comment]
I am looking at this now. 

What modpack are you installing here?

**Comment by Loci2021** [comment]
Im installing the Modpack "ATM 6 to the Sky" With the modpack ID: 442246

**Comment by parkervcp** [comment]
there is a known issue with the ATM packs due to them shipping an updated format for modpacks. I have no worked with it and have no updated the egg.

The current work around is to just upload the files yourself.

**Comment by Loci2021** [comment]
Oh okay, then i try it this way thanks.
