### ISSUE TITLE
FiveM install bug

### ISSUE THREAD

**Issue by KartoniarzEssa** [parkervcp/eggs#2058]
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

Curl download the files and proceed to the next install step

### Actual Behavior

This is error in console:
Running curl -sSL null -o null
Curl: (6) Could not resolve host: null

### Steps To Reproduce

Just install server nothing changed in startup, fivem version is recommended

### Install logs

https://pteropaste.com/pmbkk7

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> 
> 1.11.2
> ### Wings Version
> 
> 1.11.0
> ### Service
> 
> FiveM
> ### Modified
> 
> No, I did not modify the egg
> ### Expected Behavior
> 
> Curl download the files and proceed to the next install step
> ### Actual Behavior
> 
> This is error in console: Running curl -sSL null -o null Curl: (6) Could not resolve host: null
> ### Steps To Reproduce
> 
> Just install server nothing changed in startup, fivem version is recommended
> ### Install logs
> 
> https://pteropaste.com/pmbkk7

Please revoke that licence

**Comment by QuintenQVD0** [comment]
it is because of this: 
![afbeelding](https://user-images.githubusercontent.com/67589015/212466750-ab67eb32-d9e7-4bb9-9746-bb19667c8e33.png)

**Comment by gOOvER** [comment]
can confirm:

```
Cloning into '/tmp'...
remote: Enumerating objects: 1165, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 1165 (delta 93), reused 90 (delta 90), pack-reused 1045
Receiving objects: 100% (1165/1165), 3.60 MiB | 8.52 MiB/s, done.
Resolving deltas: 100% (544/544), done.
Running curl -sSL null -o null
curl: (6) Could not resolve host: null
Extracting fivem files
unknown filetype. Exiting
```

New install

**Comment by QuintenQVD0** [comment]
there changelog page is empty

**Comment by gOOvER** [comment]
> there changelog page is empty

404

They removed it

**Comment by QuintenQVD0** [comment]
for now just set the download_url to `https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/5848-4f71128ee48b07026d6d7229a60ebc5f40f2b9db/fx.tar.xz`

**Comment by QuintenQVD0** [comment]
@KartoniarzEssa please test out #2059
