### ISSUE TITLE
Conan Exiles not working with mods

### ISSUE THREAD

**Issue by adonisraul** [parkervcp/eggs#206]
Please fill out the information bellow and remove from the line up
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.13
Daemon Version: 0.6.12
Service: conan exiles
Modified: yes
Expected Behavior: the egg is perfect for vanilla servers but when i try use mods, is not working anymore
i try install manualy but no luck, could't validate the files

**Comment by Valiantiam** [comment]
Having the same issue here. 

I can get some mods to work, but then when one doesnt, and you try to remove the mod, the server crashes everytime you try to start it until you fully delete the server and re-deploy.

**Comment by NgLoader** [comment]
Backup your world and delete them, there data in your saves from the mod and when you try to remove the mod from the server they can't read the save again
