### ISSUE TITLE
[Bug]: Vanilla Bedrock ARM64

### ISSUE THREAD

**Issue by Arinautic** [parkervcp/eggs#2061]
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

I expected the server to start like normal and function.

### Actual Behavior

Server is running however nobody can join and it does not respond to anything. I am using the ARM version as my server uses ARM architecture.

Pterodactyl Console Output:

container@pterodactyl~ Server marked as starting...
:/home/container$ box64 ./bedrock_server
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:4
Params database has 14 entries
Box64 with Dynarec v0.2.1 53eee70c built on Jan  6 2023 07:19:37
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 27 Env var
Looking for ./bedrock_server
Rename process to "bedrock_server"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libcurl.so.4
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
NO LOG FILE! - setting up server logging...
[2023-01-14 12:46:54:217 INFO] Starting Server
[2023-01-14 12:46:54:218 INFO] Version 1.19.51.01
[2023-01-14 12:46:54:218 INFO] Session ID 6834d06e-b0e1-42b9-bf1c-1cc207bc261a
[2023-01-14 12:46:54:226 INFO] Level Name: Bedrock level
[2023-01-14 12:46:54:236 INFO] Game mode: 0 Survival
[2023-01-14 12:46:54:236 INFO] Difficulty: 1 EASY
Warning, call to __cxa_thread_atexit_impl(0x5a09560, 0x5b9d5b18, 0x6d16008) ignored
[2023-01-14 12:46:55:533 INFO] opening worlds/Bedrock level/db
refreshProtection(0x5d8ab010): 0x5d8ab000/0x7 (ret=-1/Permission denied)
Strange SIGSEGV with Access error on 0x5d8ab010 for 0x5d8ab010, db=0xffff37dc4ae0, prot=0x7 (old_addr=(nil))
refreshProtection(0x5d8ab010): 0x5d8ab000/0x7 (ret=-1/Permission denied)
refreshProtection(0x5d8ab010): 0x5d8ab000/0x7 (ret=-1/Permission denied)
Strange SIGSEGV with Access error on 0x5d8ab010 for 0x5d8ab010, db=0xffff37dc4ae0, prot=0x7 (old_addr=0x5d8ab010)
Error: unimplemented option 20094 in curl_easy_setopt
refreshProtection(0x5d8ab0dc): 0x5d8ab000/0x7 (ret=-1/Permission denied)
Strange SIGSEGV with Access error on 0x5d8ab0dc for 0x5d8ab0dc, db=0xffff37df8260, prot=0x7 (old_addr=(nil))
refreshProtection(0x5d8ab0dc): 0x5d8ab000/0x7 (ret=-1/Permission denied)
refreshProtection(0x5d8ab0dc): 0x5d8ab000/0x7 (ret=-1/Permission denied)
Strange SIGSEGV with Access error on 0x5d8ab0dc for 0x5d8ab0dc, db=0xffff37df8260, prot=0x7 (old_addr=0x5d8ab0dc)

### Steps To Reproduce

Step 1: Install Egg.
Step 2: Create Server using ARM Bedrock Egg.
Step 3: Start Server.

### Install logs

https://pteropaste.com/5s9qkk

**Comment by gOOvER** [comment]
looks like an emulator issue

**Comment by QuintenQVD0** [comment]
have you tryed reinstalling?

**Comment by QuintenQVD0** [comment]
works fine for me: 
![afbeelding](https://user-images.githubusercontent.com/67589015/212473986-e1394eea-cccf-4eb5-982e-c9f7411a0258.png)

**Comment by Arinautic** [comment]
> have you tryed reinstalling?

Yes, I’ve tried reinstalling.

**Comment by Notacod3r** [comment]
Works fine for me too. Also Quinten, thank you for the work on this egg for ARM.

**Comment by QuintenQVD0** [comment]
The curl easy stop methode was added to the emulator. The server works fine and is joinable. The console will not not spam that error anymore.
