### ISSUE TITLE
[Install Bug]: FiveM

### ISSUE THREAD

**Issue by SrStellar** [parkervcp/eggs#2064]
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

I was hoping that I only needed to put in the fivem and steam keys, and the download links for the fivem files.

### Actual Behavior

exec /bin/bash exec format error

### Steps To Reproduce

Step 1: Get the fivem egg from this repo.
Step 2: create the server, and configure it.
Step 3: Get the logs with the command: `tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/ */ /g' | cut - s -d' ' -f9) | nc pteropaste.com 99`

### Install logs

https://pteropaste.com/wy3fjx

**Comment by gOOvER** [comment]
use latest egg

**Comment by SrStellar** [comment]
but it's not working, not even with the updated egg.

**Comment by SrStellar** [comment]
https://pteropaste.com/mb1sij
same error

**Comment by gOOvER** [comment]
> [pteropaste.com/mb1sij](https://pteropaste.com/mb1sij) same error

FiveM is not for ARM64

**Comment by QuintenQVD0** [comment]
This egc does not support arm64 and works as intended.
