### ISSUE TITLE
[Egg Request]: Plex Media Server

### ISSUE THREAD

**Issue by TheRazvy** [parkervcp/eggs#2069]
### Does this expand an already existing service

Yes

### Link to a game or software

https://support.plex.tv/articles/200288586-installation/

### Links for the download

https://www.plex.tv/media-server-downloads/#plex-media-server

### Links for the install docs

https://support.plex.tv/articles/200288586-installation/

**Comment by QuintenQVD0** [comment]
Duplicate of https://github.com/parkervcp/eggs/issues/1117
