### ISSUE TITLE
[Install Bug]: FiveM

### ISSUE THREAD

**Issue by treekiller12** [parkervcp/eggs#2071]
### Panel Version

1.10.4

### Wings Version

1.11.0

### Service

gta/fivem

### Modified

No, I did not modify the egg

### Expected Behavior

install server, play

### Actual Behavior

[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
Digest: sha256:dc6a3ce00176c151177eae6ede00161d396334a1a404f80e32bd9056aed3055b 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
/entrypoint.sh: line 13: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

0

### Install logs

https://pteropaste.com/bn8o60

**Comment by gOOvER** [comment]
update your egg

**Comment by treekiller12** [comment]
i have latest egg

**Comment by gOOvER** [comment]
pls use discord for support; the egg works fine

**Comment by danny6167** [comment]
FiveM does not run on arm. Please use discord for support instead of opening issues here.
There is no bug with the egg.
