### ISSUE TITLE
[Install Bug]: Pocketmine

### ISSUE THREAD

**Issue by Jeanlx** [parkervcp/eggs#2082]
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

pocketmine installation

### Modified

No, I did not modify the egg

### Expected Behavior

Hello, what happens is that I'm trying to install a pocketmine server and it doesn't download some data, I see the error that it releases and it's the following

![image](https://user-images.githubusercontent.com/86314622/214207639-5ec60728-a639-425e-bc8d-ccbde3ec97d5.png)

### Console

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
Digest: sha256:1aa05ed709a704e2308096330b1b1568a2c44eba16efe293e23b3a89b5abc75b 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard --disable-ansi
/entrypoint.sh: line 13: ./bin/php7/bin/php: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...

### Steps To Reproduce

none

### Install logs

https://pteropaste.com/9hizt2/

**Comment by gOOvER** [comment]
Looks like, PHP dl url changed

https://jenkins.pmmp.io/job/PHP-8.0-Aggregate/lastSuccessfulBuild/artifact/PHP-8.0-Linux-x86_64-PM4.tar.gz

**Comment by QuintenQVD0** [comment]
+ not that it will fix your issue but your egg is also not up to date
