### ISSUE TITLE
[Egg Request]: Dyson Sphere Program w/ Nebula mod

### ISSUE THREAD

**Issue by kkoshelev** [parkervcp/eggs#2086]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/hubastard/nebula

### Links for the download

https://github.com/hubastard/nebula/wiki/Installation

### Links for the install docs

https://github.com/hubastard/nebula/pull/553

**Comment by gOOvER** [comment]
is atm not possible with ptero, because DSP is windows only and have no server. Also the Mod runs only for COOP and is not a server

@QuintenQVD0 can be closed, becasue there is no server and the mod is only for the client which needs a GUI

**Comment by QuintenQVD0** [comment]
Closed because a gui is needed

**Comment by MvBonin** [comment]
https://github.com/hubastard/nebula/wiki/Setup-Headless-Server

It seems possible to setup headless, without a gui..
Its not a real dedicated server but should be doable.

**Comment by QuintenQVD0** [comment]
I still note it. Can nlt promise if i can get it to workk.

**Comment by gOOvER** [comment]
you must own the Game to downloasd the Game.

**Comment by kkoshelev** [comment]
There is a docker version of the server. Can it be adopted to run on Pterodactyl?

https://github.com/WhyKickAmooCow/dsp-docker-server
