### ISSUE TITLE
[Bug]: ark_survival_evolved

### ISSUE THREAD

**Issue by TNT44777** [parkervcp/eggs#2087]
### Panel Version

1.11.2

### Wings Version

1.11.2 

### Service

eggs/game_eggs/steamcmd_servers/ark_survival_evolved

### Modified

No, I did not modify the egg

### Expected Behavior

The Server staying Online trough the Night.

### Actual Behavior

The Server is online but not showing up anywhere.

The Server is giving me the following Logs :

[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
Not updating game server as auto update was set to 0. Starting Server
:/home/container$ rmv() { echo -e "stopping server"; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c saveworld && rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD} -c DoExit; }; trap rmv 15; cd ShooterGame/Binaries/Linux && ./ShooterGameServer ${SERVER_MAP}?listen?SessionName="${SESSION_NAME}"?ServerPassword=${ARK_PASSWORD}?ServerAdminPassword=${ARK_ADMIN_PASSWORD}?Port=${SERVER_PORT}?RCONPort=${RCON_PORT}?QueryPort=${QUERY_PORT}?RCONEnabled=True$( [ "$BATTLE_EYE" == "1" ] || printf %s ' -NoBattlEye' ) -server ${ARGS} -log & until echo "waiting for rcon connection..."; rcon -t rcon -a 127.0.0.1:${RCON_PORT} -p ${ARK_ADMIN_PASSWORD}; do sleep 5; done
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
Shutdown handler: initalize.
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: rcon: read packet size: read tcp 127.0.0.1:59726->127.0.0.1:27020: i/o timeout
waiting for rcon connection...
cli: auth: rcon: rcon: read packet size: read tcp 127.0.0.1:37086->127.0.0.1:27020: i/o timeout
waiting for rcon connection...
Waiting commands for 127.0.0.1:27020 (or type :q to exit)
container@pterodactyl~ Server marked as running...

### Steps To Reproduce

Step 1 Go to Sleep
Step 2 Wake up
Step 3 Read Discord Messages
Step 4 Find the Server broken

This might be a joke but i dont know what might have caused this

### Install logs

I cant access them currently (I will post the link in the comments)

**Comment by Software-Noob** [comment]
The server is up and running. Should it not be reachable on the query port, you have not assigned all the required ports to the server and opened them in your firewall/router.

See the egg readme for additional information.

**Comment by TNT44777** [comment]
![image](https://user-images.githubusercontent.com/98651563/214390118-57fcedd1-7999-4c19-b638-5d7ce57d77db.png)
That can't be it I had these ports assigned and it worked for a time (I don't host this server locally so the firewall/router thing also cant be)

**Comment by Software-Noob** [comment]
The query port is closed on the IP and you have a very random primary port. Firewalls exist everywhere, not just on a local network.

It's not an egg issue once the server is running and rather an allocation/network one.

**Comment by TNT44777** [comment]
Ik but its not likely that it has something to do with the ports as i have hosted another ark server on it before (ill try giving it a new port)

**Comment by Software-Noob** [comment]
Just because something used to work by itself says nothing. The server is running.

The fact that the query port, which is used for connecting to the server is unreachable is a literal definition of a network issue. I've run a port scan and it's closed. Unreachable. No Bueno.

 I don't know why you're stubborn and trying to argue, instead of troubleshooting it to resolve your issue.
