### ISSUE TITLE
[Egg Request]: <Software> Wordpress

### ISSUE THREAD

**Issue by CrystalVortex** [parkervcp/eggs#2088]
### Does this expand an already existing service

Yes

### Link to a game or software

https://wordpress.org/download/

### Links for the download

https://wordpress.org/download/

### Links for the install docs

https://wordpress.org/documentation/article/how-to-install-wordpress/

**Comment by Boy132** [comment]
Duplicate of https://github.com/parkervcp/eggs/issues/1293#issuecomment-897142125
