### ISSUE TITLE
[Egg Request]: ChatGPT discord bot

### ISSUE THREAD

**Issue by OddPvP** [parkervcp/eggs#2089]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/rlphwkm/chatgpt-discord-bot

### Links for the download

https://github.com/rlphwkm/chatgpt-discord-bot/archive/refs/heads/main.zip

### Links for the install docs

Just install like any other bot

**Comment by devnote-dev** [comment]
You can run this with the NodeJS generic egg.

**Comment by yesBad** [comment]
> You can run this with the NodeJS generic egg.

Yeah you even said "install like any other bot", so it must not be hard! 🍿

**Comment by QuintenQVD0** [comment]
This can be ran with the generic nodejs egg
