### ISSUE TITLE
[Egg Request]: Pufferfish Minecraft Server

### ISSUE THREAD

**Issue by AIMBOT312** [parkervcp/eggs#2092]
### Does this expand an already existing service

Yes

### Link to a game or software

minecraft.net

### Links for the download

https://pufferfish.host/downloads

### Links for the install docs

https://github.com/pufferfish-gg/Pufferfish

**Comment by parkervcp** [comment]
I have called out that I am not adding any more minecraft servers to the repo many times.

Many eggs come with the ability to set a download link.

**Comment by QuintenQVD0** [comment]
Duplicate: #2013
