### ISSUE TITLE
[Egg Request]: BattleBit

### ISSUE THREAD

**Issue by Max62800** [parkervcp/eggs#2106]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.patreon.com/battlebit

### Links for the download

https://store.steampowered.com/app/671860/BattleBit_Remastered/

### Links for the install docs

https://steamcommunity.com/sharedfiles/filedetails/?id=1224952510

**Comment by Max62800** [comment]
https://discord.gg/p4xKJeATM3

**Comment by gOOvER** [comment]
This game is not official released and the server is only aviable on mega to download.

**Comment by Max62800** [comment]
> This game is not official released and the server is only aviable on mega to download. As long the server is not hosted on Github or is downloadble via SteamCMD, an egg is not possible.
> 
> Also; WINDOWS only

okay

**Comment by QuintenQVD0** [comment]
I am closing this for now. The moment the server releases on steamcmd or github and has a native linux version or runs with wine then you can reopen it or leave a comment.

**Comment by MaXx-62** [comment]
I reopen the post because the game is released on 06/15/2023 (tomorrow)

I spoke with the founder of the game who doesn't know pterodactyl, so maybe do something with him to get an egg

![image](https://github.com/parkervcp/eggs/assets/4140252/8f56e462-e1eb-4913-adad-a530e1f3dc44)

**Comment by danny6167** [comment]
There's no Linux server, and no plans to have one, so even if we can support this it would have to be through wine.

**Comment by QuintenQVD0** [comment]
> I reopen the post because the game is released on 15/06/2023 (tomorrow)
> 
> I spoke with the founder of the game who doesn't know pterodactyl, so maybe do something with him to get an egg
> 
> ![image](https://user-images.githubusercontent.com/4140252/245788862-8f56e462-e1eb-4913-adad-a530e1f3dc44.png)

if they release documentation on how to set it up and it runs with wine as it is sounds like it is windows only then we will have a look.

**Comment by mdangerf** [comment]
Is this enough for an egg?

https://github.com/BattleBit-Community-Servers/Battlebit-Community-Server-Launcher

**Comment by Bluscream** [comment]
Eggs for days: https://github.com/Royal-Multi-Gamers/eggs/tree/master/game_eggs/steamcmd_servers/battlebit_remastered
