### ISSUE TITLE
[egg request] arm64 version of GTA Connected

### ISSUE THREAD

**Issue by r2fo** [parkervcp/eggs#2111]
### Does this expand an already existing service

Yes

### Link to a game or software

gtaconnected.com

### Links for the download

https://gtaconnected.com/downloads/

### Links for the install docs

https://wiki.gtaconnected.com/GettingStarted

**Comment by QuintenQVD0** [comment]
I see no arm64 download

**Comment by gOOvER** [comment]
its Not arm64 compatible. this issue can be closed

**Comment by QuintenQVD0** [comment]
> its Not arm64 compatible. this issue can be closed

It is a 64 bit bin. Maybe the box64 emulator does. I need to test it.

**Comment by QuintenQVD0** [comment]
This does not work, I tryed
