### ISSUE TITLE
[Egg Request]: <Software/Game>

### ISSUE THREAD

**Issue by mastergamer0404** [parkervcp/eggs#2117]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.farming-simulator.com/about.php?lang=en&country=us&platform=pc

### Links for the download

https://eshop.giants-software.com/downloads.php

### Links for the install docs

https://www.ionos.com/digitalguide/server/know-how/fs-22-server/

**Comment by mastergamer0404** [comment]
I would like to see if this is even possible, i know they have a key requirement and all the files are already downloaded when you get your game. If its no possible that is fine. I am still working my way through understanding a lot of this stiff.

**Comment by gOOvER** [comment]
it Not possible

**Comment by RADICALAdrift** [comment]
> it Not possible

I'm trying with wings in host mode and still yet to get a result but still probably wont work, Will update my comment if im successful or not :)

**Comment by RADICALAdrift** [comment]
Well i was unsucessful with Wings in host mode as it still appears the connection is blocked for managing the server using it's webinterface which im guess is an issue with docker itself vs Pterodactyl/Wings or Wine though in host mode docker should be ignoring its network setup by Pterodactyl

**Comment by QuintenQVD0** [comment]
The server works with wine but hard binds to 127.0.0.1, so blocking all connections. I tried a VPN and a reverse proxy, it does not work. I even tried decompiling the binary. Still no luck. So as long as they don't fix their ip bind logic or give a variable to set the bind ip, this is not possible.
