### ISSUE TITLE
MariaDB egg request

### ISSUE THREAD

**Issue by lrmtheboss** [parkervcp/eggs#212]
Service: mariaDB

Does this expand an already existing service: n

Link to game: https://mariadb.org/

Links for server downloads: https://downloads.mariadb.org/

Links for install steps/docs: https://mariadb.com/kb/en/library/documentation/

**Comment by parkervcp** [comment]
database is not an existing service.

Just because there is a folder does not make it one.

Also mariadb is separate from postgres in about every way possible.

**Comment by lrmtheboss** [comment]
> database is not an existing service.
> 
> Just because there is a folder does not make it one.
> 
> Also mariadb is separate from postgres in about every way possible.

fixed
