### ISSUE TITLE
[Bug]: GTA SA:MP - Cannot stop server

### ISSUE THREAD

**Issue by sakulmore** [parkervcp/eggs#2120]
### Panel Version

1.11.3

### Wings Version

1.11.2

### Service

game_eggs/gta/samp/egg-s-a--m-p.json

### Modified

No, I did not modify the egg

### Expected Behavior

Nothing

### Actual Behavior

The stop command "^C" not working to stop the server. I think there have to be something like "pkill" or similar this. I changed it to "pkil samp03svr" and it's working, but when I have multiple servers, one server will stop all these servers.

So, "^C" stop command must be changed. What I have to write there? It's just saying "Server marked as stopping.".

### Steps To Reproduce

Install the server
Stop it or restart it (without killing it)

### Install logs

https://pteropaste.com/0qdgor

**Comment by QuintenQVD0** [comment]
> have

try setting the stop cmd to `^^C`
