### ISSUE TITLE
[Egg Request]: REd discord bot(needs update) 

### ISSUE THREAD

**Issue by Shriy1556k** [parkervcp/eggs#2122]
### Does this expand an already existing service

Yes

### Link to a game or software

https://discord.red

### Links for the download

idk 

### Links for the install docs

https://docs.discord.red/

**Comment by Shriy1556k** [comment]
I meant that the version that is there rn is old

**Comment by Shriy1556k** [comment]
there were some updates recently

**Comment by gOOvER** [comment]
> I meant that the version that is there rn is old

AGAIN, idk from WHERE YOU got your egg; the EGG in parker repo install latest Redbot !!!!!!!!!!!!

**Comment by gOOvER** [comment]
can be closed; problem is on his side.

Fresh install:

https://haste.goover.de/xezorikaka.sql

Lastes Bot installed

**Comment by QuintenQVD0** [comment]
I am closing this as it installs the latest version fine
