### ISSUE TITLE
[Egg Request]: MongoDB Community Edition (Free version)

### ISSUE THREAD

**Issue by louanfontenele** [parkervcp/eggs#2123]
### Does this expand an already existing service

No

### Link to a game or software

https://www.mongodb.com/

### Links for the download

https://www.mongodb.com/docs/manual/

### Links for the install docs

https://www.mongodb.com/docs/manual/administration/install-community/#std-label-install-community

**Comment by QuintenQVD0** [comment]
We already have a mongi db egg. https://github.com/parkervcp/eggs/tree/master/database/nosql/mongodb
