### ISSUE TITLE
[Install Bug]: minetest

### ISSUE THREAD

**Issue by Tealk** [parkervcp/eggs#2130]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

minetest

### Modified

No, I did not modify the egg

### Expected Behavior

install the serve

### Actual Behavior

installation faild with message:

```
-- *** Will build version 5.6.1 ***
CMake Error at CMakeLists.txt:113 (message):
  IrrlichtMt headers are required to build the server, but none found.
  The Minetest team has forked Irrlicht to make their own customizations.  It
  can be found here: https://github.com/minetest/irrlicht
  For example use: git clone --depth=1 https://github.com/minetest/irrlicht
  lib/irrlichtmt
-- Configuring incomplete, errors occurred!
```

### Steps To Reproduce

Inport the egg
set up server with version 5.6.1
click install

### Install logs

https://pteropaste.com/bj1yt6/

**Comment by gOOvER** [comment]
and which egg?

**Comment by QuintenQVD0** [comment]
> and which egg?

he filled it in: minetest

**Comment by gOOvER** [comment]
> > and which egg?
> 
> he filled it in: minetest [`master`/game_eggs/minetest](https://github.com/parkervcp/eggs/tree/master/game_eggs/minetest?rgh-link-date=2023-02-11T16%3A01%3A53Z)

yeah; changed it above :D Egg is old as hell; i bet its not really up2date

**Comment by Tealk** [comment]
sorry about the title I have left out

this is the only egg that I found, so I tried it.

**Comment by QuintenQVD0** [comment]
likly yes, they have up to date alpine builds so I think so

**Comment by QuintenQVD0** [comment]
there alpine bins are trash, lets try wine

**Comment by Tealk** [comment]
that is annoying, I hope that wine works

**Comment by gOOvER** [comment]
No need for Wine

https://wiki.minetest.net/Setting_up_a_server#Linux_2

Only egg needs an update

**Comment by QuintenQVD0** [comment]
I got it to work fine, only if you want a interactive console what is needed it is bugged out as hell. It does work

**Comment by QuintenQVD0** [comment]
as the minetestserver does not exists anymore and is now just minetest with the --server flag. then it works but if you use --terminal to make it interactive it does work but is buggy
