### ISSUE TITLE
[Install Bug]: PocketMine

### ISSUE THREAD

**Issue by ewn69** [parkervcp/eggs#2131]
### Panel Version

1.11.3

### Wings Version

1.11.2

### Service

PocketMine

### Modified

No, I did not modify the egg

### Expected Behavior

i expected pocketmine starts

### Actual Behavior

:/home/container$ ./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard --disable-ansi
/entrypoint.sh: line 13: ./bin/php7/bin/php: No such file or directory

### Steps To Reproduce

Just re-install your server then start it will happen

### Install logs

https://pteropaste.com/6xuwks

**Comment by parkervcp** [comment]
It's known that the pocketmine jenkins site is down. They have moved to a github release so people can download it and I am updating the egg now.
