### ISSUE TITLE
[Install Bug]: hlds (cs 1.6 / counter strike 1.6) Invalid game type 'cstrike' sepecified.

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#2135]
### Panel Version

1.6.1

### Wings Version

1.7.4

### Service

game_eggs/steamcmd_servers/hlds_server/rehlds/egg-custom-re-h-l-d-s-engine-game.json

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Install the server. Start without any problems.

### Actual Behavior

```
Finished pulling Docker container image
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1676336512
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '90' state is 0x6 after update job.
:/home/container$ ./hlds_run -console -game ${HLDS_GAME} -port ${SERVER_PORT} -sport ${VAC_PORT} +maxplayers ${MAX_PLAYERS} +map ${SRCDS_MAP} +ip 0.0.0.0 -strictportbind -norestart
Invalid game type 'cstrike' sepecified.
Tue Feb 14 18:29:39 CET 2023: Server Failed
```

### Steps To Reproduce

1. Install this egg
2. Change "Game Name" setting to "cstrike"
3. Install server

### Install logs

Provided in actual behavior.

**Comment by gOOvER** [comment]
update your panel; you are out of date not this Panel version is not supported

**Comment by BenasPaulikas** [comment]
Thank you I will update. However this isn't related to panel/wings version. This is something different.

I've tried multiple node locations and onlyplace where it's working is Helsinki, Finland. Other locations doesn't work.

**Comment by QuintenQVD0** [comment]
1. old panel
2. old wings
3. HLDS now needs an actual user that owns the game (app id 90) to download everything, so add the steam username and password to the needed variables with a new server, it will not work with reinstall or with 2FA on

**Comment by BenasPaulikas** [comment]
Thank you I will update. However this isn't related to panel/wings version(I read the changelog). This is something different.

Only in Helsinki, Finland it works. I'm trying many other locations across the globe and it's same error everywhere.

@QuintenQVD0 Thank you I will try to add user. Strange that it works without user in one specific region.

**Comment by QuintenQVD0** [comment]
> te. However this isn't related to panel/wings version(I re

if it still wont work then feel free to reopen this.

**Comment by BenasPaulikas** [comment]
@QuintenQVD0 thank you. After adding steam username/pass it works! Even tho I don't own that game.

**Comment by gOOvER** [comment]
> @QuintenQVD0 thank you. After adding steam username/pass it works! Even tho I don't own that game.

with this, it easier to ban cracked versions

**Comment by BenasPaulikas** [comment]
Does steam care about kids cracking cs 1.6 :D
I thought they swim in money from csgo

**Comment by gOOvER** [comment]
> Does steam really care about kids cracking cs 1.6 :D I thought they swim in money from csgo

Oh yes, the ban the server and all, which join it
