### ISSUE TITLE
[Egg Request]: BetterDiscordPanel

### ISSUE THREAD

**Issue by Exophobias** [parkervcp/eggs#2138]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/SanjaySunil/BetterDiscordPanel

### Links for the download

https://betterdiscordpanel.github.io/

### Links for the install docs

https://sanjaysunil.gitbook.io/betterdiscordpanel/

**Comment by parkervcp** [comment]
This could most likely be ran in the nodejs generic egg - https://github.com/parkervcp/eggs/tree/master/generic/nodejs
