### ISSUE TITLE
[Egg Request]: appwrite 

### ISSUE THREAD

**Issue by navin-hariharan** [parkervcp/eggs#2139]
### Does this expand an already existing service

Yes

### Link to a game or software

https://appwrite.io/

### Links for the download

https://github.com/appwrite/appwrite

### Links for the install docs

https://appwrite.io/docs

**Comment by parkervcp** [comment]
@navin-hariharan what service does this expand?

**Comment by diedyesterdaywashere** [comment]
> @navin-hariharan what service does this expand?

it's "Yes" by default, maybe he didn't mean to choose yes and just didn't see it idk

**Comment by parkervcp** [comment]
This also requires access to the docker socket to run anything their install says to do so it's a no anyways.
