### ISSUE TITLE
Teamspeak Server Update

### ISSUE THREAD

**Issue by JayJay1989** [parkervcp/eggs#214]
Service: (Ex. minecraft/factorio/etc) ts3server
Does this expand an already existing service: Y
Link to game: https://www.teamspeak.com/en/
Links for server downloads: https://www.teamspeak.com/en/downloads/#server
Links for install steps/docs: see original nest from pterodactyl

Information:
Is it possible to update/create a egg for teamspeak. When update to latest version (as of 3.8.0) the server wont boot cause something with glibc.

**Comment by JPylypiw** [comment]
```
./ts3server: Relink `/usr/lib/libgcc_s.so.1' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `memset'
Segmentation fault (core dumped)
```

These are the messages I get when booting the server. In TeamSpeak 3 Server Changelog they have written:

```
Important: This release requires GNU C library (glibc) 2.17 or later on Linux. If you need to
           check which version of glibc is installed on your system, you can use `ldd --version`,
           which usually comes with any glibc installation.
```

So I think the glibc Version is too low for starting the new Server version.
Maybe the Docker Container has to be rebuilt with the new glibc version.

**Comment by xion87** [comment]
i have the same issue i can't start the ts server after update

**Comment by xion87** [comment]
I solved use the ts3 edition for alpine https://files.teamspeak-services.com/releases/server/3.8.0/teamspeak3-server_linux_alpine-3.8.0.tar.bz2

**Comment by parkervcp** [comment]
using `quay.io/parkervcp/pterodactyl-images:base_debian` will resolve this issue. considering my repo isn't the one everyone gets this egg from it's more appropriate to post this on the panel repo.

As there is already an issue there and I have a PR for a fix I will close this.

**Comment by JPylypiw** [comment]
Thanks @xion87,
I used your suggestion in my Egg Version [JPylypiw/teamspeak-egg
](https://github.com/JPylypiw/teamspeak-egg)
It works properly with teamspeak 3.8.0.
