### ISSUE TITLE
[Bug]: <Egg Name>

### ISSUE THREAD

**Issue by Tzanou123** [parkervcp/eggs#2141]
### Panel Version

1.11.13

### Wings Version

1.11.4

### Service

7daytodie

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, Start, You should connect to it

### Actual Behavior

Hello,
I successfully installed pterodactyl and wing on my debian server who is installed home behind my box
I created a game server for 7 day to die get from https://github.com/parkervcp/eggs
From my box i create a tcp redirection to my server network ip (192.168.1.x) with the port set in the server config (26900)
Allocation is my server network ip  (192.168.1.x) with the port( 192.168.1.x:26900)
It started successfully but i cant reach the server from the game with my public address
I get nothing in the server log when i try to connect 
Do you have any idea ?
Thanks

ps: i try to run the minecraft vanilla server with 192.168.1.x and it s workin i can connect from my public ip on it ! So i think it coming from the sevendaytodie config

### Steps To Reproduce

Step 1 : Install eggs
Step 2 : Install server from egg
Step 3 : Allow port needed in firewall and port forwarding from the internet box  
Step 3 : Start the server
Step 4 : Try to connect to it

### Install logs

https://pteropaste.com/88679m

**Comment by gOOvER** [comment]
your Log is not from 7d2d.

please use Discord for support. thats Not really an Egg issue

**Comment by QuintenQVD0** [comment]
Come for this to the discord.

**Comment by Tzanou123** [comment]
@QuintenQVD0 i already posted on discord on help but no response :(

**Comment by gOOvER** [comment]
> @QuintenQVD0 i already posted on discord on help but no response :(

Its notr a Problem with the Egg ;) Check your Network, as you host at home

**Comment by Tzanou123** [comment]
Sorry to insist, but exact same configuration work for minecraft server ! its not mean the problem come for the egg ?

**Comment by gOOvER** [comment]
> Sorry to insist, but exact same configuration work for minecraft server ! its not mean the problem come for the egg ?

Its notr an egg issue; more an issue with your Network. But please go to discord

**Comment by Tzanou123** [comment]
I finally find out how to fix this !
I just had to add ServerDisabledNetworkProtocols to "" (-ServerDisabledNetworkProtocols="") for startup command in the egg config and i can greatly connect to the server !
It woulb be a great idea to add this instruction on the readme for peaople who run the server behind a box ! I can propose you an mr if you like the idea !
