### ISSUE TITLE
[Bug]: ARK Server not stopping properly

### ISSUE THREAD

**Issue by HellStormBeast** [parkervcp/eggs#2142]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

ARK

### Modified

No, I did not modify the egg

### Expected Behavior

Server saving world and stopping properly. 

### Actual Behavior

Server ist just marked as stopping and does not continue. I have to kill the Server to stop it. I got the Problem with 12 ARK Server plus a new Test Server I just created.

Addition:

If I run the command (DoExit) in the RCON Console, this is the Output:

> doexit
Exiting...
> /entrypoint.sh: line 73:    17 Aborted                 (core dumped) ./ShooterGameServer ${SERVER_MAP}?listen?SessionName="${SESSION_NAME}"?ServerPassword=${ARK_PASSWORD}?ServerAdminPassword=${ARK_ADMIN_PASSWORD}?Port=${SERVER_PORT}?RCONPort=${RCON_PORT}?QueryPort=${QUERY_PORT}?RCONEnabled=True?GameModIds=${MOD_ID}$( [ "$BATTLE_EYE" == "1" ] || printf %s ' -NoBattlEye' ) -server -automanagedmods ${ARGS} -log

### Steps To Reproduce

1. Install new ARK Server
2. Start Server and wait for it to finish
3. Stop Server

### Install logs

https://pteropaste.com/fcudh2

**Comment by gOOvER** [comment]
This is a known problem and as long https://github.com/pterodactyl/wings/pull/160 is not merged and published, the only solution is, to use ^^C as StopCMD

**Comment by QuintenQVD0** [comment]
> This is a known problem and as long [pterodactyl/wings#160](https://github.com/pterodactyl/wings/pull/160) is not merged and published, the only solution is, to use `^^C` as StopCMD

Didn't you remember mathew message? We should use a ^ followed by a kill signal

**Comment by gOOvER** [comment]
> > This is a known problem and as long [pterodactyl/wings#160](https://github.com/pterodactyl/wings/pull/160) is not merged and published, the only solution is, to use `^^C` as StopCMD
> 
> Didn't you remember mathew message? We should use a ^ followed by a kill signal

I remember, but all from Matthew dont work and ends in an error

**Comment by QuintenQVD0** [comment]
for now use `^^C` until we find a proper way to handle this so meaning merged pr from parker or some way to set the kill cmd send or that `^C` is fixt
