### ISSUE TITLE
caves not working on dedicated don't starve together server

### ISSUE THREAD

**Issue by mov51** [parkervcp/eggs#215]
Please fill out the information bellow and remove from the line up
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.13
Daemon Version: 0.6.12
Service: don't starve together
Modified: yes, I've added mods through the server mod installer

Expected Behavior: when moving a world configured in game with caves on to the server caves would be enabled.

Actual Behavior: caves are disabled.

Steps to Reproduce: 
create a world with the in game world configuration with caves enabled
copy the files from the local server to the dedicated one
open a sinkhole to the caves
find that the sinkhole is closed

**Comment by parkervcp** [comment]
So this is complicated as it looks like each part the main server and caves are actually 2 different servers.

I have poked at it a bit and am still working on it.

**Comment by mov51** [comment]
Awesome, glad to hear it. We have looked into it on our own but havent had any progress. Thanks for maintaining the egg :D

**Comment by Butain** [comment]
Yes, caves requires a separate server instance... i had this working a while back and it was a pain being able to get the two eggs to communicate with each other. I think it was mostly a NAT issue, but ever since my router died and I had to get a new one, I havn't been able to get it to work again. I'm still working on getting it working again. (wish i would have made a backup of my configs).

**Comment by mov51** [comment]
Ah dang, that doesn't sound fun. Hoping we can get  a standardized way to do it.

**Comment by parkervcp** [comment]
I think this may be easier if it's two eggs. I can play with that idea.

**Comment by Butain** [comment]
Got caves working again - pretty sure my issue was NAT related as i was running ubuntu on a windows server hyperv (VM)... 
I gave up trying to figure out how to tunnel through to the VM on that and installed ubuntu on an ssd and booted from that and everything went smoothly.

**Comment by ewanm89** [comment]
@Butain will the caves work with domain name instead of IP? Cause then Split-Horizon DNS might be a a better option than Hairpin NAT (internal clients get different IP address to external clients).

**Comment by parkervcp** [comment]
I am now fairly certain I got this working in a single server context. I will PR this in the morning.

**Comment by parkervcp** [comment]
@mov51 Can I ask that you look at this change. I finally figured out how to run a cave server with the master.

**Comment by mov51** [comment]
Can do! Thank you for the work on this :D

**Comment by mov51** [comment]
I believe I installed the egg correctly, however I am receiving [this error](https://pastebin.com/1p529eXk) in startup. It also took an abnormally long time to install the server (10 minutes).

**Comment by parkervcp** [comment]
You need to restart the daemon when you import an egg. 

Also steam installs can take some time with anonymous accounts.

**Comment by parkervcp** [comment]
I hadn't seen your response until after I had merged the changes.

**Comment by mov51** [comment]
Sorry about that, I've been disconnected for a few days and just say your mention today. And yeah, forgot about restarting wings. On the plus side I just confirmed that it works perfectly! Thank you for working on this, it has made my whole setup easier :D
