### ISSUE TITLE
[Bug]: Rage MP

### ISSUE THREAD

**Issue by JaredHuh** [parkervcp/eggs#2150]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

GTA V

### Modified

No, I did not modify the egg

### Expected Behavior

Successful server startup.

### Actual Behavior

https://pastebin.com/BeAJA3pE

### Steps To Reproduce

Import egg (https://github.com/parkervcp/eggs/tree/master/game_eggs/gta/ragemp).
Make server with it.
Try to start server.

### Install logs

https://pteropaste.com/qd57wxtrpt30/

**Comment by parkervcp** [comment]
Best guess is that you are trying to run this on a an arm server and ragemp doesn't support running on arm.

**Comment by QuintenQVD0** [comment]
> Best guess is that you are trying to run this on a an arm server and ragemp doesn't support running on arm.

Look at the pr. I have it working with box64

**Comment by JaredHuh** [comment]
Is there any way to run rage mp on arm?

**Comment by QuintenQVD0** [comment]
> Is there any way to run rage mp on arm?

Yes, get the eg out of pr, set it to the arm64 image and set the arch variable to arm64

**Comment by JaredHuh** [comment]
Can you please help with this?
I don't know much about this stuff.

**Comment by VladlenKaveev** [comment]
Hey there! @QuintenQVD0 @JaredHuh 

Maybe anyone know how to run GTA V RP with m1 chip? Maybe i can modify anti-cheat part for that?

I have an error with arm64 from EAC :(

**Comment by parkervcp** [comment]
> Maybe anyone know how to run GTA V RP with m1 chip? Maybe i can modify anti-cheat part for that?
> I have an error with arm64 from EAC :(

@VladenKaveev So far as I understand arm isn't supported for gta at all.
