### ISSUE TITLE
[Egg Request]: MediaWiki

### ISSUE THREAD

**Issue by Phoenix4O4** [parkervcp/eggs#2154]
### Does this expand an already existing service

No

### Link to a game or software

https://www.mediawiki.org/wiki/MediaWiki

### Links for the download

https://www.mediawiki.org/wiki/Download
https://github.com/bitnami/containers/tree/main/bitnami/mediawiki

### Links for the install docs

https://www.mediawiki.org/wiki/Manual:Installing_MediaWiki  https://github.com/bitnami/containers/blob/main/bitnami/mediawiki/README.md

**Comment by QuintenQVD0** [comment]
Falls under webhosting as it needs php and a webserver. Not supported c
