### ISSUE TITLE
[Egg Request]: Plesk

### ISSUE THREAD

**Issue by TZ0123** [parkervcp/eggs#2161]
### Does this expand an already existing service

No

### Link to a game or software

https://www.plesk.com/

### Links for the download

https://docs.plesk.com/de-DE/onyx/deployment-guide/installation-und-upgrade-von-plesk-auf-einem-einzelnen-server/1klickinstallation-von-plesk/installieren-von-plesk-f%C3%BCr-linux-mit-nur-einem-klick.76444/

### Links for the install docs

https://docs.plesk.com/de-DE/onyx/deployment-guide/erste-schritte.76607/

**Comment by QuintenQVD0** [comment]
webhosting is not supported and this can not run in pterodactyl

**Comment by gOOvER** [comment]
Plesk CANT be hosted in a docker Container :D
