### ISSUE TITLE
[Egg Request]: Generic php

### ISSUE THREAD

**Issue by Bestfast** [parkervcp/eggs#2169]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.php.net/

### Links for the download

https://www.php.net/downloads.php

### Links for the install docs

https://www.php.net/manual/en/install.unix.php

**Comment by QuintenQVD0** [comment]
Pterodactyl does not support webhosting.

**Comment by Bestfast** [comment]
I'm not talking about web hosting with PHP here. Many telegram bots use pooling along PHP libraries to do that, which doesn't require any type of web hosting. Refer to https://github.com/westacks/telebot and https://docs.madelineproto.xyzfor example of long pooling without any type of web hosting.

**Comment by QuintenQVD0** [comment]
I will leave the decision for Parker if he wants to reopen this
