### ISSUE TITLE
[Bug]: Satisfactory

### ISSUE THREAD

**Issue by uplandstatue** [parkervcp/eggs#2170]
### Panel Version

1.11.13

### Wings Version

1.11.4

### Service

Satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Per the documentation I should be able to use alternate ports and not be limited to 7777, 15777, and 15000 as long as the externally forwarded ports match the internal ports.

### Actual Behavior

If you change the Query port from 15777, external clients can see it online, but are unable to make changes or claim the server. While internal clients have no problem seeing it or claiming/configuring it.

If you change the Beacon or Game ports you will get an error like the attached. The difference between changing the beacon or game port is that if the game port is changed it will display the game port first, if the game port is default and the Beacon port is changed it will display that port.
![satisfactory network error](https://user-images.githubusercontent.com/51497978/222025561-0d45d70c-989f-4f1c-b1d3-e64335956272.PNG)

### Steps To Reproduce

Configure server, change allocations to anything besides default game ports.

 Let server install and come one.

Try connecting to server under changed query port.

External client will fail to claim server even if external and internal port match.
Internal Client will be able to claim.

Claim server.

External and internal clients will fail to connect to server, server will remain running.

Error displayed is from internal client trying to connect on non default ports.

![satisfactory network error](https://user-images.githubusercontent.com/51497978/222026094-57be4718-c4d2-4c79-97b1-382320744b1a.PNG)

### Install logs

https://pteropaste.com/v1kitce0jrm4

**Comment by gOOvER** [comment]
Wirks fine for me with different ports

**Comment by uplandstatue** [comment]
> Works fine for me with different ports

Which ports are you using if you don't mind me asking? I recently ran into an issue that makes me believe it may be my router not functioning correctly.

**Comment by lilkingjr1** [comment]
@uplandstatue I use 3 random ports that are at least 100 away from any other Satisfactory servers. I made sure they are allocated to the Ptero server (with the primary port being the game port) and are specified correctly in the startup params. I connect just fine using the Query port (note this is different from the primary game port).

**Comment by uplandstatue** [comment]
Thanks everyone, I was able to confirm it was a firewall issue.
