### ISSUE TITLE
[Bug]: valheim_bepinex

### ISSUE THREAD

**Issue by Sikksens** [parkervcp/eggs#2173]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

valheim

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Public server option not enabling by default

### Actual Behavior

Server is not listed as public, had to change startup command to `-public 1` instead of `-public {{PUBLIC_SERVER}}` for it to appear publicly.

### Steps To Reproduce

Imported latest egg
Enabled Public Server option
Started Server
Checked A2S on query port (2457)
No response

### Install logs

https://pteropaste.com/g7cv6my94srk

**Comment by gOOvER** [comment]
did you changed the Variable ?

**Comment by Software-Noob** [comment]
The environment variable is `PUBLIC`. The egg environment variable should be updated to match the startup parameters

**Comment by gOOvER** [comment]
variable is also wrong in Vanilla egg

**Comment by Sikksens** [comment]
Didn't even think to check the set variable, I see now, thanks will change my startup command to match.
![image](https://user-images.githubusercontent.com/15923337/222689993-9597340a-664b-4cc8-b6c4-cccac4a37cfb.png)
