### ISSUE TITLE
[Install Bug]: among-us--impostor-server

### ISSUE THREAD

**Issue by belac257** [parkervcp/eggs#2175]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

Among Us

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server
Installation complete successfully

### Actual Behavior

Server failed with error no URL
<img width="1223" alt="Screenshot 2023-03-04 at 9 24 51 pm" src="https://user-images.githubusercontent.com/123096905/222904365-fbebfc51-f246-4974-b41e-abe1b89e2094.png">

### Steps To Reproduce

Import Egg
Install on server

### Install logs

https://pteropaste.com/hz3m5ut3m0q9

**Comment by gOOvER** [comment]
imposter is a crap to keep it up2date

**Comment by QuintenQVD0** [comment]
I have no idea wy it faild, I am having a look rn
(and make it support arm64 as the dotnet image are now arm64 and amd64)

**Comment by gOOvER** [comment]
The dev change every release sth. The maintain of this egg is really annoying

**Comment by QuintenQVD0** [comment]
I love when shit works on the SSH connection to the machine but not in the install script

**Comment by belac257** [comment]
This has fixed the issue, thank you!
