### ISSUE TITLE
[Install Bug]: <Euro truck simulator 2 Steam CMD>

### ISSUE THREAD

**Issue by kodaren2** [parkervcp/eggs#2177]
### Panel Version

1.11.3

### Wings Version

1.7.4

### Service

Steam CMD/Euro truck simulator 2

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server and give the auth code and all it wants and start to play.

### Actual Behavior

Server started to install but suddenly stopped and wanted the authentication code and i could not type it in.

### Steps To Reproduce

1, Installed server
2, Waited for it to be done
3, Tried to type the authentication code

### Install logs

Can't find any

**Comment by parkervcp** [comment]
This is a known issue where you cannot use a steam auth code during the install as it will time out and you also cannot input anything during the install.
