### ISSUE TITLE
[Egg Request]: Mount & Blade II: Bannerlord

### ISSUE THREAD

**Issue by NWEmil** [parkervcp/eggs#2178]
### Does this expand an already existing service

No

### Link to a game or software

https://forums.taleworlds.com/index.php?threads/patch-notes-v1-1-0.457526/

### Links for the download

https://steamdb.info/app/1863440/depots/

### Links for the install docs

https://moddocs.bannerlord.com/multiplayer/hosting_server/

I made a very basic egg just to download the new Linux server files together with dotnet and have been trying out different startup lines. Unfortunately, their documentation isn't updated yet. I can't seem to find the right dotnet version and executable.

**Comment by QuintenQVD0** [comment]
![afbeelding](https://user-images.githubusercontent.com/67589015/222949331-9f21a9f4-06cb-422d-9629-e96917f13a8a.png)

for the linux version you need to own the game and have access to the beta branch: linux_test

**Comment by killertobyd** [comment]
The game still has a lot of bugs. You have to install a patch yourself almost every 2 weeks, otherwise the server crashes every 10 minutes :)
![Unbenannt](https://user-images.githubusercontent.com/96026375/222982753-137b4ed9-4261-4fd2-92f4-1c347d00cd63.PNG)

**Comment by CrafterDungin** [comment]
I got my Bannerlord egg from @killertobyd and runs very well.

**Comment by QuintenQVD0** [comment]
We can not make an egg for this as you have to own the game to be able to download the files. This can be reopend if someone is willing to make an egg that owns the game

**Comment by parkervcp** [comment]
This can stay open as it's still a request.

**Comment by Jonny-Havoc** [comment]
Here is new documentation for this: 
https://forums.taleworlds.com/index.php?threads/guide-dedicated-server-on-linux.454799/
Original is only required to generate private auth token

**Comment by Jonny-Havoc** [comment]
Do you think it would be be possible to have an egg using wine @QuintenQVD0 as shown in the forum link above?

**Comment by killertobyd** [comment]
Dotnet works perfectly. However, building an Egg for it that breaks after every update of TaleWorlds makes no sense. I run it myself with Dotnet and am allowed to insert the image and other missing files after every update.

**Comment by QuintenQVD0** [comment]
> Do you think it would be be possible to have an egg using wine @QuintenQVD0 as shown in the forum link above?

Should be. But I am on holidays

**Comment by WurstiNW** [comment]
Any news on this? :D

**Comment by QuintenQVD0** [comment]
> Any news on this? :D

I forgot abou this. I have a look when I can. If you do not need the game to be owned

**Comment by WurstiNW** [comment]
Well right now you need an auth code that you get from a command in the main game, but to start the Server you only need the Dedicated Server files

**Comment by QuintenQVD0** [comment]
> Well right now you need an auth code that you get from a command in the main game, but to start the Server you only need the Dedicated Server files and put the Auth Code into the start.bat that you get from this video
> 
> https://www.youtube.com/watch?v=9Hvuz12Bfzg

we don't run .bat files, everything has to be done in the startup cmd. there docs are a pay and some are outdated and spread everywhere

**Comment by WurstiNW** [comment]
Ahhh okay :D my bad

**Comment by QuintenQVD0** [comment]
> Ahhh okay :D my bad

and they ship the linux files with the windows download?

![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/4e09c597-c3e8-4da3-9e57-e2f7b9baec53)

**Comment by QuintenQVD0** [comment]
@WurstiNW Please try:

```json
{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v2",
        "update_url": null
    },
    "exported_at": "2023-08-15T19:16:50+02:00",
    "name": "Mount & Blade II: Bannerlord",
    "author": "josdekurk@gmail.com",
    "description": "A strategy\/action RPG. Create a character, engage in diplomacy, craft, trade and conquer new lands in a vast medieval sandbox. Raise armies to lead into battle and command and fight alongside your troops in massive real-time battles using a deep but intuitive skill-based combat system.",
    "features": null,
    "docker_images": {
        "ghcr.io\/parkervcp\/yolks:wine_latest": "ghcr.io\/parkervcp\/yolks:wine_latest"
    },
    "file_denylist": [],
    "startup": "cd \/home\/container\/bin\/Win64_Shipping_Server\/ && wine DedicatedCustomServer.Starter.exe \/port {{SERVER_PORT}}  \/dedicatedcustomserverauthtoken \"{{AUTH_TOKEN}}\" \/dedicatedcustomserverconfigfile tdm_config.txt _MODULES_*Native*Multiplayer*DedicatedCustomServerHelper*_MODULES_",
    "config": {
        "files": "{}",
        "startup": "{\r\n    \"done\": \"Custom Game server is ready! You can now enter console commands\"\r\n}",
        "logs": "{}",
        "stop": "^^C"
    },
    "scripts": {
        "installation": {
            "script": "#!\/bin\/bash\r\n# steamcmd Base Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\n# Image to install with is 'ghcr.io\/parkervcp\/installers:debian'\r\n\r\n\r\n\r\n# Install packages. Default packages below are not required if using our existing install image thus speeding up the install process.\r\n#apt -y update\r\n#apt -y --no-install-recommends install curl lib32gcc-s1 ca-certificates\r\n\r\n## just in case someone removed the defaults.\r\nif [[ \"${STEAM_USER}\" == \"\" ]] || [[ \"${STEAM_PASS}\" == \"\" ]]; then\r\n    echo -e \"steam user is not set.\\n\"\r\n    echo -e \"Using anonymous user.\\n\"\r\n    STEAM_USER=anonymous\r\n    STEAM_PASS=\"\"\r\n    STEAM_AUTH=\"\"\r\nelse\r\n    echo -e \"user set to ${STEAM_USER}\"\r\nfi\r\n\r\n## download and install steamcmd\r\ncd \/tmp\r\nmkdir -p \/mnt\/server\/steamcmd\r\ncurl -sSL -o steamcmd.tar.gz https:\/\/steamcdn-a.akamaihd.net\/client\/installer\/steamcmd_linux.tar.gz\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/steamcmd\r\nmkdir -p \/mnt\/server\/steamapps # Fix steamcmd disk write error when this folder is missing\r\ncd \/mnt\/server\/steamcmd\r\n\r\n# SteamCMD fails otherwise for some reason, even running as root.\r\n# This is changed at the end of the install process anyways.\r\nchown -R root:root \/mnt\r\nexport HOME=\/mnt\/server\r\n\r\n## install game using steamcmd\r\n.\/steamcmd.sh +force_install_dir \/mnt\/server +login ${STEAM_USER} ${STEAM_PASS} ${STEAM_AUTH} $( [[ \"${WINDOWS_INSTALL}\" == \"1\" ]] && printf %s '+@sSteamCmdForcePlatformType windows' ) +app_update ${SRCDS_APPID} $( [[ -z ${SRCDS_BETAID} ]] || printf %s \"-beta ${SRCDS_BETAID}\" ) $( [[ -z ${SRCDS_BETAPASS} ]] || printf %s \"-betapassword ${SRCDS_BETAPASS}\" ) ${INSTALL_FLAGS} validate +quit ## other flags may be needed depending on install. looking at you cs 1.6\r\n\r\n## set up 32 bit libraries\r\nmkdir -p \/mnt\/server\/.steam\/sdk32\r\ncp -v linux32\/steamclient.so ..\/.steam\/sdk32\/steamclient.so\r\n\r\n## set up 64 bit libraries\r\nmkdir -p \/mnt\/server\/.steam\/sdk64\r\ncp -v linux64\/steamclient.so ..\/.steam\/sdk64\/steamclient.so\r\n\r\n## add below your custom commands if needed\r\n\r\n## install end\r\necho \"-----------------------------------------\"\r\necho \"Installation completed...\"\r\necho \"-----------------------------------------\"",
            "container": "ghcr.io\/parkervcp\/installers:debian",
            "entrypoint": "bash"
        }
    },
    "variables": [
        {
            "name": "Windows",
            "description": "",
            "env_variable": "WINDOWS_INSTALL",
            "default_value": "1",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "App id",
            "description": "",
            "env_variable": "SRCDS_APPID",
            "default_value": "1863440",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string|in:1863440",
            "field_type": "text"
        },
        {
            "name": "Auto update",
            "description": "Auto update the server on restart.",
            "env_variable": "AUTO_UPDATE",
            "default_value": "1",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "[SYSTEM] WINEDEBUG",
            "description": "don't change this !!!",
            "env_variable": "WINEDEBUG",
            "default_value": "-all",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string|max:64",
            "field_type": "text"
        },
        {
            "name": "[SYSTEM] WINEARCH",
            "description": "",
            "env_variable": "WINEARCH",
            "default_value": "win64",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string|max:20",
            "field_type": "text"
        },
        {
            "name": "WINEPATH",
            "description": "",
            "env_variable": "WINEPATH",
            "default_value": "\/home\/container",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string|max:32",
            "field_type": "text"
        },
        {
            "name": "WINETRICKS_RUN",
            "description": "",
            "env_variable": "WINETRICKS_RUN",
            "default_value": "vcrun2019 dotnet472",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string|",
            "field_type": "text"
        },
        {
            "name": "Auth token",
            "description": "See: https:\/\/www.youtube.com\/watch?v=9Hvuz12Bfzg",
            "env_variable": "AUTH_TOKEN",
            "default_value": "",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|",
            "field_type": "text"
        }
    ]
}
```

the first start will take a lot of time

**Comment by WurstiNW** [comment]
I was able to host it on Ubuntu 22.04 with the Win64_Shipping_Server files yea, if thats what you mean

Thank you I will test it later :D

**Comment by WurstiNW** [comment]
So I have tested it

![image](https://github.com/parkervcp/eggs/assets/52246383/f7047e44-e02a-4c5b-ad97-39d21d011505)

This is basically what is shown repeatedly at the end of the process

**Comment by QuintenQVD0** [comment]
@WurstiNW Am I dreaming or did you post a message here that it did not work?

**Comment by WurstiNW** [comment]
Yea I posted one but I am changeing something as it mightve been on me :D

**Comment by QuintenQVD0** [comment]
> Yea I posted one but I am changeing something as it mightve been on me :D

the egg should have created the needed configs, set the ports and download the wintricks on first start

**Comment by QuintenQVD0** [comment]
@WurstiNW It looks like I messed up with something in the install script. one sec

**Comment by QuintenQVD0** [comment]
@WurstiNW I updated the egg, it should know downloads it default config in to the native multiplayer folder

**Comment by WurstiNW** [comment]
Alright I will set everything up again in ~2 hours as I also had an error on my side

**Comment by WurstiNW** [comment]
My host got Problems so it might get delayed, im sorry

**Comment by WurstiNW** [comment]
![image](https://github.com/parkervcp/eggs/assets/52246383/21c59da4-6606-412b-afce-04839ec38d89)
Thats where its stuck now for over 1 hour

**Comment by WurstiNW** [comment]
![image](https://github.com/parkervcp/eggs/assets/52246383/59c570f8-e67c-4174-81b4-b83bc7614959)
Update

**Comment by QuintenQVD0** [comment]
> ![image](https://user-images.githubusercontent.com/52246383/261673818-59c570f8-e67c-4174-81b4-b83bc7614959.png) Thats what I get now
> 
> Tho now it says its in installing state again for some reason, so I will give it another go after that

That is install faild. Post logs.

**Comment by WurstiNW** [comment]
https://pastebin.com/pJYD7c6j

Hope you meant these, sorry im fairly new :D

**Comment by WurstiNW** [comment]
Yea I updated it with the logs :D

**Comment by QuintenQVD0** [comment]
> Yea I updated it with the logs :D

Install looks fine. Can you have a look in the file manger if you can find that file?

**Comment by WurstiNW** [comment]
![image](https://github.com/parkervcp/eggs/assets/52246383/06b8d6d4-1c35-4a9a-a852-426388937bfd)

And I also cant find it inside the linux32 & linux64 folder on the panel

**Comment by QuintenQVD0** [comment]
> I cant find it inside the linux32 & linux64 folder on the panel nor inside the sdk32 and sdk64 folders
> 
> Nor with commands in terminal
> 
> Ill remove the link to the install logs for now as people could see my auth code :D

That is not where you should have looked

**Comment by WurstiNW** [comment]
Well a possible Error is that on Taleworlds it says you need to login with a proper steam account rather than an anonymous one, which is also a possible reason I find for the missing steamservice.so

**Comment by gOOvER** [comment]
> Well a possible Error is that on Taleworlds it says you need to login with a proper steam account rather than an anonymous one, which is also a possible reason I find for the missing steamservice.so

igonore all about steamservice.so. Thats not implemented yet in steamcmd

**Comment by WurstiNW** [comment]
Could it still be possible that its about having the anonymous account instead of my personal one?

**Comment by QuintenQVD0** [comment]
> Could it still be possible that its about having the anonymous account instead of my personal one?

No. Anonymous works fine.

**Comment by WurstiNW** [comment]
Alright so the problem was the Firewall Panel of my host on their website, i removed all opened ports and just allow "ALL" and now its working

**Comment by parkervcp** [comment]
My bad I didn't check who opened the issue

**Comment by WurstiNW** [comment]
Hello again :D Is it also possible to let the user change the Module without me having to change the startup commands / get an easy mod installation?
