### ISSUE TITLE
7 Days to Die

### ISSUE THREAD

**Issue by logmein345** [parkervcp/eggs#218]
Please fill out the information bellow and remove from the line up
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.13
Daemon Version: 0.6.12
Service: 7 Days to die
Modified: No

Expected Behavior:
Respect set server port.

Actual Behavior:
Still wants to bind to 26900 no matter what is set. Is this expected? other games respect setting the port.

Steps to Reproduce: 
Deploy a 7 days to die instance and if the port is not 26900 you can't connect.

**Comment by parkervcp** [comment]
This is due to the xml parsing not working. 

To fix the xml corruption issue I had to make it not try to edit the file.

**Comment by logmein345** [comment]
Ah ok I see. So that stuff has to be manually set after the container is deployed? Or is there a different way to specify? I have only started using the panel recently so just trying to figure it all out.

**Comment by parkervcp** [comment]
needs to be manually set for now.
