### ISSUE TITLE
[No deb available]: <Open TTD>

### ISSUE THREAD

**Issue by rhinotastic** [parkervcp/eggs#2185]
### Panel Version

1.11.3

### Wings Version

1.11.3

### Service

OpenTTD

### Modified

No, I did not modify the egg

### Expected Behavior

Installs the latest version of openTTD (version 13.0)

### Actual Behavior

Fails to download the openttd deb file.
Doesn't install openTTD

From looking at the egg it is due to trying to download a deb file from the CDN but there is none for version 13.0
openTTD uses tar.xz as the default linux package when releasing any versions and can take months (if at all) for a distro specific package to be made and available.

The Egg should probably be changed to look for and unpack:
"**_https://cdn.openttd.org/openttd-releases/${OPENTTD_VERSION}/openttd-${OPENTTD_VERSION}-linux-generic-amd64.tar.xz_**" 
As this is the standard release package for openTTD.

From checking the CDN the last deb release was 13.0RC1. (january 1st)
[/openttd-releases/13.0](https://cdn.openttd.org/openttd-releases/13.0/ )

### Steps To Reproduce

step 1. set to version 13.0 (latest)
step 2. install
step 3. see it hasn't installed anything due to no deb file available to be pulled.

### Install logs

NA

**Comment by parkervcp** [comment]
Have you updated to the latest version of the egg that was PR'd here - https://github.com/parkervcp/eggs/pull/2047

**Comment by QuintenQVD0** [comment]
> Have you updated to the latest version of the egg that was PR'd here - #2047

They stopped pushing .deb files. so the egg has to be rewritten to download the openttd-${OPENTTD_VERSION}-linux-generic-amd64.tar
