### ISSUE TITLE
Install failed with Forge Generic

### ISSUE THREAD

**Issue by JoshuaWalsh** [parkervcp/eggs#219]
Panel Version: 0.7.13
Daemon Version: 0.6.12
Service: Minecraft Forge Generic
Modified: Specified "https://minecraft.curseforge.com/projects/all-the-mods-3-remix" for MODPACK_URL

Expected Behavior: All The Mods 3: Remix should be installed successfully

Actual Behavior: 

```
  inflating: scripts/oredict/atm_oredict_chisel.zs
  inflating: scripts/oredict/atm_oredict_misc.zs
  inflating: scripts/oredict/atm_oredict_ores.zs
  inflating: scripts/oredict/atm_oredict_unidict.zs.unused
  inflating: scripts/oredict/atm_oredict_unify_metals.zs
  inflating: scripts/oredict/atm_oredict_wood.zs
   creating: scripts/recipeconflicts/
  inflating: scripts/recipeconflicts/atm_recipeconflicts_misc.zs
  inflating: scripts/recipeconflicts/atm_recipeconflicts_natura.zs
  inflating: scripts/recipeconflicts/atm_recipeconflicts_quark.zs
  inflating: scripts/recipeconflicts/atm_recipeconflicts_quark_rustic_planks.zs
  inflating: ServerStart.bat
  inflating: ServerStart.sh
  inflating: settings.cfg
-14.23.5.2825

-14.23.5.2825orge Version 1.12.2

-installer.jar -o installer.jar \nminecraftforge.net/maven/net/minecraftforge/forge/1.12.2
curl: (3) URL using bad/illegal format or missing URL
-universal.jar -O \nhttps://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2
curl: (3) URL using bad/illegal format or missing URL
Error: Unable to access jarfile installer.jar
mv: can't rename '*universal.jar': No such file or directory
rm: can't remove 'installer.jar': No such file or directory
```

Steps to Reproduce: (Step by step what to do to cause the issue)

1. Import the Forge Generic egg
2. Attempt to create an All The Mods 3: Remix server
3. Observe that installation fails

**Comment by parkervcp** [comment]
I have a better way to do this.

**Comment by parkervcp** [comment]
@JoshuaWalsh Check my new branch. It uses dos2unix.

**Comment by JoshuaWalsh** [comment]
Why not just use my PR, it uses dos2unix too? You don't need to `apk add dos2unix` since it's included by default in the installation image you use, `openjdk:8-alpine`.

**Comment by parkervcp** [comment]
I read the diff from my phone and it looked like you had done way more than use dos2unix. It's because you have the ## notes in there as well.

**Comment by parkervcp** [comment]
I thought you were trying to grep the /r/n in the file

**Comment by JoshuaWalsh** [comment]
Funny thing, I actually initially was grepping /r/n in the file because I didn't think `dos2unix` would be included with Alpine. But I never committed that change, even locally, because I realised that dos2unix was present. So you might be a little bit psychic?
