### ISSUE TITLE
[Bug]: ECO - Crash while loading Elixir Mods - Read only filesystem

### ISSUE THREAD

**Issue by scootz** [parkervcp/eggs#2191]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

game_eggs/steamcmd_servers/eco

### Modified

No, I did not modify the egg

### Expected Behavior

Expected Elixir Mods to work.

Game runs fine without the mod.  Tried running it on another linux box without pterodactyl/wings via steamcmd.  Installed the mod there and works flawlessly.  Trying to get the mods to work inside pterodactyl gives read only error.

### Actual Behavior

Server crashed with error Read-only file system : '/home/container\Configs\Mods'
[log_230317064914.log](https://github.com/parkervcp/eggs/files/10998719/log_230317064914.log)

### Steps To Reproduce

Install ECO egg, run server, close server down, unzip elixir mods into /home/container, run server, during start up, crashes with read only filesystem error.

### Install logs

https://pteropaste.com/q8kk74b1tkm2

**Comment by gOOvER** [comment]
Not an Egg issue. your Mod try to 2rite outside /Home/container

**Comment by gOOvER** [comment]
Next Problem; your Mod is Not compatible with latest Version of Eco and had over 1 year no update

**Comment by QuintenQVD0** [comment]
^^
