### ISSUE TITLE
[Egg Request]: Growtopia Private Server

### ISSUE THREAD

**Issue by vanevgt** [parkervcp/eggs#2196]
### Does this expand an already existing service

No

### Link to a game or software

https://www.growtopiagame.com/

### Links for the download

https://www.growtopiagame.com/

### Links for the install docs

*

**Comment by gOOvER** [comment]
you cant create Servers for this Mobile Game. 

Thats why you dont add some.installguides

**Comment by QuintenQVD0** [comment]
There is no dedicated server
