### ISSUE TITLE
[Bug]: gitea

### ISSUE THREAD

**Issue by MvBonin** [parkervcp/eggs#2200]
### Panel Version

1.11.2

### Wings Version

1.11.5

### Service

gitea

### Modified

No, I did not modify the egg

### Expected Behavior

I go to my account settings in gitea and add a ssh key.
Ssh key gets added to my account.

### Actual Behavior

When I try to add the key, I get the following error message:

`Cannot verify your SSH key: SSHKeyGenParsePublicKey: fail to parse public key: exec(641c36d9-2:SSHKeyGenParsePublicKey) failed: exit status 255() stdout: stderr: No user exists for uid 999 - No user exists for uid 999 `

### Steps To Reproduce

1. Click on your profile in gitea and then on settings.
2. Click on SSH / GPG Keys
3. Under Manage SSH Keys, click on add Key.
4. Add an email and a key
5. The error message appears, key doesn't get added

### Install logs

-

**Comment by QuintenQVD0** [comment]
> And how exactly do I do this? And could we add it to the egg somehow, so that it gets done with installation?

this is not done with the egg, this is done with mounts on the panel. If you can not then just don't use ssh keys for now

**Comment by QuintenQVD0** [comment]
I will close this as this is not egg releated but how pterodactyl containers work
