### ISSUE TITLE
[Bug]: Bastion Bot

### ISSUE THREAD

**Issue by marcoastor** [parkervcp/eggs#2207]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

Bastion Bot

### Modified

No, I did not modify the egg

### Expected Behavior

It would install successfully & start.

### Actual Behavior

```
:/home/container$ npm start
/entrypoint.sh: line 13:    15 Illegal instruction     (core dumped) mongod --fork --dbpath /home/container/mongodb/ --port 27017 --logpath /home/container/mongod.log
> bastion@10.10.0 start
> node .
[ERROR Tue Mar 28 2023 23:11:00 GMT+0200 (Central European Summer Time)]
Error [TokenMissing]: Request to use token, but token was unavailable to the client.
    at fetchRecommendedShardCount (/home/container/node_modules/discord.js/src/util/Util.js:69:21)
    at TesseractShardingManager.spawn (/home/container/node_modules/discord.js/src/sharding/ShardingManager.js:190:22)
    at file:///home/container/dist/index.js:12:9
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'TokenMissing'
}
Trace
    at file:///home/container/node_modules/@bastion/tesseract/dist/TesseractLogger.js:1:3445
[ERROR]
/entrypoint.sh: line 19: syntax error near unexpected token `('
/entrypoint.sh: line 19: `mongo --eval \"db.getSiblingDB('admin').shutdownServer()\'
```

### Steps To Reproduce

1 Install latest version of the BastionBot egg
2 Press start
3 See it not work

### Install logs

https://pteropaste.com/99ykdfd7wwtc/

**Comment by gOOvER** [comment]
use the latest egg

**Comment by Doldak** [comment]
same here and use latest egg....

**Comment by gOOvER** [comment]
> same here and use latest egg....

this error should be fix since a long time.
Ok found the problem:
Image is still not merged: https://github.com/parkervcp/yolks/pull/110

Since 3 Months. I hate this. @parkervcp must merge it, but it looks like, he dont want it. idk

**Comment by marcoastor** [comment]
Ok, so the only solution there is to wait for @parkervcp to update it?

**Comment by QuintenQVD0** [comment]
you are waiting for #2010 and the parkervcp/yolks#110 to be able to run this

**Comment by QuintenQVD0** [comment]
I got the mongodb error firxt. But they moved to .env file and removed rthe options to use system ENV. let me fix this

**Comment by QuintenQVD0** [comment]
@marcoastor Please test with ths egg:
https://github.com/parkervcp/eggs/pull/2010
and the docker image `quintenqvd/pterodactyl_images:temp_bastion`

**Comment by gOOvER** [comment]
> Illegal instruction

What CPU are you using?

This error:

`Illegal instruction`

is in 90% of all cases a too old CPU

**Comment by marcoastor** [comment]
Intel Celeron J4125

**Comment by gOOvER** [comment]
> Intel Celeron J4125

sorry to say, but your CPU is not supporterd. Upgrade your CPU.

`/entrypoint.sh: line 42:    67 Illegal instruction     (core dumped) mongod --eval "db.adminCommand({ "shutdown" : 1 })"`
tell you, that your CPU dont support an instruction used.

So this ticket can be closed @QuintenQVD0

**Comment by marcoastor** [comment]
My CPU is not very old, it is from late 2019 ([here](https://nanoreview.net/en/cpu/intel-celeron-j4125) you can check it) because even if it is a 1998 series (Intel Celeron) the J4125 model is from 2019, so I don't think that's the problem.

**Comment by gOOvER** [comment]
> My CPU is not very old, it is from late 2019 ([here](https://nanoreview.net/en/cpu/intel-celeron-j4125) you can check it) because even if it is a 1998 series (Intel Celeron) the J4125 model is from 2019, so I don't think that's the problem.

as i said; your CPU DONT !!!!!!! Support the instructions, which Mongo needs. 

So, its definitiv the problem of this weak CPU

**Comment by marcoastor** [comment]
Ok, and last question, would it be possible to use another version of mongodb? I have another unused CPU and I want to try to install mongodb.

**Comment by gOOvER** [comment]
> Ok, and last question, would it be possible to use another version of mongodb? I have another unused CPU and I want to try to install mongodb.

not for Bastion. you have to write your own egg for it.

Use an actual (not a low budged) CPU and all is fine

**Comment by QuintenQVD0** [comment]
@marcoastor your cpu is to old to run mongodb, the egg supports using an external mongodb like the free on the provided at atlasdb.
