### ISSUE TITLE
[Egg Request]: RCON Web Admin

### ISSUE THREAD

**Issue by Kitof** [parkervcp/eggs#2213]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/rcon-web-admin/rcon-web-admin

### Links for the download

https://github.com/rcon-web-admin/rcon-web-admin/archive/refs/heads/master.zip

### Links for the install docs

https://github.com/rcon-web-admin/rcon-web-admin/blob/master/README.md

**Comment by Kitof** [comment]
It could be very interesting to add support for Rcon Web Admin :
- Most of the supported Game support RCON
- A local web admin could allow to use only local connection to RCON and not exposed ports to Internet.
- A docker image is maintained for this software : https://hub.docker.com/r/itzg/rcon/

If I have time, I'll try to create this egg, but I've no knowledge, so don't hesitate to give me a hand !

**Comment by Kitof** [comment]
Because it's done ;)

**Comment by RogueRaiden** [comment]
Though im not very knowledgeable, the project says it runs on nodejs. Perhaps it could run on the genaric nodejs egg

**Comment by Kitof** [comment]
Actually, i'm on it, it almost works. It will probably need an fork & update of the original projet.

**Comment by QuintenQVD0** [comment]
The generic nodejs egg can run this. just set the main file to `src/index.js start` and it will work
