### ISSUE TITLE
[Bug]: Arma 3

### ISSUE THREAD

**Issue by vedaanty** [parkervcp/eggs#2215]
### Panel Version

1.11.3

### Wings Version

1.11

### Service

Arma 3

### Modified

No, I did not modify the egg

### Expected Behavior

Hello! I am using Pterodactyl and want to host a second Arma server on the same device. I have set the ports to 2402-2406 and changed the startup command accordingly: 

[STARTUP]: Starting server with the following startup command:
./arma3server -ip=0.0.0.0 -port=2402 -profiles=./serverprofile -bepath=./ -cfg=basic.cfg -config=server.cfg -mod="@1135539579;@1135541175;@1135543967;@1199318917;@1201499127;@1224892496;@1355481562;@1486853849;@1515845502;@1515851169;@1573457111;@1638341685;@1661066023;@1673456286;@1714019280;@1770265310;@1808723766;@1875281645;@1916062371;@1974559189;@2034363662;@2041057379;@2073987581;@2129532219;@2162811561;@2185874952;@2189592034;@2216362075;@2260572637;@2268351256;@2271191070;@2349084885;@2372036642;@2420501364;@2467589125;@2467590475;@2513044572;@2578187969;@2653040999;@2820127143;@2862809007;@2869511168;@2915386682;@333310405;@450814997;@463939057;@615007497;@639837898;@753946944;@766491311;@770418577;@823636749;@843425103;@843577117;@843593391;@843632231;@893328083;@893339590;@893346105;@893349825;@894678801;@940841212;" -serverMod="@2162811561" "-enableHT -autoInit"

Have even added the following lines to the server.cfg:
upnp = 1;
steamPort = 2402;
steamQueryPort = 2403;

### Actual Behavior

Yet, when the server starts it starts at 2302, and I am unable to direct connect with the 2402 port?

 6:55:17 Game Port: 2302, Steam Query Port: 2303
 6:55:17 Initializing Steam server - Game Port: 2302, Steam Query Port: 2303
Arma 3 Console version 2.12.150301 x86 : port 2302
 6:55:25 UPNP failed
 6:55:26 Host identity created.
 6:55:26 Connected to Steam servers
container@pterodactyl~ Server marked as running...

### Steps To Reproduce

Create second server
Set different port
Launch

### Install logs

https://pteropaste.com/zf65rew0kbeu

**Comment by QuintenQVD0** [comment]
@vedaanty this are cleearly not the install logs of this server

**Comment by lilkingjr1** [comment]
Does this still occur on the 64-bit binary? When hosting only one server, will it work when using port 2402?

**Comment by vedaanty** [comment]
Tried with the 64 bit binary.. The same issue persists. Even when only one server is online it still refuses to change from 2302 to 2402

**Comment by lilkingjr1** [comment]
Have you tried replicating the issue with a new, completely vanilla server instance? In other words: default settings, default mission file, default everything (except Steam credentials and port number)

**Comment by lilkingjr1** [comment]
Closing this issue as stale. Please comment again if you have tried my troubleshooting step above and would like the issue reopened.
