### ISSUE TITLE
[Bug]: fivem gta-rp

### ISSUE THREAD

**Issue by Bobbbe** [parkervcp/eggs#2217]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

restart and stop button

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Hello, I like your work and thank you for the offers you provide us.

The "stop server" button and the "restart server" button work but they take an abnormal time! 3 to 5 minutes to work! I have to press the "kill" button and I wonder if this can damage files or something else? If so, maybe there is something wrong. PS; I'm using the latest version of the egg you posted.

the server does not create any logs in the logs folder.

### Actual Behavior

ok...

### Steps To Reproduce

just start server and push stop button

### Install logs

no log

**Comment by NoShitSherlockium** [comment]
Go into your egg settings for fivem and change the stop command to:

^SIGKILL

**Comment by QuintenQVD0** [comment]
Try this ^^ first

If it does not work set the stop to `^^c`

This is not a bug with the egg, this is pterodactyl

**Comment by Bobbbe** [comment]
(^^c )   Work very nice! 

thank you for your help and especially for the speed you had :)

**Comment by QuintenQVD0** [comment]
> (^^c ) Work very nice! what is the difference between the (^^) and (^^c) thank you for your help and especially for the speed you had :)

It send a difrend stop signal to the server
