### ISSUE TITLE
[Improvement]: Euro Truck Simulator 2 Can not connect to server

### ISSUE THREAD

**Issue by Mr-Rene** [parkervcp/eggs#2220]
### Panel Version

1.11.3

### Wings Version

Latest: 1.11.5

### Service

Euro Truck Simulator 2

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

In the Steam Guard application, I click the approve button and type the Steam guard code into the server console and the server starts.

### Actual Behavior

It doesn't show anything to the console except the message itself
(Enter the current code from your Steam Guard Mobile Authenticator app) and the Steam code from the mobile app is not shown there either.

### Steps To Reproduce

I enter my token from the website https://steamcommunity.com/dev/managegameservers, then I enter the password and account name and create the server itself.

### Install logs

I don't have today's log.

**Comment by Mr-Rene** [comment]
How?

**Comment by lilkingjr1** [comment]
This is not a bug per-say, but its solution should be made more clear in the README. If you need to log in with a real Steam account to download the server, Steam Guard must be fully turned off. It is either very hard or impossible to input Steam 2FA codes due to the nature of Ptero. Therefore, @kj4lxc (or anyone willing) should add this warning to the README. I recommend leaving this issue open until this is resolved.

**Comment by Mr-Rene** [comment]
Once I remove the Steam authenticator and the server loads correctly, can I reactivate it?

**Comment by QuintenQVD0** [comment]
> Once I remove the Steam authenticator and the server loads correctly, can I reactivate it?

No, auth is done on every startup. You can try disabling auto update.

**Comment by Mr-Rene** [comment]
Can something be done about this, please, so that we don't have to remove the authenticator from the Steam account? please

**Comment by lilkingjr1** [comment]
> Can something be done about this, please, so that we don't have to remove the authenticator from the Steam account? please

When someone has time to fix the egg they will, so be patient. In the meantime, I have already given you a workaround.

**Comment by Mr-Rene** [comment]
Where should I set up please Steam anonymous ?

**Comment by Mr-Rene** [comment]
It tells me that I don't have any modifications, but I turned off mods_optioning: false
