### ISSUE TITLE
[Bug]: Open Fortress

### ISSUE THREAD

**Issue by CitizenPrayer** [parkervcp/eggs#2221]
### Panel Version

1.11.3

### Wings Version

1.10.4

### Service

?

### Modified

No, I did not modify the egg

### Expected Behavior

I expected to install the server and start it and play. I did change one thing and that was the port associated with the game. I already have Avorion up and running and it's using the same default ports. So I changed the ports to 27022 and 27023. Other than that, nothing has changed.

### Actual Behavior

Server crashed with the following:

`
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:games_source 
Digest: sha256:888c583e0681cf895b8abdaf4f70942532f84acb1761b8a1b123aa1d7109f650 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ ./srcds_run -game open_fortress -console -port 27022 +map dm_2fort +ip 0.0.0.0 -strictportbind -norestart -debug +maxplayers 24
ERROR: Invalid game type 'open_fortress' sepecified.
Wed Apr 12 08:25:30 CEST 2023: Server Failed
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 130
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:games_source 
Digest: sha256:888c583e0681cf895b8abdaf4f70942532f84acb1761b8a1b123aa1d7109f650 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ ./srcds_run -game open_fortress -console -port 27022 +map dm_2fort +ip 0.0.0.0 -strictportbind -norestart -debug +maxplayers 24
ERROR: Invalid game type 'open_fortress' sepecified.
Wed Apr 12 08:25:32 CEST 2023: Server Failed
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 130
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

`

### Steps To Reproduce

Step 1: Import the egg
Step 2: Install the server
Step 3: Allocate ports 27022 and 27023 to the server.
Step 4. Start the server.

### Install logs

this I don't have but can have upon direct request.

**Comment by danny6167** [comment]
@CitizenPrayer Can you test the updated egg in the linked PR ?
