### ISSUE TITLE
[Egg Request]: Swords 'n Magic and Stuff

### ISSUE THREAD

**Issue by EvilGenius13** [parkervcp/eggs#2222]
### Does this expand an already existing service

No

### Link to a game or software

https://www.playswordsandmagic.com/

### Links for the download

https://steamdb.info/app/2058450/

### Links for the install docs

https://discord.com/channels/398282199788552193/1022758416923504680

**Comment by EvilGenius13** [comment]
I figured I would ask about this. The game devs posted the information on their discord and never put it in a more public place so I copied the information here. It's windows only so I assume it needs wine to run?

**Instructions Below:**
Dedicated servers are finally here! Get started now with the latest v1.5.0+ update!

Dedicated servers allow you to host a server on your machine without having to have the graphical version of the game running. You can run the dedicated server at the same time on the same machine as running the game client. The server runs in the background on your computer as a separate process.

Prerequisites
OS: Windows 64-bit
RAM: 1-4GB additional to run the server; your machine will need a minimum of 8GB total RAM
CPU: The server will use 25%-100% of a single virtual core
GPU: The server uses little to no GPU resources

Note: To be able to run a dedicated server, you must own a copy of Swords 'n Magic and Stuff on Steam. Running a server will use about the same amount of CPU and GPU usage as hosting a server through the graphical game client, but it will consume an additional 1-4GB of RAM.

To install the dedicated server, you can find it on Steam by enabling the Tools category to be shown in your Steam Library:
Find a drop down box on the left hand side of the Steam Library page, under the search box
Click the drop down (likely says "Games")
Select Tools

From here, you can find Swords 'n Magic and Stuff Dedicated Server item in your list and click INSTALL.

Once installed, you can press LAUNCH to bring up a menu to run the server or Show Manual. I highly recommend you choose Show Manual as it gives very detailed instructions on how to configure your server and any other caveats.

Also note that you must keep the dedicated server up to date with the game. Updates are delivered through Steam similar to games.

The ports it uses are 27015 for the Steam Query and 7777 for the Game Sever. 

Thanks for looking at it!

**Comment by mikeseese** [comment]
SnM dedicated server volunteer here (I'm the one that manages, maintains, and builds the dedicated server builds). I updated the blurb regarding "must own a copy of the game to run a server":

> Note: You can run the dedicated server without owning a copy of Swords 'n Magic and Stuff by using SteamCMD (https://developer.valvesoftware.com/wiki/SteamCMD) and logging in as anonymous and app id 2058450. We do not provide a full set of instructions for this install method at this time and recommend this for advanced users.
>
> To be able to run a dedicated server via the Steam GUI (i.e. without SteamCMD, you must own a copy of Swords 'n Magic and Stuff on Steam to see the tool.

**Comment by QuintenQVD0** [comment]
> SnM dedicated server volunteer here (I'm the one that manages, maintains, and builds the dedicated server builds). I updated the blurb regarding "must own a copy of the game to run a server":
> 
> > Note: You can run the dedicated server without owning a copy of Swords 'n Magic and Stuff by using SteamCMD (https://developer.valvesoftware.com/wiki/SteamCMD) and logging in as `anonymous` and app id `2058450`. We do not provide a full set of instructions for this install method at this time and recommend this for advanced users.
> > To be able to run a dedicated server via the Steam GUI (i.e. without SteamCMD), you must own a copy of Swords 'n Magic and Stuff on Steam to see the tool.

is there a way to print the logs to the console like this:
```
[2023-04-24T18:37:21.571Z] - Dedicated server started; initializing.
[2023-04-24T18:37:21.571Z] - Version: 1.5.13
[2023-04-24T18:37:30.111Z] - Setting reset timer for 19,350 seconds
[2023-04-24T18:37:30.111Z] - Next reset warning in 15750.0 seconds.
[2023-04-24T18:37:30.111Z] - World loaded; updating Steam.
[2023-04-24T18:37:30.112Z] - WARNING: Failed to get Steam session settings. Can be ignored if the server just started. If the server just underwent a reset, this should be considered an ERROR.
[2023-04-24T18:37:30.537Z] - No server name specified; choosing a random one.
[2023-04-24T18:37:30.537Z] - Creating Steam session with configuration:
  Name:  "Lockjaw Diamond"
  Password: ""
  Steam Owner ID: "***************"
  Max players: 16
  Days until reset: 1
  Reset warnings in minutes: 60
[2023-04-24T18:37:30.548Z] - Succeeded to create Steam session with ID: **********************
```

As I got it to work just fine with wine

**Comment by mikeseese** [comment]
I will investigate an option to print to stdout, but the current packaged solution doesn't have the option as is.

With that said, users will have to be able to access the files under the `SNM2020/Saved` directory as that's how they configure their server; will they be able to do that (either through a volume mount of some sort/etc)?

**Comment by mikeseese** [comment]
> is there then a way to write to a static log file that gets cleared on every startup. then I write a C++ program to handle this

Yes, I can make it so that it writes to the timestamped file (for those still needing the historical record) as well as a static `SnMDedSrv-Current.log`. This would be fairly easy if you'd prefer that implementation, though I believe there's value in printing to stdout regardless. If printing out to stdout isn't trivial, I'll revert to the static file and let you know.

**Comment by QuintenQVD0** [comment]
> > is there then a way to write to a static log file that gets cleared on every startup. then I write a C++ program to handle this
> 
> Yes, I can make it so that it writes to the timestamped file (for those still needing the historical record) as well as a static `SnMDedSrv-Current.log`. This would be fairly easy if you'd prefer that implementation, though I believe there's value in printing to stdout regardless. If printing out to stdout isn't trivial, I'll revert to the static file and let you know.

printing to stdout would make my live a lot easyer. I am still new to c++ so I have to clearn it with trial and error and then it can take a wille

**Comment by parkervcp** [comment]
How does the server handle being stopped anyways?  A command would be best from the cli side but if it handles being killed gracefully that would work as well.

**Comment by mikeseese** [comment]
@QuintenQVD0 Looks like we'll be able to support printing to `stdout` in the next version. A couple of recommendations for when that happens:
1. Run `.\SNM2020\Binaries\Win64\SNMASServer-Win64-Shipping.exe` directly instead of the `.\SNMASServer.exe`
2. Add the `-log` argument to enable logging to stdout

Ultimately, the command should look like `.\SNM2020\Binaries\Win64\SNMASServer-Win64-Shipping.exe -log`

It's possible this will fork and create a new process that then logs, so we'll have to test and see if it works and make any adjustments post-release for a subsequent patch release.

**Comment by mikeseese** [comment]
It'll look slightly different than the `SnMDedSrv-<timestamp>.log` since we'll be using UE's built in logging, but the same messages will be printed out:

![image](https://user-images.githubusercontent.com/549323/234128238-1723a5d0-b490-498c-a525-30bc68d3f769.png)

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Looks like we'll be able to support printing to `stdout` in the next version. A couple of recommendations for when that happens:
> 
> 1. Run `.\SNM2020\Binaries\Win64\SNMASServer-Win64-Shipping.exe` directly instead of the `.\SNMASServer.exe` (the latter is just a wrapper and can prevent you from actually getting the correct process handle for seeing stdout potentially)
> 2. Add the `-log` argument to enable logging to stdout
> 
> Ultimately, the command should look like `.\SNM2020\Binaries\Win64\SNMASServer-Win64-Shipping.exe -log`
> 
> It's possible this will fork and create a new process that then logs, so we'll have to test and see if it works and make any adjustments post-release for a subsequent patch release.

That is 100 fine! Thanks you.

**Comment by QuintenQVD0** [comment]
@mikeseese any idea when this will be pushed to steam as then I can PR the egg

**Comment by mikeseese** [comment]
The release is several weeks away with no ETA. If you make a draft PR, I can test your changes on a development build in the meantime to try to have full support on release.
