### ISSUE TITLE
[Egg Request]: Strapi

### ISSUE THREAD

**Issue by xMrAfonso** [parkervcp/eggs#2224]
### Does this expand an already existing service

No

### Link to a game or software

https://strapi.io/

### Links for the download

https://docs.strapi.io/dev-docs/quick-start#step-1-run-the-installation-script

### Links for the install docs

https://docs.strapi.io/dev-docs/installation/docker

**Comment by xMrAfonso** [comment]
For those wondering, it's a self-hosted modern CMS.

**Comment by parkervcp** [comment]
pterodactyl isn't meant for hosting services like this. Their doocker compose is also a multipart image setup so this is not feasable for running in pterodactyl.
