### ISSUE TITLE
[Egg Request]: Night of the Dead

### ISSUE THREAD

**Issue by khisanthax** [parkervcp/eggs#2225]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1377380/Night_of_the_Dead/

### Links for the download

https://steamdb.info/app/1420710/

### Links for the install docs

https://steamcommunity.com/sharedfiles/filedetails/?id=2252239447

**Comment by QuintenQVD0** [comment]
Duplicate https://github.com/parkervcp/eggs/issues/1745
