### ISSUE TITLE
[Egg Request]: Call Of Duty World At War

### ISSUE THREAD

**Issue by m70b1jr** [parkervcp/eggs#2230]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/10090/Call_of_Duty_World_at_War/

### Links for the download

https://store.steampowered.com/app/10090/Call_of_Duty_World_at_War/

### Links for the install docs

https://segmentnext.com/cod5-waw-private-server-tutorial/

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> 
> No
> ### Link to a game or software
> 
> https://store.steampowered.com/app/10090/Call_of_Duty_World_at_War/
> ### Links for the download
> 
> https://store.steampowered.com/app/10090/Call_of_Duty_World_at_War/
> ### Links for the install docs
> 
> https://segmentnext.com/cod5-waw-private-server-tutorial/

And where do we download the game files? as there should be somewhere officaly. as the end user upload then .exe is not allowed. You need to be able to download them from like steam

**Comment by gOOvER** [comment]
There is no server and its not possible and private servers are againbt ToS
