### ISSUE TITLE
[Install Bug]: Sogebot

### ISSUE THREAD

**Issue by MAL5002** [parkervcp/eggs#2231]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

Sogebot

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server and start the bot

### Actual Behavior

Server will install successfully, however upon attempting to start it the following error comes up:
sh: 1: cross-env: not found

### Steps To Reproduce

1. Install the bot
2. Attempt to run the bot

### Install logs

https://pteropaste.com/16qo0paiffeu/

**Comment by QuintenQVD0** [comment]
I have a look as soon as I can

**Comment by QuintenQVD0** [comment]
@MAL5002 Time for you to test ^^ 
please make a new server as that is easyer

**Comment by MAL5002** [comment]
@QuintenQVD0 It works now. Thankyou for the help!
