### ISSUE TITLE
[Bug]: ETS2 The server cannot be searched by name.

### ISSUE THREAD

**Issue by Mr-Rene** [parkervcp/eggs#2234]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

Euro Truck Simulator 2

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

1. The server cannot be searched by name.

### Actual Behavior

1. The server will not appear in the list.

### Steps To Reproduce

1. I enter the name of the server in the search

### Install logs

I don't have today's log.

**Comment by QuintenQVD0** [comment]
This is not realy egg related.  if the steam token is valid it should show up in the list. As we can not guarantee it will show up in server list. This is more of a game limitation.
