### ISSUE TITLE
[Bug]: SpaceEngineers default blocks are getting invisible

### ISSUE THREAD

**Issue by Trimilur** [parkervcp/eggs#2240]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

spaceengineer default

### Modified

No, I did not modify the egg

### Expected Behavior

Install start, play, blocks should stay visible

### Actual Behavior

After a while blocks become invisible

### Steps To Reproduce

Latest Version
Install
Play a few hours blocks become invisble out of nothing. Full base invisible but still existent you can walk on it

### Install logs

transferred server no logs available anymore of original install

**Comment by gOOvER** [comment]
Not an egg issue; ask the devs
