### ISSUE TITLE
[Bug]: Space Engineers - Torch -> Ram utilization will not go above 4.8GB max

### ISSUE THREAD

**Issue by Vaultpls** [parkervcp/eggs#2244]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

Space Engineers Torch Server

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Install server, install Steam Workshop mods, and TorchAPI plugins and have more than 4.8GB+ used.

### Actual Behavior

When having any amount of  players in the server even 8+, the server consumes only 4.8GB max~ and constantly has GC running ruining the performance since the low amount of RAM it's utilizing. 

### Steps To Reproduce

1. Install server
2. Install any workshop mods and/or plugins you desire
3. Have enough content(like loading a scenario) to be able to saturate 4GB of RAM.
4. Experience intermittent lag spikes from garbage collection 

(I even tried to ensure Wine64 was running in startup, my only modification to the egg and I can confirm Wine's prefix is indeed Win64-enabled)

### Install logs

https://pastebin.com/raw/qQ0YhZw4

**Comment by gOOvER** [comment]
Not an Egg issue. ask their support

**Comment by Vaultpls** [comment]
Well in that case: https://support.keenswh.com/spaceengineers/pc/topic/28477-dedicated-server-will-not-use-above-4-8gb

If anyone wants to follow since there has been no others having this issue after searching on their forums and the Github issues here.

**Comment by blindguy** [comment]
thanks @Vaultpls - having the same issue.  I got a monster server with over 128GB ram and want to use it all.  I'll follow that thread.

**Comment by QuintenQVD0** [comment]
This is more like an game engine issue not egg releated. If you later find out it is egg related feel free to reopen this
