### ISSUE TITLE
[Egg Request]: CharacterAI Discord Bot

### ISSUE THREAD

**Issue by mzrtamp** [parkervcp/eggs#2247]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot

### Links for the download

https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/tag/1.87

### Links for the install docs

https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/wiki/How-to-set-up

**Comment by mzrtamp** [comment]
I am requesting a new egg for the CharacterAI Discord Bot project.
The server requires the following dependencies to be installed:

- [CharacterAI (c.ai)](https://c.ai)
- [PuppeteerSharp](https://www.puppeteersharp.com/)
- Full permissions (`777`) for all files and folders in the container

Please let me know if any further information is needed to create the egg.

Thank you.

**Comment by QuintenQVD0** [comment]
I tried making a egg for it, but it needs chromium what auto downloads, but it can not launch as there is no real display to pterodactyl containers. This is not possible
