### ISSUE TITLE
[Install Bug]: FiveM (install: unknown filetype. Exiting)

### ISSUE THREAD

**Issue by jay-zeex** [parkervcp/eggs#2252]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

To start the server flawlessly

### Actual Behavior

While starting the server the container image is pulled, but there is apparently missing the "ld-musl-x86_64.so.1" file so it cant start properly :(

It could maybe do something with the information in the log saying:
Resolving deltas: 100% (541/541), done.
Running curl -sSL null -o null
curl: (6) Could not resolve host: null
Extracting fivem files
unknown filetype. Exiting

Pterodactyl log:
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
/entrypoint.sh: line 13: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: No such file or directory

### Steps To Reproduce

1. Upload egg
2. Install new server with the egg
3. Start the server
4. Error

**Comment by parkervcp** [comment]
@jay-zeex it looks like your install script is messed up or something because it's trying to reach a null value when I can say for certain that there should be links there.

**Comment by jay-zeex** [comment]
Agreed, i was just looking at that.
Is the variable "DOWNLOAD_URL" used there? Because it is empty.

**Comment by parkervcp** [comment]
There is no reason to go to that page and set the url manually. It sounds like your install failed to get the page correctly to get the current recommended and latest releases.

**Comment by jay-zeex** [comment]
We will try next install without the DownloadURL set, but for right now I only know that without the specified URL it wouldn't download and with it it went ok.
To the noob user like me it seems that the URL is missing in the install script and you need to fill it by yourself. There is no information that the variable is optional and should be used only in some cases. When you read the description "This is the link to download fivem from." and there is nothing, then in my understanding it shouldn't download at all :)
