### ISSUE TITLE
[Bug]: V Rising Vanilla 

### ISSUE THREAD

**Issue by KayTwenty** [parkervcp/eggs#2263]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

vrising

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, should be able to play without any crash

### Actual Behavior

```
PersistenceV2 - Successfully serialized Persistence Header. Header was 778299 by
tes large.

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 29
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

### Steps To Reproduce

Save and upload V Rising Vanilla egg as JSON
Import egg
Create server
And then it fails.

### Install logs

https://pteropaste.com/ft8u1so0y6oj/

**Comment by gOOvER** [comment]
pls do a uname -a

**Comment by KayTwenty** [comment]
Linux ptero 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oOScuByOo** [comment]
Same here 

![image](https://github.com/parkervcp/eggs/assets/5473243/c25eadd0-6133-45bd-8451-055ea2dc9278)

**Comment by KayTwenty** [comment]
I've done some digging and I believe the `Exit Code: 29` is a hardware issue. I'm running Proxmox 7.4 with a Ubuntu Server 22.04 virtual machine. I've swapped the virtualization mode for the CPU to using the host instead of the default kvm64. I still get the same error as before.

**Comment by KayTwenty** [comment]
Interesting, I've installed Wings on another virtual machine on my other Proxmox host and it seems to not give me the exit code. It actually seems to work. Although, with the other host, It seems that Intel Xeon E5620 do not work well and give the Exit code 29.

**Comment by lilkingjr1** [comment]
> Interesting, I've installed Wings on another virtual machine on my other Proxmox host and it seems to not give me the exit code. It actually seems to work. Although, with the other host, It seems that Intel Xeon E5620 do not work well and give the Exit code 29.

My quick Googling tells me that CPU is 13 years old... That might be why. Instruction sets have changed slightly since then I think (but I'm not an expert).

**Comment by gOOvER** [comment]
> Interesting, I've installed Wings on another virtual machine on my other Proxmox host and it seems to not give me the exit code. It actually seems to work. Although, with the other host, It seems that Intel Xeon E5620 do not work well and give the Exit code 29.

This CPU is not supported. Use an actual CPU
