### ISSUE TITLE
[Bug]: Arma 3 doesn't shut down immediately

### ISSUE THREAD

**Issue by Stage4000** [parkervcp/eggs#2264]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

arma 3

### Modified

No, I did not modify the egg

### Expected Behavior

Server to stop upon request via panel 'stop' button.

### Actual Behavior

server fails to stop and must be killed.

### Steps To Reproduce

install an arma server, put a mission on it of any kind im experiencing this across 3 seperate servers (same panel but differnt mods, missions, etc.).

### Install logs

https://pteropaste.com/1cyx531bzyiz

**Comment by gOOvER** [comment]
known issue

**Comment by lilkingjr1** [comment]
I'm looking into it, but awaiting a possible Yolk/Wings update before I do anything major. In the meantime, you can change the shutdown command to `^^C` to instantly kill the server.
