### ISSUE TITLE
[Bug]: Space Engineers / Torch 

### ISSUE THREAD

**Issue by DjQuro** [parkervcp/eggs#2266]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Space Engineers

### Modified

No, I did not modify the egg

### Expected Behavior

Set an Administrator like this:

https://www.roxservers.com/knowledgebase.php?action=displayarticle&id=497&language=english

Or using remote API

Also Gamemode will not be set.

### Actual Behavior

I can write absolute Trash in the config file, container/config/SpaceEngineers-Dedicated.cfg and the config is still loaded

### Steps To Reproduce

Step1 Install one of the Eggs and allocate the Ports 8766, 8081 and the Gameport
Step2 Try to Connect using VRageRemoteClient
or
Step2.1 Change container/config/SpaceEngineers-Dedicated.cfg like set an Administrator

### Install logs

 https://pteropaste.com/mxhwxd7qcuwy

**Comment by gOOvER** [comment]
API dont work on Linux

**Comment by DjQuro** [comment]
Am I seeing right, you are providing non functional stuff? I better look for an alternative Solution.
