### ISSUE TITLE
[Egg Request]: Northstar (Titanfall 2)

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2268]
### Does this expand an already existing service

No

### Link to a game or software

https://northstar.tf/

### Links for the download

https://github.com/R2Northstar/Northstar/releases/tag/v1.14.2 (there's also 3 installers but i wasn't sure which one to put)

### Links for the install docs

https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/basic-setup

**Comment by diedyesterdaywashere** [comment]
https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/manual-installation this is the manual installation guide which is probably the most suitable for the egg

**Comment by parkervcp** [comment]
#1553 was already created and closed. The guide you linked is for windows.

We can keep this one open for tracking purposes.

**Comment by diedyesterdaywashere** [comment]
https://r2northstar.gitbook.io/r2northstar-wiki/hosting-a-server-with-northstar/dedicated-server there's this, idk

**Comment by diedyesterdaywashere** [comment]
but its probably for windows too

**Comment by diedyesterdaywashere** [comment]
i'll check if there's a linux guide in a bit

**Comment by diedyesterdaywashere** [comment]
> > #1553 was already created and closed. The guide you linked is for windows.
> > 
> > We can keep this one open for tracking purposes.
> 
> https://github.com/pg9182/northstar-dedicated
> 
> This exists, _could_ be used to make a Pterodactyl compatible edition.

yeah I've also seen this, but I didn't know if i was allowed to post it and stuff

**Comment by yesBad** [comment]
> yeah I've also seen this, but I didn't know if i was allowed to post it and stuff 

ah why not

**Comment by diedyesterdaywashere** [comment]
> > yeah I've also seen this, but I didn't know if i was allowed to post it and stuff
> 
> ah why not

![image](https://github.com/parkervcp/eggs/assets/81169193/8ff8ce17-90e6-4de6-85b8-5415b96e42de)

**Comment by QuintenQVD0** [comment]
I think I would say no to this as the game files are needed for this and there 62.96 GiB big + that mod and pterodactyl does not work with docker-compose.
\+ it looks like it needs a real display: https://github.com/pg9182/northstar-dedicated#running-with-wine

if anyone gets it running then feel free to re-open this
