### ISSUE TITLE
Pavlov VR Server

### ISSUE THREAD

**Issue by ryan1161** [parkervcp/eggs#227]
Service: Pavlov VR Server - Linux

Does this expand an already existing service: N

Link to game: https://store.steampowered.com/app/555160/Pavlov_VR/

Links for server downloads: http://wiki.pavlov-vr.com/index.php?title=Dedicated_server

Links for install steps/docs: http://wiki.pavlov-vr.com/index.php?title=Dedicated_server

**Comment by ryan1161** [comment]
Hint: I managed to get it working on the panel but the issue is with the workshop downloading to a folder outside the container /tmp/workshop which tells me I only have 568MB and I have 5tb drive.

**Comment by parkervcp** [comment]
That is due to how the containers are started and configured. There is no way around this.

**Comment by ryan1161** [comment]
I would love to see this on the panel someday. I guess I can only play the original maps with the game for now. Can't wait to play TTT,Jailbreak on the server in VR.

**Comment by parkervcp** [comment]
technically you can change the temp file size. I have had the issue before.

```
    "policy": {
      "container": {
        "tmpfs": "rw,exec,nosuid,size=1G"
      }
    }
```

**Comment by ryan1161** [comment]
Where would I exactly put that at in the Dockerfile or entrypoint.sh I knew it was possible but no clue where to implement it in.

**Comment by parkervcp** [comment]
It's in the daemon config.

**Comment by ryan1161** [comment]
Okay thanks I’ll give it a try tonight.

**Comment by ryan1161** [comment]
Like location? I found /srv/daemon/core.json but idk if that’s the file?

**Comment by parkervcp** [comment]
you would add it in after or around your other docker config parts already there. do not replace the whole docker config.

**Comment by ryan1161** [comment]
I can't get it to reconnect the daemon on the panel it's just spinning out but if I remove what I add it reconnects. Anyway I can send you the core.json privately to check for code issue I may have?

**Comment by ryan1161** [comment]
Here is the top of my core to give you a better look:

{
  "web": {
    "host": "0.0.0.0",
    "listen": 8443,
    "ssl": {
      "enabled": true,
      "certificate": "/etc/letsencrypt/live/gamepanel.ryandward.com/fullchain.pem",
      "key": "/etc/letsencrypt/live/gamepanel.ryandward.com/privkey.pem"
    }
  },
  "docker": {
    "container": {
      "user": 999
     },
    "network": {
      "name": "pterodactyl_nw"
    },

**Comment by parkervcp** [comment]
my entire docker section is as follows
```
  "docker": {
    "container": {
      "user": 100
    },
    "network": {
      "name": "pterodactyl_nw"
    },
    "policy": {
      "container": {
        "tmpfs": "rw,exec,nosuid,size=1G"
      }
    },
    "socket": "/var/run/docker.sock",
    "autoupdate_images": true,
    "timezone_path": "/etc/localtime",
    "interface": "172.18.0.1"
  },
```

**Comment by ryan1161** [comment]
Thank you server is now running and downloading workshop content.
