### ISSUE TITLE
[Egg Request]: <JMusicBot>

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2271]
### Does this expand an already existing service

Yes

### Link to a game or software

https://jmusicbot.com/

### Links for the download

https://github.com/jagrosh/MusicBot/releases/tag/0.3.9

### Links for the install docs

https://jmusicbot.com/setup/

**Comment by diedyesterdaywashere** [comment]
This is a self-hosted music bot, i'm not sure if it will work with java egg so i decided to submit this.

**Comment by Software-Noob** [comment]
It already exists if you check the repository

**Comment by diedyesterdaywashere** [comment]
im just blind, sorry
