### ISSUE TITLE
[Egg Request]: No One Survived

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2272]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1963370/No_One_Survived/

### Links for the download

https://steamdb.info/app/2329680/

### Links for the install docs

https://store.steampowered.com/news/app/1963370/view/3673285758055384940 (windows version, but it might work with wine?)

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> No
> 
> ### Link to a game or software
> https://store.steampowered.com/app/1963370/No_One_Survived/
> 
> ### Links for the download
> not sure what to put here because it is accessed through steamcmd
> 
> ### Links for the install docs
> https://store.steampowered.com/news/app/1963370/view/3673285758055384940 (windows version, but it might work with wine?)

Do you know if it works with wine or proton else this is not posible. For yhe downlozd link you put the steamdb url for the dedicated server.

**Comment by diedyesterdaywashere** [comment]
> > ### Does this expand an already existing service
> > No
> > ### Link to a game or software
> > https://store.steampowered.com/app/1963370/No_One_Survived/
> > ### Links for the download
> > not sure what to put here because it is accessed through steamcmd
> > ### Links for the install docs
> > https://store.steampowered.com/news/app/1963370/view/3673285758055384940 (windows version, but it might work with wine?)
> 
> Do you know if it works with wine or proton else this is not posible. For yhe download link you put the steamdb url for the dedicated server.

https://github.com/michaelarlt/NoS-Dedicated-Server

**Comment by diedyesterdaywashere** [comment]
![image](https://github.com/parkervcp/eggs/assets/81169193/ace9fc85-56ca-4c2e-84e7-7e61be889915)
i also made a question on their discord forum, maybe they'll respond to me idk

**Comment by diedyesterdaywashere** [comment]
![Screenshot_2023-05-26-00-20-56-160_com discord](https://github.com/parkervcp/eggs/assets/81169193/033594f1-c057-4cfa-80ba-5ca5f97b1288)
I'm afraid that might not be possible to implement rn
