### ISSUE TITLE
[Egg Request]: DDRaceNetwork

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2273]
### Does this expand an already existing service

Yes

### Link to a game or software

https://ddnet.org/

### Links for the download

https://ddnet.org/downloads/

### Links for the install docs

https://forum.ddnet.org/viewtopic.php?t=5095 (this is a windows version, but the linux version has the same files so it's almost the exact process)

**Comment by QuintenQVD0** [comment]
What egg does it expand?

**Comment by diedyesterdaywashere** [comment]
> What egg does it expand?

DDRacenetwork is a mod for Teeworlds i think?

**Comment by diedyesterdaywashere** [comment]
> > What egg does it expand?
> 
> DDRacenetwork is a mod for Teeworlds i think?

like not the "mod" but a standalone modified version, idk if that still counts, but i guess it does
