### ISSUE TITLE
[Egg Request]: Jitsi Meet

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2274]
### Does this expand an already existing service

No

### Link to a game or software

https://jitsi.org/

### Links for the download

https://jitsi.org/

### Links for the install docs

https://jitsi.github.io/handbook/docs/devops-guide

**Comment by QuintenQVD0** [comment]
Not posible as nginx is required and we do not supported webhosting. Also port 80 is needed what is also not posible.
