### ISSUE TITLE
[Bug]: <egg-v-rising.json>

### ISSUE THREAD

**Issue by MaXx-62** [parkervcp/eggs#2276]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

V rising

### Modified

No, I did not modify the egg

### Expected Behavior

A good description

### Actual Behavior

Description server with last updated eggs v rising vanilla not work

![Screenshot_2](https://github.com/parkervcp/eggs/assets/4140252/420288ab-1379-4ab0-aa03-69ac9b168749)
![Screenshot_3](https://github.com/parkervcp/eggs/assets/4140252/17cc5ce3-abc7-4646-9344-508674da6802)

https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/v_rising/v_rising_vanilla/egg-v-rising.json

### Steps To Reproduce

Modify the eggs or maybe pterodactyl that causes this bug?

### Install logs

https://pteropaste.com/za89eo8cycdt/

**Comment by MaXx-62** [comment]
![Screenshot_8](https://github.com/parkervcp/eggs/assets/4140252/2a234fb9-bb18-4089-a411-ffaf91a085c1)
![Screenshot_9](https://github.com/parkervcp/eggs/assets/4140252/989eb315-3220-4331-854f-1950382132a6)

**Comment by diedyesterdaywashere** [comment]
maybe that's a game problem? i don't think ptero or an egg could cause that, but you can try removing those duplicate slashes idk

**Comment by parkervcp** [comment]
The slashes are escaped when they are converted to the string. Honestly this is not an egg issue but one the panel can't really deal with.

**Comment by MaXx-62** [comment]
> maybe that's a game problem? i don't think ptero or an egg could cause that, but you can try removing those duplicate slashes idk

![Screenshot_12](https://github.com/parkervcp/eggs/assets/4140252/abf8a24a-6f54-4441-8415-9d5240e9be35)

**Comment by MaXx-62** [comment]
> The slashes are escaped when they are converted to the string. Honestly this is not an egg issue but one the panel can't really deal with.

Before it worked, I changed eggs to this one, because it's up to date with the new v rising extension

**Comment by MaXx-62** [comment]
Before when I made servers the \n it worked fine, maybe I have to go back to a previous version of pterodactyl

**Comment by MaXx-62** [comment]
> The slashes are escaped when they are converted to the string. Honestly this is not an egg issue but one the panel can't really deal with.

Is it not possible to remove the mandatory description via the panel? and to modify it only by the file, because when I want to modify it via the file it delete and puts back that of the panel description server by default

**Comment by lilkingjr1** [comment]
It's probably an issue with the config parser in Ptero. You can simply remove this field from the Configuration Files section of the egg and just set it manually in the appropriate file.
