### ISSUE TITLE
[Install Bug]: Openworld Rimworld

### ISSUE THREAD

**Issue by drkthunder02** [parkervcp/eggs#2278]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

./Openworld

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, and find the linux-x64.zip file to be found.

### Actual Behavior

linux-x64.zip file is not found due to github repository no longer existing.

### Steps To Reproduce

Step 1: Setup server and install server.
Step 2: Watch console to see the linux-x64.zip file is not found in the proper location due to the github repository not existing anymore under the user the install script was created with.

### Install logs

https://pteropaste.com/zp5mthraa7bb

**Comment by QuintenQVD0** [comment]
they moved there repo, again so
go to the install script of the egg and there are 2 lines
```bash
LATEST_JSON=$(curl --silent "https://api.github.com/repos/mypassowordisntweak/OpenWorld/releases/latest")
RELEASES=$(curl --silent "https://api.github.com/repos/mypassowordisntweak/OpenWorld/releases")
```

change them to for now
```bash
LATEST_JSON=$(curl -L --silent "https://api.github.com/repos/mypassowordisntweak/OpenWorld/releases/latest")
RELEASES=$(curl -L --silent "https://api.github.com/repos/mypassowordisntweak/OpenWorld/releases")
```

**Comment by diedyesterdaywashere** [comment]
i can update an egg if needed too

**Comment by QuintenQVD0** [comment]
> i can update an egg if needed too

that is fine but then do not use the -L trick but change the api links to the new repo

**Comment by diedyesterdaywashere** [comment]
https://github.com/D12-Dev/OpenWorld so i think this is their repo now?

**Comment by QuintenQVD0** [comment]
> https://github.com/D12-Dev/OpenWorld so i think this is their repo now?

yes, it should be now:
```bash
LATEST_JSON=$(curl --silent "https://api.github.com/repos/D12-Dev/OpenWorld/releases/latest")
RELEASES=$(curl --silent "https://api.github.com/repos/D12-Dev/OpenWorld/releases")
```
