### ISSUE TITLE
[Egg Request]: Sniper Elite V2 Remastered

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2283]
### Does this expand an already existing service

No

### Link to a game or software

https://rebellion.com/games/sniper-elite-v2-remastered/

### Links for the download

https://steamdb.info/app/756760/info/

### Links for the install docs

I couldn't find it, but i'll try to make an egg myself (it would also need wine)

**Comment by QuintenQVD0** [comment]
last updated 4 yearsd ago, and there is no documentation for it and it does not run with wine

**Comment by gOOvER** [comment]
Sniper Elite V2 is a fucking old game :D

**Comment by diedyesterdaywashere** [comment]
> Sniper Elite V2 is a fucking old game :D

remastered was released in 2019 so it's not that old :D

**Comment by QuintenQVD0** [comment]
> > Sniper Elite V2 is a fucking old game :D
> 
> remastered was released in 2019 so it's not that old :D

The server last update was 4 years ago.

**Comment by diedyesterdaywashere** [comment]
@QuintenQVD0 can you pls close it as not planned then?
