### ISSUE TITLE
[Egg Request]: Just Cause 3: Multiplayer

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2284]
### Does this expand an already existing service

No

### Link to a game or software

https://just-cause.mp/

### Links for the download

https://steamdb.info/app/619960/info/

### Links for the install docs

https://steamcommunity.com/sharedfiles/filedetails/?id=1094953641

**Comment by diedyesterdaywashere** [comment]
it's linux native, so it doesn't require wine or anything, i already own the game, so i may be able to test the server, i can try to make an egg for it if needed

**Comment by QuintenQVD0** [comment]
Latedt release was 6 years ago..

**Comment by diedyesterdaywashere** [comment]
yeah i'll try to make an egg for this in a second

**Comment by diedyesterdaywashere** [comment]
they took one url down, so i won't be able to make an egg
