### ISSUE TITLE
[Egg Feature Request]: Project Zomboid | Easy Mod Install

### ISSUE THREAD

**Issue by m70b1jr** [parkervcp/eggs#2292]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/108600/Project_Zomboid/

### Links for the download

https://store.steampowered.com/app/108600/Project_Zomboid/

### Links for the install docs

N/A

I was wondering if it was possible maybe under the startup or settings tab for the Project Zomboid Egg, to have an entry to add workshop items / mods. It sounds dumb, but can make spinning up modded servers much easier for my less tech savy friends using the panel.

EDIT: I actually can't find the folders / files normally used to add mods (in linux) , do you guys maybe know?

**Comment by QuintenQVD0** [comment]
https://www.bisecthosting.com/clients/index.php?rp=/knowledgebase/237/How-to-install-mods-on-a-Project-Zomboid-server.html

it should already work

**Comment by m70b1jr** [comment]
> https://www.bisecthosting.com/clients/index.php?rp=/knowledgebase/237/How-to-install-mods-on-a-Project-Zomboid-server.html
> 
> it should already work

Thank you, I didn't realize that was the directory.

Is there any chance in the future we could get a pretty GUI in the panel to easily add them?

**Comment by QuintenQVD0** [comment]
> > https://www.bisecthosting.com/clients/index.php?rp=/knowledgebase/237/How-to-install-mods-on-a-Project-Zomboid-server.html
> > it should already work
> 
> Thank you, I didn't realize that was the directory.
> 
> Is there any chance in the future we could get a pretty GUI in the panel to easily add them?

No, the panel is headless.
