### ISSUE TITLE
[Egg Request]: discordtickets.app by eartharoid (v4 with panel web UI)

### ISSUE THREAD

**Issue by GameAreaCZ** [parkervcp/eggs#2293]
### Does this expand an already existing service

Yes

### Link to a game or software

https://discordtickets.app/

### Links for the download

https://github.com/discord-tickets/bot/releases

### Links for the install docs

https://discordtickets.app/getting-started/

**Comment by gOOvER** [comment]
you can use the generic nodejs egg for that

**Comment by QuintenQVD0** [comment]
The generic nodejs can run this. It may need a an extra variable but it will run it.

**Comment by GameAreaCZ** [comment]
Oh ok, will try. Thank you.
