### ISSUE TITLE
[Install Bug]: yuzu-emu

### ISSUE THREAD

**Issue by 2Shad** [parkervcp/eggs#2294]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

game_eggs/yuzu-emu

### Modified

No, I did not modify the egg

### Expected Behavior

(no idea, first time trying, I assume) Install the server, it compiles, and server is up
tried spinning up this container, and it works https://github.com/yuzu-emu/yuzu-multiplayer-dedicated

### Actual Behavior

server not installing properly, it cannot seem to find yuzu-room. check logs

### Steps To Reproduce

1. Import egg
2. Set port allocation, reasonable Memory/Disk (set 4096/16384 for my case)
3. Set room name, remove preferred game, set max players to 12, and set Room password (tried with other configs too)

### Install logs

https://pteropaste.com/txtyig1xh9fj

**Comment by diamkil** [comment]
Same problem for me here, would be nice if it could be fixed

**Comment by QuintenQVD0** [comment]
> Same problem for me here, would be nice if it could be fixed

It is on my list no worries. Just not that easy to debug as compiling software is a pain.

**Comment by QuintenQVD0** [comment]
This issue is not related to use but to them see: https://github.com/yuzu-emu/yuzu-multiplayer-dedicated/actions failing

**Comment by PilaScat** [comment]
any news?

**Comment by gOOvER** [comment]
> any news?

looks like no ;)

**Comment by QuintenQVD0** [comment]
> any news?

They fixt it on there site. Now the egg needs a rewrite.

**Comment by QuintenQVD0** [comment]
@Z3r0byte This is something for you as they redid there github

**Comment by Z3r0byte** [comment]
Unfortunately, I am unable to recreate this issue. I just created a fresh server using the egg, and it compiles and starts fine. The original issue looks like some git error, but that seems to be gone now. If anyone is still having issues, please post new logs of the installation process and I'll take a look at it.

**Comment by QuintenQVD0** [comment]
While testing #2609 This issue is not present anymore

**Comment by PilaScat** [comment]
Tried installing with new egg but it stops here and remains in installation
```
cp -f iso3166.tab leapseconds tzdata.zi zone1970.tab zone.tab '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/zoneinfo/.'
cp tzselect '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/bin/.'
cp zdump '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/bin/.'
cp zic '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/sbin/.'
cp libtz.a '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/lib/.'
: '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/lib/libtz.a'
cp -f newctime.3 newtzset.3 '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/man/man3/.'
cp -f tzfile.5 '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/man/man5/.'
cp -f tzselect.8 zdump.8 zic.8 '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/man/man8/.'
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/server/yuzu-mainline/build
+ ninja yuzu-room
```

**Comment by gOOvER** [comment]
> Tried installing with new egg but it stops here and remains in installation
> 
> ```
> cp -f iso3166.tab leapseconds tzdata.zi zone1970.tab zone.tab '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/zoneinfo/.'
> cp tzselect '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/bin/.'
> cp zdump '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/bin/.'
> cp zic '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/sbin/.'
> cp libtz.a '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/lib/.'
> : '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/lib/libtz.a'
> cp -f newctime.3 newtzset.3 '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/man/man3/.'
> cp -f tzfile.5 '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/man/man5/.'
> cp -f tzselect.8 zdump.8 zic.8 '/mnt/server/yuzu-mainline/build/externals/nx_tzdb/tzdb_to_nx/externals/tz/tz/usr/share/man/man8/.'
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /mnt/server/yuzu-mainline/build
> + ninja yuzu-room
> ```

not an egg issue; check your space or server. I see no error

**Comment by PilaScat** [comment]
I've set unlimited memory and disk, is that the problem?

**Comment by QuintenQVD0** [comment]
> I've set unlimited memory and disk, is that the problem?

check the host os, never set anything unlimited about disk space, cpu and ram. Also do not use old issue, come to the discord for that.
