### ISSUE TITLE
[Egg Request]: TimescaleDB

### ISSUE THREAD

**Issue by Semetrix** [parkervcp/eggs#2295]
### Does this expand an already existing service

No

### Link to a game or software

https://www.timescale.com/

### Links for the download

https://docs.timescale.com/self-hosted/latest/install/

### Links for the install docs

https://docs.timescale.com/self-hosted/latest/configuration/

**Comment by QuintenQVD0** [comment]
This needs postgres and TimescaleDB in 1 docker image, and it requires them to both run at the same time and do manual configuration in the postgres server.
Pterodactyl is not made for handling more than 1 process. Just run it on the host or directly in docker with there images
