### ISSUE TITLE
[Bug]: egg-vanilla-bedrock.json

### ISSUE THREAD

**Issue by Rayth** [parkervcp/eggs#2297]
### Panel Version

1.11.3

### Wings Version

1.11

### Service

minecraft bedrock 

### Modified

No, I did not modify the egg

### Expected Behavior

Keep the allowlist.json file when reinstalling server

### Actual Behavior

allowlist.json file is deleted and replaced with the blank one from install.

### Steps To Reproduce

Step 1- Set up a minecraft bedrock server
Step 2- Enable allowlist in the server.properties file
Step 3- Turn on server
Step 3- Add a user to allowlist (allowlist add Name) via console
Step 4- stop server
Step 5- Reinstall server
Step 6- Check files.

whitelist.json has been deprecated in bedrock since some time in 1.17

### Install logs

https://pteropaste.com/th7rvnf2x3wj

**Comment by gOOvER** [comment]
@Quinten; as i know, there is a Backup partt in install script. Mb its needed to add this file to tat

**Comment by Rayth** [comment]
> we could add `mv allowlist.json allowlist.json.bak` that would be a option

That's what I done to get it working on mine. I just setup my own ptero for the first time today and that has been annoying me since it started happening.
