### ISSUE TITLE
[Bug]: Satisfactory Experimental is using UE5, changes to startup command needed for update.

### ISSUE THREAD

**Issue by ovingiv** [parkervcp/eggs#2298]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

Satisfactory 

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Set to install "experimental" branch of the server. Wait for install, start it, play.

### Actual Behavior

Waited for install to finish, started server, server errored out. File ./Engine/Binaries/Linux/UE4Server-Linux-Shipping does not exist.

UE4Server-Linux-Shipping was changed to UnrealServer-Linux-Shipping.

### Steps To Reproduce

Step 1: Set "[Advanced] Branch Name" to "Experimental".
Step 2: Set "[Repair] Validate Server Files" to "true or 1"
Step 3: Wait for re-installation of server.
Step 4: See server error out saying file not found.

### Install logs

N/A

**Comment by ovingiv** [comment]
This is only needed if wanting to play on the Experimental branch of the game. But edits will need to be made for when Update 8 comes to Early Access/ Default Branch.

**Comment by lilkingjr1** [comment]
@ovingiv Good catch, and thank you for opening an issue. I'll see if I can resolve this issue soon by using a wildcard for the binary name. In the meantime, installing the Early Access branch, switching the branch afterwards with Auto-Update enabled, and manually changing the startup command should be a good workaround.

**Comment by lilkingjr1** [comment]
@ovingiv Please test the PR above and comment on the PR if it works for you. Thanks.

**Comment by QuintenQVD0** [comment]
This can stay open
