### ISSUE TITLE
[Bug]: Astroneer egg not start

### ISSUE THREAD

**Issue by Shandeika** [parkervcp/eggs#2303]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

astroneer

### Modified

No, I did not modify the egg

### Expected Behavior

The server starts and works

### Actual Behavior

Error at startup:
```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/steamcmd 
Digest: sha256:fe2851561cf732acd9b57e40dcc3f1db78ed6ad263f6c10c3ae59627ab870038 
Status: Image is up to date for ghcr.io/parkervcp/steamcmd:proton 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
/entrypoint.sh: line 70: ./steamcmd/steamcmd.sh: No such file or directory
:/home/container$ proton run ./Astro/Binaries/Win64/AstroServer-Win64-Shipping.exe
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
container@pterodactyl~ Server marked as running...
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/steamcmd 
Status: Image is up to date for ghcr.io/parkervcp/steamcmd:proton 
Digest: sha256:fe2851561cf732acd9b57e40dcc3f1db78ed6ad263f6c10c3ae59627ab870038 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
/entrypoint.sh: line 70: ./steamcmd/steamcmd.sh: No such file or directory
:/home/container$ proton run ./Astro/Binaries/Win64/AstroServer-Win64-Shipping.exe
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
container@pterodactyl~ Server marked as running...
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

### Steps To Reproduce

1. Click start

### Install logs

ls: cannot access '/var/log/pterodactyl/install/*.log': No such file or directory

**Comment by QuintenQVD0** [comment]
Hit reinstall the get the install logd. 

And also `uname -a` please

**Comment by QuintenQVD0** [comment]
As the install definitly faild

/entrypoint.sh: line 70: ./steamcmd/steamcmd.sh: No such file or directory

Or you uploaded the files by hand

**Comment by Shandeika** [comment]
reinstall logs https://pastebin.com/rtjgmYad
uname -a out: `Linux scott 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Shandeika** [comment]
After these actions, the server starts, but with errors
```
container@pterodactyl~ Server marked as running...
steam user is not set.

Using anonymous user.

WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1686881296
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '728470' already up to date.
:/home/container$ proton run ./Astro/Binaries/Win64/AstroServer-Win64-Shipping.exe
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
```

**Comment by QuintenQVD0** [comment]
> After these actions, the server starts, but with errors
> 
> ```
> container@pterodactyl~ Server marked as running...
> steam user is not set.
> 
> Using anonymous user.
> 
> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
> [  0%] Checking for available updates...
> [----] Verifying installation...
> Steam Console Client (c) Valve Corporation - version 1686881296
> -- type 'quit' to exit --
> Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
> OK
> 
> Connecting anonymously to Steam Public...OK
> Waiting for client config...OK
> Waiting for user info...OK
> "@sSteamCmdForcePlatformType" = "windows"
> Success! App '728470' already up to date.
> :/home/container$ proton run ./Astro/Binaries/Win64/AstroServer-Win64-Shipping.exe
> esync: up and running.
> wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> ```

Those are normal. As the sound driver is not enabled.

**Comment by Shandeika** [comment]
@QuintenQVD0 But the server is not working
scott.shandy-dev.ru:20000

**Comment by QuintenQVD0** [comment]
@Shandeika if you want to not see those errors set the startup to `pulseaudio --daemonize=true; proton run ./Astro\/Binaries/Win64/AstroServer-Win64-Shipping.exe´

**Comment by gOOvER** [comment]
> reinstall logs https://pastebin.com/rtjgmYad uname -a out: `Linux scott 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

this kernel is really old and you need 5.15+

**Comment by Shandeika** [comment]
> > reinstall logs https://pastebin.com/rtjgmYad uname -a out: `Linux scott 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
> 
> this kernel is really old. looks like you are using Ubuntu 18.04 which is EOL and not longer supported here. Upgrade to 22.04
> 

20.04

**Comment by gOOvER** [comment]
> > > reinstall logs https://pastebin.com/rtjgmYad uname -a out: `Linux scott 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
> > 
> > 
> > this kernel is really old. looks like you are using Ubuntu 18.04 which is EOL and not longer supported here. Upgrade to 22.04
> 
> 20.04

still not really supported with latest Wine 8. You need 5.15 or later

**Comment by Shandeika** [comment]
> > > > reinstall logs https://pastebin.com/rtjgmYad uname -a out: `Linux scott 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
> > > 
> > > 
> > > this kernel is really old. looks like you are using Ubuntu 18.04 which is EOL and not longer supported here. Upgrade to 22.04
> > 
> > 
> > 20.04
> 
> still not really supported with latest Wine 8. You need 5.15 or later

Hmm, I tried to upgrade using `apt install linux-generic`, but got this:
```
root@scott:~# apt install linux-generic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-generic is already the newest version (5.4.0.152.149).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
This is strange

**Comment by QuintenQVD0** [comment]
> > > > > reinstall logs https://pastebin.com/rtjgmYad uname -a out: `Linux scott 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
> > > > 
> > > > 
> > > > this kernel is really old. looks like you are using Ubuntu 18.04 which is EOL and not longer supported here. Upgrade to 22.04
> > > 
> > > 
> > > 20.04
> > 
> > 
> > still not really supported with latest Wine 8. You need 5.15 or later
> 
> Hmm, I tried to upgrade using `apt install linux-generic`, but got this:
> 
> ```
> root@scott:~# apt install linux-generic
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> linux-generic is already the newest version (5.4.0.152.149).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> ```
> 
> This is strange

You have to upgrade to ubuntu-20.04 as 18.04 does not work and you are already on the latest release kernek for 18.04

**Comment by Shandeika** [comment]
> > > > > > reinstall logs https://pastebin.com/rtjgmYad uname -a out: `Linux scott 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
> > > > > 
> > > > > 
> > > > > this kernel is really old. looks like you are using Ubuntu 18.04 which is EOL and not longer supported here. Upgrade to 22.04
> > > > 
> > > > 
> > > > 20.04
> > > 
> > > 
> > > still not really supported with latest Wine 8. You need 5.15 or later
> > 
> > 
> > Hmm, I tried to upgrade using `apt install linux-generic`, but got this:
> > ```
> > root@scott:~# apt install linux-generic
> > Reading package lists... Done
> > Building dependency tree       
> > Reading state information... Done
> > linux-generic is already the newest version (5.4.0.152.149).
> > 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is strange
> 
> You have to upgrade to ubuntu-20.04 as 18.04 does not work and you are already on the latest release kernek for 18.04

```
root@scott:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by dgn-ramann** [comment]
> > After these actions, the server starts, but with errors
> > ```
> > container@pterodactyl~ Server marked as running...
> > steam user is not set.
> > 
> > Using anonymous user.
> > 
> > WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> > Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
> > [  0%] Checking for available updates...
> > [----] Verifying installation...
> > Steam Console Client (c) Valve Corporation - version 1686881296
> > -- type 'quit' to exit --
> > Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> > dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
> > OK
> > 
> > Connecting anonymously to Steam Public...OK
> > Waiting for client config...OK
> > Waiting for user info...OK
> > "@sSteamCmdForcePlatformType" = "windows"
> > Success! App '728470' already up to date.
> > :/home/container$ proton run ./Astro/Binaries/Win64/AstroServer-Win64-Shipping.exe
> > esync: up and running.
> > wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
> > ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> > ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> > ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> > ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
> > ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> > ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> > ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> > ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> > ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
> > ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> > ```
> 
> Those are normal. As the sound driver is not enabled.

Hi there,
I ran into the same problem but am running Ubuntu 22.04
do I need to install additional packages on my VM or what can be done/solved the issue?

**Comment by Shandeika** [comment]
> > > After these actions, the server starts, but with errors
> > > ```
> > > container@pterodactyl~ Server marked as running...
> > > steam user is not set.
> > > 
> > > Using anonymous user.
> > > 
> > > WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> > > Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
> > > [  0%] Checking for available updates...
> > > [----] Verifying installation...
> > > Steam Console Client (c) Valve Corporation - version 1686881296
> > > -- type 'quit' to exit --
> > > Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> > > dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
> > > OK
> > > 
> > > Connecting anonymously to Steam Public...OK
> > > Waiting for client config...OK
> > > Waiting for user info...OK
> > > "@sSteamCmdForcePlatformType" = "windows"
> > > Success! App '728470' already up to date.
> > > :/home/container$ proton run ./Astro/Binaries/Win64/AstroServer-Win64-Shipping.exe
> > > esync: up and running.
> > > wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
> > > ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> > > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> > > ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> > > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> > > ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> > > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> > > ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
> > > ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> > > ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> > > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> > > ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> > > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> > > ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> > > ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> > > ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
> > > ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
> > > ```
> > 
> > 
> > Those are normal. As the sound driver is not enabled.
> 
> Hi there, I ran into the same problem but am running Ubuntu 22.04 do I need to install additional packages on my VM or what can be done/solved the issue?

If you have the errors that you quoted, you can just forget about it. The sound does not affect the game in any way, it's the same server

**Comment by dgn-ramann** [comment]
Hi @Shandeika ,
Apart from those messages the server crashes as soon as i try to connect to the Port and then tries to restart, crash, restart, and so on. I have reinstalled the server multiple times.
Is there anything in the settings that could cause the problem? I have already successfully installed a handful of servers like this and have never had this problem.

**Comment by Shandeika** [comment]
Is there something in the logs when a crash occurs?

**Comment by dgn-ramann** [comment]
Unfortunately I cannot check right now but I will send an update later today.
Thank you for your help in advance!

**Comment by Doctober** [comment]
Hi, reporting back from a different account (originally dgn-ramann)
got the server running after updating my vm to the latest ubuntu 22.04, shouldve done that since i havent for a couple months
