### ISSUE TITLE
[Egg Request]: <MTASA-BLUE>

### ISSUE THREAD

**Issue by uNippw** [parkervcp/eggs#2304]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/multitheftauto/mtasa-blue

### Links for the download

https://github.com/multitheftauto/mtasa-blue

### Links for the install docs

https://github.com/multitheftauto/mtasa-blue

**Comment by gOOvER** [comment]
> For arm64

ARM architectures are currently in experimental phase, which means they're unstable, untested and may crash randomly. 

Feel free to create an egg for it
