### ISSUE TITLE
[Bug]: Minecraft, Paper

### ISSUE THREAD

**Issue by Bobbbe** [parkervcp/eggs#2305]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

just start normally like everyday

### Actual Behavior

Hello, I am updating minecraft 1.19.3 to 1.20.1 and in the console I have this error, "[org.eclipse.aether.internal.impl.synccontext.named.DiscriminatingNameMapper] Failed to get hostname, using 'localhost' "Any idea what is different between 1.19.3 and 1.20.1 and where I should change? i'm past to pastbin for complete error in console. https://pastebin.com/yuX6AJtc
I'm try java 18 and same... i'm change 127.0.0.1  localhost for 127.0.0.1  [hostname] localhost in etc/host file nothing change !
you have a idea ?

### Steps To Reproduce

just change version of minecraft

### Install logs

dont have

**Comment by gOOvER** [comment]
use discord for Support.

**Comment by QuintenQVD0** [comment]
You somewhere edited 0.0.0.0 to localhost. Last time i tested it. It worked fine. And you changed the startup args so at this point it is not supported anymore.

**Comment by Bobbbe** [comment]
I would have changed the o.o.o.o to localhost where? in the etc/host file? but it was already like this,
I tested and put it back as it was. here is my etc/host as it is now originally and i still have the same error.
```127.0.0.1  localhost

::1	localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters


127.0.1.1	debian.example.com
127.0.1.1	ns3054476.ip-213-32-6.eu	ns3054476```

**Comment by gOOvER** [comment]
again; GITHUB is not 4 support and your problem have nothing to do with the egg

**Comment by Bobbbe** [comment]
oh! ok thx if it does not come from the egg i'm try discord but in which section ?

**Comment by gOOvER** [comment]
> oh! ok thx if it does not come from the egg i'm try discord but in which section ?

#linux-help

**Comment by Bobbbe** [comment]
thx, have a nice day :)

**Comment by QuintenQVD0** [comment]
As previous mentioned, this is for the discord.

**Comment by Cyanoure** [comment]
It would be nice if I could read the solution here.

**Comment by YuanYuanOwO** [comment]
It would be nice if I could read the solution here.

**Comment by CarmJos** [comment]
It would be nice if I could read the solution here.
