### ISSUE TITLE
Not able to install / update : Alt:v

### ISSUE THREAD

**Issue by Davinel17** [parkervcp/eggs#2307]
### Panel Version

1.11.3

### Wings Version

1.11.2

### Service

GTA V/Alt:V

### Modified

No, I did not modify the egg

### Expected Behavior

install / update the egg ,  start and play without error

### Actual Behavior

when you install or update, receive this error at the end :

[Error] Failed to check for update, try again later

### Steps To Reproduce

Install a server with the Alt:V egg

### Install logs

https://pteropaste.com/673cz6114f6d/

**Comment by QuintenQVD0** [comment]
@Davinel17 Please test the linked PR
