### ISSUE TITLE
[Bug]: SinusBot

### ISSUE THREAD

**Issue by Stormez1998** [parkervcp/eggs#2308]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

SinusBot

### Modified

No, I did not modify the egg

### Expected Behavior

Install the Server, WebPanel of bot is Running but when i Try to connect it to a Server it wont connect or go online.

### Actual Behavior

"error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory"

I made sure i have installed all in dependencies on the server, including libevent. But it brings all time the same Message in the log. Down i have what it looks like when i "try" to install the dependencies of SinusBot.

apt-get install -y x11vnc xvfb libxcursor1 ca-certificates curl bzip2 libnss3 libegl1-mesa x11-xkb-utils libasound2 libpci3 libxslt1.1 libxkbcommon0 libxss1 libxcomposite1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libasound2 is already the newest version (1.2.4-1.1).
bzip2 is already the newest version (1.0.8-4).
ca-certificates is already the newest version (20210119).
curl is already the newest version (7.74.0-1.3+deb11u7).
libxcomposite1 is already the newest version (1:0.4.5-1).
libxcursor1 is already the newest version (1:1.2.0-2).
libxkbcommon0 is already the newest version (1.0.3-2).
libxslt1.1 is already the newest version (1.1.34-4+deb11u1).
libxss1 is already the newest version (1:1.2.3-1).
libegl1-mesa is already the newest version (20.3.5-1).
libnss3 is already the newest version (2:3.61-1+deb11u3).
libpci3 is already the newest version (1:3.7.0-5).
x11-xkb-utils is already the newest version (7.7+5).
x11vnc is already the newest version (0.9.16-7).
xvfb is already the newest version (2:1.20.11-1+deb11u6).
libglib2.0-0 is already the newest version (2.66.8-1).
libevent-2.1-7 is already the newest version (2.1.12-stable-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

### Steps To Reproduce

Tryed to reinstall
tryed to install all dependencies 

### Install logs

https://pteropaste.com/4nu2tjxjml15/

**Comment by QuintenQVD0** [comment]
Does not mather as you are in docker.

**Comment by Stormez1998** [comment]
yeah thats also what i thought ^^ So do you ever heard of that?

**Comment by QuintenQVD0** [comment]
@Stormez1998 please test with `quintenqvd/pterodactyl_images:temp_sinusbot` if it works then leave a revieuw on the yolks PR

**Comment by Stormez1998** [comment]
@QuintenQVD0 Thanks for your Reply but im a littlebit stupid or not that know with Github, i found what you changed but i dont know touse it to import into Petodactyl :) Would you be so nice to explain it a bit Detailed to me what i have to dot. An i understood that i can make a review after it worked that you can close it :) TY

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Thanks for your Reply but im a littlebit stupid or not that know with Github, i found what you changed but i dont know touse it to import into Petodactyl :) Would you be so nice to explain it a bit Detailed to me what i have to dot. An i understood that i can make a review after it worked that you can close it :) TY

Set the docker image of the server to the one I told you. Then restart the server. It will pull the new image. If the error goos away then press the button that sends you to the yolks pr. Just scroll down and add a comment like : tested and fixt.

**Comment by Stormez1998** [comment]
i tryed it but now i get a diffrent error after i pastet in like you said, installation worked well (Fresh Setup) 
![image](https://github.com/parkervcp/yolks/assets/57358176/c16b9397-9dcb-4603-be65-e8baf3160513)

Now i get a the same Messag but now it is missing liblcms2.so.2

`2023/06/18 23:17:41 e82a182f 06ab179e DEBUG  TS>/home/container/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: error while loading shared libraries: liblcms2.so.2: cannot open shared object file: No such file or directory`

**Comment by QuintenQVD0** [comment]
> i tryed it but now i get a diffrent error after i pastet in like you said, installation worked well (Fresh Setup) ![image](https://user-images.githubusercontent.com/57358176/246691232-c16b9397-9dcb-4603-be65-e8baf3160513.png)
> 
> Now i get a the same Messag but now it is missing liblcms2.so.2
> 
> `2023/06/18 23:17:41 e82a182f 06ab179e DEBUG TS>/home/container/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: error while loading shared libraries: liblcms2.so.2: cannot open shared object file: No such file or directory`

I look in to it. My machine did not have that error.

**Comment by QuintenQVD0** [comment]
@Stormez1998 I update my dev image try agian please.

also reinstall first

**Comment by Stormez1998** [comment]
I don't want to be a spoilsport, but I have the same error again, but this time libatomic.so.1 is missing

`2023/06/19 11:06:04 c45eca48 d87919f3 DEBUG  TS>/home/container/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

**Comment by QuintenQVD0** [comment]
The packages are now fixt in the Yolks PR but it will still not work as the client is buggy as hell, see: https://community.teamspeak.com/t/teamspeak-3-client-3-6-0/41112

**Comment by Stormez1998** [comment]
From Sinusbot Discord:

![image](https://github.com/parkervcp/eggs/assets/57358176/c676785f-dbef-4f9e-a762-ee56e85c26ab)
