### ISSUE TITLE
[Egg Feature Request]: Auto install and updater for eggs

### ISSUE THREAD

**Issue by louanfontenele** [parkervcp/eggs#2313]
### Does this expand an already existing service

No

### Link to a game or software

https://pterodactyl.io/

### Links for the download

https://pterodactyl.io/

### Links for the install docs

https://pterodactyl.io/project/introduction.html

### Feature Request
It would be interesting to have a panel/script directly in the pterodactyl administrative panel, which could automatically download and update the eggs from this git repository.

**Comment by lilkingjr1** [comment]
While I like this idea, please submit this feedback to https://github.com/pterodactyl/panel or the Discord. This repo is not responsible, nor has the means to implement, this functionality you request.
