### ISSUE TITLE
[Bug]: RabbitMQ

### ISSUE THREAD

**Issue by furryformula** [parkervcp/eggs#2314]
### Panel Version

1.11.3

### Wings Version

1.11.3

### Service

RabbitMQ

### Modified

No, I did not modify the egg

### Expected Behavior

I install the egg with the Json without modifying anything, I create the server with the image "ghcr.io/parkervcp/yolks:erlang_26" and I even put version 3.12.0 (I also tried it with "latest"), I assign port 5672 (I also open in my VM tcp and udp) but when starting the server it crashes immediately.

I am using Oracle Cloud always free

I iven try with other combinations like:

V: 3.11.18 erlang_25
V3.12.0 erlang_25

take a look at the https://www.rabbitmq.com/which-erlang.html page for compatibility checks

### Actual Behavior

Error Event [ffeef1e0-f9ce-4732-bd15-12ed6cbf592c]: environment/docker: failed to run pre-boot process: environment/docker: failed to create container: Error response from daemon: No such image: ghcr.io/parkervcp/yolks:erlang_26

### Steps To Reproduce

Install Json
Select image ghcr.io/parkervcp/yolks:erlang_26
assign port 5672
Run the server

### Install logs

*

**Comment by furryformula** [comment]
Log

[cmd.txt](https://github.com/parkervcp/eggs/files/11827830/cmd.txt)

**Comment by danny6167** [comment]
I think you will find the egg/yolk doesn't support arm, and that's why you're having issues.
