### ISSUE TITLE
[Egg Request]: Nginx or Apache with PHP

### ISSUE THREAD

**Issue by zigazajc007** [parkervcp/eggs#2316]
### Does this expand an already existing service

No

### Link to a game or software

https://www.php.net

### Links for the download

https://www.php.net/downloads.php

### Links for the install docs

https://www.vultr.com/docs/how-to-install-nginx-mariadb--php-lemp-on-debian-11-99568/

**Comment by gOOvER** [comment]
not needed. you have a running apache or ngix server on your Host system

I hate vacations

**Comment by zigazajc007** [comment]
Lets encrypt / SSL certs can be skipped and a external proxy manager can be used, so you will only deploy website on a random port and use external proxy manager to handle with SSL certs.

**Comment by QuintenQVD0** [comment]
Pterodactyl is not made for webhosting and it is also not supported!

**Comment by zigazajc007** [comment]
Pterodactyl is capable enough to become a web-hosting.

It has build in MySQL / MariaDB support and easy to use file manager / FTP
