### ISSUE TITLE
[Bug]: Satisfactory Egg Update 8

### ISSUE THREAD

**Issue by Spielepapagei** [parkervcp/eggs#2317]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

Satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

The Server sould start normaly

### Actual Behavior

:/home/container$ ./Engine/Binaries/Linux/UE4Server-Linux-Shipping FactoryGame ?listen -Port=${SERVER_PORT} -ServerQueryPort=${QUERY_PORT} -BeaconPort=${BEACON_PORT} -multihome=0.0.0.0 $(if ${DISABLE_SEASONAL}; then echo "-DisableSeasonalEvents"; fi)
/entrypoint.sh: line 73: ./Engine/Binaries/Linux/UE4Server-Linux-Shipping: No such file or directory

### Steps To Reproduce

Setp 1 Install Satisfactory Egg
Step 2 Change branche to Experimantel
Step 3 Start Server

### Install logs

https://pteropaste.com/i2ayrinfipee/

**Comment by QuintenQVD0** [comment]
egg was already updated. your local egg is old: https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/satisfactory

https://github.com/parkervcp/eggs/pull/2299
