### ISSUE TITLE
[Egg Request]: Sons Of The Forest

### ISSUE THREAD

**Issue by HerrSammyDE** [parkervcp/eggs#2318]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/

### Links for the download

N/A

### Links for the install docs

https://xgamingserver.com/blog/how-to-set-up-a-dedicated-server-for-sons-of-the-forest/

**Comment by HerrSammyDE** [comment]
The game developers have announced that they will soon offer dedicated server support, so I have already created the Egg Request.
https://store.steampowered.com/news/app/1326470/view/3689059134030584436

As soon as there is more info about it, I would post it here

**Comment by yesBad** [comment]
Just saying that install doc link is for The Forest.

**Comment by HerrSammyDE** [comment]
Oh okay - then we still have to wait for the update....

**Comment by QuintenQVD0** [comment]
This 100% will be forgoten. You only open a egg request if the game server is out and there some decent docs out. An will there be linuw support or will wine be needed?

**Comment by HerrSammyDE** [comment]
> This 100% will be forgoten. You only open a egg request if the game server is out and there some decent docs out. An will there be linuw support or will wine be needed?

I don't think that will be forgotten when the update is apparently supposed to come today. I think wine

**Comment by QuintenQVD0** [comment]
I wil add it to my to do list for wine or proton. Please ping me if you have the steamdb page. This will be for Wednesday.

**Comment by marekgrebac** [comment]
> I wil add it to my to do list for wine or proton. Please ping me if you have the steamdb page. This will be for Wednesday.

https://steamdb.info/app/2465200/

**Comment by PrinceBunBun981** [comment]
> ### Does this expand an already existing service
> No
> 
> ### Link to a game or software
> https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/
> 
> ### Links for the download
> N/A
> 
> ### Links for the install docs
> https://xgamingserver.com/blog/how-to-set-up-a-dedicated-server-for-sons-of-the-forest/

Here are the proper docs, since the link provided was for The Forest.
https://steamcommunity.com/sharedfiles/filedetails/?id=2992700419

**Comment by Draakoor** [comment]
Looks like you can use the forest egg but you need some customisations for it. I will look into it later

**Comment by Draakoor** [comment]
[egg-sons-of-the-forest.txt](https://github.com/parkervcp/eggs/files/11852875/egg-sons
<img width="267" alt="2023-06-23 22_43_09-test _ Console" src="https://github.com/parkervcp/eggs/assets/11836348/52da656b-b727-46d8-addb-498bce847877">
-of-the-forest.txt)

I attached a working egg. It uses ghcr.io/parkervcp/yolks:wine_latest.
But I got one problem is spaming some errors in the console also the config is not working correctly. If somebody fixes this this should be the egg for sons of the forest

**Comment by killertobyd** [comment]
Where does the server put its COnfig ? haven't found it so far

**Comment by vp-en** [comment]
I think I'd rather wait for @QuintenQVD0's egg, or go for a regular docker one, e.g. [1](https://github.com/ich777/docker-steamcmd-server/tree/sonsoftheforest) or [2 (when that's ready to go](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server).

Also Quinten - you asked specifically to get pinged with SteamDB (and documentation)

**SteamDB app id:**
https://steamdb.info/app/2465200/

**Documentation:**
https://steamcommunity.com/sharedfiles/filedetails/?id=2992700419

**Comment by QuintenQVD0** [comment]
Thank you all for the documentation. I will make a egg just give a couple of hours as I am just awake. I also likly will use proton and not wine directly.

**Comment by gOOvER** [comment]
> Thank you all for the documentation. I will make a egg just give a couple of hours as I am just awake. I also likly will use proton and not wine directly.

use wine. works fine with staging

**Comment by gOOvER** [comment]
> https://github.com/Draakoor/eggs/blob/master/game_eggs/steamcmd_servers/sonsoftheforest/egg-sons-of-the-forest.json <img alt="2023-06-23 22_43_09-test _ Console" width="267" src="https://user-images.githubusercontent.com/11836348/248401257-52da656b-b727-46d8-addb-498bce847877.png"> -of-the-forest.txt)
> 
> I attached a working egg. It uses ghcr.io/parkervcp/yolks:wine_latest. But I got one problem is spaming some errors in the console also the config is not working correctly. If somebody fixes this this should be the egg for sons of the forest

you dont need xvfb, disable sound, GLST

SOTF works fine without
