### ISSUE TITLE
[Egg Request]: Zombie Panic! Source

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2319]
### Does this expand an already existing service

No

### Link to a game or software

https://zombiepanicsource.com/

### Links for the download

https://steamdb.info/app/17505/

### Links for the install docs

https://steamcommunity.com/sharedfiles/filedetails/?id=2243196939

**Comment by PsychoZander** [comment]
You can use the built in Custom Source Engine Game egg to create a ZPS server with ease. Here's a link to the documentation for the egg:

https://github.com/parkervcp/eggs/tree/master/stock_eggs/source-engine#custom-source-engine-game

**Comment by QuintenQVD0** [comment]
As mentioned the generic source egg thar comes with the panel will run this.
