### ISSUE TITLE
[Bug]: Unturned

### ISSUE THREAD

**Issue by zigazajc007** [parkervcp/eggs#2322]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

unturned

### Modified

No, I did not modify the egg

### Expected Behavior

Be able to log into the server.

![Screenshot 2023-06-26 101630](https://github.com/parkervcp/eggs/assets/44822563/67903c19-1f48-477f-a441-c70bbecade0a)

Unturned egg should accept Game Server Login Token.

### Actual Behavior

As Game Server Login Token (GSLT) is not / can't be provided we can't log into the server with this egg.

### Steps To Reproduce

Step 1: Download Unturned egg
Step 2: Upload Unturned egg
Step 3: Create a server with Unturned egg

### Install logs

Egg doesn't have an error, but it does not accept required parameter (GSLT)

**Comment by Griffeng** [comment]
For the unturned server there is no variable for adding a GSLT token but you can still add it in you config (servers/default/config.json - Login_Token)

I will make a PR with an updated egg that includes an option for adding a GSLT token as a variable
