### ISSUE TITLE
[Install Bug]: Valheim Vanilla

### ISSUE THREAD

**Issue by Micim987** [parkervcp/eggs#2327]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Valheim Vanilla

### Modified

No, I did not modify the egg

### Expected Behavior

I expected the server to install start normally

### Actual Behavior

Server failed installation with the error 
`Error Event [1bf0db0d-2f2c-4130-871b-5d466db1ba4d]: environment/docker: failed to run pre-boot process: environment/docker: failed to create container: Error response from daemon: No such image: ghcr.io/parkervcp/games:valhei`

### Steps To Reproduce

Install the egg in the latest version of Pterodactyl/Wings
Attempt to install a server with the egg selected
Server fails to install with the error above

### Install logs

https://pteropaste.com/d58vwy730r47

**Comment by parkervcp** [comment]
I know for a fact that the command works on rocky linux. Please run `uname -a`

**Comment by Micim987** [comment]
Sorry I wasn't logged in as root for the command. I've updated the top comment with the link

**Comment by danny6167** [comment]
This game/egg does not support arm.

**Comment by QuintenQVD0** [comment]
Steamcmd foes not work on arm64
