### ISSUE TITLE
[Bug]: The isle

### ISSUE THREAD

**Issue by andy01745** [parkervcp/eggs#2329]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

game_eggs/steamcmd_servers/the_isle/evrima

### Modified

No, I did not modify the egg

### Expected Behavior

The server to install and being able to connect.

### Actual Behavior

The server installed with the egg just fine. After it has done installing and all ports are open. I get an error 

2]LogTemp: Warning: Failed to start Session!

I have been getting very frustrated with not being able to connect to the server with all the correct ports open. Any other steam game is fine. I can connect with no problems. I have a feeling it has something to do with the error shown above. 

I look over the list of servers in game and can not find my server anywhere no matter what I do or what ports I use. 

Also adding the server to my favourites in steam I just get this. 
![image](https://github.com/parkervcp/eggs/assets/84942293/797b8615-08b6-4427-b5a6-a9fe01d0e1b8)

Server responds with [2023.06.28-21.17.16:362][411]LogNet: NotifyAcceptingConnection accepted from: My_ip_here:58101

### Steps To Reproduce

1). Set to the latest version 
2). Install
3). try and connect

### Install logs

https://nothing_to_do_with_wings

**Comment by gOOvER** [comment]
logs?

**Comment by andy01745** [comment]
What logs would you be looking for?

**Comment by QuintenQVD0** [comment]
> What logs would you be looking for?

install logs and console logs

**Comment by QuintenQVD0** [comment]
I and [enozii](https://github.com/parkervcp/eggs/commits?author=enozii) pushed some updates to this egg and were able to join so this sounds like a configuration issue, if you still have that, update your egg and post install logs in the discord.
