### ISSUE TITLE
[Bug]: v_rising_bepinex

### ISSUE THREAD

**Issue by vMax-dev1** [parkervcp/eggs#2330]
### Panel Version

1.11.3

### Wings Version

1.11.x

### Service

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/v_rising/v_rising_bepinex

### Modified

No, I did not modify the egg

### Expected Behavior

server is blocking

### Actual Behavior

![image](https://github.com/parkervcp/eggs/assets/4140252/cd650ff6-7e8b-4e67-adcc-4a35ba8cb371)
![image](https://github.com/parkervcp/eggs/assets/4140252/01b875be-5572-40e7-8dad-81426acf7591)

### Steps To Reproduce

install last version bepinex, and start it for reproduce error

### Install logs

https://pteropaste.com/e915p0fmtmvo

**Comment by gOOvER** [comment]
or use latest egg. there is a pr allready merged to support latest patch

**Comment by gOOvER** [comment]
@MaXx-62 is a wine error and have nothing to do with the egg.

please post more infos for your Sytem; Kernel version, distro

**Comment by MaXx-62** [comment]
> or use latest egg. there is a pr allready merged to support latest patch

i try with latest egg and it work, thx

**Comment by OfficiallySp** [comment]
i am getting the same issue as this but with the latest bepinex egg. vanilla works fine however

**Comment by gOOvER** [comment]
they are using bepinex 6 now insteed 5. need some testing

**Comment by gOOvER** [comment]
> i am getting the same issue as this but with the latest bepinex egg. vanilla works fine however

works fine for me

**Comment by OfficiallySp** [comment]
huh very wierd. am using the latest version of wings on ubuntu 22.04

**Comment by gOOvER** [comment]
> huh very wierd. am using the latest version of wings on ubuntu 22.04. i've tried reinstalling to no luck

use the latest egg. Wings have nothing to do with such an issue. Pls post the full log

**Comment by OfficiallySp** [comment]
https://pteropaste.com/7jl7b1e3tvt7/ with the latest egg
