### ISSUE TITLE
[Egg Request]: Spacestation 14

### ISSUE THREAD

**Issue by Fiftyllama** [parkervcp/eggs#2333]
### Does this expand an already existing service

No

### Link to a game or software

https://spacestation14.io/

### Links for the download

https://central.spacestation14.io/builds/wizards/builds.html

### Links for the install docs

https://docs.spacestation14.io/en/getting-started/hosting

**Comment by QuintenQVD0** [comment]
I wanted to make an egg for this but there website is down

**Comment by Fiftyllama** [comment]
Yeah, it seems they're down (just my luck 😅)
I talked to the Devs, they said they expect it to be back up within the day @QuintenQVD0

**Comment by QuintenQVD0** [comment]
> Yeah, it seems they're down (just my luck 😅) I talked to the Devs, they said they expect it to be back up within the day @QuintenQVD0

I have the basics working. Just need to setup the parser so thar port and servername automatically get set.
