### ISSUE TITLE
[BUG]: <Vintage STory>

### ISSUE THREAD

**Issue by SneaKz123** [parkervcp/eggs#2346]
### Panel Version

1.10.4

### Wings Version

1.7.2

### Service

game_eggs/vintage_story

### Modified

No, I did not modify the egg

### Expected Behavior

Install it, start it, play

### Actual Behavior

Install it, try to start it, crashing with following error whilest starting:

[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ eval java -Xms128M -Xmx${SERVER_MEMORY}M -Dterminal.jline=false -Dterminal.ansi=true $( [ ! -f unix_args.txt ] && printf %s "-jar ${SERVER_JARFILE}" || printf %s "@unix_args.txt" )
/entrypoint.sh: line 13: java: command not found
container@pterodactyl~ Server wechselt in den Status offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

Just setup a Vintage Story Server

### Install logs

https://pteropaste.com/d96ba32g8nu8

**Comment by RogueRaiden** [comment]
It appears its trying to launch using java??

Vintage story doesn't use java. It uses mono on linux until the .net7 version, then it uses .net7

**Comment by diedyesterdaywashere** [comment]
![image](https://github.com/parkervcp/eggs/assets/81169193/b7e28ce7-f354-49e1-8cfb-f769c4a04e85)
@SneaKz123 are you sure that you're using vintage story egg, because it does not launch with java

**Comment by diedyesterdaywashere** [comment]
![image](https://github.com/parkervcp/eggs/assets/81169193/558d7a4c-ff64-4ac4-83c1-cd4e1c76426a)
just installed the server and it runs perfectly

**Comment by diedyesterdaywashere** [comment]
> It appears they are using the Vintage egg (or at least the correct image) but have a minecraft (likely forge) startup line. Did you install a minecraft server and then change the egg or something ?

yeah it's probably that

**Comment by parkervcp** [comment]
If you changed the egg the server is using the startup needs to be changed as well.

**Comment by SneaKz123** [comment]
Hi there,

thanks for the comments!

I've changed the Server Egg and totally forgot that the startup command doesn't change by itself!
The problem is solved now!
