### ISSUE TITLE
[Egg Request]: Minecraft Quilt

### ISSUE THREAD

**Issue by Fishvap** [parkervcp/eggs#2348]
### Does this expand an already existing service

Yes

### Link to a game or software

https://quiltmc.org/en/

### Links for the download

https://quiltmc.org/en/install/server/

### Links for the install docs

https://quiltmc.org/en/install/server/#cli-installation https://quiltmc.org/en/usage/

**Comment by Fishvap** [comment]
I would say that this is an essential MC egg as it impacts many users to not have an easy-to-access Quilt egg (many Minecraft Fabric mods have decided to move to Quilt as they feel that it is easier for them and the community is better, I don't entirely agree but it means that many Quilt mods do not work on Fabric but a majority of Fabric mods work on Quilt. Quilt is basically just Fabric but developers wanted to get away from the community due to drama and now they are attempting to improve the existing systems.

**Comment by diedyesterdaywashere** [comment]
so uh i'll try to make an egg for quilt right now, i'll keep you updated
