### ISSUE TITLE
[Bug]: <Sons of the Forest>

### ISSUE THREAD

**Issue by pixelwave** [parkervcp/eggs#2352]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

sonsoftheforest

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Server running and being able to type commands.

### Actual Behavior

Not able to type commands, server Command Output:

container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_staging 
Digest: sha256:2061c754bc49c444a5bd547c8da1f1b1bfb5147ab3dca904c5b8ba00de34be4e 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 11.7
Current timezone: Etc/UTC
wine-8.11 (Staging)
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1687387651
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
dlmopen libSDL3.so.0 failed: libSDL3.so.0: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '2465200' already up to date.
First launch will throw some errors. Ignore them
Installing mono
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Installing vcrun2019
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: 0f7e30aee05ab6747ef0d6a089830b91f90a4f70534b6ec581e75ef1eb71fa68 with wine-8.11 (Staging) and WINEARCH=win64
Executing w_do_call vcrun2019
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
vcrun2019 already installed, skipping
:/home/container$ wine ./SonsOfTheForestDS.exe -userdatapath "/home/container/serverconfig" -dedicatedserver.IpAddress "0.0.0.0" -dedicatedserver.GamePort "${SERVER_PORT}" -dedicatedserver.QueryPort "${QUERY_PORT}" -dedicatedserver.BlobSyncPort "${BLOBSYNC_PORT}" -dedicatedserver.MaxPlayers "${MAX_PLAYERS}" -dedicatedserver.Password "${SRV_PW}" -dedicatedserver.GameMode "${GAME_MODE}" -dedicatedserver.LogFilesEnabled "true" -dedicatedserver.TimestampLogFilenames "true"
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Initialize engine version: 2022.2.16f1 (d535843d11e1)
[Subsystems] Discovering subsystems at path Z:/home/container/SonsOfTheForestDS_
Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0; jobified=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
There is no texture data available to upload.
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subsh
aders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Hidden/HDRP/FallbackError' - All subshaders remove
d
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader Hidden/HDRP/FallbackError shader is not supported on this GPU (non
e of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Hidden/HDRP/FallbackError' - All subshaders remove
d
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
WARNING: Shader Unsupported: 'HDRP/Lit' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader HDRP/Lit shader is not supported on this GPU (none of subshaders/f
allbacks are suitable)
WARNING: Shader Unsupported: 'HDRP/Lit' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
WARNING: Shader Unsupported: 'Hidden/HDRP/MaterialError' - All subshaders remove
d
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader Hidden/HDRP/MaterialError shader is not supported on this GPU (non
e of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Hidden/HDRP/MaterialError' - All subshaders remove
d
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader Hidden/HDRP/CameraMotionVectors shader is not supported on this GP
U (none of subshaders/fallbacks are suitable)
ERROR: Shader Hidden/HDRP/GGXConvolve shader is not supported on this GPU (none
of subshaders/fallbacks are suitable)
ERROR: Shader Hidden/HDRP/OpaqueAtmosphericScattering shader is not supported on
 this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Shader Graphs/Water' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
WARNING: Shader Unsupported: 'Shader Graphs/Water' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader Hidden/HDRP/CustomPassRenderersUtils shader is not supported on th
is GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Hidden/HDRP/FinalPass shader is not supported on this GPU (none of
 subshaders/fallbacks are suitable)
ERROR: Shader Hidden/PostProcessing/SubpixelMorphologicalAntialiasing shader is
not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Hidden/HDRP/LensFlareDataDriven shader is not supported on this GP
U (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Shader Graphs/SolidColor' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader Shader Graphs/SolidColor shader is not supported on this GPU (none
 of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Shader Graphs/SolidColor' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
WARNING: Shader Unsupported: 'HDRP/DefaultFogVolume' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader HDRP/DefaultFogVolume shader is not supported on this GPU (none of
 subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'HDRP/DefaultFogVolume' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten tu
rning Fallback off?
ERROR: Shader Sons/HDRPLit shader is not supported on this GPU (none of subshade
rs/fallbacks are suitable)
ERROR: Shader Hidden/VoxelizeShader shader is not supported on this GPU (none of
 subshaders/fallbacks are suitable)
Microsoft Media Foundation video decoding to texture disabled: graphics device i
s Null, only Direct3D 11 and Direct3D 12 (only on desktop) are supported for har
dware-accelerated video decoding.
Texture2DArray is not supported on this platform/GPU
UnityEngine.Texture2DArray:Internal_Create(Texture2DArray, Int32, Int32, Int32,
Int32, GraphicsFormat, TextureCreationFlags)
UnityEngine.Texture2DArray:.ctor(Int32, Int32, Int32, TextureFormat, Int32, Bool
ean, Boolean)
UnityEngine.Texture2DArray:.ctor(Int32, Int32, Int32, TextureFormat, Boolean, Bo
olean)
Crest.TextureArrayHelpers:CreateTexture2DArray(Texture2D)
Crest.TextureArrayHelpers:CreateBlackTexArray()
Crest.TextureArrayHelpers:InitStatics()

[ line 1109160]

UnityException: Failed to create 2D array texture because of invalid parameters.
  at UnityEngine.Texture2DArray.Internal_Create (UnityEngine.Texture2DArray mono
, System.Int32 w, System.Int32 h, System.Int32 d, System.Int32 mipCount, UnityEn
gine.Experimental.Rendering.GraphicsFormat format, UnityEngine.Experimental.Rend
ering.TextureCreationFlags flags) [0x00000] in <00000000000000000000000000000000
>:0
  at UnityEngine.Texture2DArray..ctor (System.Int32 width, System.Int32 height,
System.Int32 depth, UnityEngine.TextureFormat textureFormat, System.Int32 mipCou
nt, System.Boolean linear, System.Boolean createUninitialized) [0x00000] in <000
00000000000000000000000000000>:0
  at UnityEngine.Texture2DArray..ctor (System.Int32 width, System.Int32 height,
System.Int32 depth, UnityEngine.TextureFormat textureFormat, System.Boolean mipC
hain, System.Boolean linear) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.TextureArrayHelpers.CreateTexture2DArray (UnityEngine.Texture2D textu
re) [0x00000] in <00000000000000000000000000000000>:0
  at Crest.TextureArrayHelpers.CreateBlackTexArray () [0x00000] in <000000000000
00000000000000000000>:0
  at Crest.TextureArrayHelpers.InitStatics () [0x00000] in <00000000000000000000
000000000000>:0
Rethrow as TypeInitializationException: The type initializer for 'Crest.TextureA
rrayHelpers' threw an exception.

[EnvironmentArgs] ...
{"-userdatapath":"/home/container/serverconfig","-dedicatedserver.IpAddress":"0.
0.0.0","-dedicatedserver.GamePort":"8766","-dedicatedserver.QueryPort":"27016","
-dedicatedserver.BlobSyncPort":"9700","-dedicatedserver.MaxPlayers":"4","-dedica
tedserver.Password":"Buschnattern$69","-dedicatedserver.GameMode":"normal","-ded
icatedserver.LogFilesEnabled":"true","-dedicatedserver.TimestampLogFilenames":"t
rue"}
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Endnight.Utilities.CommandLine.EnvironmentArgs:get_Instance()
Sons.Utilities.SonsPaths:InitializeUserDataPath()
System.Lazy`1:ViaFactory(LazyThreadSafetyMode)
System.Lazy`1:ExecutionAndPublication(LazyHelper, Boolean)
System.Lazy`1:CreateValue()
Endnight.Utilities.Dedicated.HeadlessLogHandler:HookHeadlessLogHandler()

User data path is overriden to: Z:\home\container\serverconfig
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Sons.Utilities.SonsPaths:InitializeUserDataPath()
System.Lazy`1:ViaFactory(LazyThreadSafetyMode)
System.Lazy`1:ExecutionAndPublication(LazyHelper, Boolean)
System.Lazy`1:CreateValue()
Endnight.Utilities.Dedicated.HeadlessLogHandler:HookHeadlessLogHandler()

ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshade
rs/fallbacks are suitable)
UnloadTime: 0.546300 ms
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default

### Steps To Reproduce

Install and start Sons of the forest server.

### Install logs

https://pteropaste.com/wuhzv5cm9i5f

**Comment by pixelwave** [comment]
Ah ok - but it also does not seem to start / work properly. I can not find it either online nor in LAN. Firewall rules are added for the three main ports as stated ..

**Comment by parkervcp** [comment]
You should add the server to the favorites in steam. Some servers don't show as online for some reason

**Comment by pixelwave** [comment]
Managed now to show it in the game browser.
