### ISSUE TITLE
[Bug]: Stormworks: Build and Rescue (Error connecting to server)

### ISSUE THREAD

**Issue by vp-en** [parkervcp/eggs#2355]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

SteamCMD --> Stormworks: Build and Rescue

### Modified

No, I did not modify the egg

### Expected Behavior

I installed the server from [the egg](https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/stormworks), and I kept all settings to default.

I allocated the default ports (25564, 25565 and 25566) and setup the egg using those ports.

The server seems to be working, according to the logs, and it [shows up in the ingame browser](https://i.imgur.com/c6b3jXn.png)

### Actual Behavior

But I can't connect to the server. It gives a "Error connecting to server: Disconnected from server" message, after seemingly timing out.

### Steps To Reproduce

1) Grab the egg from [here](https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/stormworks)

2) Set up a new server, using the default ports for the game, in this case `25565`, `25566` and `25567`

3) Wait for the installation to complete

4) Get to the part, where the console changes output to something [like this](https://i.imgur.com/fprOCVt.png)

5) Try and connect to the server ingame

6) You get the "Error connecting to server: Disconnected from server" after waiting a few seconds

### Install logs

https://paste.ec/paste/346-7XH8#bbsOQI6UQpV5RIx3sEeNTaoVrLz0uRrlewojzbXe2V3

**Comment by QuintenQVD0** [comment]
Notthing wrong with the install. Are the ports open in the firewall (udp and tcp) ad some hostings block udp by default.

**Comment by vp-en** [comment]
I have no firewall setup on my dedicated server from Hetzner, other than "allow all", and no ufw active on my Ubuntu setup:
https://i.imgur.com/5snOUOR.png

My iptables -L only shows docker related stuff as well:
https://paste.ec/paste/Bz3WWgql#xmK+4FB4ijcs71uDcGiZVr9-ZYoJ3x2zXIrql4Z9Fdk

I don't have any set rules, other than what Docker creates by itself. I have a [few other game servers](https://i.imgur.com/T3F53Mx.png) that can connect fine, so I'm not sure if it's an issue with Wine and this game specifically?

**Comment by QuintenQVD0** [comment]
@vp-en where do you host?

**Comment by vp-en** [comment]
> @vp-en where do you host?

@QuintenQVD0 
Do you mean location wise? I'm using a [EX101](https://www.hetzner.com/dedicated-rootserver/ex101) server, based in Hetzner's datacenter in Helsinki, Finland. I still can't connect to the server.

Originally when I made this issue, the server was hosted in their datacenter in Falkenstein, Germany. But that location didn't work out for me, so I since moved it to the Helsinki datacenter.

**Comment by delphyinium** [comment]
@vp-en Hey, I have alot of experience with Hetzner products, and can say that the allow all firewall rule really doesn't mean much. I would go into the firewall config and add all of those ports manually, for both TCP and UDP. Might solve your problem.

**Comment by vp-en** [comment]
Sorry, I totally forgot to close this issue. I don't know when or how this was fixed, but it works fine now.

Also, I did not need to do any tinkering with the Hetzner Firewall. I'm still thinking it was some odd Wine issue.
