### ISSUE TITLE
[Bug]: FiveM

### ISSUE THREAD

**Issue by mrnoahfink** [parkervcp/eggs#2356]
### Panel Version

1.11.3

### Wings Version

1.7.3

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

Installing FiveM fresh and starting server just fine starting.

### Actual Behavior

The server crashed two times with Exit Code 132. 

### Steps To Reproduce

Step 1 Download FiveM egg from this [FiveM egg](https://github.com/parkervcp/eggs/blob/master/game_eggs/gta/fivem/egg-five-m.json )
Step 2 Configure and install like normally you would do. But the FiveM server I try run on is 6550
Step 3 after the installation was done, start the server, but ended up crashing two times. 

### Install logs

https://paste.ec/paste/VVKWzLzg#mRtE5z3Bi3PR32QKPCT0O3FRVzb0TRwuHbSKGTo9Ajt

**Comment by QuintenQVD0** [comment]
You uploaded your own build or have some old db stuff. 

Or this fivem build is again corrupted. First try reinstalling. Else manual set a other build. This is not a issue releated to pterodactyl but to a plugin or a bad build.
