### ISSUE TITLE
[Install Bug]: Sons of The Forest

### ISSUE THREAD

**Issue by walidoow** [parkervcp/eggs#2357]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

sonsoftheforest

### Modified

No, I did not modify the egg

### Expected Behavior

The server is installed using [the egg](https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/sonsoftheforest) without any change in the configuration.
After installation, the server should start without problems.
The server should be available in the server list when launching the game.
The player should be able to join the server and play on it from the server list.

### Actual Behavior

After installation, start the server and it crashes with error even though I have my ports open.

```
        -dedicatedserver.GameMode
        normal
        -dedicatedserver.LogFilesEnabled
        true
        -dedicatedserver.TimestampLogFilenames
        true
Processed options
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshade
rs/fallbacks are suitable)
Releases.Initialize
Releases : 07/21/2023 00:00:00
Version.Initialize
Version : EarlyAccess.36798DS
UnloadTime: 0.417300 ms
Missing GameSettingsManager Instance!
Fps Limiter set to 0
FMOD Setting Voice Count 128
FMOD Setting maxVorbisCodecs 118
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
[FMOD] Error (ERR_INVALID_PARAM): An invalid parameter was passed to this functi
on.
FMOD System output rate: 48000 speaker mode: _5POINT1
Screen.brightness : 1
Screen.cutouts :
Screen.dpi : 96
Screen.height : 544
Screen.orientation : Portrait
Screen.resolutions :
        h:768 w:1024 rate:0
Screen.width : 762
Screen.currentResolution :
        h:768 w:1024 rate:0
Screen.fullScreen : False
Screen.safeArea :
        w:762 h:544 x:0 y:0
Screen.sleepTimeout : -1
Screen.autorotateToPortrait : False
Screen.fullScreenMode : Windowed
Screen.autorotateToLandscapeLeft : False
Screen.autorotateToLandscapeRight : False
Screen.autorotateToPortraitUpsideDown : False
Missing GameSettingsManager Instance!
Fps Limiter set to 30
[Self-Tests] Running self tests...
[Self-Tests] [AppId] App ID is correct.
[Self-Tests] [Settings] Validating game settings file format...
[Self-Tests] [Settings] Game settings file is valid.
[Self-Tests] [Config] Validating server config file and command line arguments..
.
[cfg-dedicatedserver] Field (IpAddress) from (dedicatedserver.cfg) overridden by
 command line arg to value (0.0.0.0)
[cfg-dedicatedserver] Field (GamePort) from (dedicatedserver.cfg) overridden by 
command line arg to value (8766)
[cfg-dedicatedserver] Field (QueryPort) from (dedicatedserver.cfg) overridden by
 command line arg to value (27016)
[cfg-dedicatedserver] Field (BlobSyncPort) from (dedicatedserver.cfg) overridden
 by command line arg to value (9700)
[cfg-dedicatedserver] Field (MaxPlayers) from (dedicatedserver.cfg) overridden b
y command line arg to value (8)
[cfg-dedicatedserver] Field (Password) from (dedicatedserver.cfg) overridden by 
command line arg to value (walidlebg)
[cfg-dedicatedserver] Field (GameMode) from (dedicatedserver.cfg) overridden by 
command line arg to value (normal)
[cfg-dedicatedserver] Field (LogFilesEnabled) from (dedicatedserver.cfg) overrid
den by command line arg to value (true)
[cfg-dedicatedserver] Field (TimestampLogFilenames) from (dedicatedserver.cfg) o
verridden by command line arg to value (true)
Server configuration is valid. More...
{
  "IpAddress": "0.0.0.0",
  "GamePort": 8766,
  "QueryPort": 27016,
  "BlobSyncPort": 9700,
  "ServerName": "Walidoow Binks",
  "MaxPlayers": 8,
  "Password": "walidlebg",
  "LanOnly": false,
  "SaveSlot": 1,
  "SaveMode": "Continue",
  "GameMode": "Normal",
  "SaveInterval": 600,
  "IdleDayCycleSpeed": 0.0,
  "IdleTargetFramerate": 5,
  "ActiveTargetFramerate": 60,
  "LogFilesEnabled": true,
  "TimestampLogFilenames": true,
  "TimestampLogEntries": true,
  "SkipNetworkAccessibilityTest": false,
  "GameSettings": {
    "Gameplay.TreeRegrowth": true,
    "Structure.Damage": true
  },
  "CustomGameModeSettings": {
    "GameSetting.Environment.DayLength": "Default",
    "GameSetting.Environment.PrecipitationFrequency": "Default",
    "GameSetting.Environment.SeasonLength": "Default",
    "GameSetting.Environment.StartingSeason": "Summer",
    "GameSetting.Survival.ColdPenalties": "Off",
    "GameSetting.Survival.ConsumableEffects": "Normal",
    "GameSetting.Survival.PlayerStatsDamage": "Off",
    "GameSetting.Survival.ReducedFoodInContainers": false,
    "GameSetting.Survival.SingleUseContainers": false,
    "GameSetting.Vail.AnimalSpawnRate": "Normal",
    "GameSetting.Vail.EnemyAggression": "Normal",
    "GameSetting.Vail.EnemyArmour": "Normal",
    "GameSetting.Vail.EnemyDamage": "Normal",
    "GameSetting.Vail.EnemyHealth": "Normal",
    "GameSetting.Vail.EnemySpawn": true
  }
}
[Self-Tests] [Config] Dedicated Server configuration file is valid.
[Self-Tests] [Networking] Testing public accessibility...
Setting breakpad minidump AppID = 1326470
src\clientdll\steamengine.cpp (3003) : Assertion Failed: Attempt to call interfa
ce with invalid hSteamUser /+/ 1, appid=1326470, hpipe=131073, inprocess, thread
=912
src\clientdll\steamengine.cpp (3003) : Assertion Failed: Attempt to call interfa
ce with invalid hSteamUser /+/ 1, appid=1326470, hpipe=131073, inprocess, thread
=912
src\common\interfacemap.cpp (890) : Assertion Failed: IPC call to IClientHTTP::R
eleaseHTTPRequest returned failure code 12
src\common\interfacemap.cpp (890) : Assertion Failed: IPC call to IClientHTTP::R
eleaseHTTPRequest returned failure code 12
[Self-Tests] [Networking] Testing server ports against public ip XX.XX.XXX.XX(The ip in X shows my own public IP address)...
[Self-Tests] [Networking] UDP GamePort [8766] is closed. Please fix and restart.
[Self-Tests] [Networking] UDP QueryPort [27016] is closed. Please fix and restar
t.
[Self-Tests] [Networking] UDP BlobSyncPort [9700] is closed. Please fix and rest
art.
[Self-Tests] [Networking] Some ports are closed or already in use and the game s
erver will not be accessible. You may need to setup port forwarding and open the
m in your firewall, or change port numbers if they are used by some other softwa
re. Alternatively, consider using the LanOnly configuration if you didn't intend
 to make your server public. Please fix and restart.
[Self-Tests] Please restart the server.
```

### Steps To Reproduce

Install the server with the egg sonsoftheforest
In the installation process, allocate its default ports 8766, 27016 and 9700
Open the ports 8766, 27016 and 9700 in the router
Start the server
The console should show the error

### Install logs

https://pteropaste.com/ajkj1ojxlt0p

**Comment by gOOvER** [comment]
Not an egg issue.

```
[Self-Tests] [Networking] Testing server ports against public ip XX.XX.XXX.XX(The ip in X shows my own public IP address)...
[Self-Tests] [Networking] UDP GamePort [8766] is closed. Please fix and restart.
[Self-Tests] [Networking] UDP QueryPort [27016] is closed. Please fix and restar
t.
[Self-Tests] [Networking] UDP BlobSyncPort [9700] is closed. Please fix and rest
art.
[Self-Tests] [Networking] Some ports are closed or already in use and the game s
erver will not be accessible. You may need to setup port forwarding and open the
m in your firewall, or change port numbers if they are used by some other softwa
re. Alternatively, consider using the LanOnly configuration if you didn't intend
 to make your server public. Please fix and restart.
[Self-Tests] Please restart the server.
```

**Comment by QuintenQVD0** [comment]
Sons of the forest has a sell check what faild because some ports where not allocated or correctly set or not opened in the firewall.

**Comment by rathmerdominik** [comment]
I have already addressed this bug [here](https://github.com/parkervcp/eggs/pull/2320) 

Nobody really listened to the obvious concerns though
I was able to prove that the server runs when it started and that there is no firewall issue or port forward issue

An Assertion Error is **always** and without any exceptions a program issue.

Because a HTTP Issue can **never** be allowed to create an Assertion Error

The Error also clearly states an interface call with an invalid steam user

It is not an Egg issue though. That much is correct. It is an issue with the steam client api integration in the dedicated server

Sadly all communication regarding this gets blocked off by the one that created the pull request

It is like talking against a brick wall

**Comment by rathmerdominik** [comment]
This is also reproducible under Linux

You can pull the dedicated server and run it with wine

It will be flaky

**Comment by gOOvER** [comment]
so its not an Egg issue. we can Not change things. so better open a Bugreport to SOTF guys

**Comment by gOOvER** [comment]
> This is also reproducible under Linux
> 
> You can pull the dedicated server and run it with wine
> 
> It will be flaky

Ptero only Supports Linux and the Egg runs only in wine ;)

**Comment by walidoow** [comment]
I was able to reproduce this issue on a friend`s machine on a different network. Firewall was not blocking any port and the the ports were open on the network.

After thorough search we finally achieved to run the server by adding one line to the `/home/server/files/serverconfig/dedicatedserver.cfg` file that would skip the Self-Tests check. We added `"SkipNetworkAccessibilityTest": true` to skip the Self-Tests as we knew it was not a network issue.

This is what how our config file ended looking like
```
{
    "ActiveTargetFramerate": 60,
    "BlobSyncPort": 9700,
    "CustomGameModeSettings": {
        "GameSetting.Environment.DayLength": "Default",
        "GameSetting.Environment.PrecipitationFrequency": "Default",
        "GameSetting.Environment.SeasonLength": "Default",
        "GameSetting.Environment.StartingSeason": "Summer",
        "GameSetting.Survival.ColdPenalties": "Off",
        "GameSetting.Survival.ConsumableEffects": "Normal",
        "GameSetting.Survival.PlayerStatsDamage": "Off",
        "GameSetting.Survival.ReducedFoodInContainers": false,
        "GameSetting.Survival.SingleUseContainers": false,
        "GameSetting.Vail.AnimalSpawnRate": "Normal",
        "GameSetting.Vail.EnemyAggression": "Normal",
        "GameSetting.Vail.EnemyArmour": "Normal",
        "GameSetting.Vail.EnemyDamage": "Normal",
        "GameSetting.Vail.EnemyHealth": "Normal",
        "GameSetting.Vail.EnemySpawn": true
    },
    "GameMode": "Normal",
    "GamePort": 8766,
    "GameSettings": {
        "Gameplay.TreeRegrowth": true,
        "Structure.Damage": true
    },
    "IdleDayCycleSpeed": 0,
    "IdleTargetFramerate": 5,
    "IpAddress": "0.0.0.0",
    "LanOnly": false,
    "LogFilesEnabled": true,
    "MaxPlayers": 8,
    "Password": "",
    "QueryPort": 27016,
    "SaveInterval": 600,
    "SaveMode": "Continue",
    "SaveSlot": 1,
    "ServerName": "SotF Server",
    "SkipNetworkAccessibilityTest": true,
    "TimestampLogEntries": true,
    "TimestampLogFilenames": true
}
```

**Comment by gOOvER** [comment]
you can also add this to startup

Walid ***@***.***> schrieb am Mo., 10. Juli 2023, 15:28:

**Comment by gOOvER** [comment]
@walidoow #2362  ;)

**Comment by walidoow** [comment]
> @walidoow #2362 ;)

Great! Thanks for the changes! 😁

**Comment by rathmerdominik** [comment]
> so its not an Egg issue. we can Not change things in steamcmd API. so better open a Bugreport to SOTF guys.
> 
> Where did i Block you?
> 
> What do you think, i should do to fix anything. in the dedicated Server?
> 
> The Egg works without any Problem for ne and a lot of other Users.

I did not mean blocking as in blocking me but blocking off any comments I made about the Server behavior and instead pushing the blame on nonexistent network related issues. 

I also confirmed multiple times that the issue is indeed **not** with your egg, but the Server itself. 

The thing I was questioning the entire time was if we should merge eggs, where there is an obvious issue with the program it tries to use. It feels kind of unprofessional, but I also do not know what the stance of the Maintainers are on quality standards regarding the servers.

I did not mean to come off as offending, but want to give constructive feedback :smile:

**Comment by rathmerdominik** [comment]
> > This is also reproducible under Linux
> > You can pull the dedicated server and run it with wine
> > It will be flaky
> 
> Ptero only Supports Linux and the Egg runs only in wine ;)

That is indeed correct. That is why I said you should reproduce it on Linux with wine :sweat_smile:

**Comment by rathmerdominik** [comment]
> @walidoow #2362 ;)

+1

Great workaround until end night fixes the issue in their server

**Comment by rathmerdominik** [comment]
> I did not mean blocking as in blocking me but blocking off any comments I made about the Server behavior and instead 
> The thing I was questioning the entire time was if we should merge eggs, where there is an obvious issue with the program it tries to use. It feels kind of unprofessional, but I also do not know what the stance of the Maintainers are on quality standards regarding the servers.


Regarding this

Could @parkervcp maybe give a statement himself?

I would like to know in what regards an egg is considered "ready to merge"

Is it already enough if the egg functions as intended? Or does the corresponding server have to fully work as well?

I fully understand if the dogma is "As long as people can have fun with it"

**Comment by parkervcp** [comment]
@rathmerdominik 
My primary concern is that the default configuration is usable without modifications.

This consists of importing the egg, adding the default port allocations, running an install, starting the server, finally being able to connect to it.

As for the network errors supplied. They are weird because they are looking for open ports on UDP which doesn't respond with an open status. Unless they are attempting connections. This could be a NAT issue or a port forwarding issue or any number of other network issues. Without a better understanding of the configuration of the network it's quite hard to diagnose, especially when it's working for so many other people.
