### ISSUE TITLE
[Egg Request]: Memcached

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2363]
### Does this expand an already existing service

No

### Link to a game or software

https://memcached.org/

### Links for the download

https://memcached.org/downloads

### Links for the install docs

https://github.com/memcached/memcached/wiki/Install

**Comment by diedyesterdaywashere** [comment]
![image](https://github.com/parkervcp/eggs/assets/81169193/03d83890-9e61-48e5-a280-3047fab6434e)
🤨

**Comment by QuintenQVD0** [comment]
They don't have precompiled binary's and we like to avoid building software in the install container

**Comment by gOOvER** [comment]
they have:

https://packages.debian.org/search?keywords=memcached

**Comment by gOOvER** [comment]
Time to update to Debian 12. No reason for staying with oldstable :D

**Comment by QuintenQVD0** [comment]
> Time to update to Debian 12. No reason for staying with oldstable :D

a lot of things still depend on it. An extra OS image something like `ghcr.io/parkervcp/yolks:debian_12` that is fine as libssl1.1 is removed

**Comment by gOOvER** [comment]
libssl 1.1 is eol :D 

https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/

11.09.2023 it should not be longer used

**Comment by gOOvER** [comment]
i will create an Debian 12 image

**Comment by QuintenQVD0** [comment]
> libssl 1.1 is eol :D
> 
> https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
> 
> 11.09.2023 it should not be longer used from that date

still a lot of things needed so we like to keep it for now.

**Comment by gOOvER** [comment]
> > libssl 1.1 is eol :D
> > https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
> > 11.09.2023 it should not be longer used from that date
> 
> still a lot of things needed so we like to keep it for now.

I can't think of any reason why Steamcmd wouldn't run on Debian 12, as well as the installer image and the Wine images. 

I find it somehow irresponsible to provide images that pose a security risk.

What does libssl 1.1 need?

**Comment by QuintenQVD0** [comment]
> > > libssl 1.1 is eol :D
> > > https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
> > > 11.09.2023 it should not be longer used from that date
> > 
> > 
> > still a lot of things needed so we like to keep it for now.
> 
> I can't think of any reason why Steamcmd wouldn't run on Debian 12, as well as the installer image and the Wine images.
> 
> I find it somehow irresponsible to provide images that pose a security risk.
> 
> What does libssl 1.1 need?

some fivem modules and some other things like ragemp

**Comment by QuintenQVD0** [comment]
@diedyesterdaywashere 

Please try 

```json
{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v2",
        "update_url": null
    },
    "exported_at": "2023-08-14T17:04:47+02:00",
    "name": "Memcached",
    "author": "josdekurk@gmail.com",
    "description": "Free & open source, high-performance, distributed memory object caching system",
    "features": null,
    "docker_images": {
        "Alpine": "ghcr.io\/parkervcp\/yolks:alpine"
    },
    "file_denylist": [
        "\/home\/container\/memcached",
        "memcached"
    ],
    "startup": ".\/memcached  --listen=0.0.0.0 --port={{SERVER_PORT}} --memory-limit={{ITEM_LIMIT}} --conn-limit={{MAX_CON}} --threads={{THREADS}} -vv",
    "config": {
        "files": "{}",
        "startup": "{\r\n    \"done\": \"server listening\"\r\n}",
        "logs": "{}",
        "stop": "^C"
    },
    "scripts": {
        "installation": {
            "script": "#!\/bin\/ash\r\n\r\napk update\r\napk add curl memcached\r\n\r\nmkdir -p \/mnt\/server\r\ncd \/mnt\/server\r\n\r\nmv \/usr\/bin\/memcached \/mnt\/server\r\n\r\necho \"done\"",
            "container": "alpine:latest",
            "entrypoint": "ash"
        }
    },
    "variables": [
        {
            "name": "Threads",
            "description": "The number of threads to use",
            "env_variable": "THREADS",
            "default_value": "4",
            "user_viewable": true,
            "user_editable": false,
            "rules": "required|numeric",
            "field_type": "text"
        },
        {
            "name": "Item memory limit",
            "description": "The item memory in megabytes",
            "env_variable": "ITEM_LIMIT",
            "default_value": "64",
            "user_viewable": true,
            "user_editable": false,
            "rules": "required|numeric",
            "field_type": "text"
        },
        {
            "name": "Max connections",
            "description": "The max simultaneous connections",
            "env_variable": "MAX_CON",
            "default_value": "1024",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|numeric|between:100,2000",
            "field_type": "text"
        }
    ]
}
```

you will need to use my test image `quintenqvd/pterodactyl_images:temp_memcached` as it needs changes to the regular image

**Comment by QuintenQVD0** [comment]
@diedyesterdaywashere You have tested this, or you don't need this egg any more (if so, please close this)
