### ISSUE TITLE
[Install Bug]: <Egg SAMP>

### ISSUE THREAD

**Issue by MaskioSss** [parkervcp/eggs#2368]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

SAMP

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

IT DOESN'T WORK IT KEEP INSTALLING INFINITELY YOU RUINED PARKERSV'S EGG

### Actual Behavior

IT DOESN'T WORK IT KEEP INSTALLING INFINITELY YOU RUINED PARKERSV'S EGG

### Steps To Reproduce

IT DOESN'T WORK IT KEEP INSTALLING INFINITELY YOU RUINED PARKERSV'S EGG

### Install logs

 IT DOESN'T WORK IT KEEP INSTALLING INFINITELY YOU RUINED PARKERSV'S EGG

**Comment by parkervcp** [comment]
We need more than "it doesn't work"

**Comment by gOOvER** [comment]
i love vacations :/ 

parker i would close thias, as long he is not able to create a understandble bugreport

**Comment by gOOvER** [comment]
@MaskioSss 

Problem on your site: Work as exspected:
https://haste.goover.de/zulexenini.coffeescript

**Comment by QuintenQVD0** [comment]
I can confirm it is working. Before I left on vacation. 1nd notthing changed. Ans you wont provide the logs and all those caps is not needed.
