### ISSUE TITLE
[Bug]: Conan Exiles

### ISSUE THREAD

**Issue by HerrSammyDE** [parkervcp/eggs#2369]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Conan Exiles

### Modified

No, I did not modify the egg

### Expected Behavior

Server starts, but does not start properly due to the error

### Actual Behavior

Server does not crash

### Steps To Reproduce

Install and start server

### Install logs

https://ptero.co/egimyjuvek.pl

**Comment by QuintenQVD0** [comment]
Latest is not a version we would like a number.

**Comment by QuintenQVD0** [comment]
It can take a lot of time as wine is creating and getting its file system ready. If it takes longer then 10 minutes kill it. Removed all files and reinstall.

**Comment by HerrSammyDE** [comment]
> It can take a lot of time as wine is creating and getting its file system ready. If it takes longer then 10 minutes kill it. Removed all files and reinstall.

The server has been running like this for 47 minutes without doing anything. There is no error, there is no new message, nothing.

**Comment by thierrybla** [comment]
I also experience this.

**Comment by gOOvER** [comment]
They changed somethings: Server starts fine, but have no longer consoleoutput. You can check this in the logfiles:

https://haste.goover.de/vexipahuxo.md

**Comment by HerrSammyDE** [comment]
I downloaded the normal Egg from Github and tested it, it doesn't work for me.

**Comment by Volyz** [comment]
Having the same problem as the OP.

Updated my image the day before and since then it doesn't work anymore

```
container@pterodactyl~ Server marked as starting...
Running on Debian 11.7
Current timezone: Etc/UTC
wine-8.12 (Staging)
steam user is not set.

Using anonymous user.

WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1689034828
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '443030' already up to date.
First launch will throw some errors. Ignore them
:/home/container$ export WINEDEBUG=-all; xvfb-run --auto-servernum wine /home/container/ConanSandboxServer.exe ConanSandbox?listen?PVPEnabled=${PVP}?Port=${SERVER_PORT}?QueryPort=${QUERY_PORT} -ServerName="${SRV_NAME}" -ServerPassword=${SRV_PW} -console -log
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
```

Waited more than 24 hours and restarted the server => same output.

**Comment by gOOvER** [comment]
> Having the same problem as the OP.
> 
> Updated my image the day before and since then it doesn't work anymore
> 
> ```
> container@pterodactyl~ Server marked as starting...
> Running on Debian 11.7
> Current timezone: Etc/UTC
> wine-8.12 (Staging)
> steam user is not set.
> 
> Using anonymous user.
> 
> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
> [  0%] Checking for available updates...
> [----] Verifying installation...
> Steam Console Client (c) Valve Corporation - version 1689034828
> -- type 'quit' to exit --
> Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> OK
> 
> Connecting anonymously to Steam Public...OK
> Waiting for client config...OK
> Waiting for user info...OK
> "@sSteamCmdForcePlatformType" = "windows"
> Success! App '443030' already up to date.
> First launch will throw some errors. Ignore them
> :/home/container$ export WINEDEBUG=-all; xvfb-run --auto-servernum wine /home/container/ConanSandboxServer.exe ConanSandbox?listen?PVPEnabled=${PVP}?Port=${SERVER_PORT}?QueryPort=${QUERY_PORT} -ServerName="${SRV_NAME}" -ServerPassword=${SRV_PW} -console -log
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> ```
> 
> Waited more than 24 hours and restarted the server => same output.

have nothing to do with the image

**Comment by tola1990** [comment]
I've added Wine_latest|ghcr.io/parkervcp/yolks:wine_latest to to egg docker images, started if with it, and i have logs now and panel shows server as running, but haven't tested it within game for stability

**Comment by gOOvER** [comment]
> I've added Wine_latest|ghcr.io/parkervcp/yolks:wine_latest to to egg docker images, started if with it, and i have logs now and panel shows server as running, but haven't tested it within game for stability

ty for the Info. i will do some tests

**Comment by gOOvER** [comment]
i can confirm, that staging have a bug and dont show console;

@QuintenQVD0; we should use stable atm, because staging have a bug, which stops a server to show console

**Comment by QuintenQVD0** [comment]
> i can confirm, that staging have a bug and dont show console;
> 
> @QuintenQVD0; we should use stable atm, because staging have a bug, which stops a server to show console


That is fije for me.

**Comment by SamuelBrownSE** [comment]
Im still having this same issue? any update on this?

**Comment by SamuelBrownSE** [comment]
Got the server showing logs with Wine_latest|ghcr.io/parkervcp/yolks:wine_latest but still can't connect in game.

**Comment by tola1990** [comment]
@SamuelBrownSE i'll installed game and tested with my instance of server, i got connection. are you sure you have setup everything wright ?

**Comment by QuintenQVD0** [comment]
This is some configuration issue you have as if you change to the wine latest image. You can you. Please check your port and network. Else come to the discord.
