### ISSUE TITLE
[Bug]: <barotrauma>

### ISSUE THREAD

**Issue by tola1990** [parkervcp/eggs#2372]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

barotrauma

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play

### Actual Behavior

Server starts, but performance is abysmal, constant rubberbanding.
Server and client both same local network, sometimes you can see "server running slowly" messages on client console(F3)

### Steps To Reproduce

Step 1 Install and start server
Step 2 Connect to it 
Step 3 Start a game session 

### Install logs

https://pteropaste.com/7svse8clsx3g/

**Comment by gOOvER** [comment]
Sounds Like, its Not really an Egg issue

**Comment by tola1990** [comment]
Any other Egg's that running on my machine don't have any performance issues, for testing purpose i spun up barotrauma container in docker and there was no rubberbanding

**Comment by QuintenQVD0** [comment]
@tola1990 what specs did you allocated?

**Comment by tola1990** [comment]
> @tola1990 what specs did you allocated?

I didn't limit it at all, here what i have in about section
CPU Limit | Unlimited
CPU Pinning | Not Set
Memory | Unlimited / Not Set
Disk Space | Unlimited
Block IO Weight | 500

**Comment by QuintenQVD0** [comment]
> > @tola1990 what specs did you allocated?
> 
> I didn't limit it at all, here what i have in about section CPU Limit | Unlimited CPU Pinning | Not Set Memory | Unlimited / Not Set Disk Space | Unlimited Block IO Weight | 500

do not give it unlimeted give it a real number some games can not handle unlimited

**Comment by tola1990** [comment]
> > > @tola1990 what specs did you allocated?
> > 
> > 
> > I didn't limit it at all, here what i have in about section CPU Limit | Unlimited CPU Pinning | Not Set Memory | Unlimited / Not Set Disk Space | Unlimited Block IO Weight | 500
> 
> do not give it unlimeted give it a real number some games can not handle unlimited

tested it with 
CPU Limit | 200%
CPU Pinning | Not Set
Memory | 6000MiB/ Not Set
Disk Space | 6000MiB
it didn't help
by my observation of  logs it takes about 1 second for entity to load, so if i sit there for ~10minutes it will load, in comparison with ich777/steamcmd:barotrauma it dosn't take a 5 second to fully load. so i wracking my brain trying to understand why is so slow

**Comment by QuintenQVD0** [comment]
Show me the full page please with the memory and cpu you set as it is working fine for me @tola1990

**Comment by tola1990** [comment]
![image](https://github.com/parkervcp/eggs/assets/18589608/fee3aeff-6958-4d79-9c5f-88dca0a8d3b9)
this is my last settings, as from last testing i installed server performance fix mod, now i need to wait for about 30 - 60 second, as i change location/station, and game becomes playable

**Comment by QuintenQVD0** [comment]
> ![image](https://user-images.githubusercontent.com/18589608/258656348-fee3aeff-6958-4d79-9c5f-88dca0a8d3b9.png) this is my last settings, as from last testing i installed server performance fix mod, now i need to wait for about 30 - 60 second, as i change location/station, and game becomes playable

Is 2 threads not a bit to litte for this game?  Please try with 350 cpu and no thread pinning. As there server is not very optimized.

**Comment by QuintenQVD0** [comment]
This is not pterodactyl related but just bad game optimalisation
see(https://www.reddit.com/r/Barotrauma/comments/138zho4/linux_dedicated_server_performance_issuesrubber/?rdt=64438)
