### ISSUE TITLE
[Egg Request]: restreamer

### ISSUE THREAD

**Issue by alincupunct** [parkervcp/eggs#2373]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/datarhei/restreamer

### Links for the download

https://github.com/datarhei/restreamer/releases

### Links for the install docs

https://docs.datarhei.com/restreamer

**Comment by gOOvER** [comment]
ptero ist the wrong solution for this

**Comment by QuintenQVD0** [comment]
Pterodactyl is indeed the wrong solution for this, and you are required to build it from source, and we like to avoid that and no we can not use their docker image as no files can be in the docker container
