### ISSUE TITLE
[Egg Request]: QuiltMC (Should be similar to FabricMC)

### ISSUE THREAD

**Issue by HughSparks** [parkervcp/eggs#2374]
### Does this expand an already existing service

Yes

### Link to a game or software

https://quiltmc.org/en/

### Links for the download

https://github.com/QuiltMC/quilt-installer

### Links for the install docs

https://github.com/QuiltMC/quilt-loader/wiki

**Comment by yesBad** [comment]
Already has been requested and a working egg is available in pr's.

**Comment by parkervcp** [comment]
duplicate of #2348
