### ISSUE TITLE
[Install Bug]: Arma Reforger

### ISSUE THREAD

**Issue by HerrSammyDE** [parkervcp/eggs#2377]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Arma Reforger

### Modified

No, I did not modify the egg

### Expected Behavior

Server starts, but does not start properly due to the error

### Actual Behavior

The server crashes after installation

### Steps To Reproduce

Install and launch standard egg

### Install logs

https://ptero.co/ucipaxuriq.apache

**Comment by QuintenQVD0** [comment]
BACKEND   (E): Param "#/gameHostBindAddress" is not allowed and must be removed.
   
   prity clear that this must be removed out of the config or you have wrong set ut

**Comment by QuintenQVD0** [comment]
but how is this egg even working as steamdb only tells you that there is a windows version

**Comment by HerrSammyDE** [comment]
I have also already updated the parser in my Test Egg, however it doesn't do me any good because there are errors like "`BACKEND   (E): Param "#/game/gameProperties/battlEye" has an incorrect type. Expected "boolean", but the value is "string"`
" coming and this hasn't been fixed in the panel until now
(https://github.com/pterodactyl/panel/issues/4087)

```
{
    "config.json": {
        "parser": "json",
        "find": {
            "region": "{{server.build.env.REGION}}",
            "gameHostBindAddress": "0.0.0.0",
            "gameHostBindPort": "{{server.build.default.port}}",
            "gameHostRegisterBindAddress": "{{server.build.default.ip}}",
            "gameHostRegisterPort": "{{server.build.default.port}}",
            "game.name": "{{server.build.env.SERVER_NAME}}",
            "game.password": "{{server.build.env.SERVER_PASS}}",
            "adminPassword": "{{server.build.env.ADMIN_PASS}}",
            "game.scenarioId": "{{server.build.env.SCENARIO_ID}}",
            "game.playerCountLimit": "{{server.build.env.PLAYERS}}",
            "game.autoJoinable": "{{server.build.env.AUTO_JOINABLE}}",
            "game.visible": "{{server.build.env.VISIBLE}}",
            "game.gameProperties.disableThirdPerson": "{{server.build.env.DISABLE_THIRD}}",
            "game.gameProperties.battlEye": "{{server.build.env.BATTLEYE}}",
            "game.crossPlatform": true
        }
    }
}
```

**Comment by QuintenQVD0** [comment]
> BATTLEYE

what are the rules of the BATTLEYE variable?

**Comment by HerrSammyDE** [comment]
> > BATTLEYE
> 
> what are the rules of the BATTLEYE variable?

`required|string|in:true,false`

**Comment by QuintenQVD0** [comment]
> > > BATTLEYE
> > 
> > 
> > what are the rules of the BATTLEYE variable?
> 
> `required|string|in:true,false`

should be fine you can try removing the string

**Comment by HerrSammyDE** [comment]
i have now created a completely new server again and now this error comes up (info: i used it with my parser which is suitable for json):
```
INIT         : Creating game instance(ArmaReforgerScripted), version 0.9.9.47 built 2023-07-18 1:38:18 UTC.
Loading dedicated server config.
 BACKEND      : Server config loaded.
 BACKEND      : JSON Schema Validation:
  BACKEND      : additionalProperties error:
   BACKEND   (E): Param "#/adminPassword" is not allowed and must be removed.
  BACKEND   (E): JSON is invalid!
 BACKEND   (E): There are errors in server config!
BACKEND   (E): Unable to continue with a broken DS config! Shutdown!
ENGINE    (E): Error while initializing game.
ENGINE    (E): Unable to initialize the game
ENGINE       : Game destroyed.
RESOURCES (E): ==== Resource leaks ====
```

this is my config
```
{
    "adminPassword": "",
    "dedicatedServerId": "",
    "game": {
        "autoJoinable": "true",
        "crossPlatform": true,
        "gameProperties": {
            "battlEye": "true",
            "disableThirdPerson": "false",
            "fastValidation": true,
            "missionHeader": {},
            "networkViewDistance": 1000,
            "serverMaxViewDistance": 2500,
            "serverMinGrassDistance": 50
        },
        "mods": [],
        "name": "Arma Reforger Server",
        "password": "",
        "playerCountLimit": 40,
        "scenarioId": "{ECC61978EDCC2B5A}Missions/23_Campaign.conf",
        "visible": "true"
    },
    "gameHostBindAddress": "0.0.0.0",
    "gameHostBindPort": XXXXXX,
    "gameHostRegisterBindAddress": "XXXXXXXX",
    "gameHostRegisterPort": XXXXXX,
    "region": "DE"
}
```

**Comment by HerrSammyDE** [comment]
> > > > BATTLEYE
> > > 
> > > 
> > > what are the rules of the BATTLEYE variable?
> > 
> > 
> > `required|string|in:true,false`
> 
> should be fine you can try removing the string

As soon as I remove the string here (  "game.gameProperties.battlEye": `"`{{server.build.env.BATTLEYE}}`"`,  ), the panel says no.

**Comment by lilkingjr1** [comment]
> but how is this egg even working as steamdb only tells you that there is a windows version

There's a Linux binary: https://steamdb.info/app/1874900/depots/

**Comment by lilkingjr1** [comment]
I'll try to replicate the issue when I have some free time. Seems like BI may have updated their `config.json` and the Egg's Configuration Files parser may need adjusting, but I'm not sure until I test.

@HerrSammyDE You read [this part](https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/arma/arma_reforger#define-host-registered-bind-address) of the Egg's README, right?

**Comment by HerrSammyDE** [comment]
> I'll try to replicate the issue when I have some free time. Seems like BI may have updated their `config.json` and the Egg's Configuration Files parser may need adjusting, but I'm not sure until I test.
> 
> @HerrSammyDE You read [this part](https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/arma/arma_reforger#define-host-registered-bind-address) of the Egg's README, right?

Yes I have! I got this error (gameHostBindAddress) with the default Egg. With my Egg, where I use only my parser, the error did not come, but only the others, which I have already communicated above. I'll send you my Egg export on Discord, so you can have a look at it and maybe take my parser into the standard Egg.

**Comment by Boy132** [comment]
> I have also already updated the parser in my Test Egg, however it doesn't do me any good because there are errors like "`BACKEND (E): Param "#/game/gameProperties/battlEye" has an incorrect type. Expected "boolean", but the value is "string"` " coming and this hasn't been fixed in the panel until now ([pterodactyl/panel#4087](https://github.com/pterodactyl/panel/issues/4087))
> 
> ```
> {
>     "config.json": {
>         "parser": "json",
>         "find": {
>             "region": "{{server.build.env.REGION}}",
>             "gameHostBindAddress": "0.0.0.0",
>             "gameHostBindPort": "{{server.build.default.port}}",
>             "gameHostRegisterBindAddress": "{{server.build.default.ip}}",
>             "gameHostRegisterPort": "{{server.build.default.port}}",
>             "game.name": "{{server.build.env.SERVER_NAME}}",
>             "game.password": "{{server.build.env.SERVER_PASS}}",
>             "adminPassword": "{{server.build.env.ADMIN_PASS}}",
>             "game.scenarioId": "{{server.build.env.SCENARIO_ID}}",
>             "game.playerCountLimit": "{{server.build.env.PLAYERS}}",
>             "game.autoJoinable": "{{server.build.env.AUTO_JOINABLE}}",
>             "game.visible": "{{server.build.env.VISIBLE}}",
>             "game.gameProperties.disableThirdPerson": "{{server.build.env.DISABLE_THIRD}}",
>             "game.gameProperties.battlEye": "{{server.build.env.BATTLEYE}}",
>             "game.crossPlatform": true
>         }
>     }
> }
> ```

https://github.com/pterodactyl/panel/issues/4087 is not related to your problem, 4087 is about not accepting `true`/ `false` but only `1`/ `0` in the _admin area_.

**Comment by HerrSammyDE** [comment]
> > I have also already updated the parser in my Test Egg, however it doesn't do me any good because there are errors like "`BACKEND (E): Param "#/game/gameProperties/battlEye" has an incorrect type. Expected "boolean", but the value is "string"` " coming and this hasn't been fixed in the panel until now ([pterodactyl/panel#4087](https://github.com/pterodactyl/panel/issues/4087))
> > ```
> > {
> >     "config.json": {
> >         "parser": "json",
> >         "find": {
> >             "region": "{{server.build.env.REGION}}",
> >             "gameHostBindAddress": "0.0.0.0",
> >             "gameHostBindPort": "{{server.build.default.port}}",
> >             "gameHostRegisterBindAddress": "{{server.build.default.ip}}",
> >             "gameHostRegisterPort": "{{server.build.default.port}}",
> >             "game.name": "{{server.build.env.SERVER_NAME}}",
> >             "game.password": "{{server.build.env.SERVER_PASS}}",
> >             "adminPassword": "{{server.build.env.ADMIN_PASS}}",
> >             "game.scenarioId": "{{server.build.env.SCENARIO_ID}}",
> >             "game.playerCountLimit": "{{server.build.env.PLAYERS}}",
> >             "game.autoJoinable": "{{server.build.env.AUTO_JOINABLE}}",
> >             "game.visible": "{{server.build.env.VISIBLE}}",
> >             "game.gameProperties.disableThirdPerson": "{{server.build.env.DISABLE_THIRD}}",
> >             "game.gameProperties.battlEye": "{{server.build.env.BATTLEYE}}",
> >             "game.crossPlatform": true
> >         }
> >     }
> > }
> > ```
> 
> [pterodactyl/panel#4087](https://github.com/pterodactyl/panel/issues/4087) is btw not related to your problem, 4087 is about not accepting `"true"`/ `"false"` but only `1`/ `0` in the _admin area_.

But you can not remove the quotation marks
"game.gameProperties.battlEye": `"`{{server.build.env.BATTLEYE}}`"`,

**Comment by Arcanum417** [comment]
About to barge in here after creating a duplicate. BIS changed the config variables and broke compatibility in the latest patch.
https://community.bistudio.com/wiki/Arma_Reforger:Server_Config

**Comment by QuintenQVD0** [comment]
I will have a look tomorrow on fixing this

**Comment by lilkingjr1** [comment]
@QuintenQVD0 Thanks. I don't have much free time at the moment. If it's just a simple config parsing issue, it should be easy to fix.

**Comment by HerrSammyDE** [comment]
> I will have a look tomorrow on fixing this

I have fixed the Egg for me. But I removed the true/false variables, because otherwise you get "`BACKEND   (E): Param "#/game/gameProperties/battlEye" has an incorrect type. Expected "boolean", but the value is "string"`" as an error in the console.
https://github.com/HerrSammyDE/eggs/blob/master/game_eggs/steamcmd_servers/arma/arma_reforger/egg-arma-reforger.json

**Comment by Arcanum417** [comment]
Would be cool to get publicIP as a startup parameter not a necessary egg modification too.
