### ISSUE TITLE
[Install Bug]: Waterfall

### ISSUE THREAD

**Issue by DRNGx** [parkervcp/eggs#2384]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Minecraft/proxy/waterfall

### Modified

No, I did not modify the egg

### Expected Behavior

installing waterfall 1.16 with provided link

### Actual Behavior

I tried to install the proxy waterfall, but when I provide the DL:
https://api.papermc.io/v2/projects/waterfall/versions/1.16/builds/431/downloads/waterfall-1.16-431.jar

it ignores the Link and keeps installing waterfall version 1.20

if i try to give him a mc version it gives me an error that "The Minecraft Version variable may only contain letters and numbers." because i try to give him 1.16

### Steps To Reproduce

step 1 fill in all details
step 2 leaves everything to latest
step 3 providing the link
step 4 installs wrong version

### Install logs

https://pteropaste.com/9h2zxm7wnrri

**Comment by diedyesterdaywashere** [comment]
i think you need to just give it a version number, not a link?

**Comment by diedyesterdaywashere** [comment]
hold on i'll try it

**Comment by diedyesterdaywashere** [comment]
yeah i think the egg is broken?

**Comment by DRNGx** [comment]
`unning hooks in /etc/ca-certificates/update.d...
done.
Using supplied download url: 
Running curl -o waterfall.jar 
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Downloading waterfall config.yml`

it somehow ignores the link and tries to curl "waterfall.jar"

**Comment by DRNGx** [comment]
I think I fixed it with:
`if [ -n "${DL_LINK}" ]; then
	echo -e "Using supplied download url: ${DL_LINK}"
	DOWNLOAD_URL=`eval echo $(echo ${DL_LINK} | sed -e 's/{{/${/g' -e 's/}}/}/g')``
