### ISSUE TITLE
[Install Bug]: <7days to die> Undead Legacy impossible to connect to the server

### ISSUE THREAD

**Issue by InteralexDev** [parkervcp/eggs#2387]
### Panel Version

1.11.3

### Wings Version

v1.11.7

### Service

game_eggs/steamcmd_servers /7_days_to_die

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Hello everybody,

I used a modified egg (this one : [egg-7dtd-undead-legacy.json.txt](https://github.com/parkervcp/eggs/files/12184746/egg-7dtd-undead-legacy.json.txt))

I installed it on my server, and after some discussion on this thread : https://github.com/parkervcp/eggs/issues/1804 i also added older version for some mods from this archive : (direct link here: https://illy.bz/fi/7dtd/server_fixes_v22_24_39.tar.gz) to avoid problems with these mods.

The installation went well and the start of the server works

### Actual Behavior

But when i'm connecting to the server i got these error messages : 
![image](https://github.com/parkervcp/eggs/assets/87869970/ddc5544b-5f79-4724-895f-5a548443b752)

Here are the logs from server console after running : 

> [Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/games 
Status: Image is up to date for ghcr.io/parkervcp/games:source 
Digest: sha256:7641a3334db392e6eab7afb751efd0e7a7f90da6fd27841698f8b96d1ee298ff 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
Not updating game server as auto update was set to 0. Starting Server
:/home/container$ ./startserver.sh -configfile=serverconfig.xml -ServerPort=${SERVER_PORT} -ServerMaxPlayerCount=${MAX_PLAYERS} -GameDifficulty=${GAME_DIFFICULTY} -ControlPanelEnabled=true -ControlPanelPort=${CONTROL_PORT} -ControlPanelPassword=${CONTROL_PASSWORD} -TelnetEnabled=true -TelnetPort=${TELNET_PORT} -TelnetPassword=${PASSWORD} & echo -e "Checking on telnet connection" && until nc -z 127.0.0.1 ${TELNET_PORT}; do echo -e "Waiting on telnet connection..."; sleep 5; done && $( [[ -z ${PASSWORD} ]] && printf %s "telnet -E 127.0.0.1 ${TELNET_PORT}" || printf %s "rcon -t telnet -a 127.0.0.1:${TELNET_PORT} -p ${PASSWORD}" )
Checking on telnet connection
Waiting on telnet connection...
Using config file: serverconfig.xml
Found UnityPlayer, hooking into it instead
Set current directory to /home/container
Found path: /home/container/7DaysToDieServer.x86_64
Waiting on telnet connection...
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is 'off'.
*** Connected with 7DTD server.
*** Server version: Alpha 20.7 (b1) Compatibility Version: Alpha 20.7
container@pterodactyl~ Server marked as running...
*** Dedicated server only build
Server IP:   Any
Server port: 26900
Max players: 10
Game mode:   GameModeSurvival
World:       Navezgane
Game name:   My Game
Difficulty:  2
Press 'help' to get a list of all commands. Press 'exit' to end session.
2023-07-27T14:55:40 4.750 INF Started thread TelnetClient_127.0.0.1:44918
2023-07-27T14:55:40 4.751 ERR IOException in ReadLine for TelnetClient_127.0.0.1:44904: Unable to write data to the transport connection: The socket has been shut down.
2023-07-27T14:55:40 4.753 EXC Unable to write data to the transport connection: The socket has been shut down.
2023-07-27T14:55:40 4.758 INF StartAsServer
2023-07-27T14:55:40 4.778 ERR Exception in thread TelnetClient_127.0.0.1:44904:
2023-07-27T14:55:40 4.779 EXC The operation is not allowed on non-connected sockets.
2023-07-27T14:55:40 4.780 INF Exited thread TelnetClient_127.0.0.1:44904
2023-07-27T14:55:41 5.807 INF Loaded (local): materials
2023-07-27T14:55:41 6.317 INF Loaded (local): physicsbodies
2023-07-27T14:55:42 6.806 INF Loaded (local): painting
2023-07-27T14:55:42 7.406 INF Loaded (local): shapes

### Steps To Reproduce

Step 1 : install the server
Step 2 : run it
Step 3 : connect to the server

### Install logs

https://pteropaste.com/exampleLogs

**Comment by QuintenQVD0** [comment]
No install logs, mods are not offical supported and does the non edited egg work? And please use a paste link for the logd ok the screen and the startup you posted here.
