### ISSUE TITLE
[Bug]: JMusicBot

### ISSUE THREAD

**Issue by jAvEE-fr** [parkervcp/eggs#2390]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

JMusicBot

### Modified

No, I did not modify the egg

### Expected Behavior

create server
install
listen!

### Actual Behavior

install stop here:

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Updating certificates in /etc/ssl/certs...
137 added, 0 removed; done.
Setting up libgssapi-krb5-2:amd64 (1.17-3+deb10u5) ...
Setting up jq (1.5+dfsg-2+b1) ...
Setting up libcurl4:amd64 (7.64.0-4+deb10u6) ...
Setting up curl (7.64.0-4+deb10u6) ...
Processing triggers for libc-bin (2.28-10+deb10u2) ...
Processing triggers for ca-certificates (20200601~deb10u2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
using anon api call
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
config found
Job's Done

Apparently script dont dl jmusicbot.jar neither config.txt soooo... there is nothing in Files except an emply config.txt

minor bug also: new bot system have tokens longer than 64 characters!

### Steps To Reproduce

latest egg-jmusicbot.json
in Eggs of my panel
create server
install it -> fail (follow it in Console at first launch)

### Install logs

https://pteropaste.com/3kuonz3ltsu2

**Comment by jAvEE-fr** [comment]
Hello, the jmusicbot still cut Token

**Comment by QuintenQVD0** [comment]
> Hello, the jmusicbot still cut Token

No idea. It worked fine for me. And we do not limit the token variable length
