### ISSUE TITLE
[Bug]: Project Zomboid

### ISSUE THREAD

**Issue by SamuelBrownSE** [parkervcp/eggs#2398]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

Project-Zomboid

### Modified

No, I did not modify the egg

### Expected Behavior

When I install the server its been fine in the past, but recently for some other reason, the server is now giving me this error (this is a  fresh install btw) 

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/games 
Status: Image is up to date for ghcr.io/parkervcp/games:source 
Digest: sha256:7641a3334db392e6eab7afb751efd0e7a7f90da6fd27841698f8b96d1ee298ff 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
Not updating game server as auto update was set to 0. Starting Server
:/home/container$ /home/container/start-server.sh -port ${SERVER_PORT} -steamport1 ${STEAM_PORT} -cachedir=/home/container/.cache -servername "${SERVER_NAME}" -adminusername ${ADMIN_USER} -adminpassword "${ADMIN_PASSWORD}"
/entrypoint.sh: line 73: /home/container/start-server.sh: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/games 
Status: Image is up to date for ghcr.io/parkervcp/games:source 
Digest: sha256:7641a3334db392e6eab7afb751efd0e7a7f90da6fd27841698f8b96d1ee298ff 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
Not updating game server as auto update was set to 0. Starting Server
:/home/container$ /home/container/start-server.sh -port ${SERVER_PORT} -steamport1 ${STEAM_PORT} -cachedir=/home/container/.cache -servername "${SERVER_NAME}" -adminusername ${ADMIN_USER} -adminpassword "${ADMIN_PASSWORD}"
/entrypoint.sh: line 73: /home/container/start-server.sh: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

Can anyone help? 

### Actual Behavior

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

Ive tried setting the update to 1 but makes no difference, all ive done was try to test to see if the egg was working. this was working literally a week ago.

### Install logs

https://pteropaste.com/erfxrmb50dn0/

**Comment by HoleInTheSeat** [comment]
> /home/container/start-server.sh: No such file or directory

Does the file `start-server.sh` exist?

**Comment by QuintenQVD0** [comment]
That is definitly not the offical startup as we do not allow a script as startup. So my guess is that you are not using an offical egg.

**Comment by HoleInTheSeat** [comment]
> That is definitly not the offical startup as we do not allow a script as startup. So my guess is that you are not using an offical egg.

it seems it does use a script. Is it part of the yolk?

**Comment by QuintenQVD0** [comment]
It seems indeed the script is used what is not allowed. I have a look.

**Comment by QuintenQVD0** [comment]
> > That is definitly not the offical startup as we do not allow a script as startup. So my guess is that you are not using an offical egg.
> 
> it seems it does use a script. Is it part of the yolk?

No it is not

**Comment by QuintenQVD0** [comment]
It looks like you have dns issues.

**Comment by QuintenQVD0** [comment]
It works fine for me, It looks to me like you have a dns issue.
You can try reinstalling this server if it does not work then please come to the discord as the egg itself works fine.
