### ISSUE TITLE
[Bug]: <egg-node-js-generic.json>

### ISSUE THREAD

**Issue by NickolayG** [parkervcp/eggs#2400]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

NodeJS

### Modified

No, I did not modify the egg

### Expected Behavior

I expected the egg to automatically fetch the github repo on startup.
Also expected to fetch any changes on startup.

### Actual Behavior

Nothing at all, no console logging of any Github related actions.

### Steps To Reproduce

1. Uploaded the egg (https://github.com/parkervcp/eggs/blob/master/generic/nodejs/egg-node-js-generic.json).
2. Installed a server with the egg.
3. Filled in github related fields on startup.
4. Reinstalled server (also tried not doing it). - Was required to do this step on a shared-hosting server to make it work.

Used identical credentials I used on a different pterodactyl host, with a similar egg, and it worked without issues.

### Install logs

https://pteropaste.com/g48trv3q27dl/

**Comment by QuintenQVD0** [comment]
/mnt/server directory is not empty


Meaning there where already files. So it will not clone anything
