### ISSUE TITLE
in vanilla bedrock egg installation script, there is an url type error.

### ISSUE THREAD

**Issue by catalystsitaly** [parkervcp/eggs#241]
DOWNLOAD_URL=https:\/\/www.minecraft.azureedge.net\/bin-linux\/bedrock-server-$BEDROCK_VERSION.zip

The correct url should be https://minecraft.azureedge.net, without 'www'

**Comment by lazarsn** [comment]
https://github.com/parkervcp/eggs/blob/master/minecraft_bedrock/bedrock/egg-vanilla-bedrock.json
