### ISSUE TITLE
[Bug]: No One Survied

### ISSUE THREAD

**Issue by DJKenzoDE** [parkervcp/eggs#2411]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

no one survived

### Modified

No, I did not modify the egg

### Expected Behavior

installed the server, start it and waiting for the "marked as startet/running"

### Actual Behavior

installed server, start the server and the status is starting all the time

### Steps To Reproduce

pull the egg from the rep
install the server
start the server and look ^^

### Install logs

https://pteropaste.com/4vcbhng5swo6

**Comment by QuintenQVD0** [comment]
Install is fine. Change the docker image to `ghcr.io/parkervcp/yolks:wine_latest` staging is buged atm.

**Comment by DJKenzoDE** [comment]
> Install is fine. Change the docker image to `ghcr.io/parkervcp/yolks:wine_latest` staging is buged atm.

"problem" aka bug is solved with wine latest ^^

**Comment by QuintenQVD0** [comment]
This is fixt in wine devel. For now use wine latest. If staging update you can back use staging. Notthing we can directly do about it and it is not worth changing the image of the egg here.
