### ISSUE TITLE
[Bug]: Sons of the Forest - not using pterodactyl primary correct ip when running self-testing.

### ISSUE THREAD

**Issue by VanillaChan6571** [parkervcp/eggs#2413]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

game_eggs/steamcmd_servers/sonsoftheforest

### Modified

No, I did not modify the egg

### Expected Behavior

Use the correct ip.

Usable IPS: x.x.49.171, x.x.49.172, x.x.49.173, x.x.49.174

### Actual Behavior

#DSL [Self-Tests] [Networking] Testing server ports against public ip x.x.49
.170...
#DSE [Self-Tests] [Networking] UDP GamePort [60000] is closed. Please fix and re
start.
#DSE [Self-Tests] [Networking] UDP QueryPort [60001] is closed. Please fix and r
estart.
#DSE [Self-Tests] [Networking] UDP BlobSyncPort [60002] is closed. Please fix an
d restart.
#DSE [Self-Tests] [Networking] Some ports are closed or already in use and the g
ame server will not be accessible. You may need to setup port forwarding and ope
n them in your firewall, or change port numbers if they are used by some other s
oftware. Alternatively, consider using the LanOnly configuration if you didn't i
ntend to make your server public. Please fix and restart.
#DSE [Self-Tests] Please restart the server.

**Using INCORRECT ip as the primary is using x.x.49.171**

### Steps To Reproduce

1. Start Server.
2. Uses incorrect ip.

### Install logs

https://pteropaste.com/28vhmujl9yrc/

**Comment by danny6167** [comment]
Try ticking the Force Outgoing IP in the egg.

**Comment by QuintenQVD0** [comment]
The egg works fine. As told use force outgoing ip as eggs are made and tested with 1 ip in a machine.
