### ISSUE TITLE
[Egg Request]: Update MariaDB's version to 11.0.2

### ISSUE THREAD

**Issue by 4193883-eng** [parkervcp/eggs#2414]
### Does this expand an already existing service

Yes

### Link to a game or software

mariadb.org

### Links for the download

mariadb.org

### Links for the install docs

mariadb.org

**Comment by QuintenQVD0** [comment]
There are already new images. Just the egg has to be rewriten. There already open issues for this.

**Comment by 4193883-eng** [comment]
> There are already new images. Just the egg has to be rewriten. There already open issues for this.

how do i this? (rewrite the egg)

**Comment by QuintenQVD0** [comment]
> > There are already new images. Just the egg has to be rewriten. There already open issues for this.
> 
> how do i this? (rewrite the egg)

It is not aqqeasy sad then done. It is been worked on.
