### ISSUE TITLE
[Egg Request]: Bun

### ISSUE THREAD

**Issue by feartoxb** [parkervcp/eggs#2420]
### Does this expand an already existing service

No

### Link to a game or software

bun.sh

### Links for the download

bun.sh/install

### Links for the install docs

bun.sh/docs/installation

**Comment by realspinelle** [comment]
for u my friend took me an hour

https://github.com/Zastinian/eseggs/blob/master/bun/egg-bun.json

/!\ change "ghcr.io/zastinian/esdock:bun" to "ghcr.io/realspinelle/esdock:bun" as zastinian didnt update his docker image
