### ISSUE TITLE
[Egg Request]: <Neko Self hosted virtual browser>

### ISSUE THREAD

**Issue by candied-apple** [parkervcp/eggs#2424]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/m1k1o/neko

### Links for the download

https://github.com/m1k1o/neko

### Links for the install docs

https://github.com/m1k1o/neko/tree/master/docs

**Comment by QuintenQVD0** [comment]
Pterodactyl is the wrong solution for this, if you really need it run it directly on the host
