### ISSUE TITLE
[Install Bug]: Loki

### ISSUE THREAD

**Issue by TRLKO** [parkervcp/eggs#2429]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

Loki

### Modified

No, I did not modify the egg

### Expected Behavior

Install loki server and run

### Actual Behavior

Error with parsing config

### Steps To Reproduce

Create nie server with Loki egg

### Install logs

failed with parsing config, nothing more. I send pull request in few mins

**Comment by QuintenQVD0** [comment]
@TRLKO What was wrong?
