### ISSUE TITLE
[Bug]: node.js generic

### ISSUE THREAD

**Issue by niridya** [parkervcp/eggs#2434]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

nodejs

### Modified

No, I did not modify the egg

### Expected Behavior

Text added at the end of “Main file” is considered as Node.js args.

### Actual Behavior

Text added at the end of “Main file” cause a crash because “Main file” doesn't end by .js or .ts.

### Steps To Reproduce

Step 1: Go to Startup and “Main file” variable
Step 2: Add an argument after “index.js” (such as number 1 for me)
Step 3: Start your Node.js server

I specify that this problem wasn't present before recent Node.js' egg updates.

### Install logs

https://pteropaste.com/em4n83q7efnu/

**Comment by QuintenQVD0** [comment]
ofc, you are not allowed to enter enything else then a file that ends in .js or .ts, this is not for nodejs args

**Comment by QuintenQVD0** [comment]
@niridya You also leaked your acces token

**Comment by niridya** [comment]
Hi @QuintenQVD0, thanks for your answer!

So, how can we set args on the new Node.js egg?

Thank you for the access token, I regenerated it. Not good that the support command leaks our tokens…

**Comment by QuintenQVD0** [comment]
> Hi @QuintenQVD0, thanks for your answer!
> 
> So, how can we set args on the new Node.js egg?
> 
> Thank you for the access token, I regenerated it. Not good that the support command leaks our tokens…

normaly not as it is a security risk as you can easy make it run extra commands that you may not intend

**Comment by QuintenQVD0** [comment]
> Yes, maybe. I changed the startup command to add my args options. But I steel feel it's a bad idea to prevent users to add args options.

It was and will never be intended by the egg. As normaly a js or ts file do nog need args if coded properly. I will think maybe an extra variable for args. I thin about it.

**Comment by niridya** [comment]
Yes, why not adding a new variable if people wants to use it. It will bring a proper way to add startup args if developers want to use it.
