### ISSUE TITLE
[Bug]: <Arma3> Arma 3 throws error on start (segmentation fault)

### ISSUE THREAD

**Issue by HaxForNox** [parkervcp/eggs#2438]
Please note that pterodactyl is running on UnRaid  
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

Arma 3

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, start , play

### Actual Behavior

Server crashed with 

container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/games 
Digest: sha256:8996439369b6dfacea113470770aa907d4ec84345a0462193af67d4255d7e5d4 
Status: Image is up to date for ghcr.io/parkervcp/games:arma3 
[Pterodactyl Daemon]: Finished pulling Docker container image
[STARTUP_WARN]: Arma 3 Modlist file "modlist.html" could not be found, or is invalid!
        Ensure your uploaded modlist's file name matches your Startup Parameter.
        Only files exported from an Arma 3 Launcher are permitted.
[STARTUP]: Starting checks for all updates...
(It is okay to ignore any "SDL", "steamservice", and "thread priority" errors during this process)
[UPDATE]: Checking for game server updates with App ID: 233780...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1691628584
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Logging in user 'haxfornox_server' to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '233780' already up to date.
[UPDATE]: Game server is up to date!
[STARTUP]: Starting server with the following startup command:
./arma3server_x64 -ip=0.0.0.0 -port=25567 -profiles=./serverprofile -bepath=./ -cfg=basic.cfg -config=server.cfg -mod="" -serverMod="" "-noLogs"
19:11:56 Could not enable linux core dumps. Error 1 - ��)o�
19:11:56 SteamAPI initialization failed. Steam features won't be accessible!
sh: 1: /sbin/ifconfig: not found
19:12:07 Dedicated host created.
19:12:14 BattlEye Server: Initialized (v1.220, Arma 3 2.12.150779)
CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
CApplicationManagerPopulateThread took 1 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
RecordSteamInterfaceCreation (PID 49): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 49): SteamUtils009 / Utils
Setting breakpad minidump AppID = 107410
19:12:14 Game Port: 25567, Steam Query Port: 25568
RecordSteamInterfaceCreation (PID 49): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 49): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 49): SteamNetworking005 / Networking
RecordSteamInterfaceCreation (PID 49): SteamGameServerStats001 / GameServerStats
RecordSteamInterfaceCreation (PID 49): STEAMHTTP_INTERFACE_VERSION002 / HTTP
RecordSteamInterfaceCreation (PID 49): STEAMINVENTORY_INTERFACE_V002 / Inventory
RecordSteamInterfaceCreation (PID 49): STEAMUGC_INTERFACE_VERSION010 / UGC
RecordSteamInterfaceCreation (PID 49): STEAMAPPS_INTERFACE_VERSION008 / Apps
Arma 3 Console version 2.12.150779 x64 : port 25567
19:12:14 Host identity created.
container@pterodactyl~ Server marked as running...
/entrypoint.sh: line 398:    49 Segmentation fault      ${modifiedStartup}
PTDL_CONTAINER_ERR: There was an error while attempting to run the start command.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

1>install egg
2>setup server (this entails ONLY adding steam user name and password)
3>press start after server install.

### Install logs

https://pteropaste.com/0i98d8n0emum/

**Comment by QuintenQVD0** [comment]
Unraid is not supported. There kernel is to old for some games and is missing some inside modules.
