### ISSUE TITLE
[Bug]: Sinusbot

### ISSUE THREAD

**Issue by dension0** [parkervcp/eggs#2439]
### Panel Version

1.1.13

### Wings Version

1.11.7

### Service

/bots/discord/sinusbot

### Modified

No, I did not modify the egg

### Expected Behavior

After install, and start and restart, can connect to TS3 server wich on same server where the Sinubot runing. For connection I use the TS3 server inside docker IP (asked: docker inspect SERVER_UUID_HERE).

### Actual Behavior

Sinsubot Instance do not connect with the right IP. After 2-4 trieing, the Disk space run out from 1 GB.
In consol the Sinsubot says: 
2023/08/20 16:51:49 2dc590d7 39cbe03b INFO   TS |INFO    |              |   |TeamSpeak Client 3.6.1 (2023-07-24 10:06:33)
2023/08/20 16:51:49 2dc590d7 39cbe03b INFO   TS |INFO    |              |   |SystemInformation: Linux 5.10.0-24-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08) x86_64 Binary: 64bit
2023/08/20 16:51:49 2dc590d7 39cbe03b DEBUG  TS>Breakpad crash /home/container/data/ts3/2dc590d7-3a61-4fea-a157-fe4f5cb51fc2/39cbe03b-e3bc-4998-96cb-ddb339418bca/crashdumps/bc024e41-0402-4c63-75be64a6-a2288604.dmp
2023/08/20 16:51:49 2dc590d7 39cbe03b DEBUG  TS>Starting Error Reporter: /home/container/TeamSpeak3-Client-linux_amd64/error_report
2023/08/20 16:51:49 X [MAIN] New connection
2023/08/20 16:51:49 2dc590d7 39cbe03b DEBUG  Closed.
2023/08/20 16:51:49 2dc590d7 39cbe03b INFO   TSClient quit. LogLevel has been increased, please try to connect again to see more details.
2023/08/20 16:51:50 2dc590d7 39cbe03b DEBUG  closing channels
2023/08/20 16:52:17 2dc590d7 39cbe03b DEBUG  Storing configuration.

### Steps To Reproduce

Install on Panel TS3 server with built in original Nest
Install on same Panel and Node the Parkervcp Sinsubot egg
Try to connect to TS3 server with this Sinusbot.

I tried with other sinsubot egg too, but the result was same.

### Install logs

https://pteropaste.com/a0v5yd1u0sa2

**Comment by QuintenQVD0** [comment]
The current sinusbot egg does not work with latest ts3 server because they do not update there code. So the sinusbot egg is locked down to an older version see #2425 but it is still in pr

**Comment by QuintenQVD0** [comment]
Duplicate #2375
