### ISSUE TITLE
[Bug]: Node.JS Generic

### ISSUE THREAD

**Issue by Huguitis** [parkervcp/eggs#2441]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

generic/nodejs

### Modified

No, I did not modify the egg

### Expected Behavior

Start the server without any error.

### Actual Behavior

All NodeJS servers are crashing with this error:

```
node:internal/modules/cjs/loader:1051
  throw err;
  ^
Error: Cannot find module '/home/container/"/home/container/index.js"'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

(Directory and file exists)

### Steps To Reproduce

1. Create a index.js file.
2. Start the NodeJS server.

### Install logs

https://pteropaste.com/1cbf3qjiflui

**Comment by parkervcp** [comment]
do these nodejs apps have an `index.js` file?

**Comment by Huguitis** [comment]
> do these nodejs apps have an `index.js` file?

Yes, correct.

**Comment by parkervcp** [comment]
It looks like you set the file name to `/home/container/index.js` in the fielname and it should just be `index.js`

**Comment by Huguitis** [comment]
> It looks like you set the file name to `/home/container/index.js` in the fielname and it should just be `index.js`

![imagen](https://github.com/parkervcp/eggs/assets/65133800/ac9d1939-ec96-432c-a13f-850a405b9efe)

I do not think so...

**Comment by parkervcp** [comment]
Can you share the repo you are using?

**Comment by Huguitis** [comment]
I'm not using any repo, it's just my discord bot.

**Comment by QuintenQVD0** [comment]
Something is wrong as it is printing 2 times /home/container. Please share the startup and all variables.

**Comment by Huguitis** [comment]
> Something is wrong as it is printing 2 times /home/container. Please share the startup and all variables.

![imagen](https://github.com/parkervcp/eggs/assets/65133800/a252abf1-d82e-4a6c-a332-a9c46a78ecdc)
(Default egg values and startup command)

**Comment by QuintenQVD0** [comment]
> > Something is wrong as it is printing 2 times /home/container. Please share the startup and all variables.
> 
> ![imagen](https://user-images.githubusercontent.com/65133800/263459129-a252abf1-d82e-4a6c-a332-a9c46a78ecdc.png) (Default egg values and startup command)

I see. It looks like something went wrong with my export with the egg that added the addition args.

**Comment by QuintenQVD0** [comment]
@Huguitis Something is wrong with your egg import as you startup is messed up.

![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/c8911473-b070-49d8-84fb-203b8476a0c0)

It looks to me like you edited or have some other egg than this one as your sas NodeJS v20 and the offical sas Nodejs 20
and the startup is messed up so this is not related to the egg as it is working fine.

**Comment by Huguitis** [comment]
> @Huguitis Something is wrong with your egg import as you startup is messed up.
> 
> ![afbeelding](https://user-images.githubusercontent.com/67589015/263459953-c8911473-b070-49d8-84fb-203b8476a0c0.png)
> 
> It looks to me like you edited or have some other egg than this one as your sas NodeJS v20 and the offical sas Nodejs 20 and the startup is messed up so this is not related to the egg as it is working fine.

![imagen](https://github.com/parkervcp/eggs/assets/65133800/98d214ab-98c7-488e-84b6-80f35b34a028)
![imagen](https://github.com/parkervcp/eggs/assets/65133800/e5ec31cd-8f63-4257-b3db-fc887063042b)

Alright now reinstalled the egg completely and getting the same error. Compare my startup command with the one in the egg, it's the same.

**Comment by QuintenQVD0** [comment]
> > @Huguitis Something is wrong with your egg import as you startup is messed up.
> > ![afbeelding](https://user-images.githubusercontent.com/67589015/263459953-c8911473-b070-49d8-84fb-203b8476a0c0.png)
> > It looks to me like you edited or have some other egg than this one as your sas NodeJS v20 and the offical sas Nodejs 20 and the startup is messed up so this is not related to the egg as it is working fine.
> 
> ![imagen](https://user-images.githubusercontent.com/65133800/263460710-98d214ab-98c7-488e-84b6-80f35b34a028.png) ![imagen](https://user-images.githubusercontent.com/65133800/263460715-e5ec31cd-8f63-4257-b3db-fc887063042b.png)
> 
> Alright now reinstalled the egg completely and getting the same error. Compare my startup command with the one in the egg, it's the same.

clearly not? don't you see all the \ faults between the "" for example . It looks like you wrong downloaded the egg off here or coppyed the startup filed out of the .json file directly to the startup field there

**Comment by Huguitis** [comment]
But is the default startup command check it @QuintenQVD0: https://github.com/parkervcp/eggs/blob/master/generic/nodejs/egg-node-js-generic.json

**Comment by QuintenQVD0** [comment]
> But is the default startup command check it @QuintenQVD0: https://github.com/parkervcp/eggs/blob/master/generic/nodejs/egg-node-js-generic.json

your panel shows the direct json startup. the panel on import if done properly should unescape it! so something on your panel modification went wrong on that or the import as it should say:

```bash
if [[ -d .git ]] && [[ {{AUTO_UPDATE}} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; if [[ "${MAIN_FILE}" == "*.js" ]]; then /usr/local/bin/node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; else /usr/local/bin/ts-node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; fi```

**Comment by parkervcp** [comment]
My guess is that the `*.js` is expanding to `/home/container/index.js` and I am working on a fixed start command

**Comment by Huguitis** [comment]
Thanks
