### ISSUE TITLE
[Bug]: Project Zomboid

### ISSUE THREAD

**Issue by KenRen98** [parkervcp/eggs#2446]
### Panel Version

Not Relevant

### Wings Version

Not Relevant

### Service

Start Up

### Modified

No, I did not modify the egg

### Expected Behavior

Expect start up normally

### Actual Behavior

Not starting up, indicating no space for writing backups

### Steps To Reproduce

Once  .Cache  folder exceeds 500MB, the server will not start up. No space for writing the Backups on Start up

Current Solution:
In .cache/Server/ <SERVER_NAME> .ini
Change BackupsOnStart=true  ---->  BackupsOnStart=false 

Tried to use config JSON fix this
But the JSON cant repalce file name/path for custom SERVER_NAME.ini

### Install logs

Not Relevant

**Comment by QuintenQVD0** [comment]
this is not egg releated. that is the game that limits the .cache folder to max 500mb

**Comment by joker-119** [comment]
I can't even get PZ to start at all.

The container just freezes at
`[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
src/tier0/threadtools.cpp (4197) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
[  0%] Checking for available updates...
src/tier0/threadtools.cpp (4197) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
CWorkThreadPool::StartWorkThread: Thread creation failed.`

**Comment by gOOvER** [comment]
> I can't even get PZ to start at all.
> 
> The container just freezes at
> `[Pterodactyl Daemon]: Finished pulling Docker container image
> steam user is not set.
> Using anonymous user.
> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
> src/tier0/threadtools.cpp (4197) : Probably deadlock or failure waiting for thread to initialize.
> Thread failed to initialize
> [  0%] Checking for available updates...
> src/tier0/threadtools.cpp (4197) : Probably deadlock or failure waiting for thread to initialize.
> Thread failed to initialize
> CWorkThreadPool::StartWorkThread: Thread creation failed.`


Post the output of:

`hostnamectl status`

pls

**Comment by QuintenQVD0** [comment]
The 500mb issue is related to the game not to us. I just started my server just fine so my guess is you are running an unsupported system like LXC, OpenVZ or unraid. Else come to the discord
