### ISSUE TITLE
[Egg Request]: TOR router egg

### ISSUE THREAD

**Issue by Motzumoto** [parkervcp/eggs#2447]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.torproject.org

### Links for the download

Not relevant

### Links for the install docs

Not relevant

**Comment by Motzumoto** [comment]
If i want to route my internet traffic through my server to TOR, i feel like having an egg to do this would be pretty beneficial for privacy concerns.

**Comment by gOOvER** [comment]
Ptero is the wrong solution for this

**Comment by Motzumoto** [comment]
> Ptero is the wrong solution for this

You're very right but I was looking for a plug and play solution. Do you know of any other sources that might accomplish this?

**Comment by parkervcp** [comment]
You can google for docker containers and compose files to do what you want.

**Comment by Motzumoto** [comment]
> You can google for docker containers and compose files to do what you want.

Okie dokie appreciate it greatly
