### ISSUE TITLE
[Egg Request]: <Software> Dashy

### ISSUE THREAD

**Issue by H1ghSyst3m** [parkervcp/eggs#2452]
### Does this expand an already existing service

No

### Link to a game or software

https://dashy.to/

### Links for the download

https://github.com/Lissy93/dashy/tree/master

### Links for the install docs

https://dashy.to/docs/deployment

**Comment by parkervcp** [comment]
This is similar to uptime kuma so it at least makes some sense.

**Comment by QuintenQVD0** [comment]
Last release was over a year ago, we will not make eggs for non updated software

**Comment by parkervcp** [comment]
It also looks like this may be able to run in the nodejs generic egg so I am going to close it out.
