### ISSUE TITLE
[Bug]: Icarus Dedicated (stuck on startup)

### ISSUE THREAD

**Issue by Ballaual** [parkervcp/eggs#2457]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

game_eggs/steamcmd_servers/icarus

### Modified

No, I did not modify the egg

### Expected Behavior

Install and start the server from Pterodactyl

### Actual Behavior

Installation seems work fine.
When starting the server some messages from wine appear which seems fine so far.
When launching the server it will stuck und starting and not marked as running

> container@pterodactyl~ Server marked as starting...
> Running on Debian 11.7
> Current timezone: Etc/UTC
> wine-8.14 (Staging)
> steam user is not set.
> 
> Using anonymous user.
> 
> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
> [  0%] Checking for available updates...
> [----] Verifying installation...
> Steam Console Client (c) Valve Corporation - version 1691628584
> -- type 'quit' to exit --
> Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
> OK
> 
> Connecting anonymously to Steam Public...OK
> Waiting for client config...OK
> Waiting for user info...OK
> "@sSteamCmdForcePlatformType" = "windows"
> Success! App '2089300' already up to date.
> First launch will throw some errors. Ignore them
> Installing vcrun2019
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter > problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> Using winetricks 20230212-next - sha256sum: be4196ba3358be7c68cb58e7a7cbe9b37418e12e92beb88876e119998f438532 > with wine-8.14 (Staging) and WINEARCH=win64
> Executing w_do_call vcrun2019
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter > problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> vcrun2019 already installed, skipping
> Installing corefonts
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter > problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> Using winetricks 20230212-next - sha256sum: be4196ba3358be7c68cb58e7a7cbe9b37418e12e92beb88876e119998f438532 > with wine-8.14 (Staging) and WINEARCH=win64
> Executing w_do_call corefonts
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter > problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> corefonts already installed, skipping
> :/home/container$ wine64 ./Icarus/Binaries/Win64/IcarusServer-Win64-Shipping.exe -Log -SteamServerName=${SERVER_NAME} -PORT="${SERVER_PORT}" -QueryPort="${QUERY_PORT}"

### Steps To Reproduce

Implement current egg version and install / start server

### Install logs

https://pteropaste.com/vcqrpol3yoou/

**Comment by gOOvER** [comment]
Icarus Egg is broken since a Long time. the author should fix it

**Comment by Ballaual** [comment]
> Icarus Egg is broken since a Long time. the author should fix it
> 
> you can also try wine_stable as Image

wine_latest will start the server but with a lot of warn and error messages.
dont know if thats actually correct.

https://pastebin.com/zGgZeBDE

**Comment by QuintenQVD0** [comment]
> > Icarus Egg is broken since a Long time. the author should fix it
> > you can also try wine_stable as Image
> 
> wine_latest will start the server but with a lot of warn and error messages. dont know if thats actually correct.
> 
> https://pastebin.com/zGgZeBDE

Thatq normal. If you can join it is fine.

**Comment by Ballaual** [comment]
> > > Icarus Egg is broken since a Long time. the author should fix it
> > > you can also try wine_stable as Image
> > 
> > 
> > wine_latest will start the server but with a lot of warn and error messages. dont know if thats actually correct.
> > https://pastebin.com/zGgZeBDE
> 
> Thats normal. If you can join it is fine.

will try it out later and update the egg at least for this issue.

**Comment by Ballaual** [comment]
> Icarus Egg is broken since a Long time. the author should fix it
> 
> you can also try wine_stable as Image

just quick information:
server runs perfectly with wine_latest and also starting / loading open world missions without crashing (can not confirm the open issue which says the server is crashing). egg got updated so egg runs well for now. the configuration part was a bit tricky/confusing but once you're into it this works well too.
