### ISSUE TITLE
[Bug]: Generic Python

### ISSUE THREAD

**Issue by Liscuri** [parkervcp/eggs#2459]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

python generic

### Modified

No, I did not modify the egg

### Expected Behavior

The server fully starts except the server status changed to started (Green color)

### Actual Behavior

The server fully starts just the server status stays on starting (Yellow color)

### Steps To Reproduce

Step 1. Add egg
Step 2. Make server
Step 3. Start server
Step 4. See for yourself

### Install logs

https://pteropaste.com/xls3q4xhadng/

**Comment by danny6167** [comment]
This isn't a bug - You did not read the readme for the egg at all
https://github.com/parkervcp/eggs/tree/master/generic/python

**Comment by QuintenQVD0** [comment]
This is because you did not read the Readme and not configured the egg!
