### ISSUE TITLE
Fivem Error

### ISSUE THREAD

**Issue by XxTopKillerzZ** [parkervcp/eggs#246]
The fivem install script is broken. i fixed it, here's the final code.
`#!/bin/ash 

apk add openssl tar xz curl wget git --no-cache

cd /mnt/server

mkdir resources

echo "updating citizenfx resource files"
git clone https://github.com/citizenfx/cfx-server-data.git /tmp
cp -Rf /tmp/resources/* resources/ 

cd /mnt/server

echo -e "pulling files from https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/${latest_fivem_url}fx.tar.xz"
wget https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/${FIVEM_VERSION}/fx.tar.xz

echo "Extracting fivem files"

tar xf fx.tar.xz

rm -rf fx.tar.xz run.sh

if [ -e server.cfg ]; then
    echo "server config file exists"
else
    echo "Downloading default fivem config"
    curl https://raw.githubusercontent.com/parkervcp/eggs/master/gta/fivem/server.cfg >> server.cfg
fi

mkdir logs/

echo "install complete"`

Its was missing a "/" after ${FIVEM_VERSION}

Also, is it possible to have more than 30 players suport, with the new onesync? We can talk if you need help doing it but to enable it you need:
add +set onesync_enabled 1 or +set onesync_enabled 0 in the Startup Command depending if you want more than 30 players and then sv_maxplayers need to adapt based on the onesync status.

**Comment by parkervcp** [comment]
I have said no to onesync in more than one issue and will continue to not enable onesync intul it;s out of beta.
