### ISSUE TITLE
[Bug]: <Python Generic>

### ISSUE THREAD

**Issue by Blue-Gamer48** [parkervcp/eggs#2462]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

Python Programm General

### Modified

No, I did not modify the egg

### Expected Behavior

Program is stopped properly and completely

### Actual Behavior

Server hangs in stop process and can only be stopped with kill

### Steps To Reproduce

Starting des Programms and Stopping Wait for 5 Minutes

### Install logs

https://pteropaste.com/vo1nq5x2ukvi

**Comment by gOOvER** [comment]
know issue and could be fixed with searching discord or github before.

Change stopcmd to ^^C

**Comment by Blue-Gamer48** [comment]
Where

**Comment by Blue-Gamer48** [comment]
> know issue and could be fixed with searching discord or github before.
> 
> Change stopcmd to ^^C

I hav this change the bug is not fixed

**Comment by gOOvER** [comment]
post consoleoutput of the stop pls

**Comment by Blue-Gamer48** [comment]
I have a fix

In the start config from the egg is this:
![Screenshot_2023-09-08-15-06-25-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/parkervcp/eggs/assets/97996264/3d038d9b-5ec6-49f4-8b22-0a088b694930)

{
  "done":[
    "Start one succes",
    "start thwo succes"
  ]
}

**Comment by gOOvER** [comment]
> I have a fix
> 
> In the start config from the egg is this: ![Screenshot_2023-09-08-15-06-25-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/97996264/266619548-3d038d9b-5ec6-49f4-8b22-0a088b694930.jpg)

Thats not a fix for stopcmd and your problem described.

Please read the readme BEFORE ;)

**Comment by QuintenQVD0** [comment]
If the server is not marked as started, then you did not configure the egg.
IF on stop it does not exit and hangs, than set the stop cmd of the egg to `^^C`  as Goover mentioned.
