### ISSUE TITLE
[Egg Request]: FastAPI

### ISSUE THREAD

**Issue by FreemoX** [parkervcp/eggs#2463]
### Does this expand an already existing service

Yes

### Link to a game or software

https://fastapi.tiangolo.com/

### Links for the download

https://github.com/tiangolo/fastapi

### Links for the install docs

https://fastapi.tiangolo.com/tutorial/

**Comment by iamkubi** [comment]
This is just a Python library, you should be able to use the discord.py egg for it.

**Comment by dagbs** [comment]
https://github.com/parkervcp/eggs/tree/master/generic/python

**Comment by FreemoX** [comment]
I tried using the python egg, but it complains about not finding uvicorn despite it being installed during installation
