### ISSUE TITLE
[Egg Request]: Wiki.js

### ISSUE THREAD

**Issue by FreemoX** [parkervcp/eggs#2464]
### Does this expand an already existing service

No

### Link to a game or software

https://js.wiki/

### Links for the download

https://github.com/requarks/wiki

### Links for the install docs

https://docs.requarks.io/

**Comment by QuintenQVD0** [comment]
Yea no. Needs a postgress db, it currently does support mariadb. But it needs a browser installed so no as containers are headless

**Comment by FreemoX** [comment]
> Yea no. Needs a postgress db, it currently does support mariadb. But it needs a browser installed so no as containers are headless

Doesn't **_need_** postgress. As you stated, it supports database connection, including MySQL/MariaDB, which are already available eggs and connectable. 
And it doesn't require a browser being installed; I've successfully installed and run it on a headless ubuntu lab server that doesn't have a browser installed. 
If you're referring to the docs mentioning setup being accessible from localhost, that can easily be replaced with the server IP

**Comment by QuintenQVD0** [comment]
> > Yea no. Needs a postgress db, it currently does support mariadb. But it needs a browser installed so no as containers are headless
> 
> Doesn't **_need_** postgress. As you stated, it supports database connection, including MySQL/MariaDB, which are already available eggs and connectable. And it doesn't require a browser being installed; I've successfully installed and run it on a headless ubuntu lab server that doesn't have a browser installed. If you're referring to the docs mentioning setup being accessible from localhost, that can easily be replaced with the server IP

When v3 comes out postgress will be required so making this egg will not work anymore when it releases and having postgress and wiki.js in the same egg/image is a pain

**Comment by FreemoX** [comment]
Right, fair point, I never looked at their roadmap, shame they're going with postgress only for 3x ...
