### ISSUE TITLE
[Egg Request]: Draupnir

### ISSUE THREAD

**Issue by Tealk** [parkervcp/eggs#2469]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/the-draupnir-project/Draupnir

### Links for the download

https://hub.docker.com/r/gnuxie/draupnir

### Links for the install docs

https://github.com/the-draupnir-project/Draupnir/blob/main/docs/setup.md

**Comment by Tealk** [comment]
I've tried it myself, but I don't really understand the system yet. There is already a ready-made Docker image from Droupnir, if I use that I don't need an install command?

**Comment by QuintenQVD0** [comment]
> I've tried it myself, but I don't really understand the system yet. There is already a ready-made Docker image from Droupnir, if I use that I don't need an Startup Command?

You can not use regular docker images for pterodactyl. They have to be made for it and no files can be in the docker image. Only packages

**Comment by QuintenQVD0** [comment]
It needs yarn and has to be build from source. So some modification will be needed

**Comment by Tealk** [comment]
I have tried a little, but does not work
[egg-draupnir.json.txt](https://github.com/parkervcp/eggs/files/12640788/egg-draupnir.json.txt)

**Comment by gOOvER** [comment]
> It needs yarn and has to be build from source. So some modification will be needed

can be done in installscript

**Comment by Tealk** [comment]
I don't quite understand the installation script, it downloads something but I don't see any data in the container.

**Comment by QuintenQVD0** [comment]
> I don't quite understand the installation script, it downloads something but I don't see any data in the container.

https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md#be-aware-of-the-pterodactyl-install-process

**Comment by gOOvER** [comment]
> I don't quite understand the installation script, it downloads something but I don't see any data in the container.

please use generic nodejs egg and adapt it to your needs.

i would Take to Long, to explain all

**Comment by QuintenQVD0** [comment]
with litte modification the generic nodejs egg will run this.

or custom
Install image: `node:18-bullseye`
Install shell: `bash`
install script:

```
#!/bin/bash

apt update
apt install -y git curl

mkdir -p /mnt/server
cd /mnt/server

git clone https://github.com/gnuxie/draupnir.git .
npm i -g yarn

yarn install
yarn build

cp config/default.yaml config/production.yaml
nano config/production.yaml

echo "done"
```
server image:  `ghcr.io/parkervcp/yolks:nodejs_18`
and the startup cmd as:

`node lib/index.js --draupnir-config ./config/production.yaml`

then you would only need to manual set the port
