### ISSUE TITLE
[Egg Request]: ntfy server 

### ISSUE THREAD

**Issue by diedyesterdaywashere** [parkervcp/eggs#2471]
### Does this expand an already existing service

No

### Link to a game or software

https://ntfy.sh

### Links for the download

https://github.com/binwiederhier/ntfy/releases/

### Links for the install docs

https://docs.ntfy.sh/install/

**Comment by QuintenQVD0** [comment]
Pterodactyl is the wrong solution for this as you for like any action need to change the startup command and that is not secure
