### ISSUE TITLE
[Bug]: JMusicBot - Discord user id validation

### ISSUE THREAD

**Issue by phit** [parkervcp/eggs#2474]
### Panel Version

1.11.3

### Wings Version

1.11.4

### Service

JMusicBot

### Modified

No, I did not modify the egg

### Expected Behavior

Can put in my Discord user id, because validation is set to `digits_between:17,18`

### Actual Behavior

Can't put in my user id because its too short

### Steps To Reproduce

Try to set owner id variable to my discord id `66235899918159872`, validation expects 18 digits but 17 digits are valid for older accounts

https://github.com/parkervcp/eggs/blob/c3a9240ee9fbfe442668e20794ea9c380102bdd4/bots/discord/jmusicbot/egg-j-music-bot.json#L48

### Install logs

N/A

**Comment by parkervcp** [comment]
That validation should be 17 or 18 characters long.

**Comment by parkervcp** [comment]
@phit You could submit a PR to resolve this issue as you have already identified a fix it appears.
