### ISSUE TITLE
[Egg Update Request]: <Software/Game>

### ISSUE THREAD

**Issue by elysium38711** [parkervcp/eggs#2477]
### Does this expand an already existing service

Yes

### Link to a game or software

https://steamdb.info/app/1670340/

### Links for the download

https://steamdb.info/app/1670340/

### Links for the install docs

Not sure?

**Comment by elysium38711** [comment]
Craftopia just released this a few days ago. Can we update the Egg? It changed with the seamless world update.

**Comment by parkervcp** [comment]
What needs to change here? The server appid hasn't changed

**Comment by elysium38711** [comment]
Does the appid when installing the server just automatically pull from the updated version there?

**Comment by parkervcp** [comment]
It gets whatever server version is on steams end. If they didn't update the server files then you need to wait,

**Comment by elysium38711** [comment]
Alright. We can close this then. Its not up to date yet. I thought it was. nvm

**Comment by gOOvER** [comment]
There is no new Server release yet. It was planned in September.
