### ISSUE TITLE
[Bug]: Uptime Kuma

### ISSUE THREAD

**Issue by FreemoX** [parkervcp/eggs#2478]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

Uptime Kuma

### Modified

No, I did not modify the egg

### Expected Behavior

After egg installation and giving Uptime Kuma a websocket-enabled subdomain (or when connecting directly using the port, either on public or local IP), the user should be directed to the setup screen/dashboard where the user may set up their instance according to their preferences

### Actual Behavior

The URL redirects to /setup-database which displays a "Page not found" error page.
Additionally, the browser console reports of websocket issues.

Actual browser console log entries:
```
Failed to connect to the backend. Socket.io connect_error: websocket error
WebSocket connection to 'ws://uptime.mysite.com/socket.io/?EIO=4&transport=websocket' failed:
```

Additionally, the server console log:
```
npm ERR! A complete log of this run can be found in: /home/container/.npm/_logs/2023-09-24T11_50_50_126Z-debug-0.log
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /home/container/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c node index.js --exec install
npm ERR! Installing Cypress (version: 13.2.0)
npm ERR! 
npm ERR! [STARTED] Task without title.
npm ERR! [TITLE]  Downloading Cypress      0% 0s
npm ERR! node:events:492
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! 
npm ERR! Error: ENOSPC: no space left on device, write
npm ERR! Emitted 'error' event on WriteStream instance at:
npm ERR!     at WriteStream.onerror (node:internal/streams/readable:785:14)
npm ERR!     at WriteStream.emit (node:events:514:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   errno: -28,
npm ERR!   code: 'ENOSPC',
npm ERR!   syscall: 'write'
npm ERR! }
```

### Steps To Reproduce

1. Setup server and install egg
2. Await installation completion
3. Navigate to the instance URL

### Install logs

https://pteropaste.com/syjs884u2bni

**Comment by QuintenQVD0** [comment]
no space left on device, write

you are out  of disk space or you have to increase tempfs size in the wings config file

**Comment by FreemoX** [comment]
Also note, the console complains about "npm ERR! Error: ENOSPC: no space left on device, write"; this is false in regards of the server space, as both the physical server, and the instance, both have more-than-required storage space

**Comment by QuintenQVD0** [comment]
> Also note, the console complains about "npm ERR! Error: ENOSPC: no space left on device, write"; this is false in regards of the server space, as both the physical server, and the instance, both have more-than-required storage space

your tempfs not.

**Comment by FreemoX** [comment]
6.3GB available in tempfs

**Comment by FreemoX** [comment]
> > Also note, the console complains about "npm ERR! Error: ENOSPC: no space left on device, write"; this is false in regards of the server space, as both the physical server, and the instance, both have more-than-required storage space
> 
> your tempfs not.

Don't be so quick to close this issue ..

**Comment by QuintenQVD0** [comment]
> 6.3GB available in tempfs
> 
> ```
> # df -h
> Filesystem                         Size  Used Avail Use% Mounted on
> tmpfs                              6.3G  2.8M  6.3G   1% /run
> /dev/mapper/ubuntu--vg-ubuntu--lv  1.9T   88G  1.8T   5% /
> tmpfs                               32G     0   32G   0% /dev/shm
> tmpfs                              5.0M     0  5.0M   0% /run/lock
> /dev/sda2                          2.0G  251M  1.6G  14% /boot
> tmpfs                              6.3G  4.0K  6.3G   1% /run/user/1000
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/3355d54ad72e1bf7dd6c2b17f6cb99cb63ba78a4935c36275c2f5420bd6de18b/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/fbf1a4ad06cdeccd96699037a8d8ddc9ce19502fb68eb914ac6709e8de54b5b1/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/0c9f223b9071808790edfba4d01b429a74babead3c8b64742fbeecb5f19a012a/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/97a031b41ec8d21da86e64d2dce9afe8d6a6c6546893d095e99f717c821c17b8/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/4f977115a68302715a7153b0f65ad337589ed25ec8cc726a4c4635075587ba18/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/8abd297c8bf40409ee4bf1420c8ec2badb851224a32f98545e643475a4cfb34f/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/789d4522119b38761ac880cd381f51e4a43191f063a80de3c32475d0cc79d1ef/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/9a1a2b716ee6fc13b6941376c6823b5cfb516259f82ee1c8386c1b2c87fadd4c/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/75641e86984f3fc139e257a8e549def472b86a17c79a742ab8bbaf64dc6ede8b/merged
> overlay                            1.9T   88G  1.8T   5% /var/lib/docker/overlay2/4f65e278d07b183b931d18224e58ca1d27366f7c9f3c0d08d8483c1595631832/merged
> ```

Pterodactyl has its own tempfs ...

**Comment by QuintenQVD0** [comment]
so open the wings config file, looks for tempfs , increase it like bedault value * 10 (or *5) save it, restart the wings and try again

**Comment by FreemoX** [comment]
> so open the wings config file, looks for tempfs , increase it like bedault value * 10 (or *5) save it, restart the wings and try again

The container tempfs is 1024 (too high for most uses, but required due to some custom eggs)

**Comment by QuintenQVD0** [comment]
> > so open the wings config file, looks for tempfs , increase it like bedault value * 10 (or *5) save it, restart the wings and try again
> 
> The container tempfs is ~1024~ 512 (too high for most uses, but required due to some custom eggs)

Cypress zip 190 mb  + the unpacked zip 650 mb + npm logs 150 mb = more then 512

**Comment by QuintenQVD0** [comment]
and yes I did close this as this is not an egg issue, this is a configuarion issue what support is for in the discord.

**Comment by FreemoX** [comment]
> and yes I did close this as this is not an egg issue, this is a configuarion issue what support is for in the discord.

Increased to 1024, that did indeed allow cypress to install properly, but did not resolve my described issue with the URL being redirected to /setup-database.

As a side-note, the egg README.md file should probably include a mention about this non-standard requirement

**Comment by QuintenQVD0** [comment]
> > and yes I did close this as this is not an egg issue, this is a configuarion issue what support is for in the discord.
> 
> Increased to 1024, that did indeed allow cypress to install properly, but did not resolve my described issue with the URL being redirected to /setup-database.
> 
> As a side-note, the egg README.md file should probably include a mention about this non-standard requirement

The egg may be removed in the future as ping does not even work

**Comment by FreemoX** [comment]
> The egg may be removed in the future as ping does not even work

Oh, well that's kinda breaking for a service supposed to check if services are alive..
Thanks for clarifying, I won't waste more time trying to get the egg to work

**Comment by gOOvER** [comment]
> > > and yes I did close this as this is not an egg issue, this is a configuarion issue what support is for in the discord.
> > 
> > 
> > Increased to 1024, that did indeed allow cypress to install properly, but did not resolve my described issue with the URL being redirected to /setup-database.
> > As a side-note, the egg README.md file should probably include a mention about this non-standard requirement
> 
> The egg may be removed in the future as ping does not even work

Not really sth, that a egg must be removed, only while ping not working

**Comment by gOOvER** [comment]
> Cypress

cant confirm the issue with the redirect. Works fine. After install and start, it direct you to dashboard
