### ISSUE TITLE
[Egg Request]: <Rimworld Open World>

### ISSUE THREAD

**Issue by jakub961241** [parkervcp/eggs#2481]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/294100/RimWorld/

### Links for the download

https://github.com/D12-Dev/OpenWorld/releases/tag/v1.0.4

### Links for the install docs

https://github.com/D12-Dev/OpenWorld

**Comment by yesBad** [comment]
Already exists as far as I can see.

**Comment by QuintenQVD0** [comment]
Already in the repo.

**Comment by jakub961241** [comment]
ok thanks
