### ISSUE TITLE
[Bug]: <FiveM>

### ISSUE THREAD

**Issue by shaino7** [parkervcp/eggs#2486]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

start the fivem server, then attempt to stop.

### Actual Behavior

Sever does not shutdown, instead it says marked as offline when it isn't.

### Steps To Reproduce

Step 1 download the fivem egg
Step 2 run the server
Step 3 Attempt to shutdown the server

### Install logs

https://pteropaste.com/usyk2rzfg1xn

**Comment by shaino7** [comment]
thanks, much appreciated!

**Comment by MASRPNathan-G** [comment]
Whats the link to the PR?
