### ISSUE TITLE
[Install Bug]: ET Legacy

### ISSUE THREAD

**Issue by SulivanM** [parkervcp/eggs#2487]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

etlegacy

### Modified

No, I did not modify the egg

### Expected Behavior

That the game server can launch without problems.

### Actual Behavior

In installation we have a error and when we want to start we have this :

Error in install :
![image](https://github.com/parkervcp/eggs/assets/139988886/3801dee5-ef4b-4878-9d03-e48f9219d58b)

Error in start :
![image](https://github.com/parkervcp/eggs/assets/139988886/b42dbca9-309c-4983-b77e-eaaa4be0500e)

### Steps To Reproduce

Step 1 : Get The Last Version Of Pterodactyl
Step 2 : Download The Egg
Step 3 : Install And Run The Game And See Errors

### Install logs

pteropaste.com/6d4fz8z1

**Comment by gOOvER** [comment]
can not write.....

Sounds like No diskspace

**Comment by parkervcp** [comment]
This is definitely not the egg causing the issue. This looks like there is a disk space issue and you need to resolve that.

**Comment by SulivanM** [comment]
Hello,

Today, I checked the disk space in my virtual machine, and I allocated more 300GB for it. I currently have ample space available, as I've managed to create 8 Minecraft servers. Is it possible for you to verify if the server egg is functioning correctly on your end?

Best regards,

**Comment by gOOvER** [comment]
> Hello,
> 
> Today, I checked the disk space in my virtual machine, and I allocated more 300GB for it. I currently have ample space available, as I've managed to create 8 Minecraft servers. Is it possible for you to verify if the server egg is functioning correctly on your end?
> 
> Best regards,

do a 

`ls -a`

as root

**Comment by SulivanM** [comment]
![image](https://github.com/parkervcp/eggs/assets/139988886/6f8e0a7d-5209-43a3-99ed-a94d1b5b77c2)
![image](https://github.com/parkervcp/eggs/assets/139988886/bf6929fd-02fb-4f9d-84c6-ad38aa5439fe)
For you 👍

**Comment by gOOvER** [comment]
and now pls:

hostnamectl status

**Comment by SulivanM** [comment]
![image](https://github.com/parkervcp/eggs/assets/139988886/67562473-77f8-49c1-b018-3e6dfa7b289a)
Oh yes its LXC x)
Its really bad is not supported, i need to remake maybe my vm :)

**Comment by gOOvER** [comment]
> ![image](https://user-images.githubusercontent.com/139988886/273449411-67562473-77f8-49c1-b018-3e6dfa7b289a.png) Oh yes its LXC x) Its really bad is not supported, i need to remake maybe my vm :)

LXC is not supported. switch to KVM; else you are alone  and no support for you ;)

**Comment by SulivanM** [comment]
Oh okay, i make that and i tell you for progress, thanks !

**Comment by gOOvER** [comment]
> Oh okay, i make that and i tell you for progress, thanks !

really senseless to host a container in a container ;)

**Comment by SulivanM** [comment]
Yes, my technician did something wrong, I have to correct that :p

**Comment by wahke** [comment]
Hello , i modify the EGG for ET Legacy and this works
https://github.com/wahke/etl_egg

**Comment by SulivanM** [comment]
Confirmed, works now !
