### ISSUE TITLE
[Egg Feature Request]: Minecraft Curseforg egg allow for installation of additional Mods

### ISSUE THREAD

**Issue by Jodsderechte** [parkervcp/eggs#2488]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/parkervcp/eggs/tree/master/game_eggs/minecraft/java/curseforge

### Links for the download

https://github.com/parkervcp/eggs/tree/master/game_eggs/minecraft/java/curseforge

### Links for the install docs

I'm gonna blatently use this field to do a bit of description instead of putting another Link here (since there is no other field to actually add some context). However Curseforge modpacks have the ability to add specific mods to them. E.g. some people like to install optifine or other things additionally. Now there are mods that are either Serverside only e.g. WorldEDIT or ones that would be interesting to load for both partys. What i'd like would be an option to specify additional mods to be loaded. an Id list with comma seperated values or other things. This does not need to interact with the modpack install and should just install those mods seperatly onto the Server. I tried looking into how the egg handles installations but sadly my understanding of shell is non existant.

**Comment by parkervcp** [comment]
If someone wants to PR a change to the logic they can. Otherwise the mods can be uploaded by the user.

I won't be keeping this open.
