### ISSUE TITLE
[Egg Request]: MariaDB 10.7

### ISSUE THREAD

**Issue by Apfelmoes** [parkervcp/eggs#2491]
### Does this expand an already existing service

Yes

### Link to a game or software

https://mariadb.com/

### Links for the download

https://mariadb.com/downloads/

### Links for the install docs

https://www.mariadbtutorial.com/getting-started/install-mariadb/

**Comment by parkervcp** [comment]
mariadb after 10.3 is currently broken and waiting on a PR and wings release. I already have plans to split the mariadb egg into individual versions later
