### ISSUE TITLE
[Egg Request]: CS2

### ISSUE THREAD

**Issue by KenRen98** [parkervcp/eggs#2496]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/730/CounterStrike_2/

### Links for the download

https://store.steampowered.com/app/730/CounterStrike_2/

### Links for the install docs

https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers

**Comment by QuintenQVD0** [comment]
We will not run the client. This can be re opend if they update app id 740 to support cs2. As the clients needs a non steam guard account that owns the game.
