### ISSUE TITLE
[Bug]: Feed The Beast

### ISSUE THREAD

**Issue by HerrSammyDE** [parkervcp/eggs#2501]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/java/ftb/egg-ftb-modpacksch-server.json

### Modified

No, I did not modify the egg

### Expected Behavior

Server install, start, play

### Actual Behavior

Server installed but does not start because the "start-server.jar" is not renamed or present.

### Steps To Reproduce

1. Import Egg
2. Add "FTB modpack ID" `119` (https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120)
3. Let install and try to start the server

### Install logs

https://ptero.co/hehisocyta.cs

**Comment by cc3768** [comment]
Same problem. But it keeps showing a headless problem
![image](https://github.com/parkervcp/eggs/assets/5598486/dcf5b882-7a1f-459c-b96a-b5cd8cdb9c2f)

**Comment by F9Alejandro** [comment]
Take a look at the files section of the server. There should be a new file called run.sh and run.bat, update that startup to use ./run.sh and it should start properly and popup for eula acceptance.

**Comment by QuintenQVD0** [comment]
> Take a look at the files section of the server. There should be a new file called run.sh and run.bat, update that startup to use ./run.sh and it should start properly and popup for eula acceptance.

Offical eggs do not allow startup cmd to be a scripr for sequiry reasons.

**Comment by F9Alejandro** [comment]
okay well start-server.jar is for install mainly and will yell about gui everytime if --installserver is not added as an arg. Do you know if there is another jar file that should be used in its place?

**Comment by QuintenQVD0** [comment]
> okay well start-server.jar is for install mainly and will yell about gui everytime if --installserver is not added as an arg. Do you know if there is another jar file that should be used in its place?

the egg install script should have installed the server, not the main server

**Comment by F9Alejandro** [comment]
unix_args.txt is not in the base directory and is different per install. For dw 20 1.20 w/ forge it is under libraries/net/neoforged/forge/1.20.1-47.1.76
I had to make a copy of the unix_args.txt and move it to the base directory in order for it to be seen by the startup line.

**Comment by HerrSammyDE** [comment]
Are there any solutions so we can make the Egg work for all versions, like was done with the CurseForge Egg?

**Comment by QuintenQVD0** [comment]
This can be closed as of #2521
