### ISSUE TITLE
[Egg Request]: The Front

### ISSUE THREAD

**Issue by dagbs** [parkervcp/eggs#2504]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/2285150/The_Front/

### Links for the download

https://steamdb.info/app/2334200/

### Links for the install docs

https://www.survivalservers.com/wiki/index.php?title=How_to_Create_The_Front_Server_Guide

**Comment by AhrimFakhriy** [comment]
I would love to have this egg as well

**Comment by Dan-Mizu** [comment]
Looking forward to this egg as well.

**Comment by QuintenQVD0** [comment]
Instad of saying i want this. This it download when no user id loged in ? Has anyone tried wine latest with winetricks or proton?

**Comment by Dan-Mizu** [comment]
I own the game on steam and have an ubuntu-server pterodactyl panel set up if you need me to test any eggs. Just send me the clear instructions and I will try it.

**Comment by QuintenQVD0** [comment]
> I own the game on steam and have an ubuntu-server pterodactyl panel set up if you need me to test any eggs. Just send me the clear instructions and I will try it.

No, there is no point to that, we will/ can not make an egg if you need to own the game to download the server files

**Comment by gOOvER** [comment]
> I own the game on steam and have an ubuntu-server pterodactyl panel set up if you need me to test any eggs. Just send me the clear instructions and I will try it.

wasted time, to send eggs from one to one.

spend me a Key and i will create an egg

**Comment by gOOvER** [comment]
> I own the game on steam and have an ubuntu-server pterodactyl panel set up if you need me to test any eggs. Just send me the clear instructions and I will try it.

wasted time, to send eggs from one to one.

spend me a Key and i will create an egg

**Comment by Dan-Mizu** [comment]
> > I own the game on steam and have an ubuntu-server pterodactyl panel set up if you need me to test any eggs. Just send me the clear instructions and I will try it.
> 
> wasted time, to send eggs from one to one.
> 
> spend me a Key and i will create an egg

how can I provide this key? from where?

**Comment by QuintenQVD0** [comment]
my guess as it does not run with proton it also will not with wine

![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/1b01b771-5ceb-4a89-90bf-e5bb67fece3c)

**Comment by QuintenQVD0** [comment]
> > > I own the game on steam and have an ubuntu-server pterodactyl panel set up if you need me to test any eggs. Just send me the clear instructions and I will try it.
> > 
> > 
> > wasted time, to send eggs from one to one.
> > spend me a Key and i will create an egg
> 
> how can I provide this key? from where?

he is telling to buy him a key for the game and then he will make an egg for it

**Comment by QuintenQVD0** [comment]
![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/47e841fb-7ed2-47cd-810e-e4374c6d627a)


It seems to download anonymous

**Comment by gOOvER** [comment]
after some tests; The Server do not run in Docker yet, because it needs a dir outsite the container.

**Comment by dagbs** [comment]
> after some tests; The Server do not run in Docker yet, because it needs a dir outsite the container.
> 
> `Failed to create //.cache for shader cache (Read-only file system)---disabling.`

ENVs of `XDG_CACHE_HOME` and `HOME` could be the issue?

**Comment by QuintenQVD0** [comment]
> `XDG_CACHE_HOME`

The HOME variable is set by default.

no idea wy they would use XDG_CACHE_HOME

**Comment by gOOvER** [comment]
> > after some tests; The Server do not run in Docker yet, because it needs a dir outsite the container.
> > 
> > `Failed to create //.cache for shader cache (Read-only file system)---disabling.`
> 
> ENVs of `XDG_CACHE_HOME` and `HOME` could be the issue?

thats a server, so why i need shader Cache? they should fix their dedicated Server.

**Comment by gOOvER** [comment]
```
info:  Game: TheFrontServer.exe
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4ad3f30
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
err:   DxvkInstance: Required instance extensions not supported
err:   D3D11CreateDevice: Failed to create a DXGI factory
```

They really want a real Win System :D Thats hard. They dont know, how to create a real UE Server :D

**Comment by SirOMGitsYOU** [comment]
> ```
> info:  Game: TheFrontServer.exe
> info:  DXVK: v2.3
> info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4ad3f30
> info:  Built-in extension providers:
> info:    Win32 WSI
> info:    OpenVR
> info:    OpenXR
> info:  OpenVR: could not open registry key, status 2
> info:  OpenVR: Failed to locate module
> info:  Required Vulkan extension VK_KHR_surface not supported
> err:   DxvkInstance: Required instance extensions not supported
> err:   D3D11CreateDevice: Failed to create a DXGI factory
> ```
> 
> They really want a real Win System :D Thats hard. They dont know, how to create a real UE Server :D
> 
> Tell the devs, they should start reading, how to create an Server for UE. i know 1 man Games, which have better servers then them :D

Someone just posted this in the front discord server, https://steamdb.info/app/2334200/info/ - Looks like the devs are working on / released a linux version of the server files

**Comment by AhrimFakhriy** [comment]
Someone posted a guide on Discord on how to run this game on Linux. 
Below is his message:

> I got a server running on linux for those interested. It looks like there is something going on with the steam download servers and in most instances `app_update` downloads an older version.

1. Open steamcmd.
2. Run `login anonymous`
3. Run `app_update 2334200 validate` - This will likely download just 70MB. If it downloads more then this, you shouldn't need to continue.

4. Run `download_depot 2334200 2334201 6275183211335651031`. This is a ~1.2GB download.
    - 2334200 - This is the app ID of the linux dedi server.
    - 2334201 - This is the "SteamDB Unknown Depot" depot ID. This is what was recently updated ~9 hours ago.
    - 6275183211335651031 - This is the manifest ID from the depot.

3. After the depot has been downloaded, you'll see an output like `Depot download complete: "<download path here>" (279 files, manifest 6275183211335651031)`. Copy the 2 folders (Engine & ProjectWar) from this download path to where you installed your server (this is either where you pointed `force_install_dir` or `steamapps/common/LinuxServer` by default.)

4. Create a `start.sh` script. Just grab any of the contents from in this channel for the `start.bat` files and replace
```@echo off
start "TheFront" "..\WindowsServer\ProjectWar\Binaries\Win64\TheFrontServer.exe"```

with
```
./ProjectWar/Binaries/Linux/TheFrontServer```
Note: I placed my start.sh script in the folder alongside the Engine & ProjectWar directories so the path to TheFrontServer is relative to this.

Everything else including ports, command arguments, etc. should be the same as with the windows version.

**Comment by gOOvER** [comment]
> Someone posted a guide on Discord on how to run this game on Linux. Below is his message:
> 
> > I got a server running on linux for those interested. It looks like there is something going on with the steam download servers  and in most instances `app_update` downloads an older version.
> 
> > 1. Open steamcmd.
> > 2. Run `login anonymous`
> > 3. Run `app_update 2334200 validate` - This will likely download just 70MB. If it downloads more then this, you shouldn't  need to continue.
> 
> > 4. Run `download_depot 2334200 2334201 6275183211335651031`. This is a ~1.2GB download.
> >    - 2334200 - This is the app ID of the linux dedi server.
> >    - 2334201 - This is the "SteamDB Unknown Depot" depot ID. This is what was recently updated ~9 hours ago.
> >    - 6275183211335651031 - This is the manifest ID from the depot.
> 
> > 3. After the depot has been downloaded, you'll see an output like `Depot download complete: "<download path here>" (279 files, manifest 6275183211335651031)`. Copy the 2 folders (Engine & ProjectWar) from this download path to where you installed your server (this is either where you pointed `force_install_dir` or `steamapps/common/LinuxServer` by default.)
> 
> > 4. Create a `start.sh` script. Just grab any of the contents from in this channel for the `start.bat` files and replace
> >    `@echo off start "TheFront" "..\WindowsServer\ProjectWar\Binaries\Win64\TheFrontServer.exe"`
> 
> > with `./ProjectWar/Binaries/Linux/TheFrontServer`
> 
> > Note: I placed my start.sh script in the folder alongside the Engine & ProjectWar directories so the path to TheFrontServer is relative to this.
> 
> > Everything else including ports, command arguments, etc. should be the same as with the windows version.

i cant run 2 depots in 1 installation and copy all the times some files ;) Pls aware that we are on ptero and on docker

**Comment by gOOvER** [comment]
btw; the Linux server is not official released yet

**Comment by AhrimFakhriy** [comment]
How about the second message? Seems like he's installing only one depot.

>btw; the Linux server is not official released yet
Ah I see, well at least this is considered as progress, yes? :D

**Comment by SirOMGitsYOU** [comment]
> How about the second message? Seems like he's installing only one depot.
> 
> > btw; the Linux server is not official released yet
> > Ah I see, well at least this is considered as progress, yes? :D

Hey, That's me! I'm the second message :) Yeah while they were all figuring it out in discord I decided to try out just installing the Linux Dedicated Server from the App on steam, Moved the files to my linux server (although you can probably do all this through steamcmd but it was requiring account purchase login) - 

Copied the same configuration launch parameters 

`chmod +x "./ProjectWar/Binaries/Linux/TheFrontServer".
`
Create a start.sh 

`./ProjectWar/Binaries/Linux/TheFrontServer ProjectWar ProjectWar_Start ?Listen?MaxPlayers=8 -server -game -QueueThreshold=8 -ServerName="[SERVER NAME HERE]" -log log=log.log -locallogtimes -EnableParallelCharacterMovementTickFunction -EnableParallelCharacterTickFunction -UseDynamicPhysicsScene -OutIPAddress=[SERVER IP HERE] -ServerID=ANY_IDEA -port=15636 -BeaconPort=PORT+1 -QueryPort=PORT+2 -Game.PhysicsVehicle=false -ansimalloc -Game.MaxFrameRate=35 -ShutDownServicePort=PORT+3`

Ran this and boom hey-presto it worked and I loaded in to the dedicated server no issues at all

**Comment by gOOvER** [comment]
bash scripts are not allowed here

**Comment by ValhallaCommunityOfficial** [comment]
The Front Linux Dedicated Server depot updated 6 hours ago. Would love to see this egg made soon :)
https://steamdb.info/app/2334200/

**Comment by KalviPL** [comment]
Also looking forward to this egg

**Comment by dagbs** [comment]
[egg-the-front.json](https://github.com/parkervcp/eggs/files/12908121/egg-the-front.json)
server runs but you have to declare a manifest of the version you want to download... as this is the only workaround

**Comment by HerrSammyDE** [comment]
Can this egg be accepted into the repo like this? @QuintenQVD0 @gOOvER?

**Comment by gOOvER** [comment]
- DepotID not needed, because it never change
- Autoupdate will not work and not really usefull with the sate of the server atm
- startup have a little typo and it looks like, its not the last startupcmd
- maxplayers is a other flag
- wrong image
-

**Comment by dagbs** [comment]
> * DepotID not needed, because it never change
> * Autoupdate will not work and not really usefull with the state of the server atm

fair enough, I can clean it up

> * startup have a little typo and it looks like, its not the last startupcmd

afaik there is no typo? and I can move the `{{ARGS}}` to the end if that's the issue

> * maxplayers is a other flag

didn't think having the queue and max players being the same would be an issue.
if you'd like, I could set proper variables for it?

> * wrong image

i just used the latest docker image from ark, is there a better one to use?

> * mods are not really out yet and there are no infos about that, so the smylink is not needed

true, i'll toss it out for now

> * you are using an old steam install script

I just used the latest Ark: Survival Evolved install script. I didn't know there was an official "latest version"

**Comment by ValhallaCommunityOfficial** [comment]
Thank you for the egg! However, I'm getting "The [SERVER] PvE variable field must be true or false." No matter what I put in the box.
I want to turn PVE on so ive tried "true" "on" "PvE"
