### ISSUE TITLE
[Bug]: Rust

### ISSUE THREAD

**Issue by F9Alejandro** [parkervcp/eggs#2505]
### Panel Version

1.11.4

### Wings Version

1.11.8

### Service

Rust

### Modified

No, I did not modify the egg

### Expected Behavior

Server will bind to ip address of the node it is under with ports that are assigned to it.

### Actual Behavior

Server is inaccessible on steam and is not properly binding to the ip address of the node it is under.
```
WebSocket RCon Started on 28016

Generating procedural map of size 3000 with seed 3768

Connected to RCON. Please wait until the server status switches to "Running".
hostname: Vibecheck
version : 2508 secure (secure mode enabled, connected to Steam3)
map     : Procedural Map
players : 0 (38 max) (0 queued) (0 joining)

id name ping connected addr owner violation kicks 

Spawning 40184 entities
Starting to load entities into GlobalNetworkHandler...
Took 7ms to load entities into GlobalNetworkHandler
        done.
Enforcing SpawnPopulation Limits
        done.
Initializing 41087 entity links
        done.
Initializing 402 stability supports
        done.
Initializing 40193 entity save caches
        done.
Gamemode Convar :
No Gamemode.
SteamServer Initialized
Server startup complete
SteamServer Connected
Saved 40,613 ents, cache(0.09), write(0.02), disk(0.02).
Saving complete
Rust+ companion server connectivity test failed! Disabling Rust+ features.

Could not establish a TCP connection to 172.96.167.186:28082
Checking for new Steam Item Definitions..
```

### Steps To Reproduce

Step 1: Install
Step 2: Configure a new server
Step 3: Start server and see the issue with the ip not matching the node it is connected to in the log.

### Install logs

https://pteropaste.com/h2e25xcw31b6

**Comment by danny6167** [comment]
Enable the "Force Outgoing IP" option in the eggs setting.

**Comment by F9Alejandro** [comment]
> Enable the "Force Outgoing IP" option in the eggs setting.

I will be very surprised if this is the fix. Also dumbfounded.

**Comment by danny6167** [comment]
I don't have access to steam right now, but your server sure is responding to steam query now.
![image](https://github.com/parkervcp/eggs/assets/388231/2426c18b-c085-49f9-b869-b5ffa05ea84c)

**Comment by F9Alejandro** [comment]
![CleanShot 2023-10-12 at 06 21 28@2x](https://github.com/parkervcp/eggs/assets/1888010/6ab2141d-5970-4520-86be-e18a777059d1)

**Comment by QuintenQVD0** [comment]
I just ran mine with 4 ports (private home hosted) and let a friend of mine join and works fine. this is not an egg bug but sounds more like a configuration problem. If you still have issues please come to the discord for that.
