### ISSUE TITLE
[Bug]: FiveM (command execution and server stop issue)

### ISSUE THREAD

**Issue by moreaiok** [parkervcp/eggs#2509]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

Commands can be executed normally in the console and the server can be stopped normally.

### Actual Behavior

Commands cannot be executed in the console, and the server can only be stopped if it is force killed.

*This problem appeared when FiveM forced us to update the artifact version to `6683`, it was not present in version `5848`.

### Steps To Reproduce

Step 1: Download the FiveM egg
Step 2: Create a server with this egg
Step 3: Try to start the server and then stop it or try to execute any command in the console (neither of these actions will work).

### Install logs

https://pteropaste.com/usyk2rzfg1xn/

**Comment by parkervcp** [comment]
This is an issue with fivem and not a pterodactyl issue. I have been talking to their team already.
