### ISSUE TITLE
Project Zomboid Egg Request

### ISSUE THREAD

**Issue by rocky123xo** [parkervcp/eggs#252]
Service: Project Zomboid

Does this expand an already existing service: N

Link to game: https://store.steampowered.com/app/108600/Project_Zomboid/

Links for server downloads: https://www.reddit.com/r/projectzomboid/comments/abr530/basic_dedicated_server_setup_guide_jan_2019/

Links for install steps/docs: https://www.reddit.com/r/projectzomboid/comments/abr530/basic_dedicated_server_setup_guide_jan_2019/

**Comment by kevinsnijder** [comment]
I can help you out tommorow if you can test the egg for me, I don't own that game.
Hit me up on discord @Kevin_#9475

**Comment by Jeroen52** [comment]
Hello @kevinsnijder, I tried to contact you via Discord however I can't message your handle.

I can help you with testing the egg.

**Comment by brettrbarker** [comment]
Hello. Did anyone ever try to make an egg for Project Zomboid. I'm interested. I've never made one, but I can try to figure it out or test if someone else knows how.

**Comment by iamkubi** [comment]
I have one, although I haven't added any configuration options yet, just got it to the point that a server booted and I was able to join.

https://github.com/iamkubi/eggs/tree/master/project_zomboid

If you want to try it feel free to leave feedback on a Github issue or on Discord.  Once I get around to adding variables I'll try to get it added.

**Comment by brettrbarker** [comment]
All good. I'm the one that hit you up on Discord and got it working with that "?" question mark folder. I got it running but haven't really played much until they get multiplayer on the new PZ update.
