### ISSUE TITLE
[Bug]: Project Zomboid - Czech letters in server description not working

### ISSUE THREAD

**Issue by GameAreaCZ** [parkervcp/eggs#2522]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Project Zomboid

### Modified

No, I did not modify the egg

### Expected Behavior

To have a Czech letters like ě š č ř ž ý in server description.

### Actual Behavior

When I put a Czech word "přátelský" in server descrition it changes to "p????telsk??" after server start and I saw some of other Czech servers that they are using this kind of characters just fine.

### Steps To Reproduce

Step 1: Install PZ server.
Step 2: Set description or MOTD with special characters like š č ř ž ý á  í é.
Step 3: Start the server.
Step 4: Check the configuration or description in server browser/game.

### Install logs

https://pteropaste.com/1vp19u5pmux8

**Comment by GameAreaCZ** [comment]
Maybe is it because of the Dockerfile need to contain a language change or something like that?

**Comment by gOOvER** [comment]
> Maybe is it because of the Dockerfile needs to contain a language change or something like that?

yes, your language must be installed. english dont know your chars

**Comment by QuintenQVD0** [comment]
We wont install like 10 langs in it. Takes way to mutch space

**Comment by gOOvER** [comment]
@GameAreaCZ contact mew on discord; we create an own image for you.

**Comment by gOOvER** [comment]
can be closed, because not an egg issue

**Comment by GameAreaCZ** [comment]
Understand. Ty.
