### ISSUE TITLE
[Egg Request]: Stationeers with BepInEx support

### ISSUE THREAD

**Issue by Sakata-MC** [parkervcp/eggs#2527]
### Does this expand an already existing service

Yes

### Link to a game or software

https://steamdb.info/app/600760/info/

### Links for the download

https://github.com/BepInEx/BepInEx/releases

### Links for the install docs

https://docs.bepinex.dev/articles/user_guide/installation/index.html and possibly https://github.com/jixxed/StationeersMods

**Comment by vp-en** [comment]
Try and see if this works: https://github.com/parkervcp/eggs/issues/2527

I don't own the game, so I have no idea if the server is actually connectable.

**Comment by Sakata-MC** [comment]
Thank you for the response. I'm going to spin up the egg shortly and let you know how it goes.

**Comment by Sakata-MC** [comment]
It looks like overall it is working fine. Not sure if the redirection is required, it does cause all server logs to be dumped into BepInEx's logfile.

**Comment by Sakata-MC** [comment]
Also not sure if this is something addressable, does this in normal egg as well -- commands entered on the console lag behind by one command. So if I run "say Hi!" then run "say Bye" they will see "Hi" but only after entering another command will they see "Bye".

**Comment by vp-en** [comment]
> It looks like overall it is working fine. Not sure if the redirection is required, it does cause all server logs to be dumped into BepInEx's logfile.

Honestly not how sure how to fix that. I'm not sure by redirection if you mean the `2>&1` part, but removing it still outputs everything to the `BepInEx.log` 

> Also not sure if this is something addressable, does this in normal egg as well -- commands entered on the console lag behind by one command. So if I run "say Hi!" then run "say Bye" they will see "Hi" but only after entering another command will they see "Bye".

Not sure this is an egg issue. I at least don't know how to fix that

**Comment by Sakata-MC** [comment]
All good. Overall, the plugin is working as expected, mods will load and run, and the test server has been up for a while now. Considering the weirdness of the console in general for this server, it is probably a good thing that the logs are at least going somewhere, so I'll call that a net positive.
99% of the error messages are in the vanilla server, as the server for some idiotic reason still has the graphical code running which causes the log spam.
I think it's "production worthy", though you may wish to put in the description that it does cause console spam to be put into bepinex's log file. After installing we've been beating it up as hard as we can and it has run as well as the vanilla server.

**Comment by gOOvER** [comment]
Stationeers hove not a real console, because the devs a re to stupid, to make them work: Their excuse for this is that users are using the wrong hardware.

And the devs are not really intressted in fixing their shit. They do not really know, how to buold a server
