### ISSUE TITLE
SA-MP egg (GTA) has vulnerabilities + needs libtbb2

### ISSUE THREAD

**Issue by dennorske** [parkervcp/eggs#253]
NB: I am not following the format as the information that will be provided is not related to my issue.

The egg for SA-MP pulls a docker image that is 9 months (?) outdated. 
Could you update the packages on it and as well include libtbb2 library as:
```Loading plugin: RouteConnectorPlugin.so
[13:14:56]   Failed (libtbb.so.2: cannot open shared object file: No such file or directory)
```

![image](https://user-images.githubusercontent.com/3287543/61590885-32268800-abbf-11e9-8ead-7eb823372308.png)

Thank you!

**Comment by parkervcp** [comment]
@dennorske I have updated the image on the repo. I am working on deprecating older images while I move to the new image repo layout. Please update your image from `quay.io/parkervcp/pterodactyl-images:samp `to `quay.io/parkervcp/pterodactyl-images:game_samp`

**Comment by simeneriks1** [comment]
Thank you for the prompt action!
I have studied docker this evening and was able to build my own version of it using your repo :)

I would try to contribute in the future where I see possible, if you accept contributions from others

**Comment by dennorske** [comment]
Thank you for the fast response and action. I was able to learn enough docker to build my own image in the end, great that you followed up this.

If you accept contributions I'd love to help out with the sa-mp image, I found the repo containing the dockerfile - assuming you have automatic builds i could add pull requests whenever something needs an update etc..
Again, thank you!
den

**Comment by parkervcp** [comment]
I do accept PR's but I would like you to use the game/samp branch.

I will be working on deprecating the old samp branch.

**Comment by parkervcp** [comment]
Also, is this working now?

**Comment by dennorske** [comment]
Ah unfortunately samp doesn't support the 64 bit arch, so I had to do the following (add the i386 libs) 

```
RUN         dpkg --add-architecture i386 \
            && apt update \
            && apt upgrade -y \
            && apt install -y libstdc++6 lib32stdc++6 tar curl iproute2 openssl \
            && apt install -y libtbb2:i386 libtbb-dev:i386 \
            && useradd -d /home/container -m container

```

**Comment by parkervcp** [comment]
@dennorske I have pushed changes on the `game_samp` egg to use the 32 bit lib

**Comment by dennorske** [comment]
Works now, thank you!
:)
