### ISSUE TITLE
[Egg Request]: Microsoft SQL Server - Docker Container

### ISSUE THREAD

**Issue by OkkoGael** [parkervcp/eggs#2530]
### Does this expand an already existing service

No

### Link to a game or software

https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash

### Links for the download

https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash

### Links for the install docs

https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> No
> 
> ### Link to a game or software
> https://learn.microsoft.com/es-es/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash
> 
> ### Links for the download
> https://learn.microsoft.com/es-es/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash
> 
> ### Links for the install docs
> https://learn.microsoft.com/es-es/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash

Please provide english links!

**Comment by OkkoGael** [comment]
> > ### Does this expand an already existing service
> > No
> > ### Link to a game or software
> > https://learn.microsoft.com/es-es/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash
> > ### Links for the download
> > https://learn.microsoft.com/es-es/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash
> > ### Links for the install docs
> > https://learn.microsoft.com/es-es/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash
> 
> Please provide english links!

Done, sorry.

**Comment by QuintenQVD0** [comment]
Duplicate #1673
