### ISSUE TITLE
[Bug] Modrinth: Overrides permissions default to `0`

### ISSUE THREAD

**Issue by bleuthoot-sven** [parkervcp/eggs#2531]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

wings/pterodactyl (both run in a docker container)

### Modified

No, I did not modify the egg

### Expected Behavior

When installing a modpack, the permissions of an override should be at least `read`.

### Actual Behavior

When installing a modpack that includes overrides (like config files or mod jars), the overrides should not default to permission `0` (no access). This will cause issues if you have custom default configuration files or mods jars that are included in the `.mrpack` file.

### Steps To Reproduce

1. Create a new server with the Modrinth egg.
2. Choose a modpack that includes overrides (for example: Cobblemon [Fabric] `5FFgwNNP`)
3. Install the server
4. Check the permissions of the override files (for example: `mods/slimyfloor-1.20-1.2.8.jar` or anything in `config/`)
5. The file permission should be `0`.
6. The server will fail to start due to lacking permissions to read or write to the override files

### Install logs

*Unable to access logs due to being unable to access wings container using `/bin/sh` or `/bin/bash`*

**Comment by dhkatz** [comment]
I will take a look at this on the weekend. Should be able to fix it. Thank you for the report

**Comment by dilllxd** [comment]
Can confirm this bug, not sure the _correct_ way of setting permissions in eggs or what should be set to what permission, but setting the whole override folder to 755 before it gets copied fixes the permission denied/no access.

**Comment by ImKringle** [comment]
> Can confirm this bug, not sure the _correct_ way of setting permissions in eggs or what should be set to what permission, but setting the whole override folder to 755 before it gets copied fixes the permission denied/no access.

Mind giving this a go? Should fix it
[egg-modrinth-generic (1).json](https://github.com/parkervcp/eggs/files/13771798/egg-modrinth-generic.1.json)
Assuming it does I'll get a PR set for it

**Comment by ImKringle** [comment]
> Can confirm this bug, not sure the _correct_ way of setting permissions in eggs or what should be set to what permission, but setting the whole override folder to 755 before it gets copied fixes the permission denied/no access.

Did literally this, the correct way is that *or* we change 755 to rwxr-xr-x ; either way it'll fix it haha
