### ISSUE TITLE
[Bug]: ARK: Survival Ascended (Port not reachable)

### ISSUE THREAD

**Issue by mrpf-me** [parkervcp/eggs#2537]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

port connection

### Modified

No, I did not modify the egg

### Expected Behavior

Install Egg on a server
Starting the server
Wait for 5-10min
Server available to add to Steam game server list

### Actual Behavior

Server crashed first without console message despite 10GB ram.
It needs more than 10GB ram, at least 12 should be recommended.

Server is displayed as online in the console.
RCON port is reachable.
Auto backups run every 15min

However **port 7777 are not reachable**, just like:
- 7778
- 27015

OVH Gamefirewall is disabled.

Discussion on Discord: https://discord.com/channels/122900397965705216/1169439402326507540

### Steps To Reproduce

- Downloaded latest ASA Egg
- Install as server
- Start installed server

### Install logs

https://pteropaste.com/318nf6yci715/

**Comment by parkervcp** [comment]
I assume that similar to ARK:SE you need at least 3 ports. You also need to have 7777 as your default and the variables for the others set. The game and query ports are TCP.

Game | 7777
Raw UDP | 7778
Query | 27015
