### ISSUE TITLE
[Egg Request]: Directus

### ISSUE THREAD

**Issue by scharez** [parkervcp/eggs#2538]
### Does this expand an already existing service

No

### Link to a game or software

https://directus.io/

### Links for the download

https://docs.directus.io/self-hosted/quickstart.html

### Links for the install docs

https://docs.directus.io/self-hosted/quickstart.html#create-a-docker-compose-file

**Comment by gOOvER** [comment]
not really possible, because you need 3 or more images and running postgre in an egg for ptero is a pain.

Ptero is the wrong solution for this kind of software

**Comment by scharez** [comment]
No, only one service is required. See https://docs.directus.io/self-hosted/quickstart.html#create-a-docker-compose-file
If no db is defined, directus will be automatically using sql lite.

**Comment by gOOvER** [comment]
> No, only one service is required. See https://docs.directus.io/self-hosted/quickstart.html#create-a-docker-compose-file If no db is defined, directus will be automatically using sql lite.

Ptero cant run docker-compose files. and there is only a dockerfile, which is not made for ptero. Agaion. Ptero is the wrong solution for this

**Comment by QuintenQVD0** [comment]
This is way too complex to run in pterodactyl, and as goover mentioned, we can not run docker compose files and no game / application files can be in a docker image.

**Comment by scharez** [comment]
You can install directus with only npm too. There is no need of using docker? That would be possible?

**Comment by scharez** [comment]
> You can install directus with only npm too. There is no need of using docker? That would be possible?

https://docs.directus.io/self-hosted/cli.html

**Comment by gOOvER** [comment]
> > You can install directus with only npm too. There is no need of using docker? That would be possible?
> 
> https://docs.directus.io/self-hosted/cli.html

thats not for installing it; that for creating a project. You have to run the App in docker before

**Comment by scharez** [comment]
> > > You can install directus with only npm too. There is no need of using docker? That would be possible?
> > 
> > 
> > https://docs.directus.io/self-hosted/cli.html
> 
> thats not for installing it; that for creating a project. You have to run the App in docker before

No you do not have to run the app in docker before. You only have to initialize directus and then run ```npx directus start```.
I have already done this for work.

**Comment by gOOvER** [comment]
> > > > You can install directus with only npm too. There is no need of using docker? That would be possible?
> > > 
> > > 
> > > https://docs.directus.io/self-hosted/cli.html
> > 
> > 
> > thats not for installing it; that for creating a project. You have to run the App in docker before
> 
> No you do not have to run the app in docker before. You only have to initialize directus and then run `npx directus start`. I have already done this for work.

then feel free to create an egg for it
