### ISSUE TITLE
[Bug]: SATISFACTORY

### ISSUE THREAD

**Issue by lewanpe** [parkervcp/eggs#2539]
### Panel Version

1.11.3

### Wings Version

1.11.8

### Service

satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Connect work

### Actual Behavior

Time out 
[2023.11.03-13.43.05:302][984]LogNet: Error: UEngine::BroadcastNetworkFailure: FailureType = ConnectionTimeout, ErrorString = UNetConnection::Tick: Connection TIMED OUT. Closing connection.. Elapsed: 30.03, Real: 30.03, Good: 30.03, DriverTime: 32.93, Threshold: 30.00, [UNetConnection] RemoteAddr: 82.66.XX.XX:50364, Name: IpConnection_2147482284, Driver: IpNetDriver_2147482295 IpNetDriver_2147482295, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID, Driver = IpNetDriver_2147482295 IpNetDriver_2147482295
[2023.11.03-13.43.05:302][984]LogGame: Error: Network Error Recived: Type: ConnectionTimeout, MSG: UNetConnection::Tick: Connection TIMED OUT. Closing connection.. Elapsed: 30.03, Real: 30.03, Good: 30.03, DriverTime: 32.93, Threshold: 30.00, [UNetConnection] RemoteAddr: 82.66.XX.XX:50364, Name: IpConnection_2147482284, Driver: IpNetDriver_2147482295 IpNetDriver_2147482295, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID

### Steps To Reproduce

If you can try connec to 45.11.185.206:15778

### Install logs

https://pteropaste.com/1oswdzihvidt/

**Comment by gOOvER** [comment]
Pls post the allocated ports.. Thats looks like, you assign the ports wrong

**Comment by lewanpe** [comment]
> Pls post the allocated ports.. Thats looks like, you assign the ports wrong

I've assigned wrong and the 7777 15777 15000 both do the same timeout

**Comment by gOOvER** [comment]
> > Pls post the allocated ports.. Thats looks like, you assign the ports wrong
> 
> I've assigned wrong and the 7777 15777 15000 both do the same timeout

as i said. Post screens of your used ports and from variables

**Comment by lewanpe** [comment]
![image](https://github.com/parkervcp/eggs/assets/36868377/494e9ad5-8c52-4371-849a-c7e253f44fff)

**Comment by lewanpe** [comment]
> you must connect with 15777

that what i actually do 
![image](https://github.com/parkervcp/eggs/assets/36868377/9ee0b8b8-0b05-44ac-9543-ce6443a6655c)

**Comment by lewanpe** [comment]
the things is i can see well on firewall the packet is accepted an go to the server but the server do shit idk what.. ( working on experimental branch )

**Comment by gOOvER** [comment]
btw: in you install log

> the things is i can see well on firewall the packet is accepted an go to the server but the server do shit idk what.. ( working on experimental branch )

egg is not updated for exp branch yet, so far as i know

**Comment by lewanpe** [comment]
i've got the same error while connecting directly internaly :(

**Comment by lewanpe** [comment]
The server can tell me if i'm with the good or bad version but nothing more on network

**Comment by SamHarding23** [comment]
Are you running this behind any sort of firewall?

**Comment by delphyinium** [comment]
This is a given, but do you have any mods, such as SMM or anything similar?

**Comment by QuintenQVD0** [comment]
You are using an oudated egg as your startup does not match this one: https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/satisfactory/egg-satisfactory.json#L18

**Comment by lewanpe** [comment]
No it's not outdated you just doesnt read i've the latest

**Comment by lewanpe** [comment]
> This is a given, but do you have any mods, such as SMM or anything similar?

No mods completely clear

**Comment by lewanpe** [comment]
> Are you running this behind any sort of firewall?

Behind DATAPACKET but doesnt matter

**Comment by gOOvER** [comment]
you must connect with 15777.

you have all ports allocated and assigned correct?

7777 gameport
15777 Queryport
15000 idk 🗡️

**Comment by lewanpe** [comment]
> you must connect with 15777.
> 
> you have all ports allocated and assigned correct?
> 
> 7777 gameport 15777 Queryport 15000 idk 🗡️

yes the problem is actually not found becaus everything well configured

**Comment by lewanpe** [comment]
i've tryed allocation : 
15877
15800
7877 and doesnt work too

**Comment by lewanpe** [comment]
just found ! Satisfactory need a crypted network ! to have good work

**Comment by QuintenQVD0** [comment]
Please do not use closed issues to discuss an other problem, come to the discord for that, not an egg issue
