### ISSUE TITLE
[Bug]: Project Zomboid Egg

### ISSUE THREAD

**Issue by Apprisco** [parkervcp/eggs#2541]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

projectzomboid

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server with the new egg, start server

### Actual Behavior

Even with multiple reinstalls, I get a tcp 400 error. I noticed that once the install failed due to memory? unsure why, but I reinstalled and all files showed up as expected.
![image](https://github.com/parkervcp/eggs/assets/34324909/b4ad773d-f6da-41e3-b277-fe6a457c3494)
![image](https://github.com/parkervcp/eggs/assets/34324909/0b70dc4c-908e-416d-9e53-e453f25e32b2)
Yet zomboid refuses to launch with above.

### Steps To Reproduce

Fresh install of ptero.
Import latest parkervcp projectzomboid egg.
create new server.
Observe error.

### Install logs

https://pteropaste.com/jl4drfiy85nb/

**Comment by gOOvER** [comment]
Not an Egg issue. use Pterodactyl discord for Support

**Comment by Apprisco** [comment]
Pretty sure it's an egg issue as it's not working as intended at all.

**Comment by Apprisco** [comment]
https://ptero.co/sexodewyha

**Comment by QuintenQVD0** [comment]
This is not an issue with the egg but with. But with your server.  Please use the discord for this.
