### ISSUE TITLE
[Egg Request]: Needle (Discord Threads)

### ISSUE THREAD

**Issue by PoweredByZero** [parkervcp/eggs#2545]
### Does this expand an already existing service

No

### Link to a game or software

https://needle.gg/

### Links for the download

https://github.com/MarcusOtter/discord-needle/

### Links for the install docs

https://github.com/MarcusOtter/discord-needle/#%EF%B8%8F-self-hosting-advanced

**Comment by PsychoZander** [comment]
Looks like a fairly standard npm based discord bot. Should probably be able to manage this with the nodejs generic egg with a bit of tweaking. https://github.com/parkervcp/eggs/blob/master/generic/nodejs/egg-node-js-generic.json

**Comment by QuintenQVD0** [comment]
With litte to no midification the nodejs generic egg will run this.
