### ISSUE TITLE
[Egg Request]: Discord Music Bot

### ISSUE THREAD

**Issue by UnicornYames** [parkervcp/eggs#2548]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/wtfnotavailable/Discord-MusicBot

### Links for the download

https://github.com/wtfnotavailable/Discord-MusicBot/releases

### Links for the install docs

https://github.com/wtfnotavailable/Discord-MusicBot/blob/master/djs-bot/README.md

**Comment by QuintenQVD0** [comment]
The generic nodejs egg can with litte to no modification. The lavalink will need to be a seperate egg /server
