### ISSUE TITLE
don't auto-validate 7dtd on start

### ISSUE THREAD

**Issue by Prisma501** [parkervcp/eggs#255]
the validation on server start will undo any modded dll file installation. 
Also unconfirmed updates would happen.

**Comment by niekcandaele** [comment]
For completeness sake I wanted to add that if an unconfirmed update would happen in 7 days to die, it could break world save data. Ideally, the user should be able to indicate if an update should happen or not so that they can properly prepare for it.

**Comment by parkervcp** [comment]
@Prisma501 Can you check my PR here? I believe it should be almost identical to what you have now.

**Comment by Prisma501** [comment]
Its exellent mate. This is gonna help a LOT with maintaining versions
