### ISSUE TITLE
[Egg Request]: Hell Let Loose RCon Tool

### ISSUE THREAD

**Issue by empmdk** [parkervcp/eggs#2554]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/MarechJ/hll_rcon_tool

### Links for the download

https://github.com/MarechJ/hll_rcon_tool/releases

### Links for the install docs

https://github.com/MarechJ/hll_rcon_tool/wiki

**Comment by QuintenQVD0** [comment]
The generic python egg should be able to run this just fine with litte to no modifications
