### ISSUE TITLE
[Bug]: openmp MySQL client library missing

### ISSUE THREAD

**Issue by VibeGAMESNL** [parkervcp/eggs#2557]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

openmp

### Modified

No, I did not modify the egg

### Expected Behavior

Some plugins need MySQL client library being installed to work. Currently the openmp egg is using the samp game docker image which does not contains this package.

Error message:
> Failed (libmysqlclient_r.so.18: cannot open shared object file: No such file or directory)

### Actual Behavior

Plugins that require MySQL client library should work fine.

### Steps To Reproduce

**Step 1**
Create an openmp server

**Step 2**
Install the Open.MP mysql plugin

**Step 3**
Start the server

### Install logs

https://pteropaste.com/p35po5y3h245

**Comment by QuintenQVD0** [comment]
Then for now there is no support for it then, the stock egg works. as there litterly 0 docs on what package this .so should come from.

**Comment by QuintenQVD0** [comment]
This plugin is over 6 years old and in any stable release of debian or ubuntu is that package not provided anymore. Complain to the author!

**Comment by QuintenQVD0** [comment]
You can try using the static build else there is notthing we can do.

**Comment by VibeGAMESNL** [comment]
> This plugin is over 6 years old and in any stable release of debian or ubuntu is that package not provided anymore. Complain to the author!

Well SAMP/open.mp is an old game and these kind of plugins are not getting updated anymore in most cases.

**Comment by QuintenQVD0** [comment]
> > @QuintenQVD0  This plugin is over 6 years old and in any stable release of debian or ubuntu is that package not provided anymore. Complain to the author!
> 
> Well SAMP/open.mp is an old game and these kind of plugins are not getting updated anymore in most cases. Might be a wierd question but what do you mean with the " static build "?

look in the github download of the mod, there is a static build.
