### ISSUE TITLE
[Bug]:  Ark Survival Ascended

### ISSUE THREAD

**Issue by buddyqc69** [parkervcp/eggs#2560]
### Panel Version

1.15.5

### Wings Version

1.11.8

### Service

after reboot server

### Modified

No, I did not modify the egg

### Expected Behavior

If I want to restart the Ark server, it does so, but it restores my default game files for the configurations, which shouldn't happen, because normally we have to make it restart the server with them once a day to help the ark server.

### Actual Behavior

It reboots but does not indicate that it is modifying the server configuration files, it just does so.

### Steps To Reproduce

-1 Create an ARK ASA server
-2 Modify ark server configurations
-3 Start server
-4 Restart server
-5 Check that configuration files have been modified

### Install logs

https://pteropaste.com/exampleLogs

**Comment by dagbs** [comment]
You say you start the server after making changes but the only time this issue happens is if you try to edit the files while the server is running.

Stop the server, make your changes, start the server.

A:SA takes ~3 minutes to fully top, so if it's still running... you will have issues.

**Comment by buddyqc69** [comment]
that's what I do too

Le 16 nov. 2023 à 6:28 p.m., Blood Shot ***@***.***> a écrit :

﻿

You say you start the server after making changes but the only time this issue happens is if you try to edit the files while the server is running.

Stop the server, make your changes, start the server.

A:SA takes ~3 minutes to fully top, so if it's still running... you will have issues.

**Comment by dagbs** [comment]
1) Make sure you are not using mods. We don't know what they can/can't effect directly with the servers.
2) Make sure the server _fully_ starts and _fully_ stops at least ONE time before you touch anything. It likes to generate files on first launch and may be overwriting anything that is set. This is not an egg issue.

**Comment by dagbs** [comment]
I would also like to add that there have been MANY revisions of the A:SA egg. Please make sure you are using the _latest_ egg and that all of your startup commands are updated for your server(s). I'm sure this is the case for _everyone_, but please double-check.

**Comment by Cobras-Hosting** [comment]
> ### Panel Version
> 1.15.5
> 
> ### Wings Version
> 1.11.8
> 
> ### Service
> after reboot server
> 
> ### Modified
> No, I did not modify the egg
> 
> ### Expected Behavior
> If I want to restart the Ark server, it does so, but it restores my default game files for the configurations, which shouldn't happen, because normally we have to make it restart the server with them once a day to help the ark server.
> 
> ### Actual Behavior
> It reboots but does not indicate that it is modifying the server configuration files, it just does so.
> 
> ### Steps To Reproduce
> -1 Create an ARK ASA server -2 Modify ark server configurations -3 Start server -4 Restart server -5 Check that configuration files have been modified
> 
> ### Install logs
> https://pteropaste.com/exampleLogs

how did you get your server to run on the pter

> ### Panel Version
> 1.15.5
> 
> ### Wings Version
> 1.11.8
> 
> ### Service
> after reboot server
> 
> ### Modified
> No, I did not modify the egg
> 
> ### Expected Behavior
> If I want to restart the Ark server, it does so, but it restores my default game files for the configurations, which shouldn't happen, because normally we have to make it restart the server with them once a day to help the ark server.
> 
> ### Actual Behavior
> It reboots but does not indicate that it is modifying the server configuration files, it just does so.
> 
> ### Steps To Reproduce
> -1 Create an ARK ASA server -2 Modify ark server configurations -3 Start server -4 Restart server -5 Check that configuration files have been modified
> 
> ### Install logs
> https://pteropaste.com/exampleLogs

how did you get your server to run on the Pterodactyl panel as i cant seem to connect to mine could do with some help if you dont mind

**Comment by QuintenQVD0** [comment]
> > ### Panel Version
> > 1.15.5
> > ### Wings Version
> > 1.11.8
> > ### Service
> > after reboot server
> > ### Modified
> > No, I did not modify the egg
> > ### Expected Behavior
> > If I want to restart the Ark server, it does so, but it restores my default game files for the configurations, which shouldn't happen, because normally we have to make it restart the server with them once a day to help the ark server.
> > ### Actual Behavior
> > It reboots but does not indicate that it is modifying the server configuration files, it just does so.
> > ### Steps To Reproduce
> > -1 Create an ARK ASA server -2 Modify ark server configurations -3 Start server -4 Restart server -5 Check that configuration files have been modified
> > ### Install logs
> > https://pteropaste.com/exampleLogs
> 
> how did you get your server to run on the pter
> 
> > ### Panel Version
> > 1.15.5
> > ### Wings Version
> > 1.11.8
> > ### Service
> > after reboot server
> > ### Modified
> > No, I did not modify the egg
> > ### Expected Behavior
> > If I want to restart the Ark server, it does so, but it restores my default game files for the configurations, which shouldn't happen, because normally we have to make it restart the server with them once a day to help the ark server.
> > ### Actual Behavior
> > It reboots but does not indicate that it is modifying the server configuration files, it just does so.
> > ### Steps To Reproduce
> > -1 Create an ARK ASA server -2 Modify ark server configurations -3 Start server -4 Restart server -5 Check that configuration files have been modified
> > ### Install logs
> > https://pteropaste.com/exampleLogs
> 
> how did you get your server to run on the Pterodactyl panel as i cant seem to connect to mine could do with some help if you dont mind

Not here. Read the readme. Allocate all needed ports. Else come to the discord. Not related to this issue.

**Comment by QuintenQVD0** [comment]
this is not a bug with the egg, if you still have this issue come to the discord server.
as mentioned, you can only edit the config files if the server is stoped
also note some vlaues are controled with variables
