### ISSUE TITLE
[Bug]: ARK Survival Ascended

### ISSUE THREAD

**Issue by DasEric** [parkervcp/eggs#2561]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

/game_eggs/steamcmd_servers/ark_survival_ascended

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, start it and play

### Actual Behavior

Server starts but this is spaming in console: 

waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:5560: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:5560: connect: connection refused

### Steps To Reproduce

- Install the server
- do nothing and let the server start
- i give them 2 extra ports
![pt1](https://github.com/parkervcp/eggs/assets/60920916/34148760-9146-49e0-b3ba-e73edd2e04ee)

### Install logs

https://pteropaste.com/ez9uns7ml2tn

**Comment by dagbs** [comment]
I know you closed this but if you made a post it might be important to explain what happened.

When you start the server it takes roughly 10-15 minutes to fully start up. I know this isn't mentioned in the README but it does mention how to determine if the server crashed which, in my opinion, is roughly the same thing.

https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/ark_survival_ascended/README.md#crash-identifiers
