### ISSUE TITLE
[Egg Request]: PostgreSQL 16

### ISSUE THREAD

**Issue by Apfelmoes** [parkervcp/eggs#2562]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.postgresql.org/

### Links for the download

https://www.postgresql.org/download/

### Links for the install docs

https://www.postgresql.org/docs/current/tutorial-install.html

**Comment by QuintenQVD0** [comment]
Does the current postgresql even work with the 14 image?

**Comment by WilliamDavidHarrison** [comment]
I have opened a PR for this #2602
