### ISSUE TITLE
[Install Bug]: forge/forge Install failed using Forge version 1.18.2-40.2.0 and Minecraft version .

### ISSUE THREAD

**Issue by RexGuard** [parkervcp/eggs#2563]
### Panel Version

 1.11.5

### Wings Version

1.11.8

### Service

minecraft/java/forge/forge

### Modified

No, I did not modify the egg

### Expected Behavior

successfully installed forge 1.18.2

### Actual Behavior

failed and got error 

Install failed using Forge version 1.18.2-40.2.0 and Minecraft version .
Should you be using unlimited memory value of 0, make sure to increase the default install resource limits in the Wings config or specify exact allocated memory in the server Build Configuration instead of 0! 
Otherwise, the Forge installer will not have enough memory.

I checked the memory value and its not 0 rechecked everything else, it worked before too

### Steps To Reproduce

Step 1 : Create a server
step 2 : use forge egg
Step 3 : Let the Installer runs
Step 4 : Install stopped because of error

### Install logs

https://pteropaste.com/cdawva34aywr

**Comment by GinoX27** [comment]
Actually this needs some investigation as I can reproduce this same error when trying to install forge 1.20.1
