### ISSUE TITLE
[Bug]: database/PostgreSQL

### ISSUE THREAD

**Issue by FunixG** [parkervcp/eggs#2566]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

database/postgresql

### Modified

No, I did not modify the egg

### Expected Behavior

I start the server database
I stop the server database with the stop button
The database shut down properly and safely

### Actual Behavior

I start the server
I want to stop the server properly but I always need to kill the instance to shut it down, I want to stop the database properly but I cant

### Steps To Reproduce

- Install the egg
- Create a server with the database postgres
- Start it
- Stop it

### Install logs

no logs needed

**Comment by QuintenQVD0** [comment]
@FunixG Please try the image `quintenqvd/pterodactyl_tini:postgres_14`

**Comment by FunixG** [comment]
> @FunixG Please try the image `quintenqvd/pterodactyl_tini:postgres_14`

It won't break my actual databses ?

When I start the container I have an error :

[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Error Event [fe6f82b6-4851-4da1-8a6e-8e985024cc40]: environment/docker: failed to run pre-boot process: environment/docker: failed to pull "quintenqvd/pterodactyl_tini:postgres_14" image for server: Error response from daemon: manifest for quintenqvd/pterodactyl_tini:postgres_14 not found: manifest unknown: manifest unknown

**Comment by QuintenQVD0** [comment]
> > @FunixG Please try the image `quintenqvd/pterodactyl_tini:postgres_14`
> 
> It won't break my actual databses ?
> 
> When I start the container I have an error :
> 
> [Pterodactyl Daemon]: Finished pulling Docker container image container@pterodactyl~ Error Event [fe6f82b6-4851-4da1-8a6e-8e985024cc40]: environment/docker: failed to run pre-boot process: environment/docker: failed to pull "quintenqvd/pterodactyl_tini:postgres_14" image for server: Error response from daemon: manifest for quintenqvd/pterodactyl_tini:postgres_14 not found: manifest unknown: manifest unknown

No it will not and the build went wrong, please try again in 5 minutes

**Comment by FunixG** [comment]
I am going to wait to have a production ready image to test 😄 actually

**Comment by QuintenQVD0** [comment]
Thisbwas fixt on the image side.
