### ISSUE TITLE
[Bug]: Satisfactory

### ISSUE THREAD

**Issue by tannertechnology** [parkervcp/eggs#2568]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

When clicking Create Game or attempting to load a save it should create the game or load the save. 

### Actual Behavior

The server appears to go offline and come back up without creating or loading a save. It is perfectly stable/working until you click Create Game or Load on any save. Here is the full log:

https://pteropaste.com/aaimrq8z730d/

### Steps To Reproduce

1) Import Satisfactory egg
2) Install server with default values (and add port 15001)
3) Launch, initialize server from client 
4) Either click create game or upload any save and click load. The client says server is preparing a game, and then connecting, and then you are not connected to this server. If you connect and do the same thing again the same result occurs. Pterodactyl doesn't recognize the server as crashing.  

### Install logs

https://pteropaste.com/6pmlsqvqpjid/

**Comment by lilkingjr1** [comment]
Not sure if it's related to your issue, but the game requires 3 ports to be configured and you only mentioned 2 (primary port and 15001). Make sure to follow the egg's README carefully for setup and then report back with the 3 ports you are using for each of the 3 services if you continue to have issues. Also, report what port you are connecting to with the client.

**Comment by parkervcp** [comment]
I have just validated that I can start and join my own server on the latest experimental release. I am certain that this is related to allocations.

**Comment by trianl2** [comment]
> I have just validated that I can start and join my own server on the latest experimental release. I am certain that this is related to allocations.

I agree too, I can join to mine too

**Comment by tannertechnology** [comment]
How embarrassing, you are correct. Added 7777 and made default, working a treat now. Thank you!

**Comment by parkervcp** [comment]
happens to the best of us.
