### ISSUE TITLE
[Egg Request]: DocsGPT

### ISSUE THREAD

**Issue by ArtyomCZ** [parkervcp/eggs#2569]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/arc53/DocsGPT

### Links for the download

https://github.com/arc53/DocsGPT

### Links for the install docs

https://docs.docsgpt.co.uk/Deploying/Hosting-the-app

**Comment by Loki-101** [comment]
Not compatible; this requires access to the system's GPU.
https://github.com/arc53/DocsGPT#our-open-source-models-optimized-for-docsgpt

**Comment by ArtyomCZ** [comment]
Hi, I asked on Discord and got an answer from one of the DocsGPT developers that it is not necessary to use GPU. DocsGPT can be used with OpenAI API.

So apparently it should be possible to use Pterodactyl to host DocsGPT with the OpenAI API. Or am I missing something?

<img width="581" alt="image" src="https://github.com/parkervcp/eggs/assets/16862369/c94c3705-dfd1-4fc5-89f0-8bfbb357cc92">

**Comment by Loki-101** [comment]
It looks like you're right; this can be done with OpenAI as the backend. An egg could be made for this.
With that being said, it would probably go on the backburner for a while if this is re-opened, as there is already a compose file for running it and this doesn't really have anything to do with game servers. It's one of those things that is a bit out of the way, but would probably be accepted if someone made an egg for it and sent in a pull request.

I'd recommend just running it with the compose file for now, unless you want to give the egg a shot.

**Comment by ArtyomCZ** [comment]
I agree, Pterodactyl is primarily geared towards game servers, but there are already eggs for software like uptimekuma etc. so I thought that shouldn't be a problem.

I would be grateful if someone with more experience with Docker and Pterodactyl would take on the creation of an egg, it would be fantastic. Unfortunately, my knowledge of Docker is lacking.

If anyone is up for the challenge, I would be grateful for their help 🙏

@parkervcp Will you please consider reopening the issue now that the compatibility issue seems to be resolved?

**Comment by parkervcp** [comment]
I'm leaving this closed as it needs multiple services all running at the same time.

You are better off just using compose outside the panel.

**Comment by gOOvER** [comment]
@ArtyomCZ contact me on discord: ```
@goover
```
