### ISSUE TITLE
[Install Bug]: NodeJS

### ISSUE THREAD

**Issue by hywar** [parkervcp/eggs#2570]
### Panel Version

1.11.3

### Wings Version

1.11.3

### Service

nodejs

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

the egg has its related files

### Actual Behavior

its not getting the index.js or related files

### Steps To Reproduce

Installed nodejs said it couldnt fine index.js

### Install logs

https://pteropaste.com/3xqu9f99vukg/

**Comment by QuintenQVD0** [comment]
the repo you have setup does not exists, so notthing was xloned so there is no index.js file in the file manger

**Comment by QuintenQVD0** [comment]
Just tested the egg and works just fine, you have misconfigured it likely so if you still want help please come to the discord for support. as you have not setup a git repo, let it install, upload all your files (.js files and package.json) hit reinstall and then try to use it
