### ISSUE TITLE
[Bug]: Multi Theft Auto database connection

### ISSUE THREAD

**Issue by dension0** [parkervcp/eggs#2585]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

game_eggs/gta/mtasa

### Modified

No, I did not modify the egg

### Expected Behavior

Databse connection establish

### Actual Behavior

Get Consol error: ERROR: Could not load /home/container/x64/dbconmy.so - libssl.so.1.1: cannot open shared object file: No such file or directory[18:43:58] WARNING: [motor]/sql_motor/mysql.lua:9: Bad usage @ 'dbConnect' [Could not connect]

### Steps To Reproduce

Install MTA
Create DB connection
Restart and read consol output

### Install logs

https://pteropaste.com/0czx9p773x6y

**Comment by QuintenQVD0** [comment]
use `ghcr.io/parkervcp/games:mta`

**Comment by QuintenQVD0** [comment]
I am closing this as your egg is out of date. So update the egg and of all already running servers change the image to the one included in the latest egg.

**Comment by dension0** [comment]
I downloaded this egg 3 minutes ago from here...

**Comment by QuintenQVD0** [comment]
> I downloaded this egg 3 minutes ago from here...

@dension0 
![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/51088d67-e934-4c3a-9af8-bcf5626f4a9f)

[HERE](https://github.com/parkervcp/eggs/blob/master/game_eggs/gta/mtasa/egg-multi-theft-auto.json) Is the latest egg

if you think you have the latest egg then post a coppy past from the moment you hit start to the error and put it here (but in a paste link)

**Comment by gOOvER** [comment]
Not needed; he dont have the latest egg ;)
