### ISSUE TITLE
[Bug]: MTA EGG ERROR

### ISSUE THREAD

**Issue by dension0** [parkervcp/eggs#2586]
### Panel Version

1.11.3

### Wings Version

1.11.8

### Service

game_eggs/gta/mtasa

### Modified

No, I did not modify the egg

### Expected Behavior

Established SQL connection.

### Actual Behavior

Get error:
`ERROR: Could not load /home/container/x64/dbconmy.so - libssl.so.1.1: cannot open shared object file: No such file or directory[18:43:58] WARNING: [motor]/sql_motor/mysql.lua:9: Bad usage @ 'dbConnect' [Could not connect]`

### Steps To Reproduce

Install MTA with this egg
Create SQL connection
Get error in consol.

### Install logs

https://pteropaste.com/0czx9p773x6y

**Comment by gOOvER** [comment]
https://github.com/parkervcp/eggs/issues/2585#issuecomment-1837230663

STOP open all the time tickets

**Comment by gOOvER** [comment]
Your egg is not up2date. MTA should be deleted ;/

**Comment by dension0** [comment]
Sorry you was too fast I can not see the answer. Sorry.

**Comment by QuintenQVD0** [comment]
![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/cb454bc1-841e-4405-b7d3-30a717593d79)

libssl1.1 is 100% in there
