### ISSUE TITLE
[Bug]: Avorion - Server name input gets cut off

### ISSUE THREAD

**Issue by Voronsky** [parkervcp/eggs#2593]
### Panel Version

1.11

### Wings Version

1.11

### Service

avorion

### Modified

No, I did not modify the egg

### Expected Behavior

Server name in the build configurations should be written out correctly inside the server.ini file for the corresponding galaxy

### Actual Behavior

Server name gets partially written. It seems to only take the first word in a server name. If you place everything together such as

`--server-name MyPublicServer`

It works. But if it is

`--server-name My Public Server` it fails. Instead the ini file will only have the word "My" as the server name. Here are some screenshots as an example

![Screenshot from 2023-12-06 23-02-54](https://github.com/parkervcp/eggs/assets/1648245/8a4e3ed8-665b-4d58-a988-418ae66280b0)
![Screenshot from 2023-12-06 23-03-21](https://github.com/parkervcp/eggs/assets/1648245/9ba326fb-db21-4629-88d3-77c3531f8b46)

### Steps To Reproduce

1. Import the egg to your avorion nest
2. For  "server name", input a name with white spaces and choose any name for the galaxy
3. Look at the corresponding galaxy's server.ini file after it is built or, look at the terminal output when it's finished.

### Install logs

https://pteropaste.com/pxcy6ra4giiu/

**Comment by QuintenQVD0** [comment]
the server.ini file is not used by the egg as everything is set on startup as arguments and it has "" around the server name variable so it should just work, we do not touch the config file with the egg

**Comment by QuintenQVD0** [comment]
@Voronsky Please try this egg in a seperate server and do not update the egg that is already imported with this one (this one has some cleanup changes that may brake your already made server so import it (so now you have 2 of the same egg imports) and make a server with this one)

[egg-avorion.json](https://github.com/parkervcp/eggs/files/13627751/egg-avorion.1.json)

**Comment by Voronsky** [comment]
> @Voronsky Please try this egg in a seperate server and do not update the egg that is already imported with this one (this one has some cleanup changes that may brake your already made server so import it (so now you have 2 of the same egg imports) and make a server with this one)
> 
> [egg-avorion.json](https://github.com/parkervcp/eggs/files/13627751/egg-avorion.1.json)

Hey there, sorry for the silence. I found time to try this new json egg and I noticed a few things

- It did not fix the name getting chopped at all. It seems to be parsed onto the CLI input string incorrectly or something. Here is an example . In this instance all it parsed out was " [US] " , but left everything else out
![Screenshot from 2023-12-14 16-11-55](https://github.com/parkervcp/eggs/assets/1648245/5ffc6338-127c-4b96-a155-02323590ae94)
 
This is what I put in for the server argument
![Screenshot from 2023-12-14 16-15-56](https://github.com/parkervcp/eggs/assets/1648245/da8c33e1-94de-4de0-b23d-b05c46685bc9)


- The BETA branch variable suddenly seems to be required, but I do not wish to use beta nor did I recall having to do that when I first used the egg linked in the README of this repo, I am not sure how I can use the 'default' as described here in the avorion docs: https://avorion.fandom.com/wiki/Setting_up_a_server#Switching_between_default_and_beta_2

**Comment by QuintenQVD0** [comment]
> > @Voronsky Please try this egg in a seperate server and do not update the egg that is already imported with this one (this one has some cleanup changes that may brake your already made server so import it (so now you have 2 of the same egg imports) and make a server with this one)
> > [egg-avorion.json](https://github.com/parkervcp/eggs/files/13627751/egg-avorion.1.json)
> 
> Hey there, sorry for the silence. I found time to try this new json egg and I noticed a few things
> 
> * It did not fix the name getting chopped at all. It seems to be parsed onto the CLI input string incorrectly or something. Here is an example . In this instance all it parsed out was " [US] " , but left everything else out
>   ![Screenshot from 2023-12-14 16-11-55](https://private-user-images.githubusercontent.com/1648245/290658306-5ffc6338-127c-4b96-a155-02323590ae94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTQ2NDEsIm5iZiI6MTcwMjU5NDM0MSwicGF0aCI6Ii8xNjQ4MjQ1LzI5MDY1ODMwNi01ZmZjNjMzOC0xMjdjLTRiOTYtYTE1NS0wMjMyMzU5MGFlOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMjI1MjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM4MTU1OTExNDlmY2EwNzAwYTUwNzU3MmVmZjIyYjM0MmYyMTkwN2Y2NGZhNjFlYzNlMTU1Njg1NzViNDA2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ijvuBcVnpS90IYWuvt6N39ekaxMcHEyZ40glYKl-_ac)
> 
> This is what I put in for the server argument ![Screenshot from 2023-12-14 16-15-56](https://private-user-images.githubusercontent.com/1648245/290658455-da8c33e1-94de-4de0-b23d-b05c46685bc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTQ2NDEsIm5iZiI6MTcwMjU5NDM0MSwicGF0aCI6Ii8xNjQ4MjQ1LzI5MDY1ODQ1NS1kYThjMzNlMS05NGRlLTRkZTAtYjIzZC1iMDVjNDY2ODViYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMjI1MjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQyNjJiNGQ1ZGQ4ODNjNGMxMWRjZDkxOTg3MTAyZTkxMmI3ZmM4ZTA1YTllMzY3MzI1ZWM2MDAyMzFkMGRkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8Fe7rB5k3Bv6mP6TBhkRQoZoE1R-Qtytz2PLcO_JdWc)
> 
> * The BETA branch variable suddenly seems to be required, but I do not wish to use beta and the old egg had it be a boolean value. I am not sure how I can use the 'default' as described here in the avorion docs: https://avorion.fandom.com/wiki/Setting_up_a_server#Switching_between_default_and_beta_2  , passing "default" seems to be invalid.
> * Is there a way to have more than 1 admin ? It seems that every time the server is restarted, the `admin.xml` file is overwritten, even if I remove the admin flag in the startup cmd.
> 
> Thanks for following up! 😄

The way the old egg did it was and still is bad. You can leave it empty and it will take the default branch,  that cutting of should not happen but server names should also not have pipes in them. About the admin file that is not something we modify or control directly. We just pass the argument to the binary. It should handle itself.

**Comment by QuintenQVD0** [comment]
Also I told you to make a new server? As the startup changed.

**Comment by Voronsky** [comment]
> Also I told you to make a new server? As the startup changed.

So I used your new egg, JSON, as you said above, sorry for not making that clear, my apologies. But with that said

- Beta branch does not allow me to leave it empty. It throws an error and it specifies that it is a required parameter.
 
![Screenshot from 2023-12-15 15-37-29](https://github.com/parkervcp/eggs/assets/1648245/f7e6e1da-0afe-4ea2-b6c4-0780f4e5778f)
![Screenshot from 2023-12-15 15-38-04](https://github.com/parkervcp/eggs/assets/1648245/83cfd92e-9096-40ce-b951-bcee23671db0)

- I tested now with simply just words and white spaces, no special characters and still I have the same issue.
![Screenshot from 2023-12-15 15-41-09](https://github.com/parkervcp/eggs/assets/1648245/946c27b8-dffe-4298-8692-538bdaeb039d)
![Screenshot from 2023-12-15 15-44-12](https://github.com/parkervcp/eggs/assets/1648245/520ec812-1e0a-432c-ac47-6aeeed231110)

- Here is what the new egg json provided as the start up command
`./bin/AvorionServer --galaxy-name {{GALAXY_NAME}} --admin {{ADMIN_ID}} --datapath galaxy --port {{SERVER_PORT}} --query-port {{QUERY_PORT}} --steam-master-port {{STEAM_MASTER_PORT}} --steam-query-port {{STEAM_QUERY_PORT}} --max-players {{MAX_PLAYERS}} --difficulty {{DIFFICULTY}} --collision-damage {{COLLISION_DMG}} --save-interval {{SAVE_INTERVAL}} --same-start-sector {{SAME_START_SECTOR}} --server-name \"{{SERVER_NAME}}\" --threads {{GAME_THREADS}} --listed {{SERVER_LISTED}}`

This came from the egg json you provided, 
[egg-avorion.1(1).json](https://github.com/parkervcp/eggs/files/13689659/egg-avorion.1.1.json)


Thanks for clarification on the admin file !


My current workaround to all of this, is I simply omit the server name and just modify the `server.ini` file directly, which is fine for me but figured in case others come into this similar issue.

**Comment by QuintenQVD0** [comment]
That beta nor working is my fault. I see what i can do to fix it.

**Comment by Voronsky** [comment]
Thank you! Let me know if you'd like me to test for you again.  :smiley:

**Comment by QuintenQVD0** [comment]
> Thank you! Let me know if you'd like me to test for you again. 😃

Ues, please test the pr egg i posted and leave a comment on it. For me ir works now.

**Comment by Voronsky** [comment]
Thanks so much PR #2610 does, in fact, address the issue. I'll comment there, too! The name came out fine with white spaces and with the default branch.
