### ISSUE TITLE
[Egg Request]:  linux native ark survival ascended server software

### ISSUE THREAD

**Issue by BrianWolvers** [parkervcp/eggs#2595]
### Does this expand an already existing service

Yes

### Link to a game or software

https://steamdb.info/app/2430930/depots/

### Links for the download

https://steamdb.info/app/2430930/depots/

### Links for the install docs

https://developer.valvesoftware.com/wiki/SteamCMD

**Comment by BrianWolvers** [comment]
There is how linux native ark ascended server software available

**Comment by parkervcp** [comment]
Seeing as the server page still only says windows. The depot doesn't mean much.

What you linked
![image](https://github.com/parkervcp/eggs/assets/1207679/b792357e-e56f-49e7-bc1a-b11dcb693271)



See ARK:Survival Evolved
![image](https://github.com/parkervcp/eggs/assets/1207679/e113feca-1ae7-4b07-a05e-574dd96d3c55)

**Comment by BrianWolvers** [comment]
But here it dode show the depot
![Screenshot_2023-12-08-23-07-59-37_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/parkervcp/eggs/assets/121485743/fd0368fb-3e38-4219-b45c-eff435f7d259)

**Comment by danny6167** [comment]
All that shows is that it's linked to the Linux SDK repo. Doesn't mean Ark is available for Linux.

Besides, I just tested this. There is still no Linux binaries.

**Comment by dagbs** [comment]
https://steamdb.info/depot/2430931/

Go to [Files] and search:
`ShooterGame/Binaries/Win64`

Then search:
`ShooterGame/Binaries/Linux`

You people keep scaring the community. There are no plans for releasing a Linux binaries. Information about getting the Windows binaries to work through Proton (in Linux) got made known to Wildcard and are happy that we got it to work. The only reason why Linux Binaries would be good is if it provides support to a wider community which wouldn't be the case...

**Comment by QuintenQVD0** [comment]
There are just no linux binaries,  yes there is an linux sdk linked so that is wy it sas linux as supported but there no files. It runs fine with proton.
