### ISSUE TITLE
[Egg Request]: MongoDB Version 7

### ISSUE THREAD

**Issue by zLevii** [parkervcp/eggs#2598]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.mongodb.com/

### Links for the download

https://www.mongodb.com/try/download/community

### Links for the install docs

https://www.mongodb.com/try/download/community

**Comment by jayceslesar** [comment]
looks pretty straight forward...seems that there is already a yolk upstream https://github.com/parkervcp/yolks/blob/master/mongodb/7/Dockerfile so you should be able to pretty much copy paste https://github.com/parkervcp/eggs/blob/master/database/nosql/mongodb/egg-mongo-d-b6.json and just change all the references to 7...
