### ISSUE TITLE
SA:MP server

### ISSUE THREAD

**Issue by astrello** [parkervcp/eggs#26]
Is there a way to restrict users from changing maxplayers in samp server config or to revert it back if they changed it.

**Comment by parkervcp** [comment]
You need to add the changes in the "Configuration Files" area. I recommend making it a variable if anything.

**Comment by astrello** [comment]
I've made a new variable but it seems like it doesnt work, they can easily change the maxplayers and run server with that change.

**Comment by parkervcp** [comment]
You need to add a configuration file thing for it as well. Then you need to restart the daemon to get the change pulled over.

**Comment by astrello** [comment]
I've done that, so for example if i make variable max do i call in in configuration files my {{max}} or by {{env.max}}. I was unable to find that in documentation.

**Comment by astrello** [comment]
I've managed to set it up. Ty for the help. ;)
