### ISSUE TITLE
PaperMC server.properties reset necessary?

### ISSUE THREAD

**Issue by gpago** [parkervcp/eggs#260]
This is mostly a QoL thing, but when re-installing a **PaperMC** server, is the reset of server.properties necessary?
I understand that when first installing a server, the existence of a `server.properties` file is required, but is it possible for it to check if a `server.properties` file already exists and not download another?

Same thing with `config.yml` of the **Waterfall** egg.

**Comment by parkervcp** [comment]
Its not necessary. Its just something overlooked.

**Comment by parkervcp** [comment]
Paper shouldn't be downloading the server.properties every time.

If the file doesn't exist it should ignore it.

**Comment by parkervcp** [comment]
@gpago Can you test that to be sure it does what you want?

**Comment by gpago** [comment]
I apparently missed all notifications about this issue (not that I had any other notifications...). I apologize.
Should I manually import the `.json` file for Paper as I do for Waterfall? (since it's a core egg)
Waterfall works~
Thank you for fixing the issue so quickly! :D
