### ISSUE TITLE
[Bug]: V Rising BepInEx

### ISSUE THREAD

**Issue by Upd4ting** [parkervcp/eggs#2600]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

vrising bepinex

### Modified

No, I did not modify the egg

### Expected Behavior

I expect the server to run

### Actual Behavior

The server is stucked on the command `WINEDLLOVERRIDES="winhttp=n,b"; xvfb-run wine ./VRisingServer.exe -persistentDataPath save-data -address 0.0.0.0`

### Steps To Reproduce

Just startup a VRising server with the VRising Bepinex image.
There was an update from wine 2 days ago, and the `yolks:wine_staging` which is used by the egg was updated 12 hours ago. 
Since that `yolks:wine_staging` got `wine 9 rc1` instead of the previous `wine 8.0.2`. 
I tried to put the egg on `yolks:wine_latest` which is still on `wine 8.0.2` but it does the same problem it's why we had put `yolks:wine_staging` (PR 2550)

Any idea on how we could fix that?
@gOOvER 

### Install logs

no need

**Comment by WSG-ViViV** [comment]
Same here ˆˆ

**Comment by Upd4ting** [comment]
> set the docker image to `ghcr.io/parkervcp/yolks:wine_staging@sha256:34d886534dc7da843f25ae61c209d6e06f4feb0fd52337928b41e5be5af9ac8e`

Just found that too! Should we update the VRising Bepinex egg with that one until the latest built image works again?

**Comment by gOOvER** [comment]
Should not be the problem, that is wine 9 RC1. Staging is everytime bloody dev version of Wine

**Comment by gOOvER** [comment]
Should not be the problem, that is wine 9 RC1. Staging is everytime bloody dev version of Wine

Staging was on Wine 8.12 and not on 8.0.2

**Comment by gOOvER** [comment]
Works fine with Wine 9.0RC1

https://haste.goover.de/uhuzepetim.sql

**Comment by QuintenQVD0** [comment]
> Works fine with Wine 9.0RC1
> 
> https://haste.goover.de/jirejeloxu.yaml

that startup does not match the offical one

**Comment by gOOvER** [comment]
> > Works fine with Wine 9.0RC1
> > https://haste.goover.de/jirejeloxu.yaml
> 
> that startup does not match the offical one

we are on bepinex, not on vanilla vrising

**Comment by QuintenQVD0** [comment]
It seems to be working just fine, you may have to remove the .wine folder.
else just use the older build for now that still has wine 8
