### ISSUE TITLE
[Install Bug]: SAMP

### ISSUE THREAD

**Issue by RuzitoTV** [parkervcp/eggs#2601]
### Panel Version

1.11.5

### Wings Version

1.11.5

### Service

game_eggs/gta/samp

### Modified

No, I did not modify the egg

### Expected Behavior

I expected the egg to install the native GTA SAMP SERVER files and after that start the server normally

### Actual Behavior

The egg intended to install the native GTA Samp files but after waiting about 2 minutes, it throws an error indicating that it could not be installed and after that, it does not install any files and does not run the server either.

### Steps To Reproduce

Step 1: Perform server configuration.
Step 2: begin the Server installation.
Step 3: Error Display

![imagen_2023-12-11_161156862](https://github.com/parkervcp/eggs/assets/150984937/4f27a43f-1510-4683-bb67-1f3d0c792d57)

### Install logs

https://pteropaste.com/foe4te7jgohm

**Comment by Anaphylaxis** [comment]
Egg works fine for me, are you sure this isn't network related?
Your install is failing right at the start where it downloads the file.
`curl -sSL -o samp.tar.gz https://sampcenter.com/download/server/linux/0.3.7.tar.gz` works fine for me.
![image](https://github.com/parkervcp/eggs/assets/40187776/4739b327-0071-4ca1-8aec-b9e44a69e213)
![image](https://github.com/parkervcp/eggs/assets/40187776/a599ef22-a810-4992-9736-a5f9876d0034)

**Comment by RuzitoTV** [comment]
Oh, I've been trying to solve this problem for literally 2 days, can you suggest a solution please? 😣

**Comment by Anaphylaxis** [comment]
> Oh, I've been trying to solve this problem for literally 2 days, can you suggest a solution please? 😣

I would check your docker container outbound connectivity first, as a workaround you can try downloading elsewhere and rehosting it / extracting it manually and uploading the files via sftp, but naturally you'd want to fix the connectivity issues

**Comment by RuzitoTV** [comment]
> > Oh, I've been trying to solve this problem for literally 2 days, can you suggest a solution please? 😣
> 
> I would check your docker container outbound connectivity first, as a workaround you can try downloading elsewhere and rehosting it / extracting it manually and uploading the files via sftp, but naturally you'd want to fix the connectivity issues

I have the ports open on my VPS, and it doesn't want to download it automatically, I don't know what to do :(

**Comment by RuzitoTV** [comment]
> > Oh, I've been trying to solve this problem for literally 2 days, can you suggest a solution please? 😣
> 
> I would check your docker container outbound connectivity first, as a workaround you can try downloading elsewhere and rehosting it / extracting it manually and uploading the files via sftp, but naturally you'd want to fix the connectivity issues

Friend, I ask you a question, what ports should you open or how can I check that I have the connectivity correctly configured, greetings

**Comment by QuintenQVD0** [comment]
This issue is closed because you have a modified version or not the latest version of the egg.
Your shows the installer image as Ubuntu and the official is Debian.
We do not support that. 
the official latest egg works and has the right certs installed

**Comment by RuzitoTV** [comment]
> This issue is closed because you have a modified version or not the latest version of the egg. Your shows the installer image as Ubuntu and the official is Debian. We do not support that. the official latest egg works and has the right certs installed

Hello friend, I installed my VPS to Debian 12, now trying the egg again gives me the same error, what do you think it could be? Greetings

**Comment by Anaphylaxis** [comment]
> > This issue is closed because you have a modified version or not the latest version of the egg. Your shows the installer image as Ubuntu and the official is Debian. We do not support that. the official latest egg works and has the right certs installed
> 
> Hello friend, I installed my VPS to Debian 12, now trying the egg again gives me the same error, what do you think it could be? Greetings
> 
> ![image](https://private-user-images.githubusercontent.com/150984937/290005417-065443b7-dbbc-4425-a93e-b046964f06c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTg1NjksIm5iZiI6MTcwMjQxODI2OSwicGF0aCI6Ii8xNTA5ODQ5MzcvMjkwMDA1NDE3LTA2NTQ0M2I3LWRiYmMtNDQyNS1hOTNlLWIwNDY5NjRmMDZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQyMTU3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWM3NDMwMzU4ZmZkM2ZkNDVhYTkwYTllNDdhMWI5NTUxMTM0MmMzN2NhYjg0NzJmMDkyOWFiN2U3ZTlmZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rfQb-B_G0dU0wt51hThQMXO3dky9yWwh24Fh2Cxg_Sk)

Export your egg from the panel and send it here. If it's not the same that is your issue. If it is then you have outbound docker connectivity issues, which is out of scope. Maybe reinstall docker whilst following the Pterodactyl guide all the way through.

**Comment by RuzitoTV** [comment]
> > > This issue is closed because you have a modified version or not the latest version of the egg. Your shows the installer image as Ubuntu and the official is Debian. We do not support that. the official latest egg works and has the right certs installed
> > 
> > 
> > Hello friend, I installed my VPS to Debian 12, now trying the egg again gives me the same error, what do you think it could be? Greetings
> > ![image](https://private-user-images.githubusercontent.com/150984937/290005417-065443b7-dbbc-4425-a93e-b046964f06c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTg1NjksIm5iZiI6MTcwMjQxODI2OSwicGF0aCI6Ii8xNTA5ODQ5MzcvMjkwMDA1NDE3LTA2NTQ0M2I3LWRiYmMtNDQyNS1hOTNlLWIwNDY5NjRmMDZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQyMTU3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWM3NDMwMzU4ZmZkM2ZkNDVhYTkwYTllNDdhMWI5NTUxMTM0MmMzN2NhYjg0NzJmMDkyOWFiN2U3ZTlmZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rfQb-B_G0dU0wt51hThQMXO3dky9yWwh24Fh2Cxg_Sk)
> 
> Export your egg from the panel and send it here. If it's not the same that is your issue. If it is then you have outbound docker connectivity issues, which is out of scope. Maybe reinstall docker whilst following the Pterodactyl guide all the way through.

Hello friend, here I am sending you the egg, although it is the same one that I downloaded from here, do you know how I can reinstall the Dockers? Greetings and thank you very much for the help
[egg-s-a--m-p.json](https://github.com/parkervcp/eggs/files/13653605/egg-s-a--m-p.json)
[README.md](https://github.com/parkervcp/eggs/files/13653607/README.md)
