### ISSUE TITLE
[Install Bug]: ReHLDS 25th anniversary issue

### ISSUE THREAD

**Issue by MEEKR1T** [parkervcp/eggs#2603]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

HLDS/ReHLDS

### Modified

No, I did not modify the egg

### Expected Behavior

I expect that the server will eventually start up after setup. However due to a bug that came with the HL 25th anniversary update, ReHLDS will not work. Per the ReHLDS github issues, the solution is to install the steam_legacy beta version of the game. https://github.com/dreamstalker/rehlds/issues/999#issuecomment-1826375535
I cannot figure out how to implement this in the egg.

### Actual Behavior

`Error: /home/container/engine_i486.so: undefined symbol: SteamGameServer
Unable to load engine, image is corrupt.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.`

### Steps To Reproduce

Download the egg from this repo, the file is called egg-custom-re-h-l-d-s-engine-game.json
Add the egg to Pterodactyl from the Nests menu
Create a new server with the egg
Wait for it to finish downloading SteamCMD and all the dependencies.
Watch the console for the error I am having. 

### Install logs

https://pteropaste.com/owcejcknowtt

**Comment by danny6167** [comment]
Try deleting the libstdc++.so.6 file the game server downloaded

**Comment by QuintenQVD0** [comment]
if that ^^ does not work I write you a fix to allow for downloading a other branch

**Comment by MEEKR1T** [comment]
I tested this and I was able to get it working once with a Half Life server. Then I tried to make another server but for CS1.6, and was not successful. I even tried making another Half Life server and it didn't work. I'll keep messing with it to see if I am just making a mistake.

This is the libstdc++.so.6 file that is located in /home/container/steamcmd/linux32 correct?

**Comment by MEEKR1T** [comment]
Update to my previous comment. I still cannot get this fix to work again. Not sure what has changed, but every time I delete the libstdc++.so.6 file from /home/container/steamcmd/linux32, it reappears when I restart the container. I have tried deleting the server and recreating it from the egg, multiple times with no success.

**Comment by MEEKR1T** [comment]
I got it working.

https://github.com/parkervcp/eggs/pull/2605

**Comment by QuintenQVD0** [comment]
Fixt as of #2605
