### ISSUE TITLE
[Egg Request]: Nginx with PHP 8.2

### ISSUE THREAD

**Issue by scharez** [parkervcp/eggs#2619]
### Does this expand an already existing service

No

### Link to a game or software

https://www.nginx.com/

### Links for the download

https://www.nginx.com/

### Links for the install docs

https://www.nginx.com/

**Comment by gOOvER** [comment]
ptero is Not for webhosting

**Comment by scharez** [comment]
> ptero is Not for webhosting

But it works. See https://github.com/Sigma-Production/ptero-eggs

**Comment by QuintenQVD0** [comment]
> > ptero is Not for webhosting
> 
> But it works. See https://github.com/Sigma-Production/ptero-eggs

we never sad not possible, we sad not supported
