### ISSUE TITLE
[Bug]: Conan Exiles | no password set , the server will still ask for a password.

### ISSUE THREAD

**Issue by jhondoue** [parkervcp/eggs#2626]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Source Engine

### Modified

No, I did not modify the egg

### Expected Behavior

I assumed that even if I left the server password blank in the panel, I would be able to log in to the server without a password if I restarted it.

### Actual Behavior

The server will ask for your password.

### Steps To Reproduce

Current Egg	Source Engine :: Conan Exiles

xvfb-run --auto-servernum wine /home/container/ConanSandbox/Binaries/Win64/ConanSandboxServer-Win64-Shipping.exe -Port={{SERVER_PORT}} -QueryPort={{QUERY_PORT}} -RconPort={{RCON_PORT}} -ServerName="{{SRV_NAME}}" -ServerPassword="{{SRV_PW}}" -console -log

### Install logs

https://pteropaste.com/4l01v6qt0gs3/

**Comment by QuintenQVD0** [comment]
![image](https://github.com/parkervcp/eggs/assets/67589015/bf1d8f97-db83-4954-9b24-27590ef79fc6)

Was not empty on install. You can try just hitting join ane leaving the field empty. Else then for now just use a password. I fix this later.

**Comment by QuintenQVD0** [comment]
@jhondoue Try changing the startup to `xvfb-run --auto-servernum wine /home/container/ConanSandbox/Binaries/Win64/ConanSandboxServer-Win64-Shipping.exe -Port={{SERVER_PORT}} -QueryPort={{QUERY_PORT}} -RconPort={{RCON_PORT}} -ServerName="{{SRV_NAME}}" $(if [ -n "$SRV_PW" ]; then echo "-ServerPassword=\"${SRV_PW}\""; fi) -console -log` and see if it works.

**Comment by jhondoue** [comment]
@QuintenQVD0 Thank you for answering.
The verification results are reported below.

1) If you change the startup and create a server without a password, clients can log in to the server without a password.

2) When I entered "SERVER PASSWORD" on the startup tab of the panel and restarted the server, I was unable to log in to the server even though I entered the correct password.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Thank you for answering. The verification results are reported below.
> 
> 1. If you change the startup and create a server without a password, clients can log in to the server without a password.
> 2. When I entered "SERVER PASSWORD" on the startup tab of the panel and restarted the server, I was unable to log in to the server even though I entered the correct password.

So you edited the startup of the already made server to the one i posted? Hit save then left the field empty.  Then the startup bash logic should have not printed the -serverpassword. Note that there may be a default one in a random config file that you may have to clear.

**Comment by jhondoue** [comment]
@QuintenQVD0
The test was performed while deploying a completely new server.
When creating a new server, I rewrote the startup script with the content you provided.

**Comment by QuintenQVD0** [comment]
Install went fine but should not be related. I need to check myself. But currently busy

**Comment by gOOvER** [comment]
> @QuintenQVD0 The test was performed while deploying a completely new server. When creating a new server, I rewrote the startup script with the content you provided.
> 
> Below is the log during installation. I'll share it just in case https://pteropaste.com/bgrwr84qnsvz/

install was fine ;) as you see on your log

**Comment by jhondoue** [comment]
@QuintenQVD0 
No problem.
The problem of not being able to log in even though a password has not been set has been resolved.
thank you.

A related problem is that if you set a password on the panel and reboot the Conan server, you will not be able to log in with the password you set, and you will also be unable to log in without the password.

However, when I logged into the server and set the server password in the in-game admin panel, it worked properly.

The root of the problem lies elsewhere, not in the installation part.
This time, we were able to partially avoid the problem using the script you provided.

**Comment by jhondoue** [comment]
I created an account for verification on my panel.
Anyone can use it freely.

Username: github2626
Password:Password
panelURL:https://gsv.bestnetllc.co.jp/

**Comment by QuintenQVD0** [comment]
> I created an account for verification on my panel. Anyone can use it freely.
> 
> Username: github2626 Password:Password panelURL:https://gsv.bestnetllc.co.jp/

![image](https://github.com/parkervcp/eggs/assets/67589015/da4cfef1-68e2-4bdd-a393-e5cff0844950)

My logic did work. There was no server password passed as an argument to the server. And in the config field for it it is also empty. So there is not realy more I can do.

**Comment by jhondoue** [comment]
@QuintenQVD0 
Yes, the script you created is working perfectly.
thank you.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Yes, the script you created is working perfectly. thank you.

So there should be no password to the server.

**Comment by Drlanderf** [comment]
Nobody fix this ?
The startup script u send don't work, with password and without password.

Also, some parameters aren't in the right location following the doc provided by conan exile..

**Comment by Drlanderf** [comment]
ServerName and  server password normaly are save inside the /
home/container/ConanSandbox/Saved/Config/WindowsServer/Engine.ini file not the ServerSettings.ini file..
also, normaly the AdminPassword need to be set in the ServerSettings.ini file

there is a problem at the base of the container..
