### ISSUE TITLE
[Egg Request]: Deadside

### ISSUE THREAD

**Issue by zRxnx** [parkervcp/eggs#2627]
### Does this expand an already existing service

No

### Link to a game or software

https://www.deadsidegame.com

### Links for the download

https://steamdb.info/app/1275530/info/

### Links for the install docs

NA

**Comment by yesBad** [comment]
How are we supposed to make an egg for something that has no documentation? 🤔

**Comment by Software-Noob** [comment]
There are no public dedicated server files. Only their partnered host gportal is granted access if you look up any of their past replies to questions about allowing community to host them.
