### ISSUE TITLE
[Bug]: Valheim Vanilla

### ISSUE THREAD

**Issue by Talung** [parkervcp/eggs#2631]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

valheim vanilla

### Modified

No, I did not modify the egg

### Expected Behavior

Get about the same ping as on a straight docker install of valheim

### Actual Behavior

Running through the egg it adds approximately 50ms ping time.  Using the command ingame `/ping`.

ie.  Pterodactyle docker gives me a result of 70-89ms
using lloesche/valheim-server docker image I get about 16-30ms.

### Steps To Reproduce

1. On the same machine setup a vanilla Valheim server using the egg and setup one using another docker image. 
2. Login to pterodactyl one and hit "enter" then type `/ping` a few times to get the latency.  might want to wait 2 minutes for things to settle.
3. Login to docker one and do the same.

### Install logs

https://pteropaste.com/ky2nrdd5d09h

**Comment by Talung** [comment]
Added notes:
I get the same ping as the straight docker running Valheim through LGSM on a container.
I have also created a separate Virtual Machine for a new Wing and get the same issue on the Pterodactyl Wing.

**Comment by QuintenQVD0** [comment]
This is not an bug with the egg? 50ms is needed some extra delay but nothing that we can fix on the egg side

**Comment by Talung** [comment]
> This is not an bug with the egg? 50ms is needed some extra delay but nothing that we can fix on the egg side

I believe it is a bug with the egg build.  There is something weird going on in the docker image of that egg that doesn't happen in any alternative system be it on docker or other container.  This doesn't appear to be an issue with other games like 7 days to die etc. but only with the valheim build.

But honestly I just don't know.  I have tried everything I can think of and it persists.  Currently I am running the game on a straight docker image.

**Comment by QuintenQVD0** [comment]
this is not egg related

**Comment by Talung** [comment]
> this is not egg related

Maybe I don't understand the terminology correctly. Can you at least point me in the direction that this is related too.  It is not the network as that works fine with everything else, It is not the actual game as again it works fine under alternative installs.  The only place that has issues is installing it via the egg on a pterodactyl wing.

**Comment by Talung** [comment]
While having a shower... I figured it out.. it was crossplay that adds the 50ms!

I am closing this issue.
