### ISSUE TITLE
[Install Bug]: Curseforge Generic

### ISSUE THREAD

**Issue by Ebnater** [parkervcp/eggs#2632]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

minecraft/curseforge-generic

### Modified

No, I did not modify the egg

### Expected Behavior

Install Modpack with ID 4076357

### Actual Behavior

Retrieving CurseForge project information...
        No file ID specified, using latest file
        Found server pack file id '4076357'
        Retrieving version information for '4076357'
        ERROR: Failed to retrieve file data for file id '4076357'

### Steps To Reproduce

1. Create new server
2. Choose Curseforge
3. Choose ID 4076357
4. Install

### Install logs

https://pteropaste.com/r3hb6ughppui

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> 
> 1.11.5
> ### Wings Version
> 
> 1.11.8
> ### Service
> 
> minecraft/curseforge-generic
> ### Modified
> 
> No, I did not modify the egg
> ### Expected Behavior
> 
> Install Modpack with ID 4076357
> ### Actual Behavior
> 
> Retrieving CurseForge project information... No file ID specified, using latest file Found server pack file id '4076357' Retrieving version information for '4076357' ERROR: Failed to retrieve file data for file id '4076357'
> ### Steps To Reproduce
> 
>     1. Create new server
> 
>     2. Choose Curseforge
> 
>     3. Choose ID 4076357
> 
>     4. Install
> 
> 
> ### Install logs
> 
> https://pteropaste.com/r3hb6ughppui

Keep in mind that this leaked your api key.

And where did you get your API key? I hope for you that it is one from here: https://console.curseforge.com/#/login

**Comment by Ebnater** [comment]
Yes it is. It's regenerated now

**Comment by Ebnater** [comment]
Found out it's cursforge which is providing null as download url:

`"fileDate":"2022-01-11T19:53:48.54Z",
            "fileLength":153398920,
            "downloadCount":657,
            "downloadUrl":null,`
