### ISSUE TITLE
[Egg Request]: Varnish

### ISSUE THREAD

**Issue by n1ses** [parkervcp/eggs#2636]
### Does this expand an already existing service

Yes

### Link to a game or software

https://varnish-cache.org/

### Links for the download

https://varnish-cache.org/releases/index.html

### Links for the install docs

https://varnish-cache.org/docs/trunk/installation/index.html

**Comment by QuintenQVD0** [comment]
Pterodactyl does not support web hosting (same for reverse proxies) also this will not work that well as you can not allocate ports lower then 1024.
