### ISSUE TITLE
[Bug]: SpaceStation 14 Robust Server: Permission Denied and .NET 8 update needed.

### ISSUE THREAD

**Issue by IzyAcorn** [parkervcp/eggs#2641]
### Does this expand an already existing service

Yes

### Link to a game or software

https://spacestation14.io/

### Links for the download

https://spacestation14.io/about/nightlies/

### Links for the install docs

https://docs.spacestation14.com/en/general-development/setup/server-hosting-tutorial.html

**Comment by IzyAcorn** [comment]
**Steps to reproduce with current egg:**
1. Install the Space Station 14 server using this egg: https://github.com/parkervcp/eggs/tree/master/game_eggs/spacestation_14
2. Run the server.
3. Error will appear saying Robust Server: Permission denied.

**Current behaviour:**
1. After running the server first go, it brings up the error `Robust Server: Permission denied`.
2. When that is fixed it demands that you have .NET 8 installed.

**My Fix:**
I have managed to get it running by changing the docker image from **Dotnet 7|ghcr.io/parkervcp/yolks:dotnet_7** to **Dotnet 8|ghcr.io/parkervcp/yolks:dotnet_8**.

You still also have to SSH into the server and run `chmod u+x ./Robust.Server` in the servers' folder. Mine was in _var/lib/pterodactyl/volumes/[server folder]_. This will make the Robust.Server and executable and allow you to run the server provided that .NET 8 is installed on the image.

Below is the egg with the edited .NET docker image:
[egg-spacestation14 - .NET 8.json](https://github.com/parkervcp/eggs/files/13814815/egg-spacestation14.-.NET.8.json)

Not overly sure about the process of updating eggs but it would help others if the .NET 8 version was uploaded along with some extra guidance in the README for running `chmod u+x ./Robust.Server`, if this could be done automatically via the install script that'd be even better.

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> Yes
> 
> ### Link to a game or software
> https://spacestation14.io/
> 
> ### Links for the download
> https://spacestation14.io/about/nightlies/
> 
> ### Links for the install docs
> https://docs.spacestation14.com/en/general-development/setup/server-hosting-tutorial.html

You used the wrong template. You should have used bug report.

**Comment by IzyAcorn** [comment]
> You used the wrong template. You should have used bug report.

Ahh my apologies, I was unsure which one to use. Had both templates open in my browser at one point lol.

**Comment by QuintenQVD0** [comment]
@IzyAcorn Please leave a comment on the PR to confirm that it is working or not.

**Comment by IzyAcorn** [comment]
@QuintenQVD0 This is now done :)
