### ISSUE TITLE
[Egg Request]: Raft

### ISSUE THREAD

**Issue by ValhallaCommunityOfficial** [parkervcp/eggs#2642]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/648800/Raft/

### Links for the download

Within the install docs

### Links for the install docs

https://rdswiki.raftmodding.com/tutorials/linux-installing-your-server

**Comment by ValhallaCommunityOfficial** [comment]
Not sure if this is even possible, just posted out of chance. Feel free to delete if it cant be done.

**Comment by ImKringle** [comment]
Server software is behind a paywall; not able to be installed in a script whatsoever - plus it requires ownership of the game. Unlikely

**Comment by QuintenQVD0** [comment]
It needs login to get the server files, their docs seem prity good on how to install / run it. I do not own the game but if someone can provide those files (just for testing only ofc) or want to buy this game for me then an egg I guess can be made.

**Comment by QuintenQVD0** [comment]
I am going to mark this as not feasable, if someone disagrees let me know. 

- needs an account that own the games with steamguard off
- need a logged in account to get the 3rth party server files
- need patron to activate the server.
