### ISSUE TITLE
[Egg Request]: Farming Simulator 2022

### ISSUE THREAD

**Issue by KalviPL** [parkervcp/eggs#2644]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/1248130/Farming_Simulator_22/

### Links for the download

dedicatedServer.exe (will be downloaded with game)

### Links for the install docs

Only exec dedicatedServer.exe

**Comment by QuintenQVD0** [comment]
Yea no, You need a 2nd copy of the game that is non-steam, you need a nginx reverse proxy for in the container for the web dashboard what is not allowed (web hosting). And the 2nd copy that is required must be activated on Windows on the same machine as the wings are as it is hardware locked and then be uploaded. So I am marking this as not possible.

**Comment by QuintenQVD0** [comment]
> > Yea no, You need a 2nd copy of the game that is non-steam, you need a nginx reverse proxy for in the container for the web dashboard what is not allowed (web hosting). And the 2nd copy that is required must be activated on Windows on the same machine as the wings are as it is hardware locked and then be uploaded. So I am marking this as not possible.
> 
> yes you have to own a 2nd copy but you can also own it through another steam account and make a server through it. why should webhosting not be allowed? there are enough eggs that do this and as far as i know it is not hardware locked with steam

This is a game hosting panel. Not a web hosting panel. And no supported eggs use a webserver. 

And for steam you then need a running steamclient in the backup what does not work with pelican or pterodactyl.
