### ISSUE TITLE
[Bug]: FiveM

### ISSUE THREAD

**Issue by higuysimnewhere561** [parkervcp/eggs#2646]
### Panel Version

1.11.3

### Wings Version

1.11.8

### Service

gta/fivem

### Modified

No, I did not modify the egg

### Expected Behavior

The container should be responding to console commands.

### Actual Behavior

The container does not respond to console commands, further resulting in the "stop" button not working and having to force-kill the server.

### Steps To Reproduce

Step 1 - Install the egg
Step 2 - Attempt to use console commands and/or stop server.
![image_2024-01-06_092607193](https://github.com/parkervcp/eggs/assets/137571695/627186d4-ee3c-48c7-a734-eac475c74805)

### Install logs

https://pteropaste.com/mhuy79t8tkne

**Comment by parkervcp** [comment]
From prior conversations. This is a know issue. So far as I understand it's related to this change <https://github.com/citizenfx/fivem/commit/bf86882d9420c739f8b4e6e1fa6104f1697ba29b>

This is also known on their side. I have talked to their team about this in the past.

**Comment by QuintenQVD0** [comment]
Just a note, if you want the stop to properly work, change the egg stop from `quit` to `^C`
