### ISSUE TITLE
panel variables are not resolved on gameserver start

### ISSUE THREAD

**Issue by Prisma501** [parkervcp/eggs#265]
Panel Version: 0.7.14
Daemon Version: 0.6.12
Service: 7dtd
Modified: (yes) : only the name of the latest 7dtd egg for non-intrusive import 

Expected Behavior: variables in the startup command are resolved to value of the field defined in panel. Ex. ${{server.build.env.MAX_PLAYERS}} should be resolved to 8 (default)

Actual Behavior: variables are resolved to $${varname}. Ex. ${{server.build.env.MAX_PLAYERS}} is resolved to $${server.build.env.MAX_PLAYERS} rendering the startup command to something like this:
/7DaysToDieServer.x86_64 -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated -ServerPort=$${server.build.default.port} -ServerMaxPlayerCount=$${server.build.env.MAX_PLAYERS} -GameDifficulty=$${server.build.env.GAME_DIFFICULTY} -ControlPanelEnabled=false -TelnetEnabled=true -TelnetPort=28004 -logfile logs/latest.log & echo -e "Checing on telnet connection" && until nc -z -v -w5 127.0.0.1 28004; do echo "Waiting for telnet connection..."; sleep 5; done && telnet -E 127.0.0.1 28004

Steps to Reproduce: create a server with latest egg. Let default values live. On server start look at the startup command used in console. Server wont be able to start because of illegal gameport (-ServerPort=$${server.build.default.port})

**Comment by Sir3lit** [comment]
You gotta call the variables correctly for them to work

{{SERVER_PORT}} would be the defualt port. 
{{GAME_DIFFICULTY}} etc.

**Comment by Prisma501** [comment]
This is stock egg. I didnt change the var calls. And i did test with a custom egg wrapping vars in {{  }} 
That resolved the vars to ${varname}

**Comment by Prisma501** [comment]
Oh i see what you mean now. Stock eggs contains vars like ${{server.build.env.MAX_PLAYERS}}  and ${{server.build.default.port}}.
In my test i only removed the $ so they are {{server.build.env.MAX_PLAYERS}} and {{server.build.default.port}}. That didnt work. I will defo try removing the server.build.env. part from the vars and test again. Stock egg is not good then. So still a bug. :)

**Comment by Prisma501** [comment]
Tested with startup string in egg:
"'.\/7DaysToDieServer.x86_64 -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated -ServerPort={{SERVER_PORT}} -ControlPanelEnabled=false -ControlPanelPort={{CONTROLPANEL_PORT}} -TelnetEnabled=true -TelnetPort={{TELNET_PORT}} -SaveGameFolder={{SAVES_FOLDER}} -UserDataFolder={{USERDATA_FOLDER}} -logfile logs\/latest.log & echo -e \"Checing on telnet connection\" && until nc -z -v -w5 127.0.0.1 {{TELNET_PORT}}; do echo \"Waiting for telnet connection...\"; sleep 5; done && telnet -E 127.0.0.1 {{TELNET_PORT}}'",


in console after resolving it shows:
./7DaysToDieServer.x86_64 -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated -ServerPort=${SERVER_PORT} -ControlPanelEnabled=false -ControlPanelPort=${CONTROLPANEL_PORT} -TelnetEnabled=true -TelnetPort=${TELNET_PORT} -SaveGameFolder=${SAVES_FOLDER} -UserDataFolder=${USERDATA_FOLDER} -logfile logs/latest.log & echo -e "Checing on telnet connection" && until nc -z -v -w5 127.0.0.1 ${TELNET_PORT}; do echo "Waiting for telnet connection..."; sleep 5; done && telnet -E 127.0.0.1 ${TELNET_PORT}

But it works! The panel vars are used in the startup command. So the egg in repo just has to has the $ removed and all should be good.

Thanks Sir3lit

**Comment by parkervcp** [comment]
Seeing as the egg in the repo doesn't have doubled $ signs like your had I am closing this out.

See the following - https://github.com/parkervcp/eggs/blob/master/source_servers/7_days_to_die/egg-7-days-to-die.json#L11

**Comment by msgerbs** [comment]
I'm actually seeing this same issue.

**Comment by msgerbs** [comment]
My startup command in the configuration is this:

`'./7DaysToDieServer.x86_64 -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated -ServerPort=${{server.build.default.port}} -ServerMaxPlayerCount=${{server.build.env.MAX_PLAYERS}} -GameDifficulty=${{server.build.env.GAME_DIFFICULTY}} -ControlPanelEnabled=false -TelnetEnabled=true -TelnetPort=8081 -logfile logs/latest.log & echo -e "Checing on telnet connection" && until nc -z -v -w5 127.0.0.1 8081; do echo "Waiting for telnet connection..."; sleep 5; done && telnet -E 127.0.0.1 8081'`

But the actual command shown in the server log is this:

`./7DaysToDieServer.x86_64 -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated -ServerPort=$${server.build.default.port} -ServerMaxPlayerCount=$${server.build.env.MAX_PLAYERS} -GameDifficulty=$${server.build.env.GAME_DIFFICULTY} -ControlPanelEnabled=false -TelnetEnabled=true -TelnetPort=8081 -logfile logs/latest.log & echo -e "Checing on telnet connection" && until nc -z -v -w5 127.0.0.1 8081; do echo "Waiting for telnet connection..."; sleep 5; done && telnet -E 127.0.0.1 8081`

**Comment by parkervcp** [comment]
Then there is something else parsing incorrectly.

**Comment by msgerbs** [comment]
So... Does that mean it's something I did wrong? I literally just left the defaults alone.

**Comment by parkervcp** [comment]
No it doesn't mean you did anything wrong but I have never seen it fail on my own.
