### ISSUE TITLE
[Egg Request]: BedrockConnect

### ISSUE THREAD

**Issue by Lovingtaken3** [parkervcp/eggs#2653]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/Pugmatt/BedrockConnect

### Links for the download

https://github.com/Pugmatt/BedrockConnect/releases

### Links for the install docs

https://github.com/Pugmatt/BedrockConnect/wiki/Setting-up-on-Linux

**Comment by QuintenQVD0** [comment]
Reading up on this, this needs BIND9 `ubuntu dnsutils package` but it has to be special configured what in pterodactyl we can not do as the file system is read only where the config file is and there is no systemd so this can not work.
