### ISSUE TITLE
[Egg Request]: N8N

### ISSUE THREAD

**Issue by louanfontenele** [parkervcp/eggs#2656]
### Does this expand an already existing service

No

### Link to a game or software

https://n8n.io/

### Links for the download

https://github.com/n8n-io/n8n

### Links for the install docs

https://docs.n8n.io/hosting/installation/

**Comment by QuintenQVD0** [comment]
The generic Node.js with little to no modification can run this. 

edit the MAIN_FILE to have a max of 32 and not 16 char and set its value to `node_modules/n8n/bin/n8n`
set the NODE_PACKAGES to `n8n`

and it will run, you will have to make some extra variables for the port or and bind ip but it can run it just fine

**Comment by QuintenQVD0** [comment]
> > The generic Node.js with little to no modification can run this.
> > edit the MAIN_FILE to have a max of 32 and not 16 char and set its value to `node_modules/n8n/bin/n8n` set the NODE_PACKAGES to `n8n`
> > and it will run, you will have to make some extra variables for the port or and bind ip but it can run it just fine
> 
> Did you test it?

Yes I did
