### ISSUE TITLE
[Install Bug]: BeamMP Server

### ISSUE THREAD

**Issue by Gelvey** [parkervcp/eggs#2667]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

beammp

### Modified

No, I did not modify the egg

### Expected Behavior

Manage -> Reinstall Server -> (Updated BeamMP Server)

### Actual Behavior

Manage -> Reinstall Server -> Deleted the startup file and server will not start (./BeamMP-Server)

### Steps To Reproduce

1 Admin Control Panel 2 Servers 3 (Your Server) 4  Manage 5 Reinstall Server

### Install logs

https://pteropaste.com/byadtgw050ri/

**Comment by QuintenQVD0** [comment]
Your egg is not up to date.

**Comment by Gelvey** [comment]
And how do I update the egg?

**Comment by Gelvey** [comment]
Ended up being a BeamMP issue, not an egg issue.
