### ISSUE TITLE
[Install Bug]: MariaDB

### ISSUE THREAD

**Issue by Redstoner89** [parkervcp/eggs#2673]
### Panel Version

1.11.3

### Wings Version

1.11.3?

### Service

mariadb

### Modified

No, I did not modify the egg

### Expected Behavior

Install the SQL and use it

### Actual Behavior

Server crashed
:/home/container$ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true $( [[ ! -f unix_args.txt ]] && printf %s "-jar ${SERVER_JARFILE}" || printf %s "@unix_args.txt" )
/entrypoint.sh: line 13: java: command not found

### Steps To Reproduce

1. Install MariaDB
2. Load egg
3. Run the egg for the first time (/ install it)

### Install logs

The command won't execute (gets stuck)

**Comment by Redstoner89** [comment]
Full error: :/home/container$ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true $( [[ ! -f unix_args.txt ]] && printf %s "-jar ${SERVER_JARFILE}" || printf %s "@unix_args.txt" )
/entrypoint.sh: line 13: java: command not found

**Comment by QuintenQVD0** [comment]
This is some random mismatch, update your egg as this is a java startup
