### ISSUE TITLE
[Egg Request]: Mailu

### ISSUE THREAD

**Issue by DevJernejTDO** [parkervcp/eggs#2674]
### Does this expand an already existing service

Yes

### Link to a game or software

https://mailu.io/2.0/index.html

### Links for the download

https://mailu.io/2.0/index.html

### Links for the install docs

https://mailu.io/2.0/setup.html

**Comment by yesBad** [comment]
Not even possible in Ptero.

**Comment by DevJernejTDO** [comment]
ok
