### ISSUE TITLE
[Egg Request]: Enshrouded

### ISSUE THREAD

**Issue by FlowyFlow** [parkervcp/eggs#2675]
### Does this expand an already existing service

No

### Link to a game or software

https://enshrouded.com/

### Links for the download

https://enshrouded.zendesk.com/hc/en-us/articles/16051370691485-Dedicated-Server-Installation-on-Steam

### Links for the install docs

https://enshrouded.zendesk.com/hc/en-us/articles/16055441447709-Dedicated-Server-Configuration

**Comment by hoechstn** [comment]
I get this error when server tries to run 

```
ERROR: [Jan 23 09:39:20.724] failed to parse and update server configuration file error=invalid character ':' after top-level value server=00000000-0000-0000-0000-0000000000

Stacktrace:
invalid character ':' after top-level value
github.com/pterodactyl/wings/server.(*Server).UpdateConfigurationFiles.func1
        /wings/server/config_parser.go:29
github.com/gammazero/workerpool.worker
        /go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:237
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650
```

**Comment by QuintenQVD0** [comment]
> I get this error when server tries to run
> 
> ```
> ERROR: [Jan 23 09:39:20.724] failed to parse and update server configuration file error=invalid character ':' after top-level value server=00000000-0000-0000-0000-0000000000
> 
> Stacktrace:
> invalid character ':' after top-level value
> github.com/pterodactyl/wings/server.(*Server).UpdateConfigurationFiles.func1
>         /wings/server/config_parser.go:29
> github.com/gammazero/workerpool.worker
>         /go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:237
> runtime.goexit
>         /usr/local/go/src/runtime/asm_amd64.s:1650
> ```

You can not use this egg until it is merged as the config download will fail.
manualy place the config there if you want to test it

**Comment by hoechstn** [comment]
> You can not use this egg until it is merged as the config download will fail. manualy place the config there if you want to test it

This error was after I manually placed the config file

**Comment by QuintenQVD0** [comment]
> > You can not use this egg until it is merged as the config download will fail. manualy place the config there if you want to test it
> 
> This error was after I manually placed the config file

It sounds to me like the config you copied had some wrong char in them.

**Comment by ValhallaCommunityOfficial** [comment]
Not sure if these install docs have been posted..
https://github.com/PR3SIDENT/enshrouded-server

Now we just need to wait for them to make server files accessible anonymously.

**Comment by QuintenQVD0** [comment]
> Not sure if this has been posted.. https://github.com/PR3SIDENT/enshrouded-server
> 
> Now we just need to wait for them to make server files accessible anonymously.

An egg was merged what will work the moment anonymous download is enabled.

**Comment by QuintenQVD0** [comment]
Closed as of https://github.com/parkervcp/eggs/pull/2686
