### ISSUE TITLE
Server not findable: Ark Survival Evolved

### ISSUE THREAD

**Issue by tyler72us** [parkervcp/eggs#2680]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Ark Survival Evoloved

### Modified

No, I did not modify the egg

### Expected Behavior

I am hosting several servers on one node.  I expect to be able to discover and connect to them individually. 

### Actual Behavior

They are all marked as running on the console, but when I try to add them via the local network IP in the steam server list view, only 2 are discoverable. When I try to add the rest manually, it says "Did not find any servers at this address".

### Steps To Reproduce

Step one.  Host 5 Ark server.
Step two: Try to connect via Steam Server list after they are marked as running. 

### Install logs

https://drive.google.com/file/d/1C4Pd36PYSYYt1yfWxK5CLdxdLd6TjJqU/view?usp=sharing

**Comment by parkervcp** [comment]
We have covered this many times. There is a hard limit of 25k servers on the list and they are always over that. You can reload the list and might show up.

**Comment by tyler72us** [comment]
That is not my issue.  I am not trying to see it in the in-game server list.  I am trying to add it over LAN,  through steams favorite server menueg.
4. Log in to Steam.


5. Select View on the top left.


6. Choose Game Servers.


7. Click on the Favorites tab.


8. Press the plus icon on the bottom right.


9. Paste the game server's IP:Port.

This has nothing to do with 25k entries.  The servers have been left on for a few days so have had plenty of time to finish establishing themselves on the network

**Comment by parkervcp** [comment]
You need to add the server via the query port and not the game server port.

**Comment by tyler72us** [comment]
That's what I was missing.  Thank you very much!
