### ISSUE TITLE
[Bug]: Enshrouded

### ISSUE THREAD

**Issue by jojolebobo** [parkervcp/eggs#2687]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Enshrouded

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server and start it 

### Actual Behavior

Crypto API failed certificate check, error flags 0x00010008 for '/jurisdictionC=
US/jurisdictionST=Washington/businessCategory=Private Organization/serialNumber=
602 290 773/C=US/ST=Washington/L=Bellevue/O=Valve Corp/CN=store.steampowered.com

### Steps To Reproduce

Step 1 : Install the server 
Step 2 : Run the server
Step 3 : Error after downloading server content and run

### Install logs

https://pteropaste.com/rv26eqziflm1

**Comment by gOOvER** [comment]
Not an egg issue. Looks like a bad cert. Reinstall the server

**Comment by jojolebobo** [comment]
After new install, https://pteropaste.com/lr1sj5x317gl

**Comment by jojolebobo** [comment]
Ok i deleted all file and reinstall from scratch and issue is now fixed.

**Comment by Dhenier** [comment]
I am having this exact same issue. The host admins have completely wiped the directory where it was installed and re-created a fresh instance again. Still has same bug reported. The server is Linux os hosted in USA.
