### ISSUE TITLE
[Bug]: Enshrouded Lost Packet

### ISSUE THREAD

**Issue by oOScuByOo** [parkervcp/eggs#2689]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Enshrouded

### Modified

No, I did not modify the egg

### Expected Behavior

Move smoothly, didn't lost such packet

### Actual Behavior

![image](https://github.com/parkervcp/eggs/assets/5473243/acc45ed1-a507-4491-ba88-6f679e58ecff)

### Steps To Reproduce

Nothing special done ...

### Install logs

https://pteropaste.com/56e4fo9mz4xu

**Comment by Vapok** [comment]
This is not due to the egg or Pterodactyl.

This is a bandwidth latency issue.  Keep in mind that Enshrouded requires a much higher bandwidth than other games.
