### ISSUE TITLE
[Bug] Enshrouded egg 

### ISSUE THREAD

**Issue by Cerberus2459** [parkervcp/eggs#2694]
### Panel Version

1.11.5

### Wings Version

1.57

### Service

Enshrouded

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Everything installed as it should, server ran and was visible in game. 

### Actual Behavior

Server password syntax error?
Server password doesn't apply in game. 
Password sets without required quotations, is ignored by server?
![Screenshot 2024-01-26 082432](https://github.com/parkervcp/eggs/assets/157809242/44a06700-a166-4a55-936e-42a6e7364fd3)

### Steps To Reproduce

Normal install, apply server password, check in game, no pass.
Remove server.
Edit egg to remove from config files: "password": "{{server.build.env.SERVER_PASSWORD}}",
Install server.
Setup as normal, skip password box.
Edit enshrouded_server.json add the password with quotations "12345"
Password now works with server.
![Screenshot 2024-01-26 082309](https://github.com/parkervcp/eggs/assets/157809242/32b9de53-dd33-4392-b69a-5a4adf4ecf2c)

### Install logs

https://pteropaste.com/0iinvkniv2kn

**Comment by QuintenQVD0** [comment]
This egg is in the process of moving to proton and I will check it as it is almost a whole rewrite

**Comment by Cerberus2459** [comment]
> This egg is in the process of moving to proton and I will check it as it is almost a whole rewrite

Glad I could contribute in any small way, Appreciate your work.
