### ISSUE TITLE
[Bug]: <Enshrouded>

### ISSUE THREAD

**Issue by CoatiTV** [parkervcp/eggs#2695]
### Panel Version

1.11.5

### Wings Version

v1.11.8

### Service

enshrouded

### Modified

No, I did not modify the egg

### Expected Behavior

i have install the server and start it but its not in server list

### Actual Behavior

Hey i have install the Enshrouded egg and install the server run but its not in der Server List

### Steps To Reproduce

......................................

### Install logs

gk

**Comment by parkervcp** [comment]
There is nothing we can do to guarantee that a server will show up on the server list.

**Comment by gOOvER** [comment]
@CoatiTV Check the FAQ in Enshrouded Discord
