### ISSUE TITLE
[Egg Request]: Huginn

### ISSUE THREAD

**Issue by Zaybrah** [parkervcp/eggs#2698]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/huginn/huginn

### Links for the download

https://github.com/huginn/huginn/releases

### Links for the install docs

https://github.com/huginn/huginn/blob/master/doc/manual/installation.md

**Comment by gOOvER** [comment]
Not really sth for pterodactyl. it needs ruby, postgredb

I think, its not really possible and easy to create an Egg for it

**Comment by QuintenQVD0** [comment]
This is way to complex for pterodactyl, eggs are designed to run a single application.

Sorry
