### ISSUE TITLE
[Egg Request]: Java 21

### ISSUE THREAD

**Issue by scharez** [parkervcp/eggs#2701]
### Does this expand an already existing service

Yes

### Link to a game or software

https://openjdk.org/projects/jdk/21/

### Links for the download

https://openjdk.org/projects/jdk/21/

### Links for the install docs

https://openjdk.org/projects/jdk/21/

**Comment by yesBad** [comment]
This is not a place to request Java yolks. 

Plus it already exists; ghcr.io/pterodactyl/yolks:java_21

**Comment by scharez** [comment]
> This is not a place to request yolks tbh.
> 
> Plus it already exists; ghcr.io/pterodactyl/yolks:java_21

So I only have to add it to the java egg?

**Comment by QuintenQVD0** [comment]
> > This is not a place to request yolks tbh.
> > Plus it already exists; ghcr.io/pterodactyl/yolks:java_21
> 
> So I only have to add it to the java egg? Under docker_images?

Yes. But in a panel! Please do not edit the json files directly.

**Comment by scharez** [comment]
> > > This is not a place to request yolks tbh.
> > > Plus it already exists; ghcr.io/pterodactyl/yolks:java_21
> > 
> > 
> > So I only have to add it to the java egg? Under docker_images?
> 
> Yes. But in a panel! Please do not edit the json files directly.

Thank you very much ^^
