### ISSUE TITLE
[Egg Request]: LiveKit

### ISSUE THREAD

**Issue by SanctifiedDevil** [parkervcp/eggs#2702]
### Does this expand an already existing service

Yes

### Link to a game or software

https://livekit.io/

### Links for the download

https://github.com/livekit/livekit

### Links for the install docs

https://docs.livekit.io/realtime/self-hosting/vm/

**Comment by QuintenQVD0** [comment]
This can not run in Pterodactyl, as it needs multiple services, including Redis and a web server. Pterodactyl is made to run 1 single application, an egg
