### ISSUE TITLE
[Egg Request]: World Of Warcraft(Azerothcore)

### ISSUE THREAD

**Issue by FirestormeDS** [parkervcp/eggs#2703]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.azerothcore.org/

### Links for the download

https://www.azerothcore.org/wiki/linux-core-installation

### Links for the install docs

https://www.azerothcore.org/wiki/installation

**Comment by FirestormeDS** [comment]
theres 2 types of installation 
1. is a manual installation
2. is an installation process based on Docker with a pre built image

**Comment by gOOvER** [comment]
WoW Server are against TOS of Blizzard and not allowed

**Comment by QuintenQVD0** [comment]
I don't know if it is against the TOS, but This will at least take 40 + min an installation.

The install container should never need to run that long just for a single server that may not even be allowed
