### ISSUE TITLE
[Bug]: <Palworld can't change server settings>

### ISSUE THREAD

**Issue by Greensnake2001** [parkervcp/eggs#2705]
### Panel Version

1.11.2

### Wings Version

..

### Service

/ home / container / Pal / Saved / Config / LinuxServer / PalWorldSettings.ini

### Modified

No, I did not modify the egg

### Expected Behavior

Good morning,

We used the egg from Palworld to make pterodactyl. Now we just want to change the server settings to enable PVP, for example. This just doesn't work for us and we don't know where it can happen.

There is an ini file called defaultpalworldsettings.ini. It clearly states that you have to go to another path to change the settings, but when I go to that path the document is empty.

Do you have any idea where the server config is located?
![1345](https://github.com/parkervcp/eggs/assets/158144049/ad4413a4-a12e-4e94-b944-5d22e25e3376)
![134](https://github.com/parkervcp/eggs/assets/158144049/4a3f276e-de67-45f9-a0ec-41b68d4caa80)

### Actual Behavior

Not need

### Steps To Reproduce

a

### Install logs

a

**Comment by QuintenQVD0** [comment]
Please remove all files in the saved/config/linuxserver directory, update your egg and then hit reinstall

**Comment by Greensnake2001** [comment]
Yes i think i found the problem

The setup scirpt saying this
if [ -f "/mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" ]; then
    echo "Config file already exitis, backing up and overwriting with a new one"
    mv /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings_$(date +"%Y%m%d%H%M%S").ini
    cp /mnt/server/DefaultPalWorldSettings.ini /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
else 
    echo "Creating new config file"
    cp /mnt/server/DefaultPalWorldSettings.ini /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
fi

So i remove this an copie the settings to palwolrdsetinngs restart the sever and then this file will now remain full with data, so I'll test it this afternoon to see if it works

**Comment by QuintenQVD0** [comment]
> Yes i think i found the problem
> 
> The setup scirpt saying this if [ -f "/mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" ]; then echo "Config file already exitis, backing up and overwriting with a new one" mv /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings_$(date +"%Y%m%d%H%M%S").ini cp /mnt/server/DefaultPalWorldSettings.ini /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini else echo "Creating new config file" cp /mnt/server/DefaultPalWorldSettings.ini /mnt/server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini fi
> 
> So i remove this an copie the settings to palwolrdsetinngs restart the sever and then this file will now remain full with data, so I'll test it this afternoon to see if it works

That is on OLD egg! update first, remove the file then hit reinstall it will work.

**Comment by Greensnake2001** [comment]
Where can i found the new egg?
And if i reinstall will i lose than my process on the server?

Is this the egg?
https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/palworld

**Comment by QuintenQVD0** [comment]
> Where can i found the new egg? And if i reinstall will i lose than my process on the server?
> 
> Is this the egg? https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/palworld

Yes it is that egg, it was update about 12 hours ago, and no reinstalling will not delete data, if you want to be certain then make a backup first.

**Comment by Greensnake2001** [comment]
Ah okayy i will try it. Thank you

To make sure if i do reinstall. Than the server will by reinstall not that i lose the pokemons and the levels form the players who are playing.

**Comment by Greensnake2001** [comment]
So now this wil work? There is now data in the folder palworldsettings.

![12](https://github.com/parkervcp/eggs/assets/158144049/1d51d212-ced2-48e3-b746-67d6bb029ee0)

**Comment by QuintenQVD0** [comment]
> So now this wil work? There is now data in the folder palworldsettings.
> 
> ![12](https://private-user-images.githubusercontent.com/158144049/300757308-1d51d212-ced2-48e3-b746-67d6bb029ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDg5NzUsIm5iZiI6MTcwNjYwODY3NSwicGF0aCI6Ii8xNTgxNDQwNDkvMzAwNzU3MzA4LTFkNTFkMjEyLWNlZDItNDhlMy1iNzQ2LTY3ZDZiYjAyOWVlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwOTU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWUyYmM3NzdiNDY0OTVkMDc3MDg2ZjEzMzdhNjM5MWUzNWFlNmM1NmMyNjMxMmUzZDZlYWY5YmJlMzQ3MmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hTM50g8Z8IoyZGWXZorTN1DND6eG2IGLTUTQn9cnAY4)

Yes, now it is up to the game engine.

**Comment by QuintenQVD0** [comment]
I am closing this as this is resolved, if something does not work with that config then that is a game issue and not egg related.
