### ISSUE TITLE
[Bug]: Palworld

### ISSUE THREAD

**Issue by devpanda0** [parkervcp/eggs#2707]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

palworld

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

That the server starts

### Actual Behavior

The error appears as shown in the picture. I have already seen the error in the Egg Request, but the error also occurs with the latest Egg version
![image](https://github.com/parkervcp/eggs/assets/49129501/29b90384-81e1-4b8e-9781-daddfe204ad5)

### Steps To Reproduce

Step 1: Import egg
Step 2: Install server
Step 3: See errors in the console :) 

### Install logs

https://pteropaste.com/pfqjriav7r2w/

**Comment by KemMuammer** [comment]
I also got this Issue. 

container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/steamcmd 
Status: Image is up to date for ghcr.io/parkervcp/steamcmd:debian 
Digest: sha256:e32a3f0104c9aa3c0f9790d203e72261f106ee06e6dc8c9650f7da9038a3395c 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
tid(21) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '2394010' already up to date.
:/home/container$ /home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publicip=${PUBLIC_IP} -port=${SERVER_PORT} -publicport=${SERVER_PORT} -servername="${SERVER_NAME}" -players=${MAX_PLAYERS} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword=\"${SERVER_PASSWORD}\""; fi) -adminpassword="${ADMIN_PASSWORD}"
Shutdown handler: initalize.
- Existing per-process limit (soft=1048576, hard=1048576) is enough for us (need only 1048576)
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Loaded '/home/container/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
Setting breakpad minidump AppID = 2394010
container@pterodactyl~ Server marked as running...
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

Is there anything I can also provide to fix this?

**Comment by parkervcp** [comment]
Pleas explain which part of this you see as an issue?

**Comment by KemMuammer** [comment]
I hoped you can tell me more about it, I cannot connect to the server at all. I thought maybe it is the api fails at the end. 
![image](https://github.com/parkervcp/eggs/assets/32688950/93efc500-ffcc-4240-b869-302bbc613c23)
Is what I get when I try to connect. The public ip in the settings is the right port is forwarded. I did not change any settings except the ones at the start.

**Comment by parkervcp** [comment]
You startup looks fine. As for not being able to connect I have seen all kinds of weird issues from others with no issues myself without the public ip set

**Comment by parkervcp** [comment]
This screams issues with networking. Are you certain that you have all the ports open properly? If this is on OVH the game firewall will block all UDP connections until a TCp connection is made. You need to disable it to make it work.

**Comment by spaulli** [comment]
I'm having the exact same issues. Anyone have a fix?

**Comment by rowbawts** [comment]
I've got a server running for some friends and I see those same messages but I just assumed them benign as the server has been working with no issues.

**Comment by leetxen** [comment]
I was just sitting down to troubleshoot this issue and found this guide: https://tech.palworldgame.com/dedicated-server-guide

It talks about doing these changes:
`mkdir -p ~/.steam/sdk64/
steamcmd +login anonymous +app_update 1007 +quit
cp ~/Steam/steamapps/common/Steamworks\ SDK\ Redist/linux64/steamclient.so ~/.steam/sdk64/`

However I am not sure how to run these in the container.

**Comment by QuintenQVD0** [comment]
> I also got this Issue.
> 
> container@pterodactyl~ Server marked as starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/steamcmd Status: Image is up to date for ghcr.io/parkervcp/steamcmd:debian Digest: sha256:e32a3f0104c9aa3c0f9790d203e72261f106ee06e6dc8c9650f7da9038a3395c [Pterodactyl Daemon]: Finished pulling Docker container image steam user is not set. Using anonymous user. tid(21) burning pthread_key_t == 0 so we never use it WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' Logging directory: '/home/container/Steam/logs' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1705108307 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK Success! App '2394010' already up to date. :/home/container$ /home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publicip=${PUBLIC_IP} -port=${SERVER_PORT} -publicport=${SERVER_PORT} -servername="${SERVER_NAME}" -players=${MAX_PLAYERS} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword="${SERVER_PASSWORD}""; fi) -adminpassword="${ADMIN_PASSWORD}" Shutdown handler: initalize.
> 
> * Existing per-process limit (soft=1048576, hard=1048576) is enough for us (need only 1048576)
>   Increasing per-process limit of core file size to infinity.
> * Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
>   dlopen failed trying to load:
>   steamclient.so
>   with error:
>   steamclient.so: cannot open shared object file: No such file or directory
>   [S_API] SteamAPI_Init(): Loaded '/home/container/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
>   CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
>   dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
>   Setting breakpad minidump AppID = 2394010
>   container@pterodactyl~ Server marked as running...
>   [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
>   [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
>   [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
>   [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
> 
> Is there anything I can also provide to fix this?

Those are all normal. And means running. They can be ignored because there is no steam client installed. But steamcmd.so file is there so it will use that. 

This is a network issue.

**Comment by devpanda0** [comment]
I could now try it. I can access the server despite the error messages

**Comment by Ballaual** [comment]
when seeing this "errors" is everything fine and the server is running. you might also check on 3rd party websites if you find your server there. if you cant connect its 99% a port forwaring issue on the host system or some connection issues on the client side.
however you can try to set ``bIsMultiplay`` from false to true in your ``PalWorldSettings.ini``. Due to lack of information in they official documentation there is not known a lot about this setting but allegedly it helped some people with their connection issues.

**Comment by Kickbut101** [comment]
For what it's worth, I have thrown out the public IP part of the startup command completely.

This is what I have in the "Startup Command" field for my server and it's been running since the first dev egg was started about a week ago.

`/home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal -port=20007 -players=16 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS EpicApp=PalServer -servername="{{SRV_NAME}}" -adminpassword="PASSWORD"`

**Comment by QuintenQVD0** [comment]
> For what it's worth, I have thrown out the public IP part of the startup command completely.
> 
> This is what I have in the "Startup Command" field for my server and it's been running since the first dev egg was started about a week ago.
> 
> `/home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal -port=20007 -players=16 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS EpicApp=PalServer -servername="{{SRV_NAME}}" -adminpassword="PASSWORD"`
> 
> And if you're referring to these errors: `[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded. [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded. [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded. [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.`
> 
> Those I get too, but my server operates fine

that startup is heavy out of date, update your egg, and then the startup of all already made servers and then hit reinstall als the latest egg has a working console and a configuration parser.

**Comment by parkervcp** [comment]
It's time for me to close this as it is most likely a networking issue.
