### ISSUE TITLE
Rust egg issue

### ISSUE THREAD

**Issue by Alexhill2233** [parkervcp/eggs#271]
I am trying to make a rust server and whenever i press start it does the steamcmd loading correctly. But then straight after gets stuck on `Waiting for RCON to come up...` and then won't finish loading.  I waited 3 hours for it to start and instead of it starting it just flooded the console with `Waiting for RCON to come up...`. I have all the ports i need open and on the server (28015 [Default] and 28016 [RCON] and 27015 [Steam]).

**Comment by Sceptox** [comment]
Having the exact same issue.
Only fix is to open port the RCON port, 8401 if I am right.

**Comment by Madogi** [comment]
let it launch with no mods before u start adding mods in

**Comment by parkervcp** [comment]
I am going to call out that if you only see `Waiting for RCON to come up...` then you didn't set the variable for the rcon or the server hung on startup and it will never start.
