### ISSUE TITLE
[Bug]: Palworld

### ISSUE THREAD

**Issue by ZaxLofful** [parkervcp/eggs#2710]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Palworld

### Modified

No, I did not modify the egg

### Expected Behavior

Running without errors

### Actual Behavior

After the server is started, this continues to pop-up

OODLE USAGE WARNING : Destination buffer appears to be in uncached
or write-combined memory! This is extremely slow. See "How do I
decompress to graphics memory quickly?" in the Oodle FAQ.
(Usage warnings can be disabled via Oodle_SetUsageWarnings.)

### Steps To Reproduce

Install Palworld and leave it running for multiple days, it will repeat this every hour or so

### Install logs

https://pteropaste.com/hegbk4leiaxb/

**Comment by yesBad** [comment]
This is not an issue. It is normal. Complain to Palworld.

**Comment by QuintenQVD0** [comment]
1. This us not an egg issue 
2. Your egg is very old.

**Comment by ZaxLofful** [comment]
> 1. This us not an egg issue
> 
>     2. Your egg is very old.

I have updated the egg multiple times, do I have to reinstall the game container?

**Comment by rowbawts** [comment]
> I have updated the egg multiple times, do I have to reinstall the game container?

Yes, also make sure you update the startup command.
