### ISSUE TITLE
[Bug]: Stationeers Server process doesn't start listening on designated ports

### ISSUE THREAD

**Issue by joecasanova** [parkervcp/eggs#2711]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

stationeers

### Modified

No, I did not modify the egg

### Expected Behavior

Expect the server to report "World load complete" and for game to become available to join.

### Actual Behavior

Server hangs in a starting state and clients cannot connect.

### Steps To Reproduce

1. Pull latest version of Stationeers egg.
2. Upload into Nest in panel.
3. Create new server with appropriate startup configurations/port mappings.
4. Wait - last line in console will be something to the effect of: Total: 387.670196 ms (FindLiveObjects: 20.139462 ms CreateObjectMapping: 10.321165 ms MarkObjects: 349.707334 ms  DeleteObjects: 7.501145 ms)
5. Run netstat -plunt within the container and see the server process is not listening on any ports.

### Install logs

https://pteropaste.com/jsau6ttuzkqi

**Comment by gOOvER** [comment]
pls post the full console output

**Comment by joecasanova** [comment]
> Stationeers have no consoleout, so check your network

Can you elaborate on what in my network I should be checking?  My overall pterodactyl/wings set up works fine on many other eggs - this one seems to be giving a specific issue.

I see traffic pass to the server when I try to connect from the WAN IP or LAN IP.  The client reports "a connection could not be established" in both cases.

Running nmap from an external host against the two assigned ports for the server return as closed on both TCP and UDP.

On the wing server I see docker-proxy listening on TCP & UDP ports assigned to this server.  Docker reports it is mapping the assigned ports to the container.

When I exec a shell into the container running stationeers and run netstat -plunt I see nothing listening on the assigned ports.  This is after 2+ hours of "starting".  It would appear there isn't a process listening on the assigned ports.

I can pull a PCAP on the situation if you'd like.

**Comment by illmaren** [comment]
I've got the same issue with the Stationeers Egg.
The Server is Starting I get quite some errors regarding the assets not being compatible with the GPU and then after a bit I get the following message:

`Total: 278.478695 ms (FindLiveObjects: 16.348418 ms CreateObjectMapping: 10.670671 ms MarkObjects: 247.178508 ms  DeleteObjects: 4.280588 ms)`

Which is the last one the output is showing. Pterodactyl is listing the Server as starting and nothing else happens. 
Letting it run for 24h does not change anything. 

Ports there correctly assigned. 16gb of ram and 40gb disk space were allocated. 

After starting the Server I get this error here:
`
EntryPointNotFoundException: SetConsoleOutputCP assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) UI.ImGuiUi.RocketSystemConsole.SetConsoleOutputCP(uint)
  at UI.ImGuiUi.RocketSystemConsole..ctor (System.String title) [0x00074] in <ebda921d0c3d4ea7967246ef4933952e>:0 
  at Assets.Scripts.ConsoleWindow._Init () [0x0006d] in <ebda921d0c3d4ea7967246ef4933952e>:0
`
after the startup command.

**Comment by X-Coder** [comment]
Exactly same for me as illmaren reported.

Tried with 3 different eggs on two debian bookworm servers as host (one server started from a fresh install, the other server had a running install before).

The process is freezing before the world is generating and before the listening ports opens.

Running netstat -anop inside the docker container shows no listening ports while the process is running. If you try to start the process manually again inside the docker container you can't stop the process by pressing ctrl+c, only by kill-command. So the process has to be frozen.

Tried strace -f on the process these are the last lines (the last lines where repeating, so I removed them):
```
2751656 lstat("/home/container/.config", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/.steam", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/BepInEx", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/Steam", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/doorstop_libs", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/rocketstation_DedicatedServer_Data", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/saves", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/scripts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/steamapps", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 lstat("/home/container/steamcmd", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 close(5)                        = 0
2751656 getcwd("/home/container", 261)  = 16
2751656 lstat("/home/container/stationeers_1", 0x7fffaeb44af0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
2751656 stat("/home/container", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 stat("/home/container/saves", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 stat("/home/container/scripts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 openat(AT_FDCWD, "/home/container/saves", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 5
2751656 newfstatat(5, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
2751656 getdents64(5, 0x5652457aa7f0 /* 3 entries */, 32768) = 88
2751656 getdents64(5, 0x5652457aa7f0 /* 0 entries */, 32768) = 0
2751656 lseek(5, 0, SEEK_SET)           = 0
2751656 getdents64(5, 0x5652457aa7f0 /* 3 entries */, 32768) = 88
2751656 getdents64(5, 0x5652457aa7f0 /* 0 entries */, 32768) = 0
2751656 lstat("/home/container/saves/stationeers_1", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2751656 close(5)                        = 0
2751656 openat(AT_FDCWD, "/home/container/saves/stationeers_1", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 5
2751656 newfstatat(5, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
2751656 getdents64(5, 0x5652457aa7f0 /* 2 entries */, 32768) = 48
2751656 getdents64(5, 0x5652457aa7f0 /* 0 entries */, 32768) = 0
2751656 lseek(5, 0, SEEK_SET)           = 0
2751656 getdents64(5, 0x5652457aa7f0 /* 2 entries */, 32768) = 48
2751656 getdents64(5, 0x5652457aa7f0 /* 0 entries */, 32768) = 0
2751656 close(5)                        = 0
2751742 <... clock_nanosleep resumed>NULL) = 0
2751742 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751656 futex(0x7f847f5b2188, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
2751739 <... futex resumed>)            = 0
2751656 <... futex resumed>)            = 1
2751739 futex(0x7f847f5b2188, FUTEX_WAKE_PRIVATE, 1) = 1
2751740 <... futex resumed>)            = 0
2751739 sched_get_priority_min(SCHED_OTHER) = 0
2751740 futex(0x7f847f5b2188, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1712174969, tv_nsec=703089000}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
2751739 sched_get_priority_max(SCHED_OTHER) = 0
2751739 sched_setscheduler(96, SCHED_OTHER, [0]) = 0
2751739 sched_get_priority_min(SCHED_OTHER) = 0
2751739 sched_get_priority_max(SCHED_OTHER) = 0
2751739 sched_setscheduler(96, SCHED_OTHER, [0]) = 0
2751739 futex(0x7f847f5b2188, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1712174965, tv_nsec=304237000}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
2751741 <... clock_nanosleep resumed>NULL) = 0
2751741 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751656 mmap(0x41297000, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS|MAP_32BIT, -1, 0) = 0x41297000
2751742 <... clock_nanosleep resumed>NULL) = 0
2751742 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751741 <... clock_nanosleep resumed>NULL) = 0
2751741 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751742 <... clock_nanosleep resumed>NULL) = 0
2751742 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751741 <... clock_nanosleep resumed>NULL) = 0
2751741 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751742 <... clock_nanosleep resumed>NULL) = 0
2751742 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751741 <... clock_nanosleep resumed>NULL) = 0
2751741 clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000},  <unfinished ...>
2751656 futex(0x7f83f00023e0, FUTEX_WAKE_PRIVATE, 11 <unfinished ...>
2751678 <... futex resumed>)            = 0
2751677 <... futex resumed>)            = 0
2751676 <... futex resumed>)            = 0
2751675 <... futex resumed>)            = 0
2751673 <... futex resumed>)            = 0
2751672 <... futex resumed>)            = 0
2751671 <... futex resumed>)            = 0
2751674 <... futex resumed>)            = 0
2751670 <... futex resumed>)            = 0
2751669 <... futex resumed>)            = 0
2751656 <... futex resumed>)            = 11
2751679 <... futex resumed>)            = 0
2751678 futex(0x7f83f00023e0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=4294967, tv_nsec=295000000} <unfinished ...>
2751677 futex(0x7f83f00023e0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=4294967, tv_nsec=295000000} <unfinished ...>
```

**Comment by X-Coder** [comment]
Ok, found a fix for me:
World Name had to be a uppercased "**M**ars", not mars.

**Comment by illmaren** [comment]
@X-Coder Thanks for that Info I changed the egg directly and now it works for me like a charm too.
