### ISSUE TITLE
[Bug]: Barotrauma unsupported text

### ISSUE THREAD

**Issue by Sean-Destefano** [parkervcp/eggs#2712]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Barotrauma

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

The console should properly display character outputs from the server, and unhandled characters should be properly discarded.

### Actual Behavior

The server has issues with some of the output from the server, leading to garbled data in the console and severely degrading server performance. See [here](https://github.com/FakeFishGames/Barotrauma/issues/11483) for more detail.

This was fixable by modifying the startup script from
 `./DedicatedServer -batchmode` 
to
 `./DedicatedServer -batchmode 2>&1 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"`

### Steps To Reproduce

Step 1: Setup Barotrauma via provided egg
Step 2: Connect and start a game.
Step 3: View the garbled console output, and degraded performance.

### Install logs

https://pteropaste.com/5hagbd8vv5by/

**Comment by QuintenQVD0** [comment]
if we append that to the startup then it will preform better and stop outputting garbage?

**Comment by Sean-Destefano** [comment]
> if we append that to the startup then it will preform better and stop outputting garbage?

Yes, at least so far in my testing.
