### ISSUE TITLE
[Bug]: Palworld server start

### ISSUE THREAD

**Issue by tommycentral** [parkervcp/eggs#2713]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

palworld

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Start the server, runs and can connect.

### Actual Behavior

Getting console error: "Shutdown handler: initalize.
Refusing to run with the root privileges."

Full run:
steam user is not set.

Using anonymous user.

tid(21) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '2394010' already up to date.
:/home/container$ /home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publicip=${PUBLIC_IP} -port=${SERVER_PORT} -publicport=${SERVER_PORT} -servername="${SERVER_NAME}" -players=${MAX_PLAYERS} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword=\"${SERVER_PASSWORD}\""; fi) -adminpassword="${ADMIN_PASSWORD}"
Shutdown handler: initalize.
Refusing to run with the root privileges.

### Steps To Reproduce

Installed the egg
Server installs egg
Trying to reboot/run server, produces error.

### Install logs

https://pteropaste.com/osumfcbtiofk/

**Comment by parkervcp** [comment]
What did you change here? There is no explanation for what you did.

**Comment by tommycentral** [comment]
Ah my bad, I didn't change anything, I'm just trying to install the server with the egg, that's it.

**Comment by parkervcp** [comment]
I have no idea why it's looking for root. We don't use root for any eggs.
