### ISSUE TITLE
[Egg Request]: Palworld How Do I set the all game configuration on the panel

### ISSUE THREAD

**Issue by LAIguapi** [parkervcp/eggs#2715]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/palworld

### Links for the download

https://store.steampowered.com/app/1623730/Palworld/

### Links for the install docs

https://tech.palworldgame.com/dedicated-server-guide

**Comment by LAIguapi** [comment]
I tried to preset all the game settings on the startup command, but unfortunately, when I finished my settings and restarted the 
Pterodactyl server, the settings didn`t work 
so I wanted an egg that provided all the variables to change, i tried to write a preset and I don't know if that helped you
[egg-palworld--all--variables.json](https://github.com/parkervcp/eggs/files/14123345/egg-palworld--all--variables.1.json)

**Comment by QuintenQVD0** [comment]
> I tried to preset all the game settings on the startup command, but unfortunately, when I finished my settings and restarted the Pterodactyl server, the settings didn`t work so I wanted an egg that provided all the variables to change, i tried to write a preset and I don't know if that helped you [egg-palworld--all--variables.json](https://github.com/parkervcp/eggs/files/14123345/egg-palworld--all--variables.1.json)

To be honest, wait until I update my parser application to allow changing other variables then the default that come with the egg, this change will normally happen in the next 24 hours, then I make a PR and then you can do that

**Comment by LAIguapi** [comment]
> > I tried to preset all the game settings on the startup command, but unfortunately, when I finished my settings and restarted the Pterodactyl server, the settings didn`t work so I wanted an egg that provided all the variables to change, i tried to write a preset and I don't know if that helped you [egg-palworld--all--variables.json](https://github.com/parkervcp/eggs/files/14123345/egg-palworld--all--variables.1.json)
> 
> To be honest, wait until I update my parser application to allow changing other variables then the default that come with the egg, this change will normally happen in the next 24 hours, then I make a PR and then you can do that

really? In this case, I will wait patiently for your PR, so that I can change all variables on the panel with the new PalWorld egg. 
Thanks for your reply
