### ISSUE TITLE
[Bug]: <Enshrouded>

### ISSUE THREAD

**Issue by vvb7456** [parkervcp/eggs#2721]
### Panel Version

1.11.4.0

### Wings Version

1.11.8.0

### Service

Enshrouded

### Modified

No, I did not modify the egg

### Expected Behavior

Set server password

### Actual Behavior

There is a server password in the json file, but the password is not required when joining the server.
(Maybe the password value needs to be enclosed in double quotes as well?)

### Steps To Reproduce

Automatically generated json file

```
{
    "gamePort": 15638,
    "ip": "0.0.0.0",
    "logDirectory": "./logs",
    "name": "my server name",
    "password": mypassword,
    "queryPort": 15639,
    "saveDirectory": "./savegame",
    "slotCount": 16
}
```

### Install logs

Unable to provide

**Comment by QuintenQVD0** [comment]
The latest egg should do that just fine, try updating your egg, then removing the config file , hit reinstall (the data will not be lost) and see as there indeed should be "" around that.

**Comment by blacktail1937** [comment]
I encounter that also, and with the lastest egg in main branch.

**Comment by omgftw** [comment]
This is an active bug. It happens when a password is purely numeric. I believe since the parser is "json" it's considered a number and rendered as such on server start-up (by pterodactly). Then, because the game is expecting a string, the value is ignored. Also I can't find any log output indicating this from the game, so it's fairly difficult to know why your password isn't getting set and the config file seems to be overwritten every time the server is restarted, so modifying the enshrouded_server.json doesn't work because it just gets overwritten.

Example: {"password": 1234}

Current workaround: Add a letter to your password.

**Comment by blacktail1937** [comment]
> This is an active bug. It happens when a password is purely numeric. I believe since the parser is "json" it's considered a number and rendered as such on server start-up (by pterodactly). Then, because the game is expecting a string, the value is ignored. Also I can't find any log output indicating this from the game, so it's fairly difficult to know why your password isn't getting set and the config file seems to be overwritten every time the server is restarted, so modifying the enshrouded_server.json doesn't work because it just gets overwritten.
> 
> Example: {"password": 1234}
> 
> Current workaround: Add a letter to your password.

I'll try it, thx

**Comment by ginsm** [comment]
>  the config file seems to be overwritten every time the server is restarted, so modifying the enshrouded_server.json doesn't work because it just gets overwritten.

For anyone running into this issue.. instead of modifying the `enshrouded_server.json` file directly via `Files`, click on `Startup` and modify it there.

**Comment by ValhallaCommunityOfficial** [comment]
Since a bug post is already here I might as well add this.. The new enshrouded update totally borked the server with viper's egg

![image](https://github.com/parkervcp/eggs/assets/142844832/200a84d5-adc6-4737-a245-1f9110dfbcee)

**Comment by gOOvER** [comment]
Drive c is wrong. delete Prefix and restart server

**Comment by QuintenQVD0** [comment]
This is not directly thr eggs fault. Just enter a password that always has 1 letter in it.
