### ISSUE TITLE
[Install Bug]: Palworld

### ISSUE THREAD

**Issue by rhettp** [parkervcp/eggs#2722]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Palworld Install

### Modified

No, I did not modify the egg

### Expected Behavior

Install with no issues

### Actual Behavior

Installation fails, don't know why.

root@instan:~# uname -a
Linux instan 5.15.0-1045-oracle #51-Ubuntu SMP Fri Sep 22 10:56:53 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

![server](https://github.com/parkervcp/eggs/assets/8878434/d6b0c0b2-7a39-4339-85c1-b11c440bf23f)

### Steps To Reproduce

Step 1: Import egg
Step 2: Install server
Step 3: See errors in the console :)

### Install logs

https://pteropaste.com/sy515br68sec/

**Comment by QuintenQVD0** [comment]
Palworld just like all other steam eggs do not work on arm64

**Comment by rhettp** [comment]
> Palworld just like all other steam eggs do not work on arm64

Ahhh thank you.
