### ISSUE TITLE
[Bug]: Feed The Beast

### ISSUE THREAD

**Issue by KartoniarzEssa** [parkervcp/eggs#2728]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

Start installing server

### Actual Behavior

Installation crash with error "Error: Unable to access jarfile start-server.jar"

### Steps To Reproduce

I tried to install FTB modpack id 100 version id 11655 with java 17 (ghcr.io/pterodactyl/yolks:java_17) and default startup settings seems to don't work. The egg is latest [449577b](https://github.com/parkervcp/eggs/commit/449577ba5bfadc6c1c1f53284775c3e65c14cb2d) from https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/java/ftb/egg-ftb-modpacksch-server.json

### Install logs

There are no install logs generated

**Comment by FirestormeDS** [comment]
its the same for me too on curseforge egg 
it give me : could not find or load main class user_jvm_args.txt

**Comment by QuintenQVD0** [comment]
> its the same for me too on curseforge egg it give me : could not find or load main class user_jvm_args.txt

Completely unrelated as it is an other egg

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> 
> 1.11.5
> ### Wings Version
> 
> 1.11.8
> ### Service
> 
> minecraft
> ### Modified
> 
> No, I did not modify the egg
> ### Expected Behavior
> 
> Start installing server
> ### Actual Behavior
> 
> Installation crash with error "Error: Unable to access jarfile start-server.jar"
> ### Steps To Reproduce
> 
> I tried to install FTB modpack id 100 version id 11655 with java 17 (ghcr.io/pterodactyl/yolks:java_17) and default startup settings seems to don't work. The egg is latest [449577b](https://github.com/parkervcp/eggs/commit/449577ba5bfadc6c1c1f53284775c3e65c14cb2d) from https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/java/ftb/egg-ftb-modpacksch-server.json
> ### Install logs
> 
> There are no install logs generated

no install logs = no help, so you will need to get them

**Comment by FirestormeDS** [comment]
just a small note hehe

**Comment by KartoniarzEssa** [comment]
> > ### Panel Version
> > 1.11.5
> > ### Wings Version
> > 1.11.8
> > ### Service
> > minecraft
> > ### Modified
> > No, I did not modify the egg
> > ### Expected Behavior
> > Start installing server
> > ### Actual Behavior
> > Installation crash with error "Error: Unable to access jarfile start-server.jar"
> > ### Steps To Reproduce
> > I tried to install FTB modpack id 100 version id 11655 with java 17 (ghcr.io/pterodactyl/yolks:java_17) and default startup settings seems to don't work. The egg is latest [449577b](https://github.com/parkervcp/eggs/commit/449577ba5bfadc6c1c1f53284775c3e65c14cb2d) from https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/java/ftb/egg-ftb-modpacksch-server.json
> > ### Install logs
> > There are no install logs generated
> 
> no install logs = no help, so you will need to get them

So what can I do when its not generating them. Its generating in every other installation but not in this

**Comment by KartoniarzEssa** [comment]
![image](https://github.com/parkervcp/eggs/assets/81422890/9b6e75a3-5e98-48d6-81dd-932cbdd0c74e)
Server is instantly going offline not even trying to install. Other eggs works normally
