### ISSUE TITLE
[Egg Request]: Mixpost

### ISSUE THREAD

**Issue by joecasanova** [parkervcp/eggs#2730]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/inovector/mixpost

### Links for the download

https://github.com/inovector/mixpost

### Links for the install docs

https://hub.docker.com/r/inovector/mixpost

**Comment by yesBad** [comment]
This is a whole Laravel application which requires PHP, a DB, Redis, WebServer etc.
It's the same idea as running Pterodactyl inside Pterodactyl, it's just crazy wacky idea.

You're better off running this on the same machine that runs Pterodactyl as we don't support web eggs much here already this is just a high nope.

**Comment by QuintenQVD0** [comment]
Sorry but as Bad stated this is not for in pterodactyl.
