### ISSUE TITLE
[Bug]: <Palworld> seems like rcon is not connectable from outside

### ISSUE THREAD

**Issue by sliely** [parkervcp/eggs#2731]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

steamcmd/palworld

### Modified

No, I did not modify the egg

### Expected Behavior

when I install the server with this egg rcon should be enabled and connectable by default

### Actual Behavior

i can't connect to rcon though can send commands from pterodactyl's console

### Steps To Reproduce

idk just install the server with this egg?

### Install logs

the commands not working

**Comment by parkervcp** [comment]
Did you allocate the port you want to use for rcon as well as update the variable for it?

**Comment by sliely** [comment]
iirc the port is not needed to be allocated? btw it does not fix the issue

**Comment by yesBad** [comment]
port is required to be allocated for the server if you want to access it externally

**Comment by QuintenQVD0** [comment]
> iirc the port is not needed to be allocated? btw it does not fix the issue

For local pterodactyl console use is it not needed, if you want external connection then that port does need to be allocated

**Comment by sliely** [comment]
well i allocated it but still not connectable
