### ISSUE TITLE
[Bug]: Vanilla Bedrock

### ISSUE THREAD

**Issue by petervk** [parkervcp/eggs#2735]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

minecraft bedrock

### Modified

No, I did not modify the egg

### Expected Behavior

I'm able to join my minecraft server from the latest client version.

### Actual Behavior

I get an error that the host is outdated. The client is Minecraft bedrock version 1.20.60 on windows 11 and the host is still running 1.20.50.03. 

Minecraft has issued a newer version of the service (version 1.20.61.01) that is compatable with the 1.20.60 client.  (see this link: https://www.minecraft.net/en-us/download/server/bedrock).

I attempted to restart, and also stop and start the server again but it doesn't seem to recgonize that a newer version of the server is available and it keeps running the old version.

I have the version set to latest.

![image](https://github.com/parkervcp/eggs/assets/33823/cc1ff4c0-76e8-4d48-8fcc-509e703878e7)

### Steps To Reproduce

Version is set to latest.
Restarted server, but it doesn't update.

### Install logs

https://pteropaste.com/c4gkpv4chcky

**Comment by petervk** [comment]
I was able to fix this by backing up the server and reinstalling it, then it pulled down the new version of the server.

**Comment by parkervcp** [comment]
This server doesn't auto update on restart.
