### ISSUE TITLE
[Bug]:  Enshrouded

### ISSUE THREAD

**Issue by Evergrace** [parkervcp/eggs#2736]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Enshrouded

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Install server via egg, connect to server IP, play game

### Actual Behavior

Install server via egg, cannot connect to server, check .json and update localhost to 127.0.0.1, ensure port forwarding is properly set up, still can't connect to server, steam saying no server present at IPv4

### Steps To Reproduce

Install server via egg
Start server
Try to play on server

### Install logs

this command did nothing on my wings server

**Comment by gOOvER** [comment]
Not an Egg issue. Setup your Network correct. Egg works fine

**Comment by QuintenQVD0** [comment]
There is something wrong with your network config as yiu never should have anywhere 127.0.0.1 or localhost. Always a real ip. Local or public.
