### ISSUE TITLE
[Egg Request]: <Arclight/Minecraft>

### ISSUE THREAD

**Issue by shams919** [parkervcp/eggs#2739]
### Does this expand an already existing service

Yes

### Link to a game or software

https://minecraft.net

### Links for the download

https://github.com/IzzelAliz/Arclight

### Links for the install docs

https://github.com/IzzelAliz/Arclight/wiki/Contributing

**Comment by shams919** [comment]
Please add the Arclight Minecraft Egg for Pterodactyl Panel.

**Comment by parkervcp** [comment]
There have been multiple other servers like this and they have all been abandoned. If they ship a jar file you can just have the vanilla egg pull it as a download.

This is the reasoning behind why I am saying no to this.

**Comment by shams919** [comment]
> There have been multiple other servers like this and they have all been abandoned. If they ship a jar file you can just have the vanilla egg pull it as a download.
> 
> This is the reasoning behind why I am saying no to this.

Why? It’s a good software for both plugins and mods

**Comment by ImKringle** [comment]
> > There have been multiple other servers like this and they have all been abandoned. If they ship a jar file you can just have the vanilla egg pull it as a download.
> > This is the reasoning behind why I am saying no to this.
> 
> Why? It’s a good software for both plugins and mods this https://github.com/IzzelAliz/Arclight

> There have been multiple other servers like this and they have all been abandoned

He answered your question lol Hybrid loaders get abandoned, not to mention half the repo is minecraft eggs. Just use the vanilla egg and give it a JAR file, itll boot fine - or make one yourself if so inclined, several eggs in this git have examples for pulling from Git releases
