### ISSUE TITLE
Forge Version name rules changed

### ISSUE THREAD

**Issue by TreeHD** [parkervcp/eggs#274]
Please fill out the information bellow and remove from the line up
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.14
Daemon Version: 0.6.12
Service: minecraft
Modified: no 

Expected Behavior:
Installing Forge 1.14.4

Actual Behavior:

Fetching latest from version 1.14.4
!!! Invalid forge version "" !!!

Steps to Reproduce:

Starup Forge version change to 1.14.4
but 1.12.2 or 1.10.2 is Working Well

**Comment by JayJay1989** [comment]
there is a json where you can find the 'latest' and 'recomended' build for forge.
`https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json`
Its better tahn scrape the html pages

**Comment by parkervcp** [comment]
You want to tell me what the exact issue is. like what version is expected kind of thing?

**Comment by JayJay1989** [comment]
forge changed the version numbers from x.x.x.x > x.x.x. the egg "Forge Minecraft" searches for x.x.x.x which result in a bad downloadlink

**Comment by parkervcp** [comment]
Am I safe to assume this is the vanilla forge egg and not the forge-generic egg?

**Comment by JayJay1989** [comment]
yes

**Comment by SeaLife** [comment]
Hey guys, using the JSON above would make much more sense, but as a "quick" workaround, you can modify the regex to match both versions.

```
#!/bin/ash
# Forge Installation Script
#
# Server Files: /mnt/server
apk update
apk add curl

if [ -z "$MC_VERSION" ] || [ "$MC_VERSION" == "latest" ]; then
  FORGE_VERSION=$(curl -sl https://files.minecraftforge.net/maven/net/minecraftforge/forge/ | grep -A1 Latest | grep  -o -e '[1]\.[0-9][0-9]\?\.\?[0-9]\?[0-9] - [0-9][0-9]\.[0-9][0-9]\.[0-9]\?[0-9]\.[0-9][0-9][0-9][0-9]' | sed 's/ //g')
else
  FORGE_VERSION=$(curl -sl https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_$MC_VERSION.html | grep -A1 Latest | grep  -o -e '[1]\.[0-9][0-9]\?\.\?[0-9]\?[0-9] - [0-9.]\+' | sed 's/ //g')
fi

cd /mnt/server

echo -e "\nDownloading Forge Version $FORGE_VERSION\n"
curl -sS https://files.minecraftforge.net/maven/net/minecraftforge/forge/$FORGE_VERSION/forge-$FORGE_VERSION-installer.jar -o installer.jar

echo -e "\nInstalling forge server usint the installer jar file.\n"
java -jar installer.jar --installServer

mv forge-$FORGE_VERSION $SERVER_JARFILE

echo -e "\nDeleting installer jar file and cleaning up.\n"
rm -rf installer.jar
```

**Comment by parkervcp** [comment]
I am working on on the jq to capture versions and other stuff right now. It's a bit of a mess due to 1.7.10 versions being kind of stupid too.

**Comment by parkervcp** [comment]
@treeHD can you look at this too?
