### ISSUE TITLE
[Install Bug]: Subnautica Nitrox Mod :  No such file or directory.

### ISSUE THREAD

**Issue by NakaNakaHehe** [parkervcp/eggs#2740]
### Panel Version

1.11.5

### Wings Version

???

### Service

Subnautica

### Modified

No, I did not modify the egg

### Expected Behavior

Install and works

### Actual Behavior

Need an update to 1.7.1.0 ?

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mono_latest 
Digest: sha256:9da4e508962e3503c0faf15d867ea728b0e4e79399d82d306d2a2d6b51968853 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:9da4e508962e3503c0faf15d867ea728b0e4e79399d82d306d2a2d6b51968853 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mono_latest 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

Install and runs

### Install logs

didn't work

**Comment by parkervcp** [comment]
Your install failed. Do you have the install logs?

**Comment by NakaNakaHehe** [comment]
Do i execute this :
tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99
In my console ?
Bcz nothing happen

**Comment by NakaNakaHehe** [comment]
i reinstalled it like 20 times

**Comment by NakaNakaHehe** [comment]
container@pterodactyl~ Server marked as offline...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
curl is already the newest version (7.74.0-1.3+deb11u11).
libstdc++6 is already the newest version (10.2.1-6).
libstdc++6 set to manually installed.
jq is already the newest version (1.6-2.1).
unzip is already the newest version (6.0-26+deb11u1).
libsdl2-2.0-0:i386 is already the newest version (2.0.14+dfsg2-3+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
steamcmd.sh
linux32/steamcmd
linux32/steamerrorreporter
linux32/libstdc++.so.6
linux32/crashhandler.so
### You did not specify a Steam Guardcode
### A new one should be send to you shortly
### Enter it in the startup-config after this installation is finished and reinstall the Server
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 59782 KB)...
[  0%] Downloading update (0 of 59782 KB)...
[  0%] Downloading update (0 of 59782 KB)...
[  0%] Downloading update (0 of 59782 KB)...
[  0%] Downloading update (1039 of 59782 KB)...
[  1%] Downloading update (3241 of 59782 KB)...
[  5%] Downloading update (5229 of 59782 KB)...
[  8%] Downloading update (7142 of 59782 KB)...
[ 11%] Downloading update (8594 of 59782 KB)...
[ 14%] Downloading update (9896 of 59782 KB)...
[ 16%] Downloading update (11208 of 59782 KB)...
[ 18%] Downloading update (12662 of 59782 KB)...
[ 21%] Downloading update (13963 of 59782 KB)...
[ 23%] Downloading update (15274 of 59782 KB)...
[ 25%] Downloading update (16722 of 59782 KB)...
[ 27%] Downloading update (18030 of 59782 KB)...
[ 30%] Downloading update (19335 of 59782 KB)...
[ 32%] Downloading update (20640 of 59782 KB)...
[ 34%] Downloading update (22093 of 59782 KB)...
[ 36%] Downloading update (23405 of 59782 KB)...
[ 39%] Downloading update (24709 of 59782 KB)...
[ 41%] Downloading update (26140 of 59782 KB)...
[ 43%] Downloading update (27449 of 59782 KB)...
[ 45%] Downloading update (28753 of 59782 KB)...
[ 48%] Downloading update (30192 of 59782 KB)...
[ 50%] Downloading update (31492 of 59782 KB)...
[ 52%] Downloading update (32798 of 59782 KB)...
[ 54%] Downloading update (34105 of 59782 KB)...
[ 57%] Downloading update (35559 of 59782 KB)...
[ 59%] Downloading update (36845 of 59782 KB)...
[ 61%] Downloading update (38160 of 59782 KB)...
[ 63%] Downloading update (39606 of 59782 KB)...
[ 66%] Downloading update (40949 of 59782 KB)...
[ 68%] Downloading update (41598 of 59782 KB)...
[ 69%] Downloading update (42252 of 59782 KB)...
[ 70%] Downloading update (42975 of 59782 KB)...
[ 71%] Downloading update (43622 of 59782 KB)...
[ 72%] Downloading update (44274 of 59782 KB)...
[ 74%] Downloading update (44990 of 59782 KB)...
[ 75%] Downloading update (45633 of 59782 KB)...
[ 76%] Downloading update (46281 of 59782 KB)...
[ 77%] Downloading update (46999 of 59782 KB)...
[ 78%] Downloading update (47645 of 59782 KB)...
[ 79%] Downloading update (48291 of 59782 KB)...
[ 80%] Downloading update (49005 of 59782 KB)...
[ 81%] Downloading update (49657 of 59782 KB)...
[ 83%] Downloading update (50309 of 59782 KB)...
[ 84%] Downloading update (51027 of 59782 KB)...
[ 85%] Downloading update (51682 of 59782 KB)...
[ 86%] Downloading update (52330 of 59782 KB)...
[ 87%] Downloading update (53046 of 59782 KB)...
[ 88%] Downloading update (53692 of 59782 KB)...
[ 89%] Downloading update (54410 of 59782 KB)...
[ 91%] Downloading update (55051 of 59782 KB)...
[ 92%] Downloading update (55705 of 59782 KB)...
[ 93%] Downloading update (56419 of 59782 KB)...
[ 94%] Downloading update (57068 of 59782 KB)...
[ 95%] Downloading update (57722 of 59782 KB)...
[ 96%] Downloading update (58439 of 59782 KB)...
[ 97%] Downloading update (59093 of 59782 KB)...
[ 98%] Downloading update (59748 of 59782 KB)...
[ 99%] Downloading update (59782 of 59782 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
tid(289) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
Logging directory: '/mnt/server/Steam/logs'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
tid(301) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
Logging directory: '/mnt/server/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mono_latest 
Digest: sha256:9da4e508962e3503c0faf15d867ea728b0e4e79399d82d306d2a2d6b51968853 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mono_latest 
Digest: sha256:9da4e508962e3503c0faf15d867ea728b0e4e79399d82d306d2a2d6b51968853 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by gOOvER** [comment]
you need to login to steam, to download the game

**Comment by NakaNakaHehe** [comment]
okay it worked, thanks
