### ISSUE TITLE
[Egg Request]: <Arclight Minecraft>

### ISSUE THREAD

**Issue by shams919** [parkervcp/eggs#2741]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/IzzelAliz/Arclight/releases

### Links for the download

https://github.com/IzzelAliz/Arclight

### Links for the install docs

https://github.com/IzzelAliz/Arclight/wiki/Contributing

**Comment by QuintenQVD0** [comment]
Duplicate #2739
