### ISSUE TITLE
[Bug]: steam_cmd/icarus

### ISSUE THREAD

**Issue by risingfish** [parkervcp/eggs#2742]
### Panel Version

1.11.8

### Wings Version

1.11.8

### Service

game_eggs/steamcmd_servers/icarus

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play - Just like the default test states

### Actual Behavior

The game egg does not appear to create a running server. It does not appear in any of the game lists, and I cannot connect to it locally on my LAN. This is either an incomplete egg, or it is not documented enough to be able to stand up a running server.

### Steps To Reproduce

Step 1 Install the egg
Step 2 Configure a new server and start it

### Install logs

https://pastebin.com/rUfecV2w

**Comment by risingfish** [comment]
Not sure what or why but it is working now.

**Comment by gOOvER** [comment]
Sounds Like a Problem with your Network and Not really an Egg issue
