### ISSUE TITLE
[Bug]: <Egg Name>

### ISSUE THREAD

**Issue by Gelvey** [parkervcp/eggs#2746]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

generic-languages/python

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Press the start button, it automatically installs the python libraries listed in "requirements.txt" and starts the script.

### Actual Behavior

Pressed the start button, didn't install any python libraries and therefore failed to start the script (I have tried starting the script locally with the python libraries installed and have had no problems.)

### Steps To Reproduce

When installing, set python version to latest (3.11), upload your ".py" file and "requirements.txt" file and attempt to start the script.
![image](https://github.com/parkervcp/eggs/assets/68216784/8896b1ba-a6b2-4feb-b8d0-606633061988)

### Install logs

https://pteropaste.com/8368g2buc3r7/

**Comment by QuintenQVD0** [comment]
You gave it 100 mb
