### ISSUE TITLE
[Egg Request]: Myth of Empires

### ISSUE THREAD

**Issue by ValhallaCommunityOfficial** [parkervcp/eggs#2747]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1371580/Myth_of_Empires/

### Links for the download

https://steamdb.info/app/1794810/

### Links for the install docs

On Official discord. info in comments

**Comment by ValhallaCommunityOfficial** [comment]
For single and cluster servers, documents linked within dedi-server channel
https://discord.gg/mythofempires

**Comment by QuintenQVD0** [comment]
> For single and cluster servers, document files linked within dedi-server channel. I'm assuming 2 eggs would need to be made. 1 for single server and 1 for cluster? Not really sure how that all works. https://discord.gg/mythofempires

A single server egg may will be made. A cluster is to be honnest not going to happen.

**Comment by ValhallaCommunityOfficial** [comment]
Will it be made with proton or wine? Fingers crossed for proton!

**Comment by QuintenQVD0** [comment]
> Will it be made with proton or wine? Fingers crossed for proton! Wine is just a resource hog..

If it runs with proton and you prefer then I guess we can do that. Us game owership needed?

**Comment by QuintenQVD0** [comment]
It seems like the servet is shiped with the game what is not direct an issue but the only way to start it is thru a gui what will not work

**Comment by QuintenQVD0** [comment]
Buy they do have a dedicated app id? But no docs on how to use it? Thats going to be fun.

**Comment by ValhallaCommunityOfficial** [comment]
> @ValhallaCommunityOfficial I have since release a working egg. You can pm me over Discord. I will not make it public for some reasons

Thank you. Not sure of your discord ID but mine is kodeman

**Comment by ValhallaCommunityOfficial** [comment]
Not sure if they added anymore information but They posted this document to their website. 
https://www.mythofempires.com/newsall/news/2024/0220/556.html
