### ISSUE TITLE
create custom egg for my bot teamspeak 3 ?

### ISSUE THREAD

**Issue by jakub96124124** [parkervcp/eggs#276]
create custom egg for my bot teamspeak 3 ? 
 I will pay for the creation.

**Comment by DomiiBunn** [comment]
There is already a team-speak egg if that's what you are talking about. Whoever if you want a custom bot it is recommended to hit up the discord server for the panel to get HELP with making one os someone might help you out and make it. Whoever I don't belie the issues section is a good place for this.

**Comment by jakub96124124** [comment]
but i need to make an egg for my bot which is meant for ts3

**Comment by DomiiBunn** [comment]
Again this is not a bug nor an issue. This is not a place for this.

**Comment by parkervcp** [comment]
As you didn't fill out anything like I have requested I am closing this out.
