### ISSUE TITLE
[Bug]: Open Fortress

### ISSUE THREAD

**Issue by OhaDerErste** [parkervcp/eggs#2763]
### Panel Version

1.11.5

### Wings Version

1.11

### Service

Open Fortress

### Modified

No, I did not modify the egg

### Expected Behavior

Server should install and start sucessfully

### Actual Behavior

Egg cant download files required for the server to run and thus failes to install it propperly

### Steps To Reproduce

1. Download and import egg
2. Create server and install server

### Install logs

https://pteropaste.com/tvnrspt6nn8u/

**Comment by parkervcp** [comment]
Are you running this on an Ubuntu based host? It looks like there is a DNS failure here.

**Comment by parkervcp** [comment]
Nevermind it looks like the URL toast.openfortress.fun isn't valid anymore.

**Comment by OhaDerErste** [comment]
yeah. looks like they moved it. Haven't asked about where they moved it yet

**Comment by OhaDerErste** [comment]
Got this answer from their discord server
![image](https://github.com/parkervcp/eggs/assets/77100649/df489243-60d6-4fa3-b7f1-789600dcf543)
