### ISSUE TITLE
[Install Bug]: BeamMP

### ISSUE THREAD

**Issue by Crazys-Corner** [parkervcp/eggs#2764]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

beamMP

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play

### Actual Behavior

container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Starting installation process, this could take a few minutes...
Using latest BeamMP server version
Running curl -sSL  -o BeamMP-Server
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
chmod: cannot access 'BeamMP-Server': No such file or directory
-----------------------------------------
Installation completed...
-----------------------------------------
When you try to start it:

[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:4e0ebeab6b56219588d650c3a57ecbc3f6ebf1e99d0850a6ad07c0b1af373236 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./BeamMP-Server
/entrypoint.sh: line 13: ./BeamMP-Server: No such file or directory

### Steps To Reproduce

Step 1: Create a server

Step 2: Once installation starts, wait for it to break. 

### Install logs

https://pteropaste.com/kggv42pn5x29/

**Comment by QuintenQVD0** [comment]
Your egg is old as it still has. A match variable.
