### ISSUE TITLE
[Bug]: PocketMine-MP

### ISSUE THREAD

**Issue by lezetho** [parkervcp/eggs#2767]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

eggs/game_eggs/minecraft/bedrock

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, have it download, run successfully.

### Actual Behavior

Got error:
`Downloading latest PHP  binary for PM5
#=#=#                                                                        
                                                                             ##O#-#                                                                       
##O=#  #                                                                     

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
parse error: Invalid numeric literal at line 1, column 10
(23) Failed writing body
Downloading PM5 from 
curl: (3) URL using bad/illegal format or missing URL
Configuring php.ini
find: 'bin': No such file or directory
grep: bin/php7/bin/php.ini: No such file or directory
/mnt/install/install.sh: line 26: bin/php7/bin/php.ini: No such file or directory`

### Steps To Reproduce

Step 1: Install latest PMMP code

### Install logs

https://pastebin.com/KsgxhWxi

**Comment by QuintenQVD0** [comment]
@lezetho Post full install logs (change the command to grep more lines) as I need this from the top as there is some importan information there

**Comment by lezetho** [comment]
@QuintenQVD0 alright, here: https://pastebin.com/FSvKNSdx

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 alright, here: https://pastebin.com/FSvKNSdx

thats still no export as the variables are missing

**Comment by lezetho** [comment]
I'm sorry but I'm kinda new to pterodactyl. How would I do that?

**Comment by QuintenQVD0** [comment]
> I'm sorry but I'm kinda new to pterodactyl. How would I do that?

`tail -n 5000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99`

**Comment by QuintenQVD0** [comment]
@lezetho I see the issue, their API site is ofline , nothing we can do for that. THats something they have to fix

**Comment by lezetho** [comment]
Is https://apidoc.pmmp.io their API website?

**Comment by QuintenQVD0** [comment]
> Is https://apidoc.pmmp.io their API website?

No there download API website  https://update.pmmp.io/api

**Comment by lezetho** [comment]
Ah I see. Thank you.

**Comment by lezetho** [comment]
@QuintenQVD0 Just got word that it was fixed by the way!

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Just got word that it was fixed by the way!

its up, hit reinstall and it will work
