### ISSUE TITLE
[Bug]: Ark Server Egg: rcon startup

### ISSUE THREAD

**Issue by XiNaru** [parkervcp/eggs#2768]
### Panel Version

1.11.5

### Wings Version

idk latest

### Service

Ark Survival Evolved

### Modified

No, I did not modify the egg

### Expected Behavior

Server must start correctly

### Actual Behavior

Success. Downloaded item 2715085686 to "/home/container/Steam/steamapps/workshop/content/346110/2715085686" (906187 bytes) waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: dial tcp 127.0.0.1:27020: connect: connection refused
waiting for rcon connection...
cli: auth: rcon: rcon: read packet size: read tcp 127.0.0.1:35436->127.0.0.1:27020: i/o timeout
waiting for rcon connection...
Waiting commands for 127.0.0.1:27020 (or type :q to exit)

### Steps To Reproduce

Ähm server fresh installed?

### Install logs

https://pteropaste.com/rfmis9fc12m4

**Comment by XiNaru** [comment]
https://images.xinaru.de/index.php/s/yeyBMnormPAqoPz/preview

thats all my 4 ports
i have make the ark server on an second ip because palsworld used 7777 to.

https://images.xinaru.de/index.php/s/ff3cipgTtYXS43e/preview

**Comment by Nykolos** [comment]
Just wait a few minutes, thats normal

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/ark_survival_evolved#rcon

"You will see RCON connection refused messages until the server has successfully started"

When this gets posted by the console: "Waiting commands for 127.0.0.1:27020 (or type :q to exit)"

The server is online and available

**Comment by QuintenQVD0** [comment]
Waiting commands for 127.0.0.1:27020 (or type :q to exit)
 
 means running, so if you have allocated all ports then you should be able to join (you may have to use the query port)

**Comment by XiNaru** [comment]
> Waiting commands for 127.0.0.1:27020 (or type :q to exit)
> 
> means running, so if you have allocated all ports then you should be able to join (you may have to use the query port)

okay sry..then i have understand a bit wrong. i had put the wrong port in the steam server list :P normal instead of query, now it works. thanks and sry for the time
