### ISSUE TITLE
[Egg Request]:  Wii dwc server emulator

### ISSUE THREAD

**Issue by tobywhiting10** [parkervcp/eggs#2769]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/barronwaffles/dwc_network_server_emulator

### Links for the download

https://github.com/barronwaffles/dwc_network_server_emulator/wiki

### Links for the install docs

https://github.com/barronwaffles/dwc_network_server_emulator/wiki

**Comment by yesBad** [comment]
Does not look possible in Pterodactyl.

**Comment by QuintenQVD0** [comment]
Not possible
