### ISSUE TITLE
[Egg Request]: VEIN - Linux

### ISSUE THREAD

**Issue by ValhallaCommunityOfficial** [parkervcp/eggs#2777]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/1857950/VEIN/

### Links for the download

https://steamdb.info/depot/2131402/

### Links for the install docs

https://ramjet.notion.site/Server-Hosting-85f92f43f32548c1b5b33797ddf456ad

**Comment by ValhallaCommunityOfficial** [comment]
There's a wine egg for this game which no longer seems to work with most recent update. Figured I'd submit this as they support linux now. Wasnt sure if I should select yes or now on existing service so i just selected yes.

**Comment by gOOvER** [comment]
https://github.com/parkervcp/eggs/pull/2515

**Comment by QuintenQVD0** [comment]
Yea I know I have one in PR but that is not yet merged so the answer should have been NO

**Comment by QuintenQVD0** [comment]
and that egg is already using native linux @ValhallaCommunityOfficial

**Comment by ValhallaCommunityOfficial** [comment]
Ah, sorry about that. Can delete this. I'll report the issue on the other thread.

**Comment by QuintenQVD0** [comment]
> Ah, sorry about that. Can delete this. I'll report the issue on the other thread.

Just try the egg, if changes are needed then post on that PR, if it works then also comment so it can get merged
