### ISSUE TITLE
[Bug]: Palworld commands after changing password

### ISSUE THREAD

**Issue by TheColin21** [parkervcp/eggs#2778]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

palworld

### Modified

No, I did not modify the egg

### Expected Behavior

After changing the admin password the game accepts the change and commands like clicking the stop button work as intended.

### Actual Behavior

The game seems to ignore it's startup argument `-adminpassword` and (as an example) reacts to a stop signal with 'cli: execute: auth: rcon: authentication failed'

### Steps To Reproduce

Create a server
Change its admin password
Try executing commands with the new pass

### Install logs

Installation finished successfully but the installer log includes sensitive data which I will not post here.

**Comment by QuintenQVD0** [comment]
What is your startup?

**Comment by TheColin21** [comment]
The exact one from the current egg.
Just did the egg update as described in the repo including making sure the startup matches and reinstalling the server.

Am 4. März 2024 10:55:41 MEZ schrieb Quinten ***@***.***>:

**Comment by QuintenQVD0** [comment]
> The exact one from the current egg. Just did the egg update as described in the repo including making sure the startup matches and reinstalling the server. Am 4. März 2024 10:55:41 MEZ schrieb Quinten ***@***.***>:
> […](#)
> What is your startup? -- Reply to this email directly or view it on GitHub: [#2778 (comment)](https://github.com/parkervcp/eggs/issues/2778#issuecomment-1976179908) You are receiving this because you authored the thread. Message ID: ***@***.***>

Show the config file and the startup tab

**Comment by TheColin21** [comment]
[PalWorldSettings.ini.txt](https://github.com/parkervcp/eggs/files/14480025/PalWorldSettings.ini.txt)
![Screenshot_20240304-111231~2](https://github.com/parkervcp/eggs/assets/24256864/4c7904b2-20c6-407c-a574-7424b8883859)
![Screenshot_20240304-111153](https://github.com/parkervcp/eggs/assets/24256864/b16f8db2-20e5-4e74-bb5b-6c7cfe9b1f65)

**Comment by TheColin21** [comment]
![Screenshot_20240304-111153~2](https://github.com/parkervcp/eggs/assets/24256864/2378f9bd-1750-49c1-be11-49ddfd43dc94)
![Screenshot_20240304-111231~2](https://github.com/parkervcp/eggs/assets/24256864/cff4dcdb-86a8-47b8-a071-5d0e19c429e6)
[PalWorldSettings.ini.txt](https://github.com/parkervcp/eggs/files/14480051/PalWorldSettings.ini.txt)

**Comment by QuintenQVD0** [comment]
The password is set in the file and in the startup. Their is notthing more we can do.

**Comment by Ballaual** [comment]
I just created a new server on my machine using the latest version and everything working out of the box.
When i set a new adminpassword the config gets updated and i am able to connect throught rcon and send commands via console.

**Comment by TheColin21** [comment]
> I just created a new server on my machine using the latest version and everything working out of the box. When i set a new adminpassword the config gets updated and i am able to connect throught rcon and send commands via console.

Thanks I might try and create a new one and copy the world.

**Comment by Ballaual** [comment]
Just btw, the -adminpassword in the startup is in theory superfluous since the config parser writes the variables into the config.
As well the -servername and -serverpassword. Wondering if we should remove them? @QuintenQVD0

**Comment by QuintenQVD0** [comment]
> Just btw, the -adminpassword in the startup is in theory superfluous since the config parser writes the variables into the config. As well the -servername and -serverpassword. Wondering if we should remove them? @QuintenQVD0

They read from the same variable so it is not really an issue, its now redundant but if they ever break the startup flags then the config still works.

**Comment by QuintenQVD0** [comment]
This is an issue with their server engine, complain to them, nothing we can do about it.
