### ISSUE TITLE
it will not make a server Fivem

### ISSUE THREAD

**Issue by fisk2004** [parkervcp/eggs#278]
When ever i try to make a fivem server it will not work the server is not being made and its does not say that you server has been made its just like there is no fivem server to make

**Comment by DomiiBunn** [comment]
Hi could you please provide the following

- Wings log `cd /srv/daemon/ && npm run diagnostics`
- The exact egg you have in the panel (Admin panel -> nests -> (your nest) -> (your egg) -> export
- A screenshot of your server configuration page
- Panel and daemon version no.

Also take a read trough this and see if it might be your issue fix for you. #233

**Comment by fisk2004** [comment]
i dont know what you mean my server dont want to make a fivem server

**Comment by parkervcp** [comment]
Did you put in the server version? The latest fivem changes on their end broke my script for getting release versions

**Comment by fisk2004** [comment]
no i just download the fivem thing today

**Comment by NgLoader** [comment]
Restart the deamon

**Comment by fisk2004** [comment]
i have tryde to restart the deamon

**Comment by parkervcp** [comment]
This is probably you missing a variable on setup.

You need to get the latest linux server version from the fivem artifacts repo. and put that in while setting up the server.

**Comment by parkervcp** [comment]
I have done a fresh install to see what the issue may be and I am not seeing any issues.

If you do report an issue again. Make sure you have updated the egg first.

There is no good fix and that one in the previous github issue is one that is only good for one single release.
