### ISSUE TITLE
[Egg Request]: Kodbox

### ISSUE THREAD

**Issue by TerraPlayz** [parkervcp/eggs#2781]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/kalcaddle/kodbox

### Links for the download

https://github.com/kalcaddle/kodbox

### Links for the install docs

https://github.com/kalcaddle/kodbox?tab=readme-ov-file#install

**Comment by yesBad** [comment]
This is just a website, not really something Pterodactyl is meant for tbf-

**Comment by parkervcp** [comment]
I am saying no to this. it requires both  webserver and php. The standalone services that have their own webservers built in are about as far as I go.

**Comment by Omxpro** [comment]
> I am saying no to this. it requires both webserver and php. The standalone services that have their own webservers built in are about as far as I go.

Thanks
