### ISSUE TITLE
[Install Bug]: <Subnautica Nitrox Mod> : No such file or directory

### ISSUE THREAD

**Issue by ZimPoPo** [parkervcp/eggs#2782]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Subnautica

### Modified

No, I did not modify the egg

### Expected Behavior

install the server, and launch it.

### Actual Behavior

Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:650f65aef56ad38eec69c01bf6c927d6cf6c5d6b23b23a6cd32f1d271382728e 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mono_latest 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:mono_latest 
Digest: sha256:650f65aef56ad38eec69c01bf6c927d6cf6c5d6b23b23a6cd32f1d271382728e 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ mono ./nitrox/NitroxServer-Subnautica.exe
Cannot open assembly './nitrox/NitroxServer-Subnautica.exe': No such file or directory.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

Step 1: install the egg (subnautica_nitrox_mod)
Step 2: create a server and write your account username and your password
Step 3: I have disable Steam Guard on my steam account
Step 4: launch the install
Step 5: launch the server

### Install logs

https://pastebin.com/dJ0J9xfU

**Comment by parkervcp** [comment]
Reading the install script your install should have failed. You need to have a user with a valid steamguard code to install the server according to the script.

**Comment by ZimPoPo** [comment]
I have resolve the probleme thx
