### ISSUE TITLE
[Bug]: <Arma Reforger>

### ISSUE THREAD

**Issue by rainerstudios** [parkervcp/eggs#2783]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Arma Reforger

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, add mods on the config file restart server starts

### Actual Behavior

Server crushed when a lot of mods are added to the config file 
![image](https://github.com/parkervcp/eggs/assets/21259511/1e40f66f-8545-4e9a-903d-cfdb9162ec63)

BACKEND      : MEP civil: ==>__________________ 10% 73/709 MB
 BACKEND      : RHS - Status Quo: ======>______________ 30% 1268/4097 MB
 BACKEND      : Download speed 44287.80 KB/s
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Curl error=Failed writing received data to disk/application
BACKEND   (E): Fragmentizer: Download error (fragment 622/1443)
BACKEND   (E): Fragmentizer: Download error (fragment 41/3572)
BACKEND   (E): Fragmentizer: Retrying download from fragment 41/3572
BACKEND   (E): Fragmentizer: Retrying download from fragment 621/1443

### Steps To Reproduce

install server 
add this on the mods section of the config.json file 

https://pastebin.com/mfyzch3R

### Install logs

https://pteropaste.com/6ngpo2n8ew6i/

**Comment by parkervcp** [comment]
This says that it has failed writing data to disk. Is the disk full?

**Comment by rainerstudios** [comment]
No, I have 80GB allocated some mods gets installed qnd the disk gets to about 10GB/80GB of disk usage

**Comment by QuintenQVD0** [comment]
This is a steam issue, anything above 3 GB will fail to download for mods

**Comment by gOOvER** [comment]
> This is a steam issue, anything above 3 GB will fail to download for mods

No, because Steam reforger dont use Steam Workshop. They have their own Workshop for reforger. The devs must fix that shit

**Comment by gOOvER** [comment]
@rainerstudios i told you allready, that this is not an egg issue. Pls contact the devs to fix this

**Comment by gOOvER** [comment]
> This says that it has failed writing data to disk. Is the disk full?

`BACKEND (E): Curl error=Failed writing received data to disk/application`

Curl Bug: - > https://github.com/curl/curl/pull/12340

**Comment by QuintenQVD0** [comment]
I am closing this as this is because the devs implementation of their own mod downloader is bad. Complain to them
