### ISSUE TITLE
[Egg Request]: Jan.ai

### ISSUE THREAD

**Issue by Omxpro** [parkervcp/eggs#2785]
### Does this expand an already existing service

Yes

### Link to a game or software

https://jan.ai/

### Links for the download

https://jan.ai/guides/install/

### Links for the install docs

https://jan.ai/guides/install/

**Comment by gOOvER** [comment]
nothing for ptero, since you Install a deb file

**Comment by vanderlpp** [comment]
but it can be installed via Docker too. Wouldn't it be possible to use it on the pterodactyl?

**Comment by Omxpro** [comment]
It would be pretty sure.and since it's a deb file it can be installed during the install process

**Comment by gOOvER** [comment]
> It would be pretty sure.and since it's a deb file it can be installed during the install process

not really. it must beinstalled in the image ;). The installscript is an own container only for install

**Comment by gOOvER** [comment]
> but it can be installed via Docker too. Wouldn't it be possible to use it on the pterodactyl?

no, because it needs a running minio. So, its not possible in Ptero

**Comment by QuintenQVD0** [comment]
This needs an s3 service to also run in the same container. What pterodactyl is not made for. It can use an external s3 service but an egg should work standalone
