### ISSUE TITLE
Beammp egg can't install just says no directory for Beammp-server

### ISSUE THREAD

**Issue by Bulletz4Me** [parkervcp/eggs#2788]
### Panel Version

1.11.8

### Wings Version

1.18.5

### Service

Beammp

### Modified

No, I did not modify the egg

### Expected Behavior

you input the auth key for beam and click create and it wont even start to because it has some issue with the beammp-server file it most likely can't download it since they changed the file name and how its downloaded 
![Untitled](https://github.com/parkervcp/eggs/assets/108331081/c2784e4e-950f-4361-a729-d8972456e857)

### Actual Behavior

just wont install any of the files it seems to only make the config file and thats it other people are having the issue with the egg too 

### Steps To Reproduce

just try and install a beam server with the egg supplied on pterodactyl official eggs on github and it does the issue

### Install logs

https://pteropaste.com/wsglda93rurk

**Comment by QuintenQVD0** [comment]
You still have a MATCH variable what means your egg is old
