### ISSUE TITLE
7DTD: Configuration not parsed correctly

### ISSUE THREAD

**Issue by msgerbs** [parkervcp/eggs#279]
Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: 7dtd
Modified: no

Expected Behavior: Server starts on configured port (26900)

Actual Behavior: Server does not start, and logs an error parsing config.

`2019-08-11T12:28:03 0.161 ERR Error parsing configfile: 
2019-08-11T12:28:03 0.161 EXC Expected >, but found n [110]  Line 74, position 56.
XmlException: Expected >, but found n [110]  Line 74, position 56.
  at Mono.Xml2.XmlTextReader.ExpectAfterWhitespace (Char c) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadEndTag () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.ReadNode (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.Load (System.Xml.XmlReader xmlReader) [0x00000] in <filename unknown>:0 
  at GameStartupHelper.LoadConfigFile (System.String _filename) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Logger:masterLogException(Exception)
Logger:Exception(Exception)
Log:Exception(Exception)
GameStartupHelper:LoadConfigFile(String)
GameStartupHelper:ParseCommandLine(String[])
GameManager:Awake()
 
(Filename:  Line: -1)`

Steps to Reproduce: Create a new server, allocate a port, RAM, etc, change nothing else. Start server. Server will hang forever at "Waiting for telnet". /home/container/logs/latest.log contains above error.

The issue is that the ServerPort config entry is not being parsed correctly. It ends up looking like this:
`  <property name="ServerPort">value="26900"</property name="ServerPort">`

but it should look like this:

`  <property name="ServerPort" value="26900"/>`

**Comment by msgerbs** [comment]
Looks like the xml parsing was removed, then inadvertently re-added in #264 ?

**Comment by parkervcp** [comment]
That's because xml is garbage and impossible to actually parse

**Comment by parkervcp** [comment]
@msgerbs please check the PR out.

**Comment by msgerbs** [comment]
Sweet, I'll check it out tomorrow.

**Comment by msgerbs** [comment]
Sorry, I got busy. Unfortunately this did not work either. The end result is now this:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root>
  <root>
    <root>
      <root>
        <ServerSettings>
          <property name="ServerName" value="My Game Host"/>
          <property name="ServerDescription" value="A 7 Days to Die server"/>
          <property name="ServerWebsiteURL" value=""/>
          <property name="ServerPassword" value=""/>
          <property name="ServerLoginConfirmationText" value=""/>
          <property name="ServerPort" value="26901"/>
          <property name="ServerVisibility" value="2"/>
          <property name="ServerDisabledNetworkProtocols" value="SteamNetworking"/>
          <property name="ServerMaxPlayerCount" value="8"/>
          <property name="ServerReservedSlots" value="0"/>
          <property name="ServerReservedSlotsPermission" value="100"/>
          <property name="ServerAdminSlots" value="0"/>
          <property name="ServerAdminSlotsPermission" value="0"/>
          <property name="ControlPanelEnabled" value="false"/>
          <property name="ControlPanelPort" value="8083"/>
          <property name="ControlPanelPassword" value="CHANGEME"/>
          <property name="TelnetEnabled" value="true"/>
          <property name="TelnetPort" value="8081"/>
          <property name="TelnetPassword" value=""/>
          <property name="TelnetFailedLoginLimit" value="10"/>
          <property name="TelnetFailedLoginsBlocktime" value="10"/>
          <property name="TerminalWindowEnabled" value="true"/>
          <property name="AdminFileName" value="serveradmin.xml"/>
          <property name="EACEnabled" value="true"/>
          <property name="HideCommandExecutionLog" value="0"/>
          <property name="MaxUncoveredMapChunksPerPlayer" value="131072"/>
          <property name="PersistentPlayerProfiles" value="false"/>
          <property name="GameWorld" value="Navezgane"/>
          <property name="WorldGenSeed" value="asdf"/>
          <property name="WorldGenSize" value="4096"/>
          <property name="GameName" value="My Game"/>
          <property name="GameMode" value="GameModeSurvival"/>
          <property name="GameDifficulty" value="2"/>
          <property name="BlockDamagePlayer" value="100"/>
          <property name="BlockDamageAI" value="100"/>
          <property name="BlockDamageAIBM" value="100"/>
          <property name="XPMultiplier" value="100"/>
          <property name="PlayerSafeZoneLevel" value="5"/>
          <property name="PlayerSafeZoneHours" value="5"/>
          <property name="BuildCreate" value="false"/>
          <property name="DayNightLength" value="60"/>
          <property name="DayLightLength" value="18"/>
          <property name="DropOnDeath" value="0"/>
          <property name="DropOnQuit" value="0"/>
          <property name="BedrollDeadZoneSize" value="15"/>
          <property name="MaxSpawnedZombies" value="60"/>
          <property name="MaxSpawnedAnimals" value="50"/>
          <property name="EnemySpawnMode" value="true"/>
          <property name="EnemyDifficulty" value="0"/>
          <property name="ZombieMove" value="0"/>
          <property name="ZombieMoveNight" value="3"/>
          <property name="ZombieFeralMove" value="3"/>
          <property name="ZombieBMMove" value="3"/>
          <property name="BloodMoonFrequency" value="7"/>
          <property name="BloodMoonRange" value="0"/>
          <property name="BloodMoonWarning" value="8"/>
          <property name="BloodMoonEnemyCount" value="8"/>
          <property name="LootAbundance" value="100"/>
          <property name="LootRespawnDays" value="30"/>
          <property name="AirDropFrequency" value="72"/>
          <property name="AirDropMarker" value="false"/>
          <property name="PartySharedKillRange" value="100"/>
          <property name="PlayerKillingMode" value="3"/>
          <property name="LandClaimCount" value="1"/>
          <property name="LandClaimSize" value="41"/>
          <property name="LandClaimDeadZone" value="30"/>
          <property name="LandClaimExpiryTime" value="3"/>
          <property name="LandClaimDecayMode" value="0"/>
          <property name="LandClaimOnlineDurabilityModifier" value="4"/>
          <property name="LandClaimOfflineDurabilityModifier" value="4"/>
        </ServerSettings>
      </root>
    </root>
  </root>
  <ServerPort>26900</ServerPort>
</root>`

**Comment by msgerbs** [comment]
Sorry, I realized that I am an idiot and forgot to reboot the node. The code you provided simply makes no changes to the config. I was able to get it working by changing the config block to this: 

```
{
    "serverconfig.xml": {
        "parser": "file",
        "find": {
            "    <property name=\"ServerPort\"": "    <property name=\"ServerPort\" value=\"{{server.build.env.SERVER_PORT}}\"/>"
        }
    }
}
```

I'm not 100% sure how to translate this into usable JSON but I'm hoping that should be simple enough for you. After correcting my config file (as you can see above it was pretty messed up) this now works correctly. Obviously this is pretty fragile as it relies on the config file having the exact indentation specified in the find statement (4 spaces) but that should be the default and at least if this fails it simply does nothing rather than breaking the config with erroneous entries.

... But after testing with a fresh server, I can't get it working again. The default config file seems to have changed, and now looks like this:

```<?xml version="1.0"?>
<ServerSettings>
	<!-- GENERAL SERVER SETTINGS -->

	<!-- Server representation -->
	<property name="ServerName"						value="My Game Host"/>		<!-- Whatever you want the name of the server to be. -->
	<property name="ServerDescription"				value="A 7 Days to Die server"/>	<!-- Whatever you want the server description to be, will be shown in the server browser. -->
	<property name="ServerWebsiteURL"				value=""/>					<!-- Website URL for the server, will be shown in the serverbrowser as a clickable link -->
	<property name="ServerPassword"					value=""/>					<!-- Password to gain entry to the server -->
	<property name="ServerLoginConfirmationText"	value="" />					<!-- If set the user will see the message during joining the server and has to confirm it before continuing. For more complex changes to this window you can change the "serverjoinrulesdialog" window in XUi -->

	<!-- Networking -->
	<property name="ServerPort"						value="26900"/>				<!-- Port you want the server to listen on. -->
	<property name="ServerVisibility"				value="2"/>					<!-- Visibility of this server: 2 = public, 1 = only shown to friends, 0 = not listed. As you are never friend of a dedicated server setting this to "1" will only work when the first player connects manually by IP. -->
	<property name="ServerDisabledNetworkProtocols"	value="SteamNetworking"/>	<!-- Networking protocols that should not be used. Separated by comma. Possible values: LiteNetLib, SteamNetworking. Dedicated servers should disable SteamNetworking if there is no NAT router in between your users and the server or when port-forwarding is set up correctly -->

	<!-- Slots -->
	<property name="ServerMaxPlayerCount"			value="8"/>					<!-- Maximum Concurrent Players -->
	<property name="ServerReservedSlots"			value="0"/>					<!-- Out of the MaxPlayerCount this many slots can only be used by players with a specific permission level -->
	<property name="ServerReservedSlotsPermission"	value="100"/>				<!-- Required permission level to use reserved slots above -->
	<property name="ServerAdminSlots"				value="0"/>					<!-- This many admins can still join even if the server has reached MaxPlayerCount -->
	<property name="ServerAdminSlotsPermission"		value="0"/>					<!-- Required permission level to use the admin slots above -->

	<!-- Admin interfaces -->
	<property name="ControlPanelEnabled"			value="false"/>				<!-- Enable/Disable the web control panel -->
	<property name="ControlPanelPort"				value="8080"/>				<!-- Port of the control panel webpage -->
	<property name="ControlPanelPassword"			value="CHANGEME"/>			<!-- Password to gain entry to the control panel -->

	<property name="TelnetEnabled"					value="true"/>				<!-- Enable/Disable the telnet -->
	<property name="TelnetPort"						value="8081"/>				<!-- Port of the telnet server -->
	<property name="TelnetPassword"					value=""/>					<!-- Password to gain entry to telnet interface. If no password is set the server will only listen on the local loopback interface -->
	<property name="TelnetFailedLoginLimit"			value="10"/>				<!-- After this many wrong passwords from a single remote client the client will be blocked from connecting to the Telnet interface -->
	<property name="TelnetFailedLoginsBlocktime"	value="10"/>				<!-- How long will the block persist (in seconds) -->

	<property name="TerminalWindowEnabled"			value="true"/>				<!-- Show a terminal window for log output / command input (Windows only) -->

	<!-- Folder and file locations -->
	<property name="AdminFileName"					value="serveradmin.xml"/>	<!-- Server admin file name. Path relative to the SaveGameFolder -->
	<!-- <property name="UserDataFolder"				value="absolute path" /> -->	<!-- Use this to override where the server stores all generated data, including RWG generated worlds. Do not forget to uncomment the entry! -->
	<!-- <property name="SaveGameFolder"				value="absolute path" /> -->	<!-- Use this to only override the save game path. Do not forget to uncomment the entry! -->

	<!-- Other technical settings -->
	<property name="EACEnabled"						value="true"/>				<!-- Enables/Disables EasyAntiCheat -->
	<property name="HideCommandExecutionLog"		value="0"/>					<!-- Hide logging of command execution. 0 = show everything, 1 = hide only from Telnet/ControlPanel, 2 = also hide from remote game clients, 3 = hide everything -->
	<property name="MaxUncoveredMapChunksPerPlayer"	value="131072"/>			<!-- Override how many chunks can be uncovered on the ingame map by each player. Resulting max map file size limit per player is (x * 512 Bytes), uncovered area is (x * 256 m²). Default 131072 means max 32 km² can be uncovered at any time -->
	<property name="PersistentPlayerProfiles"		value="false" />			<!-- If disabled a player can join with any selected profile. If true they will join with the last profile they joined with -->



	<!-- GAMEPLAY -->
	
	<!-- World -->
	<property name="GameWorld"						value="Navezgane"/>			<!-- RWG (see WorldGenSeed and WorldGenSize options below) or any already existing world name in the Worlds folder (currently shipping with Navezgane) -->
	<property name="WorldGenSeed"					value="asdf"/>				<!-- If RWG this is the seed for the generation of the new world. If a world with the resulting name already exists it will simply load it -->
	<property name="WorldGenSize"					value="4096"/>				<!-- If RWG this controls the width and height of the created world. It is also used in combination with WorldGenSeed to create the internal RWG seed thus also creating a unique map name even if using the same WorldGenSeed. Has to be between 2048 and 16384, though large map sizes will take long to generate / download / load -->
	<property name="GameName"						value="My Game"/>			<!-- Whatever you want the game name to be. This affects the save game name as well as the seed used when placing decoration (trees etc) in the world. It does not control the generic layout of the world if creating an RWG world -->
	<property name="GameMode"						value="GameModeSurvival"/>	<!-- GameModeSurvival -->

	<!-- Difficulty -->
	<property name="GameDifficulty"					value="2"/>					<!-- 0 - 5, 0=easiest, 5=hardest -->
	<property name="BlockDamagePlayer"				value="100" />				<!-- How much damage do players to blocks (percentage in whole numbers) -->
	<property name="BlockDamageAI"					value="100" />				<!-- How much damage do AIs to blocks (percentage in whole numbers) -->
	<property name="BlockDamageAIBM"				value="100" />				<!-- How much damage do AIs during blood moons to blocks (percentage in whole numbers) -->
	<property name="XPMultiplier"					value="100" />				<!-- XP gain multiplier (percentage in whole numbers) -->
	<property name="PlayerSafeZoneLevel"			value="5" />				<!-- If a player is less or equal this level he will create a safe zone (no enemies) when spawned -->
	<property name="PlayerSafeZoneHours"			value="5" />				<!-- Hours in world time this safe zone exists -->

	<!--  -->
	<property name="BuildCreate"					value="false" />			<!-- cheat mode on/off -->
	<property name="DayNightLength"					value="60" />				<!-- real time minutes per in game day: 60 minutes -->
	<property name="DayLightLength"					value="18" />				<!-- in game hours the sun shines per day: 18 hours day light per in game day -->
	<property name="DropOnDeath"					value="0" />				<!-- 0 = everything, 1 = toolbelt only, 2 = backpack only, 3 = delete all -->
	<property name="DropOnQuit"						value="0" />				<!-- 0 = nothing, 1 = everything, 2 = toolbelt only, 3 = backpack only -->
	<property name="BedrollDeadZoneSize"			value="15"/>				<!-- Size of bedroll deadzone, no zombies will spawn inside this area, and any cleared sleeper volumes that touch a bedroll deadzone will not spawn after they've been cleared. -->

	<!-- Performance related -->
	<property name="MaxSpawnedZombies"				value="60"/>				<!-- Making this number too large (more than about 80) may cause servers to run at poor framerates which will effect lag and play quality for clients. -->
	<property name="MaxSpawnedAnimals"				value="50"/>				<!-- If your server has a large number of players you can increase this limit to add more wildlife. Animals don't consume as much CPU as zombies. NOTE: That this doesn't cause more animals to spawn arbitrarily: The biome spawning system only spawns a certain number of animals in a given area, but if you have lots of players that are all spread out then you may be hitting the limit and can increase it. -->

	<!-- Zombie settings -->
	<property name="EnemySpawnMode"					value="true" />				<!-- Enable/Disable enemy spawning -->
	<property name="EnemyDifficulty"				value="0" />				<!-- 0 = Normal, 1 = Feral -->
	<property name="ZombieMove"						value="0" />				<!-- 0-4 (walk, jog, run, sprint, nightmare) -->
	<property name="ZombieMoveNight"				value="3" />				<!-- 0-4 (walk, jog, run, sprint, nightmare) -->
	<property name="ZombieFeralMove"				value="3" />				<!-- 0-4 (walk, jog, run, sprint, nightmare) -->
	<property name="ZombieBMMove"					value="3" />				<!-- 0-4 (walk, jog, run, sprint, nightmare) -->
	<property name="BloodMoonFrequency"				value="7" />				<!-- What frequency (in days) should a blood moon take place -->
	<property name="BloodMoonRange"					value="0" />				<!-- How many days can the actual blood moon day randomly deviate from the above setting. Setting this to 0 makes blood moons happen exactly each Nth day as specified in BloodMoonFrequency -->
	<property name="BloodMoonWarning"				value="8" />				<!-- The Hour number that the red day number begins on a blood moon day. Setting this to -1 makes the red never show.  -->
	<property name="BloodMoonEnemyCount"			value="8" />				<!-- The number of zombies spawned during blood moons per player. -->

	<!-- Loot -->
	<property name="LootAbundance"					value="100" />				<!-- percentage in whole numbers -->
	<property name="LootRespawnDays"				value="30" />				<!-- days in whole numbers -->
	<property name="AirDropFrequency"				value="72"/>				<!-- How often airdrop occur in game-hours, 0 == never -->
	<property name="AirDropMarker"					value="false"/>				<!-- Sets if a marker is added to map/compass for air drops. -->

	<!-- Multiplayer -->
	<property name="PartySharedKillRange"			value="100"/>				<!-- The distance you must be within to receive party shared kill xp and quest party kill objective credit. -->
	<property name="PlayerKillingMode"				value="3" />				<!-- Player Killing Settings (0 = No Killing, 1 = Kill Allies Only, 2 = Kill Strangers Only, 3 = Kill Everyone) -->

	<!-- Land claim options -->
	<property name="LandClaimCount"					value="1"/>					<!-- Maximum allowed land claims per player. -->
	<property name="LandClaimSize"					value="41"/>				<!-- Size in blocks that is protected by a keystone -->
	<property name="LandClaimDeadZone"				value="30"/>				<!-- Keystones must be this many blocks apart (unless you are friends with the other player) -->
	<property name="LandClaimExpiryTime"			value="3"/>					<!-- The number of days a player can be offline before their claims expire and are no longer protected -->
	<property name="LandClaimDecayMode"				value="0"/>					<!-- Controls how offline players land claims decay. All claims have full protection for the first 24hrs. 0=Linear, 1=Exponential, 2=Full protection until claim is expired. -->
	<property name="LandClaimOnlineDurabilityModifier"	value="4"/>				<!-- How much protected claim area block hardness is increased when a player is online. 0 means infinite (no damage will ever be taken). Default is 4x -->
	<property name="LandClaimOfflineDurabilityModifier"	value="4"/>				<!-- How much protected claim area block hardness is increased when a player is offline. 0 means infinite (no damage will ever be taken). Default is 4x -->


	<!-- There are several game settings that you cannot change when starting a new game.
	You can use console commands to change at least some of them ingame.
	setgamepref BedrollDeadZoneSize 30 -->
</ServerSettings>```

I'm not sure how to get this working at this point, if I copy/paste out of this config it says it's not valid JSON even after I escape the quotes. It doesn't seem to like the specific character used at the start of these lines (a tab?). Perhaps a script to replace the tabs with spaces during setup after grabbing the files from Steam?

**Comment by parkervcp** [comment]
Just to be sure you pulled my PR's file and not the one in the repo still

https://github.com/parkervcp/eggs/pull/284/files

**Comment by NHDriver4** [comment]
After using the PR, my config is no longer valid:

`...
  <property name="LandClaimOnlineDurabilityModifier" value="4"/>
  <property name="LandClaimOfflineDurabilityModifier" value="4"/>
  <property name="ServerPort">value="26900"</property name="ServerPort">
</ServerSettings>`

**Comment by parkervcp** [comment]
There is a new update to the PR. Please give it a check.

**Comment by parkervcp** [comment]
@NHDriver4 @msgerbs Please check now. I go rid of the config edit in favor of fixing the startup.

**Comment by NHDriver4** [comment]
I will test tomorrow. It's a busy weekend. Thanks for updating the PR!

**Comment by NHDriver4** [comment]
@parkervcp I tested the egg. Seems to work as expected. Thanks for resolving!
