### ISSUE TITLE
[Bug]: Space Engineers (Torch) EOS doesn't work

### ISSUE THREAD

**Issue by JamesDAdams** [parkervcp/eggs#2793]
### Panel Version

1.11.3

### Wings Version

1.11.8

### Service

space_engineers/torch

### Modified

No, I did not modify the egg

### Expected Behavior

Show the server in EOS tab

### Actual Behavior

The server appears like a steam but i enable EOS in the config

### Steps To Reproduce

Installe the server
specific EOS in the config

### Install logs

docker exec -it PterodatylWings tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log  | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99 bash: nc: command not found /bin/ls: cannot access '/var/log/pterodactyl/install/*.log': No such file or directory

**Comment by JamesDAdams** [comment]
no matter the configuration the server is always started in steam mode : 

13:16:35.1997 [INFO]   Keen:    Networking service: Steam

**Comment by QuintenQVD0** [comment]
@JamesDAdams Is your egg up to date? Please show the used docker image, the contence of the WINETRICKS_RUN variable

**Comment by gOOvER** [comment]
does SE Support EOS?

**Comment by QuintenQVD0** [comment]
As far as I see on google Space Engineers does not support EOS, not an egg issue
