### ISSUE TITLE
[Egg Request]: Dead Matter 

### ISSUE THREAD

**Issue by coyottetv** [parkervcp/eggs#2794]
### Does this expand an already existing service

Yes

### Link to a game or software

Dead Matter 

### Links for the download

https://steamdb.info/app/2584780/

### Links for the install docs

Not released yet

**Comment by QuintenQVD0** [comment]
You clearly spend 0 effort in making this request as this does not expand anything. And if their no docs then no egg will be made.

**Comment by coyottetv** [comment]
the only doc I have https://docs.google.com/document/d/e/2PACX-1vTsTsSrAaj0pJ5eKktFrycewHObbkiq_HejJoFNADB4dOEr411yzf4pDfNuKcSSitM9KCQbYiaTmuAg/pub

**Comment by QuintenQVD0** [comment]
@coyottetv I linked an PR, please test it (the server will need around 20GiB of ram to start

**Comment by coyottetv** [comment]
> @coyottetvJ'ai lié un PR, veuillez le tester (le serveur aura besoin d'environ 20 Go de RAM pour démarrer

thank you I will test that 128 gb should be good ^^

**Comment by coyottetv** [comment]
@QuintenQVD0  I have LogSteamShared: Warning: Steam Dedicated Server API failed to initialize.
LogOnline: STEAM: [AppId: 0] Game Server API initialized 0
LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable.
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogOnline: Warning: STEAM: Steam API failed to initialize! in the console but the server starts, nothing serious?

**Comment by gOOvER** [comment]
> @QuintenQVD0 I have LogSteamShared: Warning: Steam Dedicated Server API failed to initialize. LogOnline: STEAM: [AppId: 0] Game Server API initialized 0 LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable. LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown() LogOnline: Warning: STEAM: Steam API failed to initialize! in the console but the server starts, nothing serious?

full log. such msgs can be normal

**Comment by coyottetv** [comment]
I can't connect to the local server or via IP

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 I have LogSteamShared: Warning: Steam Dedicated Server API failed to initialize. LogOnline: STEAM: [AppId: 0] Game Server API initialized 0 LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable. LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown() LogOnline: Warning: STEAM: Steam API failed to initialize! in the console but the server starts, nothing serious?

Something faild. Share the install logs

**Comment by gOOvER** [comment]
> I can't connect to the local server or via IP

cant connect to local server is 98% wrong configerung network

**Comment by coyottetv** [comment]
https://pteropaste.com/xz5b3dmmlch8/

**Comment by gOOvER** [comment]
> https://pteropaste.com/xz5b3dmmlch8/

thats fine. So check your network. I bet its on your site the problem

**Comment by coyottetv** [comment]
LogSteamShared: Warning: Steam Dedicated Server API failed to initialize.
LogOnline: STEAM: [AppId: 0] Game Server API initialized 0
LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable.
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()()   this could come from no because on my other server works well

**Comment by coyottetv** [comment]
and I just saw that I don't have the steam_appid.txt

**Comment by gOOvER** [comment]
> LogSteamShared: Warning: Steam Dedicated Server API failed to initialize. LogOnline: STEAM: [AppId: 0] Game Server API initialized 0 LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine. Try running with -NOSTEAM on the cmdline to disable. LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()() this could come from no because on my other server works well

again; check your network, since you hast at home.

**Comment by coyottetv** [comment]
LogSteamShared: Display: Loading Steam SDK 1.53
LogSteamShared: Steam SDK Loaded!
LogOnline: STEAM: [AppId: 2184150] Game Server API initialized 1
LogOnline: STEAM: Initializing SteamNetworking Layer
LogOnline: STEAM: Missing P2PCleanupTimeout key in OnlineSubsystemSteam of DefaultEngine.ini, using default
LogInit: WinSock: version 1.1 (2.2), MaxSocks=32767, MaxUdp=65467
LogOnline: STEAM: AUTH: Steam Auth Enabled
LogOnline: OSS: Created online subsystem instance for: STEAM
LogOnline: OSS: TryLoadSubsystemAndSetDefault: Loaded subsystem for module [STEAM]
LogInit: ExecutableName: DeadMatterServer-Win64-Test.exe   I just added the Steamworks SDK and steam_appid.txt and it works

**Comment by gOOvER** [comment]
steamsdk should be always installed with every game. Quinten change the installscript  and images to install 1007 with every game

**Comment by coyottetv** [comment]
so it comes from steam_appid.txt so I don't know I added steam_appid.txt to the root and it works

**Comment by QuintenQVD0** [comment]
> so it comes from steam_appid.txt so I don't know I added steam_appid.txt to the root and it works I will delete and restart installation

Proton you not look at the steam_appid.txt file ever?

**Comment by coyottetv** [comment]
> > donc ça vient de steam_appid.txt donc je ne sais pas j'ai ajouté steam_appid.txt à la racine et ça marche je vais supprimer et relancer l'installation
> 
> Proton, tu n'as jamais regardé le fichier steam_appid.txt ?

No

**Comment by gOOvER** [comment]
> > so it comes from steam_appid.txt so I don't know I added steam_appid.txt to the root and it works I will delete and restart installation
> 
> Proton you not look at the steam_appid.txt file ever?

some windows based steam games need the steam_appid.txt in a special folder. never find out why

**Comment by coyottetv** [comment]
ok so a number can change everything

**Comment by coyottetv** [comment]
yes so I think the problem comes from 
![Capture d'écran 2024-03-12 234419](https://github.com/parkervcp/eggs/assets/83652144/a4d3fa0c-e50a-4c47-a239-070600cdc688)

**Comment by QuintenQVD0** [comment]
Very strange. When making this egg I did not have any of those issues. It just started wine dith no error at all. I will let it download the app id 1007 (the windows version) and add a app id txt file with the main game I guess? But I did not have to do this to get it running.

**Comment by QuintenQVD0** [comment]
@coyottetv what ip did you put in the steam_appid.txt file (in /home/container)

and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)

**Comment by coyottetv** [comment]
> @coyottetv what ip did you put in the steam_appid.txt file (in /home/container)
> 
> and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)

2184150

**Comment by QuintenQVD0** [comment]
> > @coyottetv what ip did you put in the steam_appid.txt file (in /home/container)
> > and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)
> 
> 2184150 windows

and just be certain, the SDK was installed to /home/container not their win64 folder as someone was claiming that?

**Comment by coyottetv** [comment]
> > > @coyottetv what ip did you put in the steam_appid.txt file (in /home/container)
> > > and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)
> > 
> > 
> > 2184150 windows
> 
> and just be certain, the SDK was installed to /home/container not their win64 folder as someone was claiming that?

SDK was installed in win 64 sorry

**Comment by QuintenQVD0** [comment]
> > > > @coyottetv what ip did you put in the steam_appid.txt file (in /home/container)
> > > > and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)
> > > 
> > > 
> > > 2184150 windows
> > 
> > 
> > and just be certain, the SDK was installed to /home/container not their win64 folder as someone was claiming that?
> 
> SDK was installed in win 64 sorry

so you ran something like 
`./steamcmd.sh +force_install_dir /mnt/server/DeadMatter/Binaries/Win64 +login ${STEAM_USER} ${STEAM_PASS} ${STEAM_AUTH} $( [[ "${WINDOWS_INSTALL}" == "1" ]] && printf %s '+@sSteamCmdForcePlatformType windows' ) +app_update 1007 ${INSTALL_FLAGS} validate +quit ` (will math to /home/container/DeadMatter/Binaries/Win64)

and 

`echo "2184150" > steam_appid.txt` (in /home/container?)

**Comment by coyottetv** [comment]
> > > > > @coyottetv what ip did you put in the steam_appid.txt file (in /home/container)
> > > > > and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)
> > > > 
> > > > 
> > > > 2184150 windows
> > > 
> > > 
> > > and just be certain, the SDK was installed to /home/container not their win64 folder as someone was claiming that?
> > 
> > 
> > SDK was installed in win 64 sorry
> 
> so you ran something like `./steamcmd.sh +force_install_dir /mnt/server/DeadMatter/Binaries/Win64 +login ${STEAM_USER} ${STEAM_PASS} ${STEAM_AUTH} $( [[ "${WINDOWS_INSTALL}" == "1" ]] && printf %s '+@sSteamCmdForcePlatformType windows' ) +app_update 1007 ${INSTALL_FLAGS} validate +quit ` (will math to /home/container/DeadMatter/Binaries/Win64)
> 
> and
> 
> `echo "2184150" > steam_appid.txt` (in /home/container?)

yes

**Comment by gOOvER** [comment]
> @coyottetv what ip did you put in the steam_appid.txt file (in /home/container)
> 
> and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)

add only +app_update 1007

**Comment by QuintenQVD0** [comment]
> > @coyottetv what ip did you put in the steam_appid.txt file (in /home/container)
> > and the SDK (app ID 1007) did you download the windows or linux version to /home/container? (/mnt/server in the install container)
> 
> add only +app_update 1007

someone in the discord also told me it has to be in the win64 folder.

**Comment by QuintenQVD0** [comment]
because for some reason if you run the  DeadMatterServer.exe  file in /home/container shit does not work.

**Comment by coyottetv** [comment]
I was getting that before I installed the SteamSDK

**Comment by QuintenQVD0** [comment]
> Once I added the SteamSDK it sorted itself out

I just update the PR to generate a app id file and install the windows 1007 sdk to the win64 folder, can you please retest ( if posible on a clean install?

**Comment by coyottetv** [comment]
> > Once I added the SteamSDK it sorted itself out
> 
> I just update the PR to generate a app id file and install the windows 1007 sdk to the win64 folder, can you please retest ( if posible on a clean install?

Yes, no problem
