### ISSUE TITLE
[Egg Request]: Ketting

### ISSUE THREAD

**Issue by MCdragonmasters** [parkervcp/eggs#2795]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/kettingpowered/Ketting-1-20-x

### Links for the download

https://github.com/kettingpowered/Ketting-1-20-x/releases

### Links for the install docs

Its literally just a jar file fr

**Comment by QuintenQVD0** [comment]
We stated many times we will not add any more minecraft eggs. If you really want to run this use the generic java egg
