### ISSUE TITLE
[Egg Request]: No Love Lost

### ISSUE THREAD

**Issue by verticalhost** [parkervcp/eggs#2798]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/1873120/No_Love_Lost/

### Links for the download

https://store.steampowered.com/app/1873120/No_Love_Lost/

### Links for the install docs

https://store.steampowered.com/news/app/1873120/view/4105665567919534319?l=french

To make it better i would like to say it's on Windows OS

**Comment by gOOvER** [comment]
This game has no server yet; only COOP

**Comment by verticalhost** [comment]
if you can take 2 second and looks on steam page. 
![image](https://github.com/parkervcp/eggs/assets/100486259/9775e6aa-cc71-463d-9e7d-e098b3fa685f)

**Comment by gOOvER** [comment]
> if you can take 2 second and looks on steam page. But it's okay just letting you know very good news about it. Yes you can now. ![image](https://private-user-images.githubusercontent.com/100486259/312198203-9775e6aa-cc71-463d-9e7d-e098b3fa685f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjg4MzUsIm5iZiI6MTcxMDI2ODUzNSwicGF0aCI6Ii8xMDA0ODYyNTkvMzEyMTk4MjAzLTk3NzVlNmFhLWNjNzEtNDYzZC05ZTdkLWUwOThiM2ZhNjg1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxODM1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzNjOTkyOWRlOWY4MWQ2ZTk0MjBjYjQ1NDVlY2QyOTBlZDg4NTY0NGVkNTA5ODNlNTFlNWU1MDE0Mjg2NjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R8Rq9s46iarK78WxlBL1CPxaIfQMbC_FNG2PO2G7Vw0)

if you woud start reading, mthen you would post the steamdb and a guide ;) not in all 3 questions the gamelink in the store

**Comment by QuintenQVD0** [comment]
I do not find a steamdb app id.

**Comment by gOOvER** [comment]
> I do not find a steamdb app id.

me too.

**Comment by verticalhost** [comment]
> steamdb app id.

I will ask and update this post soon they should have some where

**Comment by verticalhost** [comment]
I only found something like this : https://steamdb.info/app/1873120/ 
But i will ask for the specific things for dedicated server. 
They possibly miss to update it on it. 
So i will tell them..

**Comment by QuintenQVD0** [comment]
> > > steamdb app id.
> > 
> > 
> > I will ask and update this post soon they should have some where
> 
> no need to ask; you can search it on steamdb yourself :)
> 
> https://steamdb.info/
> 
> And there is no server listed

2833050

**Comment by gOOvER** [comment]
> > > > steamdb app id.
> > > 
> > > 
> > > I will ask and update this post soon they should have some where
> > 
> > 
> > no need to ask; you can search it on steamdb yourself :)
> > https://steamdb.info/
> > And there is no server listed
> 
> 2833050

Funny, No Distro listed :D Not windows or linux :)

**Comment by QuintenQVD0** [comment]
> > > > > steamdb app id.
> > > > 
> > > > 
> > > > I will ask and update this post soon they should have some where
> > > 
> > > 
> > > no need to ask; you can search it on steamdb yourself :)
> > > https://steamdb.info/
> > > And there is no server listed
> > 
> > 
> > 2833050
> 
> Funny, No Distro listed :D Not windows or linux :)

Only way I found it because i asked the dev. If you look on steamdb to the files it are just a bunch of folder. But on the configuration tab they mention the main .exe

**Comment by gOOvER** [comment]
Looks like, again a dev team, which dont know, how to realse a server on steam :) Let wait and see, if they start reading the steam server release guides :)

**Comment by QuintenQVD0** [comment]
they alse are having issues that you need to own the game to download the server for now.

**Comment by ImKringle** [comment]
Availability on it has been fixed, seems a tad angy running on Proton though (tbf I havent looked too far into it, but it isnt just *proton run <exec> -port* at the very least lol Wine may be better here

**Comment by ImKringle** [comment]
Got a basic egg setup [here](https://github.com/ImKringle/Ptero-Things/tree/main/NoLoveLost) , doesnt post to Console at all so someone else can figure that out; but connection works lol
