### ISSUE TITLE
Fivem Server Wont start

### ISSUE THREAD

**Issue by BlackZon77** [parkervcp/eggs#280]
Please fill out the information bellow and remove from the line up
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: fivem
Modified: no

Expected Behavior: start normaly

Actual Behavior: [Pterodactyl Daemon] A fatal error was encountered while starting this server.

Steps to Reproduce: start server

**Comment by parkervcp** [comment]
This i not an egg issue. It's a daemon error.
