### ISSUE TITLE
[Bug]: Ark Ascended

### ISSUE THREAD

**Issue by Gelvey** [parkervcp/eggs#2800]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

/steamcmd_servers/ark_survival_ascended

### Modified

No, I did not modify the egg

### Expected Behavior

Start the server, server starts up successfully without memory leak or anonymous login issue.

### Actual Behavior

Server starts by saying "Connecting anonymously to Steam Public...FAILED (Service Unavailable)"

Then your usual startup info such as "[2024.03.12-23.12.21:940][ 13]Server: "server-name" has successfully started!"

Then the container uses up all of its allocated ram (0 players - 19GB of ram available)

Then memory usage suddenly drops to 5MIB range & never starts.

### Steps To Reproduce

Install and run the ARK-Ascended egg with the latest version of ARK Ascended

Press "Start" to start the server

Watch it never successfully start

### Install logs

https://pteropaste.com/b85w0o2u37cd/

**Comment by QuintenQVD0** [comment]
@Gelvey 

Please show the network tab, the startup tab and the host os kernel `uname -a`

**Comment by gOOvER** [comment]
output of:
`hostnamectl status `'

pls

**Comment by Gelvey** [comment]
The egg had an update and seemingly fixed itself now
