### ISSUE TITLE
[Egg Request]: Ollama

### ISSUE THREAD

**Issue by TerraPlayz** [parkervcp/eggs#2801]
### Does this expand an already existing service

Yes

### Link to a game or software

https://ollama.com/

### Links for the download

https://ollama.com/download

### Links for the install docs

https://github.com/ollama/ollama/blob/main/docs/linux.md

**Comment by QuintenQVD0** [comment]
I guess this can be made bu t keep in mind that it will all cpu as their is no way to pass a gpu to a container

**Comment by Omxpro** [comment]
> I guess this can be made bu t keep in mind that it will all cpu as their is no way to pass a gpu to a container

There is no need for GPU. It works well on CPU too. It will be a little slower, but it'll work.

**Comment by QuintenQVD0** [comment]
This can not work with pterodactyl as in order to download a module the ollama binary needs to be running by systemd what is not possible in docker

**Comment by Omxpro** [comment]
> This can not work with pterodactyl as in order to download a module the ollama binary needs to be running by systemd what is not possible in docker

Alright thanks.
