### ISSUE TITLE
[Install Bug]: Minecraft CurseForge Generic

### ISSUE THREAD

**Issue by minisbett** [parkervcp/eggs#2803]
### Panel Version

1.11.5

### Service

minecraft

### Modified

No, I did not modify the egg

### Issue

The egg requires a CurseForge API key, but people won't be able to get one because CurseForge locks it behind a project submission form where u need to fill in data like ur project name, source code url etc., the API is not made for purposes like this.

**Comment by gOOvER** [comment]
you can not longer use CF API and no "normal" person get an api Key

**Comment by QuintenQVD0** [comment]
you can use a free personal key? this has always worked
https://docs.curseforge.com/#supported-download-options
https://console.curseforge.com/?#/signup

**Comment by minisbett** [comment]
> you can use a free personal key? this has always worked https://docs.curseforge.com/#supported-download-options https://console.curseforge.com/?#/signup

I'll try that, however the egg linked me to a CF wiki page that did say something else: https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key

**Comment by minisbett** [comment]
I can't try it because I'm facing a different issue;
```
cat: .serverjar: No such file or directory
container@pterodactyl~ java -Xms128M -Xmx16384M -Dterminal.jline=false -Dterminal.ansi=true -jar
Error: -jar requires jar file specification
```
It doesn't seem to download the modpack or anything, so when starting the .serverjar file is missing.

**Comment by QuintenQVD0** [comment]
> I can't try it because I'm facing a different issue;
> 
> ```
> cat: .serverjar: No such file or directory
> container@pterodactyl~ java -Xms128M -Xmx16384M -Dterminal.jline=false -Dterminal.ansi=true -jar
> Error: -jar requires jar file specification
> ```
> 
> It doesn't seem to download the modpack or anything, so when starting the .serverjar file is missing.

you hit reinstall in between? I hope so

and even then if their is not a zip they marked as dedicated server then there is no way for the egg to get the files it needs

**Comment by minisbett** [comment]
> and even then if their is not a zip they marked as dedicated server then there is no way for the egg to get the files it needs

hmm so there's a bug after all? I just fully deleted and re-installed the server, without success.
![image](https://github.com/parkervcp/eggs/assets/39670899/15ff4962-92b5-4bde-ac92-f339b5c2d350)
The modpack didn't even download.

**Comment by gOOvER** [comment]
thats the new system. CF will earn money and you need a new api key

**Comment by gOOvER** [comment]
> you can use a free personal key? this has always worked https://docs.curseforge.com/#supported-download-options https://console.curseforge.com/?#/signup

no, you cant

**Comment by minisbett** [comment]
I got it working with the (legacy?) api key. The issue with the .serverjar file not being found / the modpack not installing was that the file version id automatically defaults to `latest`, which makes it unable to install it. I provided the file version id by opening the main file link (in this case https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5184435) and providing `5184435`.

**Comment by gOOvER** [comment]
https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key

**Comment by gOOvER** [comment]
> > https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key
> 
> yes this one doesn't work. But https://console.curseforge.com/?#/signup worked for me.
> 
> Next error, wohoo...
> 
> ```
> container@pterodactyl~ Server marked as offline...
> [Pterodactyl Daemon]: Updating process configuration files...
> [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
> container@pterodactyl~ Server marked as starting...
> [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
> Pulling from pterodactyl/yolks 
> Digest: sha256:2dc464502b22a0c64edbc10a347d9f72b4581640be487b5eb750785d26ccad04 
> Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
> [Pterodactyl Daemon]: Finished pulling Docker container image
> container@pterodactyl~ java -version
> openjdk version "17.0.10" 2024-01-16
> OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
> OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
> container@pterodactyl~ java @user_jvm_args.txt -Xms128M -Xmx16384M -Dterminal.jline=false -Dterminal.ansi=true @unix_args.txt
> [16:05:44] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
> [16:05:44] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10 by Eclipse Adoptium; OS Linux arch amd64 version 5.15.0-89-generic
> [16:05:44] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
> [16:05:44] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
> [16:05:45] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/fmlcore/1.20.1-47.2.20/fmlcore-1.20.1-47.2.20.jar is missing mods.toml file
> [16:05:45] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.2.20/javafmllanguage-1.20.1-47.2.20.jar is missing mods.toml file
> [16:05:45] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.2.20/lowcodelanguage-1.20.1-47.2.20.jar is missing mods.toml file
> [16:05:45] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/mclanguage/1.20.1-47.2.20/mclanguage-1.20.1-47.2.20.jar is missing mods.toml file
> [16:05:45] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 12 dependencies adding them to mods collection
> [16:05:45] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
>         Mod ID: 'supermartijn642configlib', Requested by: 'simplemagnets', Expected range: '[1.1.6,)', Actual version: '[MISSING]'
>         Mod ID: 'architectury', Requested by: 'artifacts', Expected range: '[9.0.8,)', Actual version: '[MISSING]'
>         Mod ID: 'yungsapi', Requested by: 'betterendisland', Expected range: '[1.20-Forge-4.0.1,)', Actual version: '[MISSING]'
>         Mod ID: 'sophisticatedcore', Requested by: 'sophisticatedbackpacks', Expected range: '[0.6.0.+,)', Actual version: '[MISSING]'
>         Mod ID: 'ars_nouveau', Requested by: 'ars_ocultas', Expected range: '[4.5.0,)', Actual version: '[MISSING]'
>         Mod ID: 'integrateddynamics', Requested by: 'integratedterminals', Expected range: '[1.16.7,)', Actual version: '[MISSING]'
>         Mod ID: 'supermartijn642configlib', Requested by: 'durabilitytooltip', Expected range: '[1.1.6,)', Actual version: '[MISSING]'
>         Mod ID: 'structure_gel', Requested by: 'blue_skies', Expected range: '[2.13.0,]', Actual version: '[MISSING]'
>         Mod ID: 'architectury', Requested by: 'ftbxmodcompat', Expected range: '[9.0.8,)', Actual version: '[MISSING]'
>         Mod ID: 'cyclopscore', Requested by: 'integratedterminals', Expected range: '[1.18.4,)', Actual version: '[MISSING]'
>         Mod ID: 'refinedstorage', Requested by: 'rsinsertexportupgrade', Expected range: '[1.12,)', Actual version: '[MISSING]'
>         Mod ID: 'ftbteams', Requested by: 'ftbquests', Expected range: '[2001.1.4,)', Actual version: '[MISSING]'
>         Mod ID: 'cyclopscore', Requested by: 'integratedterminalscompat', Expected range: '[1.18.4,)', Actual version: '[MISSING]'
>         Mod ID: 'supermartijn642corelib', Requested by: 'rechiseledcreate', Expected range: '>=1.1.0 <1.2.0', Actual version: '[MISSING]'
>         Mod ID: 'cupboard', Requested by: 'connectivity', Expected range: '[1.20.1-1.5,)', Actual version: '[MISSING]'
>         Mod ID: 'attributeslib', Requested by: 'gateways', Expected range: '[1.1.4,)', Actual version: '[MISSING]'
>         Mod ID: 'valhelsia_core', Requested by: 'forbidden_arcanus', Expected range: '[1.1.1,)', Actual version: '[MISSING]'
>         Mod ID: 'commoncapabilities', Requested by: 'integratedterminals', Expected range: '[2.9.0,)', Actual version: '[MISSING]'
>         Mod ID: 'supermartijn642configlib', Requested by: 'entangled', Expected range: '[1.1.6,)', Actual version: '[MISSING]'
>         Mod ID: 'rftoolsbase', Requested by: 'xnet', Expected range: '[1.20-5.0.0,)', Actual version: '[MISSING]'
>         Mod ID: 'blockui', Requested by: 'minecolonies', Expected range: '[1.20.1-1.0.139-BETA,)', Actual version: '[MISSING]'
>         Mod ID: 'cofh_core', Requested by: 'thermal_innovation', Expected range: '[11.0.0,11.1.0)', Actual version: '[MISSING]'
>         Mod ID: 'farmersdelight', Requested by: 'twilightdelight', Expected range: '[1.20.1-1.2.4,)', Actual version: '[MISSING]'
>         Mod ID: 'structurize', Requested by: 'minecolonies', Expected range: '[1.20.1-1.0.701-BETA,)', Actual version: '[MISSING]'
>         Mod ID: 'resourcefulconfig', Requested by: 'ad_astra_giselle_addon', Expected range: '[2.1.2,)', Actual version: '[MISSING]'
>         Mod ID: 'jade', Requested by: 'jadeaddons', Expected range: '[11.5.1,)', Actual version: '[MISSING]'
>         Mod ID: 'supermartijn642corelib', Requested by: 'wirelesschargers', Expected range: '[1.1.0,1.2.0)', Actual version: '[MISSING]'
>         Mod ID: 'patchouli', Requested by: 'ars_creo', Expected range: '[1.19.2-77,)', Actual version: '[MISSING]'
>         Mod ID: 'libx', Requested by: 'mythicbotany', Expected range: '[1.20.1-5.0.12,)', Actual version: '[MISSING]'
>         Mod ID: 'domum_ornamentum', Requested by: 'minecolonies', Expected range: '[1.20-1.0.164-BETA,)', Actual version: '[MISSING]'
>         Mod ID: 'commoncapabilities', Requested by: 'integratedterminalscompat', Expected range: '[2.9.0,)', Actual version: '[MISSING]'
>         Mod ID: 'mekanism', Requested by: 'gravitationalmodulatingunittweaks', Expected range: '[10.4.0,)', Actual version: '[MISSING]'
>         Mod ID: 'cofh_core', Requested by: 'ensorcellation', Expected range: '[11.0.0,11.1.0)', Actual version: '[MISSING]'
>         Mod ID: 'architectury', Requested by: 'ftblibrary', Expected range: '[9.0.8,)', Actual version: '[MISSING]'
>         Mod ID: 'architectury', Requested by: 'findme', Expected range: '[2.3.23,)', Actual version: '[MISSING]'
>         Mod ID: 'bookshelf', Requested by: 'botanypots', Expected range: '[20,)', Actual version: '[MISSING]'
>         Mod ID: 'refinedstorage', Requested by: 'rsinfinitybooster', Expected range: '[1.12.3,)', Actual version: '[MISSING]'
>         Mod ID: 'patchouli', Requested by: 'mythicbotany', Expected range: '[1.20.1-84,)', Actual version: '[MISSING]'
>         Mod ID: 'twilightforest', Requested by: 'twilightdelight', Expected range: '[4.2,)', Actual version: '[MISSING]'
>         Mod ID: 'architectury', Requested by: 'ftbultimine', Expected range: '[9.0.8,)', Actual version: '[MISSING]'
>         Mod ID: 'integrateddynamics', Requested by: 'integratedterminalscompat', Expected range: '[1.16.7,)', Actual version: '[MISSING]'
>         Mod ID: 'supermartijn642corelib', Requested by: 'simplemagnets', Expected range: '[1.1.0,1.2.0)', Actual version: '[MISSING]'
>         Mod ID: 'refinedstorage', Requested by: 'universalgrid', Expected range: '[1.12,)', Actual version: '[MISSING]'
>         Mod ID: 'yungsapi', Requested by: 'betterjungletemples', Expected range: '[1.20-Forge-4.0.1,)', Actual version: '[MISSING]'
>         Mod ID: 'ad_astra', Requested by: 'ad_astra_giselle_addon', Expected range: '[1.15.10,)', Actual version: '[MISSING]'
>         Mod ID: 'resourcefullib', Requested by: 'chipped', Expected range: '[2.1.20,)', Actual version: '[MISSING]'
>         Mod ID: 'occultism', Requested by: 'ars_ocultas', Expected range: '[1.20.1-1.85.0,)', Actual version: '[MISSING]'
>         Mod ID: 'architectury', Requested by: 'ftbquests', Expected range: '[9.0.8,)', Actual version: '[MISSING]'
>         Mod ID: 'gunpowderlib', Requested by: 'exchangers', Expected range: '[1.20-2.2,)', Actual version: '[MISSING]'
>         Mod ID: 'refinedstorage', Requested by: 'extradisks', Expected range: '[1.12.4,)', Actual version: '[MISSING]'
>         Mod ID: 'cupboard', Requested by: 'logprot', Expected range: '[1.20.1-1.5,)', Actual version: '[MISSING]'
>         Mod ID: 'cloth_config', Requested by: 'artifacts', Expected range: '[11.0.99,)', Actual version: '[MISSING]'
>         Mod ID: 'supermartijn642configlib', Requested by: 'wirelesschargers', Expected range: '[1.1.6,)', Actual version: '[MISSING]'
>         Mod ID: 'cofh_core', Requested by: 'redstone_arsenal', Expected range: '[11.0.0,11.1.0)', Actual version: '[MISSING]'
>         Mod ID: 'rechiseled', Requested by: 'rechiseledcreate', Expected range: '>=1.1.1', Actual version: '[MISSING]'
>         Mod ID: 'bookshelf', Requested by: 'runelic', Expected range: '[20,)', Actual version: '[MISSING]'
>         Mod ID: 'botania', Requested by: 'mythicbotany', Expected range: '[1.20.1-443,)', Actual version: '[MISSING]'
>         Mod ID: 'supermartijn642corelib', Requested by: 'entangled', Expected range: '[1.1.17,1.2.0)', Actual version: '[MISSING]'
>         Mod ID: 'ars_nouveau', Requested by: 'ars_creo', Expected range: '[3.5.1,)', Actual version: '[MISSING]'
>         Mod ID: 'yungsapi', Requested by: 'betterdeserttemples', Expected range: '[1.20-Forge-4.0.1,)', Actual version: '[MISSING]'
>         Mod ID: 'rftoolsbase', Requested by: 'rftoolsstorage', Expected range: '[1.20-5.0.0,)', Actual version: '[MISSING]'
>         Mod ID: 'shetiphiancore', Requested by: 'endertanks', Expected range: '[1.20.1-1.1,)', Actual version: '[MISSING]'
>         Mod ID: 'thermal', Requested by: 'thermal_innovation', Expected range: '[11.0.0,11.1.0)', Actual version: '[MISSING]'
>         Mod ID: 'patchouli', Requested by: 'ars_ocultas', Expected range: '[1.20.1-81,)', Actual version: '[MISSING]'
> [16:05:46] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
> Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixins.shetiphiancore.json
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:262)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:144)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:152)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:213)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:186)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:34)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$11(LaunchPluginHandler.java:100)
>         at java.base/java.util.HashMap.forEach(HashMap.java:1421)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:100)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:51)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
>         at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
> Caused by: java.lang.IllegalArgumentException: The specified resource 'mixins.shetiphiancore.json' was invalid or could not be read
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1282)
>         at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
>         ... 23 more
> ```

but be aware. This key will be removed in future

**Comment by taylor-mcdonald** [comment]
specifying "latest" for any mod cannot file any mod file
```
Retrieving CurseForge project information...
        No file ID specified, using latest file
        Found server pack file id 'null'
        Retrieving version information for 'null'
        ERROR: Failed to retrieve file data for file id 'null'
```

I've attempted to specify the version to no avail as well.  Is this a bug or am I missing something?

```
Retrieving CurseForge project information...
        Checking if provided file id 'Techopolis_2-7.0.zip' exists
        ERROR: File id 'Techopolis_2-7.0.zip' not found for project 'Techopolis 2'
```

**Comment by minisbett** [comment]
I got it to work by specifying the specific version. make sure to specify the server file ID, not the normal file ID

**Comment by taylor-mcdonald** [comment]
Where do you find the server file ID?

**Comment by minisbett** [comment]
> Where do you find the server file ID?

I got it from the URL when downloading the server stuff
