### ISSUE TITLE
[Bug]: Forge Enhanced

### ISSUE THREAD

**Issue by JohnB17** [parkervcp/eggs#2804]
### Panel Version

1.11.5

### Wings Version

1.11.0

### Service

minecraft

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

It should install forge 1.7.10

### Actual Behavior

![image](https://github.com/parkervcp/eggs/assets/63297273/50cd8c73-5aa3-4128-b1d8-ee5a1e02b5af)
It fails with this message. I did modify the egg so the FORGE_VERSION variable would end with a working install URL, but the console says 404 (I copied this link out of the console and I was able to download it). I did try without the modification and just using 1.7.10 as the minecraft version, but that didn't work

### Steps To Reproduce

1. Set version to 1.7.10
2. Install

### Install logs

(The panel is owned by my friend so I can't get the panel logs easily, but I'm pretty sure this has nothing to do with the panel)

**Comment by QuintenQVD0** [comment]
This has 100 % to do with the install logs. The egg works just fine if you put in the right value in the variables and did not modify the egg. 

Come to the discord for that. Not an egg bug.

**Comment by JohnB17** [comment]
I said I also tried it without the modification...

**Comment by QuintenQVD0** [comment]
> I said I also tried it without the modification...

Then as I tols you share the install logs without the mods.

**Comment by gOOvER** [comment]
he used a wrong version. Thats the problem.

**Comment by gOOvER** [comment]
404 = file not found ;)

**Comment by JohnB17** [comment]
> 404 = file not found ;)

The link it generates is a valid link, and I can download it with that same link. I will restore the egg to parker's original and try again when I get home from work

**Comment by gOOvER** [comment]
> > 404 = file not found ;)
> 
> The link it generates is a valid link, and I can download it with that same link. I will restore the egg to parker's original and try again when I get home from work

again: 404, so sth is wrong ;)

**Comment by gOOvER** [comment]
`Error 404 is a client-side issue indicating the requested URL can’t be found on the server. It may occur because of several reasons, such as the domain is not pointed correctly, a broken.htaccess file, or misconfigured file permissions.`

**Comment by JohnB17** [comment]
My local DNS might be running on a windows server instance, but my PC and the node are on the same network and using the same DNS server. The URL leads to a valid file on my PC and curl from the node's shell can get the file too.

**Comment by gOOvER** [comment]
> My local DNS might be running on a windows server instance, but my PC and the node are on the same network and using the same DNS server. The URL leads to a valid file on my PC and curl from the node's shell can get the file too.

Ok, and again: 

you have a 404 error. Not an egg issue;)

**Comment by JohnB17** [comment]
![image](https://github.com/parkervcp/eggs/assets/63297273/e0f2c893-c039-4d9e-8c1a-3c0ce1b8e170)
Okay I get this with the original egg.

Here are the variables:
![image](https://github.com/parkervcp/eggs/assets/63297273/e170223d-25ad-4b22-bbb8-06578e8b34c0)

Am I doing something wrong?

**Comment by QuintenQVD0** [comment]
Now it faild because the mods you did are not fully reverted. Download the original egg again and import / update.

**Comment by JohnB17** [comment]
That’s what I did? I downloaded the JSON file and then used the update button on the panel.
