### ISSUE TITLE
[Egg Request]: Update Fivem/TXAdmin version

### ISSUE THREAD

**Issue by Valocai** [parkervcp/eggs#2806]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/parkervcp/eggs/tree/master/game_eggs/gta/fivem

### Links for the download

https://github.com/parkervcp/eggs/tree/master/game_eggs/gta/fivem

### Links for the install docs

https://github.com/parkervcp/eggs/tree/master/game_eggs/gta/fivem

**Comment by parkervcp** [comment]
TXAdmin releases are built into fivem releases. You should be able to manually update txadmin if you want.
