### ISSUE TITLE
FiveM server won't start

### ISSUE THREAD

**Issue by BetTD** [parkervcp/eggs#281]
Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: FiveM
Modified: no

Expected Behavior: The server should start as normal

Actual Behavior:
`Runtime critical type Mono.RuntimeStructs/HandleStackMark not found`
Steps to Reproduce: I installed the server using the FiveM egg, then uploaded my old server files to the appropiate directories, but the server gives that error instead.

Full error log: https://hasteb.in/sejukuyo.lua

**Comment by parkervcp** [comment]
So my understanding here is that you copied your old files over the new files? Thus writing old stuff over new stuff that could have changed massively and broke things?

**Comment by parkervcp** [comment]
There has been no response so I am going to close this out now.
