### ISSUE TITLE
[Egg Request]: Minecraft FTB Direwolf20 1.20 (NeoForge)

### ISSUE THREAD

**Issue by KRDucky** [parkervcp/eggs#2813]
### Does this expand an already existing service

Yes

### Link to a game or software

Minecraft

### Links for the download

https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120?tab=versions

### Links for the install docs

https://feedthebeast.notion.site/Installing-a-Feed-the-Beast-Server-aeaea8a7220945d0ad0357c80c6c9d12

**Comment by QuintenQVD0** [comment]
Have you even tryed the ftb egg?

**Comment by QuintenQVD0** [comment]
The FTB egg can run this.
