### ISSUE TITLE
[Egg Request]: <Rimworld Together>

### ISSUE THREAD

**Issue by skittles-fivem** [parkervcp/eggs#2814]
### Does this expand an already existing service

Yes

### Link to a game or software

https://rimworld-together.fandom.com/wiki/Rimworld_Together_Wiki

### Links for the download

https://github.com/Byte-Nova/Rimworld-Together

### Links for the install docs

https://github.com/Byte-Nova/Rimworld-Together

**Comment by skittles-fivem** [comment]
ik it looks the same BUT this is more maintained and works better
at first i kept trying to use the openworld and connect with the together mod and relized its 2 seperate projects 
both have the same ideas but this works alot better with little issues as they fix it either same day or next day

**Comment by parkervcp** [comment]
@skittles-fivem Can you try out https://github.com/parkervcp/eggs/pull/2820
