### ISSUE TITLE
[Bug]: <Vintage Story>

### ISSUE THREAD

**Issue by Leonard-Vrana** [parkervcp/eggs#2815]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

vintage story

### Modified

No, I did not modify the egg

### Expected Behavior

![image](https://github.com/parkervcp/eggs/assets/94246799/f698798f-e457-4d4b-8ca9-aa9b047e432e)

### Actual Behavior

/entrypoint.sh: line 20: ./VintagestoryServer: cannot execute binary file: Exec format error

### Steps To Reproduce

Step 1: Intrall Vintage story server
Step 2: After install server crashed with error: /entrypoint.sh: line 20: ./VintagestoryServer: cannot execute binary file: Exec format error

### Install logs

https://pteropaste.com/j9vqvngir9cb/

**Comment by QuintenQVD0** [comment]
This egg does not work on arm64
