### ISSUE TITLE
[Bug]: Stormworks Server Version out of Date

### ISSUE THREAD

**Issue by Crazys-Corner** [parkervcp/eggs#2816]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Stormworks

### Modified

No, I did not modify the egg

### Expected Behavior

Install Server, Start, Play

### Actual Behavior

Incompatible game version v1.10.7 (server version v1.10.3) 

### Steps To Reproduce

Step 1. Install Server
Step 2. Make sure ports are allocated correctly
Step 3. Get error when trying to join

### Install logs

https://pteropaste.com/rdw709dqnemy/

**Comment by QuintenQVD0** [comment]
@Crazys-Corner Maybe share the join error?

Also, please send your kernel version `uname -a` and a screenshot of the startup and network tab

**Comment by QuintenQVD0** [comment]
if auto update is set to 1, and you have restarted, then it will pull the latest available version. if that is not compatible with the client then that is an issue you should be taking to the devs as it is not an egg issue.

**Comment by Crazys-Corner** [comment]
Figured it out, they depreciated the Stormworks Dedicated server client and it's now bundled in the game itself, meaning the egg needs to be updated.

**Comment by QuintenQVD0** [comment]
> Figured it out, they depreciated the Stormworks Dedicated server client and it's now bundled in the game itself, meaning the egg needs to be updated.

how do you launch a server with the client then in the latest version in headless mode?

**Comment by Crazys-Corner** [comment]
Stormworks (App ID 573090) is now bundled with the Server Files, so there's an executable file named server64.exe and server.exe, the old Stormworks DS client had these files, now it's just all bundled with the game itself. I'm trying to patch the egg myself currently but it doesn't seem to want to download the game files.

**Comment by QuintenQVD0** [comment]
> Stormworks (App ID 573090) is now bundled with the Server Files, so there's an executable file named server64.exe and server.exe, the old Stormworks DS client had these files, now it's just all bundled with the game itself. I'm trying to patch the egg myself currently but it doesn't seem to want to download the game files.

you willl need to setup steam login with an accounts that owns the game and has steamguard disabled
