### ISSUE TITLE
[Egg Request]: TerraTech Worlds

### ISSUE THREAD

**Issue by PR3SIDENT** [parkervcp/eggs#2817]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/2313330/TerraTech_Worlds/
https://steamdb.info/app/2533070/

### Links for the download

https://terratechworlds.wiki.gg/wiki/Dedicated_Servers

### Links for the install docs

https://terratechworlds.wiki.gg/wiki/Dedicated_Servers

**Comment by ValhallaCommunityOfficial** [comment]
ohh yesss! came here to request this :)

+1 for proton!

**Comment by durzo** [comment]
I just made this and it works fine, playing with 2 friends online right now.

Proxmox VM(s): You'll need to change your Processor Type to `Host` (Default: kvm64)

[egg-terra-tech-worlds.json](https://github.com/parkervcp/eggs/files/14731362/egg-terra-tech-worlds.json)

If it works for others, I may submit as a PR but also happy for someone else to do it

**Comment by QuintenQVD0** [comment]
> I just made this and it works fine, playing with 2 friends online right now.
> 
> Proxmox VM(s): You'll need to change your Processor Type to `Host` (Default: kvm64)
> 
> [egg-terra-tech-worlds.json](https://github.com/parkervcp/eggs/files/14731362/egg-terra-tech-worlds.json)
> 
> If it works for others, I may submit as a PR but also happy for someone else to do it

does it have a console output?

**Comment by durzo** [comment]
> does it have a console output?

No, the binary does not output anything but it is writing logs in `TT2/Saved/Logs/`

**Comment by QuintenQVD0** [comment]
> > does it have a console output?
> 
> No, the binary does not output anything but it is writing logs in `TT2/Saved/Logs/`

can you PR your egg, I edit the PR to give it some console output and then someone else has to test it.

**Comment by durzo** [comment]
PR #2819 submitted. first time, be gentle :)

**Comment by QuintenQVD0** [comment]
> PR #2819 submitted. first time, be gentle :)

I will :)

**Comment by ValhallaCommunityOfficial** [comment]
Egg Works for me! ty

**Comment by QuintenQVD0** [comment]
> Egg Works for me! ty

was that before of after my cleanup commit?
