### ISSUE TITLE
[Egg Request]: Minetrack

### ISSUE THREAD

**Issue by Sissietto** [parkervcp/eggs#2825]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/Cryptkeeper/Minetrack

### Links for the download

https://github.com/Cryptkeeper/Minetrack/archive/refs/heads/main.zip

### Links for the install docs

https://github.com/Cryptkeeper/Minetrack/blob/main/README.md

**Comment by parkervcp** [comment]
the generic nodejs egg can run this.
