### ISSUE TITLE
[Egg Request]: Hell Let Loose

### ISSUE THREAD

**Issue by BumiMandiasDev** [parkervcp/eggs#2827]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/686810/Hell_Let_Loose/

### Links for the download

https://store.steampowered.com/app/686810/Hell_Let_Loose/

### Links for the install docs

https://store.steampowered.com/app/686810/Hell_Let_Loose/

**Comment by parkervcp** [comment]
There is no way to host your own server for Hell Let Loose. you must rent from on of their GSPs at this point.
