### ISSUE TITLE
[Bug]: ARK: Survival Ascended - Not All Additional Arguments Writing to GameUserSettings.ini

### ISSUE THREAD

**Issue by EdTheDuck** [parkervcp/eggs#2829]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

game_eggs/steamcmd_servers /ark_survival_ascended

### Modified

No, I did not modify the egg

### Expected Behavior

When entering server settings, separated by ? and no spaces, that all settings are written to the server's /ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini file.

### Actual Behavior

Settings that work and save in the config file for the server to use:
HarvestAmountMultiplie
DifficultyOffset
OverrideOfficialDifficulty
TamingSpeedMultiplier
AllowFlyerCarryPvE

Settings that to not work, and are not written to the config file:
BabyMatureSpeedMultiplier
EggHatchSpeedMultiplier
MatingIntervalMultiplier

### Steps To Reproduce

Set the following in the "Additional Arguments (Params)" field in startup:

?HarvestAmountMultiplier=3.0?BabyImprintAmountMultiplier=3.0?DifficultyOffset=1.0000?OverrideOfficialDifficulty=5.0000?TamingSpeedMultiplier=3.0?AllowFlyerCarryPvE=true?BabyMatureSpeedMultiplier=3.0?EggHatchSpeedMultiplier=3.0?MatingIntervalMultiplier=3.0

Start server, and check the /ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini to see if the values are set.

### Install logs

https://pteropaste.com/qqltvdq6jgc5

**Comment by QuintenQVD0** [comment]
Startup arguments should not be writen to a config file as their directly passed to the binary.

**Comment by EdTheDuck** [comment]
ah, so it;s the binary writing to the config?
How are we supposed to insert settings into the config, if the file is re-written on each server startup?

Sorry for the wrong logs, I just ran the command listed on the bug creation and didn't actually look at the logs.

**Comment by QuintenQVD0** [comment]
You can only change the config file itself if the server is fully off.

**Comment by EdTheDuck** [comment]
Wow, I was certain I had stopped the server multiple times when changing the contents of the config file, but I guess not.

I appreciate the help and apologies for wasting your time.
