### ISSUE TITLE
[Bug]: Palworld RCON Issue

### ISSUE THREAD

**Issue by Kit4444** [parkervcp/eggs#2830]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

Palworld

### Modified

No, I did not modify the egg

### Expected Behavior

After a restart, still accepting the Console Commands

### Actual Behavior

On the first start, the server accepts Commands from the Panel, however after a restart (due to map change - just that) the server rejects command with "cli: execute: auth: rcon: authentication failed" and I wonder why it only works on the initial boot up, not in the followings.

However after deleting the Server and re-installing the Server with the Egg, it works again - until a reboot is happening.
I'm certainly at the end of my latin and I'd like to get some help.

### Steps To Reproduce

Step 1: Install as normal
Step 2: Start
Step 3: Stop
Step 4: Start - and here it wont accept commands anymore.

### Install logs

https://pteropaste.com/po5jtzf0dydg/

**Comment by QuintenQVD0** [comment]
This is more of a game issue then an egg issue. We set the rcon password in the startup args and the config. And we do the same for enabeling rcon.

**Comment by Ballaual** [comment]
u running latest egg version and confg parser? my server is running since weeks and restarting multiple times daily and my rcon is still working.

**Comment by QuintenQVD0** [comment]
This seems not to be an issue for other people, so please check if you have the latest egg, startup, and parser application. Then it should work. If not come to the discord for this, please.
