### ISSUE TITLE
[Bug]: Enshrouded 

### ISSUE THREAD

**Issue by kochjaber** [parkervcp/eggs#2831]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

game_eggs/steamcmd_servers/enshrouded

### Modified

No, I did not modify the egg

### Expected Behavior

Wanted to join the server either from the steam favourite servers list or searching for the server over the game

### Actual Behavior

Not being able to join the server from the game servers list nor the steam, its sending back this is error: 
“App ID specified by server is invalid”

### Steps To Reproduce

N/A

### Install logs

N/a

**Comment by gOOvER** [comment]
Not an egg issue. Read their Discord

**Comment by Cobras-Hosting** [comment]
what is the discord as it coming up for me two

**Comment by GameAreaCZ** [comment]
![obrazek](https://github.com/parkervcp/eggs/assets/82257025/b03ade40-2fa7-47c4-b671-4009bfd0a518)

**Comment by HaseoTM** [comment]
We will just have to wait for a fix on their end, it's not an egg issue.

**Comment by ColeThayn** [comment]
I'm experiencing the same issue. However, had no issues after the game update. The only two things that changed were the actual game update and a proton update. I can't remember what the proton version was before it pulled a new proton image. The server doesn't fully start.

`container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/steamcmd 
Status: Image is up to date for ghcr.io/parkervcp/steamcmd:proton 
Digest: sha256:cddf3ab3493b6205a74233ad61ff8fe60eef51cc728be5334bd56994d9871e91 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
tid(23) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
Logging directory: '/home/container/.steam/steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '2278520' already up to date.
:/home/container$ proton run ./enshrouded_server.exe
esync: up and running.
CAppInfoCacheReadFromDiskThread took 4 milliseconds to initialize`

**Comment by QuintenQVD0** [comment]
> I'm experiencing the same issue. However, had no issues prior to the game update. Which pulled a new verion of proton. The only two things that changed were the actual game update and a proton update. I can't remember what the proton version was before it pulled a new proton image. I'm aware of the game server not showing up in Enshrouded server list in the game. I have always been able to join via Steam's Game Server browser. The server doesn't fully start.
> 
> ```
> [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
> Pulling from parkervcp/steamcmd 
> Status: Image is up to date for ghcr.io/parkervcp/steamcmd:proton 
> Digest: sha256:cddf3ab3493b6205a74233ad61ff8fe60eef51cc728be5334bd56994d9871e91 
> [Pterodactyl Daemon]: Finished pulling Docker container image
> steam user is not set.
> Using anonymous user.
> tid(23) burning pthread_key_t == 0 so we never use it
> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
> Logging directory: '/home/container/.steam/steam/logs'
> minidumps folder is set to /tmp/dumps
> [  0%] Checking for available updates...
> [----] Verifying installation...
> UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
> -- type 'quit' to exit --
> Loading Steam API...OK
> Connecting anonymously to Steam Public...OK
> Waiting for client config...OK
> Waiting for user info...OK
> "@sSteamCmdForcePlatformType" = "windows"
> Success! App '2278520' already up to date.
> :/home/container$ proton run ./enshrouded_server.exe
> esync: up and running.
> CAppInfoCacheReadFromDiskThread took 4 milliseconds to initialize```
> ```

The startup of the latest egg changed so their is back console output.

**Comment by ValhallaCommunityOfficial** [comment]
Come to find out, it is an egg issue. Goover's enshrouded egg actually works. I can see and join my server after i made the switch.

**Comment by ValhallaCommunityOfficial** [comment]
I deleted my comment. They had a hotfix the same minute i switched eggs and thought the other egg solved it XD

**Comment by ColeThayn** [comment]
Can confirm mine is working as well.

**Comment by QuintenQVD0** [comment]
I am closing this as the egg update fixt the xonsole output and the devs fixt the server.

**Comment by cc3768** [comment]
Im running into a program with this fix
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
tid(23) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
Logging directory: '/home/container/.steam/steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '2278520' already up to date.
:/home/container$ rm ./logs/enshrouded_server.log; proton run ./enshrouded_server.exe & ENS_PID=$! ; tail -c0 -F ./logs/enshrouded_server.log --pid=$ENS_PID
rm: cannot remove './logs/enshrouded_server.log': No such file or directory
tail: cannot open './logs/enshrouded_server.log' for reading: No such file or directory
esync: up and running.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/steamcmd 
Status: Image is up to date for ghcr.io/parkervcp/steamcmd:proton 
Digest: sha256:75d648a2b833296f0a85d1952b8e29123cbe7116722c429061338d4beb446439
