### ISSUE TITLE
[Egg Request]: Arma 2 (Operation Arrowhead)

### ISSUE THREAD

**Issue by Bluscream** [parkervcp/eggs#2832]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/33930/Arma_2_Operation_Arrowhead/

### Links for the download

https://steamdb.info/app/33935/

### Links for the install docs

https://community.bistudio.com/wiki/Arma_Dedicated_Server

**Comment by QuintenQVD0** [comment]
Duplicate #1708
