### ISSUE TITLE
Barrel

### ISSUE THREAD

**Issue by GabBiswajit** [parkervcp/eggs#2833]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/DavyCraft648/Barrel

### Links for the download

https://github.com/BarrelMC/Barrel

### Links for the install docs

Idk 😶

**Comment by ImKringle** [comment]
Hasn't been updated in nearly a year, wouldnt work either way. Bedrock clients cannot backport to v1.19.50 to support this

**Comment by GabBiswajit** [comment]
I think davyCraft start the development again: https://github.com/DavyCraft648/Barrel

**Comment by ImKringle** [comment]
That one would work better, but no releases:
https://github.com/DavyCraft648/Barrel/releases

AFAIK its not possible to compile a JAR file within the install script, so this would just be more suited for compiling the JAR file using an IDE like IntelliJ and uploading the server.jar file to a random [Java](https://github.com/parkervcp/eggs/tree/master/generic/java) egg based server

If he actually starts building releases for this, I'll likely make an egg as its a neat tool. Just requires the dev makes the JAR, cause I wont

**Comment by GabBiswajit** [comment]
https://github.com/DavyCraft648/Barrel/actions/runs/8239727948 here is the jar file idk why he don't release but he provided the jar and active on this fork!

**Comment by ImKringle** [comment]
> https://github.com/DavyCraft648/Barrel/actions/runs/8239727948 here is the jar file idk why he don't release but he provided the jar and active on this fork!

container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -jar Barrel.jar
Starting Barrel Proxy software
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Config file not found! Terminating...

Doesnt work, again needs work from the dev. this one likely is just a missing dependency in their pom.xml file but thats a guess

**Comment by ImKringle** [comment]
> https://github.com/DavyCraft648/Barrel/actions/runs/8239727948 here is the jar file idk why he don't release but he provided the jar and active on this fork!

alright so got it **kind of** working, 
[egg-barrel.json](https://github.com/parkervcp/eggs/files/14819171/egg-barrel.json)

I can see the connection in both Ptero and my bedrock server, but connection fails. Once it gets a few more updates it likely will be usable.

**Comment by ImKringle** [comment]
This doesnt seem like its ready for a PR though, so that beta egg is the most I'll do for now 👋🏼

**Comment by GabBiswajit** [comment]
Thanks 😊

**Comment by QuintenQVD0** [comment]
You can not download files with the install script from action without login in with a github login. 

And this is again a fork of something stoped and will Probably die soon so I am realy tempted to just close this.

**Comment by QuintenQVD0** [comment]
It can stay open for now. I will think about it.

**Comment by GabBiswajit** [comment]
@QuintenQVD0 Please Try Once If It's Stop In Future Than I am sorry but I don't think he close the fork because he run this server, but idk where he run it ☠️ without egg!

**Comment by ImKringle** [comment]
> You can not download files with the install script from action without login in with a github login.
> 
> And this is again a fork of something stoped and will Probably die soon so I am realy tempted to just close this.

egg I made pulls the base git and compiles the JAR in the install script, assuming the software actually gets fixed (and lets it send players) its PR'able as is

I just dont see a point in doing it, when as of now the JAR doesn't work

**Comment by QuintenQVD0** [comment]
I am going to close this. IF you just take literly any mc egg, build the jar yourself or download it from a workflow run and replace the jar on pterodactyl.
