### ISSUE TITLE
[Egg Request]: <DDNet>

### ISSUE THREAD

**Issue by Sizzuns** [parkervcp/eggs#2836]
### Does this expand an already existing service

No

### Link to a game or software

https://ddnet.org  https://steamdb.info/app/412220/

### Links for the download

https://ddnet.org/downloads/    https://steamdb.info/app/412220/depots/

### Links for the install docs

https://steamcommunity.com/sharedfiles/filedetails/?id=2474013400

**Comment by ImKringle** [comment]
[egg-d-d-net.json](https://github.com/parkervcp/eggs/files/14817719/egg-d-d-net.json)

I'll make a PR later today, but you can use this egg to do it - just make sure you set SteamUser/SteamPass variables before installing
