### ISSUE TITLE
[Install Bug]: Phantombot

### ISSUE THREAD

**Issue by Brolofmeistertv** [parkervcp/eggs#2838]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

Phantombot

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

That it works when I installed it :D

### Actual Behavior

[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:java_19 
Digest: sha256:b043512b033070043ab894f0d0559d7d12457de0cbb5a94c6b91f0c877791e45 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)
OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode, sharing)
container@pterodactyl~ java --add-opens java.base/java.lang=ALL-UNNAMED -Djava.security.policy=config/security -Dinteractive -Xms1m -Dfile.encoding=UTF-8 -jar PhantomBot.jar
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
        at java.base/java.lang.String.contains(String.java:2862)
        at com.gmt2001.util.LogFilter.filter(LogFilter.java:28)
        at com.gmt2001.Console.out.println(out.java:47)
        at com.gmt2001.Console.out.println(out.java:43)
        at tv.phantombot.PhantomBot.main(PhantomBot.java:1168)
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

change java version 
I don't know anything else to try to figure out what else could be causing it

### Install logs

/

**Comment by gOOvER** [comment]
thats Not an egg issue. Sounds more like an issue in PB

**Comment by Brolofmeistertv** [comment]
OK, thanks for your help :)

**Comment by QuintenQVD0** [comment]
Something in the config is empty that should not be empty, not an egg issue
