### ISSUE TITLE
[Bug]: Mordhau

### ISSUE THREAD

**Issue by AeonRemnant** [parkervcp/eggs#2839]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

Mordhau

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, boot the server

### Actual Behavior

Install the server, try to boot the server and then nothing happens because the image is deprecated. 

```[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [6a9c4e52-8832-4184-ad30-0fe83568db9e]: environment/docker: failed to run pre-boot process: environment/docker: failed to create container: Error response from daemon: No such image: quay.io/parkervcp/pterodactyl-images:game_mordhau
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false```

### Steps To Reproduce

Get egg. 
Install egg. 
Fail. 

### Install logs

https://pteropaste.com/3142ser5n5e1

**Comment by AeonRemnant** [comment]
Also from running `docker pull quay.io/parkervcp/pterodactyl-images:game_mordhau`

```game_mordhau: Pulling from parkervcp/pterodactyl-images
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/parkervcp/pterodactyl-images:game_mordhau to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/```

**Comment by QuintenQVD0** [comment]
> Also from running `docker pull quay.io/parkervcp/pterodactyl-images:game_mordhau`
> 
> ```
> [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/parkervcp/pterodactyl-images:game_mordhau to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/```
> ```

that is normal as all quay.io images are no longer maintained.

**Comment by QuintenQVD0** [comment]
juse use the steamcmd:debian image, it will work
