### ISSUE TITLE
[Bug]: Space Engineers Vanilla / Torch

### ISSUE THREAD

**Issue by DessertOverlord** [parkervcp/eggs#2842]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

Space Engineers, both Vanilla and Torch

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, start it up, and play. The log I provided is with the Torch egg, but the same issue occurs with the Vanilla egg as well.

### Actual Behavior

Server threw:
```
Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'NLog.Common.InternalLogger' threw an exception. ---> System.TypeInitializatio
nException: The type initializer for 'System.Uri' threw an exception. ---> Syste
m.AccessViolationException: Attempted to read or write protected memory. This is
 often an indication that other memory is corrupt.
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem..ctor()
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at NLog.Common.InternalLogger.GetSettingString(String configName, String envN
ame)
   at NLog.Common.InternalLogger.GetSetting[T](String configName, String envName
, T defaultValue)
   at NLog.Common.InternalLogger.Reset()
   at NLog.Common.InternalLogger..cctor()
   --- End of inner exception stack trace ---
   at NLog.Common.InternalLogger.Debug[TArgument1](String message, TArgument1 ar
g0)
   at NLog.Config.ConfigurationItemFactory.RegisterItemsFromAssembly(Assembly as
sembly, String itemNamePrefix)
   at NLog.Config.ConfigurationItemFactory..ctor(Assembly[] assemblies)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
   at NLog.Config.ConfigurationItemFactory.get_Default()
   at NLog.Targets.Target.Register(String name, Type targetType)
   at Torch.Server.Program.Main(String[] args) in C:\ProgramData\Jenkins\.jenkin
s\workspace\Torch_master\Torch.Server\Program.cs:line 29
wine: Unhandled exception 0xe0434352 in thread 474 at address 00006FFFFF453C57 (thread 0474), starting debugger...
``` 
and hangs instead of starting up, this occurs immediate after wings attempts to invoke the startup line with 
```
:/home/container$ export WINEDLLOVERRIDES="mscoree=n,b;mshtml=n,b"; wine /home/container/Torch.Server.exe -noupdate -nogui -console
```

### Steps To Reproduce

Install server with default options, I used 8 GiB of memory and 25 GiB of disk and gave it an allocation on port 27016.

### Install logs

https://pteropaste.com/lh2c5kxtexfn/

**Comment by gOOvER** [comment]
which CPU are you using?

pls also post output of
hostnamectl status

**Comment by gOOvER** [comment]
Tested and works Like Charm. No problems

**Comment by DessertOverlord** [comment]
CPU is an intel i7-6700k, i'll double check the hostname when I have access to the box again. What should the hostname be?

**Comment by DessertOverlord** [comment]
Static hostname: (unset)
Transient hostname: Neodymium
         Icon name: computer-desktop
           Chassis: desktop 🖥️
        Machine ID: ea93515a1c6141eab0f846acb9abaa03
           Boot ID: a86fdc4a55114c3fbffe74cf74f46014
  Operating System: Rocky Linux 9.3 (Blue Onyx)
       CPE OS Name: cpe:/o:rocky:rocky:9::baseos
            Kernel: Linux 5.14.0-362.24.1.el9_3.x86_64
      Architecture: x86-64
   Hardware Vendor: Gigabyte Technology Co., Ltd.
    Hardware Model: Z170XP-SLI
  Firmware Version: F8

**Comment by gOOvER** [comment]
your cpu is now 10 near 10 years old. Wine nneds actual CPUs. I think the problem is your cpu, since SE Vanilla and Torch runs fine for me

**Comment by parkervcp** [comment]
A 6700k should be sufficient to run a server even with wine.

**Comment by gOOvER** [comment]
this error only happens on old CPU's

wine: Unhandled exception 0xe0434352 in thread 474 at address 00006FFFFF453C57 (thread 0474)

**Comment by DessertOverlord** [comment]
From what I found that exception is just a general .NET exception (not that I'll pretend to know anything about .NET).

I'd be surprised that this is the first issue I've encountered if my hardware is truly a problem, as I've run plenty of different programs on different OS's on this hardware, including 4 other eggs. I will admit I don't know anything about Wine though.

I could spin up a VM and test if Rocky is the problem, but I dunno.

**Comment by DessertOverlord** [comment]
I just spun up a server using the Empyrion Galactic Survival egg, which uses the wine_staging image from the same repo as Space Engineers' wine_latest. Everything installed, I can execute console commands and all that.

I'm pretty confident there isn't some sort of incompability with my OS or hardware with respect to WINE, seems like the issue might be related more to .NET or NLog or something.

**Comment by QuintenQVD0** [comment]
@DessertOverlord To the WINETRICKS_RUN variable try adding mono to the end and then restart the server. (it should not be needed but we never know)

**Comment by DessertOverlord** [comment]
@QuintenQVD0 I just gave that a spin, I can see in the install logs that Winetricks pulled Mono and installed it but I still get precisely the same error. 

Would it have anything to do with the errors that get thrown regarding using a 32-bit prefix versus a 64-bit one? Or are those expected errors?

**Comment by DessertOverlord** [comment]
The install for Mono is actually the one portion that didn't throw that error. I apologize for the use of an image, I'm on mobile right now, but see below:

![Screenshot_20240403_064803_DuckDuckGo](https://github.com/parkervcp/eggs/assets/16036856/7614672e-5ba8-4be3-9cc6-0a491f62f334)

Mono installs without throwing that error, but the other wine installs do throw it.

**Comment by gOOvER** [comment]
then Install dotnet 7 or 8.

latest mono is in dotnet 7

**Comment by DessertOverlord** [comment]
I tried changing the WINETRICKS_RUN variable's dotnet48 section to dotnet7 or dotnet8 (with mono still on there) and no dice, same error.

**Comment by QuintenQVD0** [comment]
Fixt with #2853
