### ISSUE TITLE
[Install Bug]: <Rimworld Together>

### ISSUE THREAD

**Issue by SilentAssassin101** [parkervcp/eggs#2849]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

Rimworld Together Install

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play the game

### Actual Behavior

Server crashed with the following
`/entrypoint.sh: line 20: ./GameServer: No such file or directory`
there is no GameServer directory, just the "Core" directory which only has the following config file contents: 
`{
    "IP": "0.0.0.0",
    "MaxPlayers": 100,
    "Port": 27001,
    "verboseLogs": "false"
}`
I tried reinstalling, reuploading egg, trying different instances, etc. Rimworld Open World and all the other eggs I have used thus far have worked

My VPS has 32GB RAM and 500GB Disk with no other servers running. The VPS is not out of resources in any way. 

### Steps To Reproduce

Step 1: Install Rimworld Together Egg
Step 2: Create a server instance with (in my case) 10240MB Disk, unmetered RAM and CPU
Step 3: Watch server crash on install

### Install logs

https://pteropaste.com/ctiyum3kdvs1

**Comment by QuintenQVD0** [comment]
@SilentAssassin101 The install logs you shared are for openworld not the Rimworld Together egg

**Comment by SilentAssassin101** [comment]
> @SilentAssassin101 The install logs you shared are for openworld not the Rimworld Together egg

woops wrong logs, give me ~5 minutes and I'll send the correct ones to you

**Comment by SilentAssassin101** [comment]
> @SilentAssassin101 The install logs you shared are for openworld not the Rimworld Together egg

https://pteropaste.com/pd70mkmht1ry/
@QuintenQVD0 sorry about that, I was attempting to get an openworld server set up while I made this issue, so that must be why it gave me the wrong logs.

**Comment by QuintenQVD0** [comment]
> > @SilentAssassin101 The install logs you shared are for openworld not the Rimworld Together egg
> 
> https://pteropaste.com/pd70mkmht1ry/ @QuintenQVD0 sorry about that, I was attempting to get an openworld server set up while I made this issue, so that must be why it gave me the wrong logs.

I linked a pull request that should fix this, please try it.
