### ISSUE TITLE
[Bug]: Ark Survival Ascended

### ISSUE THREAD

**Issue by rafaello104** [parkervcp/eggs#2851]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

/game_eggs/steamcmd_servers/ark_survival_ascended

### Modified

No, I did not modify the egg

### Expected Behavior

- setup base settings ( do not touch any custom content -> e.g. mods etc )
- Try different ports (including defaults listed in egg documentation)
- Make sure the second port is available & assigned (game+1 for peer)
- Install server
- Run Server
- Connect with server on local network

### Actual Behavior

- Server launches
- No errors, 11.5GB RAM
- Unable to connect on local network through steam or ark survival ascended server browser
- Test Several different eggs to see if the issue lies outside of Ark SA but all work (the servers listed in picture below all work when running & trying to connect, tested the day of posting this)
![image](https://github.com/parkervcp/eggs/assets/9550947/ec893dfe-3fd9-4171-a897-fc0045178fe9)

### Steps To Reproduce

- Setup a proxmox server
- Run pterodactyl and wings on a CT (not a vm)
- Use Ubuntu 20.04 as OS
- Install Ark SA egg
- Create / Install Server with no custom settings apart from build config required to run
- Run Server
- Try to connect

### Install logs

https://pteropaste.com/t51cad311ybs/

**Comment by rafaello104** [comment]
Not sure if okay if I reply here, but none of the fields really let me fill in tried steps / different approaches, so in short:

- Tried default ports (listed in egg documentation)
- Tried custom ports
- Tried local network via steam servers
- Same but with Ark Browser (checked & unchecked all settings), also use `Ark.UseServerList 0`
- Tried running with & without Battle Eye
- With & Without mods
- Added RAM limit and set to unlimited
- Wanted to change CPU to type `Host` but since I'm running a proxmox CT this is not an option (so not running a vm)
- Checked any and all logs -> no extra information
- Did multiple installations
- **FYI** an older version of the egg used to work when the game had just launched and a very early version of the egg was uploaded, but sadly I deleted this server & the egg thinking the newer version would also work
- Tried running `Satisfactory, 7 Days to Die, Ark Survival Evolved, The Forest, Minecraft, Palworld` at the time of posting this & all of them worked without issue
- Add `-NoBattlEye` as additional command

No idea what's making this fail, would love any help & will gladly provide any extra information

**Comment by parkervcp** [comment]
It's my understanding that ARK Survival Ascended doesn't support the steam server browser.

This sounds like a network issue. As it is a container in proxmox, is the firewall configured to allow access to the ports both udp and tcp? I can't think of anything else to ask at the moment.

**Comment by QuintenQVD0** [comment]
Try dowbgrading to proton 8. 9 is almost unusable for ark ascended.

**Comment by rafaello104** [comment]
> Try dowbgrading to proton 8. 9 is almost unusable for ark ascended.

Will try & report back soon

**Comment by QuintenQVD0** [comment]
> know

some modules do not properly get passed to the kernel or are not enabled. Their no direct docs for it but it is just what we found after a lot of try and error

**Comment by rafaello104** [comment]
@QuintenQVD0 I tried running it with Proton 8 (instead of 9) and same result, I had set up default ports for all (except RCON used custom port for this one but that never seems to be an issue), no mods & battle eye turned on (as is default).

Sadly the browser is nowhere to be found

Since steam server browser is not usable for Ark SA, I figured it might be a port forwarding issue, but alas, all the ports are forwarded and work correctly when tested with any of my other servers (of other games)

**Comment by rafaello104** [comment]
I did see two odd lines in the startup log:
```
[2024.04.03-10.42.27:674][  0]LogCFCore: Warning: Couldn't load mods library from disk
[2024.04.03-10.42.27:674][  0]LogCFCore: User context not loaded from disk
```

It seems strange to me, since I do not have any mods listed & I have no idea what user context it's "missing"?
All in all I ignored them up until now since I also get the following:

```
[2024.04.03-10.43.45:008][  0]Server: "WaffleBloopieTest" has successfully started!
[2024.04.03-10.43.47:750][  0]Commandline:  TheIsland_WP?listen?MaxPlayers=30?SessionName="WaffleBloopieTest"?Port=7777?QueryPort=27015?RCONPort=14037?RCONEnabled=True?ServerPVE=True?ServerPassword=?ServerAdminPassword=[REDACTED] -WinLiveMaxPlayers=30 -oldconsole -servergamelog -Port=7777
```

**Comment by gOOvER** [comment]
> I did see two odd lines in the startup log:
> ```
> [2024.04.03-10.42.27:674][  0]LogCFCore: Warning: Couldn't load mods library from disk
> [2024.04.03-10.42.27:674][  0]LogCFCore: User context not loaded from disk
> ```
> 
> It seems strange to me, since I do not have any mods listed & I have no idea what user context it's "missing"?
> All in all I ignored them up until now since I also get the following:
> 
> ```
> [2024.04.03-10.43.45:008][  0]Server: "WaffleBloopieTest" has successfully started!
> [2024.04.03-10.43.47:750][  0]Commandline:  TheIsland_WP?listen?MaxPlayers=30?SessionName="WaffleBloopieTest"?Port=7777?QueryPort=27015?RCONPort=14037?RCONEnabled=True?ServerPVE=True?ServerPassword=?ServerAdminPassword=[REDACTED] -WinLiveMaxPlayers=30 -oldconsole -servergamelog -Port=7777
> ```

this is only a warning. you can ignore it

**Comment by rafaello104** [comment]
I just managed to get it working:
- Indeed steam server browser does not work, so checking here will never show the server
- `Show password protected servers` (in the game UI) disables non-password restricted servers (this was not clear from the naming)
- Without executing `Ark.UseServerList 0` in the main menu console (with ~ key) the server does not show up
- Proton 9 does not work for me, proton 8 does (for reference, all you need to do, to use proton 8, is change the docker image in the egg config from `...steamcmd:proton` to `...steamcmd:proton_8`)
- It only works with default Query (27015), Game (7777) & Peer (7778) ports (RCON doesn't seem to matter which one you choose)

All of the above claims are ones I tested, if I do any of the above differently, I do not see my server in the list anymore.
