### ISSUE TITLE
[Bug]: Satisfactory not detecting close

### ISSUE THREAD

**Issue by ari-party** [parkervcp/eggs#2852]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Pressing stop should close the server and exit

### Actual Behavior

Pressing stop does close the server but the egg doesn't acknowledge it and you have to kill it

### Steps To Reproduce

1. Create nest and import the egg
2. Create a server
3. Wait for the server to finish starting up
4. Close the server
5. Server will not exit

### Install logs

https://pteropaste.com/9oq8ler13pf7/

**Comment by parkervcp** [comment]
What does the term close mean here? Are you stopping the server from the panel or from the game itself?

**Comment by gOOvER** [comment]
Thats a know issue. Blame the devs for that :) There will be no update for this, until 1.0 is released

**Comment by ari-party** [comment]
> What does the term close mean here? Are you stopping the server from the panel or from the game itself?

Closing in this context is the actual game server closing/exiting

**Comment by parkervcp** [comment]
You didn't answer my question about where you were setting it to stop.

**Comment by ari-party** [comment]
> You didn't answer my question about where you were setting it to stop.

Apologies.

Pressing "Stop" on the panel.

**Comment by gOOvER** [comment]
Server stucks, when you press stop and never really stops. But the devs know that problem
