### ISSUE TITLE
[Install Bug]: <python generic>

### ISSUE THREAD

**Issue by Poseidon281** [parkervcp/eggs#2856]
### Panel Version

1.11.5

### Wings Version

1.11.9

### Service

pythob

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server with the correct version as i configured in the docker image and then i can go to work

### Actual Behavior

No mather what it set the docker image to or how many times i restart or even reinstall the server the python version is always Python 3.7.17. This happend from 1 day to the next. The day before yesterday everything was working fine. Today i login to the server and there was the issue
![Schermafbeelding 2024-04-04 111659](https://github.com/parkervcp/eggs/assets/62171904/5755d2af-be6a-43c5-86ef-af30ae19cdbb)
![Schermafbeelding 2024-04-04 111949](https://github.com/parkervcp/eggs/assets/62171904/3745117f-bf65-46c2-a4d5-45d2f5dec1bb)

### Steps To Reproduce

No idea, because i do not know how this can be

### Install logs

https://pteropaste.com/kxziv9l5a182

**Comment by QuintenQVD0** [comment]
Thats because the install image is still at debian 11 and the server image is at debian 12

**Comment by QuintenQVD0** [comment]
@Poseidon281 Use the updated egg used in #2844 and it will work.

**Comment by Poseidon281** [comment]
@QuintenQVD0 

I used it and i made a new server using that egg and it still does not work. 
![Schermafbeelding 2024-04-04 114529](https://github.com/parkervcp/eggs/assets/62171904/190f0ae9-6051-47d0-afd5-a038482b0a5b)
![Schermafbeelding 2024-04-04 114550](https://github.com/parkervcp/eggs/assets/62171904/0ba67003-8214-49e4-862b-333c3a679df7)

New Logs: https://pteropaste.com/7rvode1k2gos

**Comment by QuintenQVD0** [comment]
fatal: repository '.git' does not exist
Installing python requirements into folder
install complete

now your install faild, you did not properly setup the repo pull so it would not do anything

**Comment by Poseidon281** [comment]
@QuintenQVD0 

It was you that made a mistake i think when you update the dockerfiles you made a typo as i said here: https://github.com/parkervcp/yolks/pull/230#discussion_r1551359822

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0
> 
> It was you that made a mistake i think when you update the dockerfiles you made a typo as i said here: [parkervcp/yolks#230 (comment)](https://github.com/parkervcp/yolks/pull/230#discussion_r1551359822)

still would not cause this normally but I updated it.

**Comment by Poseidon281** [comment]
> > @QuintenQVD0
> > It was you that made a mistake i think when you update the dockerfiles you made a typo as i said here: [parkervcp/yolks#230 (comment)](https://github.com/parkervcp/yolks/pull/230#discussion_r1551359822)
> 
> still would not cause this normally but I updated it.

Oke how long does the docker image take to update because it still is 3.7 . Does parker need to do something first or do i just need to wait a little bit or do i need to make a new server again?

**Comment by QuintenQVD0** [comment]
> > > @QuintenQVD0
> > > It was you that made a mistake i think when you update the dockerfiles you made a typo as i said here: [parkervcp/yolks#230 (comment)](https://github.com/parkervcp/yolks/pull/230#discussion_r1551359822)
> > 
> > 
> > still would not cause this normally but I updated it.
> 
> Oke how long does the docker image take to update because it still is 3.7 . Does parker need to do something first or do i just need to wait a little bit or do i need to make a new server again?

it builded, try hitting restart, it will re-pull the latest one
