### ISSUE TITLE
Code-Server egg request 

### ISSUE THREAD

**Issue by NineBallAYAYA** [parkervcp/eggs#286]
Service: Code-Server

Does this expand an already existing service: Y

What it is: its a vscode in browser application that allows me to code on a low powered chromebook while on the go.

Link for full/manual download: https://github.com/cdr/code-server

Link to dockerfile: https://github.com/cdr/code-server/blob/master/Dockerfile

Link for install steps/docs: https://github.com/cdr/code-server/blob/master/README.md

**Comment by parkervcp** [comment]
I am going to go with a no on this one. This is way too close to hosting a webserver. Also their dockerfile sets their user to be able to run root whenever and that's a no go for me.

**Comment by NineBallAYAYA** [comment]
alright, well thanks for looking at it and making all these other eggs. could you point me in the right direction for doing it myself? I have limited knowledge of docker. 

(i am also new to github not sure if this will reopen it, if it does sorry...)
