### ISSUE TITLE
[Bug]: Palworld

### ISSUE THREAD

**Issue by Tealk** [parkervcp/eggs#2860]
### Panel Version

1.11.5

### Wings Version

.11.11

### Service

palworld

### Modified

No, I did not modify the egg

### Expected Behavior

Server is updateing

### Actual Behavior

Server crash with:
```
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
tid(22) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '2394010' already up to date.
:/home/container$ /home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publicip=${PUBLIC_IP} -port=${SERVER_PORT} -publicport=${SERVER_PORT} -servername="${SERVER_NAME}" -players=${MAX_PLAYERS} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword=\"${SERVER_PASSWORD}\""; fi) -adminpassword="${ADMIN_PASSWORD}"
/entrypoint.sh: line 89: /home/container/Pal/Binaries/Linux/PalServer-Linux-Test: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
```

### Steps To Reproduce

- Automatic update has been implemented
- Server no longer starts

### Install logs

https://pteropaste.com/vhsavvxkq6kj

**Comment by QuintenQVD0** [comment]
Your egg is out of date, update the egg and then update the startup of all already made servers. And please use the right egg(in your case the **NON** proton one)

**Comment by QuintenQVD0** [comment]
and because your egg is that old, you will also need to hit reinstall.

**Comment by Tealk** [comment]
i updated the egg before the bug report, the error remains.

**Comment by Tealk** [comment]
Update:
![image](https://github.com/parkervcp/eggs/assets/12276250/2fd678f0-f70c-49cf-b770-9a49922180af)

Reinstall:
![image](https://github.com/parkervcp/eggs/assets/12276250/dfdf4cb8-756c-4f68-bd5b-ddd6658ea401)


try to start:
```
Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
tid(22) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '2394010' already up to date.
:/home/container$ /home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publicip=${PUBLIC_IP} -port=${SERVER_PORT} -publicport=${SERVER_PORT} -servername="${SERVER_NAME}" -players=${MAX_PLAYERS} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword=\"${SERVER_PASSWORD}\""; fi) -adminpassword="${ADMIN_PASSWORD}"
/entrypoint.sh: line 89: /home/container/Pal/Binaries/Linux/PalServer-Linux-Test: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
```

**Comment by QuintenQVD0** [comment]
As I told you, The startup of already made servers does not update, do it manual!

**Comment by Tealk** [comment]
now I understand what you mean, the field "Startup Command" in the admin settings still needs to be adjusted.

**Comment by sebastianbingham** [comment]
@QuintenQVD0—Thanks for pointing me to the right issue. I did a quick search for Palworld and didn't find anything.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0—Thanks for pointing me to the right issue. I did a quick search for Palworld but didn't find anything. Are there any thoughts on an "Egg version" to check?

did you read up in this conversation?

Update your egg. and then on every already made server change the startup to the one that now comes with the egg.

**Comment by sebastianbingham** [comment]
In my previous communication, I may not have articulated my question with sufficient clarity. I inquired about the potential integration of a version field in the Egg system. This addition would enable users, including @Tealk and myself, to readily identify and reference the most current version, thereby mitigating the frequency of redundant issue reports. This approach could also prevent unnecessary friction caused by responses from individuals, such as @QuintenQVD0, whose interactions have occasionally appeared dismissive and unprofessional. @parkervcp

**Comment by QuintenQVD0** [comment]
> In my previous communication, I may not have articulated my question with sufficient clarity. I inquired about the potential integration of a version field in the Egg system. This addition would enable users, including @Tealk and myself, to readily identify and reference the most current version, thereby mitigating the frequency of redundant issue reports. This approach could also prevent unnecessary friction caused by responses from individuals, such as @QuintenQVD0, whose interactions have occasionally appeared dismissive and unprofessional. @parkervcp

We now their is no version control at all in eggs, you just have to go of the github last edit that or the export_at time. 
(for that you have to be at the panel repo)

and about the response,
was made before you made your message change.
![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/c42e244e-0e02-4cb8-9947-0cf6b1f46389)

That's fine you can find that from me. But this is all done in everyone free time. We (and for the last year - year and a half I am the only real active one maintain this repo and the eggs. I am very strest in real live but do not want to stop doing this as I love to do this. and no worry, parker does read this all.

As it seems you insist, I take a step back from responding to people and will just close and merge issue as then i can not be dismissive or unprofessional.

**Comment by parkervcp** [comment]
@sebastianbingham  Egg versioning has been discussed in the past and it's probably something that should be either built into the panel or an automation that is ran on commit that increments a value. Right now that's not going to be happening.

I understand the frustration and appreciate that you have figured this out, but I will say that not everyone speaks the same language natively and that may be the cause for some of these misunderstandings.
