### ISSUE TITLE
[Bug]: Palworld Egg

### ISSUE THREAD

**Issue by sebastianbingham** [parkervcp/eggs#2862]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Palworld

### Modified

No, I did not modify the egg

### Expected Behavior

Start Palworld Server
Palworld Server Boots

### Actual Behavior

Received error: /entrypoint.sh: line 89: /home/container/Pal/Binaries/Linux/PalServer-Linux-Test: No such file or directory

### Steps To Reproduce

Reporting that /home/container/Pal/Binaries/Linux/PalServer-Linux-Test might need to be changed to /home/container/Pal/Binaries/Linux/PalServer-Linux-Shipping

Corrected in Startup Command and everything works fine now. Maybe related to the dedicated server patch (https://store.steampowered.com/news/app/1623730/view/4183355194463411568?l=english)

### Install logs

N/A

**Comment by QuintenQVD0** [comment]
Duplicate #2860 , same for you the egg is not up-to-date so is your startup.
