### ISSUE TITLE
[Install Bug]: dotnet 8.0

### ISSUE THREAD

**Issue by Rabergsel** [parkervcp/eggs#2865]
### Panel Version

Irrelevant

### Wings Version

Irrelevant

### Service

dotnet/8

### Modified

No, I did not modify the egg

### Expected Behavior

It will install the .NET 8.0 framework

### Actual Behavior

It did not find the image:

Error Event [c46b34f1-a848-49b4-af4b-bcab980db3ab]: environment/docker: failed to run pre-boot process: environment/docker: failed to create container: Error response from daemon: No such image: ghcr.io/parkervcp/yolks:dotnet_8

### Steps To Reproduce

Step 1: Upload Egg JSON like provided in this Repo
Step 2: Choose .NET 8
Step 3: Run Installation.

NOTE: The egg does work with all other Version of .NET

### Install logs

unable to do so

**Comment by parkervcp** [comment]
This issue can be because you are on an ARM based server and that image isn't built for arm.

**Comment by Rabergsel** [comment]
Hi,
thanks for the fast answer.
Is there any way to change that?

**Comment by QuintenQVD0** [comment]
not to do difficult but they are build for that?
https://github.com/parkervcp/yolks/blob/master/.github/workflows/dotnet.yml#L41

That is wy we use that setup script?

**Comment by Rabergsel** [comment]
I really cannot provide any further information.
The server is a virtual one, I do not have any access to the SSH of the instance on it, a friend has it.
I only know that .NET 6 worked without any problems.
.NET 8 says it cannot find the image, which is weird....

**Comment by QuintenQVD0** [comment]
on amd64 it still pulls fine:
![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/29a4808f-bb2c-496c-82be-d864bd7b89c7)

**Comment by QuintenQVD0** [comment]
I just tryed on an arm64 machine an it also works just fine.

![afbeelding](https://github.com/parkervcp/eggs/assets/67589015/5dbd618a-e4e1-487a-a1f7-d7127c628d67)

Please try to pull it on the host, as their maybe some disk space issue or a dns issue.

**Comment by QuintenQVD0** [comment]
I am going to close this as this seems to be a system issues or DNS / disk space issue.

If you still have this problem then please come to the discord or just comment again on this as we have notifications turned on.
