### ISSUE TITLE
[Bug]: Parkertron 

### ISSUE THREAD

**Issue by FreddieDK** [parkervcp/eggs#2867]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

bots/discord/parkertron

### Modified

No, I did not modify the egg

### Expected Behavior

Starting the instance normally 

### Actual Behavior

:/home/container$ ./parkertron
./parkertron: error while loading shared libraries: libtesseract.so.4: cannot open shared object file: No such file or directory

### Steps To Reproduce

1. Install/updating to the latest version of docker
2. Restarting the parkertron instance
Or Reinstalling the instance. (same error)

### Install logs

https://pteropaste.com/51w68wxwdxo8

**Comment by QuintenQVD0** [comment]
Yes it is known. Update the install image from bullseye to bookworm. Then it will work.

**Comment by QuintenQVD0** [comment]
The PR that updates this egg is now merged so I am closing this. Thank you for your patience!
