### ISSUE TITLE
Wait Close: [Install Bug]: Palworld Already Updated Egg 4/6/2024 #2866

### ISSUE THREAD

**Issue by Kuroo2021** [parkervcp/eggs#2868]
### Panel Version

1

### Wings Version

1

### Service

1

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

https://github.com/parkervcp/eggs/issues/2866

QuintenQVD0 - Closed before waiting for reply to issue and was incorrect of closing it. Please wait a bit more than 45 minutes before closing the ticket and for replies; yes, the egg was updated today, and it was having the same issue as before. Check other ticket for details not to close. tyPlease wait a bit more than 45 minutes before closing the ticket and for replies; yes, the egg was updated today, and it was having the same issue as before.

### Actual Behavior

Above

### Steps To Reproduce

1
2
3

### Install logs

N\A

**Comment by Kuroo2021** [comment]
More given in other ticket.

**Comment by gOOvER** [comment]
> More given in other ticket.

and why open an other ticket?

**Comment by QuintenQVD0** [comment]
The error you stated would have been resolved if you did what I asked.
I have notifcations on for everything so even if their is an issue after the closed then I and some other would still read that.

**Comment by QuintenQVD0** [comment]
I reopened the other one for you. as it seems like you still are having issues. But I am going to close this one
