### ISSUE TITLE
Question regarding Discord.js egg's Git system.

### ISSUE THREAD

**Issue by ThePixelord** [parkervcp/eggs#287]
Hi, I was considering using your Discord.js egg (and its Git integration) but I have a question about how it pulls requests: does it support giving credentials, e.g. for pulling from a private Git service?
I may be sounding dumb here, and I apologise for that, but I'd just like to clarify it. Thanks!

**Comment by parkervcp** [comment]
Currently it doesn't support that. You are free to add the support if you want.

Please take general questions to Discord.

https://discordapp.com/invite/pterodactyl
