### ISSUE TITLE
[Install Bug]: REHLDS 

### ISSUE THREAD

**Issue by skenda-unikkatil** [parkervcp/eggs#2875]
### Panel Version

1.11.11

### Wings Version

1.11.11

### Service

REHLDS CS 1.6

### Modified

No, I did not modify the egg

### Expected Behavior

server is not runin and egg installed onlly rehlds and not the addons but l traid to add with FTP addons and l good the same isue server are not starting Counter Strike 1.6 l dont use steam for thet panel

### Actual Behavior

server not starting 

### Steps To Reproduce

maybe the egg and can you explain me wher to add new link to download my relhds

### Install logs

test

**Comment by QuintenQVD0** [comment]
No logs means we can not help you.

**Comment by QuintenQVD0** [comment]
I am for now closing this as without any logs or useful info we can not debug or help you troubleshoot. (It works fine for me, can be buggy on first install and might have to hit reinstall a time 2 to get it to work, steamcmd issue)

If you do read this message. Please
1. Update your egg
2. Hit reinstall
3. post install logs and I will haply reopen this for you
