### ISSUE TITLE
[Egg Request]: Arclight

### ISSUE THREAD

**Issue by Secondyou** [parkervcp/eggs#2876]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/IzzelAliz/Arclight

### Links for the download

https://files.hypertention.cn/v1/files/arclight/branches

### Links for the install docs

https://wiki.izzel.io/s/arclight-docs/doc/arclight-wiki-jFj8TXTeIz

**Comment by QuintenQVD0** [comment]
Duplicate #2741 #2739 #1785
