### ISSUE TITLE
[Bug]: Python Generic

### ISSUE THREAD

**Issue by crocosnipe** [parkervcp/eggs#2878]
### Panel Version

1.11

### Wings Version

1.11

### Service

generic/python

### Modified

No, I did not modify the egg

### Expected Behavior

I expect that if I add „mariadb“ to the additional package list, that I will install as normally as on my windows pc or on my other Linux server. So I can access my mariadb via Python.

### Actual Behavior

I add „mariadb“ to my additional package list. When I now start the server I get the error seen in the pictures:

https://ibb.co/tYbWWdL
https://ibb.co/fpRkXsv

### Steps To Reproduce

Step 1: Create a new Python 3.12 Server
Step 2: Go to startup and add mariadb to additional packages
Step: 3: Go back to console and start the server

btw it is not working with any other database connector like psycopg2 for postgresql. Not working on any other server

### Install logs

https://pteropaste.com/cz8pvjazd3dw

**Comment by QuintenQVD0** [comment]
This module requires MariaDB to be started in the background. This is not possible with pterodactyl as there is no systemd
