### ISSUE TITLE
Add PhantomBot Egg (Discord/Twitch Bot)

### ISSUE THREAD

**Issue by TheSoulrester** [parkervcp/eggs#288]
Service: Discord/Twitch Bot

Does this expand an already existing service: Y

Link to game: https://phantom.bot/

Links for server downloads: https://phantom.bot/#download

Links for install steps/docs: https://community.phantom.bot/c/documentation

**Comment by TheSoulrester** [comment]
as a short reminder: Will this be implemented soon or will I have to wait even longer for it?

**Comment by gOOvER** [comment]
There is not really a Dockerimage ready for it. Thats the problem i think

**Comment by NgLoader** [comment]
Looks easy for me, I commit it soon (currently running on my server) (testing...)

**Comment by NgLoader** [comment]
#441

**Comment by parkervcp** [comment]
This has been merged.
