### ISSUE TITLE
Add Feather MC server

### ISSUE THREAD

**Issue by parkervcp** [parkervcp/eggs#289]
Service: Minecraft Feather Server
Does this expand an already existing service: Y
Link to game: https://www.minecraft.net/en-us/

Links for server downloads: https://github.com/caelunshun/feather

Links for install steps/docs: https://github.com/caelunshun/feather

**Comment by Sir3lit** [comment]
Would you rather this egg download the pre-compiled from the GitHub? or compile it on install?

**Comment by parkervcp** [comment]
I already pull the compiled version in my install script.

I was thinking about the map that doesn't exist because one needs to be uploaded.

**Comment by parkervcp** [comment]
Please check here - https://github.com/parkervcp/eggs/tree/add/feather/minecraft_java/feather

**Comment by Sir3lit** [comment]
Curious why you run it in the `base_debian` image works fine for me in `pterodactyl/core:java`

Apparently the IP not changing to something other than 127.0.0.1 is a known issue and is already fixed but not released yet.

**Comment by parkervcp** [comment]
It's not java based. That is why.

**Comment by NgLoader** [comment]
🤔 where is the problem?

**Comment by parkervcp** [comment]
There was a bug in the software somewhere. I have most of this egg already complete.

**Comment by NgLoader** [comment]
Debug your curl request 😅 
you will see its a permanently redirection.
use ``curl -Ls "https://...`` instead

**Comment by NgLoader** [comment]
the server is running fine for me

**Comment by NgLoader** [comment]
![image](https://user-images.githubusercontent.com/13753840/76157340-d259fe80-6107-11ea-833b-382cef99c972.png)

**Comment by parkervcp** [comment]
The bug wasn't in my curl. But the software itself. not changing from 127.0.0.1 is what we were talking about...

**Comment by NgLoader** [comment]
you mean that? [issue](https://github.com/feather-rs/feather/issues/148)

**Comment by parkervcp** [comment]
That was fixed after my comment yes.

**Comment by parkervcp** [comment]
@NgLoader Want to look at it now?
