### ISSUE TITLE
How to set gta sa:mp max players ?

### ISSUE THREAD

**Issue by HostRK1** [parkervcp/eggs#291]
Hello,

I want to set a maxplayers variable for gta sa:mp so that the user can't edit it.

The variable should be in server.cfg at the maxplayers line. 
I tried to do this via the variable option: [![Screenshot from Gyazo](https://gyazo.com/c6af3017dbb3d753e3c6f478d73ba2ef/raw)](https://gyazo.com/c6af3017dbb3d753e3c6f478d73ba2ef)
And added it in the configuration section: [![Screenshot from Gyazo](https://gyazo.com/3c18860979f160d04cc7e74a031d5b83/raw)](https://gyazo.com/3c18860979f160d04cc7e74a031d5b83)

But it doesn't really work, what have I done wrong ? I don't understand and I didn't find any aditional documentation to help me do this... Maybe I've set the name wrong in the configuration file section ? it shouldn't be {{server.build.env.player_slots}} ? 
I've set that name from the server.json file: [![Screenshot from Gyazo](https://gyazo.com/243d4fe42aa9e683282b13c25ccc442f/raw)](https://gyazo.com/243d4fe42aa9e683282b13c25ccc442f)

Also you could add this variable by default and set it to maximum 1000 players and the hosts can edit it if they want to.

**Comment by parkervcp** [comment]
I am not setting this by default. I try to avoid force a max_players variable. I understand some have a variable for it but this isn't an issue for this specific issue.

If you want help with this please ask in the #eggs channel on discord.
