### ISSUE TITLE
Fix for Mordhau - Debian systems running 64 bit

### ISSUE THREAD

**Issue by lpjn** [parkervcp/eggs#294]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number) 0.7.15
Daemon Version: (version number)
Service: (minecraft/factorio/etc)
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)

Expected Behavior: Mordhau server starts

Actual Behavior: Mordhau server crashes and throws the below

:/home/container$ ./MordhauServer.sh /Game/Mordhau/Maps/Grad/FL_Grad?MaxSlots=48? -USEALLAVAILABLECORES -Port=27554 -queryport=27015 -beaconport=15000
/home/container/Mordhau/Binaries/Linux/MordhauServer-Linux-Shipping: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------

Steps to Reproduce: (Step by step what to do to cause the issue)

Install mordhau server via usual egg

Start server

FIX:

Install 32bit Libraries

https://developer.valvesoftware.com/wiki/SteamCMD#32-bit_libraries_on_64-bit_Linux_systems

**Comment by parkervcp** [comment]
If you read it specifically calls out libcurl-gnutls Which is not a 32 bit library. So your fix is incorrect. 

You didn't fill out the issue correctly so I am closing this.
