### ISSUE TITLE
[Out of memory: false]: <Palworld>

### ISSUE THREAD

**Issue by AAvic** [parkervcp/eggs#2943]
### Panel Version

1.11.

### Wings Version

x

### Service

Palworld

### Modified

No, I did not modify the egg

### Expected Behavior

[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1714855729
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '2394010' already up to date.
:/home/container$ /home/container/Pal/Binaries/Linux/PalServer-Linux-Test Pal EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publicip=5.178.65.8 -port=25581 -publicport=25581 -servername="${SERVER_NAME}" -players=32 $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword=\"${SERVER_PASSWORD}\""; fi) -adminpassword="${ADMIN_PASSWORD}"
/entrypoint.sh: line 89: /home/container/Pal/Binaries/Linux/PalServer-Linux-Test: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Actual Behavior

I have update the egg and i restart the server. I get the error Out of memory: false.

The memory on the server is more than 80gb so there is no out of memory problem.

### Steps To Reproduce

I have install the server again still the same probleem.

### Install logs

x

**Comment by QuintenQVD0** [comment]
Your egg or / and startup is out of date. Also read this egg readme.

**Comment by AAvic** [comment]
Hi Quinten,

I have update the egg and the startup and i read the egg but still i get the out of memory: False.

I use this file.
[egg-palworld1.json](https://github.com/pelican-eggs/eggs/files/15299479/egg-palworld1.json)


![SCript for the egg](https://github.com/pelican-eggs/eggs/assets/11776513/b2de2a25-1628-4ba0-9399-9f07bf5530cf)

I have restart the server and the server was updating but still the same code.


reinstall the server and still not working.

This is the startup command:

./PalworldServerConfigParser; (while read cmd; do rcon -s -a "localhost:$RCON_PORT" -p "$ADMIN_PASSWORD" "$cmd";done) < /dev/stdin & /home/container/Pal/Binaries/Linux/PalServer-Linux-Shipping Pal -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -port={{SERVER_PORT}} -publicport={{SERVER_PORT}} -servername="{{SERVER_NAME}}" -players={{MAX_PLAYERS}} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword=\"${SERVER_PASSWORD}\""; fi) -adminpassword="{{ADMIN_PASSWORD}}" -rcon
