### ISSUE TITLE
SQUAD - Start up Params incorrect

### ISSUE THREAD

**Issue by lpjn** [parkervcp/eggs#297]
Panel Version: (version number) 0.7.15
Daemon Version: (version number) 0.6.12
Service: (minecraft/factorio/etc) Squad
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) No

Expected Behavior: Server to start

Actual Behavior: Server fails, cannot find the ./SquadServer.sh file. 

Steps to Reproduce: (Step by step what to do to cause the issue) Import Squad egg, restart daemon service, start server

FIX: Manually modify the param to be ./SquadGameServer.sh - easy workaround but thought I'd highlight this.

**Comment by parkervcp** [comment]
So what it looks like is that they renamed the start script name

**Comment by parkervcp** [comment]
@lpjn can you try setting the start command to `./SquadGame/Binaries/Linux/SquadGameServer  Port=27015 QueryPort=27016`

**Comment by lpjn** [comment]
```
[2019.10.01-16.06.08:095][ 50]LogSquad: Error: No target or source were passed in for finding shortest distance
[2019.10.01-16.08.07:086][954]LogEasyAntiCheatServer: [Cerberus] [Backend] Connection established.
[2019.10.01-16.10.07:120][911]LogEasyAntiCheatServer: [Cerberus] [Backend] Disconnected.
[2019.10.01-16.12.07:232][872]LogEasyAntiCheatServer: [Cerberus] [Backend] Connection established.
[2019.10.01-16.14.07:266][829]LogEasyAntiCheatServer: [Cerberus] [Backend] Disconnected.
```
The above is the latest in the console with the above startup command used, the server is neither marked as started and does not appear in the server list. Using the below start up params I can see the server in the server list however the server also stays at Starting.

**Comment by Sir3lit** [comment]
This could be closed? seems to be fixed in the egg?
 https://github.com/parkervcp/eggs/blob/master/squad/squad/egg-squad.json#L11

**Comment by Sir3lit** [comment]
This is fixed with https://github.com/parkervcp/eggs/pull/320

**Comment by lpjn** [comment]
Hey, I installed the new egg and restarted wings. The install fails with the below:

/mnt/install/install.sh: line 18: ${{SRCDS_APPID}}: bad substitution
cp: cannot stat '/mnt/server/steam/linux32/steamclient.so': No such file or directory
chmod: cannot access '/mnt/server/SquadGame/Binaries/Linux/SquadGameServer': No such file or directory

Multiple daemon's tested, all same error during install.

**Comment by lpjn** [comment]
I used the master branch egg, changed the Start Configuration & Configuration Files, added the variables manually and amended the start up params and it works. Below is my version of the egg.

https://hastebin.com/gusidurara.json
