### ISSUE TITLE
Ark ports not working

### ISSUE THREAD

**Issue by JKJameson** [parkervcp/eggs#298]
I can't get connect to ARK server (other eggs tested, are working)
Connection refused.
Ports 7777, 7778, 27015 and 27020 configured in the server.

Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: ark survival evolved
Modified: no

**Comment by SheppeR** [comment]
How did you try to connect to the server ?

**Comment by JKJameson** [comment]
I tried to add all of the ports to the Steam Server Browers as a favourite but none of them respond.
The server is using 2GB of RAM and I see the ShooterGame process running in top.

`Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[ 0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '376030' already up to date.
:/home/container$ cd ShooterGame/Binaries/Linux && ./ShooterGameServer Ragnarok?listen?SessionName='Arkfall'?ServerPassword=?ServerAdminPassword=u7c54ETtk95U?Port=7777?MaxPlayers=20?RCONPort=27020?QueryPort=27015?RCONEnabled=false -server -log
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110`

**Comment by JKJameson** [comment]
Are there any kind of special requirements for docker networking?
I can connect to a Factorio server running on the same IP.
I can also connect to a test CS:GO server on a different port.
I'm a little stumped as to why I can't connect to Ark.

**Comment by SheppeR** [comment]
There is no console output for ark on linux so status on panel is wrong, a server boot in 4/5min sometimes 10/15. You will aslo need more ram for your server, my vanilla one use actualy 5g with only 4 players. just add you ip:queryport on steam and wait 10/15 min
