### ISSUE TITLE
Add Shoutcast Server

### ISSUE THREAD

**Issue by newbie029** [parkervcp/eggs#309]
Service: Shoutcast Server

Does this expand an already existing service: N
Link to game: https://www.shoutcast.com/Pricing/Software
Links for server downloads: http://download.nullsoft.com/shoutcast/tools/sc_serv2_linux_x64-latest.tar.gz
Links for install steps/docs: https://www.linode.com/docs/applications/media-servers/how-to-install-shoutcast-dnas-server-on-linux/

**Comment by Sir3lit** [comment]
I've made an egg for this, but it doesn't have the encoder or anything else. Is this what you're looking for?
[https://justmyrandomstuff.com/img/9EljOQD.jpg](url)

**Comment by newbie029** [comment]
Yes that was what I looking for,
It works like a minecraft bedrock vanilla server right?

**Comment by Sir3lit** [comment]
Minecraft and a shoutcast server have NOTHING in common.....Like at all.... You sure you know what you're looking for?

**Comment by newbie029** [comment]
I have tried to run sc_serv with minecraft bedrock vanilla egg before,
I know what I'm looking for

**Comment by Sir3lit** [comment]
Could you explain how they're supposed to work together?

**Comment by newbie029** [comment]
Yes I just tried uploading sc_serv to minecraft vanilla bedrock because the file looks similar to me.
Dont know what changes I made to make it works before
https://i.imgur.com/GVXxc21.png
Now its not work anymore

**Comment by mattmalec** [comment]
Are you out of your mind. A radio broadcasting service and a version of Minecraft have nothing in relation with each other. It's like porn and spaghetti. Completely unrelated things.

**Comment by newbie029** [comment]
Im talking about the egg not the game.
My english is not really good so I think we have some misunderstand here.
I know what minecraft is
I know what shoutcast is

**Comment by newbie029** [comment]
@Sir3lit Can I have the egg please?

**Comment by newbie029** [comment]
I run shoutcast on Minecraft Vanilla Bedrock EGG
https://i.imgur.com/wI67aiT.png

**Comment by Sir3lit** [comment]
I only have the server itself not the transcoder

**Comment by newbie029** [comment]
Can I see?

**Comment by Sir3lit** [comment]
I mean I posted a picture of it. That's all it is at this stage

**Comment by newbie029** [comment]
Oh okay, I'll just make my own egg

**Comment by toster234** [comment]
@newbie029 Can you publish your egg?

**Comment by Rezanans-wow** [comment]
Hello! I uploaded my version of egg Shoutcast. Its have bug with server status, but shoutcast work :1st_place_medal: 
https://github.com/Rezanans-wow/Shoutcast-server-egg

**Comment by toster234** [comment]
@Rezanans-wow thanks! I will try it 👍
