### ISSUE TITLE
Squad Egg - master branch | Shows 'Starting' in Ptero Server view

### ISSUE THREAD

**Issue by lpjn** [parkervcp/eggs#315]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number) 0.7.15
Daemon Version: (version number) 0.6.12
Service: (minecraft/factorio/etc) Squad
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) No

Expected Behavior: Service displays started once online

Actual Behavior: Service remains on a blue status of Starting when online. 

Steps to Reproduce: (Step by step what to do to cause the issue)

Create server with Squad egg, start it and return to Servers view on ptero USER panel

**Comment by parkervcp** [comment]
Please read the main page of the repo next time. If you had asked in the discord server we would have told you the same thing.

![image](https://user-images.githubusercontent.com/1207679/65966291-e0577500-e42d-11e9-99de-b970840f499d.png)

**Comment by parkervcp** [comment]
Also you already have an open issue for squad you have seem to forgotten/ignored.

Please use that.
