### ISSUE TITLE
FTB | ServerCrashing issue.

### ISSUE THREAD

**Issue by LewisBelton** [parkervcp/eggs#32]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.6
Daemon Version: 0.5.5
New Service: No
Service: FTB
Modified: Only as shown in Discord - Just the default pack, which you said is fine.

Expected Behavior: Feed the Beast Server is created, and boots up with the corresponding Mod Pack which in my case was: https://www.feed-the-beast.com/projects/ftb-infinity-evolved

Actual Behavior: Server is created, installs within 1-2 minutes, looks fine FTB files are dropped into the correct locations by the look of them, Server crashes when you try to boot it. Logs look fine and don't seem to show anything of any use.

Steps to Reproduce: No idea really.

If this is a request for a new service then you can add info here like links to the site where the server files can be found. If it is a steamcmd game have you looked at the custom source engine service yet?

Logs:

Console Log: https://hastebin.com/hefupeguzu.vbs
Daemon Logs: https://hastebin.com/zozikivali
Install Logs: https://hastebin.com/comipunofi.md

**Comment by parkervcp** [comment]
Startup changes were needed for this server. I need to test on others now as well.
