### ISSUE TITLE
Arma 3 - Server.cfg is un-editable in File Viewer

### ISSUE THREAD

**Issue by lpjn** [parkervcp/eggs#322]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number) 0.7.15
Daemon Version: (version number) 0.6.12
Service: (minecraft/factorio/etc) [Arma 3](https://github.com/parkervcp/eggs/tree/master/arma/arma3)

Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) No

Expected Behavior: basic.cfg & server.cfg in root file viewer are editable

Actual Behavior: basic.cfg & server.cfg in root file viewer are not editable.

Steps to Reproduce: (Step by step what to do to cause the issue)
Create Arma 3 Server
Go to file viewer

**Comment by parkervcp** [comment]
This is not an egg issue. It doesn't manage the editable files.

I am fairly certain it's a file size issue.

https://i.imgur.com/44DCCcz.gif

**Comment by parkervcp** [comment]
It's not even the file size either.

It's not an egg issue though.
