### ISSUE TITLE
Discord Bot (Bastion)

### ISSUE THREAD

**Issue by lrmtheboss** [parkervcp/eggs#324]
Service: Bots/Discord

Does this expand an already existing service: Y

Link to game: https://bastionbot.org/

Links for server downloads: https://github.com/TheBastionBot/Bastion

Links for install steps/docs: https://docs.bastionbot.org/

there is a docker image but I'm not sure if it will help/save you time
from terminal its (docker pull joshj23/bastionbot)

**Comment by parkervcp** [comment]
https://github.com/parkervcp/eggs/tree/master/bots/discord/bastion
