### ISSUE TITLE
Discord Bot (RED)

### ISSUE THREAD

**Issue by lrmtheboss** [parkervcp/eggs#325]
Service: Bots/Discord

Does this expand an already existing service: Y

Link to game: https://github.com/Cog-Creators/Red-DiscordBot (no actual website that i can find)

Links for server downloads: https://github.com/Cog-Creators/Red-DiscordBot

Links for install steps/docs: https://red-discordbot.readthedocs.io/en/stable/install_linux_mac.html

**Comment by NonStopGamer** [comment]
This would be cool to see

**Comment by NgLoader** [comment]
I check this out later

**Comment by NgLoader** [comment]
Will work, I commit the egg soon

**Comment by parkervcp** [comment]
@lrmtheboss can you try this out?

**Comment by lrmtheboss** [comment]
sorry it took a long time but it seems to be working fine so far
