### ISSUE TITLE
REQUEST: Universal Discord Bot

### ISSUE THREAD

**Issue by Gagels** [parkervcp/eggs#327]
Service: Discord Bot Egg That Supports NodeJS, Java/JDK, Python, Lua

Does this expand an already existing service: Y

Link to game: discordapp.com

Links for server downloads: N/A.

Links for install steps/docs: just install NodeJS, Java/JDK, Python, Lua

**Comment by lazarsn** [comment]
I can make an docker image and egg for this

**Comment by lazarsn** [comment]
https://gitlab.com/lazarsn/universal-bot/blob/master/eggs/egg-v2-bot.json

**Comment by lazarsn** [comment]
DM me on Discord If You want
Bee#1502

**Comment by itsmemac** [comment]
the universal bot by @ghost doesnt work anymore since he removed his account from gitlab and everywhere. Please anyone help.

**Comment by parkervcp** [comment]
I am not into supporting a mas of languages. It's hard enough for people to understand with just a generic discordjs egg.
