### ISSUE TITLE
Rising World Dedicated server egg

### ISSUE THREAD

**Issue by crypticv** [parkervcp/eggs#328]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Rising World  dedicated server egg

Does this expand an already existing service: N this is new to pterodactyl panel

Link to game: https://store.steampowered.com/app/324080/Rising_World/

Links for server downloads: i know it says no forum but this is the official dedicated server setup post on the rising world website forum : https://forum.rising-world.net/thread/8075-dedicated-server-setup/

Links for install steps/docs: same as above https://forum.rising-world.net/thread/8075-dedicated-server-setup/

**Comment by parkervcp** [comment]
@crypticv can you test this please?

**Comment by parkervcp** [comment]
@crypticv Can you test #727 ?
