### ISSUE TITLE
BFBC2 Egg request (Project Rome)

### ISSUE THREAD

**Issue by itsmemac** [parkervcp/eggs#329]
Just trying to revive the old game for my buddies and other who still love to play it

Service: Battlefield : Bad Company 2 (Project Rome)

Does this expand an already existing service: Y

Link to game: https://forums.veniceunleashed.net/viewforum.php?f=44

Links for server downloads: This needs to be an official link and not one that is hosted on somf forum page or a personal github page.
https://forums.veniceunleashed.net/bf/
https://mega.nz/#!PhxkWQhC!HhgW9UX_k0Nod_KNCdUqCyMxL1dqBCn-ckNXvTkuQEo
(Couldnt find the direct link so uploaded the OG file which i got years back to host)

Links for install steps/docs:
https://forums.veniceunleashed.net/viewtopic.php?p=60#p60

**Comment by Sir3lit** [comment]
Same thing with this, as the files are not available from the publisher, by the looks of it, this egg probably won't be made.

**Comment by itsmemac** [comment]
> Same thing with this, as the files are not available from the publisher, by the looks of it, this egg probably won't be made.

Oh, okay. Battlefield dedicated files for original is hard to find even more. :(
