### ISSUE TITLE
iW4x (Call of Duty : Modern Warfare 2) Egg request

### ISSUE THREAD

**Issue by itsmemac** [parkervcp/eggs#331]
Service: Call of Duty : Modern Warfare 2

Does this expand an already existing service: Y

Link to game: https://store.steampowered.com/app/10180/Call_of_Duty_Modern_Warfare_2/

Links for server downloads: This needs to be an official link and not one that is hosted on somf forum page or a personal github page.
https://github.com/Jawesome99/IW4x/releases/tag/0.6.0-server

Links for install steps/docs:
https://github.com/Jawesome99/IW4x/wiki

Reason : no official servers for long time in region and exsisting servers are empty and high ping
iW4x has modding support for long dead game

**Comment by Sir3lit** [comment]
I would say this is a no, unless it's able to be ran in wine. As I see no Linux versions of this. Not to mention the installer bat file uses a pirated version of the game from some gaming community website.

**Comment by parkervcp** [comment]
Reading into this it looks like Sir3lit is correct. It's not something I want to support. It probably won't run in wine. the way to get server files is questionable at best.
