### ISSUE TITLE
ARK Survival egg broken

### ISSUE THREAD

**Issue by rowan76** [parkervcp/eggs#332]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: Ark
Modified: no

Expected Behavior:
The server to start

Actual Behavior:
It doesn't start and gives this error:
:/home/container$ ./ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?ServerPassword=?ServerAdminPassword=?Port=7777?MaxPlayers=20
/entrypoint.sh: line 25: ./ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory

Steps to Reproduce: (Step by step what to do to cause the issue)
Make an ark server and try to start it

This bug has existed for some time now so that's why I decided to make the bug report as I could really use a fix

**Comment by lazarsn** [comment]
Restart daemon
``service ei restart``

**Comment by rowan76** [comment]
> Restart daemon
> `service wings restart`

The error is still present after a restart of the daemon

**Comment by lazarsn** [comment]
Recreate server

**Comment by parkervcp** [comment]
You clearly didn't read the template when submitting this issue. I am closing this out.
