### ISSUE TITLE
Ark egg broken

### ISSUE THREAD

**Issue by rowan76** [parkervcp/eggs#333]
Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: Ark
Modified: no

Expected Behavior:
The server to start

Actual Behavior:
It doesn't start and gives this error:
:/home/container$ ./ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?ServerPassword=?ServerAdminPassword=?Port=7777?MaxPlayers=20
/entrypoint.sh: line 25: ./ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory

Steps to Reproduce: (Step by step what to do to cause the issue)
Make an ark server and try to start it

This bug has existed for some time now so that's why I decided to make the bug report as I could really use a fix

**Comment by lazarsn** [comment]
Use #eggs Discord channel for Support

**Comment by rowan76** [comment]
> Use #eggs Discord channel for Support

I did on the 31/08/2019

**Comment by parkervcp** [comment]
I believe I would have asked for install logs.

That is what I am going to ask for here as well.

**Comment by rowan76** [comment]
> I believe I would have asked for install logs.
> 
> That is what I am going to ask for here as well.
Here you go:

` Update state (0x11) preallocating, progress: 89.31 (8158342753 / 9134398339)
 Update state (0x11) preallocating, progress: 89.98 (8219536551 / 9134398339)
 Update state (0x11) preallocating, progress: 99.56 (9094656335 / 9134398339)
 Update state (0x61) downloading, progress: 0.01 (1048576 / 9134398339)
 Update state (0x61) downloading, progress: 0.65 (59355456 / 9134398339)
 Update state (0x61) downloading, progress: 3.07 (279993053 / 9134398339)
 Update state (0x61) downloading, progress: 4.81 (439572431 / 9134398339)
 Update state (0x261) stopping, progress: 6.56 (599585163 / 9134398339)
Error! App '376030' state is 0x402 after update job.
'linux32/steamclient.so' -> '../.steam/sdk32/steamclient.so'`

**Comment by rowan76** [comment]
> > I believe I would have asked for install logs.
> > That is what I am going to ask for here as well.
> > Here you go:
> 
> ` Update state (0x11) preallocating, progress: 89.31 (8158342753 / 9134398339) Update state (0x11) preallocating, progress: 89.98 (8219536551 / 9134398339) Update state (0x11) preallocating, progress: 99.56 (9094656335 / 9134398339) Update state (0x61) downloading, progress: 0.01 (1048576 / 9134398339) Update state (0x61) downloading, progress: 0.65 (59355456 / 9134398339) Update state (0x61) downloading, progress: 3.07 (279993053 / 9134398339) Update state (0x61) downloading, progress: 4.81 (439572431 / 9134398339) Update state (0x261) stopping, progress: 6.56 (599585163 / 9134398339) Error! App '376030' state is 0x402 after update job. 'linux32/steamclient.so' -> '../.steam/sdk32/steamclient.so'`

https://pastebin.com/7FzweqH2

**Comment by parkervcp** [comment]
This is a regular issue with ARK and the install process for it.

It appears to be a server issue on their side as that is what the 402 error is. It's not something I can fix or control.
