### ISSUE TITLE
FiveM egg start error 

### ISSUE THREAD

**Issue by Chocobon27** [parkervcp/eggs#338]
Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: FiveM
Modified: No

Expected Behavior: normally start the server

Actual Behavior: 
the server turns on and gives this error "Could not find component cache storage file (components.json).Aborted (core dumped)"

Steps to Reproduce: i just press the start button 
![Screenshot_55](https://user-images.githubusercontent.com/27243351/67617638-64aad700-f7e5-11e9-98f6-464e7ecc42e3.png)

**Comment by parkervcp** [comment]
<https://forum.fivem.net/t/fivem-server-on-vps-ubuntu-18-04/846521>

This appears to be an issue with the latest builds and not an egg issue.
