### ISSUE TITLE
7 Days to die v18 server issue

### ISSUE THREAD

**Issue by Carsondd** [parkervcp/eggs#339]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (0.7.15)
Daemon Version: (0.6.12 )
Service: (7Days to die)
Modified: no

Expected Behavior: Starting the server would let me connect to it after startup.

Actual Behavior:  Unable to connect to the server. "Server is still initializing, try again in a few minutes" Server log throws this error at the end of startup. 

`2019-10-26T03:57:31 32.375 INF StartGame done
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local 
steamclient.so.
2019-10-26T03:57:32 33.132 ERR [Steamworks.NET] Could not initialize GameServer`

Steamclient.so files seem to be out of wack. Tried to link them but had no luck in that area. All of this happened when they pushed v18 of the game last night. This is also a fresh install of the server. 

Steps to Reproduce: Start the server after it updated, gets the same error every startup. 

Sorry about the first submission with out the formatting, not sure how I worked around that. Here is the full log again just in case. https://pastebin.com/AyiysgMm

**Comment by parkervcp** [comment]
Have you tried out the latest PR'd version of the egg to fix this sort of issue?

https://github.com/parkervcp/eggs/pull/335

**Comment by Carsondd** [comment]
Always the one thing I didn't try or notice. Thanks for the help.

**Comment by parkervcp** [comment]
Did that work for you @Carsondd ?

**Comment by parkervcp** [comment]
I am going to go with a yes.
