### ISSUE TITLE
Rust startup broken due to changes to rcon

### ISSUE THREAD

**Issue by parkervcp** [parkervcp/eggs#342]
Panel Version:  0.7.15
Daemon Version: 0.6.12
Service: Rust
Modified: no

Expected Behavior: show up as started correctly

Actual Behavior: hung on starting due to rcon changes

Steps to Reproduce: start a server using the latest release.

This need an update to the server wrapper.

**Comment by renegade428** [comment]
workaround after the rcon wait is over
Write console "save" server is running

**Comment by parkervcp** [comment]
I am working on a fix for it to do it on it's own right now.

**Comment by renegade428** [comment]
Yeah I saw on discord. This worked for me and people kept asking so I figured I'd put it on here in case someone was looking.

**Comment by parkervcp** [comment]
This was resolved.
