### ISSUE TITLE
Game request: Minecraft Waterdog

### ISSUE THREAD

**Issue by provsalt** [parkervcp/eggs#348]
Service: minecraft bedrock and minecraft java

Does this expand an already existing service: Yes

Link to game: minecraft.net

Link to download
https://ci.codemc.io/job/yesdog/job/Waterdog/

Links for install steps/docs:
https://github.com/yesdog/Waterdog/blob/master/README.md

**Comment by provsnoobgaming** [comment]
woopsy forgoten to change first line to Service: minecraft and minecraft bedrock

**Comment by lrmtheboss** [comment]
also minecraft proxy
would love to see a egg for this
