### ISSUE TITLE
Minecraft Forge Generic egg failure to download

### ISSUE THREAD

**Issue by Mayzie** [parkervcp/eggs#351]
## Environment:

Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: Minecraft Forge Generic
Modified: No

## Expected Behavior:

Find and download a valid modpack archive.

## Actual Behavior:

Minecraft Forge Generic egg cannot download and install modpacks from CurseForge, due to a failure to extract the relevant IDs. One such command is below:

```bash
curl -L https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix/download//file -o server.zip
```

From attempting to download and install the All The Mods 3 Remix pack (project URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix), with the modpack version as both `latest` and `1.5.1` (as "`latest`" is now no longer prefilled).

## Steps to Reproduce:

1. Create a new Pterodactyl server with the Minecraft Forge Generic egg.
2. Enter the following as the modpack URL: `https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix`
3. Fill out the other settings.
4. ???
5. Wings daemon will report: `"err":{"message":"Install script failed with code 1","name":"Error","stack":"Error: Install script failed with code 1...`, while Pterodactyl Panel will report the server as still "Installing".

## Workaround:

For those desperate (this is not a solution, just a temporary hack because I'm lazy and just wanted installation for one server working), I've just worked around it by replacing the `get_download` function with the following:

```bash
function get_download {
    cd /mnt/server

    echo "Executing curl -L ${MODPACK_URL} -o server.zip"
    curl -L ${MODPACK_URL} -o server.zip

    unzip -o server.zip

    rm -rf server.zip
}
```

`MODPACK_URL` (when setting up the server) can be found by initiating a download of the server file in your browser, and then copying and pasting that url into the `MODPACK_URL` text field. An example URL would look like this: `https://media.forgecdn.net/files/2790/133/ATM3R-1.5.1_Server-Full.zip`

**Comment by parkervcp** [comment]
If you look I switched too using the modpack ID and not the URL anymore. This is due to the site being cloudflare protected.

**Comment by parkervcp** [comment]
It at past I thought I did.

**Comment by Mayzie** [comment]
[Is this not the egg I should be using](https://github.com/parkervcp/eggs/blob/master/minecraft_java/forge/forge-mod-generic/egg-forge-generic.json#L28)?

**Comment by parkervcp** [comment]
I swear I updated it because it was broken already. Just updated the whole section.

https://github.com/parkervcp/eggs/tree/master/minecraft_java/forge/curseforge-generic
