### ISSUE TITLE
MC modpack dont get fully downloaded

### ISSUE THREAD

**Issue by IceCupe123** [parkervcp/eggs#353]
Panel Version: (0.7.15)
Daemon Version: (0.6.12)
Service: (curseforge-generic)
Modified: (no)

Expected Behavior:
download the mod pack

Actual Behavior:
all files for the server get downloaded exept the mods from mods folder
it just download there a file called download with the content :"error code: 1020"

**Comment by parkervcp** [comment]
Any specific pack that this is for?

**Comment by IceCupe123** [comment]
all packs i tryed

**Comment by parkervcp** [comment]
@IceCupe123 Please try out the updated install.

**Comment by IceCupe123** [comment]
almost working correct now mods get downloaded , but it dont like spaces like in : https://www.curseforge.com/minecraft/mc-mods/botania/files/2782181
then it only create a file called botania
screen shot : https://imgur.com/JkoX37D.png

**Comment by parkervcp** [comment]
Which mod pack is this?

**Comment by IceCupe123** [comment]
https://www.curseforge.com/minecraft/modpacks/ftb-revelation

**Comment by parkervcp** [comment]
Who puts spaces in filenames... honestly.

**Comment by IceCupe123** [comment]
ikr but some big mods doing it

**Comment by parkervcp** [comment]
There it's fixed in the latest update. try again.

**Comment by IceCupe123** [comment]
looking good

**Comment by IceCupe123** [comment]
download is working now , i still need to test if versions doesnt work on more packs then just https://www.curseforge.com/minecraft/modpacks/ftb-revelation its grabbing grabbing version 3.1.0 instead of 3.2.1

**Comment by parkervcp** [comment]
What version did you put in?

**Comment by parkervcp** [comment]
@IceCupe123 ^^

**Comment by IceCupe123** [comment]
i typed version : 3.2.1 in

**Comment by IceCupe123** [comment]
i tryed now some more packs and it never getting the latest version

**Comment by IceCupe123** [comment]
i know now why its grabbing this version if u check https://addons-ecs.forgesvc.net/api/v2/addon/296062 the json file it always grabing the version from latest files with id "0"

**Comment by parkervcp** [comment]
@IceCupe123 Done. Please try again.

**Comment by IceCupe123** [comment]
now i get a install error if i set modpack version latest or if i set version manual

> pid":18750,"level":60,"err":{"message":"Install script failed with code 1","name":"Error","stack":"Error: Install script failed with code 1\n    at DockerController.run (/srv/daemon/src/controllers/option.js:169:41)\n    at /srv/daemon/node_modules/dockerode/lib/docker.js:1417:11\n    at /srv/daemon/node_modules/dockerode/lib/container.js:783:7\n    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)"},"msg":"A fatal error was encountered while attempting to create a server.","time":"2019-11-17T15:36:06.818Z","v":0}

**Comment by parkervcp** [comment]
install logs please.

Server install logs are located in `/srv/daemon/config/servers/<server-uuid>/install.log`

**Comment by IceCupe123** [comment]
the thing is this server folder gets deleted after the install fails

**Comment by IceCupe123** [comment]
if i keep reloading befor the folder gets deleted i dont even see a install log

**Comment by IceCupe123** [comment]
https://ptero.co/ekojufefud.pl

**Comment by parkervcp** [comment]
There updated again

**Comment by IceCupe123** [comment]
now lastest version is working fine 
manual set version isnt ,but in my opinion it isnt rly necessary
https://ptero.co/kugidikoro.pl

**Comment by IceCupe123** [comment]
need to say rly nice support and pretty fast

**Comment by parkervcp** [comment]
Trying to match versions is stupidly hard. There is a reason I default to latest is matches fail.

**Comment by IceCupe123** [comment]
maybe u could add a folder check in ur install script so if a new version from a pack is released and the user reinstall the server for an update that it check if the folders ;(config, mods, resources, scripts)
exist and delete them other wise u get duplicated files with different versions : https://imgur.com/RpnHQAl.png

**Comment by IceCupe123** [comment]
if u want : https://github.com/IceCupe123/eggs/tree/patch-1/minecraft_java/forge/curseforge-generic 
 i added a funktion that this script also delete the mods , config , scripts, resources folder befor it download the new files so u can use the reinstall server funktion to update the modpack at new release

**Comment by parkervcp** [comment]
One issue with that being if a user has any custom settings they don't want to delete.

I won't accept that as an option.
