### ISSUE TITLE
FiveM Server behaving Strange

### ISSUE THREAD

**Issue by killer-kirito** [parkervcp/eggs#355]
Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: Fivem
Modified: no

Expected Behavior: Automatic Updating Console, Sending Commands, and updating status

Actual Behavior: 
Status always on Starting,
Console won't automaticly update
Cant send Console Commands

Steps to Reproduce: 
Added the egg to the Panel, Restarted the Daemon 
Installed the server with 2 ports attached (default ports for fivem) 
Start the Server

**Comment by parkervcp** [comment]
So far I have no other people calling out console issues. My 2 test servers appear to be running fine.

One is running the latest recommended with OneSync enabled and everything.

**Comment by killer-kirito** [comment]
i've tested the latest version of the egg to see if it was an version issue but still nothing

**Comment by parkervcp** [comment]
My server admin guys who I host for also say they do most of their work in game.

**Comment by parkervcp** [comment]
Other people on Discord have said their servers are also working fine. When putting commands into the console it prints multiple times but it's actually working and sending fine.

**Comment by parkervcp** [comment]
So seeing that there have been no responses I am closing this out.
