### ISSUE TITLE
7 Days to Die setlocale('en_US.UTF-8') failed

### ISSUE THREAD

**Issue by NHDriver4** [parkervcp/eggs#356]
Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: 7 Days to Die
Modified: Yes-Just changed the name of the config file

Expected Behavior: Installed server should load

Actual Behavior: Server will not initialize and console contains error messages. This happens with existing servers as well as new ones.

Steps to Reproduce: Install 7 Days to Die "latest" version.

Logs: https://pastebin.com/kSvXRfZz

Daemon Diag: https://hastebin.com/qakoweloga

**Comment by parkervcp** [comment]
Please paste logs to a gist or something instead of flooding this with unreadable logs.

The set locale error is minimal as best as it's not breaking anything.

**Comment by NHDriver4** [comment]
Updated, sorry about that.

**Comment by parkervcp** [comment]
How much ram did you allocate to the server? Did you allocate all the ports that were listed in the readme?  

See the readme here - https://github.com/parkervcp/eggs/tree/master/steamcmd_servers/7_days_to_die

**Comment by NHDriver4** [comment]
Yes. Unlimited ram (0). This happened with an already existing installation as well as a new one.

**Comment by NHDriver4** [comment]
So perhaps something else was going on outside of my environment, because both the new and old server are now booting. I am however still getting the new "selocale failed" error still.

**Comment by parkervcp** [comment]
Again... The setlocale error doesn't actually cause issues. It's just that the only locale in the image is `C.UTF-8`

**Comment by NHDriver4** [comment]
Again, it's new. Any new messages causes questions by users.

**Comment by parkervcp** [comment]
That is not a new error. It's be happening for a long time.
