### ISSUE TITLE
Add switches to Insurgency Egg

### ISSUE THREAD

**Issue by ozzygit** [parkervcp/eggs#357]
Is your feature request related to a problem? Please describe.
Lack of startup parameters prevent some features working with Insurgency Egg

Describe the solution you'd like
Parameters added to default egg as follows:
-workshop -secure +maxplayers 49

Describe alternatives you've considered
N/A

Additional context
-workshop (enables downloading of workshop items. This is normally default on servers)
-secure (enables VAC be default for AntiCheat)
+maxplayers 49 (This sets the max allowable players to 49 which is default. The game engine will not allow more)

These settings will make creating servers faster especially for novices and prevent a lot of troubleshooting like workshop items not downloading or only 8 players can join etc.

Panel Version: 0.7.15
Daemon Version: 0.6.12
Service: Insurgency2014
Modified: (yes/no) Yes

Expected Behavior:
Workshop items download and maximum players be able to join server. Also, VAC enabled on server.

Actual Behavior:
Insurgency Eggs don't allow the server to have VAC enabled, more than (8 or 16 players, I forget which), and download workshop items.

Steps to Reproduce: 
Switches not present
Please add "-workshop -secure +maxplayers 49" to the default Insurgency startup command line

Eg, 
./srcds_run -port {{SERVER_PORT}} +map {{SRCDS_MAP}} checkpoint +ip 0.0.0.0 -strictportbind -norestart -workshop +exec pure.cfg -secure +maxplayers 49

**Comment by parkervcp** [comment]
I am specifically asking about the maxplayers right now. If it defaults to 49 why even set it?

If someone wants to add max players, let them add the flags on their own.

As for the rest it makes sense to add them.

**Comment by ozzygit** [comment]
It doesn't default to 49 I just researched it.
For co-op it defaults to 8 and for pvp I think it's 16 or 32.
Everyone sets it on the startup command in their servers so it makes sense to add it imo.

**Comment by gOOvER** [comment]
Easiest Way; add a Variable and everyone can decide alone

**Comment by parkervcp** [comment]
Making it a variable would be best here either way.
