### ISSUE TITLE
Unable to connect to running 7Days2Die Server 

### ISSUE THREAD

**Issue by bloggy** [parkervcp/eggs#358]
Panel Version: 0.7.12
Daemon Version: 0.6.11
Service: 7days2die
Modified: no

Expected Behavior:

Connect to the server

Actual Behavior:

I am unable to connect to my server (7days2die)

Here is the logfile (server start log):
https://pastebin.com/fDUZYVnu

Screenshot:
https://i.imgur.com/tG9YHjG.png

Steps to Reproduce: (Step by step what to do to cause the issue)

**Comment by parkervcp** [comment]
Your startup and everything looks fine. Did you allocate all the ports required?

As called out here - https://github.com/parkervcp/eggs/blob/master/steamcmd_servers/7_days_to_die/README.md#server-ports

**Comment by parkervcp** [comment]
@bloggy Can you please answer the question?

**Comment by bloggy** [comment]
I have just added the ports you mentioned. But now when I try to start the server I just get:

[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 13390M / 50000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] A fatal error was encountered while starting this server.

When I only add the game ports (26900 - 26902), the server starts but I am still unable to connect.

Screenshots:
https://i.imgur.com/omzsM5A.png
https://i.imgur.com/7KZgrJX.png

**Comment by bloggy** [comment]
I now connected directly in the game, and it seems to work! Thank you !
