### ISSUE TITLE
GTA 5 FiveM EGG (stuck on starting)

### ISSUE THREAD

**Issue by ConflictKingdoms** [parkervcp/eggs#36]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: (version number)
0.7.6
Daemon Version: (version number)
0.5.5
New Service: (yes/no) (Is this a request for a new service?)
No
Service: FiveM
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)
No

Expected Behavior:
the server dosent start at all
Actual Behavior:
Its not starting
Steps to Reproduce: (Step by step what to do to cause the issue)

-  install panel
- install egg
- make server
- on server creation i had startup when installation is done
- and its just stuck on starting
http://prntscr.com/jcwfma

run.sh might be wrong also
https://cdn.discordapp.com/attachments/414559797468200992/441314367229788172/unknown.png

got any questions lemme know :)

**Comment by parkervcp** [comment]
Can you get me logs for things? The install log is in the /srv/daemon/servers/<server_uuid>/install.log

I have several servers with this running and none of them are stuck in starting. I have also ran the install process recently as well with no issue. We don't use the run.sh.

**Comment by ConflictKingdoms** [comment]
https://hastebin.com/elitasogad.erl

**Comment by parkervcp** [comment]
The install looks good. I assume this is the latest fivem egg from the panel.

Also the folder layout for this server is going to be different. The proot setup they use is broken in the panel.

**Comment by ConflictKingdoms** [comment]
So what do I need to do?

**Comment by parkervcp** [comment]
Did you restart the daemon after adding the egg?

**Comment by ConflictKingdoms** [comment]
minecraft works just fine

but i noticed the console for arma 3 works just like normal beside errors etc wich isnt important but.

but in fivem i get just this http://prntscr.com/jcxf2p

**Comment by parkervcp** [comment]
For now I have identified the issue.

They added a new library and that is breaking it.

Remove the last line (red arrow) and the `,` (comma at blue arrow) 

![rjyzv6q](https://user-images.githubusercontent.com/1207679/39768649-f333cc90-52b7-11e8-95a9-f3833b4e2f30.png)

**Comment by JoaoCosta52PT** [comment]
I can confirm that I also have this problem and removing that last component fixed it. Do you have an idea of when the docker image will be updated with the required libraries and fixed?

**Comment by parkervcp** [comment]
I will be updating it within the next week. I have weddings and graduations to go to. A bit busy right now.

**Comment by Beaast-exe** [comment]
@JoaoCosta52PT adiciona-me no discord Beaast#6798

**Comment by JoaoCosta52PT** [comment]
Has this been fixed yet?

**Comment by parkervcp** [comment]
No. I am mostly done. I have been testing it.
