### ISSUE TITLE
steamcmd doesn't use the provided steam account to download Starbound

### ISSUE THREAD

**Issue by fenpaws** [parkervcp/eggs#371]
Panel Version:  0.7.15
Daemon Version: 0.6.12
Service: starbound
Modified: yes, I modified the egg scripts to mod support and forced steamcmd to download workshop items. [Look here for the modified version](https://pastebin.com/beNVae3x).
Line 20, 29-34

Expected Behavior:
steamcmd should download the game with my provided username and password, downloads the workshop content and symlinks them to mods

Actual Behavior:
steam downloads the game anonymously and refuses to download it.
```
Loading Steam API...OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '211820' (No subscription)
:/home/container$ ./starbound_server
/entrypoint.sh: line 25: ./starbound_server: No such file or directory
```

Steps to Reproduce:
1. Use the current Starbound egg
2. copy my modified egg script version and replace it with the original one
3. create a server and use your steam login
4. start the server

**Comment by parkervcp** [comment]
You can't install starbound with an anonymous account. This server requires an account that owns the game to install the server.

**Comment by parkervcp** [comment]
reopening after re-reading.

**Comment by parkervcp** [comment]
This is a two part issue. Install script is probably fine. The entrypoint to the game tries to update the server. It uses anon to do that and it's failing.

**Comment by fenpaws** [comment]
Sorry if I wasn't to clear about the issue. 

I tried, multiple things now and every time the same issue occurs, steam uses the anon user to download it. I updated my wings server and everything.

If I remove the `+workshop_download_item` flag it downloads the game without a problem, but again as the anon user. I even tried to hardcoded my steam credentials into the script but well again, it downloads it as anon.

**Comment by parkervcp** [comment]
@fenpaws Please try the new egg.

A note on using steam 2fa. The installer takes long enough to get to the install command that it will most likely time out.

**Comment by fenpaws** [comment]
@parkervcp i looked up the new egg and it seems that you only uploaded a [starbound_server.config](1e45eafc17071800a867687d281a54bd13096889) file. Should I replace it with my existing one or do I need to reimport the egg completely?

**Comment by parkervcp** [comment]
It's currently in a PR. It's right above my last post here.

**Comment by fenpaws** [comment]
oh yeah sorry, didn't saw that somehow. Im testing now

**Comment by fenpaws** [comment]
Okay from the output intselfe it looks good, steamcmd logs in with my account. I can't join the server for now but I will test this asap.
