### ISSUE TITLE
Game Request: Red Dead Redemtion 2 (REDM)

### ISSUE THREAD

**Issue by TimRambo** [parkervcp/eggs#379]
Service: (Ex. minecraft/factorio/etc)
Red Dead Redemtion 2 (RedM)

Does this expand an already existing service: Y/N
Overall, the setup process is very similar to Setting up a FiveM Server 
Link to game: (Ex. minecraft.net/factorio.com/etc)
https://redm.gg (Dont ask me why its there lol)
Links for server downloads:
http://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/
Links for install steps/docs:
https://forum.fivem.net/t/how-to-setup-a-redm-server/918850

**Comment by parkervcp** [comment]
This is literally the same as the fivem install with an added `gamename rdr3` to the startup so far as I can tell. I am only tested starting the server locally on my machine. I don't own RDR2 to test this with.

**Comment by parkervcp** [comment]
Please give the redm egg I just PR's a test.

@TimRambo @GamerXCZ
