### ISSUE TITLE
Nukkit Config Parsing Issue

### ISSUE THREAD

**Issue by wraith1200** [parkervcp/eggs#38]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.6
Daemon Version: 0.5.5
New Service: no
Service: Nukkit
Modified: no

Expected Behavior: Install server and set the server-port to {{server.build.default.port}} via config parsing.

Actual Behavior: Installs server and server-port is set to default nukkit port

Steps to Reproduce: Install nukkit server and check server.properties to see if the port set correctly.

**Comment by parkervcp** [comment]
the server.properties file doesn't get set until the first run of the game server. That is why it fails to work properly. I may have a fix for that and will see what I can do for it.

**Comment by wraith1200** [comment]
I think there may be an easy work around for this. If the default server.properties file is pulled from git or another location during the install script it should be able to set that during the first run since the file would exist.

I am going to do some testing and if I get a working installer I will PR it into your repo.

**Comment by parkervcp** [comment]
That was the idea I had. Just keep a copy in the repo.

**Comment by wraith1200** [comment]
Added PR for those changes #40
