### ISSUE TITLE
Game Request: OpenRCT2

### ISSUE THREAD

**Issue by parkervcp** [parkervcp/eggs#381]
Service: OpenRCT2

Does this expand an already existing service: Y (Tycoon Games)

Link to game: https://openrct2.org/

Links for server downloads: https://openrct2.org/downloads

Links for install steps/docs: https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer

**Comment by microton79** [comment]
Is this still needed ? It seems you need the gamefiles from RCT2 to run the dedicated server.
To start the dedicated server `openrct2 --headless --port 11753 <saved game path>
`

**Comment by parkervcp** [comment]
I know how to install it. I just need to export the egg after some testing.

**Comment by microton79** [comment]
Can i take a look at it ? Would like to try.

**Comment by parkervcp** [comment]
@microton79 If you know how to stop it I have it starting fine

**Comment by microton79** [comment]
Asking on their discord at the moment about that. 
Does your current egg pull the gamefiles from steam ? Is there also a way to use a GOG File to get the Files from ?

**Comment by MrMelon54** [comment]
This is a few months old now. Are you still looking into this?

**Comment by parkervcp** [comment]
@MrMelon54 as previously stated. I was looking for a stop command.

**Comment by MrMelon54** [comment]
I had it open in a terminal and pressing ctrl+c or ctrl+d twice closed it

**Comment by parkervcp** [comment]
that is different than running it in docker.

**Comment by MrMelon54** [comment]
Unfortunately I couldn't find a command try asking in the OpenRCT2 discord?

**Comment by MrMelon54** [comment]
I asked in the OpenRCT2 discord

```
console.executeLegacy("exit");
```

**Comment by parkervcp** [comment]
Well I get a core dump when the server starts now

```
VERBOSE: begin openrct2 loop
VERBOSE: setsockopt(socket, IPV6_V6ONLY) failed: 92
/entrypoint.sh: line 13:    15 Floating point exception(core dumped) ${MODIFIED_STARTUP}
```

My startup  
the save i got is from their example.
```
./openrct2-cli host https://bit.do/openrct2-bpb --headless --user-data-path=/home/container/game_data --address=0.0.0.0 --port={{SERVER_PORT}} --verbose
```

**Comment by MrMelon54** [comment]
I'm assuming that `setsockopt()` sets a socket option but idk why it says `IPV6_V6ONLY`. Can you export your current egg so I can take a look at it?

**Comment by parkervcp** [comment]
This should have been closed when the game was merged.
