### ISSUE TITLE
Waterfall egg: Setting a version doesn't work

### ISSUE THREAD

**Issue by hoffleit** [parkervcp/eggs#384]
With the Waterfall egg, setting a version (WATERFALL_VERSION) seems to have no effect. It always seems to fetch the latest version of the Waterfall jar.

Looking at the code, the egg doesn't seem to use the WATERFALL_VERSION variable at all.

If setting the version will be supported, I think the description should include a short explanation WHICH version number is expected (Minecraft version - a float? Waterfall Build number - integer?).

**Comment by parkervcp** [comment]
@hoffleit Try that please. It was a quick change.

**Comment by hoffleit** [comment]
Had just a quick try. Yep, the error is gone (with the 4.1.19a.zip).
