### ISSUE TITLE
Barotrauma Game issue

### ISSUE THREAD

**Issue by AndyLee1024** [parkervcp/eggs#391]
Hi, develop.

I created an Barotrauma egg. After importing it to the server, it can be turned on, but after a few seconds, the server crashed.

![alt text](https://i.loli.net/2019/12/27/HlSAT7zMWiafjLI.png "snap1")

I cannot find any error log.  Can you help me. pls. 

Here is my egg. 

```
{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v1"
    },
    "exported_at": "2019-12-27T00:20:45+08:00",
    "name": "Barotrauma",
    "author": "lee@test.com",
    "description": "Barotrauma dedicated server",
    "image": "quay.io\/pterodactyl/\/core:source",
    "startup": ".\/DedicatedServer.exe",
    "config": {
        "files": "{}",
        "startup": "{\r\n    \"done\": \"Setting breakpad minidump AppID = 602960\",\r\n    \"userInteraction\": []\r\n}",
        "logs": "{}",
        "stop": "exit"
    },
    "scripts": {
        "installation": {
            "script": "#!\/bin\/bash\r\n# Barotrauma Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\napt -y update\r\napt -y --no-install-recommends install curl lib32gcc1 ca-certificates\r\ncd \/tmp\r\ncurl -sSL -o steamcmd.tar.gz https:\/\/steamcdn-a.akamaihd.net\/client\/installer\/steamcmd_linux.tar.gz\r\nmkdir -p \/mnt\/server\/steamcmd \/mnt\/server\/logs\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/steamcmd\r\ncd \/mnt\/server\/steamcmd\r\n# SteamCMD fails otherwise for some reason, even running as root.\r\n# This is changed at the end of the install process anyways.\r\nchown -R root:root \/mnt\r\nexport HOME=\/mnt\/server\r\n\r\n.\/steamcmd.sh +login anonymous +force_install_dir \/mnt\/server +app_update 1026340 -validate +quit | tee output.txt\r\nwhile ! grep -q \"Success\" output.txt; do\r\n   .\/steamcmd.sh +login anonymous +force_install_dir \/mnt\/server +app_update 1026340 -validate +quit | tee output.txt\r\ndone\r\n\r\nmkdir -p \/mnt\/server\/.steam\/sdk32\r\ncp -v linux32\/steamclient.so ..\/.steam\/sdk32\/steamclient.so",
            "container": "ubuntu:18.04",
            "entrypoint": "bash"
        }
    },
    "variables": [
        {
            "name": "LD_LIBRARY_PATH",
            "description": "LD_LIBRARY_PATH",
            "env_variable": "LD_LIBRARY_PATH",
            "default_value": ".\/linux64\/",
            "user_viewable": 0,
            "user_editable": 0,
            "rules": "string|max:20"
        },
        {
            "name": "TEST",
            "description": "TEST",
            "env_variable": "TEST",
            "default_value": "TEST",
            "user_viewable": 1,
            "user_editable": 1,
            "rules": "required|string|max:20"
        }
    ]
}
```

**Comment by parkervcp** [comment]
You're trying to run an exe in Linux.

**Comment by AndyLee1024** [comment]
> You're trying to run an exe in Linux.

That exe is a shell file  😄

**Comment by Jeroen52** [comment]
Why'd you add an .exe extension though?

**Comment by NgLoader** [comment]
Try it with "wine"

**Comment by NgLoader** [comment]
Create a default steam egg and change the app_id to **1026340**

**Comment by NgLoader** [comment]
and use app_run and not DedicatedServer.exe

**Comment by AndyLee1024** [comment]
![https://i.loli.net/2019/12/27/SWJl9HDPBr7bfj4.png](linuxgsm)

here is Linuxgsm's config.  I imitate him

**Comment by AndyLee1024** [comment]
Here is DedicatedServer.exe‘s content 
![alt text](https://i.loli.net/2019/12/27/GQKhDoCdn96NW3A.png)

**Comment by NgLoader** [comment]
Its working for me when I run it with steamcmd.

When you look in the officle documentation you will see this...
Note: that your not on a windows platform with a running Steam application.

- Install SteamCMD following these instructions.
- Log in to SteamCMD using the command "login anonymous".
- Install the Barotrauma dedicated server using "app_update 1026340 validate".
- Make sure you've configured the server settings, port forwarding, firewall settings and such as instructed in the "Hosting using the dedicated server" section.
- Launch the server using "app_run 1026340".

**Comment by NgLoader** [comment]
And when you like to use the DedicatedServer.exe move the steamcmd to the correct path (I don't know where there are)

**Comment by AndyLee1024** [comment]
Yes. I also see that official documentation.  but I did n’t use it in the end.
Can you show me your startup ？

I use "./steamcmd/steamcmd.sh  +login anonymous +force_install_dir /home/container +app_update 1026340 -validate +app_run 1026340" but not working ..

**Comment by AndyLee1024** [comment]
> Why'd you add an .exe extension though?

When I downloaded it, it was like this.  I'm not modify any file. ^_^

**Comment by NgLoader** [comment]
It is currently very unstalbe, the server is running but the inializing always failed

**Comment by NgLoader** [comment]
And use the steamcmd to run your server.
The DedicatedServer.exe is no longer supportet.
``./steamcmd.sh +login anonymous +force_install_dir /mnt/server +app_run 1026340``

**Comment by AndyLee1024** [comment]
> And use the steamcmd to run your server.
> The DedicatedServer.exe is no longer supportet.
> `./steamcmd.sh +login anonymous +force_install_dir /mnt/server +app_run 1026340`

I just tested it on VPS, server is turned on, but the server cannot be found in the game.

When I use DedicatedServer.exe to start server,  It can be found in the game.

**Comment by parkervcp** [comment]
steamcmd should be installed if you use my install script.

It would be installed at `steamcmd/steamcmd.sh`
