### ISSUE TITLE
CS:GO server cannot shutdown.

### ISSUE THREAD

**Issue by Archerfy** [parkervcp/eggs#398]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number) 0.7.16
Daemon Version: (version number) 0.6.12
Service: (minecraft/factorio/etc) Counter Strike Global Offensive 
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) No

Expected Behavior: Server should normally shutdown with stop button or CTRL+C command.

Actual Behavior: Server cannot be stopped. There is no stop button only a start button. And CTRL+C doesn't work.

Steps to Reproduce: (Step by step what to do to cause the issue) There are no steps really. If you install a new server with the source engine and than choose Counter Strike Global Offensive it just installs starts it and there it is, No button no option to shutdown the server.

(EDIT) The Counter Strike Gllobal Offensive egg is already deliverd with the panel.
I cannot find another egg anywhere as of it is also not listed on this egg page anymore under steamcmd servers.

**Comment by parkervcp** [comment]
This egg is under the stock_eggs section.

**Comment by Archerfy** [comment]
Owh, I am so dumb. Thank you i will take a look and hope it will work than.

**Comment by Archerfy** [comment]
Tested command "quit" and it works.
