### ISSUE TITLE
Game Request: alt:V

### ISSUE THREAD

**Issue by RikoDEV** [parkervcp/eggs#402]
Service: alt:V

Does this expand an already existing service: Y

Link to game: https://altv.mp/#/

Links for server downloads: https://altv.mp/#/downloads

Official CDN (linux builds): https://cdn.altv.mp/server/stable/x64_linux/

Links for install steps/docs: None in wiki for linux based builds. The instructions for windows are very similar, so you can rely on them. https://wiki.altv.mp/Altv_server_setup_windows

**Comment by Sir3lit** [comment]
There would have to be a Linux version in order to make this work unless we use wine, but it could be unstable.

**Comment by RikoDEV** [comment]
> There would have to be a Linux version in order to make this work unless we use wine, but it could be unstable.

You don't need wine, I've added a server link for linux.

**Comment by Sir3lit** [comment]
Ahh i see, ill see what i can work on, i don't have gta5 so ill test what i can

**Comment by parkervcp** [comment]
@RikoDEV Want to check that out?

**Comment by RikoDEV** [comment]
Config seems broken. Wait a sec...

**Comment by RikoDEV** [comment]
Fixed configuration files:

`{
    "server.cfg": {
        "parser": "file",
        "find": {
            "host:": "host: 0.0.0.0,",
            "port:": "port: {{server.build.default.port}},",
            "password:": "password: \"{{server.build.env.PASSWORD}}\",",
            "description:": "description: \"{{server.build.env.SERVER_DESC}}\","
        }
    }
}`

**Comment by parkervcp** [comment]
That hastebin link is empty.

**Comment by parkervcp** [comment]
Also when I added the `\"` in the config management it breaks and doesn't post the replacement into the config.

**Comment by RikoDEV** [comment]
I have reinstalled the server again on your egg and the problem with the configuration file has disappeared. Everything works fine.
