### ISSUE TITLE
Request: Discord RSS Bot

### ISSUE THREAD

**Issue by buracat** [parkervcp/eggs#406]
Service: Bots/Discord

Does this expand an already existing service: Y

Link to game: https://github.com/synzen/Discord.RSS

Links for server downloads: https://github.com/synzen/Discord.RSS

Links for install steps/docs: https://github.com/synzen/Discord.RSS/wiki/Setup

**Comment by NgLoader** [comment]
I  commit a egg later for this

**Comment by parkervcp** [comment]
This can use the generic nodejs egg.
