### ISSUE TITLE
Cuberite SSL error

### ISSUE THREAD

**Issue by marier-nico** [parkervcp/eggs#407]
Panel Version: 0.7.16
Daemon Version: 0.6.12
Service: minecraft (cuberite)
Modified: no

Expected Behavior: Players are able to connect to the server with no issues

Actual Behavior: Players get kicked upon attempting to connect and the following messages are printed to the console :
```
[17:48:39] SecureRequest: SSL reading failed: -0x4c
[17:48:39] Kicking player {player name} for "Failed to authenticate account!" 
```

Steps to Reproduce: Import the egg into the panel and restart the daemon on the node the server will run on. Create a cuberite server and wait for it to boot. Once it is booted, restart it and try to login (logging in without restarting works fine).

**Note**: I've tried downloading the same build locally and performing the steps on my machine, this works without issues, so I suspect this might be related to the docker image somehow, but I'm not sure.

**Comment by gOOvER** [comment]
in my eye's thats the problem of your server

**Comment by parkervcp** [comment]
I can confirm I am seeing this as well.

What OS is your node running on @marier-nico ?

**Comment by marier-nico** [comment]
@parkervcp Thanks for checking!

It's running `Ubuntu 18.04.3 LTS`

**Comment by parkervcp** [comment]
Well it's not the base system then. I am testing things on my end in a bit. I am tied up right now with another project.

**Comment by marier-nico** [comment]
Sure, no problem! Thanks for looking into it :smile:

**Comment by parkervcp** [comment]
I have tested this recently and it looks like the cert issue is resolved.
