### ISSUE TITLE
Nukkit

### ISSUE THREAD

**Issue by DavidBrockway** [parkervcp/eggs#408]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number) Latest 
Daemon Version: (version number)  Latest 
Service: (minecraft/factorio/etc) Bedrock Minecarft
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)
No

Expected Behavior:

Server to load in on the mc bedrock client 

Actual Behavior:

Refuses to connect to world. 

Steps to Reproduce: (Step by step what to do to cause the issue)

Install Nukkit egg

**Comment by parkervcp** [comment]
Logs please
