### ISSUE TITLE
Discordia Discord Library

### ISSUE THREAD

**Issue by Sampleeeee** [parkervcp/eggs#409]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc) discord

Does this expand an already existing service: no

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://github.com/SinisterRectus/Discordia

Links for server downloads: This needs to be an official link and not one that is hosted on somf forum page or a personal github page.
`lit install SinisterRectus/discordia`

Links for install steps/docs:
https://github.com/SinisterRectus/Discordia/blob/master/README.md

**Comment by devil38** [comment]
https://gitlab.com/devil38/fork-rewrite/blob/lua/egg-lua.json

**Comment by parkervcp** [comment]
@Sampleeeee can you test that out?

**Comment by Sampleeeee** [comment]
I no longer have a pterodactyl instance set up, sorry

**Comment by parkervcp** [comment]
well my test install worked. I'll go and merge it.
