### ISSUE TITLE
Unreal Tournament GOTY & Unreal Tournament 2004 Egg Request | Pre-Alpha

### ISSUE THREAD

**Issue by ryan1161** [parkervcp/eggs#41]
Can you please get Unreal Tournament GOTY & Unreal Tournament 2004 working on the panel as I have tried many times but end up failing I can get it to download the files and install them in the container but when trying to get the start command to work it ends up crashing with nothing in the logs to help me find out why.

**Comment by parkervcp** [comment]
@ryan1161 When you opened this issue there was a base set of questions. Can you give me links and things to work with on this one please?

**Comment by ryan1161** [comment]
So the hard thing about this one was back in the day it was the cd that had
the server files I know that this website is somehow getting the server
files I do have the cds on my server that are the originals I can upload
them to my website and give you the link to download and host them so other
can install this.

https://linuxgsm.com/lgsm/ut99server/

https://linuxgsm.com/lgsm/ut2k4server/

**Comment by ryan1161** [comment]
Here is my links for the original server files. With the patches as you will need if using steams Unreal Tournament GOTY and Unreal Tournament 2004.

Unreal Tournament GOTY - tafaricraft.com/hidden/download/UTGOTYOriginals.tar.gz
Unreal Tournament 2004 - tafaricraft.com/hidden/download/UT2004Originals.tar.gz

**Comment by parkervcp** [comment]
So as I look at this is looks like you need to own the files to set up a server right?

**Comment by ryan1161** [comment]
Yes that is correct. Let me know if you need anything for it as I do have them running in my background but no on the gamepanel yet.

**Comment by parkervcp** [comment]
I would hazard to say that hosting the files may get you in trouble, and that you would need to supply your own links for the files.

**Comment by ryan1161** [comment]
You can’t start the servers unless you provide a valid product key. Link to this is on epics website: https://www.epicgames.com/unrealtournament/forums/cdkey.php?2004

**Comment by Joshuaharry120** [comment]
📦

**Comment by ryan1161** [comment]
I'm building a docker on this tonight now that I understand how to do all of this.

**Comment by ryan1161** [comment]
UT99 is done might need to tweak mine since it's hosted on the same network to download the server files and setup the packages for it to run but good enough for me just to see that in the web panel now.

Ut2004 should be done in a couple of mins now that my base build is working.
![ut - done](https://user-images.githubusercontent.com/2374149/45592594-9ccfbd00-b937-11e8-9eee-0ffd7ba5d87c.PNG)

**Comment by ryan1161** [comment]
UT2004 - is a bit tricky
Any idea on how to make the server cd into the System/ directory as the ./System/ucc-bin server didn't work as ut2004 likes to be cd into that directory and run the ucc-bin file. Any help would be appreciated.
Here are my docker images from docker hub.
UT99 - https://hub.docker.com/r/rryanward/ut99/
UT2004 - https://hub.docker.com/r/rryanward/ut2004/
Eggs:
UT99 - http://tafaricraft.com/UT99/UT99.json
UT2004 - http://tafaricraft.com/UT2004/UT2004.json

**Comment by parkervcp** [comment]
If you want those in the repo please submit a PR.

If you are going to submit a PR please look into a generic image to run the servers. I am sure it's totally doable. I haven't looked yet.

Also If you submit a PR please keep from using links to anything that could be copy written and dmca'd.

**Comment by ryan1161** [comment]
UT2004 gtg that magic file for the paths works. I don't want to PR the image as it's not clean and its has my product keys to activate the servers which I took out when uploading to my private ftp site.
![ut2004](https://user-images.githubusercontent.com/2374149/45593750-9995fa80-b952-11e8-9907-e8e34f33aeba.PNG)

**Comment by parkervcp** [comment]
I recommend moving the keys to a variable. Use it in the install process as a variable.

**Comment by ryan1161** [comment]
I'm closing this as I have it working the way I want and if anyone wants to pick this up for public use you can.

**Comment by QuintenQVD0** [comment]
I don't see an offical place to get a key + an offical place to download the server files: https://wiki.unrealadmin.org/Server_Setup_%28UT2004%29

**Comment by QuintenQVD0** [comment]
> There probably isn't an official place for the files anymore. Could we maybe use the files provided by linuxgsm?
> 
> http://linuxgsm.download/UnrealTournament99/

no, we need an offical download url. also this is a request for 2 compelty diffrend eggs? I found some files for UT2004
