### ISSUE TITLE
error while loading shared libraries: libSDL2-2.0.so.0

### ISSUE THREAD

**Issue by LanoHere** [parkervcp/eggs#411]
**Panel Version:**  0.7.16
**Daemon Version:** 0.6.12
**Service:** OpenTTD
**Modified:** 
*I forgot* I changed openttd version to 1.1.0beta2

**Expected Behavior:**
Server started and players can join.

**Actual Behavior:**
On startup server give me string
`./openttd: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory`
**Steps to Reproduce:** 
Server instalation --> Clicking "Start" button --> Getting this error
![image](https://user-images.githubusercontent.com/38018789/72840012-ae477880-3c93-11ea-9068-e2f5d2df4dea.png)

**Usefull info**
When i tried to make my own docker image where no "shares libraries" error happend, i got another error. Hostname was always set to "?", and console gave me error that was telling me that there's no any entrypoint.sh

**Comment by parkervcp** [comment]
@LanoHere rebuild your server please.

**Comment by LanoHere** [comment]
Yeah, now it's working **right.**
Thanks!
