### ISSUE TITLE
Spigot Egg Hangs on Installtion

### ISSUE THREAD

**Issue by tehguy** [parkervcp/eggs#412]
Panel Version: 0.7.16
Daemon Version: 0.6.12
Service: minecraft
Modified: no

Expected Behavior: The egg not taking over 20 minutes to install

Actual Behavior: installation hangs, docker stats showing unusually low activity before a spike in resource usage and termination of the install container. Panel still shows as installing. Server made as a test was deleted mid-install, docker still has a container for that install open, though using less than 1% CPU and ~30MB RAM (which was similar to the first container before it suddenly started using resources like it was doing something).

If it helps, this started as of the MC/Spigot 1.15.2 update.

Steps to Reproduce: create a new minecraft server using the spigot egg, "latest" spigot version

**Comment by parkervcp** [comment]
Please grab install logs for any servers you think are hung. The spigot install takes a long time to build the server jar files. This is why paper is the default for the panel.

**Comment by tehguy** [comment]
Went through and just let it sit while watching the logs and, yeah, it eventually installs. Still much longer than I'm sure it took for 1.14 and 1.15 but maybe my memory on it is hazy or something's wrong with my setup. I've moved on to paper, anyways

Closing the issue
