### ISSUE TITLE
SCP REQUEST

### ISSUE THREAD

**Issue by MarquesCoding** [parkervcp/eggs#417]
Service: SCP Secret Laboratory

Link to game: https://store.steampowered.com/app/700330/SCP_Secret_Laboratory/

**Comment by gOOvER** [comment]
Thats a complete NEW egg.

**Comment by gOOvER** [comment]
@parkervcp can u change the title to "REQUEST", because this is a complete differnt egg and it's not an Update :)

**Comment by MarquesCoding** [comment]
Explained what to me on discord, never been on the discord before. Some clients for my company have requested to have SCP implemented inside the pterodactyl panel.

**Comment by gOOvER** [comment]
See: https://github.com/parkervcp/eggs/pull/405

Then i ask me, why UPDATE?

**Comment by parkervcp** [comment]
If someone can verify that 405 works I will accept the PR.

**Comment by MarquesCoding** [comment]
I tried the egg that was provided from GOOvER and didn't work on my panel.

**Comment by gOOvER** [comment]
@MarquesCoding  Error pls

**Comment by MarquesCoding** [comment]
![image](https://user-images.githubusercontent.com/40672230/73386496-d6079380-42c6-11ea-9cbb-dbfe583f24cd.png)

**Comment by gOOvER** [comment]
I used the new Version; Server works as it should; only thing i saw, they change the message, when Server is ready. But u can connect

**Comment by gOOvER** [comment]
@MarquesCoding restart deamon ;)

**Comment by MarquesCoding** [comment]
What do you mean new version? I used your most recent egg, and my panel is the latest of pterodactyl, I would restart the daemon but I have many clients on this node and don't want their servers to go down for this.

**Comment by gOOvER** [comment]
I used a old Server Version. I Updated to newest and the change Server ready Notice

**Comment by gOOvER** [comment]
Ok, they don't change. Egg should work, but u MUST restart deamon after import; else it nor work ;)

**Comment by gOOvER** [comment]
@MarquesCoding  I wait 4 answer ;)

**Comment by thomasjosif** [comment]
Egg works perfectly. @gOOvER @parkervcp

**Comment by parkervcp** [comment]
resolved by #405
