### ISSUE TITLE
Unable to run Ark Server Commands

### ISSUE THREAD

**Issue by zzla** [parkervcp/eggs#418]
Panel Version: 0.7.16
Daemon Version: 0.6.12
Service: Ark: Survival Evolved
Modified: No

Expected Behavior:
Send RCON commands to Ark Server console from Panel.

Actual Behavior:
RCON Commands do not reach server.

Steps to Reproduce: 
Create ARK server, start server, attempt to pass a command to this server.

**Comment by SheppeR** [comment]
There is no console output/imput for ark linux server. You will have to use external tools like Arkon( rcon tool) to exec commands.

**Comment by parkervcp** [comment]
I am going to keep this open. I will look at adding an rcon wrapper to the startup

**Comment by lasa01** [comment]
I made a small wrapper to allow commands to be executed from the console for my own server [here](https://github.com/lasa01/ark_cliplus). It's still very experimental though.
