### ISSUE TITLE
OpenTTD Config Resetting

### ISSUE THREAD

**Issue by BadWorksFun** [parkervcp/eggs#419]
Panel Version: 0.7.16
Daemon Version: unsure/latest
Service: tycoon/openttd
Modified: no
Expected Behavior:
openttd.cfg when edited to use the values inputed
Actual Behavior:
always resets the values to default. example the password always becomes 0
Steps to Reproduce: (Step by step what to do to cause the issue)
start the game server.

**Comment by parkervcp** [comment]
If the password value is empty it looks like it sets a `0` as the value.
