### ISSUE TITLE
Game request: Minetest

### ISSUE THREAD

**Issue by tacotexmex** [parkervcp/eggs#421]
Service: Minetest

Does this expand an already existing service: N

Link to game: minetest.net

Links for server downloads:
- https://www.minetest.net/downloads/
- https://github.com/minetest/minetest
- https://launchpad.net/~minetestdevs/+archive/ubuntu/stable

Links for install steps/docs:
Use package manager of system. For example, on Debian/Ubuntu it's `sudo apt get install minetest`. However, it's important to stay on the the latest stable release which I don't think all distros do, so Ubuntu with the [stable PPA](https://launchpad.net/~minetestdevs/+archive/ubuntu/stable) is a trusty source.

**Comment by srkhost** [comment]
https://github.com/parkervcp/eggs/pull/310 ?

**Comment by parkervcp** [comment]
If you validate that the PR minetest server works I will accept the PR

**Comment by Aaronstar-McClure** [comment]
#776
