### ISSUE TITLE
Game Request: Starmade

### ISSUE THREAD

**Issue by IntenseToxicity** [parkervcp/eggs#422]
Service: Starmade

Does this expand an already existing service: N

Link to game: https://www.star-made.org/

Links for server downloads: https://www.star-made.org/download

Links for install steps/docs: https://www.star-made.org/help/setting_up_a_server

**Comment by parkervcp** [comment]
@IntenseToxicity Can you look at #268 

I don't own the game and never tested it.

**Comment by IntenseToxicity** [comment]
I apologize. It seems I am blind. I can confirm that the egg works. Thank you.
