### ISSUE TITLE
Arma III Startup Error

### ISSUE THREAD

**Issue by DevilDonkey69** [parkervcp/eggs#429]
Panel Version: Pterodactyl Panel version (0.7.16)
Daemon Version: 0.6.12 (Latest: 0.6.12)
Service: Arma III
Modified: No

Expected Behavior:
I expected the server to start up.

Actual Behavior:
Received one error. It was resolved by restarting the daemon.
Received a different error stating: "There was an error while attempting to run the start command."
Full Error: https://gyazo.com/f17b039b4a11905b3a61767a4147d3b6

Steps to Reproduce: 
Installed the egg properly, and clicked start server.
Error showed up.

**Comment by parkervcp** [comment]
You are required to have a user that owns Arma to install the server. So this is not an egg issue but the fact that you never set a user to install the server.
