### ISSUE TITLE
How to get the latest release from github actions

### ISSUE THREAD

**Issue by Dmitri233** [parkervcp/eggs#432]
bdlauncher works fine on pterodactyl.
![IMG_20200214_025904](https://user-images.githubusercontent.com/36127740/74468567-fd20b080-4ed5-11ea-9969-4adc22f82577.jpg)

But I don't know how to set up Install Script from https://github.com/BDLDev/bdlauncher/actions
Download any release

**Comment by parkervcp** [comment]
As this follows none of my issue or request formats I am closing it out.
