### ISSUE TITLE
J Music bot corrupted jar file

### ISSUE THREAD

**Issue by optimusprime338** [parkervcp/eggs#436]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.16
Daemon Version: 0.6.12
Service: Discord Bot
Modified: no

Expected Behavior:
Normal start

Actual Behavior:
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
openjdk version "1.8.0_232"
[Pterodactyl Daemon] Server marked as ON
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
:/home/container$ java -Djavax.accessibility.assistive_technologies= -Dnogui=true -jar JMusicBot.jar
Error: Invalid or corrupt jarfile JMusicBot.jar
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 1
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.

Steps to Reproduce:
1. Install J Music Bot
2. Start from console

**Comment by parkervcp** [comment]
Need to get the install logs.

`curl /srv/daemon/config/servers/${server-uuid}/install.log | nc bin.ptdl.co 99`

**Comment by optimusprime338** [comment]
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20190108-r0)
7  0%                                             8[0K7  1%                                             8[0K7  2% #                                           8[0K7  3% #                                           8[0K7  4% #                                           8[0K7  4% ##                                          8[0K7  5% ##                                          8[0K7  6% ##                                          8[0K7  6% ###                                         8[0K7  7% ###                                         8[0K7  8% ###                                         8[0K7  9% ###                                         8[0K7  9% ####                                        8[0K7 10% ####                                        8[0K7 11% ####                                        8[0K7 11% #####                                       8[0K7 12% #####                                       8[0K7 13% #####                                       8[0K7 13% ######                                      8[0K7 14% ######                                      8[0K7 15% ######                                      8[0K7 16% #######                                     8[0K7 17% #######                                     8[0K7 18% #######                                     8[0K7 18% ########                                    8[0K7 19% ########                                    8[0K7 20% ########                                    8[0K7 20% #########                                   8[0K7 21% #########                                   8[0K7 22% #########                                   8[0K7 22% ##########                                  8[0K7 23% ##########                                  8[0K7 24% ##########                                  8[0K7 25% ###########                                 8[0K7 26% ###########                                 8[0K7 27% ###########                                 8[0K7 27% ############                                8[0K7 28% ############                                8[0K7 29% ############                                8[0K7 29% #############                               8[0K7 30% #############                               8[0K7 31% #############                               8[0K7 32% ##############                              8[0K7 33% ##############                              8[0K7 34% ###############                             8[0K7 35% ###############                             8[0K(2/5) Installing nghttp2-libs (1.35.1-r1)
7 39% #################                           8[0K(3/5) Installing libssh2 (1.9.0-r1)
7 48% #####################                       8[0K(4/5) Installing libcurl (7.64.0-r3)
7 61% ##########################                  8[0K(5/5) Installing curl (7.64.0-r3)
7 87% ######################################      8[0K7100% ############################################8[0KExecuting busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 7 MiB in 19 packages
Latest version=0.2.7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     41      0 --:--:-- --:--:-- --:--:--    41
config not found getting default
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   600  100   600    0     0   2290      0 --:--:-- --:--:-- --:--:--  2290

  0  5620    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5620  100  5620    0     0   8063      0 --:--:-- --:--:-- --:--:-- 5488k
Job's Done
`
