### ISSUE TITLE
ServerJars support

### ISSUE THREAD

**Issue by joshuasing** [parkervcp/eggs#438]
Hey, The format didn't really fit my request, I just want to know if you can create eggs that use https://serverjars.com/ Thanks.

Thanks, Joshua.

**Comment by parkervcp** [comment]
Nope. We specifically wrote a ton of eggs to pull non-dcma'd server files.

**Comment by joshuasing** [comment]
@parkervcp I forgot to mention that I mean the AutoUpdater.

**Comment by parkervcp** [comment]
Not doing that either. Users can already upload new jars if they want to.

**Comment by joshuasing** [comment]
Alright, Thank you.
