### ISSUE TITLE
Soldat egg request

### ISSUE THREAD

**Issue by hypersmc** [parkervcp/eggs#443]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc)
Soldat

Does this expand an already existing service: Y/N
NO 

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://www.soldat.pl/en/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
https://www.soldat.pl/en/downloads/

Links for install steps/docs:
https://wiki.soldat.pl/index.php/Dedicated_Server

**Comment by gOOvER** [comment]
I try to create on, when i have more Time :) Looks easy to add :)

**Comment by gOOvER** [comment]
The dedicated Server is now on Steam

https://steamdb.info/app/638500/info/

Working on it :) But no ETA ;)

**Comment by gOOvER** [comment]
Created a Egg
https://github.com/gOOvER/eggs/tree/soldatserver/steamcmd_servers/soldat

But as long lib32gcc1 is not added to Debian_base image, i cant PR it

**Comment by gOOvER** [comment]
Please Test https://github.com/parkervcp/eggs/pull/508

**Comment by parkervcp** [comment]
@hypersmc Please test that egg if you can.

**Comment by hypersmc** [comment]
@parkervcp I'm on it rn!

**Comment by hypersmc** [comment]
I can confirm that the Egg is working.
