### ISSUE TITLE
ARK server not saving world on restart 

### ISSUE THREAD

**Issue by IceCupe123** [parkervcp/eggs#445]
Service: ark
Modified: no
If u restart the ark server the server dont save the world so u have a rollback 

soulution would be bevor the restart happen to send the command "cheat saveworld" to the server

**Comment by SheppeR** [comment]
If you restart the server before the sheduled save, you will have a rollback of xxx minutes.
By default Ark server save every 20 minutes.
Save frequency can be edited in GameUserSettings.ini => [ServerSettings]  => AutoSavePeriodMinutes=xxx
To prevent any rollback, save your world before restart

**Comment by Syntax3rror404** [comment]
This solution works. But i think the ARK Egg has more problems. I must kill the server. By pushing the button stop the server won't stop. I use the newest egg version.
