### ISSUE TITLE
Postgres

### ISSUE THREAD

**Issue by ZandercraftGames** [parkervcp/eggs#447]
Service: PostgreSQL

Does this expand an already existing service: a folder and config file already exist

Link to resource: https://www.postgresql.org/

Links for server downloads: https://www.postgresql.org/download/

Links for install steps/docs: https://www.postgresql.org/docs/12/tutorial-install.html

**Comment by parkervcp** [comment]
Just because the folder exists doesn't mean the egg exists and this would technically be a "new server"

Now, with that, this will need some testing.

**Comment by ZandercraftGames** [comment]
Hey... Was just commenting on how it looked you were already planning it at some point.

**Comment by parkervcp** [comment]
@ZandercraftGames This still needs testing. I make no promises about it's perf or functionality as of yet.

**Comment by ZandercraftGames** [comment]
Thats fine. I didnt expect it to immediately be perfect. If it is though, then thats a bonus 😄

**Comment by ZandercraftGames** [comment]
```postgres (PostgreSQL) 9.6.17
:/home/container$ postgres -D /home/container/postgres_db/
FATAL: "/home/container/postgres_db" is not a valid data directory
DETAIL: File "/home/container/postgres_db/PG_VERSION" does not contain valid data.
HINT: You might need to initdb.```

**Comment by ZandercraftGames** [comment]
Yeah... I just realised I need to initiate the DB... Nevermind.

**Comment by parkervcp** [comment]
It's might have been my bad. I just updated the image and installer to use postgres 12.2

**Comment by parkervcp** [comment]
@ZandercraftGames This seem to be working now? Fresh installs should all be up to date.

**Comment by ZandercraftGames** [comment]
I will try

**Comment by parkervcp** [comment]
@ZandercraftGames Did you try this out?

**Comment by parkervcp** [comment]
I have merged in the postgres egg.
