### ISSUE TITLE
TypeScript / generic Node JS 

### ISSUE THREAD

**Issue by elias-knodel** [parkervcp/eggs#449]
---------------

Service: A generic Node JS instance with typescript feature

Does this expand an already existing service: Y 

**Others:** I already made my own version of the egg. If i thing that it is ready **i will create a PR**.
I edited the generic [discord.js](https://github.com/parkervcp/eggs/blob/master/bots/discord/discord.js) egg so this is now a Node JS egg which can compile and run typescript if wanted. 

This is very useful for testing npm packages before release or for downloading, compiling and then running discord bots / typescript instances.

**Comment by parkervcp** [comment]
@elias-knodel The discord js egg just uses the packages.json to pull required packages. It's not exactly discordjs only.
