### ISSUE TITLE
Factorio Egg: Not Parsing Latest Version

### ISSUE THREAD

**Issue by wraith1200** [parkervcp/eggs#45]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.6
Daemon Version: 0.5.5
New Service: no
Service: factorio
Modified: no

Expected Behavior: download and extract latest factorio tar.gz

Actual Behavior: parsing does not store a version number when Factorio Version is set to latest or experimental during the download.

Steps to Reproduce: install factorio server with  from the repo and the package will not be downloaded when creating a new server.

Log of the install. notice no version was put into the curl for the download.

`fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20171114-r0)
^[7  0%                                             ^[8^[[0K^[7  1%                                          $
^[7 31% █████████████                               ^[8^[[0K(3/7) Installing libcurl (7.60.0-r1)
^[7 38% █████████████████                           ^[8^[[0K(4/7) Installing curl (7.60.0-r1)
^[7 57% █████████████████████████                   ^[8^[[0K(5/7) Installing tar (1.29-r1)
^[7 67% █████████████████████████████               ^[8^[[0K^[7 84% █████████████████████████████████████    $
^[7 87% ██████████████████████████████████████      ^[8^[[0K(7/7) Installing xz (5.2.3-r1)
^[7 93% █████████████████████████████████████████   ^[8^[[0K^[7 94% █████████████████████████████████████████$
Executing ca-certificates-20171114-r0.trigger
Executing glibc-bin-2.27-r0.trigger
OK: 13 MiB in 21 packages
./mnt/install/install.sh: line 7: -s: not found
./mnt/install/install.sh: line 7: jq: not found
./mnt/install/install.sh: line 8: -s: not found

 running 'curl -L https://www.factorio.com/get-download//headless/linux64 -o factorio-.tar.gz'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7625  100  7625    0     0  47067      0 --:--:-- --:--:-- --:--:-- 47067
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
copying map-gen default settings
mv: can't rename 'data/map-gen-settings.example.json': No such file or directory
copying server default settings
mv: can't rename 'data/server-settings.example.json': No such file or directory
copying map default settings
mv: can't rename 'data/map-settings.example.json': No such file or directory
./mnt/install/install.sh: line 54: ./bin/x64/factorio: not found
chmod: gamesave.zip: No such file or directory
`

**Comment by parkervcp** [comment]
Fixed by https://github.com/parkervcp/eggs/commit/41744332c854c183053a314f2b97d1cf0afc9539
