### ISSUE TITLE
[Request] Citadel: Forged with Fire

### ISSUE THREAD

**Issue by lakilla21** [parkervcp/eggs#451]
Service: Citadel: Forged with Fire

Does this expand an already existing service: No

Link to game: https://store.steampowered.com/app/487120/Citadel_Forged_with_Fire/

Links for server downloads: Only through SteamCMD AppID: 489650

Links for install steps/docs: 
Windows Server Using SteamCMD: https://steamcommunity.com/app/487120/discussions/0/1471967529574156952/

Linux Install Script (Found Online):
https://gist.github.com/nurdism/62b2ee63f93a361a52facbe0c689f6b7

**Comment by gOOvER** [comment]
LOve to see it too.

**Comment by gOOvER** [comment]
Created it :)

#497

**Comment by parkervcp** [comment]
@lakilla21 Please verify this if you can.

**Comment by gOOvER** [comment]
Can be closed.

Merged with https://github.com/parkervcp/eggs/commit/9c5b739079c98a081511986a6a55bc7039793e80
