### ISSUE TITLE
Minecraft Curseforge Modpack does not grab some server files

### ISSUE THREAD

**Issue by Mayzie** [parkervcp/eggs#458]
Panel Version: 0.7.16
Daemon Version: 0.6.12
Service: Minecraft
Modified: No
Egg used: [curseforge-generic](https://github.com/parkervcp/eggs/tree/master/minecraft_java/forge/curseforge-generic)

The egg does not appear to grab the server files properly. For example, with [this modpack](https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles) it grabs the [client files](https://media.forgecdn.net/files/2894/292/DDSS-7.2b.zip) instead, and therefore once installed, it will fail to start. Hardcoding the URL for the [server files ZIP file](https://media.forgecdn.net/files/2894/293/DDSS+Serverfiles+V.+7.2b.zip) into the egg (overwriting shell var `DOWNLOAD_URL`), will make everything run smoothly.

This issue occurs across multiple mod packs I have tried (cannot remember which ones as it was a while ago).

**Comment by parkervcp** [comment]
It's hard enough trying to account for every forge pack. I am literally using their own api to get versions. 

I will give this a look and see what I can do.

**Comment by parkervcp** [comment]
@Mayzie will you look at that please?

**Comment by parkervcp** [comment]
This should be resolved
