### ISSUE TITLE
Forge 1.7.10 won't install

### ISSUE THREAD

**Issue by LoganBwDE** [parkervcp/eggs#459]
Panel Version: 0.7.17
Daemon Version: 0.6.13
Service: Minecraft
Modified: no
Egg used: [https://github.com/parkervcp/eggs/tree/master/minecraft_java/forge/forge](Forge Enhanced)

After getting all the libraries, the Installer is stopping the install because he didnt find the forge version:
`minecraft version: 1.7.10
build type: latest
Downloading forge version null
link is invalid closing out`

**Comment by Sir3lit** [comment]
Using the egg you linked, I was able to install Forge 1.7.10 and start it. 

![Install Log](https://justmyrandomstuff.com/img/XRpu18m.jpg)
![Server Start-up](https://justmyrandomstuff.com/img/JGVAs4t.jpg)
