### ISSUE TITLE
Wine / Subnautica Nitrox Mod

### ISSUE THREAD

**Issue by Dreaming-Codes** [parkervcp/eggs#465]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Subnautica Nitrox

Does this expand an already existing service: N

Link to game: https://nitrox.rux.gg/

Links for server downloads: https://nitrox.rux.gg/download

Links for install steps/docs:
There is a graphical interface to start it. But that interface throws the file in /lib/NitroxServer-Subnautica.exe so I think it's feasible to emulate with wine.

**Comment by tolel** [comment]
https://www.youtube.com/watch?v=gvTYUUGdxPg

**Comment by gOOvER** [comment]
I don't think, it' really possible. I looks like you need to copy files from the game. So you must own the game

**Comment by gOOvER** [comment]
I think, this can be closed, until you need an own Copy of the Game to run the Server. This is nothing for a public egg

**Comment by NhProGamer** [comment]
just connect to the cli steam to download subnautica files

**Comment by TuEye** [comment]
I made an egg for Subnautica and the Nitrox mod #1012.

With the requirement to own the game. In addition, there is the requirement to receive Steamguard codes by mail and not to use the authenticator.
