### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by Adek01** [parkervcp/eggs#470]
/entrypoint.sh: line 46: 44 Segmentation fault (core dumped)

I'm running a Counter-Strike 1.6 server, when i change map and this error crash the server!

**Comment by DomiiBunn** [comment]
Hi. Did you try asking in the official discord 1st? It's faster to debug there ^.^ https://discord.gg/gzVC3j

**Comment by parkervcp** [comment]
You filled out no information here.
