### ISSUE TITLE
Minetest

### ISSUE THREAD

**Issue by alexbgameson** [parkervcp/eggs#474]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: minetest

Does this expand an already existing service: N

Link to game: https://www.minetest.net/

Links for server downloads: https://packages.ubuntu.com/bionic/amd64/minetest-server/download

Links for install steps/docs: https://packages.ubuntu.com/bionic/amd64/minetest-server/download

**Comment by parkervcp** [comment]
#310 Already exists.

**Comment by alexbgameson** [comment]
Okay. When will it be available for user?

**Comment by parkervcp** [comment]
You can download it already, that's the glory of open source.

It's not in my repo because it uses a game specific image and I don't like to have those.

**Comment by alexbgameson** [comment]
I'm sorry but I cant seem to find the egg. Any chance you could point me in its direction?

**Comment by parkervcp** [comment]
https://github.com/parkervcp/eggs/blob/c912e8cb33c6182ac7139726f6c958995f9921d0/minetest/egg-minetest-511.json
