### ISSUE TITLE
Can Someone Please help

### ISSUE THREAD

**Issue by Corprosss** [parkervcp/eggs#479]
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 10177M / 12000M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[ 0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
OK.
Connecting anonymously to Steam Public...Loaded client id: 13761814868778519313
Listening for IPv4 broadcast on: 27036
Logged in OK
Waiting for user info...OK
srcds_run
Success! App '4020' already up to date.
:/home/container$ ./srcds_run -game garrysmod -console -port 27090 +ip 0.0.0.0 +host_workshop_collection 2041055462 +map rp_downtown_tits_v1 +gamemode darkrp -strictportbind -norestart +sv_setsteamaccount +maxplayers 40 -tickrate 22
Auto detecting CPU
Using default binary: ./srcds_linux
srcds_run
/entrypoint.sh: line 25: 45 Segmentation fault (core dumped) ./srcds_run -game garrysmod -console -port 27090 +ip 0.0.0.0 +host_workshop_collection 2041055462 +map rp_downtown_tits_v1 +gamemode darkrp -strictportbind -norestart +sv_setsteamaccount +maxplayers 40 -tickrate 22
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 139
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 10177M / 12000M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[ 0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
OK.
Connecting anonymously to Steam Public...Loaded client id: 13761814868778519313
Listening for IPv4 broadcast on: 27036
Logged in OK
Waiting for user info...OK
Success! App '4020' already up to date.
:/home/container$ ./srcds_run -game garrysmod -console -port 27090 +ip 0.0.0.0 +host_workshop_collection 2041055462 +map rp_downtown_tits_v1 +gamemode darkrp -strictportbind -norestart +sv_setsteamaccount +maxplayers 40 -tickrate 22
Auto detecting CPU
Using default binary: ./srcds_linux
/entrypoint.sh: line 25: 45 Segmentation fault (core dumped) ./srcds_run -game garrysmod -console -port 27090 +ip 0.0.0.0 +host_workshop_collection 2041055462 +map rp_downtown_tits_v1 +gamemode darkrp -strictportbind -norestart +sv_setsteamaccount +maxplayers 40 -tickrate 22
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 139
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.

**Comment by parkervcp** [comment]
This is not the place to say you are having an issue please take this to discord.

**Comment by Corprosss** [comment]
please can you send me the discord link
