### ISSUE TITLE
B3Bot

### ISSUE THREAD

**Issue by poljak07** [parkervcp/eggs#480]
Hello,
Can you create B3Bot ( Big brother bot ) egg, it is very useful for some games because you can use
commands ingame and give other players rank without a lot permission, it supports a lot of games ( 30+ ) 
Games like CS:GO, COD4, you can check games list on their github site, I will paste it below.
I think it is useful because there are no b3 egg created for Pterodactyl or egg for similar apps ( server administration apps),
There are GSManager, Manu admin mod too, but can't find egg anywhere.
Github : https://github.com/BigBrotherBot/big-brother-bot
Thanks.

Does this expand an already existing service: Y

Link to game: It supports more games, 30+ games ( CS:GO, Cod4... ) 

Links for server downloads: https://github.com/BigBrotherBot/big-brother-bot

Links for install steps/docs:https://github.com/BigBrotherBot/big-brother-bot/wiki

**Comment by parkervcp** [comment]
From what I can tell B3 is an abandoned bot that has no support and no default config for anything.

their online config generator is down so I hope you have your own.

**Comment by gOOvER** [comment]
https://b3configs.reactiongaming.us/

**Comment by parkervcp** [comment]
@poljak07 have you tested this yet?

**Comment by poljak07** [comment]
It works: https://gyazo.com/07d8fd863ba25cfd9b4a3b9d2e51e352
For log path, I used web. I have "fast download" plugin, so as gameserver (cod4) log path I used: http://93.186.201.31:3007/.callofduty4/mods/vkci-pml/games_mp.log
You told me "communication" between server is impossible so local path for log is impossible too.
It is possible to read log with sftp://user:pass@host/path, I tried, but it doesn't work: https://gyazo.com/4a6b8f338e37554a4509722cb8b4158f
b3.log : https://pastebin.com/pXmide2C

**Comment by parkervcp** [comment]
You would need to install paramiko as a python package to get that to work.

**Comment by parkervcp** [comment]
@poljak07 I updated the install script to have paramiko as well to support what you are looking for.

**Comment by poljak07** [comment]
It doesn't work with remote path, b3 starts, but can't read .log and answer to commands ingame
https://pastebin.com/ePaRLtyg

**Comment by parkervcp** [comment]
That looks like the sftpclient had an error and not the egg itself.
