### ISSUE TITLE
Hurtworld Support

### ISSUE THREAD

**Issue by MrFallen** [parkervcp/eggs#486]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Hurtworld ItemV2

Does this expand an already existing service: No

Link to game: https://store.steampowered.com/app/393420/Hur

Links for server downloads: SteamCMD

Links for install steps/docs:
https://www.youtube.com/watch?v=R9nOADx7sfw

**Comment by parkervcp** [comment]
You can probably already do this with the source game default egg. 

I do not accept a youtube video as a viable source for install docs.

**Comment by parkervcp** [comment]
You can also check out - https://github.com/parkervcp/eggs/pull/34

It's a bit older but it may still work

**Comment by MrFallen** [comment]
@parkervcp doesn't works.
![image](https://user-images.githubusercontent.com/5339386/79314206-cce0a700-7f44-11ea-8846-b847b588f8e4.png)

**Comment by parkervcp** [comment]
That looks a while lot like the servers started though. It only needs some tweaking.

**Comment by MrFallen** [comment]
@parkervcp  When I tried to create my egg, I had the same error. I do not know what's the matter :(

**Comment by parkervcp** [comment]
What error exactly are you seeing? You just can't connect?

**Comment by AndyLee1024** [comment]
change start command to:   

> "./Hurtworld.x86_64	 -batchmode -nographics -exec \"host ${SERVER_PORT} ${SERVER_MAP} ${LOAD_SAVE};queryport ${QUERY_PORT};maxplayers ${MAX_PLAYERS};servername ${SERVER_NAME};creativemode ${CREATIVE_MODE};${ADMINS}\" -logfile \"${LOG_FILE}\" "

**Comment by parkervcp** [comment]
Where it logs is really unimportant. I have a better plan moving forward.
