### ISSUE TITLE
Empyrion - Galactic Survival

### ISSUE THREAD

**Issue by Markezzz** [parkervcp/eggs#487]
Service: Empyrion - Galactic Survival

Does this expand an already existing service: N

Link to game: http://empyriongame.com

Links for server downloads: ./steamcmd.sh +login anonymous +app_update 530870 +quit

Links for install steps/docs: https://empyrion.gamepedia.com/Dedicated_Server_Setup

Pterodactyl Egg from PHENOM: https://git.phenomic.net/PHENOM/Pterodactyl-Egg-Empyrion/src/branch/master

Empyrion-Docker from BitR: https://github.com/BitR/empyrion-docker

**Comment by parkervcp** [comment]
If anything @Markezzz I would tell you to ask them to PR that here. I prefer not to have a custom game specific image if I can help it.

Please reach out to the egg developer if they want to PR to the repo I will look at it.

**Comment by Markezzz** [comment]
I wrote Phenom in Discord. Unfortunately, I have not yet received an answer from him. I know you wrote about it with him in Discord in January.
Isn't there a way that you can create a new one?

**Comment by parkervcp** [comment]
The work there is done. I have no reason to take someone else's work without credit.

**Comment by Markezzz** [comment]
The work is not fully done. I have to modify files from pterodactyl to create the docker file.
i thought that pterodactyl would like to support as many games as possible to make it easy for so many people to host servers. 
it is frustrating for me to master the whole thing with my half knowledge. hence the request for an official egg.

**Comment by PHENOMICAL** [comment]
I noticed that this issue got opened here and wasn't aware of it until 2 days ago. 

I could try to improve the Docker image, so that it is more compatible with more games. But currently don't have much time to work on it, since I have to work for my apprenticeship. Back then I tried using [this](https://github.com/parkervcp/images/tree/debian/wine-4) Docker image for Empyrion, but it would just immediatly crash, even setting the xvfb variables in the entrypoint.sh script accordingly. I suspect it got something to do with the fact that my Docker image uses a Staging version of Wine (wine-staging=4.10).

Recently I tested my Docker Image against the new 1.0 beta of Wings and the panel, but it seems the rewritten Golang Docker adapter in Wings doesn't recognize locally tagged Docker images.

**Comment by parkervcp** [comment]
You would use ~/image:tag I believe for local. I am not sure but please don't build new egg on 1.0 betas.

**Comment by fabm3n** [comment]
With the latest commits to wings (the quay thing) the "bug" with the local empyrion image is fixed.
(I think he never wanted to create a new egg in the beta, he just tested it on his own after i tried to use his egg in the beta and it failed to start ^^)

**Comment by acl1704** [comment]
I've completed porting to wings and switching to stock pterodactyl images. Just need someone to test it as I don't own the game.
https://github.com/acl1704/pterodactyl-empyrion/tree/develop

**Comment by TASelwyn** [comment]
> I've completed porting to wings and switching to stock pterodactyl images. Just need someone to test it as I don't own the game.
> https://github.com/acl1704/pterodactyl-empyrion/tree/develop

I just imported the egg and tried installing it, doesn't even seem to wanna launch.
I have the game btw.

**Comment by Wannab007** [comment]
> > I've completed porting to wings and switching to stock pterodactyl images. Just need someone to test it as I don't own the game.
> > https://github.com/acl1704/pterodactyl-empyrion/tree/develop
> 
> I just imported the egg and tried installing it, doesn't even seem to wanna launch.
> I have the game btw.

I also cannot get the game to launch and have the game. Console showing:

:/home/container$ wine ./DedicatedServer/EmpyrionDedicated.exe -batchmode -log -logFile Logs/current.log "$@" &> Logs/wine.log | tail -f Logs/current.log
/entrypoint.sh: line 84: Logs/wine.log: No such file or directory
tail: cannot open 'Logs/current.log' for reading: No such file or directory
tail: no files remaining
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

**Comment by Markezzz** [comment]
> I've completed porting to wings and switching to stock pterodactyl images. Just need someone to test it as I don't own the game.
> https://github.com/acl1704/pterodactyl-empyrion

I tested your egg and got the same issue with the log file on startup.
So i started to edit the egg and get it to start. But it crashes in startup. I attached the log files.

[wine.log](https://github.com/parkervcp/eggs/files/6409340/wine.log)
[current.log](https://github.com/parkervcp/eggs/files/6409341/current.log)

**Comment by kkoshelev** [comment]
> I also cannot get the server to launch and have the game. Console showing:
> 
> :/home/container$ wine ./DedicatedServer/EmpyrionDedicated.exe -batchmode -log -logFile Logs/current.log "$@" &> Logs/wine.log | tail -f Logs/current.log
> /entrypoint.sh: line 84: Logs/wine.log: No such file or directory
> tail: cannot open 'Logs/current.log' for reading: No such file or directory
> tail: no files remaining
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

This particular error fixes by creating "logs" directory inside container, for some reason it's not created automatically.

Someone please add "mkdir /mnt/server/logs" to thje installation script.

**Comment by parkervcp** [comment]
> Issues: Console output is tailing a log file so server commands cannot be executed through the console, use the telnet server instead. Server need to be killed as the stop command doesn't work (because of above)

ARK only has an rcon console and we connect to that. Check it out to see how we use it.

If you need help you can always ask in discord.

**Comment by devildog4355** [comment]
@Rephot modified egg worked great! I had one issue and it was with the Game Seed. I had to change `"rules": "required|numeric|between:1,7"` to `"rules": "required|numeric|between:1,9999999"`

```
{
            "name": "Game Seed",
            "description": "World generation seed. Numeric between 1 and 7 characters.",
            "env_variable": "SEED",
            "default_value": "1011345",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|numeric|between:1,7"
        },
```

**Comment by MWGMorningwood** [comment]
Would it possibly be more wise to host the empyrion server manager instead?
Kind of how the FiveM egg utilizes TXAdmin to install/launch everything else

**Comment by gOOvER** [comment]
> Would it possibly be more wise to host the empyrion server manager instead?
> Kind of how the FiveM egg utilizes TXAdmin to install/launch everything else

What is the Empyrion Server Manager?

there is somewhere a working Empyrion egg

**Comment by MWGMorningwood** [comment]
> What is the Empyrion Server Manager?
> 
> there is somewhere a working Empyrion egg

My bad, Empyrion Admin Helper, the pre-packaged control panel for it.
The direct GUI interaction won't be required if a solid RCon setup is baked in. It's been a while, though.

**Comment by parkervcp** [comment]
The rcon we ship in the image is solid. It's used for ark and rust I do believe.
