### ISSUE TITLE
Only I can connect to factorio server

### ISSUE THREAD

**Issue by Cpaczek** [parkervcp/eggs#488]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.17
Daemon Version: v0.6.13
Service: factorio
Modified: no

I am able to connect to the server but my friends are unable. They can ping the server just fine but when they try and connect to the factorio server it just says could not connect to server. This is the case with modified and no modifications to the config

Steps to Reproduce: (Step by step what to do to cause the issue)

Make a new factorio server and allocate an IP and Ram.
Leave all settings default

**Comment by parkervcp** [comment]
Is this server hosted on OVH?

**Comment by Cpaczek** [comment]
Yes it is hosted on OVH

**Comment by parkervcp** [comment]
Please check and see if the game firewall is turned on. If it is turn it off.

**Comment by Cpaczek** [comment]
That was it
Thanks
