### ISSUE TITLE
Neverwinter Nights Egg Request

### ISSUE THREAD

**Issue by ne0g33k** [parkervcp/eggs#507]
Hi Parker!!! 

It would be awesome to get NWN running on ptero. Thank you for all your hard work maintaining this REPO!!

Service: NeverWinter Nights Egg
Does this expand an already existing service: N

Link to game: https://store.beamdog.com/products/neverwinter-nights-enhanced-edition

Links for server downloads: https://forums.beamdog.com/post/googleplus/discussion?id=67157

Links for install steps/docs: https://hub.docker.com/r/beamdog/nwserver/
Link to the commands, windows version but the game commands are the same, if you scroll down you will see the section.
http://neverwinternights.info/dedicatedserver.htm

**Comment by parkervcp** [comment]
I can't load the beamdog post. I will look at this. Does this require a paid copy of the game?

**Comment by ne0g33k** [comment]
https://forums.beamdog.com/discussion/67157/server-download-package-to-tide-you-over-and-also-docker

It does require a paid copy, I have no issues helping you test, I live in my office, between working from home and gaming

**Comment by parkervcp** [comment]
@ne0g33k That "install steps" is basically useless to me FYI. It's not a doc.

**Comment by NgLoader** [comment]
Currently working on this egg

**Comment by ne0g33k** [comment]
Thank you!!!!

**Comment by killertobyd** [comment]
![Screenshot 2024-01-01 190205](https://github.com/parkervcp/eggs/assets/96026375/d8d884c1-f690-4091-b516-bab19a7b6ddc)

I got it so far but the server is missing a module does anyone know where to get it ? Then I can finish the egg and upload it

**Comment by gOOvER** [comment]
missing Module?
