### ISSUE TITLE
Lost egg (SCP Secret Laboratory)

### ISSUE THREAD

**Issue by Oyplap** [parkervcp/eggs#509]
The link gives me a "404 Not found" 
https://github.com/parkervcp/eggs/blob/master/steamcmd_servers/scpsl

**Comment by gOOvER** [comment]
there are 2 differnt Version. Only Dedi and with Multidamin.

;)

**Comment by parkervcp** [comment]
The links needs to be updated. But you can still get there by going to the steamcmd  folder.

**Comment by Oyplap** [comment]
Thank you fellas!
