### ISSUE TITLE
MTA-SA web server issue

### ISSUE THREAD

**Issue by Gradin98** [parkervcp/eggs#511]
Panel Version: 0.7.17
Daemon Version: 0.6.13
Service: GTA SA - Multi Theft Auto
Modified: no

Expected Behavior:
User connect to server and download available resources from web server.
![image](https://user-images.githubusercontent.com/17599490/80457192-94bf6800-8937-11ea-9027-672eef4b2309.png)

Actual Behavior:
The panel is not opening the required web server
![image](https://user-images.githubusercontent.com/17599490/80457159-85d8b580-8937-11ea-94b6-e3af5c7f95e0.png)
![image](https://user-images.githubusercontent.com/17599490/80457266-b15ba000-8937-11ea-95f2-25a15af32aa1.png)

Steps to Reproduce:
1. Install the egg
2. Create the server
3. Connect to game

**Comment by IcedHost** [comment]
Make sure your server has the allocation for port 22005

**Comment by Gradin98** [comment]
@IcedHost yes, for both of them (22003 and 22003)
![image](https://user-images.githubusercontent.com/17599490/80466572-6a74a700-8945-11ea-969e-3b963ecbc5d9.png)
![image](https://user-images.githubusercontent.com/17599490/80466824-b58eba00-8945-11ea-82dd-1cc59d10b0b3.png)

**Comment by parkervcp** [comment]
I assume this was resolved.
