### ISSUE TITLE
Atlas Game

### ISSUE THREAD

**Issue by DAThosting** [parkervcp/eggs#512]
Service: Atlas

Does this expand an already existing service: N

Link to game: https://store.steampowered.com/app/834910/ATLAS/

Links for server downloads: https://atlas.gamepedia.com/Server_setup#Downloads

Links for install steps/docs: https://atlas.gamepedia.com/Server_setup#Downloads

Steam-Server-ID: 1006030

I tried around using the ark egg and changed some settings in the startup command, but I can't get this running.
Also on cmd based steamcmd, I didn't get the ShooterGame binary, maybe I'm just stupid :D

**Comment by gOOvER** [comment]
Sry, don't have the game to test, so i can't create a egg :) But game looks nice :)

**Comment by DAThosting** [comment]
You don't need the game to test the server startup or am I wrong :o
SteamCMD is anonymous. 

It doesn't just look nice ;)

**Comment by DAThosting** [comment]
I tried around and get it mostly installed.
But if I want to start the game, the following error appears:
`[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
:/home/container$ ./ShooterGame/Binaries/Linux/ShooterGameServer Ocean?ServerX=0?ServerY=0?AltSaveDirectoryName=00?ServerAdminPassword=?MaxPlayers=20 -log -server -NoCrashDialog -NoBattlEye
./ShooterGame/Binaries/Linux/ShooterGameServer: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
[Pterodactyl Daemon] Server marked as OFF`

I added:
`apt -y --no-install-recommends install curl lib32gcc1 ca-certificates libssl1.0.0 libssl-dev

cd /lib/x86_64-linux-gnu
sudo ln -s libssl.so.1.0.0 libssl.so.10
sudo ln -s libcrypto.so.1.0.0 libcrypto.so.10`

To the install script for the server but this also doesn't seems to work.
wings are restarted...

**Comment by parkervcp** [comment]
The packages need to be added to the image that is used to run the server not the install script.

**Comment by DAThosting** [comment]
You mean the docker image itself?

**Comment by parkervcp** [comment]
the one running the server, yes.

**Comment by gOOvER** [comment]
I have the Game New and create an egg, when i have more time

**Comment by parkervcp** [comment]
I have started looking at this and have it "somewhat" running

**Comment by djdascream** [comment]
Atlas is not realy Easy to Host
You need a "Map Grid too the Servers" 
You Need Main Servers and Expansion Server to use the Full Map 
The Card Blackwood is made for 1 Server
If you want to Use the Complete World of Atlas you need an Server Grid with 225 Servers they are linkend into an Redis Database

**Comment by parkervcp** [comment]
We have primarily been discussing it in discord. I want to note a few things as a response to you @djdascream 

> If you want to Use the Complete World of Atlas you need an Server Grid with 225 Servers they are linkend into an Redis Database
I know. I have a redis DB in my panel for this reason alone. But even with a single tile it fails to run.

> The Card Blackwood is made for 1 Server
Someone got it working using my egg with this map set

**Comment by xyo2612** [comment]
is there an egg for atlas now?

**Comment by gOOvER** [comment]
> is there an egg for atlas now?

not a working one

**Comment by parkervcp** [comment]
I am closing this for now. I have working eggs and they are in a branch.

The egg only supports the single static world as their system is weird and I have no idea why it doesn't work.
