### ISSUE TITLE
TeaSpeak

### ISSUE THREAD

**Issue by lferezy4** [parkervcp/eggs#516]
Service: stock-eggs/voice-servers/

Does this expand an already existing service: Y

Link to game: https://teaspeak.de/

Links for server downloads: https://repo.teaspeak.de/server/linux/amd64_stable/TeaSpeak-1.4.12.tar.gz

Links for install steps/docs:

**Comment by parkervcp** [comment]
https://github.com/parkervcp/eggs/tree/master/voice_servers/teaspeak
