### ISSUE TITLE
TS3MusicBot

### ISSUE THREAD

**Issue by lferezy4** [parkervcp/eggs#517]
Service: Discord/Ts3 music bot

Does this expand an already existing service: N

Link to game: https://www.ts3musicbot.net/

Links for server downloads: `removed`

Links for install steps/docs: https://www.ts3musicbot.net/index.php?mode=account&tab=how_to_install

**Comment by parkervcp** [comment]
Using that link anywhere is likely to get me DCMA'd. I have removed it. I am not buying a license just to host that and work around their startup script.
