### ISSUE TITLE
MTA:SA egg SQL exec error

### ISSUE THREAD

**Issue by vtrsz** [parkervcp/eggs#518]
Panel Version: ( 0.7.17 )
Daemon Version: ( 0.6.13 )
Service: ( Multi Theft Auto (MTA:SA) )
Modified: ( "yes", not really modded, but an error occurs in a standard MTA function when we try to execute

Expected Behavior: connect to sqlite database and work

Actual Behavior: gives a error: dbExec failed (1) SQL logic error

Steps to Reproduce: just try use the dbExec function (https://wiki.multitheftauto.com/wiki/DbExec) and gives a error

how test:

1. create a folder with any name, we will use "test" name
2. create a file called "meta.xml" inside the folder
3. open "meta.xml" and put inside:
```
<meta>
<script src="server.lua" type="server"/>
</meta>
```
4. create a file called "server.lua" and put inside it:
```
local con = dbConnect("sqlite", "donate.db")
dbExec(con, "CREATE TABLE IF NOT EXISTS donators (account TEXT, time TEXT)")
dbExec(con, "INSERT INTO donators (account, time) VALUES (?, ?)", "test", "1")
```

and the error will appears on line 3. (for me)

a possible fix at: https://wiki.multitheftauto.com/wiki/Installing_and_Running_MTASA_Server_on_GNU_Linux

If you are using the inbuilt MySQL functions such as dbConnect and dbQuery, you will need to have libmysqlclient.so.16 installed.
If you get a problem with such as "libmysqlclient.so.16: cannot open shared object file: No such file or directory", it can be solved on Debian/Ubuntu by doing this:
apt-get install libmysqlclient16
If that fails:

For 32 bit Linux, download 32 bit [libmysqlclient.so.16](http://nightly.mtasa.com/files/modules/32/libmysqlclient.so.16) and put it in /usr/lib/
For 64 bit Linux, download 64 bit [libmysqlclient.so.16](http://nightly.mtasa.com/files/modules/64/libmysqlclient.so.16) and put it in /usr/lib/

**Comment by parkervcp** [comment]
@vtrsz Can you please see if this is resolved?

**Comment by parkervcp** [comment]
I will close this now as you have not verified.
