### ISSUE TITLE
Arma 3 BEServer cannot find channel.

### ISSUE THREAD

**Issue by dragonmunday12** [parkervcp/eggs#520]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.17
Daemon Version: 0.6.13
Service: Arma 3
Modified: Added steam username and password to default variables for easy installs.

Expected Behavior: Players can join the server without issue.

Actual Behavior: When any user tries to join the server will error with "BEServer: cannot find channel #1336183221, users.card=0"

Steps to Reproduce: Install server. Set port to 2302. Start Server. Try to join server. Fail to connect fully.

When I run the server in a shell outside of pterodactyl it works fine. Maybe a problem with docker or the way the egg sets up the docker session?

**Comment by dragonmunday12** [comment]
I forgot to mention the user will get kicked after the server spits out that message.

**Comment by parkervcp** [comment]
I call out in the game readme that ARM required something like 7 ports.

You need 2302-2306 for the base game and 2344-2345 for BattleEye

**Comment by dragonmunday12** [comment]
Already forwarded ports 2300-3000

**Comment by dragonmunday12** [comment]
Which baffles me

**Comment by parkervcp** [comment]
You need to allocate them to the server in the panel... Not just port forward them.

**Comment by dragonmunday12** [comment]
Ah.

**Comment by dragonmunday12** [comment]
Yep that worked. Thank you!
