### ISSUE TITLE
java.io.IOException on minecraft paper egg while using mobile IPS

### ISSUE THREAD

**Issue by LanoHere** [parkervcp/eggs#521]
Panel Version: (0.7.16)
Daemon Version: (0.6.13)
Service: (minecraft paper)
Modified: (yes) (I modified startup parameters to get "better" performance on server)

Expected Behavior: Player with any IPS in my country can connect to the server

Actual Behavior: Player with Mobile LTE Internet can't connect to the server or after connection He gets an error:

`Internal Exception: java.io.IOException: an existing connection was forcibly closed by the remote host`

Steps to Reproduce: 
Launching minecraft on version specified by server
Trying to join to server
Getting this error immediately or after few second (not more than ~ 60)

Problem with this timeout/error only appear in minecraft servers on pterodactyl panels.
For example on ARK or CSGO servers even on the same port as minecraft server this problem doesn't appear

**Comment by parkervcp** [comment]
This is not an egg issue, It's a network issue at best.

**Comment by LanoHere** [comment]
Network on server side or client?

**Comment by parkervcp** [comment]
Mobile clients will have inherent network lag and spikes in reliability.
