### ISSUE TITLE
Minecraft Forge Enhanced - Missing Defaults

### ISSUE THREAD

**Issue by Toakan** [parkervcp/eggs#524]
The Forge enhanced egg is missing two default options which prevent a clean startup.

1) The server jar name is currently using server.jar, after the download completes for a specific version you are still getting `forge-MCVERSION-FORGEBUILD-universal.jar`. Can the Install script be modified to move this forge jar to the expected name?

2) The EULA check for Minecraft is missing / doesn't prompt properly. It may be because the server failed to launch first time?

https://github.com/parkervcp/eggs/blob/c2eea508a3d188cede2ee75166d540b9d212bb5d/minecraft_java/forge/forge/egg-forge-enhanced.json#L1

**Comment by fenpaws** [comment]
Also, I found another error in the Forge EGG.
The RegEX is not working probably, it adds a unwanted `<` at the end.

solution
`'[1].[0-9]*.[0-9]* - [0-9]*.[0-9]*.[0-9]*.[0-9]'`

**Comment by parkervcp** [comment]
should be fixed #549
