### ISSUE TITLE
TShock update for Terraria: Journey's End has released

### ISSUE THREAD

**Issue by MikedeKokkie** [parkervcp/eggs#526]
Service: Terraria (TShock)

Does this expand an already existing service: Yes

Link to game: https://terraria.org/

Links for server downloads / Links for install steps/docs: 
The Vanilla Terraria Server comes with the game, and the Vanilla Egg is already updated to the Journey's End update. However, the egg containing Tshock based server software is still using a version before Journey's End, while Tshock has now updated their software as well: https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre1

Thank you so much for the amazing software!

**Comment by parkervcp** [comment]
the tshock egg supports versions. So this is technically already supported.

Though looking at this it seems like they broke the naming scheme and I will need to update the installed to just grab the latest download link from github.

**Comment by MikedeKokkie** [comment]
Hi, apologies in advance for the possibly unnecessary post, but I just want to thank you so much for the support and the quick response!!! It's great to see the Game itself, Tshock and then Ptaerodactyl being updated so quickly within less than 48 hours of the update dropping. Can't wait to try it!

**Comment by parkervcp** [comment]
@MikedeKokkie please check that out if you can. I have tested on 1.4.0.2 and connected fine.

**Comment by MikedeKokkie** [comment]
Yep, it's working!!! Thank you so much!!!
