### ISSUE TITLE
MOTD Startup Parameter always resets using Terraria Vanilla Egg

### ISSUE THREAD

**Issue by MikedeKokkie** [parkervcp/eggs#527]
Panel Version: Don't know, I am just a container user, hopefully shouldn't matter
Daemon Version: Don't know, I am just a container user, hopefully shouldn't matter
Service: Terraria Vanilla Egg (Newest version for Journey's End)
Modified: No, only changed startup parameters

Expected Behavior: MOTD / Server MOTH Startup Parameter changes "motd=" line in config, which in turn changes the welcome message when you join the Terraria Server in-game

Actual Behavior: The "MOTD" Startup Parameter resets to "undefined" no matter what string you put in the Startup Parameter, which in turn resets the "motd=" line in the Server Config Files, making it impossible to change the welcome message. This happens even if you change the "motd=" line itself in the Server Config Files.

Steps to Reproduce: See above

**Comment by iamkubi** [comment]
Looks like the variable name is just incorrect, will be fixed shortly.

**Comment by iamkubi** [comment]
Fixed by #https://github.com/parkervcp/eggs/pull/528

**Comment by MikedeKokkie** [comment]
Thank you so much!!!!!!
