### ISSUE TITLE
Ark-Server-Tools

### ISSUE THREAD

**Issue by ryan1161** [parkervcp/eggs#53]
Could you implement this into being used so I can monitor my servers like stopping them and starting them from the panel?

https://github.com/FezVrasta/ark-server-tools

**Comment by parkervcp** [comment]
I don't see why I should implement this into the egg. You could do this all on your own. the panel already monitors the cpu and ram usage of the egg.

**Comment by parkervcp** [comment]
You have given no information on this and why it "should" be standard.

**Comment by ryan1161** [comment]
What information are you needing it’s just a tool that’s better than just using Ark dedicated server standalone. This tool has more features for hosting multiple Ark servers in one directory so that saves me a ton of hard drive space also makes clusters servers a breeze to setup.

**Comment by parkervcp** [comment]
These all sound like reasons for you but not fur everyone as a whole. I also don't like the idea of running a cluster in a single container.

**Comment by parkervcp** [comment]
As you haven't responded with a reason this should be standard I am going to close this out now.

**Comment by ryan1161** [comment]
With the authors help I got this working with the panel.
https://github.com/FezVrasta/ark-server-tools/issues/977
