### ISSUE TITLE
Bug Minecraft Egg Spigot

### ISSUE THREAD

**Issue by kekev2001** [parkervcp/eggs#536]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (0.7.17)
Daemon Version: v0.6.13
egg: (minecraft)
Modified: (no) (did you add or change things, this includes startup configs/install scripts/variables)

Expected Behavior:[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Your server container needs to be rebuilt. This should only take a few seconds, but could take a few minutes. You do not need to do anything else while this occurs. Your server will automatically continue with startup once this process is completed.
[Pterodactyl Daemon] Server marked as STOPPING
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Rebuilding server container...
[Pterodactyl Daemon] A fatal error was encountered booting this container.

Actual Behavior:[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Your server container needs to be rebuilt. This should only take a few seconds, but could take a few minutes. You do not need to do anything else while this occurs. Your server will automatically continue with startup once this process is completed.
[Pterodactyl Daemon] Server marked as STOPPING
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Rebuilding server container...
[Pterodactyl Daemon] A fatal error was encountered booting this container.

Steps to Reproduce:I have found the following for: https://hastebin.com/ejiyeziqin
The Docker image you are trying to pull is bad.
Please talk to the maintainer about fixing it.

**Comment by devil38** [comment]
Restart daemon

**Comment by kekev2001** [comment]
> Restart daemon

Did same Error

**Comment by iamkubi** [comment]
```
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`
```
Please read the template, support issues are handled on Discord.

**Comment by iamkubi** [comment]
Oh, I'm blind and you just didn't remove the template text from your issue.  Anyway, the issue is likely  that Quay is failing at the moment.  You can check https://status.quay.io/ for updates.
