### ISSUE TITLE
Add c# support to GTA RageMP

### ISSUE THREAD

**Issue by alukar4eg** [parkervcp/eggs#537]
Need to run C# module is  aspnetcore-runtime-2.2
but if i run server as usually i get problems (i think with rights) because  it return Failed to initialize CoreCLR error

This docker container already with this package . https://github.com/eisengrind/docker-ragemp-server-with-bridge

To turn on C# 
in config file need add   "csharp": "enabled"

**Comment by parkervcp** [comment]
@alukar4eg can you try using the `quay.io/parkervcp/pterodactyl-images:debian_dotnet` image and test if c# works?

**Comment by parkervcp** [comment]
Well I am going to assume this fixes it

**Comment by alukar4eg** [comment]
Hi not working ...
https://prnt.sc/v0kl6k

**Comment by parkervcp** [comment]
Did you try using the dotnet image I linked before?

**Comment by alukar4eg** [comment]
![image](https://user-images.githubusercontent.com/16633295/96270793-c48d2580-0fd4-11eb-9d66-cc6da58bd258.png)
Yep i use your link 
```

:/home/container$ ./server
Starting RAGE Multiplayer server...
[=========================================================]
MaxPlayers: 50
Sync rate: 40
Name: ALKAD:MP Unofficial server
Gamemode: freeroam
Streaming distance: 500
Announcement: disabled
Voice chat: disabled
Address: 0.0.0.0:20770
Connection limits: disabled
Encryption: disabled
NodeJS: enabled
C#: enabled
[=========================================================]
[N] Starting network... - OK: (IPv4-only) at 127.0.0.1:20770
(node:12) ExperimentalWarning: The ESM module loader is experimental.
Loading packages
Initializing bridge (0.3.7.0)..
Failed to initialize CoreCLR, HRESULT: 0x8007001F
[P] Plugin bridge.so loaded!
Started HTTP server at 20771 port.
[Pterodactyl Daemon] Server marked as ON
/entrypoint.sh: line 12: 12 Segmentation fault (core dumped) ./server
[Pterodactyl Daemon] Server marked as STOPPING
```

conf.json
```
{
  "maxplayers": 50,
  "name": "Unofficial server",
  "gamemode": "freeroam",
  "stream-distance": 500,
  "announce": 0,
  "port": 20770,
  "csharp": "enabled",
  "bind": "0.0.0.0"
}

```

**Comment by parkervcp** [comment]
As far as I can tell dotnet 3.1 is installed in the dotnet image.

There is something specific to ragemp that's not working. The `Failed to initialize CoreCLR, HRESULT: 0x8007001F` isn't very good and gives me little information.

**Comment by alukar4eg** [comment]
My be you can explore this container   . https://github.com/eisengrind/docker-ragemp-server-with-bridge ???

**Comment by parkervcp** [comment]
Yeah looking at that dockerfile it looks like they are installing dotnet 2.2

**Comment by alukar4eg** [comment]
can you try add dotnet 2.2 ? )

**Comment by parkervcp** [comment]
I have a dotnet 2.2 image and it still fails with the `Failed to initialize CoreCLR, HRESULT: 0x8007001F` error. I have no idea what is causing that.

**Comment by Onlykendo** [comment]
hi, can anyone tell me where I can find the wiki / library for scripting (by ragemp)?

**Comment by parkervcp** [comment]
This is not the place to ask about that @Onlykendo ...

**Comment by Onlykendo** [comment]
sorry but i don't know where else to ask if you have some time you could write me here Onlykendo#1417 on discord

**Comment by Onlykendo** [comment]
sorry if I still bother you but can you tell me where can I find a tutorial where to add cars on ragemp?

**Comment by DatMayo** [comment]
@alukar4eg did you try with the latest dotnet image?

**Comment by QuintenQVD0** [comment]
This egg was update some time ago and works, there seem to be no need for dotnet anymore, if it is needed for some random plugin then the user can update the image to our dotnet one, it works
