### ISSUE TITLE
OpenRct2 Egg Request

### ISSUE THREAD

**Issue by Drprofmayer2** [parkervcp/eggs#543]
Service:RollerCoaster Tycoon 2

Does this expand an already existing service: N

Link to game: https://openrct2.org/

Links for server downloads: https://openrct2.org/downloads

Links for install steps/docs: https://openrct2.org/quickstart

Just thought this would be a cool egg to have I enjoy playing this with friends.

**Comment by parkervcp** [comment]
Duplicate of #381
