### ISSUE TITLE
Astroneer Egg Request

### ISSUE THREAD

**Issue by ckippen** [parkervcp/eggs#544]
Service: Astroneer

Does this expand an already existing service: Y ([steamcmd_servers](https://github.com/parkervcp/eggs/tree/master/steamcmd_servers))

Link to game: https://astroneer.space/

Links for server downloads: SteamCMD with the appid 728470

Links for install steps/docs: https://blog.astroneer.space/p/astroneer-dedicated-server-details/

**Comment by parkervcp** [comment]
I will look as I own it as well.

**Comment by parkervcp** [comment]
So this will need to sit in hold due to issues with the server not outputting anything to console and also requiring some graphical stuff as it pops a window.

**Comment by HearNoMore** [comment]
Is there any update on this? Would really love to get this egg.

**Comment by DatMayo** [comment]
I think, there wont be any update. I had a short look around, there is a [Dockerfile for Linux](https://github.com/alatnet/astroneer-docker-server). But even this dockerfile installs a graphical interface to interact with the server. I think it could be don in ptero, but would produce a lot of overhead.

**Comment by docimin** [comment]
Astroneer server for linux is not supported and needs windows, as per also needs DirectX apparently, just as an FYI.

**Comment by pobab** [comment]
still waiting...

**Comment by parkervcp** [comment]
I am going to close this as it looks like the devs chose not to support running on linux in any way.
