### ISSUE TITLE
Factorio Fails to start after install, No Egg conf located

### ISSUE THREAD

**Issue by Sir3lit** [parkervcp/eggs#55]
Panel Version: Latest @ 0.7.9
Daemon Version: Lastest @ 0.5.6
New Service: No?
Service: Factorio
Modified: No
Expected Behavior: Server to start.

Actual Behavior: Fails to start, With following error message.
>[Pterodactyl Daemon] Server marked as STARTING
>[Pterodactyl Daemon] Checking size of server data directory...
>[Pterodactyl Daemon] Disk Usage: 134M / 1024M
>[Pterodactyl Daemon] Ensuring file permissions.
>[Pterodactyl Daemon] Running server preflight.
>[Pterodactyl Daemon] No Egg configuration located. This server cannot be started.
>[Pterodactyl Daemon] Server marked as OFF
>[Pterodactyl Daemon] Oh dear, it seems something has gone horribly wrong while attempting to boot this server.

Steps to Reproduce: Import .json, Create a new server for Factorio
npm diagnostics below
[https://hastebin.com/goyelonika](https://hastebin.com/goyelonika)

**Comment by Exonical** [comment]
Restart the daemon (wings) `systemctl restart wings`

**Comment by Sir3lit** [comment]
That's odd that I had to restart it? But it worked, Thanks
