### ISSUE TITLE
Minecraft Forge Enhanced - Incorrect Forge Download URL

### ISSUE THREAD

**Issue by ethamitc** [parkervcp/eggs#556]
Panel Version: 0.7.17
Daemon Version: 0.6
Service: Minecraft
Modified: No

Expected Behavior:
It should download forge from the correct URL.

Actual Behavior:
It has an invalid URL which results in this error: https://bin.ptdl.co/g4qyb/
Steps to Reproduce: 
1. Create New Server using Enhanced egg.
2. Set Minecraft version to 1.10.2
3. Tail the server install logs

**Comment by parkervcp** [comment]
This is not an egg issue. Per discord.
