### ISSUE TITLE
Egg for Genesys

### ISSUE THREAD

**Issue by Tio-Douglas** [parkervcp/eggs#557]
Well, I'm ordering this egg because, pocketmine contains few versions and, from what I see in 2020, most are running minecraft pocket edition servers at 0.15.10, the only system that allows players to enter 0.15.10 and Genesys ( https://github.com/iTXTech/Genisys) many use 0.15.10, so I ask you to analyze it correctly, where your eggs are, everything but genesys, like 'server.pro' they use genesys foto (https://i.imgur.com/9Tb5b97.png).
---------------

Service: Minecraft Edition (MCPE)

Does this expand an already existing service: N

Link to game: minecraft.net

Links for server downloads: https://github.com/iTXTech/Genisysf

Links for install steps/docs:

**Comment by parkervcp** [comment]
1. Yes this expands the minecraft bedrock service
2. You don't order an egg, you request one.

**Comment by parkervcp** [comment]
Also if you read their repo use pocketmine

![image](https://user-images.githubusercontent.com/1207679/83946331-05cb2880-a7de-11ea-8a22-e68740811777.png)
