### ISSUE TITLE
Request for Egg

### ISSUE THREAD

**Issue by WasThisUsernameTaken** [parkervcp/eggs#56]
Panel Version: N/A
Daemon Version: N/A
New Service: Yes
Service: SevTech Ages
Modified: N/A

Expected Behavior: N/A

Actual Behavior: N/A

Steps to Reproduce: N/A

If this is a request for a new service then you can add info here like links to the site where the server files can be found. If it is a steamcmd game have you looked at the custom source engine service yet?

Curseforge link:
[https://minecraft.curseforge.com/projects/sevtech-ages](url)

Files link:
[https://minecraft.curseforge.com/projects/sevtech-ages/files](url)

**Comment by Yomanz** [comment]
Just install it manually?

**Comment by parkervcp** [comment]
This has literally everything you need to build an egg in the server files.

All the commands you need for a script are in the zip file for the server. You could literally copy and paste your way to a fully functional egg.

We already have several minecraft (forge included) eggs that you could use as a base to build this on your own.

**Comment by parkervcp** [comment]
This should be available in https://github.com/parkervcp/eggs/commit/c70ce3eed3cc8244ed3214d633fcb57435322172
