### ISSUE TITLE
Pavlov VR Server not downloading files, need file location?

### ISSUE THREAD

**Issue by sean-phyx** [parkervcp/eggs#572]
Service: PavlovVR

Does this expand an already existing service: N

Link to game: https://store.steampowered.com/app/555160/Pavlov_VR/

Links for server downloads: http://wiki.pavlov-vr.com/index.php?title=Dedicated_server

Links for install steps/docs: http://wiki.pavlov-vr.com/index.php?title=Dedicated_server

ISSUE:
The problem I am having is simply figuring out where otherwise I would clear the files found at 
`sudo rm -rf /tmp/workshop/7777/content/555160/*`

as its a bug on the pavlovVR dedicated server page that can be fixed by clearing the files there. I already changed the tmp file size in the core.json and that has had no effect so I believe it is this.

**Comment by parkervcp** [comment]
If you rebuild the server it should clear that out.

**Comment by sean-phyx** [comment]
I rebuilt it and it works now! Thanks for the help!
