### ISSUE TITLE
/entrypoint.sh: eval: line 1: TXADMIN_ENABLE: not found

### ISSUE THREAD

**Issue by VibeGAMESNL** [parkervcp/eggs#576]
When starting using the new FiveM egg i got this error: 

/entrypoint.sh: eval: line 1: TXADMIN_ENABLE: not found

- restarted deamon
- didn't change anything at the egg.

https://i.imgur.com/4Hgozj2.png

**Comment by parkervcp** [comment]
resolved by #578
