### ISSUE TITLE
Waterfall egg not working

### ISSUE THREAD

**Issue by stonegray** [parkervcp/eggs#579]
Panel Version:  0.7.17
Daemon Version: 0.6.13
Service: Waterfall
Modified: no

Expected Behavior:
`waterfall.jar` contains waterfall.

Actual Behavior:
`waterfall.jar` contains the HTML code of a 404 error.

Steps to Reproduce: (Step by step what to do to cause the issue)
Create a new server on a node, attempt to start server.

Possibly related to #77

Contents of `waterfall.jar`:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>An Error Occurred: Not Found</title>
        <!-- removed some irrelvant CSS for readability-->
    </head>
    <body>
        <div class="container">
            <h1>Oops! An Error Occurred</h1>
            <h2>The server returned a "404 Not Found".</h2>
            <p>
                Something is broken. Please let us know what you were doing when this error occurred.
                We will fix it as soon as possible. Sorry for any inconvenience caused.
            </p>
        </div>
    </body>
</html>
```

**Comment by parkervcp** [comment]
Please make sure you have the latest version of the egg. I just installed it on my test server from the latest repo files.

**Comment by parkervcp** [comment]
I'll accept that as an "it's working" then
