### ISSUE TITLE
Rust egg issue.

### ISSUE THREAD

**Issue by Eclip7e** [parkervcp/eggs#585]
Panel Version: 0.7.17
Daemon Version: (version number) newest
Service: Rust
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)

So i change startup command to: ./runds1.sh , to run my own script on startup
![obraz](https://user-images.githubusercontent.com/17685604/85928736-7b8f5500-b8af-11ea-9648-e017435c138e.png)

And server console is spamming:
Waiting for RCON to come up...
Waiting for RCON to come up...

My startup script has same parameters as default one, but I don't want to use default script, because I need to edit parameters automatically using cron jobs for automatic server wipes.

**Comment by parkervcp** [comment]
If you customized it I cannot guarantee it will work. Especially as the rust game is wrapped by a nodejs wrapper do handle the rcon

**Comment by Eclip7e** [comment]
But its exactly same as default one!

**Comment by parkervcp** [comment]
did you also allocate enough ram to the server? it requires something like 6 gigs.

**Comment by Eclip7e** [comment]
Yes 20gb. Ok you maybe misunderstood situation, server works fine with your custom startup command, but when i edit it like I wrote in first post to run my script which is the same as your default startup command it happens what i described.

I want to use my own script to be able to edit it using cron jobs, therefore I do what I do :)

**Comment by parkervcp** [comment]
So your script should be wrapped by the wrapper.js and that is what is waiting for the rcon to come up. It sounds like your changes are making it so the server isn't actually starting, or you aren't using the variables correctly.

**Comment by Eclip7e** [comment]
server is starting

**Comment by parkervcp** [comment]
Did your set the rcon port variable to match what's in your script?

**Comment by Eclip7e** [comment]
ofc. When I use default startup command its lower part of screen, when i use my script which i posted above its upper part, so there is difference, but im adhering to syntax from documentation https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server#Command_line_parameters

![obraz](https://user-images.githubusercontent.com/17685604/85930072-c615cf00-b8b9-11ea-9df2-a9bacb72e353.png)

**Comment by Eclip7e** [comment]
You can also check startscript from official RUST server (managed by developers)
https://www.rustafied.com/how-to-host-a-rust-server-in-linux

If you use it the problem persists: Waiting for RCON to come up...

**Comment by parkervcp** [comment]
Can you open your file in sftp and get the permissions on the file please.

**Comment by Eclip7e** [comment]
644, changed them to 777 and problem still persists

**Comment by Eclip7e** [comment]
Also I'd like to point out that websocket is starting correctly:
WebSocket RCon Started on 28026

**Comment by parkervcp** [comment]
So the fact that you moved the command to a shell script and that broke it I am going to say my actual egg is perfectly fine and your modifications broke it.

You say you want to use a cron job to edit things but I have no idea what you want it to edit. Most of that you could probably do with the API honestly.

**Comment by Eclip7e** [comment]
Ok so I want to delete selected files + edit world seed value in order to wipe server into a new map. World seed value is parameter from startup command.

**Comment by Eclip7e** [comment]
This is when i use my own ./startup.sh script as Startup Command:

**Success! App '258550' already up to date.
:/home/container$ ./startup.sh
//........//
Command Line: "./RustDedicated" "-batchmode" "-nographics" "+server.port" "28025" "+rcon.port" "28026" "+rcon.password" "******" "+rcon.web" "1" "+server.maxplayers" "322" "+server.hostname" "Testing Somethin again" "+server.identity" "rust" "+server.level" "Procedural Map" "+server.seed" "12345" "+server.worldsize" "3000" "+server.saveinterval" "300" "-server.globalchat" "true" "+server.description" "Description Here" "+server.headerimage" "" "+server.url" "www.wp.pl"**

This is when I use default Startup Command:

**Success! App '258550' already up to date.
:/home/container$ ./RustDedicated -batchmode +server.port 28025 +server.identity rust +rcon.port 28016 +rcon.web true +server.hostname "A Rust Server" +server.level "Procedural Map" +server.description "Powered by Pterodactyl" +server.url "http://pterodactyl.io" +server.headerimage "" +server.worldsize "3500" +server.seed "77779" +server.maxplayers 300 +rcon.password "kekek" +server.saveinterval 600
/....../
Command Line: "./RustDedicated" "-batchmode" "+server.port" "28025" "+server.identity" "rust" "+rcon.port" "28016" "+rcon.web" "true" "+server.hostname" "A Rust Server" "+server.level" "Procedural Map" "+server.description" "Powered by Pterodactyl" "+server.url" "http://pterodactyl.io" "+server.headerimage" "" "+server.worldsize" "3500" "+server.seed" "77779" "+server.maxplayers" "300" "+rcon.password" "******" "+server.saveinterval" "600"**

Notice Command Line in both cases they are the same! but in the custom script case I cannot connect to web rcon (no its not because in one case there is "1" and in other "true" both are equivalent).

**Comment by parkervcp** [comment]
So this https://github.com/parkervcp/eggs/pull/583 would do what you want, it just does it on reinstall.

**Comment by Eclip7e** [comment]
Ok so If I might suggest. There is better option if it comes to seed - let user predefine it, if user doesn't predefine it, then generate random seed.

**Comment by parkervcp** [comment]
This only really works on reinstall. The server doesn't autostart after a reinstall. All that would be needed to to remove the seed.txt to use the seed set by the user.

Also the default is 1337 which would be a valid seed and I wouldn't want to override that with a random seed.

**Comment by parkervcp** [comment]
@Eclip7e can you check the latest update #583 It will only use the generated seed if the seed is set to 0 (current default).
