### ISSUE TITLE
Generic Discord.py discord bot

### ISSUE THREAD

**Issue by Jaimss** [parkervcp/eggs#591]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Discord

Does this expand an already existing service: N

Link to game: https://discordpy.readthedocs.io/en/latest/

Links for server downloads: N/a

Links for install steps/docs: N/a

**Comment by parkervcp** [comment]
If you had on discord the bot would have pointed you to the pixelbot egg. That is 90% of a generic egg.

**Comment by parkervcp** [comment]
Also

Yes this does expand an already existing service: bot eggs

**Comment by parkervcp** [comment]
@Jaimss Can you test this please?

**Comment by parkervcp** [comment]
@Jaimss please. I will git it a day then just PR in the new one.

**Comment by Jaimss** [comment]
Hey. Our dev decided to move our bot to jda, so I am not using this anymore, but when i initially set it up for a couple days it seemed to be working for me.
