### ISSUE TITLE
[MariaDB] Can't start : table "mysql.user" not found

### ISSUE THREAD

**Issue by Aeris1One** [parkervcp/eggs#594]
Panel Version: 0.7.17
Daemon Version: 0.6.13
Service: MariaDB/MySQL
Modified: no

Expected Behavior:
I think starting the MariaDB server.

Actual Behavior:
```bash
2020-06-30 13:19:33 0 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
2020-06-30 13:19:33 0 [Note] Server socket created on IP: '0.0.0.0'.
2020-06-30 13:19:33 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/home/container/run/mysqld/mysqld.sock' (2)
[Pterodactyl Daemon] Server marked as OFF
```

Steps to Reproduce: (Step by step what to do to cause the issue)
 - Create egg
 - Create server
 - Start server

**Comment by parkervcp** [comment]
Currently with the latest version of the egg I just imported into my test panel and installed and loaded fine. 

Can you get install logs for this server please.

**Comment by Aeris1One** [comment]
Hmm... How to get install logs ? 😅
I know how to grab daemon's logs but there was nothing strange

**Comment by Aeris1One** [comment]
Ok. Here's the full install log : 
```
Please check all of the above before submitting a bug report at http://mariadb.org/jira

+ '[' -f /mnt/server/custom.my.cnf ']'
+ echo -e 'moving current config back in place'
moving current config back in place
+ mv /mnt/server/custom.my.cnf /mnt/server/.my.cnf
+ echo -e 'install complete'
install complete
+ exit
```

**Comment by Aeris1One** [comment]
So, here's the full log :
https://paste.ubuntu.com/p/v97y3mJq45/

**Comment by parkervcp** [comment]
Judging from the logs you posted you reinstalled over an old database. This conflicted with the config the installer downloaded and had tried to install the db against.

**Comment by Aeris1One** [comment]
I had MariaDB installed on the server but disabled (cause I migrated the Pterodactyl database to a shared host some times ago), I removed and purged, should be ok now, right ?

**Comment by Aeris1One** [comment]
Hmmm... Not at all, same error :/
What can I do ?

**Comment by parkervcp** [comment]
Please make sure you are using the latest released version of the egg.

**Comment by Aeris1One** [comment]
I installed the egg one or two hours ago, so I think it's already the latest

**Comment by parkervcp** [comment]
So this egg should have nothing to do with your host mariadb. I am not sure where the config it is finding is coming from because it shouldn't be.
