### ISSUE TITLE
Game Request | Astroneer

### ISSUE THREAD

**Issue by StormyIceLeopard** [parkervcp/eggs#600]
Service: Astroneer

Does this expand an already existing service: Unsure what this question means

Link to game: [https://astroneer.space/](https://astroneer.space/)

Links for server downloads:
DOWNLOAD DEDICATED SERVER FILES
First off, you are going to need to download the Dedicated Server files via steam. Load into steam and navigate to LIBRARY > TOOLS. Find ASTRONEER Dedicated Server in the list and install.

Links for install steps/docs:
[https://astroneer.space/dedicatedserver/](https://astroneer.space/dedicatedserver/)
Located under "Q: How do I set up my own server at home?"

**Comment by parkervcp** [comment]
Is #544 a joke to you or something?

**Comment by StormyIceLeopard** [comment]
I apologize, new to GitHub for the most part (I don't really use it outside of one project) and forgot that issues can be searched.
This was not intentional.
