### ISSUE TITLE
Rust+ App Not Working (Includes how to fix the issue)

### ISSUE THREAD

**Issue by JackW6809** [parkervcp/eggs#613]
Service: Rust (SteamCMD)
Modified: Yes (Changed startup command to fix the bug)

Expected Behavior:
Rust+ App to make the connection to the rust server.

Actual Behavior:
Makes no connection to the server.

Steps to Reproduce: 
Launch the server with the default startup command and it will work fine apart from the fact that their Rust+ app does not work.

To fix it:
Add this to the Startup Command. E.g:
./RustDedicated -batchmode +server.port {{SERVER_PORT}} +app.port {{SERVER_PORT}} +server.identity "rust" +rcon.port {{RCON_PORT}} +rcon.web true +server.hostname \"{{HOSTNAME}}\" +server.level \"{{LEVEL}}\" +server.description \"{{DESCRIPTION}}\" +server.url \"{{SERVER_URL}}\" +server.headerimage \"{{SERVER_IMG}}\" +server.worldsize \"{{WORLD_SIZE}}\" +server.seed \"{{WORLD_SEED}}\" +server.maxplayers {{MAX_PLAYERS}} +rcon.password \"{{RCON_PASS}}\" +server.saveinterval {{SAVEINTERVAL}} {{ADDITIONAL_ARGS}}

**Comment by iamkubi** [comment]
I added support for the Rust+ app in https://github.com/parkervcp/eggs/commit/4c8493ed55c3a3cab384bc70fe3e147b5e0585c3.  I've tested and it's working, so I suspect you aren't using the latest egg.

**Comment by parkervcp** [comment]
So it reads like this just needs to be upped to the main panel repo.

**Comment by JackW6809** [comment]
From what I can see, your commit has been removed as it's no longer in the startup parameters. Maybe the fix can be added once again?
![image](https://user-images.githubusercontent.com/53652452/89731804-dcc74e00-da41-11ea-92b2-37f97dc5d469.png)

**Comment by iamkubi** [comment]
So you're using either rust_staging or rust_autowipe then.  The `rust` egg is under stock-eggs, which is the one I updated.  It looks like autowipe was based on staging instead of the main egg so it didn't get the new flag.

I'm suggesting we convert everything in stock-eggs to symlinks because I think the current structure is confusing, and it doesn't make sense to have the Rust eggs specifically in different paths.

**Comment by JackW6809** [comment]
This issue still persists, even on a fresh install of the panel and using the included Rust egg the startup parameter has still not been fixed to include `+app.port {{SERVER_PORT}}`. How is this still a bug?
