### ISSUE TITLE
MongoDB Egg Request

### ISSUE THREAD

**Issue by Tim3Game** [parkervcp/eggs#615]
Service: MongoDB Community

Does this expand an already existing service: N

Link to service: https://www.mongodb.com/

Links for server downloads: https://www.mongodb.com/try/download/community

Links for install steps/docs: https://docs.mongodb.com/manual/administration/install-on-linux/

**Comment by ZandercraftGames** [comment]
+1 On this

**Comment by shootdot** [comment]
+1

**Comment by parkervcp** [comment]
This needs testing.
It drops you into what is essentially a root command prompt for mongo

@Tim3Game @ZandercraftGames @stijnb1234 @shootdot

**Comment by parkervcp** [comment]
I have ran the egg with no issues on my end this will close out as I merge the egg.
