### ISSUE TITLE
Arma 3 server architecture issues

### ISSUE THREAD

**Issue by jlillis** [parkervcp/eggs#619]
Panel Version: 0.7.17
Daemon Version: 0.6.13
Service: Arma 3 Server
Modified: no

Expected Behavior:
After installation, the arma3server and arma3server_x64 executables should be present and the daemon should run the correct one based on system architecture.

Actual Behavior:
After installation, only the arma3server executable is present. Also, there appear to be other issues related to architecture "mismatch" in the server console:
`ERROR: ld.so: object '/libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

Steps to Reproduce:
1: Create a server using the Arma 3 Server egg
2: Open the file manager for the server
3: Observe that only the arma3server executable is present
4: Open the console for the server
5: Observe ELFCLASS errors that appear in the console

**Comment by parkervcp** [comment]
So after looking into this I am using the default steamcmd install. I am not specifying 32 bit or 64. If it was default to install `arma3server_x64` then it would be there.

As far as I can find online there is no `arma3server_x64` either. I am specifically calling that the linux server doesn't have that at least.

**Comment by jlillis** [comment]
Looks like I was somewhat mistaken - the 64-bit binaries for Linux aren't available _by default_ but are available on the performance and profiling branches on Steam:
`app_update 233780 -beta profiling -betapassword CautionSpecialProfilingAndTestingBranchArma3 validate`

Since this branch is "experimental" it probably isn't desirable to use it unless you're willing to go and modify the egg yourself. Unless there's something to do to this egg to resolve the error I mentioned, I guess this issue can be closed?

**Comment by parkervcp** [comment]
at this point I don't see me updating to support an experimental release in any way.
