### ISSUE TITLE
"Waiting for RCON to come up..." 

### ISSUE THREAD

**Issue by syntaxxl** [parkervcp/eggs#623]
---------------

Panel Version: 0.7.17
Daemon Version: 0.6.13
Service: Rust
Modified: no

Expected Behavior: For it to connect to RCON, but it doesn't. Don't know what else to tell you, sorry.

Actual Behavior: After loading some stuff for the server, it says: "Waiting for RCON to come up..." , and just keep spamming it. I've left it over night and didn't work. I tried multiple things, but I couldn't get it to fix, so any help would be appreciated.
Just please, remember that I'm new to this whole server with Pterodactyl thing, so being patient would be nice.

Steps to Reproduce: Install the Rust server and click Start. That's all I did, and it keeps popping up the RCON message.

**Comment by parkervcp** [comment]
If it keeps saying that your rust server never started. You probably gave it too little ram. That is a common issue.

**Comment by syntaxxl** [comment]
It has 11 GB or ram, sorry for taking so long to answer

**Comment by parkervcp** [comment]
I can also be other settings causing it to fail to start.

**Comment by syntaxxl** [comment]
Sorry for taking so long to answer again - job is time consuming. 

Do you mind if I send you some screenshots so you can help me out? 
I'm just trying to play with friends.

**Comment by parkervcp** [comment]
If you can get a capture of the shell output when it starts.

**Comment by parkervcp** [comment]
Seeing as there hasn't been a response and this is only affecting you I will be closing this. If you do continue to have this issue please take it to the #eggs channel in discord.
