### ISSUE TITLE
Cs Go Startup

### ISSUE THREAD

**Issue by JavituRec** [parkervcp/eggs#63]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: last-0.7.9
Daemon Version: last-0.6.3
Service: (minecraft/factorio/etc)
Modified: no

Erro in startup:

WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[ 0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Update state (0x5) validating, progress: 21.69 (3912560046 / 18035186392)
Error! App '740' state is 0x202 after update job.
:/home/container$ ./srcds_run -game csgo -console -port 25570 +ip 0.0.0.0 +map de_dust2 -strictportbind -norestart +sv_setsteamaccount HIDE:)
/entrypoint.sh: line 17: ./srcds_run: No such file or directory

**Comment by MikkelDK** [comment]
line 17: ./srcds_run: No such file or directory << Are you sure, it has installed? ;)

**Comment by rouing** [comment]
Can you show me a screenshot of the Root Directory?

**Comment by JavituRec** [comment]
Off course, this a root directory of server CSGO
![root of server csgo](https://user-images.githubusercontent.com/10663192/44310568-f0062c80-a3d8-11e8-9b9e-69cb2c39e026.png)

**Comment by parkervcp** [comment]
this just looks like the server failed to install. closing this out.
