### ISSUE TITLE
Request for DayZ and if i can get some help with pterodactyl

### ISSUE THREAD

**Issue by gamingmastyer** [parkervcp/eggs#630]
I have multiple dedicated server which are home hosted and are on one ip is it somehow possible to create nodes from the other 2 servers so i can control everyithing from one website. Do i need to change the deamon port or something else and how?

Now to get back to DayZ i think it is possible to make a dayz server from the arma egg but for starters like me that is pretty hard if you are able to make a dayz egg or a tutorial on how to make it from an arma egg.
Thanks in advance
---------------

Service: (Ex. DayZ)

Does this expand an already existing service: N

**Comment by parkervcp** [comment]
This repo has nothing to do with support for pterodactyl. This should only be a request for a game server.

As far as I understand the dayz dedicated server doesn't run on linux in any capacity.
