### ISSUE TITLE
FTB Not found

### ISSUE THREAD

**Issue by harveyconnor** [parkervcp/eggs#631]
Hi it appears the FTB url has changed from projects to modpack.
I cannot use your egg to download the modpack.
https://www.feed-the-beast.com/modpack/ftb_sky_odyssey

**Comment by parkervcp** [comment]
Ah yes. They changed the site to something more like an SPA. Instead of trying to support this crap I am going to just drop FTB support.

**Comment by parkervcp** [comment]
If anything you can try https://github.com/parkervcp/eggs/pull/617

**Comment by parkervcp** [comment]
@harveyconnor have you tried #617 ?

**Comment by harveyconnor** [comment]
not yet, will update you when I have :)

**Comment by parkervcp** [comment]
I will consider this resolved by #617
