### ISSUE TITLE
7DTD telnet password 

### ISSUE THREAD

**Issue by aaronkt** [parkervcp/eggs#632]
Using a discord integration bot I had to change the telnet password. Now the console makes me type it in when starting the sever. I tried adding
 -TelnetPassword="password"
After the port but still requires password when starting now. 

Is there something I can change to make it auto Imput the password?

**Comment by parkervcp** [comment]
`telnet` doesn't allow for adding a user and/or password to be part of the command. It's a pretty simple protocol that only makes a conection.

By adding a password that is something handled by the server itself and input is needed from there,
