### ISSUE TITLE
Discord.py ffmpeg not working

### ISSUE THREAD

**Issue by Minlor** [parkervcp/eggs#637]
Panel Version: 0.7.18
Daemon Version:  0.6.13
Service: discord.py
Modified: no

Expected Behavior:
1. When i try to run it thourgh my bot it should just start playing music
2. when you type in ./ffmpeg.exe it should open up ffmpeg
Actual Behavior:
1. It says that it cant find it
2. It says access denied
Steps to Reproduce:
1. Just upload ffmpeg and try to run it with a bot
2. use this small script to try to manually run ffmpeg
import os

while 1:
    os.system(input(">>>"))

when it starts the program just go to the console and type in "./ffmpeg.exe

**Comment by parkervcp** [comment]
1. This is not a mono/wine egg so it won't run a exe.
2. Please supply some sort output from the startup.

**Comment by Minlor** [comment]
![image](https://user-images.githubusercontent.com/40441731/89219511-322dd600-d5d0-11ea-943f-545c4a3f2e02.png)

**Comment by parkervcp** [comment]
I added ffmpeg to the base python image. This "should" work now.

**Comment by Minlor** [comment]
Alright, will test it and tommorow, and I will tell you how it goes.

**Comment by Minlor** [comment]
Same issiue

**Comment by SaqibYT** [comment]
hi Minlor

**Comment by parkervcp** [comment]
@Minlor can you git me the output you are seeing?

**Comment by parkervcp** [comment]
What I see you are trying to do it run an ffmpeg exe file via the console. This isn't windows. It can't run an exe.

**Comment by parkervcp** [comment]
Well I am closing this. It's been 2 weeks since I last asked for input here.
