### ISSUE TITLE
Discord.js bot egg always in "Starting"

### ISSUE THREAD

**Issue by alekitopi** [parkervcp/eggs#638]
Panel Version: 0.7.18
Daemon Version: 0.6.13
Service: discord bots
Modified: no

Expected Behavior: When starting the bot, while installing NodeJS dependencies the server status should be "Starting" but once the bot is started, the server status should change to "Online".

Actual Behavior: When starting the bot, no matter what state it is in, the status of the server is always "Starting".

Steps to Reproduce: Create a server with the egg, place a base bot and start it.

**Comment by parkervcp** [comment]
In the egg after you import it in the start config there ise a section that says "change this part".

The egg is generic and I cannot guess what your app/bot will write out once it's started. This is no an issue so much as it's the way it was made on purpose.

**Comment by alekitopi** [comment]
Even if you put a text in the section that says "change this part" and make the bot show by console the same text but it still doesn't work.

**Comment by parkervcp** [comment]
You need to restart the daemon and restart the server too. Old servers may not ever update properly and would need to be re-created.

**Comment by alekitopi** [comment]
Can the text be set through the egg variables?

**Comment by parkervcp** [comment]
No it cannot.
