### ISSUE TITLE
Discord.js egg cannot be stopped. (needs to be killed)

### ISSUE THREAD

**Issue by alekitopi** [parkervcp/eggs#639]
Panel Version: 0.7.18
Daemon Version: 0.6.13
Service: discord bots
Modified: no

Expected Behavior: When a bot is on, hitting the "Stop" button should stop it and end it (by running Ctrl+C / ^C). 

Actual Behavior: When a bot is on, hitting the "Stop" button leaves it in "Stopping" status but the bot is still working properly, you need to press the "Kill" button for it to stop. (Same with the "Restart" button).

Steps to Reproduce: Create a bot with the egg from discord.js, place a base bot and press the "Stop" or "Restart" button.

**Comment by 104938-sevenwolden** [comment]
program your bot so that it stops it process if it detects ^C in the terminal

**Comment by alekitopi** [comment]
NodeJS stop when you presa Ctrl+C like every process of Linux.

**Comment by parkervcp** [comment]
Your bot is stuck starting and you cannot hist stop on a service that is starting. I commented on your other issue as to what you need to change.
