### ISSUE TITLE
CurseForge Egg (Valhelsia 2) not working

### ISSUE THREAD

**Issue by tommyvange** [parkervcp/eggs#642]
**Information**
Panel Version: `0.7.18`
Daemon Version: `0.6.13`
Service: `eggs/minecraft/java/forge/curseforge-generic/`
Modified:` No`

System: `Ubuntu Server 20.04`
Docker: `Docker version 19.03.12, build 48a66213fe`

**Expected Behavior:**
For it to install the Valhelsia 2 modpack from curseforge.

**Actual Behavior:**
Installs and Extracts all the files, but then proceeds to delete all the files when it fails to run `FTBServer.jar`.

**Steps to Reproduce: (Step by step what to do to cause the issue)**
1. Install Egg
2. Restart Daemon
3. Make Server
4. Enter the modpack ID `357858` (for Valhelsia 2)
5. Proceed to watch it fail installing the server.

**Install Log**
https://gist.github.com/tommyvange/4499926c4e64e60c344145475f8c42dd

**Comment by tommyvange** [comment]
Just to rule out a server/firewall issue, I tried installing **FTB Revelation `283861`** and it worked flawlessly. This seems to only be an issue with **Valhelsia 2 `357858`**.

**Comment by tommyvange** [comment]
**Update**
This issue is also present in:
- Valhelsia 3 `388169`
- Valhelsia `331920`

**Comment by parkervcp** [comment]
I am looking into this. I suspect it's how they are packing the files or handling the install.

**Comment by parkervcp** [comment]
So as far as I can tell the server json file they have isn't actually a manifest.json file and is a completely new format.

**Comment by parkervcp** [comment]
@tommyvange does the install actually say failed in the panel?

**Comment by tommyvange** [comment]
@parkervcp Yes, it says install failed and deletes the server files.

**Comment by parkervcp** [comment]
@tommyvange can you try that egg update?

**Comment by tommyvange** [comment]
Yes, I can try it later or tomorrow. Depends on when I get home :)

**Comment by parkervcp** [comment]
@tommyvange I have test this change and it's working for me. I will close this out.
