### ISSUE TITLE
[Request] Travertine MC proxy

### ISSUE THREAD

**Issue by lrmtheboss** [parkervcp/eggs#644]
Service: Minecraft/proxy

Does this expand an already existing service: Y

Link to game: https://papermc.io/downloads#Travertine

Links for server downloads: https://papermc.io/downloads#Travertine

Links for install steps/docs: just a jar file to run like Waterfall

---
Travertine is a fork of Waterfall from the people who make it but with 1.7 support.
All commands and variables should be the same as Waterfall.

**Comment by parkervcp** [comment]
@lrmtheboss can you test that egg out?

**Comment by lrmtheboss** [comment]
Yes, the egg worked.

In variables, under jar name and build version, you might want to change it to say Travertine instead of Waterfall.

**Comment by parkervcp** [comment]
I thought I changed them all but I am also uninterested in changing things further.
