### ISSUE TITLE
Discord.js egg problem.

### ISSUE THREAD

**Issue by SaqibYT** [parkervcp/eggs#648]
Panel Version: 0.7.18
Daemon Version: 0.6.13
Service: discord.js
Modified: no

Hi. so ive been using the djs egg for a while now but ever since i changed webservers(from nginx to apache). the bot keeps on going offline after 5minutes. but the server stays on. theres nothing wrong with the code as it perfectly works with heroku. if you can please reply asap. as one of my paid clients are also having this issue. 

So to break it down:

I switched from nginx ot apache
Bot keeps on going offline after 5minutes
Server stays on but no sign of the bot being online

**Comment by parkervcp** [comment]
This sounds like a websocket issue or something that worked fine in nginx and is not an egg issue.
