### ISSUE TITLE
Server Crashs due to the Egg only happens to few servers

### ISSUE THREAD

**Issue by HydroGames-dev** [parkervcp/eggs#653]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number)
Daemon Version: (version number)
Service: (minecraft)
Modified: (no) (no)

Expected Behavior:

Actual Behavior:

Steps to Reproduce: (Step by step what to do to cause the issue)
If you add plugins and then start the server
![Screenshot_20200816-101045_Chrome](https://user-images.githubusercontent.com/69600115/90326876-75fae500-dfab-11ea-8526-cfd98dd4e038.jpg)
 the server it shows
/entrypoint.sh: line 13: 14 Segmentation fault ${MODIFIED_STARTUP}
and crashs doesn't even start the server

**Comment by parkervcp** [comment]
You didn't fill out the template fully.

You added plugins that could be doing anything and are most likely causing the issues you are seeing

**Comment by HydroGames-dev** [comment]
> You didn't fill out the template fully.
> 
> You added plugins that could be doing anything and are most likely causing the issues you are seeing

it happened before too i didn't have any plugins

**Comment by HydroGames-dev** [comment]
the server crashed and started and crashed
