### ISSUE TITLE
Node Args

### ISSUE THREAD

**Issue by Skeec54** [parkervcp/eggs#654]
Im trying to use the egg for discord bots and wanted to ask where i setup the arguments for node, like "node bot.js arg1 arg2 arg3....". is there a option for this or does it requires to edit the egg or anything?

**Comment by parkervcp** [comment]
Technically the bot J's file variable can be as long as you want and got can add flags there.

**Comment by Skeec54** [comment]
where do i add it?

**Comment by parkervcp** [comment]
The `BOT_JS_FILE` variable.

**Comment by Skeec54** [comment]
ok Thanks!
