### ISSUE TITLE
Killing Floor 1 Egg Request

### ISSUE THREAD

**Issue by Kanarota** [parkervcp/eggs#656]
Service: Killing Floor 1

Does this expand an already existing service: No

Link to game: https://store.steampowered.com/app/1250/Killing_Floor/

Links for server downloads: Through SteamCMD (APPID 215350): https://wiki.tripwireinteractive.com/index.php/Dedicated_Server_(KillingFloor)#Linux

Links for install steps/docs: https://wiki.tripwireinteractive.com/index.php/Dedicated_Server_(KillingFloor)

**Comment by parkervcp** [comment]
Honestly the source engine custom egg would probably run this fine. It would just need a start command set for the server.
