### ISSUE TITLE
MC Bedrock egg has properties file issues

### ISSUE THREAD

**Issue by Tranker101** [parkervcp/eggs#659]
**Panel Version:** 1.0.0-beta.5
**Daemon Version:** Not sure
**Service:** Minecraft Bedrock
**Modified:** No

**Expected Behavior:** Server boots up, reads server.properties, and loads with those configurations (difficulty, seed, cheats on/off, server name, level name, etc.)

**Actual Behavior:** The server seems to be having issues reading the server.properties file or it reads it wrong, as it formats the file in a different way on startup than the normal format (with spaces and without comments). The difficulty always loads as easy, cheats are always off, and all names (level, server) have an extra space at the beginning that are not supposed to be there. This leads to complications with transferring your own world into the server and making sure names line up.

**Steps to Reproduce:** Install the MC Bedrock server, change either the difficulty or cheats-allowed status, then run the server and join. You will find that cheats will be locked off with no way to turn them on, and the difficulty will always be easy when the server is booted up (you can change that though, it just reverts). Any level or server name you entered will be reflected with an extra space before it in the files and in-game.

I really like the whole Pterodactyl interface and would love to use it further but I'm using this for an MC test server and these are bugs that make it unusable...

**Comment by Oberfail** [comment]
You're quiet behind, I'd suggest you to update both the panel & the wings / daemon.

**Comment by parkervcp** [comment]
You are also posting an issue for the pterodactyl beta to the egg repo which has nothing to do with the panel.
