### ISSUE TITLE
Battlefield 2 Egg Request

### ISSUE THREAD

**Issue by VordyV** [parkervcp/eggs#660]
Service: Battlefield

Does this expand an already existing service: N

Link to game: http://playbf2.tilda.ws/ /Working client from PlayBF2\

The game is old, but it still works and is not very popular.

Links for server downloads: *impossible. The developer stopped supporting a long time ago*
Links for install steps/docs: 
Installing the game (the installer is downloaded. There is nothing complicated here, even a noob newbie.) Server installation /Linux\(http://wiki.opennet.ru/Battlefield_2_Dedicaded_Ranked_Server_v1.50_%2B_bf2statistics_%D0%BD%D0%B0_FreeBSD)

**Comment by parkervcp** [comment]
Without official server support this gets me narrowly close to a DMCA and I won't build an egg for this.
