### ISSUE TITLE
All in one custom egg. (It will be a payed job)

### ISSUE THREAD

**Issue by SaqibYT** [parkervcp/eggs#666]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Paper, Vanilla, Bungeecord, Pocketmine, Altay, Bedrock Vanilla, Discord.py, Discord.js, discord.php, discord.java, discord.ts, database hosting, Garry's mod, Ark, rust all in one egg

I want this to be a custom egg for my host. I will pay you if you can make it. Dm me if you can

Saqib#7187

**Comment by parkervcp** [comment]
No
