### ISSUE TITLE
latest ARK Egg

### ISSUE THREAD

**Issue by DAThosting** [parkervcp/eggs#668]
Panel Version: 0.7.18
Daemon Version: v0.6.13
Service: steam/ark
Modified: no

Expected Behavior: 
Runs without problems, startup etc.

Actual Behavior:
Ark server does not come up.
Even after one hour I can't connect.

Here is my log:
https://pastebin.com/yH05vkLz

Steps to Reproduce: 
Install the ark egg provided in steamcmd_servers

The ARK stock egg also doesn't work for me.
The server itself starts like it should but I can't connect via steam, also steam server list doesn't show anything.
All other games on pterodactyl are working, csgo e.g. is shown also in steam server list.

**Comment by danny6167** [comment]
Make sure you have added the extra ports that are required and when adding to the steam server list, use the QUERY port, not game port.
