### ISSUE TITLE
[Forge Enhanced] Possible error with 1.0-rc2

### ISSUE THREAD

**Issue by Aeris1One** [parkervcp/eggs#670]
Panel Version: 1.0-rc2
Daemon Version: 1.0-rc2
Service: Minecraft Forge Enhanced
Modified: No

I had this error https://github.com/pterodactyl/panel/issues/2275 and it can **possibly** be an error with Forge Enhanced egg. I don't know how to solve, that's why I open this issue.

**Comment by parkervcp** [comment]
That is a daemon issue as far as I am concerned. I am thinking it is the `"done"` value not parsing properly in the daemon.
