### ISSUE TITLE
GTA V: FiveM Windows build egg

### ISSUE THREAD

**Issue by VibeGAMESNL** [parkervcp/eggs#672]
Hi!

Some anticheat software and resources only works on the windows build of FiveM. It would be nice (if possible) to make a FiveM egg that is using the windows build of FiveM and not Linux.

---------------

Does this expand an already existing service: Yes and no

Link to game: https://fivem.net

Links for server downloads: https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/

Links for install steps/docs: https://docs.fivem.net/docs/server-manual/setting-up-a-server/

**Comment by parkervcp** [comment]
I am not particularly interested in running the windows version of the server.

From my experience it uses multiple times the ram and cpu to run.
