### ISSUE TITLE
Tekkit Egg Request

### ISSUE THREAD

**Issue by Darksilence43** [parkervcp/eggs#673]
Can someone make a Tekkit egg? Thanks!

Here is a link to the modpack: https://www.technicpack.net/modpack/tekkitmain.552547

**Comment by hypersmc** [comment]
Please use #681 (https://github.com/parkervcp/eggs/pull/681)

**Comment by gOOvER** [comment]
Fixes #681

**Comment by parkervcp** [comment]
resolved by #681
