### ISSUE TITLE
Server status

### ISSUE THREAD

**Issue by shootdot** [parkervcp/eggs#678]
Hi there,
I am facing an issue with server status it shows only starting and it doesn't change but the bot works, I am using the egg discord.js

**Comment by parkervcp** [comment]
You need to edit the egg to match what you but says on start.

It's currently to "change this part"

**Comment by shootdot** [comment]
I did that

**Comment by shootdot** [comment]
![image](https://user-images.githubusercontent.com/55920587/92305562-7d555300-ef99-11ea-97e1-24721947165f.png)

**Comment by shootdot** [comment]
![image](https://user-images.githubusercontent.com/55920587/92305593-c7d6cf80-ef99-11ea-8930-def7a3a845f3.png)

**Comment by shootdot** [comment]
@parkervcp
