### ISSUE TITLE
7 days to die - console

### ISSUE THREAD

**Issue by Zekhap** [parkervcp/eggs#682]
Panel Version: 1.0.0-rc.3
Daemon Version: 1.0.0-rc.3
Service: 7 days to die
Modified: no

Expected Behavior: It wont register anything in the console, no commands is working. Also server is still on when i kill the server until i start it again

Actual Behavior: if i write help is should show all commands, quit/shutdown wont register. when i press stop

Steps to Reproduce: Download egg, install egg, create server, launch.

**Comment by parkervcp** [comment]
Please verify this is an issue is the current stable version of the panel.

If you are running the RC I expect there to be issues.
