### ISSUE TITLE
CryoFall Egg Request

### ISSUE THREAD

**Issue by KyanG7** [parkervcp/eggs#685]
Service: (Ex. minecraft/factorio/etc)
CryoFall? Its on steam and already links with docker.

Does this expand an already existing service: Y/N
N

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://store.steampowered.com/app/829590/CryoFall/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
https://wiki.atomictorch.com/CryoFall/Server/Setup
(Official page, dev redirects you https://steamcommunity.com/app/829590/discussions/5/1675812484358985235/)

Links for install steps/docs:
https://wiki.atomictorch.com/CryoFall/Server/Setup

**Comment by hypersmc** [comment]
It's not on SteamCMD but i will let that slide.

**Comment by KyanG7** [comment]
> 
> 
> It's not on SteamCMD but i will let that slide.

Fixed. My bad I assumed it was on steamcmd based on it being on steam.

**Comment by hypersmc** [comment]
@parkervcp I will look into this one 👍

**Comment by parkervcp** [comment]
This was merged
