### ISSUE TITLE
7 Days to die not starting the server (telnet error)

### ISSUE THREAD

**Issue by jeanklann** [parkervcp/eggs#69]
**Panel Version**: 0.7.9
**Daemon Version**: 0.6.4
**Service**: 7 Days to die
**Modified**: yes and no (tried with default and modifying)
**Expected Behavior:**
Run the server correctly, not crashing on telnet

**Actual Behavior:**
It crashes the serverwith the error 
telnet: Unable to connect to remote host: Connection refused

[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 3551M / 5000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.  <<<--- it stucks in this part for about 5 sec.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 1
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.

Also, when it stucks on that part, i've did this: netstat -tulpn | grep LISTEN
results:

(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:2022            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 172.31.12.164:10010     0.0.0.0:*               LISTEN      -
tcp6       0      0 ::1:6379                :::*                    LISTEN      -
tcp6       0      0 :::8081                 :::*                    LISTEN      -
tcp6       0      0 :::8082                 :::*                    LISTEN      -
tcp6       0      0 :::8083                 :::*                    LISTEN      -
tcp6       0      0 :::8084                 :::*                    LISTEN      -
tcp6       0      0 :::26900                :::*                    LISTEN      -
tcp6       0      0 :::26901                :::*                    LISTEN      -
tcp6       0      0 :::26902                :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 :::26903                :::*                    LISTEN      -

Also, i've tried to telnet by myself when that part stucked with telnet 127.0.0.1 8081

Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.

The default configuration (on readme) tells that uses the port 26900, 26901, 26902, 8080, 8081 and 8082.
But the default nodejs port (required to run pterodactyl) is 8080. 

Then, i've changes on serverconfig the port of telnet and do not used the port 8080 (trying with all default, the server will be stuck on "Starting server container." forever and does not uses memory).

Also, i've modified the default serverconfig.xml just editting the ports.
[serverconfig.zip](https://github.com/parkervcp/eggs/files/2299618/serverconfig.zip)

Also, i've seen a strange thing, the memory use is very low:
![memory_cpu_sage](https://user-images.githubusercontent.com/2184082/44300458-bb617a80-a2dd-11e8-8bc2-c3cf8d9c8f7b.png)

**Steps to Reproduce:**
Import the egg, create allocs, create the server and run the server.

**Comment by jeanklann** [comment]
> It looks like your server isn't starting fast enough for the telnet to catch it. It is probably up and running.

It can be... I'm using the amazon web services EC2 (t2-micro), and it is a low memory (1GB) and performance server. (but it's free)

I am using it to test the pterodactyl and see if I can run some gameservers in aws, probaly I will buy one with more performance, because I can run other games, like Factorio.

**Comment by jeanklann** [comment]
I will try to get one server with more performance and see if the server can get up.

**Comment by jeanklann** [comment]
Even with a better instance i'm getting the same error.

Configs:
Amazon Web Services EC2
Model:  c4.large
vCPU: 2 
Mem (GiB): 3.75 
Storage: 30GB
Dedicated EBS Bandwidth (Mbps): 500

**Comment by ryan1161** [comment]
Any update on this as I get the same error for telnet. Can we somehow bind the ip I found a article on how to do so for linux for 7 days to die. https://www.x4b.net/kb/BindProcessToIPonLinux

Also this is my server build:
CPU: 2 (Cores) 32
Memory: 256GB
Raid Storage : OS - 2 x 250GB Data - 2 x 5TB Backups 2 x 10TB
Bandwidth: 200 Mbps down and 150 Mbps up

![image](https://user-images.githubusercontent.com/2374149/45108858-7d4cbf00-b103-11e8-8bab-b2395458ed59.png)

**Comment by parkervcp** [comment]
The game takes too long to start on some systems. The server is running and should be online. You just don't have the game console output. If you set a port for the webconsole they use you should be able to reach that still.

I will look into make it keep trying until the port is available.

**Comment by ryan1161** [comment]
But how does it keep running it keeps using telnet even if I turn it off and I can't get to the webconsole as the server is turned off after 3 failed starts?

**Comment by jeanklann** [comment]
No. The server does not start. When it gets the error the daemon kills the 7days server process. And then try again.

**Comment by jeanklann** [comment]
I get something that I can run: if the map is already generated it does not take too long to start. Then... I generated the map on my personal PC and uploaded the save to docker. It works, but I get a thousands of NullReferenceException...

**Comment by ryan1161** [comment]
Okay thanks for the tip jeanklann. I will give that a try.

**Comment by ryan1161** [comment]
I finally got it work server works now I got this image and created it locally to be used by the egg and now it creates the games. Also trying to work on the bind address for telnet because I can't see anything on the console but it is up cause I can connect in and saves are in the folder now.

Source image for docker:
https://github.com/KennyBZA/pterodactyl-7dtd

**Comment by parkervcp** [comment]
I pushed a new image for 7dtd @jeanklann @ryan1161 

You will need to rebuild the server to get the latest image.

**Comment by ryan1161** [comment]
I'm going to give this a try today will let you know if it works for me.

**Comment by parkervcp** [comment]
The server is probably crashing due to lack of memory. How much do you have assigned?

**Comment by ryan1161** [comment]
I have 5GB assigned does it need more than that?

**Comment by parkervcp** [comment]
Just made sure it was pushed now.

**Comment by Shirobaka** [comment]
Now it updated for me, thanks, i'll try it

**Comment by Shirobaka** [comment]
Ok, works now, but is there no way to change the telnet port?

**Comment by parkervcp** [comment]
No. The telnet port is internal only essentially as it gives the console with input.

**Comment by Shirobaka** [comment]
Oh ok, then thank you :)

**Comment by jeanklann** [comment]
I tested it today and it works perfectly. Thank you.

**Comment by NothingREM** [comment]
Good evening. I seem to be getting the same issue. I have created a fresh server using this egg and I have 30GB of disk space and 8GB of memory allocated. I have set the allocation for port 8081 and have even opened up that port on my router.

**Comment by QuintenQVD0** [comment]
> Good evening. I seem to be getting the same issue. I have created a fresh server using this egg and I have 30GB of disk space and 8GB of memory allocated. I have set the allocation for port 8081 and have even opened up that port on my router.

Please do not use old issue kike this. Use the discord

**Comment by Fr3shlama** [comment]
bump as im started to see the same issue 2 days ago

could someone please answer here or send the link to discord

**Comment by QuintenQVD0** [comment]
> bump as im started to see the same issue 2 days ago
> 
> could someone please answer here or send the link to discord

top right pterodactyl.io
