### ISSUE TITLE
Programming languages support

### ISSUE THREAD

**Issue by hwalker928** [parkervcp/eggs#692]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc) Python3

Does this expand an already existing service: Y (discord.py)

Link to game: (Ex. minecraft.net/factorio.com/etc) python.org

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page. python.org

Links for install steps/docs:
- Just a basic python 3 egg where you can do anything in python, not just discordpy

**Comment by parkervcp** [comment]
If you look closely it doesn't even default to discord. It's literally a generic python egg.
