### ISSUE TITLE
Avorion server

### ISSUE THREAD

**Issue by XPAction** [parkervcp/eggs#693]
Service: Avorion

Does this expand an already existing service: N "SteamCMD"

Link to game: https://www.avorion.net/ or https://store.steampowered.com/app/445220/Avorion/

Links for server downloads:  SteamCMD

Links for install steps/docs: https://avorion.gamepedia.com/Setting_up_a_server

**Comment by microton79** [comment]
This game looks interesting. I could create an egg for that.

**Comment by iamkubi** [comment]
There's already an egg, I just haven't added it to the main repo yet.

https://github.com/iamkubi/eggs/tree/master/avorion

**Comment by XPAction** [comment]
nice
