### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by hwalker928** [parkervcp/eggs#694]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc) bots

Does this expand an already existing service: Y

Link to game: (Ex. minecraft.net/factorio.com/etc) https://github.com/aurieh/ddg-ng

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page. https://github.com/aurieh/ddg-ng

Links for install steps/docs:

On the GitHub

**Comment by hypersmc** [comment]
I think when the “does this expand on an already existing service” I think he means like any discord bot egg. And this doesn’t seem to I could be wrong.

**Comment by gOOvER** [comment]
Really Old bot and no Commits since 3 Years. I think thats too insecure
