### ISSUE TITLE
OpenTTD server crashes: libiculx.so.60 not found

### ISSUE THREAD

**Issue by Jeroen52** [parkervcp/eggs#696]
Panel Version: 1.0.0-rc.5
Daemon Version: 1.0.0-rc.5
Service: OpenTTD
Modified: no

Expected Behavior: I expected an OpenTTD server to boot up, albeit a few revisions behind the current one.

Actual Behavior:
```
container@pterodactyl~ Server marked as starting...
:/home/container$ ./openttd -D
./openttd: error while loading shared libraries: libiculx.so.60: cannot open shared object file: No such file or directory
container@pterodactyl~ Server marked as offline...
```

Steps to Reproduce:
1. Update the egg to the latest json.
2. Make a new server, use the egg.
3. Start the server.

**Comment by parkervcp** [comment]
This was resolved but updating the base_ubuntu image
