### ISSUE TITLE
ARK Egg won't start

### ISSUE THREAD

**Issue by Pewidot** [parkervcp/eggs#697]
Panel Version: (0.7.18)
Daemon Version: (0.6.13)
Service: (ARK)
Modified: (no)
All Ports are correctly forwarded

**Expected Behavior**: Install Ark Server using steam cmd

**Actual Behavior:** The Serve is just installing Steam cmd then setting the Server status to starting. 

Following error appears in the Server Console after it automatically switched the status to starting:
[Pastebin-Link](https://pastebin.com/77EU4ppG)

Wing log: [Pastebin-Link](https://pastebin.com/wdZwu5ke)

**Steps to Reproduce:** Install the Ark Server Egg with any properties(tried everything)

**Extra info:** 
I had no problem using the most of the other eggs like minecraft or terraria, these work great!
Gave the ARK Server 16GB Ram and 120gb diskspace so this shouldn't be the Problems.
In the 
In the server folder are just 4 other folders .steam/Engine/Steam/steamcmd

Hope anyone could help me

**Comment by parkervcp** [comment]
If this is the last server you installed please get the install log.

`tail -n 100 $(ls -Alrt /srv/daemon/config/servers/*/install.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptdl.co 99`

It looks like your install failed though.

**Comment by Pewidot** [comment]
I just created a new ARK Server with the same Problem here is my install log.

[Pastebin Link](https://pastebin.com/Z7ps89bv)

**Comment by parkervcp** [comment]
Even though it says your install is complete I still think it failed somehow.

**Comment by Pewidot** [comment]
Do you have any Idea how this is possible? It happens with some of your steam cmd based eggs.

**Comment by parkervcp** [comment]
That is a steam issue. You may be getting throttled by them or your hard drive if actually full.

**Comment by Pewidot** [comment]
Found the issue seems like my steam lan cache server blocked some of the inbound packages from steam. Thanks for your help!
