### ISSUE TITLE
State stuck on [Pterodactyl Daemon] Server marked as STARTING

### ISSUE THREAD

**Issue by Paquito86** [parkervcp/eggs#699]
Panel Version: 0.7.18
Daemon Version: 0.6.13
Service: discord.js egg
Modified: No

Expected Behavior:
When the BOT finish the startup and it's working pterodactyl should do this: "[Pterodactyl Daemon] Server marked as ON"
Actual Behavior:
When the BOT finish starting it's stuck on: "[Pterodactyl Daemon] Server marked as STARTING" state. PD: The BOT works perfectly
Steps to Reproduce: Create a server with the discord.js egg, upload a BOT and start the BOT. The state will keep on "[Pterodactyl Daemon] Server marked as STARTING".

**Comment by parkervcp** [comment]
Per the readme for discord.js

**The startup configs and commands may need changing to actually function properly.**
