### ISSUE TITLE
RageMP Error on startup

### ISSUE THREAD

**Issue by IlPicasso** [parkervcp/eggs#70]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: (version number) 0.7.9 
Daemon Version: (version number) 0.6.5
Service: (minecraft/factorio/etc) RageMP
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)
No
Expected Behavior:
The server to Start
Actual Behavior:
![image](https://user-images.githubusercontent.com/5110242/44428493-1e5f4580-a55a-11e8-84b0-f5595a2a506a.png)

Steps to Reproduce: (Step by step what to do to cause the issue)

Install the Server, start the server

**Comment by parkervcp** [comment]
@IlPicasso It looks like you have a true/false that is erroring out in the json.
