### ISSUE TITLE
Ticket discord.js bot

### ISSUE THREAD

**Issue by hwalker928** [parkervcp/eggs#702]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc) Discord bots

Does this expand an already existing service: N

Link to game: (Ex. minecraft.net/factorio.com/etc) https://www.mc-market.org/resources/15337/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page. https://www.mc-market.org/resources/15337/download?version=47445

Links for install steps/docs:

Just run the index.js after its been extracted.

**Comment by parkervcp** [comment]
The generic discordjs bot can run this, I will not add it to the repo.
