### ISSUE TITLE
Duplicate Eggs for Killing Floor

### ISSUE THREAD

**Issue by SoftwareN00b** [parkervcp/eggs#703]
Hi,

There are two duplicate Killing Floor 2 eggs with only difference being default port, author email and one letter i. The egg killing-floor2.json with the typo should be removed.

https://github.com/parkervcp/eggs/tree/master/steamcmd_servers/killingfloor2
https://github.com/parkervcp/eggs/tree/master/steamcmd_servers/killing_floor_2 < Typo of one letter

**Comment by TekExplorer** [comment]
What line is this typo on?

**Comment by SoftwareN00b** [comment]
@TekExplorer 

Line , the beginning of the description should be IN but is N.

**Comment by TekExplorer** [comment]
I have verified that the only differences between them are the port, that typo, and the author/date.
question is, do we keep the one made by parker but fix the typo, or keep the one made by `trey@chazx.cc`?
note, Parker's one (with the typo) appears to be older.

**Comment by SoftwareN00b** [comment]
Issue resolved
