### ISSUE TITLE
Game Request: Minecraft Fabric

### ISSUE THREAD

**Issue by MatWise** [parkervcp/eggs#706]
Service: Minecraft Fabric

Does this expand an already existing service: Y

Link to game: [https://fabricmc.net/](https://fabricmc.net/)

Links for server downloads: 
https://fabricmc.net/use/?page=server
https://www.curseforge.com/minecraft/mc-mods/fabric-api (optional but needed for most mods)

Links for install steps/docs: 
https://fabricmc.net/use/?page=server
https://fabricmc.net/wiki/doku.php

**Comment by tmunsch** [comment]
https://github.com/parkervcp/eggs/pull/783
