### ISSUE TITLE
Sinusbot: Rewriting config.ini on every restart

### ISSUE THREAD

**Issue by kubo6472** [parkervcp/eggs#708]
Panel Version: 1.0.0-rc.6
Daemon Version: 1.0.0-rc.6
Service: SinusBot
Modified: no 

Expected Behavior: It keeps the config I set.

Actual Behavior: After pulling the image, it inserts some values into the config file (only when non-empty), making sinusbot use default values from elsewhere.
![image](https://user-images.githubusercontent.com/26146502/94297809-6638ce00-ff65-11ea-8756-d47c336b0e23.png)

Steps to Reproduce:
Changed ListenHost in config.ini to reflect the actual host.

**Comment by gOOvER** [comment]
It's a Bug in RC1.0 Deamon

**Comment by gOOvER** [comment]
https://github.com/pterodactyl/panel/issues/2393

**Comment by kubo6472** [comment]
Thanks, will follow that issue then.
