### ISSUE TITLE
Game Request: GeyserMC

### ISSUE THREAD

**Issue by x390** [parkervcp/eggs#716]
Service: GeyserMC

Does this expand an already existing service: Y (Minecraft)

Link to game: https://geysermc.org/

Links for server downloads: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/

Links for install steps/docs: https://github.com/GeyserMC/Geyser/wiki/Setup

**Comment by parkervcp** [comment]
I would go and say this is a minecraft-proxy but I'll allow it. /s

I have been meaning to work on this.

**Comment by x390** [comment]
This is a replacement for DragonProxy since it has been abandoned.

**Comment by gOOvER** [comment]
> This is a replacement for DragonProxy since it has been abandoned.

I will try to rewrite the Egg from Dragon Proxy. But no ETA

**Comment by smallstech** [comment]
A egg file for it already exists at https://github.com/GeyserMC/pterodactyl-stuff

**Comment by gOOvER** [comment]
> A egg file for it already exists at https://github.com/GeyserMC/pterodactyl-stuff

so why dont u use this?

**Comment by x390** [comment]
Didn't even look just assume they didn't bother with making an egg my bad thanks anyway.
