### ISSUE TITLE
Install Failure with Discord Bastion Bot Egg

### ISSUE THREAD

**Issue by jellyton69** [parkervcp/eggs#717]
Panel Version: 1.0.0-rc.7
Daemon 1.0.0-rc.7
Service: Bastion Discord Bot
Modified: Yes

Expected Behavior: Usage of the egg would result in a successfully installed server.

Actual Behavior: After about a minute into the installation process the server installation fails

Steps to Reproduce:
1. Create a new server and input the details
2. Paste in your bot token into the console variables and create the server
3. Wait ~30 seconds
4. The admin panel for the server will print this error: `This server is in a failed install state and cannot be recovered. Please delete and re-create the server.`

**Comment by parkervcp** [comment]
This iss working for me.

If you are on panel 1.0 this may be a bug there. Please get logs of the install if you want me to look at it.

Re-open this if you get the install logs.
