### ISSUE TITLE
XBackBone egg

### ISSUE THREAD

**Issue by MrTalon63** [parkervcp/eggs#722]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: XBackBone

Does this expand an already existing service: No

Link to game: 

Docker repo: https://github.com/Pe46dro/XBackBone-docker
Main repo: https://github.com/SergiX44/XBackBone/tree/3.2.0

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.

Links for install steps/docs:
https://github.com/Pe46dro/XBackBone-docker

**Comment by parkervcp** [comment]
Running this behind nginx using their container would be better than using the panel to host it.
