### ISSUE TITLE
[Game Request] Among Us Custom Servers (Impostor)

### ISSUE THREAD

**Issue by yashendra2797** [parkervcp/eggs#723]
Service: Among Us

Does this expand an already existing service: Y (I guess?)

Link to game: https://store.steampowered.com/app/945360/Among_Us/

Links for server downloads: https://github.com/AeonLucid/Impostor/releases/download/v1.1.0/Impostor-Server-linux-x64.zip
Links for install steps/docs: https://github.com/AeonLucid/Impostor/wiki/Running-the-server

Honestly this looks extremely easy. I spent about 2 hours trying to make the egg, but I have 0 docker experience so I was running into an issue at the end. I would be grateful if someone can help me out.

**Comment by gOOvER** [comment]
Pls Test #724
