### ISSUE TITLE
Discord.JS - Marked as "Starting"

### ISSUE THREAD

**Issue by MathisDlb** [parkervcp/eggs#728]
Panel Version: (version number) 1.0.0-rc.7 (last announced on Discord)
Daemon Version: (version number) 1.0.0-rc.7 beta announced
Service: (minecraft/factorio/etc) Discord.JS
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) no

Expected Behavior: Server marked as "Start"

Actual Behavior: Server marked to "Starting" but bot is launched and is ready

Steps to Reproduce: (Step by step what to do to cause the issue)
1 - Upload a index.js with a basic bot
2 - Launch it
3 - Server is on Starting
So you can't restart, you must kill the server to restart

**Comment by gOOvER** [comment]
logs?

**Comment by MathisDlb** [comment]
![image](https://user-images.githubusercontent.com/66321732/95679494-860dfa00-0bd3-11eb-9f33-5f51c0ce9aee.png)

**Comment by bioflugel** [comment]
did you configure your start configuration ?
try change it to this (idk how v1.0 eggs works but this work for me in 0.7)
`{
    "done": ""
}`

**Comment by MathisDlb** [comment]
What I write in "" ?

**Comment by MathisDlb** [comment]
And where ?

**Comment by bioflugel** [comment]
> And where ?

in the egg configurations it will like https://prnt.sc/ux4x5s this and "" is empty

**Comment by MathisDlb** [comment]
Hmm okay ! Thanks ;)

**Comment by parkervcp** [comment]
This also means that when a server fails to start it will go online and not show as failed.
