### ISSUE TITLE
GR: MC FTB Revelation 2.4.0 (latest)

### ISSUE THREAD

**Issue by TheGammelgalopper** [parkervcp/eggs#73]
Link to game: https://www.feed-the-beast.com/projects/ftb-revelation

I already used your egg for FTB revelation 1.6.0. However that is quite a few versions behind and I would like to get access to the newest version (2.4.0).

Could you update your egg or tell me how to update to the latest version?

**Comment by TheGammelgalopper** [comment]
Ok I figured out that I could do a reinstall (I entered the new modpack version before doing so).

However: I had to change something in the script for it to work: "ftbrevelations-" to "FTBRevelationServer_"

**Comment by parkervcp** [comment]
Fixed with https://github.com/parkervcp/eggs/commit/f97d88c3eb960e2089791ffe9e6d6f7583dd707d
