### ISSUE TITLE
Curseforge generic egg doesnt install properly

### ISSUE THREAD

**Issue by patrykf03** [parkervcp/eggs#732]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 1.0.0-rc.7
Daemon Version: 1.0.0-rc.7
Service: minecraft
Modified: no

Expected Behavior:
installing a server with this modpack and version 1.5.0-hotfix [levitated](https://www.curseforge.com/minecraft/modpacks/levitated/files)
Actual Behavior:

> Executing curl -L "https://edge.forgecdn.net/files/3074/657/Levitated-Beta-1.5.0-HOTFIX.zip" -o server.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: "https

Steps to Reproduce: (Step by step what to do to cause the issue)
create an server with curseforge generic egg
input project id 399451
input version 1.5.0-HOTFIX

**Comment by SoftwareN00b** [comment]
Can you post the full error logs, you've only posted a partial error log where it has an issue with resolving the hostname. Also, have you tried using the latest full release 1.0.x of Pterodactyl?

**Comment by parkervcp** [comment]
This is not an egg issue but the dns failing to resolve something properly.
