### ISSUE TITLE
Server continues to install. (Discord.JS and Discord.Py)

### ISSUE THREAD

**Issue by DynamixYT** [parkervcp/eggs#738]
For some reason on the discord.js generic and discord.py generic eggs, when i make servers using those eggs, the servers stay installing.

**Comment by ciber96** [comment]
Hey Dynamix, does the container installing have any logs?

**Comment by parkervcp** [comment]
Can you at least fill out the template when submitting these?

**Comment by parkervcp** [comment]
I am going to close this out. 

If you fill out the issue template and re-open this I will look at it.
