### ISSUE TITLE
Add libmysqlclient.so.16 to ubuntu_source for multi theft auto egg

### ISSUE THREAD

**Issue by ciber96** [parkervcp/eggs#739]
Panel Version: 0.7
Daemon Version: 0.6
Service: Multi Theft Auto
Modified: No

Expected Behavior: libmysqlclient.so.16 should be available in /usr/lib so that a popular multi theft auto gamemode(MTA-Paradise) that uses an old mysql library to load properly or maybe add flag in installation. More info here: https://forum.mtasa.com/topic/66856-libmysqlclientso16-cannot-open-shared-object-file/

Actual Behavior: Library not available so gamemode fails to start

Steps to Reproduce: Install fresh mta server, load configs for mta-paradise and mysql module, start the server and you will get an error like this: 
`MODULE: Unable to load x64/modules/mta_mysql.so (libmysqlclient.so.16: cannot open shared object file: No such file or directory)`

**Comment by parkervcp** [comment]
@ciber96 can I ask for assistance with the set up so I can test this without having to ask you if it works?

I just need to get a server configured where it uses a db right?

**Comment by SadMap** [comment]
mtads works i think this isiuse needs to be closed

**Comment by Talhazzers** [comment]
Same problem. Can we fix it?

**Comment by parkervcp** [comment]
I am not particularly interested in updating or making an old ubuntu based image for one specific game.

**Comment by alanescarcha** [comment]
I see in some forums that there are many MTA servers that use the MTA-MySQL module [DEPRECATED] so I have created an image with libmysqlclient.so (64 bits) so that whoever sees this can solve this error by simply **changing the Docker image in the Egg and in the Startup of the server**: `ghcr.io/alanescarcha/mta_sa_ubuntu:latest`
