### ISSUE TITLE
CryoFall Egg Request

### ISSUE THREAD

**Issue by BaxAndrei** [parkervcp/eggs#741]
Service: CryoFall

Does this expand an already existing service: I don`t think so

Link to game: https://cryofall.com/

Links for server downloads: https://wiki.atomictorch.com/CryoFall/Server/Setup (see Server installation / direct download (Windows, Linux, Mac) step 2.)

Links for install steps/docs: https://wiki.atomictorch.com/CryoFall/Server/Setup

Thank you!

**Comment by gOOvER** [comment]
duplicate #685

**Comment by gOOvER** [comment]
PR #686

**Comment by BaxAndrei** [comment]
Thank you!
