### ISSUE TITLE
Old libraries missing for socket.so & others game_samp

### ISSUE THREAD

**Issue by Dr3Ame3r** [parkervcp/eggs#746]
Panel Version:  1.0.1
Daemon Version: 1.0.1
Service: game_samp
Modified: no

Expected Behavior: 

Libraries to be added to /usr/lib/i386-linux-gnu/

        libpthread.so.0 
        libcrypto.so.0.9.8
        libssl.so.0.9.8
        libstdc++.so.6 -- Min version _25
        libm.so.6
        libgcc_s.so.1
        libc.so.6 
        libdl.so.2
        libgssapi_krb5.so.2 
        libkrb5.so.3 
        libcom_err.so.2 
        libk5crypto.so.3 
        libresolv.so.2 
        libcrypto.so.6 -- alias of libcrypto.so.0.9.8 (could be a symlink)
        libz.so.1
        libkrb5support.so.0 
        libkeyutils.so.1

Actual Behavior:

Have those libraries added
[samplibs.tar.gz](https://github.com/parkervcp/eggs/files/5396149/samplibs.tar.gz)

Steps to Reproduce: 
[socket.zip](https://github.com/parkervcp/eggs/files/5396153/socket.zip)

Use LDD on socket.so and try to add missing libraries (statically cause they are old and can't be linked anymore)

**Comment by parkervcp** [comment]
I am going to drop support for samp seeing asd their last release was in 2015 and I have no interest in helping it limp along
