### ISSUE TITLE
Conan Exiles 

### ISSUE THREAD

**Issue by tadavispmd040507** [parkervcp/eggs#747]
Panel Version: 1.0
Daemon Version: N/A Wings
Service: Conan Exiles
Modified: Only the Ports

Expected Behavior: To actually start the server.

Actual Behavior: Loads the .pak files then just sits still throwing up the following lines

![image](https://user-images.githubusercontent.com/58477652/96477814-eec52a00-1204-11eb-9cee-f6b20f8443fc.png)

Steps to Reproduce: Install Server then Start it.

**Comment by gOOvER** [comment]
I see not really an Error

**Comment by tadavispmd040507** [comment]
so a complete new install that throws these errors and wont go past this point is not the egg?? Is that what im understanding?

**Comment by Fieel** [comment]
Same as this, which has been closed without solution: https://github.com/parkervcp/eggs/issues/725

**Comment by parkervcp** [comment]
I am seeing this - http://www.pasteghost.com/wiyoxelija.md

Which is very different @Fieel

**Comment by tadavispmd040507** [comment]
Your log is basically the same and never stats that it's running which would show as always "Starting"

**Comment by tadavispmd040507** [comment]
Is there any update on, being looked at? Brushed to the side? Also if it is being fixed could we at least the proper amount of ports for the game to get full functionality, Conan takes 4 Ports not 2 you can find that info here... https://www.conanexiles.com/dedicated-servers/

**Comment by parkervcp** [comment]
Dude I have 28 open issues and a day job. it gets looked at when I have a chance.

**Comment by gOOvER** [comment]
> Is there any update on, being looked at? Brushed to the side? Also if it is being fixed could we at least the proper amount of ports for the game to get full functionality, Conan takes 4 Ports not 2 you can find that info here... https://www.conanexiles.com/dedicated-servers/

Then fix it and do a PR ;)

**Comment by Fieel** [comment]
I'd gladly help with PRs if some indications/guidelines on how to contribute to the project existed! For example, even though I know how an egg is structured/works I have no idea how to implement basic features such as how to have an egg based on steamCMD to autoupdate on restarts (which is completely missing from the Conan Exiles egg at the moment.) This is kinda offtopic so maybe let's continue the discussion somewhere else.

**Comment by parkervcp** [comment]
The current Conan server updates on restart. It's built into the wine-5 image that is uses currently

**Comment by Fieel** [comment]
Are you sure? I've been using the same image for 2 months and every time a hotfix was published by the devs I had to reinstall the server.

**Comment by Fieel** [comment]
Thank I'll have a better look at it and maybe ask around. Anyways I'd really love to contribute given how often I have to ask for support. Cheers.

**Comment by parkervcp** [comment]
Are you on the latest version of the egg?

**Comment by Fieel** [comment]
@parkervcp Yes, I'm using the latest version

**Comment by parkervcp** [comment]
@Fieel You want to try that?

**Comment by tadavispmd040507** [comment]
Im closing this issue as i have customers that are waiting and its a lot faster for me to give them access to a VM instead of waiting for a fix, not to mention they will have Auto Server Updates and Auto Mod Updates plus access to ALL the PORTS.

**Comment by parkervcp** [comment]
@tadavispmd040507 I made a pr yesterday for testing. I would have appreciated your testing that.

**Comment by tadavispmd040507** [comment]
I got it to work btw, but without having the proper amount of ports although I assign the proper amount and assign then in the Game.ini and the Engine.ini and them still not working is a problem as 98% of all server owners/admins use RCon for a lot and that's in most steam games nowadays. I'm not opposed to coming back and using this panel as it is pretty nice and a lot better than most of the panel out there even the ones you can purchase but the eggs just seem to be incomplete as Citadel Forged with Fire was the same way with the ports. Also if you wanted to make a variation to the Conan server since they have the Expansion out now then all you would have to do is add this to the Start Line after Conan sandbox.exe "/Game/DLC_EXT/DLC_Siptah/Maps/DLC_Isle_of_Siptah"

**Comment by tadavispmd040507** [comment]
Also an update checker that checks ever "specified time" and that would check for both mod and game updates. I can also tell you that Conan does not install your mods and that is a big pain for server owners, I know you are working on most of this stuff and with that said it's a really good panel it's just not to the point to where I can use it right now.

**Comment by parkervcp** [comment]
I would need to trying in all kinds of things to support timed checks and mod lookups. 

It's not a simple or easy to maintain feature. It's also specific to each game.

**Comment by tadavispmd040507** [comment]
Yeah I understand, but I'm just giving you a heads up to what most if not all server owners/admins are going to expect especially since there are stand alone programs that do this like this open source one for instance... http://www.phoenix125.com/ConanServerUtility.html just trying to give you a little help and somewhat direction, I'm more than willing to help if I can

**Comment by parkervcp** [comment]
That tool is to run the server graphically. 

You want something that easily multi-tasks like a desktop to be crammed into a single shell script. This kind of functionality isn't coming to my eggs at any point in the near or far future unless I got paid for it.

I can almost guarantee that it would require a custom image per game to do all that you want to do.

**Comment by tadavispmd040507** [comment]
Yes I understand that what I linked was graphically and was only linking if for an example. The biggest things would be mod install/update and auto updates not update on restart. I never made it through an update but there was reports of the update on restart if found would actually reinstall the entire server and that would be very bad if true, your talking about owners having to redo their configs and possibly losing their saves. Like I said tho those are from what I've read about this egg and not experienced personally

**Comment by tadavispmd040507** [comment]
I also understand and agree that you should get paid for because it is a lot of work and I don't want you to think that I don't know that

**Comment by Fieel** [comment]
> @Fieel You want to try that?

Just tried the new egg configuration and it's working. Couldn't test auto-updates on restart yet though, I will as soon as there's a new update
