### ISSUE TITLE
Installation problems with Arma 3 / Insurgency / Mordhau

### ISSUE THREAD

**Issue by tavichh** [parkervcp/eggs#748]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: **Wisp (Latest version of Ptero)**
Daemon Version: **Wisp (Latest version of Ptero)**
Service: (minecraft/factorio/etc) **Arma 3/Mordhau/Insurgency**
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) **No**

Expected Behavior:
**Arma 3 server installs.
Mordhau runs,
Insurgency installs correctly.**

Actual Behavior:
**Arma 3 server does not install. There's no errors in console. SteamCMD doesn't execute any commands from what I can tell.**

**Mordhau has various errors complaining about a question mark in the startup parameters and it doesn't appear in a server browser. (My guess is it's not actually starting anything due to the question mark even though the server is "started".**
``[2020.10.20-23.52.55:549][ 0]LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/Game/Mordhau/Maps/Grad/FL_Grad?MaxSlots=48?' is not a standard unreal filename or a long path name. Reason: Name may not contain the following characters: '?'``

**Insurgency is missing packages but the server does start. I notice it's missing weapon and attachment names when the player chooses a loadout. (It says string undefined)**

Steps to Reproduce: (Step by step what to do to cause the issue)
**Download the egg, install the egg, and start a server using the egg.**

**Comment by gOOvER** [comment]
Arma work as it should.

**Comment by tavichh** [comment]
Interesting, did you leave it as anonymous and/or change any settings? What's your OS?

**Comment by gOOvER** [comment]
You can't download ARMA 3 with Anonymous. I don't change anything and i Use Debian 10 Buster / Backports

**Comment by tavichh** [comment]
That works :), thanks. 
Mordhau and Insurgency are still broken however.

**Comment by parkervcp** [comment]
Can you tell me which mordhau egg you are using. I have 2.

**Comment by tavichh** [comment]
> Can you tell me which mordhau egg you are using. I have 2.

Sorry for the late response. The console errors are for the version without wine. However, both do not start.
Also, is the "Server Name / Password" parameter actually functional in your eggs? It's not changing the configuration file in any of mine. Just what it reports to Ptero/Wisp during the startup.
If it's supposed to be functional, then I think I found the problem hehe.

**Comment by parkervcp** [comment]
Honestly at this point @tavichh I think should be three issues not just one for all three.

As far as I have tested Insurgency is working fine with the latest panel release.

**Comment by SoftwareN00b** [comment]
I've tested both Mordhau and Insurgency without any issues, except that Mordhau takes +10 minutes to complete the boot sequence for some reason.

The Server name / Password variables are functioning as they should, they are parsing the config file and replacing the lines. You can open the config file listed in the script to confirm that the values were indeed replaced.

**Comment by tavichh** [comment]
I'm going to make a separate issue then. I thought this would be a localized issue but rust (which is a default egg) has functional parameters that save to the config which makes me thing this isn't a permissions issue with chmod so yeah.  Sorry for the bloat of an issue.
