### ISSUE TITLE
Discord bots

### ISSUE THREAD

**Issue by hwalker928** [parkervcp/eggs#749]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (version number) 1.0
1
Daemon Version: (version number) 1.0.0

But the same issue occurs on 0.7.19

Service: (minecraft/factorio/etc) bots
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) yes, just adding discord.py or discord.js to the install

Expected Behavior: The stop and restart buttons work as expected. 

Actual Behavior: The start and kill buttons work, but the stop and restart just get stuck on stopping server. 

Steps to Reproduce: (Step by step what to do to cause the issue)

Press the button?

**Comment by parkervcp** [comment]
If you are running a bot it needs to respect the `^c` or have a command to shutdown properly.

I can't control this and will close this out.
