### ISSUE TITLE
Can't start my FTB Server

### ISSUE THREAD

**Issue by antoineok** [parkervcp/eggs#752]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version:  0.7.17
Daemon Version:  0.6.13
Service: minecraft/FTB Modpack.ch
Modified: (yes/no) egg not modified

Expected Behavior:
Server starting

Actual Behavior:
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 595M / 30000M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] No server egg configuration could be located; aborting startup.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] A fatal error was encountered while starting this server.

Steps to Reproduce: (Step by step what to do to cause the issue)
create a server (in my case, it was an FTB University server), 
start it, 
crash here

**Comment by parkervcp** [comment]
@antoineok can you please get the install logs for this?

**Comment by antoineok** [comment]
i think, how can i get them?

**Comment by antoineok** [comment]
@parkervcp are the logs in the pterodactyl or in the daemon?

**Comment by antoineok** [comment]
i have found it
here it is
[install.log](https://github.com/parkervcp/eggs/files/5423476/install.log)
@parkervcp

**Comment by parkervcp** [comment]
Did you read the template when you submitted this?

```
If you are seeing any of the following go to Discord and post your error in a support channel.
A fatal error was encountered while starting this server.
No server egg configuration could be located; aborting startup.
```

you need to restart the daemon to load the new egg.
