### ISSUE TITLE
Server marked as "starting" instead of "running" when using BIND 

### ISSUE THREAD

**Issue by Dr3Ame3r** [parkervcp/eggs#754]
Panel Version: **1.0.2**(latest)
Daemon Version: **1.0.1**(latest)
Service: SA-MP(game_samp image)
Modified: (yes/no) **No**, haven't changed anything, just added bind in server.cfg

If you're using SA-MP Egg to run a san andreas server, the panel will mark your server as "starting" IF you use BIND to make it listen to specific IP(your container ip to be precise), but, there is a BUT, if you restart the daemon, it marks it as started

Linux v: **Linux games2 5.5.0-18.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.5-22.1~buster (2020-04-18) x86_64 GNU/Linux**

**Docker** info:
https://paste.gg/p/anonymous/c8d6f13f14e34e368342d4365bf8e26e

**Reproducing the issue:**

`
   1. Deploy a new SA-MP server with the standard egg
   2. Start the server without changing anything(it will be marked as running)
   3. Stop the server
   4. Open **server.cfg**
   5. Add "**bind ip.ip.ip.ip**"   #-- IN SERVER.cfg, it will not work in startup after ./samp03svr "
   6. Restart the server, you will have it marked as "starting" now.
   7. systemctl wings restart ( to mark it as running)
`

   **Expected behavior**
   X: Mark it as running without restarting wings

I am using **HOST** setup! So the ip doesn't change at all

Without **BIND**, serverinfo looks like this
http://prntscr.com/v586zf
instead of
http://prntscr.com/v587hy

**Comment by parkervcp** [comment]
I am not seeing this issue.

My current startup is `./samp03svr bind {{SERVER_IP}}` and it seems to be binding fine.

**Comment by Dr3Ame3r** [comment]
No, bind there doesn't work, you have to place it in server.cfg! Otherwise you won't have game status into SA-MP client

**Comment by Dr3Ame3r** [comment]
Should we re-open this as it hasn't been properly tested?

**Comment by parkervcp** [comment]
I want to call it that this was not clearly described to me.

**Comment by Dr3Ame3r** [comment]
I wrote "open server.cfg", but, let me edit it a bit
#done
