### ISSUE TITLE
 Game Request: Plutonium bo2

### ISSUE THREAD

**Issue by Conjuringil** [parkervcp/eggs#755]
Service: Plutonium bo2 server

Does this expand an already existing service: No

Link to game: https://plutonium.pw/

Links for server downloads: 
https://forum.plutonium.pw/topic/13/plutot6-server-set-up-guide

Links for install steps/docs:
https://forum.plutonium.pw/topic/1319/support-linux-bo2-server?_=1603481516686
https://forum.plutonium.pw/topic/586/headless-plutonium-iw5-linux-server-setup

**Comment by parkervcp** [comment]
This is gonna be a no from me.

There is no open game server for CoD that I know of and I want to avoid any possibility of getting dcma'd into the dirt.

**Comment by Conjuringil** [comment]
Ok, thank you.
