### ISSUE TITLE
FiveM json output error

### ISSUE THREAD

**Issue by Dr3Ame3r** [parkervcp/eggs#757]
Panel Version: 1.0.2
Daemon Version: 1.0.1
Service: stock FiveM egg
Modified:  Yes(only the json part)

Expected Behavior:
(following data is fictive)

```
endpoint_add_tcp "192.168.1.1:30120" 
endpoint_add_udp "192.168.1.1:30120" 
```

Actual Behavior:
```
endpoint_add_tcp "" 
endpoint_add_udp "" 
```
Steps to Reproduce: (Step by step what to do to cause the issue)

1. Go to EGG Json parser, and change

`"endpoint_add_tcp": "endpoint_add_tcp \"0.0.0.0:{{server.build.default.port}}\"",`
to
`"endpoint_add_tcp": "endpoint_add_tcp \"{{server.build.default.ip}}:{{server.build.default.port}}\"",
`

2. Start server

**Comment by Dr3Ame3r** [comment]
The main reason that i want this to work is cause:
1. I use HOST environment network
2. IP Needs to be bound in those endpoints to get FiveM reach your server and add it to "getinfo server".

**Comment by parkervcp** [comment]
So this is less of a bug and more that you really an enhancement.

While I also get that this works be better for you, this overall wouldn't work for 99% of the people who use this egg.

**Comment by Dr3Ame3r** [comment]
So, will this get a fix or? I can't control which ip clients assign to themselves, they can impersonate another users ip and this is a big problem..

**Comment by parkervcp** [comment]
What you are looking for by the way is `{{server.build.env.SERVER_IP}}`

On that note, if you are hosting the game for people and charging them you will get shut down by the fivem team

**Comment by parkervcp** [comment]
This is still not an issue with the egg as a whole but in how you have things configured.

**Comment by Dr3Ame3r** [comment]
> 
> 
> What you are looking for by the way is `{{server.build.env.SERVER_IP}}`
> 
> On that note, if you are hosting the game for people and charging them you will get shut down by the fivem team

I tried this way too, it still outputs as "", it is not an issue with how i configured it, it outputs NULL value, it doesn't matter if its an env variable made by me into the egg config, or if its a container value, if i put DOUBLE {{}} {{}} it outputs null i mean ""
But ok, i will look into it, to solve an issue that's related to the json parser

**Comment by parkervcp** [comment]
It's not a json parser. the json is the config for the parser. it's using the file parser.

**Comment by Dr3Ame3r** [comment]
So, is there any way to escape double curly braces? Cause apparently it doesn't work using 2 variables on the same row(it could be a problem in all eggs which are using double braces, as of minecraft ones)

**Comment by parkervcp** [comment]
This is probably a panel bug and not the egg itself.

**Comment by Dr3Ame3r** [comment]
Shall i open an panel bug for this issue?

**Comment by parkervcp** [comment]
I already did.
