### ISSUE TITLE
Custom eggs do not save configurations but default eggs do.

### ISSUE THREAD

**Issue by tavichh** [parkervcp/eggs#759]
Panel Version: (version number) **Latest (Wisp)**
Daemon Version: (version number) **Latest (Wisp)**
Service: (minecraft/factorio/etc)  **Mordhau, Insurgency & Arma tested**
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) **No**

Expected Behavior: **When you are manually creating a egg you specify things the daemon needs such as ram and hard drive space.  You also have access to parameters like Server Name depending on the egg, obviously.  When you enter a parameter, it should save to the configuration file specified in the egg and the next time you start up the server it should still remain.**

Actual Behavior: **When I enter a parameter for the egg (such as the "ServerName" parameter) it does not save to the file. I can look at the configuration file and see that it does not save. When I manually edit the file and go to start up the server, in the case of Mordhau, it will override the file with the default settings again. However, default eggs function just fine (Rust).**

Steps to Reproduce: (Step by step what to do to cause the issue)

**1. Reinstalled Ubuntu 20.04 after my last issue so it's again, a brand new installation.
2. Installed Apache / MySql / Php
3. Added the Wisp.gg to the node.
4. Configured location and allocation settings.
5. Imported the egg
6. Restarted the node.
7. Created a server, specifying 0 Ram & 0MB for the Ram and Hard Drive.
8. Renamed the server to something easy to remember.
9. Waited for the install to finish and the server to start.
10. See the server starts the default name.
11. Go into configuration file.
12. See configuration file is using default name.**

**Having UFW on/off does not make a difference. There is no external firewall enabled. Everything is default chmod permissions. Ran the installer as root. Re-installed Ubuntu, Installed wisp, imported egg, server's DOA.**

**Comment by parkervcp** [comment]
I have not had any issues with the daemon updating any config files.

**Comment by parkervcp** [comment]
I am going to close this out as it seems like you are the only one with this issue
