### ISSUE TITLE
curl: command not found with Minecraft Vanilla Egg

### ISSUE THREAD

**Issue by Rhydium** [parkervcp/eggs#760]
Panel Version: 1.0.2
Daemon Version: Wings@1.0.1
Service: Minecraft
Modified: No

Expected Behavior:
It should install all server files, like the server.jar.

Actual Behavior:
It doesn't because the command curl is not found.
Full log: https://pastebin.com/EF0EVKzP

Steps to Reproduce:
1. Create a server with the Minecraft Vanilla egg
2. See the error

**Comment by parkervcp** [comment]
This is already known and the pr to fix it is already in the panel repo
