### ISSUE TITLE
Alt:v Server.cgf gets broken on start

### ISSUE THREAD

**Issue by killer-kirito** [parkervcp/eggs#761]
Hey there, 
Ive pulled the newest version of the Alt:v egg, when I set the alt:V Config is is correct, 
When i start the server it breaks the server.cfg.

THe cfg how i save it when server is off: 
```
name: "test",
port: 7788,
host: "0.0.0.0",
players: 32,
gamemode: "Freeroam",
#token: ,
#password:,
announce: false,
language: "en",
modules: [
  "node-module",
 ],
resources: [],
```
The cfg when i start the server: 
```
name: "testport:host: 0.0.0.0 "0.0.0.0",
,
players: 32,
gamemode: "Freeroam",
#token: ,
#password:,
announce: false,
language: "en",
modules: [
  "node-module",
 ],
resources: [],
```

**Comment by parkervcp** [comment]
Have you edited the egg in any way? I am having no issues with the config editing.

**Comment by killer-kirito** [comment]
no i just installed it in pterodactyl, im running 1.0

**Comment by parkervcp** [comment]
Can you at least put formatting around those with the ``` in markdown?

**Comment by killer-kirito** [comment]
I even reinstalled the egg now to see if it was a problem with the version, but still the Server.cfg gets scrambled when i start the server.
When U empty the Server config section of the egg it does not destroy the server.cfg.

**Comment by parkervcp** [comment]
Can you tell me what values you set the variables to?

**Comment by parkervcp** [comment]
Also you didn't fill out the issue template when you created this.
