### ISSUE TITLE
ARK Server - RCON, Game Port and Max Player count issues

### ISSUE THREAD

**Issue by IdefixRC** [parkervcp/eggs#766]
3 Issues:

1) RCON messages even with RCON disabled
Expected Behavior: RCON disabled in settings, Server to start up with RCON disabled and no RCON connection messages to appear

Actual Behavior: Server starts, RCON connection refused messages are displayed constantly (assume issue with the start script)
waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused

2) Game port throws an error during startup
Expected Behavior: Gameport binding was previously done through variables. Now it takes the primary allocation port by default it seems. 

Actual Behavior: Server throws an error message during star-up if one of the other 2 ports (e.g. 7778 or 27015) is selected as primary allocation port instead: /home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/gameserver.cpp (715) : Assertion Failed: usGamePort != usQueryPort
Manually overwriting the start-up parameter to ?Port=7777 instead of ?Port={{SERVER_PORT}} fixes the problem and makes the server available. Note should be added to the install script that the primary port needs to be the game port and not the query or raw UDP port. Other option would be to add the game port into the config as variable again.

3) Max player variable missing
Expected Behavior: ability to set max player count in configuration

Actual Behavior:  Field for max player count in configuration and relevant field in start command else server starts with 72 players as default

**Comment by parkervcp** [comment]
1. rcon is the only way to have an actual console with ark as they decided to not have a working cli interface. I am using it to actually stop the server properly as the old way of just using ctrl+C was not saving before stopping and players would time out after several minutes. See https://github.com/parkervcp/eggs/issues/445

2. This is how is should have been done in the first place. It is the standard for all other eggs and should be expected. Using the built in variable for the primary allocation.
    I will not be changing this or making any notes about it.

3. I do not support max player variables unless required for startup, when other circumstances require it, or when I missed calling it out when someone PR'd an egg.
Ex: FiveM technically supports more than 32 players buy people need a special license so adding a limit make sense.
Ex: Don't Starve Together needs to have the same player count for both servers and it's set via flag on startup.
