### ISSUE TITLE
PixARK issue

### ISSUE THREAD

**Issue by LegBRe4ker** [parkervcp/eggs#769]
Panel Version: 1.0.3
Daemon Version: 1.0.1
Service: PixARK
Modified: no

Hi i got the following issue at start the server:

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Already exists 
Already exists 
Already exists 
Already exists 
Already exists 
Already exists 
Digest: sha256:8815c322b3e0210966c24b8761197f4bf6c70974644c1cee109be6a6ed506e9f 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:wine-source 
[Pterodactyl Daemon]: Finished pulling Docker container image
/entrypoint.sh: line 5: ip: command not found
/entrypoint.sh: line 9: ./steam/steamcmd.sh: No such file or directory
:/home/container$ wine64 ./ShooterGame/Binaries/Win64/PixARKServer.exe CubeWorld_Light?listen?MaxPlayers=10?Port=27115?QueryPort=27116?RCONPort=27117?ServerPassword=#######?ServerAdminPassword=#######?CULTUREFORCOOKING=en -NoBattlEye -CubePort=27118 -cubeworld=world -nosteamclient -NoHangDetection -game -server -log
wine: cannot find './ShooterGame/Binaries/Win64/PixARKServer.exe'
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...

**Comment by parkervcp** [comment]
@LegBRe4ker Please get the install logs

If you are on 1.0
`tail -n 100 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptdl.co 99`
If you are on or upgraded from 0.7
`tail -n 100 $(ls -Alrt /srv/daemon/config/servers/*/install.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc bin.ptdl.co 99`

**Comment by LegBRe4ker** [comment]
Send 👍

**Comment by parkervcp** [comment]
It looks like They updated a week ago - https://steamdb.info/app/824360/graphs/

That may have broken it. I am not seeing any game files being installed.
