### ISSUE TITLE
Waterfall egg not working

### ISSUE THREAD

**Issue by ZeProf2Code** [parkervcp/eggs#77]
### Hello! The Waterfall egg doesn't work! [(Click here)](https://github.com/parkervcp/eggs/blob/master/minecraft_proxy/waterfall/egg-waterfall.json) 

The error when launching the server is : 
`[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 0M / 5000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
:/home/container$ java -Xms128M -Xmx1024M -jar waterfall.jar
Error: Invalid or corrupt jarfile waterfall.jar
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 1
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.`

**Comment by ZeProf2Code** [comment]
When I download it with the direct link [(Click here)](https://destroystokyo.com/ci/job/Waterfall/lastStableBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterfall.jar) it's work

**Comment by parkervcp** [comment]
Fixed by https://github.com/parkervcp/eggs/commit/8bffd4d5badc3c63a011e01b6a1f3d148c272397

**Comment by ZeProf2Code** [comment]
Thanks so much!
