### ISSUE TITLE
AutoMuteUs

### ISSUE THREAD

**Issue by shadowtor** [parkervcp/eggs#772]
Service: AutoMuteUs

Does this expand an already existing service: Y (Discord bots)

Link to game: https://github.com/denverquane/automuteus

Links for server downloads: https://github.com/denverquane/automuteus/releases

Links for install steps/docs: https://github.com/denverquane/automuteus#docker

**Comment by Software-Noob** [comment]
Can't you use Discord Go egg to launch this?

**Comment by shadowtor** [comment]
@Software-Noob Honestly not sure, will give it a shot now and let you know

**Comment by shadowtor** [comment]
![image](https://user-images.githubusercontent.com/4159051/97795524-5d6da300-1c5b-11eb-806d-e12b22d1c902.png)
Take it i'm missing something, cant get it working myself..

**Comment by shadowtor** [comment]
Created a working (half-assed) egg below
https://gist.github.com/shadowtor/b474c652254efc42ca82ffbfa9fcfd44

**Comment by parkervcp** [comment]
The generic go egg will run this just fine. Please use that.

The executable for this would be `amongusdiscord` not `automuteus_linux`
