### ISSUE TITLE
TeamSpeak 3 Egg fails to install the service.

### ISSUE THREAD

**Issue by JackW6809** [parkervcp/eggs#774]
Panel Version: 1.0.3
Daemon Version: 1.0.2
Service: voice servers/TeamSpeak 3
Modified: No.

Expected Behavior: Install the service.

Actual Behavior: Fails on installation. 

Steps to Reproduce: Just make a TS3 server on a fresh install and it will error out with installing the packages it requires. E.g.
/mnt/install/install.sh: line 9: wget: command not found

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype

**Comment by parkervcp** [comment]
The teamspeak and mumble eggs have been updated and will update on the next panel update 

https://github.com/pterodactyl/panel/tree/develop/database/seeds/eggs/voice-servers
