### ISSUE TITLE
Request: Terraria Mobile

### ISSUE THREAD

**Issue by niekmos** [parkervcp/eggs#775]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Terraria Mobile

Does this expand an already existing service: Y

Link to game: https://terraria.org/

Links for server downloads: https://terraria.org/server/MobileTerrariaServer.zip
Links for install steps/docs: https://terraria.gamepedia.com/Guide:Setting_up_a_Terraria_server#Linux_.2F_macOS

**Comment by Software-Noob** [comment]
You could use the existing Terraria egg and replace the download URL in the script. I've just done a test and everything seems to work, except that Linux build crashes if -config startup parameter is used unlike the Windows build, even without using pterodactyl.

**Comment by acl1704** [comment]
Should be simple in theory, it's similar to the vanilla egg. Just requires unzipping twice.

**Comment by Software-Noob** [comment]
> Should be simple in theory, it's similar to the vanilla egg. Just requires unzipping twice.

In theory, it's very simple, however, the Linux builds for mobile are new and the -config startup parameter does not work. This would require configuring everything manually by typing commands in the console on each startup.

At least this was the case 26 days ago when I made an egg for it.

**Comment by camden-git** [comment]
I will make this egg and submit a pr shorty.

**Comment by BenasPaulikas** [comment]
+1

**Comment by QuintenQVD0** [comment]
I have a  running egg but the console It looks prity simelar to the server version. IS tere a command I can verify with that I have the mobile server?

**Comment by PsychoZander** [comment]
> I have a running egg but the console It looks prity simelar to the server version. IS tere a command I can verify with that I have the mobile server?

I think that since the cross platform versions have been merged into a single version that a mobile server is no longer needed that that the current egg should be sufficient.
