### ISSUE TITLE
Amoung-Us server V1.2.2 .NET 5.0 Needed

### ISSUE THREAD

**Issue by drmanyx** [parkervcp/eggs#778]
hey 
I have a Small problem with last version of among us - 
A docker Image "quay.io/parkervcp/pterodactyl-images:debian_dotnet"
not have a good version of .NET. for V1.2.2 amoung us server, need 5.0.

Error Message : 

[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:59f4ac7277eb5b1866ca1c963ce93a1ddc05d770f69404b02a96add105eb0923 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_dotnet 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./Impostor.Server
The required library /usr/share/dotnet/host/fxr/3.1.8/libhostfxr.so does not support single-file apps.
  _ To run this application, you need to install a newer version of .NET Core.

  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=debian.10-x64&apphost_version=5.0.0-rc.1.20451.14
container@pterodactyl~ Server marked as offline...

Panel Version : 1.0.3
Node Version : 1.0.1

Regard

**Comment by Lycol50** [comment]
I think they are working on it, you just need to update the image which has dotnet 5, I just need to wait for the quay.io release of the new debian_dotnet which has dotnet 5.

**Comment by Software-Noob** [comment]
You can modify the image and use it for dotnet5,  there is a PR waiting for it as well which you can copy: https://github.com/parkervcp/images/pull/57

**Comment by gOOvER** [comment]
v 1.2.2 is still Beta

**Comment by Software-Noob** [comment]
The dotnet 5 image has been added and you can now use it debian_dotnet-5

**Comment by gOOvER** [comment]
I will test it later and change image if needed
