### ISSUE TITLE
TeamSpeak 3 unable to start

### ISSUE THREAD

**Issue by Flo2410** [parkervcp/eggs#779]
Panel Version: 1.0.3
Daemon Version: 1.0.1
Service: TeamSpeak 3
Modified: no

Expected Behavior:
The server should start normaly.

Actual Behavior:
Crashes on start up with following lines:

[Pterodactyl Daemon]: Finished pulling Docker container image
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:479d479f4002b351ac14a561ad7db7f4f072ab07259cae5f71d9cb45cfea9b33 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:base_debian 
:/home/container$ ./ts3server default_voice_port=${SERVER_PORT} query_port=${SERVER_PORT} filetransfer_ip=0.0.0.0 filetransfer_port=${FILE_TRANSFER} license_accepted=1
/entrypoint.sh: line 12: ./ts3server: No such file or directory
container@pterodactyl~ Server marked as offline...

Steps to Reproduce:
I installed the egg with all default options and no cpu, ram or storage limits.
The Docker Container ist pulled from: quay.io/parkervcp/pterodactyl-images:base_debian

**Comment by parkervcp** [comment]
#774 was opened and closed already explaining this.
