### ISSUE TITLE
Minecraft Paper Auto Updater

### ISSUE THREAD

**Issue by NhProGamer** [parkervcp/eggs#784]
---------------

Service: Minecraft Paper Auto Updater

Does this expand an already existing service: Yes

Link to game: [](https://github.com/Owen-Cochell/PaperMC-Update)

Links for install steps/docs: https://github.com/Owen-Cochell/PaperMC-Update

**Comment by parkervcp** [comment]
I will not be implementing an auto-updater into minecraft eggs.
