### ISSUE TITLE
SpringBoot Application Game Container

### ISSUE THREAD

**Issue by teozfrank** [parkervcp/eggs#792]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc)
SpringBoot application

Does this expand an already existing service: Y/N
Not sure, maybe there is, is there a existing plain java container template?

Link to game: (Ex. minecraft.net/factorio.com/etc)

https://spring.io/projects/spring-boot

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.

You would have to build a simple jar file which essentially has a built in embedded tomcat server.

Links for install steps/docs:

You just run the jar file with certain parameters.

**Comment by gOOvER** [comment]
I think Ptero is the wrong Panel for this

**Comment by teozfrank** [comment]
> 
> 
> I think Ptero is the wrong Panel for this

May I ask why? Its a java application just like a minecraft server with a different set of files / ports.

**Comment by gOOvER** [comment]
It's a Framework for Java Development and not really a thing for Ptero. If you need it, you should create an own egg

**Comment by teozfrank** [comment]
I know what it is, the end result which is a executable jar file should be
able to be ran in Ptero, there is no difference between running a mc jar
and a springboot jar file. There would be a seperate set if files and ports
but other than that they should be really close. Are there any base eggs I
could start with?

**Comment by Software-Noob** [comment]
You could use the existing minecraft egg/java image to run any java application

**Comment by gOOvER** [comment]
> I know what it is, the end result which is a executable jar file should be able to be ran in Ptero, there is no difference between running a mc jar and a springboot jar file. There would be a seperate set if files and ports but other than that they should be really close. Are there any base eggs I could start with?

As i said; if you really need and use such a Framework, you will be able to create your own egg for this. This is nothign   for a GAME Panel ;)

**Comment by teozfrank** [comment]
> 
> 
> You can use the existing Minecraft egg/java image to run any java application

Yeh, I need openjdk 13 tho.

**Comment by teozfrank** [comment]
> 
> 
> > I know what it is, the end result which is a executable jar file should be able to be ran in Ptero, there is no difference between running a mc jar and a springboot jar file. There would be a seperate set if files and ports but other than that they should be really close. Are there any base eggs I could start with?
> 
> As i said; if you really need and use such a Framework, you will be able to create your own egg for this. This is nothign for a GAME Panel ;)

Is there a template I can work off of to create one?

**Comment by gOOvER** [comment]
see comment from @Software-Noob 

https://github.com/parkervcp/eggs/issues/792#issuecomment-727230311
