### ISSUE TITLE
FiveM

### ISSUE THREAD

**Issue by aogmike** [parkervcp/eggs#795]
Panel Version: latest
Daemon Version: latest
Service: fiveM
Modified: no

Expected Behavior:
The Server should normally start with txAdmin.

Actual Behavior:
After enabling txAdmin in the Service Variables and starting the server, the server gets stuck and only starts txAdmin without actually starting the fiveM server.
https://prnt.sc/vjxxwb

Steps to Reproduce: (Step by step what to do to cause the issue)
Simply installing fiveM and setting the txAdmin variable to 1, then starting the server.
https://prnt.sc/vjxxwb

**Comment by parkervcp** [comment]
TX-Admin is essentially it's own control panel.

You need to go into the TX-Admin panel to start the server or it will stay in starting until you do.
