### ISSUE TITLE
FredBoat discord music bot

### ISSUE THREAD

**Issue by alan67160** [parkervcp/eggs#799]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc)
Discord

Does this expand an already existing service: Y/N
yes

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://fredboat.com

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
https://fredboat.com/docs/selfhosting

Links for install steps/docs:
https://fredboat.com/docs/selfhosting

**Comment by alan67160** [comment]
In additional I want to request a python 3.7 d

**Comment by Software-Noob** [comment]
The self-hosted version is archived and no longer maintained, unlike the public version.
