### ISSUE TITLE
SCP

### ISSUE THREAD

**Issue by E-v-o** [parkervcp/eggs#8]
Hi there

I'm having huge issues trying to create my own egg, there is a Steam game called SCP:SL that I'm trying to get up and running. I've checked the install.log, I've tried keeping it relatively similar to the default eggs and have tested on a fresh install that it works (it does).

The Steam game is http://store.steampowered.com/app/700330

I was wondering if you could look over my script and see if I perhaps messed anything up, if you could have a look to see if you're able to get it running I would heavily appreciate it!

I'll put my script in code tags below, it's using the ubuntu 16.04 container and LocalAdmin is the executable (requires mono).
```
cd /tmp
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | tee /etc/apt/sources.list.d/mono-official.list
apt -y update
apt -y install mono-runtime
apt -y install mono-devel
mozroots --import --sync
apt -y install lib32gcc1

apt -y --no-install-recommends install curl lib32gcc1 ca-certificates

curl -sSL -o steamcmd.tar.gz http://media.steampowered.com/installer/steamcmd_linux.tar.gz

mkdir -p /mnt/server/steamcmd
tar -xzvf steamcmd.tar.gz -C /mnt/server/steamcmd
cd /mnt/server/steamcmd

# SteamCMD fails otherwise for some reason, even running as root.
# This is changed at the end of the install process anyways.
chown -R root:root /mnt

export HOME=/home/container/SCP
./steamcmd.sh +login xxxxx xxxxx +force_install_dir /mnt/server +app_update 700330 -beta linux +quit

mkdir -p /mnt/server/.steam/sdk32
cp -v linux32/steamclient.so ../.steam/sdk32/steamclient.so
```

**Comment by parkervcp** [comment]
We have official mono images. You could use those to install an run this most likely. I haven't had a chance to look this over as of yet.

**Comment by E-v-o** [comment]
@parkervcp Thanks! It got me one step closer, unfortunately still not quite there. I'm getting an error that seems to be related to the size of the terminal and cursor, I've tried -gui=true but it had no effect.

Any suggestions on how to handle this one?
```
Unhandled Exception:
System.ArgumentOutOfRangeException: Value must be positive and below the buffer width.
Parameter name: left
at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00021] in <fb0d2884a2b44d8db375bbed7cc70740>:0
at System.TermInfoDriver.set_CursorTop (System.Int32 value) [0x00015] in <fb0d2884a2b44d8db375bbed7cc70740>:0
at System.ConsoleDriver.set_CursorTop (System.Int32 value) [0x00000] in <fb0d2884a2b44d8db375bbed7cc70740>:0
at System.Console.set_CursorTop (System.Int32 value) [0x00000] in <fb0d2884a2b44d8db375bbed7cc70740>:0
at LocalAdmin.Program.Write (System.String content, System.ConsoleColor color, System.Int32 height) [0x0000e] in <b2e0d1a2187849deafb8e58b4c9928f9>:0
at LocalAdmin.Program.ShowPresetByAlias (System.String alias) [0x00029] in <b2e0d1a2187849deafb8e58b4c9928f9>:0
at LocalAdmin.Program.Main () [0x00007] in <b2e0d1a2187849deafb8e58b4c9928f9>:0
```

**Comment by parkervcp** [comment]
You don't want gui true. There is no way for it to spawn a gui. I have never looked at SCP so I have no idea what all you will need.

**Comment by E-v-o** [comment]
I cannot figure it out unfortunately, I've spent a fair few hours but have given up. If you ever get the time to check it out, I'd heavily appreciate it. It's a free to play game (not even a 1GB). If not I understand, to keep your GitHub clean just close the issue.

Thanks for taking the time.

**Comment by parkervcp** [comment]
I will see what I can do here. But I make no promises. I will be closing this now.
