### ISSUE TITLE
Geyser Egg Request

### ISSUE THREAD

**Issue by alan67160** [parkervcp/eggs#803]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc) 
Minecraft: Bedrock Edition

Does this expand an already existing service: Y/N
Y

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://www.minecraft.net/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/

Links for install steps/docs:
https://github.com/GeyserMC/Geyser/wiki/Setup

**Comment by alan67160** [comment]
DragonProxy is now abandoned
Geyser is the new one

**Comment by Software-Noob** [comment]
They have their own egg here https://github.com/GeyserMC/pterodactyl-stuff
