### ISSUE TITLE
[REQUEST ]Terraria TModloader

### ISSUE THREAD

**Issue by Davido012** [parkervcp/eggs#81]
Service: terraria
Link to game: https://terraria.org/
Link to game (modding api): https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/

Would be great if you could look into it. A more streamlined install instruction for linux servers is below:
https://www.reddit.com/r/Terraria/comments/7dbkfe/how_to_create_a_tmodloadermodded_server_on_linux/

I attampted to create this egg myself but could never get it to start for more than a few seconds. Below is my attempt at an egg. I based it on the tshock egg but modified the install script and had to switch the core cause it refused to start with the mono core.
https://pastebin.com/PDDxRY6Y

**Comment by parkervcp** [comment]
This is resolved as of https://github.com/parkervcp/eggs/commit/ac0d6aff236128382dd491522314e19cee21f55d
