### ISSUE TITLE
Paper downloads v1 API is deprecated

### ISSUE THREAD

**Issue by kruton** [parkervcp/eggs#811]
Panel Version: N/A
Daemon Version: N/A
Service: Minecraft, Paper MC

 According to the Paper Discord, the v1 API is deprecated. The current Paper egg still uses that API.

> @everyone Excuse the interruption, but we have some news:
>
> Version 2 of the PaperMC downloads API is now live - documentation can be read at https://papermc.io/api/docs/ (you can also try the API out here, too!)
>
> warning WARNING warning
> -   Version 1 of the downloads API is now deprecated
> -  Public access to Jenkins will soon be removed - please move to using our API as soon as possible to avoid any disruptions.
> 
> If you encounter any issues, please report them to us.

**Comment by Software-Noob** [comment]
There's an open draft PR #810  for it, the PR will be either fixed or a different PR will be made

**Comment by Software-Noob** [comment]
The new PR has been pushed to the repo and you can now update your egg by downloading it again
