### ISSUE TITLE
arma3_x64 egg not starting due to missing package

### ISSUE THREAD

**Issue by MrDj200** [parkervcp/eggs#812]
Panel Version: 1.1.1
Daemon Version: 1.1.1
Service: Arma3_x64
Modified: yes (changed variables to a valid steam user, because the default values throw this: `ERROR! Failed to install app '233780' (No subscription)` )

Expected Behavior: Egg to be started and server to be connectable

Actual Behavior: Installation will fail after entering steam guard code

Steps to Reproduce: 
1. Install new arma3_x64 server
2. While it's installing, It'll ask for Steam guard code. Enter it.
3. After some time, it shows this: `Steam Guard code:Warning: failed to init SDL thread priority manager: SDL not found`

According to [THIS](https://github.com/ValveSoftware/steam-for-linux/issues/7036) issue, the package `libsdl2-2.0-0:i386` is missing.

**Comment by Software-Noob** [comment]
` failed to init SDL thread priority manager: SDL not found` is normal and can be ignored since it's running inside a container.

**Comment by parkervcp** [comment]
sdl errors are not actual errors and the install will continue on fine.

Your steam guard failed to validate.

Dude to timing  and everything in the install script, it will almost always fail.

**Comment by MrDj200** [comment]
But why did it fail to Validate? 
Do I not just insert the code into the input line of the console and hit enter?

**Comment by Software-Noob** [comment]
The code expires very fast and the time between when it was entered and when the install script gets to the point of using it is usually too long

**Comment by MrDj200** [comment]
I waited for the prompt in the console and then instantly checked my emails and put the code in the console.
Took max 30 seconds. Does it expire faster than even that?

**Comment by Software-Noob** [comment]
I have not used the email-based one, but the mobile app Steam guard code changes every 30 seconds, when you enter the code it takes some time until the script actually gets to the step of logging into your account.

It's doable, but you have to literally type it in right away on generation from the mobile app.

**Comment by MrDj200** [comment]
I did it about 4 times now within 10 seconds. So maybe the mail-based just doesnt work for this
