### ISSUE TITLE
among us suggestions

### ISSUE THREAD

**Issue by jaylac2000** [parkervcp/eggs#813]
Add a way to whitelist peoples public ip address to a server

Add more options, maybe ability to add/make plugins/mods for the server

what is the invite code to my server? lol. add a spot to put that

Service: 

Among Us

Does this expand an already existing service: Y/N

Y

**Comment by parkervcp** [comment]
You need to use the imposter client config tool to be able to join a server. This is not something I can fix nor will I go through and try to add it to the server.

**Comment by jaylac2000** [comment]
where do i find this "config tool"

**Comment by parkervcp** [comment]
In their github repo
