### ISSUE TITLE
Request: OpenVPN server

### ISSUE THREAD

**Issue by WouterGritter** [parkervcp/eggs#817]
Service: VPN / OpenVPN server

Does this expand an already existing service: N

Link to game: https://openvpn.net/

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
- https://openvpn.net/download-open-vpn/

Links for install steps/docs:
- https://openvpn.net/download-open-vpn/
- https://hub.docker.com/r/linuxserver/openvpn-as

**Comment by DomiiBunn** [comment]
I don't think that is likley to happen but maybe parker is crazy enough and smart enough to do it. (IE don't get your hopes up)

**Comment by danny6167** [comment]
Seems unlikely to work considering how locked down the containers are. I doubt they can access what they need to.

**Comment by parkervcp** [comment]
Not feasible in any fashion. Having in-kernel perf would blow this away/
