### ISSUE TITLE
(Game Request) Holdfast: Nations at War

### ISSUE THREAD

**Issue by James76931** [parkervcp/eggs#819]
Service: Holdfast: Nations at War

Does this expand an already existing service: N

Link to game: https://holdfastgame.com/

Links for server downloads: No link. SteamCMD app ID is 1424230.

Links for install steps/docs: https://wiki.holdfastgame.com/Server_Hosting
There is a pre-made Docker container listed on the wiki page which may be handy.

**Comment by parkervcp** [comment]
@James76931 You can try this one and let me know - https://github.com/parkervcp/eggs/pull/96/files

**Comment by ankit2951** [comment]
@James76931 You can use this if you like. Worked on it with the Holdfast Devs and falo. https://github.com/ankit2951/pterodactyl-holdfast

**Comment by parkervcp** [comment]
I am perfectly willing to work with devs. @ankit2951 If you ever want to PR to the repo please do.

**Comment by ankit2951** [comment]
https://github.com/parkervcp/eggs/pull/826. Hopefully I did this correctly, little new to GitHub.

**Comment by James76931** [comment]
> @James76931 You can use this if you like. Worked on it with the Holdfast Devs and falo. https://github.com/ankit2951/pterodactyl-holdfast

I skipped ahead and used your egg instead of #96 since you worked directly with the Holdfast developers and have an active PR. It works like a charm - thank you!

**Comment by ankit2951** [comment]
No problem!
