### ISSUE TITLE
OpenRA server name not updating 

### ISSUE THREAD

**Issue by OpenOP2Admin** [parkervcp/eggs#820]
Panel Version: 1.1.1
Daemon Version: 1.1.1
Service: OpenRA
Modified: no

Expected Behavior: Server name changes the startup variable {server_name}

Actual Behavior: The name of the server inside pterodactyl and the game name advertised on the public listing is different. In order to change the servers public listing name, user has to go to Startup within the server page and change the server_name variable. 

Steps to Reproduce: Create an OpenRA server. Set the server name to something. Start the server. Check the public listing. Change the server's server_name (not in start up command), restart the server. The name will remain the same unless you change it from the startup tab.

**Comment by danny6167** [comment]
That's working as intended. The name given to the server in the panel doesn't set any of the servers configuration. You must set the server_name variable in the start up tab.
