### ISSUE TITLE
GoMint Support [Bedrock Edition] [Java 11]

### ISSUE THREAD

**Issue by RealTriassic** [parkervcp/eggs#827]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Minecraft

Does this expand an already existing service: Y

Link to game: https://gomint.io

Links for server downloads: https://github.com/gomint/gomint/releases

Links for install steps/docs: There are no docs for installing it at the moment, sadly, but running it is quite easy, on desktop it's just running one start.sh file [or start.cmd] and GoMint is running, running it requires the "Modules" folder to be downloaded, the contents of start.sh would be the Startup Command.

**Comment by parkervcp** [comment]
So looking at their repo and how they pack their files is annoying.

**Comment by RealTriassic** [comment]
> So looking at their repo and how they pack their files is annoying.

Sorry

**Comment by omniboy** [comment]
> Sorry

Don't be sorry for it! You're not a maintainer, you don't have to take any responsibility.

> So looking at their repo and how they pack their files is annoying.

Would you like to propose another packing/distribution strategy?

**Comment by parkervcp** [comment]
Just a single zip with the modules folder in it.

**Comment by omniboy** [comment]
I don't know if you haven't noticed it but GoMint releases do feature that. If you head over to the [releases section of GoMint](https://github.com/gomint/gomint/releases) and choose let's say [1.0.0RC5](https://github.com/gomint/gomint/releases/1.0.0RC5), you can see that there's a single `GoMint.Server.zip` file available in the assets list. Download, extract it and you'll discover three entries. `start.sh`, `start.cmd` and `modules`.

**Comment by parkervcp** [comment]
There is a `server.zip` in the release they have there. That is what i am saying here.

If if was just a single zip containing the modules and scripts I wouldn't have said anything

**Comment by omniboy** [comment]
What's the issue with `unzip`-ping the zipball, moving the _modules_ directory out there and discarding the remainder?

**Comment by parkervcp** [comment]
So every other egg I have right now so far as I know doesn't need me to unzip 2 times to get the files. I was just calling it out as annoying.

**Comment by omniboy** [comment]
I hear your concern. There must have been some misunderstandings on my site. I wasn't aware that the released zipball contained another zipball due to a broken pipeline. I understand your pain and took care of it. The release assets section now features two different flavors:
- The GoMint server including start scripts (`gomint-server.zip`)
- The GoMint server, but modules only (`gomint-server-modules.zip`)

**Comment by parkervcp** [comment]
That actually helps out greatly.
