### ISSUE TITLE
TS3 Manager

### ISSUE THREAD

**Issue by kubo6472** [parkervcp/eggs#833]
Service: ts3-manager

Does this expand an already existing service: N

Link to game: https://www.ts3.app/

Links for server downloads: https://www.ts3.app/download/

Links for install steps/docs: https://github.com/joni1802/ts3-manager#what-is-ts3-manager-

**Comment by gOOvER** [comment]
Test pls #836

**Comment by kubo6472** [comment]
Alles funktioniert, danke. Dieser Fehler würde auto-geschloßen mit dem merge.

**Comment by gOOvER** [comment]
> Alles funktioniert, danke. Dieser Fehler würde auto-geschloßen mit dem merge.

[german]
alles klar, danke für die Rückmeldung, aber bitte hier englisch

[english]
Thank you for your Feedback. But pls only english here
