### ISSUE TITLE
ARK: Survival Evolved Linux Server Tools

### ISSUE THREAD

**Issue by alan67160** [parkervcp/eggs#842]
Service: `(Ex. minecraft/factorio/etc)`
ARK: Survival Evolved

Does this expand an already existing service: `Y/N`
Y

Link to game: `(Ex. minecraft.net/factorio.com/etc)`
https://store.steampowered.com/app/346110/

Links for server downloads: `This needs to be an official link and not one that is hosted on some forum page or a personal github page.`
https://git.io/arkmanager

Links for install steps/docs:
https://github.com/arkmanager/ark-server-tools

refer:
https://github.com/arkmanager/ark-server-tools/issues/977

**Comment by parkervcp** [comment]
This doesn't really do much different from the current install process or startup process.

I don't see how this will help anything.

**Comment by alan67160** [comment]
It does! That tool can help easy to install mods on ARK server. I request this tool is because I am having trouble to install mods on my server yesterday😭

**Comment by alan67160** [comment]
I have Googled 5 hour and still don't know how to install mods, I have tried automodsmanager but when I enable that the server crash on startup
