### ISSUE TITLE
SCP SL Egg Request

### ISSUE THREAD

**Issue by Jonnyfencing1** [parkervcp/eggs#85]
Please fill out the information bellow and remove from the line up
---------------
Service: SCP Secret Laboratory

Link to game: https://store.steampowered.com/app/700330/SCP_Secret_Laboratory/

**Comment by parkervcp** [comment]
The console for this server is unusable in it's current state.

See - 
![image](https://user-images.githubusercontent.com/1207679/47953866-64bd2180-df59-11e8-9d64-dae519ae564a.png)

**Comment by Jonnyfencing1** [comment]
It's aight parker I got this error even trying to make a server without Ptero

**Comment by parkervcp** [comment]
I got it no matter what I do unless I run it manually. They know about the issue and it's being worked on.

**Comment by Jonnyfencing1** [comment]
I got that even if I ran it manually, I just ended by giving up

**Comment by parkervcp** [comment]
Running manually I get - 
![image](https://user-images.githubusercontent.com/1207679/47954140-1e69c180-df5d-11e8-8fd1-908d650f0b0e.png)


This is a working server and can be connected to. Honestly the one I have as an egg is also connectable. It's just that the terminal is unusable as far as I can tell. I do think commands work but I have no idea.

**Comment by parkervcp** [comment]
@Jonnyfencing1 Can you look at #175 and see if it works please.

**Comment by parkervcp** [comment]
I have scp eggs now.

**Comment by arockstar28** [comment]
https://pastebin.com/NXaMyyDg 

Having this issue on the PTB version of SCP, worried that it might translate when the version becomes an official update (most servers are using it right now)

**Comment by parkervcp** [comment]
If oyu are having issues you should open a new egg and not comment on an closed issue.
