### ISSUE TITLE
Cuberites | Unpack, Config and Server Status

### ISSUE THREAD

**Issue by ikbenignace** [parkervcp/eggs#850]
Panel Version: 1.1.3
Wings Version: 1.1.3
Service: Minecraft
Modified: Yes

Expected Behavior: Unpacks all files + correct config + Server status on Running

Actual Behavior:
Doesn't unpack correctly + config on start is broken (it gives dublicates etc) + Server status keep standing on Starting
Image of config: https://cdn.discordapp.com/attachments/404105683336953866/785806477378060318/unknown.png
The wrong unpacks are caused because of --strip-components=1 in the install script.

Steps to Reproduce: (Step by step what to do to cause the issue)
1. Import egg
2. Create Server
3. Start Server

**Comment by ikbenignace** [comment]
Don't close this issue, it is only partially fixed.

**Comment by snaildos** [comment]
+1 It's not fixed.

**Comment by dodoflix** [comment]
+1 Still not fixed

**Comment by gOOvER** [comment]
wow, 2 votes in 2 years; so no need to fix it asap :)

**Comment by dodoflix** [comment]
It's issue page not help desk, no need to be rude. It's just a reminder of it's not fixed.
