### ISSUE TITLE
Feather startup permission denied

### ISSUE THREAD

**Issue by acl1704** [parkervcp/eggs#855]
Panel Version: 1.1.3
Daemon Version: 1.1.3
Service: minecraft/feather
Modified: yes, updated startup script to fix the download extension.
https://github.com/acl1704/eggs/commit/1c3ea991f2d70f0dffa63b7e85588ea472e5caf3

Expected Behavior:
feather-server runs

Actual Behavior:
```
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./feather-server
/entrypoint.sh: line 12: ./feather-server: Permission denied
container@pterodactyl~ Server marked as offline...
```

Steps to Reproduce: (Step by step what to do to cause the issue)
1. Load the egg
2. Start the server

**Comment by parkervcp** [comment]
So i updated my install script to use the github api. The latest feather-server errors on the feather.toml as it generates a broken one.

**Comment by parkervcp** [comment]
So I see what the issue is and am working on it.
