### ISSUE TITLE
[Request] CrewLink (for Among Us)

### ISSUE THREAD

**Issue by James76931** [parkervcp/eggs#859]
Service: CrewLink (Among Us)

Does this expand an already existing service: Y

Link to game: https://github.com/ottomated/CrewLink

Links for server downloads: https://github.com/ottomated/CrewLink-server

Links for install steps/docs: https://github.com/ottomated/CrewLink-server/blob/master/README.md

**Comment by parkervcp** [comment]
@James76931 Can you test that?

**Comment by James76931** [comment]
It works perfectly. Thanks for making this @aske02!

**Comment by KungRaseri** [comment]
Can confirm that the egg installs and the server works nicely.  I am able to connect via http (still setting up https).
