### ISSUE TITLE
Velocity Egg uses nonexistent image

### ISSUE THREAD

**Issue by gerome1812** [parkervcp/eggs#867]
Panel Version: 1.1.1 (not panel dependant)
Daemon Version: 1.1.1 (not wings dependant)
Service: minecraft/velocity
Modified: no
Expected Behavior:

The egg is able to finish the installation process.

Actual Behavior:

Fails with this error as `pterodactyl-images:adoptopenjdk-15-hotspot` does not exist.
```
ERROR: [Dec 15 22:20:40.147] failed to create server environment during install process error=Error response from daemon: manifest for quay.io/parkervcp/pterodactyl-images:adoptopenjdk-15-hotspot not found
```

Steps to Reproduce: (Step by step what to do to cause the issue)

1. Import the egg into Pterodactyl panel.
2. Create a server with the egg.
3. Click save.
4. Check wings logs. On the panel it will just look like the installation is taking a long time.

This can be worked around just by changing the docker image used. I chose `debian_openjdk-15-hotspot`.

**Comment by Software-Noob** [comment]
The image should be debian_openjdk-15-hotspot
