### ISSUE TITLE
Web Egg Request?

### ISSUE THREAD

**Issue by AncientEntity** [parkervcp/eggs#87]
Service: Nginx/Apache

Ok let me explain I don't know exactly how pterodactyl works but I think from the looks of it integrating a way of putting a web server on it and linking it to a subdomain and/or ip would be possible.

**Comment by Bl4ckSpr4y** [comment]
well each webserver world need to run on a different port @AncientEntity

**Comment by AncientEntity** [comment]
@Bl4ckSpr4y 

Thats what I was thinking.. But wouldn't hooking them into a subdomain work?
NFOServers hooks people into NAME.site.nfoservers.com for example.

**Comment by parkervcp** [comment]
I am saying no to this.

**Comment by anondev-sudo** [comment]
But why?

**Comment by gOOvER** [comment]
> But why?

No need for it :)

**Comment by anondev-sudo** [comment]
Um so how to host websites

**Comment by gOOvER** [comment]
> Um so how to host websites

HestiaCP, Plesk, CPanel. But not Ptero :D

**Comment by anondev-sudo** [comment]
Which one is best, free, opensource like pterodactyl and can be hosted on same vps where pterodactyl is hosted? I can't afford getting second vps just to host a few websites.
