### ISSUE TITLE
Add InfoProxy

### ISSUE THREAD

**Issue by gerome1812** [parkervcp/eggs#872]
Service: minecraft/InfoProxy

Does this expand an already existing service: Y

Link to game: [https://github.com/Gabscap/InfoProxy](https://github.com/Gabscap/InfoProxy)
Links for server downloads: Must be built from source.

Links for install steps/docs: [https://github.com/Gabscap/InfoProxy/blob/master/README.md](https://github.com/Gabscap/InfoProxy/blob/master/README.md)

**Comment by tmunsch** [comment]
I have created an egg for this. It requires running on Ubuntu 20 for some of the dependencies. Currently I have it pulling the compiled version from my github and pulling a custom docker image from gitlab. It seems to work fine however. Not sure if it's something @parkervcp wants me to add to the repo or not.

**Comment by parkervcp** [comment]
i see no reason why this needs to be built when the dev could probably have built it.

**Comment by tmunsch** [comment]
Agreed, close please

**Comment by parkervcp** [comment]
Their install docs are insufficient as they don't really tell you how to run the software so much as to run a tool to build it and then nothing.
