### ISSUE TITLE
Discord.PHP Egg

### ISSUE THREAD

**Issue by S4qib** [parkervcp/eggs#877]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Discord.PHP Egg

Does this expand an already existing service: N

Link to game: https://github.com/teamreflex/DiscordPHP

Links for server downloads: https://github.com/teamreflex/DiscordPHP

Links for install steps/docs:
https://github.com/teamreflex/DiscordPHP/blob/master/README.md

**Comment by parkervcp** [comment]
I'm not building a php image to run this. If someone wants to PR the php image and an egg for this we can reconsider then.
