### ISSUE TITLE
GoMint changed its release asset scheme

### ISSUE THREAD

**Issue by fyradir** [parkervcp/eggs#883]
GoMint just introduced a new release asset scheme. The GoMint egg is likely broken and needs to be fixed.

Old scheme:
1. `gomint-server-modules.zip`
2. `gomint-server.zip`
3. `Source Code (zip)`
4. `Source Code (tar.gz)`

New scheme:
1. `<TAG>.json` (e.g. `1.0.0RC5.json`)
2. `<TAG>.zip` (e.g. `1.0.0RC5.zip`)
3. `Source Code (zip)`
4. `Source Code (tar.gz)`

**Comment by parkervcp** [comment]
The gomint egg was already using the modules file. Please try before you open an issue.

**Comment by fyradir** [comment]
After analyzing how the GoMint egg setup script works, I realized that the script does not use explicit asset indexes but lists all assets and picks out any URL that contains "modules". I re-added the zip that only contains the modules. Sorry for the inconveniences.

**Comment by gOOvER** [comment]
Change it and open a PR. It's better to see, what you want to change ;)
