### ISSUE TITLE
Request: Risk of rain 2 dedicated server

### ISSUE THREAD

**Issue by Ignaciox** [parkervcp/eggs#886]
---------------
Service: (Ex. minecraft/factorio/etc)
Risk of rain 2 dedicated server

Does this expand an already existing service: Y/N 
Yes this project allows you to host it anywhere instead of ONLY your local machine.(Official dedi: https://steamdb.info/app/1180760/)  

Link to game: (Ex. minecraft.net/factorio.com/etc) 
https://github.com/avivace/ror2-server

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.
(This is only what i could find it uses docker) https://hub.docker.com/r/avivace/ror2server 

Links for install steps/docs:
https://steamcommunity.com/sharedfiles/filedetails/?id=2077564253 (their github/docker page also has instructions)

**Comment by Software-Noob** [comment]
Can you test the egg linked in this [comment? ](https://github.com/parkervcp/eggs/pull/1102#issuecomment-827199455)

**Comment by Ignaciox** [comment]
![image](https://user-images.githubusercontent.com/45845856/120043579-7f21e380-c00c-11eb-99f1-e83741475b3b.png)
![image](https://user-images.githubusercontent.com/45845856/120043615-9234b380-c00c-11eb-97db-3856e3aaa6a4.png)
Works :D
