### ISSUE TITLE
RedBot issue - "No server egg configuration"

### ISSUE THREAD

**Issue by patrickmcisaac** [parkervcp/eggs#893]
Panel Version: (version number) 0.7
Daemon Version: (version number) 0.6
Service: (minecraft/factorio/etc) Discord bot
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) No

Expected Behavior: Run the multifunctional RedBot Discord bot.

Actual Behavior: Upon startup, I've been receiving a message as follows: "No server egg configuration could be located; aborting startup"

Steps to Reproduce: (Step by step what to do to cause the issue) Simply create a server with the egg and start it.

**Comment by parkervcp** [comment]
You didn't read the issue template when you submitted this.

You need to restart the daemon after importing an egg when running the old panel and daemon.
