### ISSUE TITLE
RedBot

### ISSUE THREAD

**Issue by patrickmcisaac** [parkervcp/eggs#894]
Panel Version: (version number) 1.0
Daemon Version: (version number) 0.6
Service: (minecraft/factorio/etc) Discord Bots
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables) no

Expected Behavior:
What amount do I have to set tmpfs amount to?

Steps to Reproduce: (Step by step what to do to cause the issue)
Start server

**Comment by gOOvER** [comment]
And whats the issue? For me Redbot works as it should

**Comment by patrickmcisaac** [comment]
I followed the egg and restarted wings however, i'm getting this error now: 
![image](https://user-images.githubusercontent.com/65414868/103437135-c2a92a80-4bf1-11eb-89b0-0ec27503b328.png)

**Comment by gOOvER** [comment]
Öhm, there is no Error :D Thats the Normal Screen after successfull start :)

**Comment by SGTGunner** [comment]
Correct. That means it is functioning correctly. :-) You need to see if it times out afterwards or when it is trying to connect via discord to the bot.

**Comment by gOOvER** [comment]
This can be closed. It's not issue
