### ISSUE TITLE
PixARK issue/Error

### ISSUE THREAD

**Issue by DJKenzoDE** [parkervcp/eggs#895]
Main OS: Ubuntu 20.04
Egg: PixARK downloaded today
Problem: dont start the server after installing

Log from server:
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Already exists 
Already exists 
Already exists 
Already exists 
Already exists 
Already exists 
Digest: sha256:8815c322b3e0210966c24b8761197f4bf6c70974644c1cee109be6a6ed506e9f 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:wine-source 

[Pterodactyl Daemon]: Finished pulling Docker container image
/entrypoint.sh: line 5: ip: command not found
/entrypoint.sh: line 9: ./steam/steamcmd.sh: No such file or directory
:/home/container$ wine64 ./ShooterGame/Binaries/Win64/PixARKServer.exe CubeWorld_Light?listen?MaxPlayers=50?Port=25518?QueryPort=25519?RCONPort=25522?ServerPassword=modasch2021?ServerAdminPassword=pix2020?CULTUREFORCOOKING=en -NoBattlEye -CubePort=25523 -cubeworld=world -nosteamclient -NoHangDetection -game -server -log
wine: cannot find './ShooterGame/Binaries/Win64/PixARKServer.exe'
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic reboot: last crash occurred less than 60 seconds ago.

**Comment by Software-Noob** [comment]
Most likely DNS issue since your container does not even have steamcmd installed

**Comment by gOOvER** [comment]
Thats no DNS Issue. Thas an Issue with Image; Read the Error correct  @Software-Noob

**Comment by gOOvER** [comment]
But should be fix with

https://github.com/parkervcp/images/pull/51

**Comment by Software-Noob** [comment]
The egg is using wine_source instead of ubuntu_wine_source

**Comment by gOOvER** [comment]
@DJKenzoDE contact me on Discord -> gOOvER#9999 for testing a new egg
