### ISSUE TITLE
FiveM Problem

### ISSUE THREAD

**Issue by flavio1310** [parkervcp/eggs#899]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7
Daemon Version: 0.6
Service: fivem
Modified: No

I'm on version 0.7 and I've never had this problem until I want to reinstall my panel so I reimport my eggs is there I have this error
saysaysaysay say tsay tesay tessay testsay test
InvokeNative: execution failed: Argument at index 0 was null.
SCRIPT ERROR: Execution of native 00000000ff7f66ab in script host failed: Argument at index 0 was null.
> handler (@rconlog/rconlog_server.lua:51)
> routeMessage (@chat/sv_chat.lua:187)
> ref (@chat/sv_chat.lua:241)

**Comment by flavio1310** [comment]
I specify when I delete the resource, when I execute a command it is duplicated and executed.

**Comment by VibeGAMESNL** [comment]
This is not an egg issue but a script issue. I dont have this issue on 1.2.0.

**Comment by aske02** [comment]
Im guessing you have become a part of this 
 [Scripting error](https://forum.cfx.re/t/rconlog-error-getnumplayeridentifiers-null-rconlog-server-lua-55/40101)

**Comment by flavio1310** [comment]
Good evening, I solved half the problem by removing the rconlog manager except that I have a problem when I execute a command it duplicates. 
![image](https://user-images.githubusercontent.com/42754288/103448630-79fa7b80-4c9c-11eb-98df-4e72e026951c.png)

**Comment by VibeGAMESNL** [comment]
> Good evening, I solved half the problem by removing the rconlog manager except that I have a problem when I execute a command it duplicates.
> ![image](https://user-images.githubusercontent.com/42754288/103448630-79fa7b80-4c9c-11eb-98df-4e72e026951c.png)

This is an issue in Pterodactyl 0.7 but was fixed in 1.0. Time for you to upgrade.

**Comment by flavio1310** [comment]
Up to 1.0
