### ISSUE TITLE
[REQUEST] Minecraft - Forge Sponge EGG

### ISSUE THREAD

**Issue by ZeProf2Code** [parkervcp/eggs#90]
Hello can you add a Sponge Forge* Egg please
Link to sponge : https://www.spongepowered.org/

**Comment by ZeProf2Code** [comment]
The link for the download of the Sponge Forge server is https://www.spongepowered.org//downloads/spongeforge/stable/<INSERT HERE VERSION>

**Comment by parkervcp** [comment]
I am going with a no on this as sponge has made it impossible to actually get their versions from their site in a programmatic way right now.
