### ISSUE TITLE
Update discord.js egg to node 14?

### ISSUE THREAD

**Issue by creepinson** [parkervcp/eggs#902]
Can you update the ptero discord.js egg to nodejs 14+? I would use this for non-discord js apps but I want to use node 14 not node 12.

**Comment by creepinson** [comment]
It looks like you have a node 14 docker image on quay.io but have not updated this repo with it.

**Comment by gOOvER** [comment]
You can do this on your own. Simple change the Image

**Comment by creepinson** [comment]
I've created a new egg that uses yarn and uses yarn run start and nodejs 14. I would still be nice for others to be able to use the more trusted one with nodejs 14 though.

**Comment by aske02** [comment]
Is i see there is already a pull request to add multiple images to discord.js egg. #901

**Comment by parkervcp** [comment]
updated in #911
