### ISSUE TITLE
Fivem eggs problem

### ISSUE THREAD

**Issue by flavio1310** [parkervcp/eggs#909]
Panel Version: last
Wings Version: last
Service: fivem
Modified: No

I'm on version 1.20 and I've never had this problem until I want to reinstall my panel so I reimport my eggs is there I have this error
saysaysaysay say tsay tesay tessay testsay test
InvokeNative: execution failed: Argument at index 0 was null.
SCRIPT ERROR: Execution of native 00000000ff7f66ab in script host failed: Argument at index 0 was null.
> handler (@rconlog/rconlog_server.lua:51)
> routeMessage (@chat/sv_chat.lua:187)
> ref (@chat/sv_chat.lua:241)

**Comment by flavio1310** [comment]
So it doesn't hinder in any way the smooth running of the service?

**Comment by parkervcp** [comment]
It shouldn't

**Comment by flavio1310** [comment]
Okay, do you think you can solve this problem?

**Comment by VibeGAMESNL** [comment]
> Okay, do you think you can solve this problem?

This is not a egg issue.

**Comment by parkervcp** [comment]
Unless it impacts the server running I will not.
