### ISSUE TITLE
MongoDB - Hoax/Scam

### ISSUE THREAD

**Issue by patrickmcisaac** [parkervcp/eggs#917]
Hello there!

The past week, I've been using the MongoDB egg that you've made. Throughout this time, there have been several occasions of DB information being wiped and a message stating the following:

`All your data is a backed up. You must pay 0.02 BTC to 1GrcLZuZXygjSjhJ5mYLFs3RgNm8rbGPGP 48 hours for recover it. After 48 hours expiration we will leaked and exposed all your data. In case of refusal to pay, we will contact the General Data Protection Regulation, GDPR and notify them that you store user data in an open form and is not safe. Under the rules of the law, you face a heavy fine or arrest and your base dump will be dropped from our server! You can buy bitcoin here, does not take much time to buy https://localbitcoins.com with this guide https://localbitcoins.com/guides/how-to-buy-bitcoins After paying write to me in the mail with your DB IP: getdb@grr.la and you will receive a link to download your database dump.`

Here is a screenshot: https://patrickm.dev/uploads/Discord_M0HA6gmgfx.png

How would we go about preventing this?

**Comment by Software-Noob** [comment]
Restrict access to the database, if you make it available to anyone then it will be abused.

**Comment by parkervcp** [comment]
This is not an egg issue. If you leave an unsecured mongodb exposed on the internet it's your own issue.
