### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BaxAndrei** [parkervcp/eggs#919]
Hello. When I install something inside container for example:
![image](https://user-images.githubusercontent.com/12484505/104104693-55ad2900-52b2-11eb-9344-ec00624de228.png)
It will be installed on my server or in container? Because I browsed to user server container and I can`t find anything.

**Comment by parkervcp** [comment]
The install script is run inside a container that is thrown away. anything installed there is thrown away when the install is complete.

**Comment by BaxAndrei** [comment]
And is possible to install something after that with `apt install -y ` ?

**Comment by parkervcp** [comment]
any packages you want for a server need to be in the image used to run the server. You cannot install any packages after.

**Comment by BaxAndrei** [comment]
> any packages you want for a server need to be in the image used to run the server. You cannot install any packages after.

I understand. So after install , all new containers uses image from `docker images` where things from my screenshot were installed before container is thrown away. Thank you.
