### ISSUE TITLE
MinIO - No automatic update

### ISSUE THREAD

**Issue by Akuramu** [parkervcp/eggs#920]
I just noticed that I simply can't update MinIO via Pterodactyl and that Pterodactyl didn't do it (same for putting commands to add users).

How to reproduce : 

- Install a MinIO instance and wait for an update
- Once the update is out, restart your instance.
(A message warning you that an update is available should appear with a command to type which should not be the case).
- Insert the command in your console

Nothing happens.

Panel Version : 1.2.1
Wings version : 1.2.2

**Comment by parkervcp** [comment]
Egg wasn't designed for updating on restart. Reinstall to update.

@tmunsch @Software-Noob FYI.

**Comment by tmunsch** [comment]
I will get this updated later in the week.
