### ISSUE TITLE
Garry's Mod

### ISSUE THREAD

**Issue by flavio1310** [parkervcp/eggs#922]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: last
Daemon Version: last
Service: Grarry's Mod
Modified: no

Hello for a while I have a problem with the eggs fivem here's the error that spam the console
RecordSteamInterfaceCreation (PID 39): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 39): STEAMHTTP_INTERFACE_VERSION003 / HTTP
Apparently there will be an update to fix this but I have a feeling it's done on the egg.

Any ideas?

**Comment by parkervcp** [comment]
none of what you said matches up.
