### ISSUE TITLE
Egg Request - RTMP Dockers

### ISSUE THREAD

**Issue by djdascream** [parkervcp/eggs#923]
I already tried to build an EGG myself with RTMP Docker system, however I didn't succeed, maybe someone who already designed several EGGs can do it?

i Recommend this Docker File 
https://hub.docker.com/r/alfg/nginx-rtmp/

**Comment by parkervcp** [comment]
I'm saying no to this as anyone could run this outside Pterodactyl much easier that running it in the panel.

**Comment by djdascream** [comment]
Yeah it is verry Easy to run it outside Pterodactyl 

Bu it would be Great if that can be Used in Pterodactyl  to install RTMP Servers in 1 Click
