### ISSUE TITLE
Something not working with rust server.

### ISSUE THREAD

**Issue by Kriiiiiiiz** [parkervcp/eggs#924]
Panel Version: 1.2.1
Daemon Version: 1.2.3
Service: Rust
Modified: No

Expected Behavior: Should start the server

Actual Behavior: Console shows "Waiting for RCON to come up..."

https://media.discordapp.net/attachments/404105683336953866/798020827404566558/unknown.png

Steps to Reproduce: Just start the Rust server

Install logs: http://bin.ptdl.co/5b26y

**Comment by parkervcp** [comment]
This install log is from a minecraft server.

Please try to install rust again and get the logs again.

**Comment by Kriiiiiiiz** [comment]
Wow u right, sorry...

This one should be: http://bin.ptdl.co/rd9vp

**Comment by parkervcp** [comment]
If you google the error at the bottom you find this

`Error! App '258550' state is 0x202 after update job.`

https://oxidemod.org/threads/error-app-258550-state-is-0x202-after-update-job-out-of-space.25482/

It's likely you are out of disk space.

**Comment by Kriiiiiiiz** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/13300613/104214221-7783e880-5437-11eb-9e41-113370f7cfe7.png">

It has physical space and still the same issue :(

**Comment by parkervcp** [comment]
depending on your disk setup and usage you might still be out of disk space.

**Comment by Kriiiiiiiz** [comment]
How can i check it ?
