### ISSUE TITLE
Request to reopen #842

### ISSUE THREAD

**Issue by alan67160** [parkervcp/eggs#927]
_Originally posted by @alan67160 in https://github.com/parkervcp/eggs/issues/842_
Reason:
That tool can help you installing mods easier, so I hope someone could take a look again

**Comment by Software-Noob** [comment]
It was closed for a reason, Pterodactyl already does it through normal install. Mod installation is something that you should Google for, it's a simple process and unrelated to pterodactyl.

**Comment by parkervcp** [comment]
1. You can re-open a request on your own.
2. I would have closed it again.
