### ISSUE TITLE
Bedrock vanilla egg server name not working with colour codes

### ISSUE THREAD

**Issue by AshleyHunter01** [parkervcp/eggs#929]
The bedrock vanilla egg does not let you use the correct colour code for bedrock minecraft as it converts the unicide character to the java format.

**Comment by gOOvER** [comment]
Not an issue ;)

**Comment by AshleyHunter01** [comment]
> Not an issue ;)

Well is there a way to fix it? It's kind of annoying.

**Comment by parkervcp** [comment]
I assume this has to do with how variables as strings are handled and it may be interpreted weirdly.

It's still not really an egg issue.

Can you offer an example here @AshleyHunter01

**Comment by AshleyHunter01** [comment]
So bedrock uses the `§` symbol for colour codes and when you try using lets say `§1 (dark blue)` it converts it to `\u00a71` which is the Java format, I've attached images below
![1](https://user-images.githubusercontent.com/38188828/104824141-59f3bc00-5847-11eb-99a6-f7658dcb5b26.png)
![2](https://user-images.githubusercontent.com/38188828/104824145-5d874300-5847-11eb-9e94-9ffe11b098ed.png)

**Comment by parkervcp** [comment]
I suspect that is go not treating strings as it's over a byte in length so it breaks.

**Comment by AshleyHunter01** [comment]
It was working fine till the egg got updated to use variables.

**Comment by parkervcp** [comment]
So the go daemon isn't handling unicode characters properly. That is what I am telling you. This is not an egg issue but a go daemon issue at this point.
