### ISSUE TITLE
TyphoonLimbo is not a Proxy

### ISSUE THREAD

**Issue by MrVapor01** [parkervcp/eggs#931]
Hello, I noticed that TyphoonLimbo is in the wrong folder. Because this is not a proxy

**Comment by Software-Noob** [comment]
Isn't it a fallback lobby to be used with something like bungee, it does nothing on its own?

**Comment by MrVapor01** [comment]
Yes but it is not a bungee but a normal server just that you are only in the void nothing more

**Comment by parkervcp** [comment]
I will keep this in with the proxies as it's about all it's used for

**Comment by MrVapor01** [comment]
It is not a proxy. A proxy does something other than that. Read the readme from the manufacturer of the server

**Comment by gOOvER** [comment]
> It is not a proxy. A proxy does something other than that. Read the readme from the manufacturer of the server

omg, then stop using this Repro, if u don't want to see it in proxy ;9 Easiest way
