### ISSUE TITLE
Rust+ still not fixed?

### ISSUE THREAD

**Issue by JackW6809** [parkervcp/eggs#932]
Not sure how it has been 6 months and this issue still exists and has not been fixed from my original issue? I will again repost what I put in the original issue. It just needs fixing in the default egg that installs with Pterodactyl.

Service: Rust (SteamCMD)
Modified: Yes (Changed startup command to fix the bug)

Expected Behavior:
Rust+ App to make the connection to the rust server.

Actual Behavior:
Makes no connection to the server.

Steps to Reproduce:
Launch the server with the default startup command and it will work fine apart from the fact that their Rust+ app does not work.

To fix it:
Add this ( +app.port {{SERVER_PORT}} ) to the Startup Command. E.g:
./RustDedicated -batchmode +server.port {{SERVER_PORT}} +app.port {{SERVER_PORT}} +server.identity "rust" +rcon.port {{RCON_PORT}} +rcon.web true +server.hostname "{{HOSTNAME}}" +server.level "{{LEVEL}}" +server.description "{{DESCRIPTION}}" +server.url "{{SERVER_URL}}" +server.headerimage "{{SERVER_IMG}}" +server.worldsize "{{WORLD_SIZE}}" +server.seed "{{WORLD_SEED}}" +server.maxplayers {{MAX_PLAYERS}} +rcon.password "{{RCON_PASS}}" +server.saveinterval {{SAVEINTERVAL}} {{ADDITIONAL_ARGS}}

So it reads like this just needs to be upped to the main panel repo.

_Originally posted by @parkervcp in https://github.com/parkervcp/eggs/issues/613#issuecomment-664065567_

**Comment by parkervcp** [comment]
I feel like this isn't needed due to the following
1. You can just add the var if needed
2. not everyone needs it.
