### ISSUE TITLE
Forge install script fails silently due to wrong move command of the jar

### ISSUE THREAD

**Issue by JanDevDE** [parkervcp/eggs#934]
**Panel Version: >1.0.0
Daemon Version: >1.0.0
Service: Minecraft, forge
Modified: no**

**Expected Behavior:** Forge jar should be moved to server.jar

**Actual Behavior:** Move command errors out due to file not found, caused by a custom forge jar

**Steps to Reproduce:** 
- Define 1.16.4-35.0.7 as forge version
- Reinstall the server
- Server jar is not going to be replaced as the move command errors out

**Install log:**
Output: /mnt/server/./libraries/net/minecraftforge/forge/1.16.4-35.0.7/forge-1.16.4-35.0.7**-server**.jar Checksum Validated: cc9c4dace794c5f3ce2d1f4e07585773e254af50

The server file name is forge-1.16.4-35.0.7-server.jar, but the install script uses FORGE_JAR=forge-${MC_VERSION}-${FORGE_VERSION}.jar

**Error is:**
mv: missing destination file operand after 'server.jar'
Try 'mv --help' for more information.
Deleting installer.jar file.

**Comment by parkervcp** [comment]
I will look into this soon.

**Comment by Software-Noob** [comment]
I looked into it and it never touches the forge_jar version if the forge version is not empty. I'll open a PR to fix it shortly.

**Comment by Software-Noob** [comment]
I made a PR for the egg that is shipped with the panel, but the forge egg from this repo works just fine and doesn't have this issue.

**Comment by parkervcp** [comment]
This was resolved.
