### ISSUE TITLE
Arma3 EGG Server not Starting

### ISSUE THREAD

**Issue by djdascream** [parkervcp/eggs#936]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (1.2.0)
Daemon Version: (1.2.2)
Service: (Arma3)
Modified: (no) 

Expected Behavior: The Server Start after the Installation

Actual Behavior: The Server don´t Start after the Installation
Error Message:

[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:1a8225a78a0afe6f7e518fb3111e5b2c74d02a84ed3e94214d8a81811d546773 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:game_arma3 
[Pterodactyl Daemon]: Finished pulling Docker container image
~/server: ./arma3server -ip=0.0.0.0 -port=2302 -cfg=basic.cfg -config=server.cfg -mod= -serverMod=
/entrypoint.sh: line 39: ./arma3server: No such file or directory
PTDL_CONTAINER_ERR: There was an error while attempting to run the start command.

Steps to Reproduce: Install Arma3 Server, start it > See the Issue

**Comment by parkervcp** [comment]
You need to have a user that owns arma to install the server.
