### ISSUE TITLE
Tekkit Lite Egg Reqest

### ISSUE THREAD

**Issue by Wannab007** [parkervcp/eggs#937]
Service: Tekkit Lite

Does this expand an already existing service: Y  ( Minecraft Java )

Link to game: https://www.technicpack.net/modpack/tekkitlite.552675  or direct link to server download http://servers.technicpack.net/Technic/servers/tekkitlite/Tekkit_Lite_Server_0.6.5.zip

Links for server downloads: http://servers.technicpack.net/Technic/servers/tekkitlite/Tekkit_Lite_Server_0.6.5.zip

Links for install steps/docs: NA

**Comment by Wannab007** [comment]
Would this work for the tekkit lite egg?

[egg-tekkit-lite.zip](https://github.com/parkervcp/eggs/files/6022656/egg-tekkit-lite.zip)

**Comment by MatusBoa** [comment]
You can install Tekkit Lite to already existing Minecraft egg pretty easily.

**Comment by parkervcp** [comment]
I am not going to add any more modded minecraft eggs to the repo unless it's a PR.

For future reference when people as for a modded minecraft egg I will reference this issue.
