### ISSUE TITLE
Rust server Crash after 16h online : failed to init SDL thread priority manager: SDL not found

### ISSUE THREAD

**Issue by zardozlogin** [parkervcp/eggs#938]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: WISP v1.0.23.
Daemon Version: (version number)
Service: Rust Server
Modified: Yes :  servername max 80

Actual Behavior:
My Rust server is crashing after being 16h online.
it's a SDL issue, so i presume it's a steam related issue

here is the error:
`eac_server.so [x64] :: OnLoad()
Warning: failed to init SDL thread priority manager: SDL not found
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
/data/src/public/tier1/utlsymbol.h (453) : Fatal Assertion Failed: Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
/data/src/public/tier1/utlsymbol.h (453) : Fatal Assertion Failed: Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
/data/src/public/tier1/utlsymbol.h (453) : Fatal assert failed: /data/src/public/tier1/utlsymbol.h, line 453.  Application exiting.`

Steps to Reproduce: (Step by step what to do to cause the issue)
1- start my RUST server at midnight
2- my RUST server crash at 4 PM
3- everyday the same.

**Comment by gOOvER** [comment]
Its not egg related

**Comment by zardozlogin** [comment]
can 't it be an issue with my egg ?

**Comment by parkervcp** [comment]
SDL has nothing to do with this crash.

**Comment by zardozlogin** [comment]
ok, sorry, my bad. you can close the thread.
i searched all over and can't find why i have this crash everyday
can you please help me to know where i have to look ?

**Comment by parkervcp** [comment]
If your error was formatted and not just one huge line it would be easier to read.

**Comment by zardozlogin** [comment]
This is how it's written in my log:

eac_server.so [x64] :: OnLoad()
Warning: failed to init SDL thread priority manager: SDL not found
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
/data/src/public/tier1/utlsymbol.h (453) : Fatal Assertion Failed: Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
/data/src/public/tier1/utlsymbol.h (453) : Fatal Assertion Failed: Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
/data/src/public/tier1/utlsymbol.h (453) : Fatal assert failed: /data/src/public/tier1/utlsymbol.h, line 453.  Application exiting.
