### ISSUE TITLE
Hallo i need a egg for the Ts3MusicBot

### ISSUE THREAD

**Issue by Fire-Host** [parkervcp/eggs#940]
Hello, since I would like to offer the Ts3MusikBots with consultation from the creator, I wanted to create an Egg.
I've already tried to create an egg, but unfortunately I didn't get very far. I hope you can help me. I would of course pay for a license to try it out.
---------------

Service: Discord/Ts3 Music Bot

Does this expand an already existing service: N

Link to game: https://www.ts3musicbot.net/index.php

Links for server downloads: NONE

Links for install steps/docs: https://www.ts3musicbot.net/index.php?mode=account&tab=how_to_install

It is important that there is a license that is being monitored. If it is known that it is created, I will take over the costs.

**Comment by Software-Noob** [comment]
Everything seems to be locked behind the paywall

**Comment by Fire-Host** [comment]
I've only been using Pterdoctyl for a short time, that's why I can't do it so easily, would it be possible if I send you the installation links?

**Comment by parkervcp** [comment]
If you paid for it assume sharing links for it would be against their ToS from when you bought it.

I won't support that and will nix it.

**Comment by Fire-Host** [comment]
I realize that I cannot pass the real links on, but if I send the installation with other links.

**Comment by Fire-Host** [comment]
The installation is actually quite short and only has 3 commands.
1. wget
2. tar
3. cd (to go into the folder to start the bot)

**Comment by Software-Noob** [comment]
> I've only been using Pterdoctyl for a short time, that's why I can't do it so easily, would it be possible if I send you the installation links?

If you can share what the bot is based on or the dependencies, then it would be a great start, such as does is it based on Java or?

If it's just a simple Discord bot, then I can make it for you, but otherwise, I'm not really interested in spending much time on an egg that will be private due to its nature

**Comment by Fire-Host** [comment]
TS3MusicBot supports java (openjdk-X-jre) 7-11.

**Comment by Software-Noob** [comment]
You can send me a friend request on Discord and I can take a look into it tomorrow

**Comment by Fire-Host** [comment]
I can't send you a request because you blocked it

**Comment by Fire-Host** [comment]
my is Yakub K.#0357

**Comment by gOOvER** [comment]
The problem is here, you cant use autoupdate, iuf a update is released.
