### ISSUE TITLE
Magma Download Fails

### ISSUE THREAD

**Issue by acl1704** [parkervcp/eggs#941]
Panel Version: 1.2.2
Daemon Version: 1.2.3
Service: minecraft/Magma
Modified: Yes, updated as best I could.
https://github.com/acl1704/eggs/blob/magma/minecraft/java/magma/egg-magma.json

Needs a workaround to the commit being part of the filename - I've been advised by the Magma team not to use the download api and to use [Jenkins ](https://ci.hexeption.dev/job/Magma%20Foundation/job/Magma/job/master/)instead.

Current egg doesn't work, neither do the changes I made.

Expected Behavior:
Installs successfully.

Actual Behavior:
Fails to download.

Steps to Reproduce: Run the install of the current egg or the modified one.

**Comment by DatMayo** [comment]
I changed line 23 in my install script to ```text
DOWNLOAD_URL="https://ci.hexeption.dev/job/Magma%20Foundation/job/Magma/job/master/lastSuccessfulBuild/artifact/build/distributions/Magma-${VANILLA_VERSION}-server.jar"
```
I changed "SERVER VERSION" to "537f1d6" and everything worked fine. (Sure, its no permanent fix, but a workaround)
