### ISSUE TITLE
No players can join the server - PocketMine

### ISSUE THREAD

**Issue by Dapro718** [parkervcp/eggs#943]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: (1.0.0)
Daemon Version: (1.2.2)
Service: (minecraft: PocketMine)
Modified: (no) (did you add or change things, this includes startup configs/install scripts/variables)

Expected Behavior: Server should act like your normal pocketmine server hosted on a VPS. Anyone is able to join, play, and have a good time.

Actual Behavior: 
No one is able to join the server. They only way to be able to join is to go to the panel’s web address (do not have to be logged in), after doing this you can join.
- There are no issues with the hosts network
- No Firewall 
- No wings errors
- No pterodactyl errors

Steps to Reproduce: Seems to be a issue with my VPS only, and continues to happen after I reinstall the server. The main reason I am opening this issue is to rule out the possibility of this problem originating from the egg.

**Comment by gOOvER** [comment]
Poketmine Egg works as it should, so not really an Problem with the Egg

**Comment by Dapro718** [comment]
Do you have any ideas on why this issue is happening?

**Comment by parkervcp** [comment]
If you are one ovh you have the game firewall enabled.
