### ISSUE TITLE
Permission Denied - FiveM

### ISSUE THREAD

**Issue by JoshuaMakuletxz** [parkervcp/eggs#944]
Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 1.2.2
Daemon Version: Not sure
Service: FiveM
Modified: No 

Expected Behavior: After Installation i start the FiveM server

Actual Behavior: Error on try to start FiveM server.

:/home/container$ /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path /home/container/alpine/usr/lib/v8/:/home/container/alpine/lib/:/home/container/alpine/usr/lib/ -- /home/container/alpine/opt/cfx-server/FXServer +set citizen_dir /home/container/alpine/opt/cfx-server/citizen/ +set sv_licenseKey [MYLICENSEKEY] +set steam_webApiKey [MY STEAM WEB API KEY] +set sv_maxplayers 32 +exec server.cfg
/entrypoint.sh: eval: line 1: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: Permission denied

Steps to Reproduce: Creating a server for FiveM

Screenshot : https://prnt.sc/xkya1g

**Comment by Totoyxz** [comment]
**i think you should ask it on the main discord server of pterodactyl. :)**
