### ISSUE TITLE
Request : Snekbox

### ISSUE THREAD

**Issue by KittensAreDaBest** [parkervcp/eggs#946]
Service: Bots / Discord

Does this expand an already existing service: N

Link to game: https://github.com/python-discord/snekbox

Links for server downloads: https://github.com/python-discord/snekbox

Links for install steps/docs: https://github.com/python-discord/snekbox/blob/master/Dockerfile / https://github.com/python-discord/snekbox/blob/master/README.md

**Comment by parkervcp** [comment]
While they ship a docker container it's not exactly something I think pterodactyl should be managing.
