### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by totoyzx** [parkervcp/eggs#947]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (Ex. minecraft/factorio/etc) nginx

Does this expand an already existing service: idk

Link to game: (Ex. minecraft.net/factorio.com/etc)
https://gitlab.com/tenten8401/pterodactyl-nginx

Links for server downloads: https://gitlab.com/tenten8401/pterodactyl-nginx

Links for install steps/docs:
https://gitlab.com/tenten8401/pterodactyl-nginx

**Comment by parkervcp** [comment]
I'm not supporting this. There are better free ways to do this.

**Comment by wolfier74** [comment]
Pls tell me exactly what ways
