### ISSUE TITLE
Azura Cast Request

### ISSUE THREAD

**Issue by Phyroks** [parkervcp/eggs#953]
Service: voice_servers/radio

Does this expand an already existing service: N

Link to game: https://www.azuracast.com/

Links for server downloads: https://www.azuracast.com/install/docker.html

Links for install steps/docs: https://www.azuracast.com/install/docker.html

**Comment by parkervcp** [comment]
This requires multiple docker images per their documentation and compose set up. Just because they run in docker doesn't mean it will work.
