### ISSUE TITLE
Arma 3 with Steam Guard

### ISSUE THREAD

**Issue by ApekByz** [parkervcp/eggs#956]
Panel Version: 1.2.2
Daemon Version: 1.2.3
Service: Arma3_x64
Modified: no
Expected Behavior: Egg to be started and server to be connectable

Actual Behavior: Installation will fail after entering steam guard code

Steps to Reproduce:

Install new arma3_x64 server
While it's installing, It'll ask for Steam guard code. Enter it.
After some time, it shows this: Steam Guard code:Warning: failed to init SDL thread priority manager: SDL not found.

**Comment by parkervcp** [comment]
can't be fixed. It takes too long for debian and steam packages to update before it prompts for a steam guard code.

SDL issues happen when the host and image both don't have sdl installed.

**Comment by gOOvER** [comment]
Create a new accoutn for ARMA3 without Steamguard; then it works ;)
