### ISSUE TITLE
Egg Request: Valheim 

### ISSUE THREAD

**Issue by Fieel** [parkervcp/eggs#959]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Valheim dedicated server

Does this expand an already existing service: Y, it's SteamCMD, linux compatible

Link to game: https://store.steampowered.com/app/892970/Valheim/

Links for server downloads:  https://steamdb.info/app/896660/

Links for install steps/docs: https://steamcommunity.com/sharedfiles/filedetails/?id=2382282960 (usual SteamCMD setup really)

**Comment by Butain** [comment]
I would be interested in this one as well, the linux server files are in this depot: https://steamdb.info/depot/896661/
