### ISSUE TITLE
Egg Request : Tachyons

### ISSUE THREAD

**Issue by Alfatossa** [parkervcp/eggs#960]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Tachyons

Does this expand an already existing service: N

Link to game: [https://spektor.itch.io/tachyon](url)

Links for server downloads: [https://github.com/Dav-Edward/TachyonsCE/releases/download/v1.0.1/TachyonsCE.zip](url)

Links for install steps/docs: extract the server folder from the zip

**Comment by parkervcp** [comment]
@Alfatossa can you check that PR?

**Comment by Alfatossa** [comment]
I am not sure what PR means

**Comment by Software-Noob** [comment]
> I am not sure what PR means

It's a pull request to add the egg to this repo. It's linked above and can also be found by clicking [here](https://github.com/parkervcp/eggs/pull/962). Try using the egg and see if it works for you.

**Comment by acl1704** [comment]
I've tested it, works as expected.

**Comment by Alfatossa** [comment]
when i try to import the json from `/ftl/tachyon` i get error 500

**Comment by Software-Noob** [comment]
Importing fails because of file_denylist parameter in the json file. There's a fix for that in the next Pterodactyl release, until then you can manually remove the line from the file.

**Comment by Alfatossa** [comment]
IT WORKS! Thank you so much! I hated the fact I had to turn off windows firewall only to let my friends join me.
