### ISSUE TITLE
Cant import the new magma egg

### ISSUE THREAD

**Issue by Felix5566** [parkervcp/eggs#966]
Cant import the new magma egg. I can still import the egg from 29.09.2020
https://i.imgur.com/TVXepNg.png

Panel Version: 1.2.2
Daemon Version: 1.2.3
Service: minecraft/egg-magma
Modified: no

**Comment by acl1704** [comment]
Not an egg issue. https://github.com/pterodactyl/panel/commit/b00def253746d1c96ba2c4bdc232d436fd7b7fee
