### ISSUE TITLE
New Minecraft Server YatopiaMC

### ISSUE THREAD

**Issue by vos6434** [parkervcp/eggs#967]
Service: Minecraft

Does this expand an already existing service: Yes

Link to game: https://yatopiamc.org

Links for server downloads: https://yatopiamc.org/download.html https://ci.codemc.io/job/YatopiaMC/job/Yatopia/

Links for install steps/docs: https://github.com/YatopiaMC/Yatopia

Yatopia is better than Purpur.

EDIT: Sorry if I've offended anyone by that, I should have done my research.

**Comment by acl1704** [comment]
> Yatopia is better than Purpur.
https://www.youtube.com/watch?v=k7AzkFWQXxE
Yeah, okay

**Comment by RealRONiN** [comment]
> Yatopia is better than Purpur.
Man, I am using latest version of Minecraft and tweaked the render distance in options.txt to 128 render chunks and still can't find who the F asked!

**Comment by DoctaEnkoda** [comment]
Yatopia is a stupid joke

**Comment by HookWoods** [comment]
Imagine reporting a bug from august that has been reverted one day latter 🤔

**Comment by DoctaEnkoda** [comment]
> Imagine reporting a bug from august that has been reverted one day later 🤔

Its an example :)
I can not submit all problem Yatopia has create to 6 month (corrupt chunk, duplication, crash, use 7 submodules without any test ...)

**Comment by vos6434** [comment]
woah please don't hate. I didn't know about its issues, I assumed it was better as it uses parts of purpur and other projects.

**Comment by acl1704** [comment]
> 
> 
> Imagine reporting a bug from august that has been reverted one day later 🤔

Just the fact that made it into master is quite telling.

**Comment by vos6434** [comment]
Should I close this issue?

**Comment by DoctaEnkoda** [comment]
It's just a big Frankenstein without really tested, just copied pasted untested and trying to adjust for it to start, after if there are corruptions, they just delete the file when they want

**Comment by parkervcp** [comment]
I am closing this. Please stop harping on the person for asking.

**Comment by HookWoods** [comment]
> It's just a big Frankenstein without really tested, just copied pasted untested and trying to adjust for it to start, after if there are corruptions, they just delete the file when they want

Hum, could you send **recent** proof of what you're saying? I'm really interested in that since my server is using a fork of Yatopia with 200 players and no problem with that.

**Comment by HookWoods** [comment]
> I am closing this. Please stop harping on the person for asking.

No, I think this should be added since server admin can choose which server they want to use, you don't force them to choose yatopia, some of them are still interested in that so could be a great thing I think even if some people disagree with that :)

**Comment by parkervcp** [comment]
> 
> 
> > I am closing this. Please stop harping on the person for asking.
> 
> No, I think this should be added since server admin can choose which server they want to use, you don't force them to choose yatopia, some of them are still interested in that so could be a great thing I think even if some people disagree with that :)


It's my repo, and I don't want to add it. On top of that if it's just a jar file any current egg that allows people to put in a download link will work fine with this already.

**Comment by vos6434** [comment]
mind sharing it?

**Comment by EsserGaming** [comment]
The project is now archived and is probably not going to be supported.
