### ISSUE TITLE
Valheim Egg Bug panel v1.2.2

### ISSUE THREAD

**Issue by Khan8615** [parkervcp/eggs#977]
Panel Version: (1.2.2)
Daemon Version: ( wings latest ) ( Note: The egg available appears to have been created with Dameon instead of wings )
Service: (Valheim)
Modified: (no) (did you add or change things, this includes startup configs/install scripts/variables)

Expected Behavior:

Actual Behavior:

Steps to Reproduce: (Step by step what to do to cause the issue)

Downloaded All eggs, used Winrar to extract on windows. 
On Server Panel 1.2.2 logged in (Admin) went to Nests > Import Egg > Selected: egg-valheim.json > Selected: Source Engine
Created a new server, it installed and booted (server IP + port 193.70.80.54:2456 (forwarded 2456 + 2457)).
Cannot direct connect and cannot find in the steam server list. Yes, it's marked public.

The egg installation appears to have been made on panel version 1.0 instead of 1.2.2 
Also again the egg references Daemon instead of wings in the egg.json file if that matters..

**Comment by Khan8615** [comment]
https://pastebin.com/SAyafnfx

Console output ^

**Comment by gOOvER** [comment]
Thats a problem with Valheim, not from the egg

**Comment by Khan8615** [comment]
I fixed it, the panel software is trying to run 32-bit steam instead of 64
cuss the panel software by default installs both on 64bit machines.

So stop server delete steamclient.so in the file container and move the one from folder linux64 to  /home/container/
