### ISSUE TITLE
Curseforge Generic Egg not working properly

### ISSUE THREAD

**Issue by person4268** [parkervcp/eggs#978]
Panel Version: 1.0.0 (I should probably update)
Daemon Version: 1.0.0
Service: Minecraft, Curseforge Generic Egg
Modified: no
Expected Behavior:
All the files to actually be in their own folders. 
Actual Behavior:
What seems to be the content of the mods folder is in the root directory and server.jar is not there. 

Steps to Reproduce: 
1. Create a server using the Curseforge Generic Egg using id 285109 (RLCraft)
2. Observe how the server doesn't start and that there are mod jars in the main server directory. 
It looks like the missing server.jar might be from the lack of server.jar in RLCraft's server pack? Do they usually come with one or is that supposed to be handled by the egg?

**Comment by parkervcp** [comment]
I am no longer updating the curseforge egg due to each pack being packed differently and requiring more time to try and make every server work.
