### ISSUE TITLE
ReHLDS Egg Request

### ISSUE THREAD

**Issue by parsman** [parkervcp/eggs#981]
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: (ReHLDS)

Does this expand an already existing service: Y

Link to game: (https://github.com/dreamstalker/rehlds)

Links for server downloads: This needs to be an official link and not one that is hosted on some forum page or a personal github page.

Links for install steps/docs: https://github.com/dreamstalker/rehlds/blob/master/README.md

**Comment by Software-Noob** [comment]
It's a grey area to offer it publically as it's not an official download and instead, a reverse-engineered version of the game. You can use the existing HLDS egg and replace the binary files to accomplish the same task.

**Comment by gOOvER** [comment]
I mean, there was allready such a request and Parker denied it
