### ISSUE TITLE
Request: Game - Post Scriptum - SteamCMD

### ISSUE THREAD

**Issue by Schroedinger00** [parkervcp/eggs#986]
Service: Game, uses SteamCMD, Name: Post Scriptum

Does this expand an already existing service: No

Link to game: [https://store.steampowered.com/app/736220/Post_Scriptum/](url)

Links for server downloads: Over SteamCMD, same as with Squad, just with Post Scriptum Game ID (Dedicated Server ID: 746200)

Links for install steps/docs: Same Install as with any other Dedicated SteamCMD Server (almost identical to Squad Install)
Can also Check here: [https://linuxgsm.com/lgsm/pstbsserver/](url)
or here (unfortunately only german): [https://hoerli.net/post-scriptum-dedicated-server-windows-linux/](url)

Since its based on Squad and Serverside (with its config and such) is almost same, it should be possible to easily modify the Egg from Squad for Post Scriptum as well.

I will gladly help with any testing!

Thank you in Advance, I really appreciate your work!

**Comment by Software-Noob** [comment]
I just made an egg for this and will release it tomorrow

**Comment by Schroedinger00** [comment]
awesome! thank you for your work, I really appreciate it!
