### ISSUE TITLE
Minecraft Fabric Server crashes after startup

### ISSUE THREAD

**Issue by VirtualHorror** [parkervcp/eggs#988]
Panel Version: 1.2.2
Daemon Version: 1.2.3
Service: Minecraft 
Modified: no

Expected Behavior:
The Minecraft Fabric Server should install required software and startup the Minecraft server as usual without crashing.

Actual Behavior:
The Minecraft Fabric Server is starting pulling docker image, running with the startup jar command, printing the error `Error: Unable to access jar file fabric-server-launch.jar` and crashing

Steps to Reproduce:
1) Download the Minecraft - Fabric egg from https://raw.githubusercontent.com/parkervcp/eggs/master/minecraft/java/fabric/egg-fabric.json
2) Import the egg onto the Minecraft Nest.
3) Create a server with sufficient resources (I was using 2 GB RAM with 512 MB SWAP, 1 GB Storage, 3 Cores) and choose the Minecraft Nest with Fabric as the egg
4) Start the server.
5) The server would crash with the following logs in the console: 

`[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:4d063baaa8a2ec8a1d0e4fd420b93a30e26b453081d7be0c000794809c5db5ca 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_openjdk-11 
[Pterodactyl Daemon]: Finished pulling Docker container image
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode)
:/home/container$ java -Xms128M -Xmx2048M -jar fabric-server-launch.jar
Error: Unable to access jarfile fabric-server-launch.jar
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.`

Additional Notes:
1) I had enabled CPU Pinning initially and had set configuration to `0-3` but later I thought this could be causing the server to crash, so I removed this configuration and tried, but it still crashed.
2) This server is not running on the default port (25565) but I had ensured that in the server.properties file had the custom port I was using. But since I thought this also could have been causing issues I tried to use the server on default port too, but again it crashed.
3) For some reason the startup jar file is set to `fabric-server-launch.jar` by default in the startup parameters but when the server is installed the startup file name is `fabric-installer-0.6.1.51.jar`, so I did try modifying this too to try and see if it would work, but again crashed.

Mentions:
@TekExplorer

**Comment by TekExplorer** [comment]
ah, i see what happened. not sure how I missed that.

**Comment by TekExplorer** [comment]
until its merged, feel free to [take it from my repo](https://raw.githubusercontent.com/TekExplorer/eggs/fix-fabric/minecraft/java/fabric/egg-fabric.json)

**Comment by Software-Noob** [comment]
> until its merged, feel free to [take it from my repo](https://raw.githubusercontent.com/TekExplorer/eggs/fix-fabric/minecraft/java/fabric/egg-fabric.json)

I gave him a fixed version in the Discord earlier prior to your PR
