### ISSUE TITLE
Valheim Egg missing things

### ISSUE THREAD

**Issue by XiNaru** [parkervcp/eggs#993]
hey, it's nice that egg exists. But 2 things are missing from the variables.

one thing is the list of admins (config / unity3d / IronGate / Valheim / adminlist.txt)

And the whitelist (config / unity3d / IronGate / Valheim / permittedlist.txt)

Would be nice if both could still be inserted :)

**Comment by gOOvER** [comment]
You can add this on your own. it's norhing for Variables and as i know not possible, because you need to add one SteamID per Line

**Comment by ryrzy** [comment]
hi, i saw that umod (oxide) is available for Valheim ;) maybe you can add this to egg ;)

https://umod.org/games/valheim

**Comment by gOOvER** [comment]
> hi, i saw that umod (oxide) is available for Valheim ;) maybe you can add this to egg ;)
> 
> https://umod.org/games/valheim

Open your own Ticket

**Comment by parkervcp** [comment]
The way the files are laid out it's not possible to do this.
