### ISSUE TITLE
Request: Webhosting 

### ISSUE THREAD

**Issue by wolfier74** [parkervcp/eggs#994]
Can you please create egg for webhosting? (html, php)

**Comment by parkervcp** [comment]
Pterodactyl wasn't built for hosting websites.

**Comment by wolfier74** [comment]
So what panel can I use for webhosting?

**Comment by grimesy88** [comment]
cPanel & WHM or Plesk to name two. There are so many out there.

**Comment by CODER-nodejs** [comment]
You can create your on https://pterodactyl.io/community/config/eggs/creating_a_custom_egg.html

**Comment by wolfier74** [comment]
@CODER-nodejs But I dont know how

**Comment by CODER-nodejs** [comment]
> @CODER-nodejs But I dont know how

There are some hosts who did it like .gg/dbh
