### ISSUE TITLE
[Arma 3] Error 500

### ISSUE THREAD

**Issue by NotDonaldTrump** [parkervcp/eggs#995]
Panel Version: **1.1.1**
Daemon Version: **1.2.3**
Service: **Arma 3**
Modified: (yes/**no**) 

Expected Behavior:
**Importing egg**

Actual Behavior:
**When importing the Arma 3 egg it proceeds to a webpage with the following: "500 | Server Error". This does not occur with other eggs, just the Arma 3 one.**

Steps to Reproduce:

- Save egg json
- Import egg
- Broken

**Comment by FoksVHox** [comment]
Upgrade to the latest version of the panel, and this isn't a egg problem.
