### ISSUE TITLE
Ark EGG Modding?

### ISSUE THREAD

**Issue by XiNaru** [parkervcp/eggs#996]
A question.
Ark mods are not possible for the variables.

How can I insert mods there? Without mods ark lw :) and a server is only partially decent playable

**Comment by XiNaru** [comment]
and a other problem.

waiting for rcon connection...
dial tcp 127.0.0.1:27020: connect: connection refused

it doesn't matter whether I turn rcon on or off. that always comes, the server does not start.

**Comment by gOOvER** [comment]
USe the Discord for Support

**Comment by parkervcp** [comment]
> 
> 
> A question.
> Ark mods are not possible for the variables.
> 
> How can I insert mods there? Without mods ark lw :) and a server is only partially decent playable

I am not particularly iterrested in supporting modded ARK. Also the way their mods are handled won't work with the way variables are handled in ptero.

> 
> 
> and a other problem.
> 
> waiting for rcon connection...
> dial tcp 127.0.0.1:27020: connect: connection refused
> 
> it doesn't matter whether I turn rcon on or off. that always comes, the server does not start.

This is not an actual issue. Leave rcon enabled if you want your server to stop properly.
