### ISSUE TITLE
Request: Ghidra Server

### ISSUE THREAD

**Issue by martmists-gh** [parkervcp/eggs#997]
Service: Ghidra Server

Does this expand an already existing service: N

Link to game: https://ghidra-sre.org/

Links for server downloads: https://ghidra-sre.org/

Links for install steps/docs: 
    - "For detailed information on installing/configuring the Ghidra Server see the &lt;GhidraInstallDir&gt;/server/svrREADME.html file." -  https://ghidra-sre.org/InstallationGuide.html#RunServer
    - Community docker image: https://github.com/bytehow/docker-ghidra-server

**Comment by parkervcp** [comment]
I am not going to do this.
